### ISSUE TITLE
How to disable sorting and editable feature from the excel sheet 

### ISSUE THREAD

**Issue by gulshan-escalon** [jspreadsheet/ce#10]
How to disable sorting and editable feature from the excel sheet ?

**Comment by gulshan-escalon** [comment]
Hi Paul,

Please reply my above query ?

**Comment by gulshan-escalon** [comment]
Hi Paul, 

Please reply

**Comment by gulshan-escalon** [comment]
??

**Comment by pphod** [comment]
You can use the directive:

columnSorting: false
