### ISSUE TITLE
How do i freeze row-number column

### ISSUE THREAD

**Issue by sivakumarnalle** [jspreadsheet/ce#1002]
Hi Paul,
I have checked the example in below link and able to freeze the first two columns.
https://jexcel.net/v4/examples/freeze-columns

But is there a way to freeze the row-number column as well?

Thanks

**Comment by pphod** [comment]
Sorry, this is won't be possible nativelly. But you can try to position: sticky on the rows you need using pure CSS.

**Comment by jlzhou** [comment]
@paulhodel Thanks, can you give some sample code for more detail?
