### ISSUE TITLE
Get and set row headers

### ISSUE THREAD

**Issue by paultpearson** [jspreadsheet/ce#1005]
Would it be possible to get and set the row headers (labels)? The default labels enumerate the rows 1, 2, 3,... in the leftmost column, and it would be nice to be able to change those labels using get and set methods.

**Comment by kgdunn** [comment]
Or hide them entirely would also be an option. I can't seem to find anything in the documentation at the moment if that is possible.

Updated: _Ignore my comment please_, I found the `table.hideIndex()` function.

**Comment by pphod** [comment]
This would do the trick in renaming the indexes.
```
for (var j = 0; j < table.rows.length; j++) {
    table.rows[j].innerText = 'Any text';
}
```
