### ISSUE TITLE
Give all as an pagination options to show all the records present in an table

### ISSUE THREAD

**Issue by dollychhabriya** [jspreadsheet/ce#1006]
Give "all" as an pagination options to show all the records present in an table.

**Comment by pphod** [comment]
You can do something like that:
document.getElementById('spreadsheet').jexcel.options.pagination = false;
document.getElementById('spreadsheet').jexcel.refresh()

Or add some options to the paginationOptions => Really big number.

**Comment by dollychhabriya** [comment]
Thank you for the help.
