### ISSUE TITLE
Cross reference sheets

### ISSUE THREAD

**Issue by jimmywarting** [jspreadsheet/ce#1011]
say i have two data sheets `countries` & `cities`

how can i from countries import a value (A1) from cities?

if it where Google spreadsheet you would have done something like:
`=Sheet1!A1 or ='Sheet number two'!B4.`
https://support.google.com/docs/answer/75943?co=GENIE.Platform%3DDesktop&hl=en

trying to do similar.

**Comment by pphod** [comment]
Unfortunatelly none of the versions implements that at this point.

**Comment by jimmywarting** [comment]
Oh, okey. Thanks for a quick response.
Maybe make this a feature request then.

**Comment by pphod** [comment]
Yes, I flagged that. Thanks for the suggestion.

**Comment by pphod** [comment]
That has been included in the Pro Distribution (v7) which will be available on 9th August 10pm UK time.
https://jexcel.net

If you wish more information, you send me an email and I am happy to reply: paul@jexcel.net

I don't see that on the CE distributions in a near future, so I am going to close that.
