### ISSUE TITLE
missing CSS style for column type `html`

### ISSUE THREAD

**Issue by VioletKnight7** [jspreadsheet/ce#1013]
The column type `html` requires the following CSS files to work properly:

```
<link rel="stylesheet" href="https://bossanova.uk/templates/jexcel-v4/css/fonts.css" type="text/css">
<link rel="stylesheet" href="https://bossanova.uk/templates/jexcel-v4/css/common.css" type="text/css">
<link rel="stylesheet" href="https://bossanova.uk/templates/jexcel-v4/css/style.css" type="text/css">
```

Can we bundle these CSS files in the distribution?

**Comment by pphod** [comment]
Those CSS are specific for the website, and does not related to Jexcel. You won't need that.

**Comment by VioletKnight7** [comment]
Thanks for your reply, Paul. 
I have reproduced the issue here: [https://jsfiddle.net/km43wr7e/2/](https://jsfiddle.net/km43wr7e/2/)
Can you have a second look?

Click the first cell to see the issue.
If you uncomment those 3 required CSS files, it works!

**Comment by pphod** [comment]
You just missed the material icons from Google. I have changed your jsfiddle.
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto|Material+Icons|Oswald" />

https://jsfiddle.net/paulhodel/o0venzus/1/

**Comment by pphod** [comment]
I would like to invite you to test Jexcel Pro. When you have some time:
https://jexcel.net/v5

**Comment by VioletKnight7** [comment]
Thanks @paulhodel. I will
