### ISSUE TITLE
Non working example in Readme.md 

### ISSUE THREAD

**Issue by sallecta** [jspreadsheet/ce#1015]
**Firefox web console output**
```console
JEXCEL: el is not a valid DOM element jexcel.js:32:21
```

**Comment by sallecta** [comment]
Replace, please 
`
jexcel(document.getElementById('spreadsheet'), {
`
with
`
jexcel(document.getElementById('mytable'), {
`

**Comment by pphod** [comment]
It has been done, thanks.
