### ISSUE TITLE
Nested Headers

### ISSUE THREAD

**Issue by fengyi9958** [jspreadsheet/ce#1017]
Hello, I have some questions for you. When I used nested table headers, I only knew about merging columns from the documentation, but now I want to merge rows. What should I do? 
thank you.
![image](https://user-images.githubusercontent.com/42599684/84587574-e4f47a00-ae52-11ea-9f06-07d519287980.png)

**Comment by pphod** [comment]
There is no rowspan for headers natively. But, you might be able to do that using pure JS to alter the table.
