### ISSUE TITLE
Dependable Dropdownlist with Ajax call

### ISSUE THREAD

**Issue by iamneaz** [jspreadsheet/ce#1018]
I am trying to load the second dropdown by ajax call from the dropdownFilter based on the first dropdown.
This is my table
`var table = jexcel(document.getElementById('spreadsheet2'), {`
       ` minDimensions: [10, 5],`
        `tableOverflow:true,`
       ` lazyLoading:true,`
        `loadingSpin:true,`
        `columns: [`
            `{type: 'text', title: 'Invoice ID', width: 120},
            {type: 'text', title: 'Recipient Name', width: 150},
            {type: 'text', title: 'Recipient Phone No', width: 150},
            {type: 'dropdown', title: 'District', width: '200', source: districts},
            {type: 'dropdown', title: 'Zone', width: '120',source: zones,filter:dropdownFilter},
            {type: 'checkbox', title: 'Buy', width: '100'},
        ]
});`
The dropdown filter
`    dropdownFilter = function(instance, cell, c, r, source) {
        var value = instance.jexcel.getValueFromCoords(c - 1, r);
        var fetched_zones=fetchZone(value);
        return fetched_zones  
    }`
The ajax call
`    function fetchZone(district_id) {
        $.ajax({
            type: 'POST',
            url: 'ajaxData_for_user.php',
            data: 'district_id_import_excel=' + district_id,
            success: function (html) {
                 return JSON.parse(html);
            }
        });
    }`

The problem with the second dropdown list is the ajax call takes time and the dropdown filter does not wait so the fetched_zones variable remains undefined. I've tried to use sleep in the filter but that does not work.
The sleep function :
`function sleep(milliseconds) {
        const date = Date.now();
        let currentDate = null;
        do {
            currentDate = Date.now();
        } while (currentDate - date < milliseconds);
    }`
I've also tried to use $.when but it doesn't work too. 
It would be awesome if you could suggest me any solution , Paul !

**Comment by pphod** [comment]
That won't be possible.
Suggestion is to load the source of the dropdown before everything, them you can return in the method Filter the options from the local without the ajax.

**Comment by iamneaz** [comment]
Sad to hear that :( . Thanks for the reply @paulhodel !

**Comment by pphod** [comment]
If you can go for a custom editor, which update the editor with new options on the callback of a possible call. Good luck with your implementation.
