### ISSUE TITLE
Not able to avoid formula

### ISSUE THREAD

**Issue by tbnovaes** [jspreadsheet/ce#102]
I don't want to allow people to type formulas on the cell. It has to be numbers only. However if the person type =, formula is invoked automatically and there is no way I could find to avoid it. 

Also the formula function has 2 console.log() logging the values of each cell

**Comment by pphod** [comment]
Yes, if = is typed they are trying to invoke that. But you could try to remove than with the updateSettings that happens every time a column is changed.

https://bossanova.uk/jexcel/examples/currency-and-masking-numbers

About the console.log this was updated in the master repository and you can get the new version without it.

**Comment by tbnovaes** [comment]
yes I can use the updateSettings, however it is called after the cell has invoked the formula, so I will have the value changed to the one I want, but I'll have and error on my console too.

I think best place to handle this type of validation would be on onbeforechange(), so I could take care of making any value validation and replacement before it take place.

However, even tho I could validate it on onbeforechange(), I have not found a way to replace the value on the cell. My idea is, if the value is valid, keep the value, if not valid then replace the new value with the old value.
