### ISSUE TITLE
Removing sort/filter

### ISSUE THREAD

**Issue by jamesargent-contexcity** [jspreadsheet/ce#1022]
Is it possible to remove filters/sort programatically after they have been added to a jexcel table?

For example something like $('#myTable').jexcel('removeSort');
For example something like $('#myTable').jexcel('removeFilter');

On a large table with a lot of filters applied it would be ideal to have a quick way of removing them. Is this possible?

**Comment by deftdawg** [comment]
You know you can look inside jexcel.js to see how filters are implemented?

A quick grep shows resetFilters() which seems like it might do the filters...

**Comment by pphod** [comment]
resetFilters() will do the trick.
