### ISSUE TITLE
Use jExcel as a Gutenberg block in WordPress?

### ISSUE THREAD

**Issue by rosshamilton29** [jspreadsheet/ce#1023]
I'm wondering if you have tried embedding jExcel in to WordPress as a Gutenberg block?  It would be really handy for a job we're working on.  I've spent a couple of days reading up on things but the Gutenberg documentation and community articles are all over the place (shifting sands, it's hard to know when you're reading current advice or things that have been outdated), plus I'm new to React.  I've used wp scaffold to run up a bare block and I can get the JS library dependencies on page but I'm struggling to get the block to instantiate a jexcel object and populate it with data specific to that block.  Any tips would be greatly appreciated!

**Comment by pphod** [comment]
Sorry, I am afraid I can't help you on that.
