### ISSUE TITLE
upgrade problem due to issue Dropdown tableOverflow #764 and now selected item does not show up in cell

### ISSUE THREAD

**Issue by HOA-MAROON** [jspreadsheet/ce#1024]
I had the same issue as "Dropdown menu position when used with tableOverflow #764". I downloaded and added the latest version of jsuites. The issues with  the dropdown position is fixed but now when a selection ismade it is not put into the cell. Any ideas why?

I tried upgrading the jexcel version afterwards to see if that had an issue and the jexcel spreadsheet shrunk down to just below the header and the header did not respect the <br> tags any more.

So I put it back to the older version of jexcel for now

**Comment by pphod** [comment]
Which version are you trying? 4.2?

**Comment by HOA-MAROON** [comment]
I just downloaded jsuites today Looks like the latest version is v3. This is in the file
 * (c) jSuites Javascript Web Components (v3)

jexcel version

 * (c) jExcel v3.4.5

**Comment by pphod** [comment]
I am going to take a closer look soon. I have a new version to release soon.

**Comment by pphod** [comment]
I have updated the master repository with v4.2.3+ which implements the correct way to handle with jsuites dropdown v3.
