### ISSUE TITLE
Getting reference loop detected error

### ISSUE THREAD

**Issue by dollychhabriya** [jspreadsheet/ce#1027]
I am getting Reference loop detected while implementing below formulae in jexcel can you help to solve the issue. Below is the data that I am trying to set in Jexcel table

data[0] = " "// A
                                                data[1] = " "  //B
                                                data[2] = " "; //C
                                                data[3] = " " ; // D
                                                data[4] = " " ; //E
                                                data[5] = " ";//F
                                                data[6] = " ";//G
                                                data[7] = " ";//H
                                                data[8] = " " ;//I
                                                data[9] = " "; //J
                                                data[10] = 5000; //K
                                                data[11] = 200; //L
                                                data[12] = 50;//M
                                                data[13] = 100;//N
                                                data[14] = `=ROUND(IF(M${i + 1}!=0,IF(K${i + 1}>L${i + 1},K${i + 1}/M${i + 1},L${i + 1}/M${i + 1}),0),2)`;//O
                                                data[15] = `=ROUND(IF(N${i + 1}!=0,IF(K${i + 1}>L${i + 1},K${i + 1}/N${i + 1},L${i + 1}/N${i + 1}),0),2)`;//P
                                                data[16] = ""; // Order based on Q
                                                data[17] = ""; // Rounding option R
                                                data[18] = ""; // User Qty S
                                                data[19] = `=IF(Q${i + 1}==3,

                                                                IF(R${i + 1}==1,
                                                                        CEILING(L${i + 1},1),
                                                                        FLOOR(L${i + 1},1)
                                                                )
                                                        ,
                                                        IF(Q${i + 1}==4,
                                                                IF(NOT(ISBLANK(S${i + 1})),
                                                                        IF(R${i + 1}==1,
                                                                                CEILING(S${i + 1}/M${i + 1},1)*M${i + 1},
                                                                                FLOOR(S${i + 1}/M${i + 1},1)*M${i + 1}
                                                                        ),
                                                                        IF(R${i + 1}==1,
                                                                                CEILING(O${i + 1},1)*M${i + 1},
                                                                                FLOOR(O${i + 1},1)*M${i + 1}
                                                                        )
                                                                ),
                                                                IF(Q${i + 1}==1,
                                                                        IF(NOT(ISBLANK(S${i + 1})),
                                                                                IF(R${i + 1}==1,
                                                                                CEILING(S${i + 1}/N${i + 1},1)*N${i + 1},
                                                                                FLOOR(S${i + 1}/N${i + 1},1)*N${i + 1}
                                                                        ),
                                                                                IF(R${i + 1}==1,
                                                                                        CEILING(P${i + 1},1)*N${i + 1},
                                                                                        FLOOR(P${i + 1},1)*N${i + 1}
                                                                                )
                                                                        ),
                                                                        IF(NOT(ISBLANK(S${i + 1})),
                                                                                IF(R${i + 1}==1,
                                                                                        CEILING(S${i + 1},1),
                                                                                        FLOOR(S${i + 1},1)
                                                                                ),
                                                                                IF(R${i + 1}==1,
                                                                                        CEILING(K${i + 1},1),
                                                                                        FLOOR(K${i + 1},1)
                                                                                )
                                                                        )
                                                                )
                                                        )
                                                 )`;  // T

**Comment by pphod** [comment]
This is typically:
B1 = C1 and C1 = D1 and D1 = B1, generating an infinity loop. Make you not generating circular loop.

**Comment by dollychhabriya** [comment]
Thank you for the help.
