### ISSUE TITLE
JSON bring all the columns in the table

### ISSUE THREAD

**Issue by muhdkhokhar** [jspreadsheet/ce#1032]
ngAfterViewInit() {
    jexcel(this.spreadsheet.nativeElement, {
      url: 'http://localhost:8888/json',
      tableOverflow: true,
  

      autoIncrement: false,
      colHeaders: ['Product Title'],
      colWidths: [300, 100, 100, 100],
      columns: [
        {type: 'text', field: 'productTitle'}],

      onchange: function (instance, cell, x, y, value) {

        console.log(this.data[y]);

      },
      minDimensions: [10, 10],

      onbeforepaste: function (data) {

        console.log(data);
      }

    });
  }

My JSON has over 100 columns obvsiouly I dont' want to show all them.
I want to show the ones im interested in 

how do I do?

**Comment by pphod** [comment]
You have three options:
1) Do not bring all columns;
2) Bring all columns, but filter before send to jexcel;
3) Set all non-desireble to be NULL.

I would suggest to bring only what is necessary. You will save lot of memory and make the performance of the table better. Consequently a better user experience.
