### ISSUE TITLE
v3: two tables on page with ajax used

### ISSUE THREAD

**Issue by sasha-x** [jspreadsheet/ce#1033]
How to reproduce:
Code:

```js
let options1 = {
url: "/some/data/url",
...
};
$(selector1).jexcel(options1);

let options2 = {
url: "/some/data/url2",
columns: [{
type :  'autocomplete',
url : '/some/dictionary/url',
},
...],
...
};
$(selector2).jexcel(options2);
```

Then, sometimes one of two tables is empty (no any data loaded to table html). 
Browser console has no errors. 

It looks jsuites ajax method uses global counter to exec `complete()` handler. And sometimes processing of two tables in parallel is interfered each other.

How to bypass:

```js

```js
let options1 = {
...
loaded: function () {
$(selector2).jexcel(options2);
}
};
$(selector1).jexcel(options1);
```

Not sure about v4.
Good solution looks like bind individual jsuites object to each jexcel table entity.

**Comment by pphod** [comment]
Yes, this is broken no one has never picked it up, thanks for letting us know. It has been fixed, but you should update both versions. Jexcel 4.3 jsuites 3.3. Both version are on the NPM and the respective master repos.

**Comment by sasha-x** [comment]
ok, thanks.
