### ISSUE TITLE
Filtering of empty values

### ISSUE THREAD

**Issue by deftdawg** [jspreadsheet/ce#1037]
In some scenarios, it may make sense to allow filtering for empty values.

For example I have a use case where users must check a `checkbox` column, there is no easy way to filter out all of the rows that have already been checked.

**Comment by pphod** [comment]
Done, available in the master repo.

**Comment by deftdawg** [comment]
Thanks for the quick fix.  I found in testing that the filter didn't work; eventually tracked it down to the search function of closeFilter that wasn't handling the case of blank query values correctly, the attached PR #1040 addresses that.

**Comment by deftdawg** [comment]
Seems some additional logic will be needed to handle checkboxes (which are converted to strings and compared during the search function, i.e. blank = 'false', checked = 'true')

**Comment by deftdawg** [comment]
Took me a while to figure it out but I eventually got it.   Please merge the PR when you get a chance. 😄
