### ISSUE TITLE
Cell's style not copied when copy-paste

### ISSUE THREAD

**Issue by mikolaikrol** [jspreadsheet/ce#1038]
the style of a cell (text style, background color, etc.) is not copied when copy-pasting cell(s)

**Comment by pphod** [comment]
I have tested and it seems to be working fine. If you wish to create a jsfiddle I am happy to take a look.
https://bossanova.uk/jexcel/v4/examples/spreadsheet-toolbars

**Comment by mikolaikrol** [comment]
Yes actually it's working when you copy/paste one cell, but if you select more than one cell, their style is not pasted
https://jsfiddle.net/gpz5n4hb/
