### ISSUE TITLE
V4 : change unique cell's type

### ISSUE THREAD

**Issue by mikolaikrol** [jspreadsheet/ce#1039]
Hello,
here is my editor i'm working on : https://softinst130972.host.vifib.net/erp5/web_site_module/officejs_jexcel_editor/app/
please choose "Local is enough" and add a new sheet.
In the toolbar I have many buttons that change the type of an entire column, by changing instance.options.columns[index].type
Is it possible to change the type of a unique cell, for example in one column have an image, a checkbox and a calendar ?

(By the way, when i change the column type to "color", open the color picker editor and choose a color, the hexadecimal code of the color is displayed in the cell instead of the div with the choosen background-color expected, idk why)

**Comment by pphod** [comment]
The type property works on the column level only. For the color picker there is an option "render:'square'" to render in div.

If you wish to render different types, you should implement a customEditor that renders the editor based on your x, y.

Second example on this page:
https://bossanova.uk/jexcel/v4/examples/column-types
