### ISSUE TITLE
Set header styles dynamically.

### ISSUE THREAD

**Issue by yash17a** [jspreadsheet/ce#1042]
To enable a user customise header for jexcel table.

**Use case** -> Based on diff types of data want to color whole column along with header which is not possible at present. Tried with innerHtml but didn't work.

`Style` in jexcel () is only for cells other than header.

**Comment by pphod** [comment]
You can use the themes
https://bossanova.uk/jexcel/v4/cases/themes

Or you can use external CSS to change the colours.

Or programatically:
document.getElementById('spreadsheet').jexcel.headers[0].style.backgroundColor = 'red';
