### ISSUE TITLE
[question] its there any "arrayformula" like to set default value column?

### ISSUE THREAD

**Issue by joneldiablo** [jspreadsheet/ce#1044]
Its there any equivalent of arrayFormula from google sheets? 
I want put a row with formulas or fixed values on every cell of row to use it as default value of the every column
 | name | value | discount |             final price                 |
 |  ___   |__ 0__|__ .5 ___ | =ArrayFormula(B1:B*C1:C) |
----------------------------------------------------------------------------
 | __________________________________________  |

**Comment by pphod** [comment]
Not available in none of the distributions yet. It should be available next month starting on the Pro distribution.

**Comment by crazyrohila** [comment]
Hi @pphod  ArrayFormula still throws an error in pro distribution, Is there a way to parse the `ArrayFormula` or tweaks formula in diff way to get working in here?

**Comment by hodeware** [comment]
It works like excel:
=A1:A10*10 for example:
https://jspreadsheet.com/products/formulas
