### ISSUE TITLE
[Question] Select with image

### ISSUE THREAD

**Issue by Wellers0n** [jspreadsheet/ce#1046]
Hi everyone, can we to do select with images ? 

E.G: 
![image](https://user-images.githubusercontent.com/39449389/86243715-3acc6000-bb7d-11ea-9d2c-8e15e5d3b378.png)

**Comment by pphod** [comment]
Yes you can, it is the last example on this page:
https://bossanova.uk/jexcel/v4/examples/dropdown-and-autocomplete

**Comment by Wellers0n** [comment]
Oh ok, but I need show images inside and outside of selector
