### ISSUE TITLE
How to overwrite the style of Frontend Framework of the website?

### ISSUE THREAD

**Issue by taurenshaman** [jspreadsheet/ce#1048]
Hello, I'm using [Metro](https://github.com/olton/Metro-UI-CSS), and copied the whole css content from https://bossanova.uk/jexcel/v4/jexcel.css, but it didn't work :(
https://codepen.io/taurenshaman/pen/GRorWrj

![image](https://user-images.githubusercontent.com/1308706/86353426-c509e680-bc99-11ea-85e8-973724015195.png)

Thank you very much!

**Comment by pphod** [comment]
Don't forget to add google material fonts.
