### ISSUE TITLE
How to create multiple tabs with multiple HTML tables ?

### ISSUE THREAD

**Issue by mikolaikrol** [jspreadsheet/ce#1050]
Hello,
it's possible to create a sheet from an HTML table like this : jexcel(document.getElementById("myTable"))
Is it possible to create multiple tabs (like with jexcel.tabs method) with multiple HTML tabs ?

**Comment by pphod** [comment]
You need to first parse all tables them apply than to jexcel.

// Container
var options = [];
// Get all tables in your page
var tables = document.querySelectorAll('table');
// for each table you parse and get the configuration
options.push(jexcel.createFromTable(table[i]);
// Create jexcel instance with the worksheets
jexcel.tabs(options);
