### ISSUE TITLE
Incompatiblity with React Router

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#1051]
Greetings. Thanks for creating this product. I'm currently using v4.
Problem is, if I use the React implementation version together with React Router, for some reason the spreadsheet will only inject the first row (the numbered one) while ignoring all other code.
Please can you take a look on that? Thank you.

**Comment by pphod** [comment]
Can you create a sample of your code on codesandbox?

**Comment by pphod** [comment]
Due the inactivity of that I will close the issue.
