### ISSUE TITLE
Example backend/database setup for handling data persistence

### ISSUE THREAD

**Issue by rainwater11** [jspreadsheet/ce#1052]
Is there a sample script for saving data and changes to rows and columns and cells into a database? 

I don’t really care if it’s python or PHP or whatever. I am just struggling to figure out a decent way to do so. 

I’ve got my schema made up of Row, Column, and Cell, Style, etc. Just wondering if this is a decent way of handling it or if there is a better or more preferred way.

**Comment by pphod** [comment]
var completeTable = yourtable.getConfig();
completeTable = JSON.Stringify(completeTable);
// Send that to the server completeTable -> Bear in mind events should be handle in a different way.

**Comment by pphod** [comment]
In the Pro distribution the persistance handles additional information, such as changing column, etc.
https://jexcel.net/v5/examples/data-persistence
