### ISSUE TITLE
Feature request: add option to index rows from zero.

### ISSUE THREAD

**Issue by scynthero** [jspreadsheet/ce#1055]
As in title, please add option to index rows from zero.

**Comment by javiercani** [comment]
could it be starting at -1? When i configure the event onInsertRow, the rowNumber parameter doesn't match with starting in 0 or 1.

**Comment by pphod** [comment]
If you wish to customize the labels of the rows, you can write a method to do that. That can be included on the onload event.
for (var j = 0; j < table.rows.length; j++) {
    tables.rows[j].innerText = j;
}

**Comment by pphod** [comment]
In regards to the insertRow event:
To consider the right row you should look at rowNumber and insertBefore variables.
