### ISSUE TITLE
 trouble to use mask at a text column

### ISSUE THREAD

**Issue by ladyllg** [jspreadsheet/ce#1056]
I'm currently using version 2 trying migrate to version 4, but I'm having trouble to use mask at a text column. My issue is how make this ( https://jsfiddle.net/lauralimadev/gqw7soc6/ ) in version 4. I want to keep the numbers always with two decimal places, only.

**Comment by pphod** [comment]
A working example:
https://jsfiddle.net/paulhodel/o4ndp8k7/

Documentation:
https://bossanova.uk/jsuites
