### ISSUE TITLE
Header for Index Column

### ISSUE THREAD

**Issue by kAvItHa-cL** [jspreadsheet/ce#1060]
Hi  Is it possible to set Header for Row Index Column

**Comment by pphod** [comment]
If I understood correctly, you can change the text of the index programmatically.

for (var i = 0; i < table.rows.length; i++) { tables.rows[i].innerText  = 'Your text'; }

**Comment by kAvItHa-cL** [comment]
Hi, I need to set the Column Name for Index Column, Not to change the Index text , like setting SL.No Header for Index Column
For Ex: we are setting column Title for all columns other than this index column like :
{ type: 'text', title: 'Name' } - like this can we set title for Index Column

I tried something like this:
 this.table.thead.firstElementChild.firstElementChild.innerText = 'slno';

It working but i don't think it is the proper solution
