### ISSUE TITLE
Get Dropdown source of a cell

### ISSUE THREAD

**Issue by rvndorado** [jspreadsheet/ce#1062]
Is there a way to get the dropdown source of a cell?

**Comment by pphod** [comment]
Do you mean from a column?

Regards,

**Comment by rvndorado** [comment]
A specific cell with dependency,  when a user paste a value on a dependency cell there is no source parameter on the on change function

**Comment by pphod** [comment]
You should use onchange to include the new option in the source of the dropdown.
