### ISSUE TITLE
Drag&Drop and Resizing icons emergence is not pixel perfect

### ISSUE THREAD

**Issue by bocasaythebert** [jspreadsheet/ce#1064]
Hi !

I got some trouble with the Drag&Drop and Resizing features.
The hover effect on the icon mouse for drag&drop and resizing features appear too soon. It is not pixel perfect.

Step to reproduce : 
- Go to the official website : https://bossanova.uk/jexcel/v4/examples/column-dragging
- Try to drag&drop a column, move the mouse from top to bottom of the cell. Exactly when the drag&drop icon appear, try to drag&drop, as a result you will produce the "selection" feature instead of the "drag&drop feature".
- Retry it, move the mouse from top to bottom of the cell. Exactly when the drag&drop icon appear, move futher 1 pixel down and try to drag&drop, as a result, the drag&drop feature is correctly called.
- Same problem with resizing column feature
- Same problem with drag&drop and resizing line feature

Thanks and have a nice day !
Best regards,

**Comment by pphod** [comment]
It seems 1px deslocated. I will fix that in the next release. Thanks

**Comment by pphod** [comment]
that has been fixed on Pro distribution and should be included on CE in from v5.
https://jexcel.net
