### ISSUE TITLE
Custom Editor won't set value if we move out of table

### ISSUE THREAD

**Issue by kAvItHa-cL** [jspreadsheet/ce#1065]
Hi , when working custom Editor - if we open editor and select value and move to next cell by mouseclick, It will set value to cell but instead of moving to any other cell , if we come out of table, the value will not be to set to selected cell. Can we fix it programmatically . Also custom Editor wont set value on Tab/Enter - no action will happen on Tab/Enter Key press

**Comment by pphod** [comment]
If you are leaving the editor you must make sure are closing the editor.
