### ISSUE TITLE
Issues on Copy and paste 

### ISSUE THREAD

**Issue by aleza0717** [jspreadsheet/ce#1066]
![CopyAndPaste](https://user-images.githubusercontent.com/21351302/87621018-7e64c380-c752-11ea-85a1-47622c475e40.png)
Can't paste the copied value from same column but different row using customize type - open editor. Please help

**Comment by aleza0717** [comment]
![CopyAndPaste](https://user-images.githubusercontent.com/21351302/87621002-7442c500-c752-11ea-9b3b-e75df46e3dfa.png)

**Comment by pphod** [comment]
Sorry, I am afraid there is not enough information for me to help you. Would you like to create a jsfiddle and give more details how I can replicate your issue?

**Comment by aleza0717** [comment]
> Sorry, I am afraid there is not enough information for me to help you. Would you like to create a jsfiddle and give more details how I can replicate your issue?

All I did is to try to copy the value of row "2" Column "Time" (16:30) and pasted it in Row "1" Column "Time" but it didnt paste.
I used your example in your website at https://bossanova.uk/jexcel/v4/examples/column-types

**2 CUSTOM COLUMN TYPE**

**Comment by aleza0717** [comment]
All I did is to try to copy the value of row "2" Column "Time" (16:30) and
pasted it in Row "1" Column "Time" but it didnt paste.
I used your example in your website at
https://bossanova.uk/jexcel/v4/examples/column-types

2 CUSTOM COLUMN TYPE

**Comment by sftl** [comment]
This works for me.

var customColumn = {
    closeEditor: ...,
   ....
    updateCell: function (cell, value) {
            cell.innerHTML = value;
            return value;
   }
}
