### ISSUE TITLE
how to refresh table dropdown item after loading the table data.

### ISSUE THREAD

**Issue by kallaguntaashok** [jspreadsheet/ce#1069]
I would like to add new items in the dropdown after loading the table, I tried using setColumData, setdata but it's not refreshing the table dropdown.

kindly help me.

**Comment by pphod** [comment]
You have access to the options in the dropdown here:
table.options.columns[columnNumber].source

You can update the options anytime. For doing that automatically you can implement something described in the conditional example in this page:
https://bossanova.uk/jexcel/v4/examples/dropdown-and-autocomplete
