### ISSUE TITLE
Feature request: Shift+Tab to navigate to leftward cell

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#107]
**Replicate**
1. Visit https://bossanova.uk/jexcel
1. Scroll to demo
1. Click cell A1.
1. Press `Tab` key.
1. Press `Shift+Tab` key.

**Expected Results**
Cursor navigates from A2 to A1, no cell is highlighted.

**Actual Results**
Cursor navigates from A2 to A3 and highlights both cells.

**Additional Information**
Excel and Calc handle `Shift+Tab` by navigating leftwards.
1. Start Excel (or LibreOffice Calc).
1. Click cell A1.
1. Press `Tab` key
1. Press `Shift+Tab` key

`Tab` and `Shift+Tab` have the same behaviour as `Right Arrow` and `Left Arrow`, respectively.

**Comment by pphod** [comment]
It has been done. It will be available in the next commit in a few moments.
