### ISSUE TITLE
includeHeadersOnCopy option seems to be broken

### ISSUE THREAD

**Issue by gshklover** [jspreadsheet/ce#1071]
If includeHeadersOnCopy=true, copy() code seems to reference str / strLabel before they are assigned throwing an error.

Thanks,
Gregory.

**Comment by noneymous** [comment]
I have the same issue. Tried to manually set column headers ('colHeaders'), but didn't help. As soon as i press CTRL+C with cells selected, the following error is triggered:

![grafik](https://user-images.githubusercontent.com/31357019/89303977-2fcd8980-d66d-11ea-8190-458fc7388c42.png)

(jExcel v4.3.0)

**Comment by pphod** [comment]
It has been fixed.
