### ISSUE TITLE
Filters on multiple columns

### ISSUE THREAD

**Issue by paulbriton** [jspreadsheet/ce#1077]
For now, it's not possible to apply multiple filters on multiple columns.

For instance if you apply a filter on column A and then on column B, the second filter will reset the first one. 

Could it be possible to add this ?

**Comment by pphod** [comment]
This will be included in the new Jexcel Pro release. It will be deployed within the next couple of weeks.

**Comment by vaisakhcp** [comment]
Any update ?

**Comment by hodeware** [comment]
That is available on the Pro since v5.
https://jspreadsheet.com/v9/docs/filters
