### ISSUE TITLE
Insert Cells - Shift Down

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#1078]
Like in Excel, is it possible to programmatically add cells (as opposed to an entire row) and shifting all cells directly underneath down?

**Comment by pphod** [comment]
We are considering bringing that in the next release of Jexcel Pro.

**Comment by ghost** [comment]
Got it. Thanks, Paul.

**Comment by pphod** [comment]
If you wish to send me an email, I can foward you with more details and timescale.

paul@jexcel.net

**Comment by pphod** [comment]
We have not included this specific feature yet. But, but the core is ready and will be included in the next. But, for the new version lot of new features are available in regards to formulas (cross worksheets, copy and paste formulas, etc).

It would be available Sunday 9th August 22pm UK time.
