### ISSUE TITLE
Feature request: Disable cell selection

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#108]
**Replicate**
1. Visit https://bossanova.uk/jexcel/examples
1. Scroll down to table is visible
1. Hold down mouse button
1. Drag over tables

**Actual Results**
Multiple cells are selected.

**Desired Results**
No cells are selected.

**Feature Request**
I would like to disable the ability to select any cells (either with the mouse or with keyboard and shift keys). The following appears to be correct:

``` .json
      rowDrag: false,
```

However, the table cells can be selected.

**Comment by pphod** [comment]
Do you mean disable the selection of multiple cells and keep the selection of one cell at time?

**Comment by ghost** [comment]
The range selection. Imagine selecting two cells containing 1 and 2, respectively. Then you drag the tiny square in the bottom right corner to apply the range selection across multiple cells. I'd like to disable this behaviour.

**Comment by pphod** [comment]
In the next commit you can use:

selectionCopy:false

`$('#my').jexcel({
    data:data,
    colHeaders: ['Country', 'Food', 'Stock'],
    colWidths: [ 300, 100, 200 ],
    onload:onload1,
    selectionCopy:false
    columns: [
        { type: 'autocomplete', source:countries },
        { type: 'dropdown', source:['Apples','Bananas','Carrots','Oranges','Cheese'] },
        { type: 'checkbox' },
        { type: 'text', readOnly:true },
    ]
});`

**Comment by sanjayAdhikari** [comment]
Can we make selectionCopy false to only one column? @paulhodel  ?

**Comment by pphod** [comment]
You can do that, by using onselection method. When you detect the cell you don't want is selected:

instance.options.selectionCopy = false;

Else

instance.options.selectionCopy = true;

**Comment by sanjayAdhikari** [comment]
@paulhodel  Thanks for the quick response, Above mentioned solution solve the problem, However selecting too quick throws an error saying: `TypeError: Cannot set property 'selectionCopy' of undefined`

```
ExcelTable.jsx:114 Uncaught TypeError: Cannot set property 'selectionCopy' of undefined
    at Object.selectionActive (ExcelTable.jsx:114)
    at Object.obj.dispatch (jexcel.js:340)
    at Object.obj.updateSelectionFromCoords (jexcel.js:2948)
    at HTMLDocument.jexcel.mouseDownControls (jexcel.js:7661)
```

**Comment by pphod** [comment]
I imagine you are using the instance you have created. If you don't have the instance you might get that using a selector:

var instance = document.getElementById('spreadsheet').jexcel;

Or

jexcel.current.options.selectionCopy
