### ISSUE TITLE
Loading Animation when Pasting Large Datasets

### ISSUE THREAD

**Issue by ScottGuthart** [jspreadsheet/ce#1081]
Similar to issue #794 I'm actually looking to implement this in vanilla javascript and I'm running into the same issue. 

The loading animation does not display when using the onbeforepaste or onbeforechange events.

I'm guessing this is because this is because `jSuites.loading.show();` is run asynchronously with the code that is hanging but I'm not sure of the best resolution.

https://codesandbox.io/s/basic-jexcel-with-loading-msg-hfz66

**Comment by pphod** [comment]
Actually Jsuites loading is very decouple of the code. I have created a jsfiddle to show a working version.
https://jsfiddle.net/paulhodel/k96xqaev/

**Comment by ScottGuthart** [comment]
Ah gotcha. I think that does demonstrate that they are decoupled. But this is still an issue, primarily during the first paste of a large dataset. 

When using that jsfiddle, the first time I paste in a large dataset (1000Rx10C) the page shows no indication that anything is happening for ~10 seconds, the loading animation for 1 second. Ideally, I think the loading animation would be displayed the entire time.

Interestingly, the next time dataset with the same size is pasted the data the total loading time is only about 2 seconds. I'm guessing this is because of the time required to setup the DOM / add elements.

**Comment by pphod** [comment]
But, if you don't include the timeout and include on the onafterchanges them you get what you are looking for. 

Have you tried the Pro distribution?
1) Open an excel copy 10K rows, go in the link below and paste in the first cell
https://jexcel.net/v7/examples/lazy-loading

Let me know what do you think.

Regards,
