### ISSUE TITLE
Extend existing context menu without repeating the code for already present options

### ISSUE THREAD

**Issue by yash17a** [jspreadsheet/ce#1082]
As per https://bossanova.uk/jexcel/v4/examples/contextmenu

For implementing custom options we need to implement full options again. Any better approach?

Use case:
My context menu should have all existing options provided as well as few more options which i will create. But with present functionality i would have to copy all code from above url (repetitive code which i dont want to copy unnecessarily) and then add my code.

Any better approach available which i missed?

**Comment by pphod** [comment]
Separated that in a different JS file. and declare only the method in the intialization.

contextMenu: yourCustomContextMenu

**Comment by yash17a** [comment]
Hi, while overriding existin paste customMenuOptions. facing issue while accessing  jexcel object
`              jexcel.current.paste(obj.selectedCell[0], obj.selectedCell[1], text);
`

what should be placed in place of jexcel.current?  @paulhodel
