### ISSUE TITLE
What will be the date format for 09-Mar-2020 for calendar column type?

### ISSUE THREAD

**Issue by dollychhabriya** [jspreadsheet/ce#1085]
What will be the date format for 09-Mar-2020 for calendar column type?

**Comment by dollychhabriya** [comment]
Hi,

Can you please provide an update for the above issue

**Comment by pphod** [comment]
Did you try DD/MON/YYYY?

**Comment by dolly-chhabriya-altius** [comment]
Thank you

**Comment by dolly-chhabriya-altius** [comment]
This date format is giving Month name in capital. It is giving MAR not Mar
