### ISSUE TITLE
Imossible to close a color picker on mobile

### ISSUE THREAD

**Issue by mikolaikrol** [jspreadsheet/ce#1086]
When a color picker is open, it's impossible to close it on moile, neither by clicking on the close button nor clicking elsewhere

**Comment by mikolaikrol** [comment]
just for the color picker in the toolbar, ex : {
            type: 'color',
            content: 'format_color_text',
            k: 'color'
        },

**Comment by mikolaikrol** [comment]
even on desktop when window width < ~850px

**Comment by pphod** [comment]
I have just tested on the desktop < 850 and it is working fine. Do you have further information on how to test? Are you on the latest version?

**Comment by mikolaikrol** [comment]
With the example on https://bossanova.uk/jexcel/v4/examples/spreadsheet-toolbars, with screen width < ~800 and less i got the same issue, it opens a colorpicker from the bottom of the screen and impossible to close it

**Comment by pphod** [comment]
Got it, I will patch that soon.

**Comment by pphod** [comment]
it has been fixed.
