### ISSUE TITLE
Hide header option

### ISSUE THREAD

**Issue by tsh356** [jspreadsheet/ce#1087]
Is there an option to hide the header, much like hideIndex()?

On Pro Version

**Comment by pphod** [comment]
You can use CSS or JavaScript:

JavaScript:
tableInstance.thead.style.display = 'none';

CSS:
.jexcel thead {
display: none;
}

For a faster Pro Distribution support, you can use: paul@jexcel.net

**Comment by pphod** [comment]
jexcel.current.thead.style.display = 'none'; // Will apply for the current spreadsheet on focus.
