### ISSUE TITLE
Percentage value cannot be executed in a formula cell

### ISSUE THREAD

**Issue by GutsTang** [jspreadsheet/ce#1089]
Hello buddy,
I find that sometimes formula cells cannot be executed correctly when it involves percentage values.
I debugged the code. Seems it's because the program uses Number function to determine whether the value is a number.
<img width="668" alt="jexc" src="https://user-images.githubusercontent.com/58201996/89619787-25a3c900-d8c1-11ea-8827-73bd3595760c.png">
Due to Number function cannot handle a percentage value, it always returns blank.

I solved this problem with some ugly codes.
<img width="733" alt="jexc2" src="https://user-images.githubusercontent.com/58201996/89620710-9c8d9180-d8c2-11ea-84bf-548a9b7bb88f.png">
Are there other better solutions?

**Comment by pphod** [comment]
You can use a custom column type, or an event to have separate the DATA & LABEL from your column. For example:

Your column label could be: 80% and the data saved is 0.8

For example:

onchange: (instance, cell, x, y) {
    if (x == 3 && y == 3) {
        instance.jexcel.options.data[y][x] / Number(cell.innerText) / 100;
    }
}
