### ISSUE TITLE
Feature request: Extended keyboard inputs

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#109]
**Replicate**
1. Visit https://bossanova.uk/jexcel/examples
1. Scroll down to the spreadsheet
1. Select cell B2
1. Press one of `Home`, `End`, `PgDn`, `PgUp`, or `Spacebar`.

**Actual Results**
Browser window scrolls or no cell focus is changed.

**Expected Results**
Here are the keys and expected results:

| Key        | Navigate | Description
| ------------- |:-------------:| --- |
| `Home`     | A2 | First cell in the current row.
| `End`     | E2 | Last cell in the current row.
| `PgDn` | B4 | Jumps down a number of rows.
| `PgUp` | B1 | Jumps up a number of rows.
| `Spacebar` | n/a | Starts data entry on active cell, cell contents are removed.

It should be possible to configure page up and page down to jump a given number of rows.

**Comment by pphod** [comment]
Home, End, Spacebar was included in the next version.
