### ISSUE TITLE
I want to use spaces to make the table appear indented, is this not feasible?

### ISSUE THREAD

**Issue by Warrens-yg** [jspreadsheet/ce#1091]
Like this:
![批注 2020-08-07 222536](https://user-images.githubusercontent.com/46614146/89650165-f317c180-d8fc-11ea-955d-d9752f16d031.png)

**Comment by pphod** [comment]
Spaces are no computed on HTML the way you are looking for. To use spaces you use the HTML code for space and change stripHTML: false. Or, I would suggest you use style to do it, such as leftPadding.

For example:
// X, y is the coords of the cell you wish to apply the space.
table.records[y][x].style.paddingLeft = '20px';
