### ISSUE TITLE
Handling events for cell Validation

### ISSUE THREAD

**Issue by jacksonbenete** [jspreadsheet/ce#1093]
Hello there,
I don't know why but some fields sometimes stop validating.

The `type: 'numeric'` columns doesn't validate anymore and I didn't found why.
But, I have to do some extra validations anyway.

For a good aesthetic effect I was validating on value change, so the user could receive a snackbar warning about any incorrect format right away.
It was working just right, I was doing it on the "onchange" event handler:

```
this.table = jexcel(tableNode.children[0], {
      data: [[]]
      ,minDimensions:[6,10]
      ,colHeaders: [...headers]
      ,colWidths: [100, 200, 100, 100, 100, 100]
      ,columns: [
        { type: 'dropdown', source:["C", "V"] },
        { type: 'autocomplete', source:symbolArray },
        { type: 'numeric' },
        { type: 'numeric', mask:'R$ #.##,00', decimal:',' },
        { type: 'numeric', mask:'R$ #.##,000', decimal:',' },
        { type: 'numeric', mask:'R$ #.##,000', decimal:',' },
      ],
    onchange: this.onTableChange.bind(this)
    });
```

I don't know why, sometimes it works just right, but sometimes it enters in an infinite loop of onchanges and freezes the tab.
Of course, if I do that on `onbeforechanges` is worse as it always freezes, but using `onchange` it freezes only sometimes even if I don't change the code.

```
onTableChange = function(instance, cell, x, y, value) {
if (x == 2) {
      if (isNaN(value)) {
        this.table.setValue(cell, (this.BRL(value) || 1))
      }
      else if (value == 0) {
        this.table.setValue(cell, 1)
      }
   }
   else if (x == 3) {
      this.table.setValue(cell, (this.BRL(value) || 1))
    }
})
```

In the first validation if is the third column (x == 2) it checks if it's numeric, if not, it converts in a number and returns it as a number, else if it's not a convertable string, it set's the cell value as the number 1. Else, if the value is equal 0, it set's to 1.
In the second validation if is the forth column ( x == 3 ) it checks as the later.

Funny enough, when I change the value on column x == 2 it sometimes works and it sometimes enters in the infinite loop, the column x == 3 will always enters the infinite loop.

The problem isn't in the `this.BRL()` function as trying to validate as a simple `this.table.setValue(cell, 1)` also enters an infinite loop.

If I can't find a way to do this, I will just validate when the user press the button to send the data, but I would like to continue validating on the fly since it was working before.

What is the best way to validate cell data change? Is at `onchange` event handler or there is any other event handler better for that job?

I couldn't make onafterchange to work, and I don't know if it's the answer anyway.

Thanks!

**Comment by pphod** [comment]
Two options here.

1) The following one will make sure the inside setValue does not trigger the same event again.
```
onTableChange = function(instance, cell, x, y, value) {
this.table.ignoreEvents = true;
if (x == 2) {
      if (isNaN(value)) {
        this.table.setValue(cell, (this.BRL(value) || 1))
      }
      else if (value == 0) {
        this.table.setValue(cell, 1)
      }
   }
   else if (x == 3) {
      this.table.setValue(cell, (this.BRL(value) || 1))
    }
this.table.ignoreEvents = false;
})
```

2) The following one will change the values without going throught jexcel.

```
onTableChange = function(instance, cell, x, y, value) {
this.table.ignoreEvents = true;
if (x == 2) {
      if (isNaN(value)) {
        cell.innnerText= this.BRL(value) || 1;
        this.table.options.data[y][x] = this.BRL(value) || 1;
      }
      else if (value == 0) {
        // do the same as above
      }
   }
   else if (x == 3) {
        // do the same as above
    }
this.table.ignoreEvents = false;
})
```
