### ISSUE TITLE
Autocomplete website example references wrong version of jsuite

### ISSUE THREAD

**Issue by johnkazer** [jspreadsheet/ce#1094]
The page [https://bossanova.uk/jexcel/v4/examples/dropdown-and-autocomplete](https://bossanova.uk/jexcel/v4/examples/dropdown-and-autocomplete) references v2 but the code uses (and needs) v3 of jsuite.

**Comment by pphod** [comment]
I have updated the whole documentation and it would be deployed soon. Thanks for letting us know.
