### ISSUE TITLE
JExcel ISSUE in POPUP Window | Edge Browser

### ISSUE THREAD

**Issue by khuthbudin** [jspreadsheet/ce#1095]
Hi Team,

We are trying to open the JExcel in the popup window, its working perfectly in chrome, Firefox. 

Eg:  window.open(windowURL, windowId,'height=' + ((screen.height/100)*75) + ',width=' + ((screen.width/100)*75) + ',resizable=yes,scrollbars=yes,toolbar=yes,menubar=yes,location=yes');

But in edge browser, it's failing when I open for the second time and it's failing with the below error.

**Opening second time causes:: The remote server machine does not exist or is unavailable jexcel.js (1550,24).**

Lib Used

- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
- <script type="text/javascript" src="https://bossanova.uk/jexcel/v3/jexcel.js"></script>
- <script type="text/javascript" src="https://bossanova.uk/jsuites/v2/jsuites.js"></script> 

Regards,
Khuthbudin T.
khuthbu123@gmail.com

![Screenshot (41)](https://user-images.githubusercontent.com/3747336/89992366-cb30b100-dca2-11ea-864c-56760c049420.png)

**Comment by pphod** [comment]
I am not sure, but I would say try to follow one of the examples in the website or create a jsfiddle with the code you have problems.
