### ISSUE TITLE
NumPad Decimal Point not working

### ISSUE THREAD

**Issue by cbeltrangomez84** [jspreadsheet/ce#1097]
My PC current locale is 'es-US' and I have a numeric column with mask = "#,##.000" and decimal = ".", when I'm editing the cell, If I press the decimal key in the NumPad nothing happend, but if I press the same key "." in the typewriter keys it works.

**Comment by pphod** [comment]
That has been fixed on the Jexcel Pro distribution (https://jexcel.net/v7) and we would bring to the Ce distribution on the next release.

**Comment by cbeltrangomez84** [comment]
Thanks @paulhodel Is there an expected release date for it?

**Comment by pphod** [comment]
We still planning for that. If you subscribe the newsletter I can keep you informed. Meawhile, if you wish to test the Pro distribution for free and send you feedback would  be great.

Regards,

**Comment by pphod** [comment]
This has been included on the CE v4.4.1+

Regards,

**Comment by cbeltrangomez84** [comment]
Hi, I just updated jexcel and the issue persist :(

**Comment by cbeltrangomez84** [comment]
Hi, I've just updated and the issue persist :(

**Comment by cbeltrangomez84** [comment]
Hi @paulhodel could you reopen this issue? regards

**Comment by misol** [comment]
I have suffered this issue, until now. (jSpreadsheet CE 4.6.0)

**Comment by misol** [comment]
@cbeltrangomez84 The issue was solved after updating jsuite to the updated files https://github.com/jsuites/jsuites .

**Comment by cbeltrangomez84** [comment]
Thanks a lot @misol
