### ISSUE TITLE
How to disable sorting and editable feature from the excel sheet 

### ISSUE THREAD

**Issue by gulshan-escalon** [jspreadsheet/ce#11]
@paulhodel : How to disable sorting and editable feature from the excel sheet created on the browser ?

**Comment by pphod** [comment]
columSorting:false
editable:false

**Comment by gulshan-escalon** [comment]
Its not working Paul ? should i need to replace my jquery,excel.js file again ?

**Comment by pphod** [comment]
Yes, you should update and get the most recent version.
