### ISSUE TITLE
Feature request: Get current row and column

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#110]
The API does not appear to offer the following methods:

``` .javascript
/**
 * Returns the column number of the active cell.
 */
$("#table").jexcel( 'getCol' );

/**
 * Returns the column number of the active cell.
 */
$("#table").jexcel( 'getRow' );
```

This would allow for convenience methods to get the column header name, for example.

**Comment by pphod** [comment]
We are going to create a method to bring that information. Meanwhile, you can use the global variable:

$.fn.jexcel.selectedCell

**Comment by pphod** [comment]
Three new methods will be introduced in a commit will be uploaded later today.

$('#spreasheet').jexcel('getSelection');
$('#spreasheet').jexcel('getCellCursor');
$('#spreasheet').jexcel('getSelectedCells');
