### ISSUE TITLE
add row in jexcel angualr

### ISSUE THREAD

**Issue by gargri** [jspreadsheet/ce#1101]
sir i m facing a problem, i m not able to understand how i can add new row in jexcel in angular , i m using typescript so can u help me to add new button without jquery

**Comment by pphod** [comment]
This is the script:
https://codesandbox.io/s/pensive-curie-bpve3

**Comment by gargri** [comment]
thanku sir for reply me, can u tell me how i van change cell value after onchange event

**Comment by pphod** [comment]
https://codesandbox.io/s/twilight-hooks-moq79

```
export class AppComponent {
  @ViewChild("spreadsheet") spreadsheet: ElementRef;
  @ViewChild("button") button: ElementRef;
  title = "an";

  ngAfterViewInit() {
    var t = jexcel(this.spreadsheet.nativeElement, {
      minDimensions: [40, 10],
      onchange: function (element, cell, x, y, value, oldValue) {
        alert(value);
      }
    });

    this.button.nativeElement.onclick = function () {
      t.insertRow();
    };
  }
}
```
