### ISSUE TITLE
Not showing all dates for calendar column type in React

### ISSUE THREAD

**Issue by dollychhabriya** [jspreadsheet/ce#1102]
All dates are not visible for some months in date picker for calendar column type. Attaching screenshot for reference
![Screenshot from 2020-08-17 14-05-32](https://user-images.githubusercontent.com/55905358/90375760-03fdcb00-e093-11ea-9af0-16c614f2e611.png)

Above screenshots displays Mar month but shows dates till 28th only.
Can you please provide solution for the same.

**Comment by pphod** [comment]
This has been fixed quite some time ago. I would suggest you get the most recent version of both jexcel and jsuites.

**Comment by dollychhabriya** [comment]
Thank you for the help.
