### ISSUE TITLE
setConfig() not working using v4 npm-4.3.0

### ISSUE THREAD

**Issue by tarunmeena512** [jspreadsheet/ce#1107]
Hi @paulhodel 

I'm trying to update the table config but it is not working.

for example- 
let config = table.getConfig();
table.setConfig() // getting undefined

i checked in jexel.js  setConfig() is not available.

Could you please help me how i can achive this.

Thanks
Tarun

**Comment by pphod** [comment]
This method should be included in the next release in the next few weeks. Meanwhile, which configuration are you trying to apply?

**Comment by tarunmeena512** [comment]
@paulhodel  thanks for the relpy.
 i want to apply "editable":false property (programmatically) so user will not be able to edit the whole table.

**Comment by pphod** [comment]
You can do that by changing the property directly.
table.options.editable = false;

**Comment by HaCherry** [comment]
@paulhodel
 is setConfig Option available yet in v4.13.4
