### ISSUE TITLE
issue with custom column type.

### ISSUE THREAD

**Issue by kallaguntaashok** [jspreadsheet/ce#1108]
kindly check the example "https://bossanova.uk/jexcel/v4/examples/column-types" --> 2) CUSTOM COLUMN TYPE.

if we apply custom logic to the column, not able to drag the value from one row to another row, it's working fine in version 3.

kindly help me.

**Comment by alfr3dosv** [comment]
Perhaps using updateCell will fix it
example
```
var customColumn = {
    closeEditor: ...,
   ....
    updateCell: function (cell, value) {
            let instance = cell.parentNode.parentNode.parentNode.parentNode.parentNode.jexcel;           
            let y = cell.dataset.y;
            let x = cell.dataset.x
            cell.innerHTML = value;
            instance.options.data[y][x] = value;
            return value;
   }
}
```

**Comment by kallaguntaashok** [comment]
you're my savior bro, I was struggling to solve this problem, how do you know all these things, I could not able to fin this peace of update cell code anywhere. 

thank you so much again for your help and support, I would like to connect with you in further if I need any help in this jexcel, you have very good understanding about this frame work.
