### ISSUE TITLE
Feature request: Add onchange hook to column

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#111]
Currently, the `onchange` method hooks on all cell changes:

https://github.com/paulhodel/jexcel/blob/master/dist/js/jquery.jexcel.js#L1898

It would be convenient if it was possible to add a hook for changes to cells in a particular column. For example:

``` .javascript
    $("#spreadsheet").jexcel({
      colHeaders: [ 'Day', 'Began', 'Ended', 'Shift', 'Total', 'Description' ],
      colWidths: [ 32, 80, 80, 48, 48, 384 ],
      columns: [
        { type: 'calendar', options: { format: 'DD' }, readOnly: true },
        { type: 'text', options: { onchange: beganChanged } },
        { type: 'text', options: { onchange: endedChanged } },
        { type: 'numeric', readOnly: true },
        { type: 'numeric', readOnly: true },
        { type: 'text' }
      ]
    });
```

This issue would obviate issue #110 for me; however, having the ability to get the active row and column would be useful for other development purposes.

**Comment by pphod** [comment]
Dave, thank you for your suggestion. But, you already can do that by getting the position from each cell using the following code:

```
changeMethod = function(instance, cell, newValue, oldValue)
{
   // Get cell position
   position = $(cell).prop('id').split('-');

   // First column
   if (position[0] == 1) {
      // Perform some action only for first column
   }
}


$("#spreadsheet").jexcel({
      colHeaders: [ 'Day', 'Began', 'Ended', 'Shift', 'Total', 'Description' ],
      colWidths: [ 32, 80, 80, 48, 48, 384 ],
      onchange:changeMethod,
      columns: [
        { type: 'calendar', options: { format: 'DD' }, readOnly: true },
        { type: 'text' },
        { type: 'text' },
        { type: 'numeric', readOnly: true },
        { type: 'numeric', readOnly: true },
        { type: 'text' }
      ]
});
```

**Comment by ghost** [comment]
Agreed, there is already a way to get this data. However, such an implementation tightly couples the formatting of the data representation to the code that uses the data. I currently have:

``` .javascript
  var rc = $(cell).prop('id').split( '-' );
  var col = rc[0];
  var row = rc[1];

  // If the header is either Began or Ended, change the contents.
  var header = $('#timesheet').jexcel('getHeader', col);

  if( header.match( /began/i ) || header.match( /ended/i ) ) {
    // Common logic...
  }
```

This isn't as clean as it could be. A slightly cleaner implementation would eliminate the coupling to the format of the ID attribute:

``` .javascript
  var row = $(cell).prop('row');
  var col = $(cell).prop('col');

  // ...
```

Even simpler is to have a function be called when any particular value in the column changes. This would reduce the code to:

``` .javascript
onColumnsChanged = function( obj, cell, value ) {
    // Common logic...
}
```

Additionally, this decouples knowledge of the column number from the implementation code, allowing the column orders to change without impacting the calling code--as in the example you posted. Using the column *name* instead of the *index* requires less maintenance.

At this point neither the column number nor the name are hard-coded, allowing the order and name to vary without requiring changes to the source code.

**Comment by pphod** [comment]
I understood your request now. I imagine you don't know which is the column number of your column with Header = Began or Ended. I would take a look on that in the next version...

**Comment by pphod** [comment]
This should work in the next commit:
  var row = $(cell).prop('row');
  var col = $(cell).prop('col');
