### ISSUE TITLE
Jexcel CE v5

### ISSUE THREAD

**Issue by pphod** [jspreadsheet/ce#1112]
Hi Everyone,

We started planning how the new Jexcel CE v5 would look like. Which features do you think should be brought to the new version?

Regards,

**Comment by whyJoe** [comment]
I hope add a function that  the selected cells can be automatically summed!!!

**Comment by gargri** [comment]
add new function that from one cell change we are able to change other cells

**Comment by mhstreta** [comment]
add new function to allow adding styles by row number or row index and also by column number or column index. This way it will be much easier to set styles programatically for specific rows or specific columns.

**Comment by mhstreta** [comment]
add options to hide row and column headers on initialization but context menu and formulas still should work

**Comment by pphod** [comment]
> add new function that from one cell change we are able to change other cells

This already exists by using the onchange or onafterchanges events.

**Comment by pphod** [comment]
> I hope add a function that the selected cells can be automatically summed!!!

Have you tried to use formulas on footers?
https://bossanova.uk/jexcel/v4/examples/footers

**Comment by jonizhenshuai** [comment]
> > I hope add a function that the selected cells can be automatically summed!!!
> 
> Have you tried to use formulas on footers?
> https://bossanova.uk/jexcel/v4/examples/footers

sorry,I haven't seen it before

**Comment by whyJoe** [comment]
> > I hope add a function that the selected cells can be automatically summed!!!
> 
> Have you tried to use formulas on footers?
> https://bossanova.uk/jexcel/v4/examples/footers

I mean the cell are selected by user,just sum the selected cell,not a column.

**Comment by krosoftware** [comment]
Option to move right after Enter is pressed.

**Comment by yuricaldasr93** [comment]
Hi everyone. I hope the CE v5 has the events onfilter and onbeforefilter and filter by conditions like below image.
[Reference link](https://handsontable.com/docs/8.0.0/demo-filtering.html)
![image](https://user-images.githubusercontent.com/17741438/91075169-0375af00-e614-11ea-851e-8b8255154182.png)

**Comment by flywalt** [comment]
better input for other languages. #935 
the scorll bar becomes wider when focused

**Comment by GBonnaire** [comment]
Add support of plugins like JExcel Pro 😊

**Comment by GBonnaire** [comment]
> add new function to allow adding styles by row number or row index and also by column number or column index. This way it will be much easier to set styles programatically for specific rows or specific columns.

Already available on Pro version with my plugin : https://github.com/Guillaume-Bo/jexcel-plugins-and-editors/tree/master/plugins/conditional_style

**Comment by pphod** [comment]
Thanks for the feedback. We would consider all requests in the next CE distribution.

**Comment by Alex-Monahan** [comment]
I think the biggest feature that would help us is cascading filters! It would require multi-column filtering, as well as recalculating the available filter options for all other columns based on what is already filtered.

**Comment by Alex-Monahan** [comment]
One other small thing would be an option for the scroll bar to show a larger remaining space when using lazy loading instead of going all the way to the bottom before adding new rows (just to indicate to the user that there are still many more rows)

**Comment by ghost** [comment]
> 我希望添加一个功能，可以自动将所选单元格加起来！！！

You can do this by selecting the event to get the first and last cell selected, combined with the formula.

**Comment by muelleRw** [comment]
Being able to select cells not next to each other using ctrl

**Comment by SamHz** [comment]
dropdown  can you add tree type ?
