### ISSUE TITLE
getValue() doesn't work if provide [x, y] rather than a cell

### ISSUE THREAD

**Issue by johnkazer** [jspreadsheet/ce#1113]
The function initially tests for 'object' to detect a cell then tries to handle the array. However, the array also counts as an object, so it doesn't work.

**Comment by pphod** [comment]
getValue accepts a DOM cell or a string in excel like format. For using coordinates, please use:

table.getValueFromCoords(x, y)

**Comment by johnkazer** [comment]
Ah yes I see now, thanks.
