### ISSUE TITLE
setValue is not working inside onchange() in angular

### ISSUE THREAD

**Issue by gargri** [jspreadsheet/ce#1117]
onchange(instance, cell, x, y, value) {
    console.log(instance);
    // var position = cell.attr('id').split('-');
    // console.log(position);
    console.log(this.table.data);
    console.log(cell);
    console.log(x);
    console.log(y);
    this.table.setValue('A1','text');
    console.log(jexcel.getColumnNameFromId([x,y]));
    console.log('New change on cell ' + jexcel.getColumnNameFromId([x,y]) + ' to: ' + value + '');
    //jexcel(this.spreadsheet).getColumnNameFromId([x,y]);
    return true;
  }

this is my code and when i use this it shows me error

core.js:6189 ERROR TypeError: this.table.setValue is not a function
    at Object.onchange 👍

**Comment by pphod** [comment]
Change: 
this.table.setValue to instance.jexcel.setValue

**Comment by gargri** [comment]
sir this is also not working . show me this error
core.js:6189 ERROR TypeError: instance.setValue is not a function
    at Object.onchange

**Comment by gargri** [comment]
plz reply its urgent

**Comment by pphod** [comment]
Change:
this.table.setValue to instance.jexcel.setValue

**Comment by gargri** [comment]
thanks for reply
but this is not working
