### ISSUE TITLE
Feature request: Get column number from header identifier

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#112]
Consider:

``` .javascript
    $("#spreadsheet").jexcel({
      colHeaders: [ 'Day', 'Began', 'Ended', 'Shift', 'Total', 'Description' ],
      colWidths: [ 32, 80, 80, 48, 48, 384 ],
      ...
    });
```

For internationalization purposes, referring to columns by identifiers can be useful:

``` .javascript
    $("#spreadsheet").jexcel({
      colHeaders: [ 'Day', 'Began', 'Ended', 'Shift', 'Total', 'Description' ],
      colHeaderIds: [ 'day', 'start', 'end', 'subtotal', 'sum', 'user.defined.1' ],
      ...
    });
```

Then:

```
// Returns 3
var col = $("#table").jexcel( 'getHeaderCol', 'subtotal' );
// Returns 0
var col = $("#table").jexcel( 'getHeaderCol', 'day' );
// Returns -1
var col = $("#table").jexcel( 'getHeaderCol', 'error-missing-id' );
```

This would allow for:

``` .javascript
    $("#spreadsheet").jexcel({
      colHeaders: [ 'Dia', 'Começasse', 'Terminou', 'Mudança', 'Total', 'Descrição' ],
      colHeaderIds: [ 'day', 'start', 'end', 'subtotal', 'sum', 'user.defined.1'  ],
      ...
    });
```

Behind the scenes, the code can use the `colHeaderIds` to reference the headers without having to hard-code the names, or rely on fixed orders. This relates to #111.

**Comment by pphod** [comment]
Unfortunately, the property id is in use. So, I get close to your request by:

    $("#spreadsheet").jexcel({
      colHeaders: [ 'Dia', 'Começasse', 'Terminou', 'Mudança', 'Total', 'Descrição' ],
      colHeaderClasses: [ 'day', 'start', 'end', 'subtotal', 'sum', 'user.defined.1'  ],
      ...
    });

    $("#spreadsheet").jexcel('getHeaderNumber', 'start'); // will return 1
