### ISSUE TITLE
Unable to call custom method on table footer formula calculation.

### ISSUE THREAD

**Issue by tarunmeena512** [jspreadsheet/ce#1122]
Hi @paulhodel
Hope you are doing well .

I'm trying below code in angular for whole column calculation but its not working .

export class AppComponent {
  @ViewChild("spreadsheet") spreadsheet: ElementRef;
  data = [
    ['Cheese', 10, 6.00, "=B1*C1"],
    ['Apples', 5, 4.00, "=B2*C2"],
    ['Carrots', 5, 1.00, "=B3*C3"],
    ['Oranges', 6, 2.00, "=B4*C4"],
];

  ngAfterViewInit() {

    var table = jexcel(this.spreadsheet.nativeElement, {
    data:this.data,
    minDimensions: [4,10],
    columnDrag:true,
    footers: [['Total','=SUMCOL(TABLE(), COLUMN())','=SUMCOL(TABLE(), COLUMN())','=SUMCOL(TABLE(), COLUMN())']],
    columns: [{
        width:'200px',
    }]
    });

  }
  
  SUMCOL = function(instance, columnId) {
    var total = 0;
    for (var j = 0; j < instance.options.data.length; j++) {
        if (Number(instance.records[j][columnId-1].innerHTML)) {
            total += Number(instance.records[j][columnId-1].innerHTML);
        }
    }
    return total;
}
}

output - 
![image](https://user-images.githubusercontent.com/30525908/91398565-f64a0180-e859-11ea-9063-3c6c10ba5ad5.png)

Could you please help us.

Thanks

**Comment by GBonnaire** [comment]
In your message : Do you have recreate function SUMCOL ? or do you have just copied a SUMCOL of JExcel ?

**Comment by pphod** [comment]
SUMCOL should be in the global scope.
maybe window['SUMCOL'] = function() {} will solve your problem

**Comment by tarunmeena512** [comment]
Perfect @paulhodel its working fine using below code.
Thanks :-)
  winRef.nativeWindow["SUMCOL"] = function (instance, columnId) {
      var total = 0;
      for (var j = 0; j < instance.options.data.length; j++) {
          if (Number(instance.records[j][columnId-1].innerHTML)) {
              total += Number(instance.records[j][columnId-1].innerHTML);
          }
      }
      return total;
    }
