### ISSUE TITLE
how to disable right click function of Jexcel v4.4

### ISSUE THREAD

**Issue by benci042** [jspreadsheet/ce#1123]
while build fixd columns table  how to disable right function of jexcel? 

![image](https://user-images.githubusercontent.com/3356609/91412297-2b674b80-e87c-11ea-8afa-82d691ba1759.png)

**Comment by GBonnaire** [comment]
Have use try with custom ContextMenu ?

and return false , null or [] for disable contextmenu on specifics area

**Comment by benci042** [comment]
it's working now. thanks.
