### ISSUE TITLE
setvalue and getValue() not working inside updateTable in angular

### ISSUE THREAD

**Issue by gargri** [jspreadsheet/ce#1126]
![jexcel](https://user-images.githubusercontent.com/42148377/91691682-adf65080-eb85-11ea-817e-c901965aa779.PNG)
1. i m using latest version of angular(10)
2. i am trying to use updateTable() funtion but i m not able to use setData() and getData() function inside it
3. i use below reference 
https://bossanova.uk/jexcel/v4/examples/table-scripting

**Comment by GBonnaire** [comment]
Why use setData on updateTable ? what do you want to do ?

On your error, your getData is not on your good instance. Can you show your code update data with getData ?

**Comment by pphod** [comment]
On the arguments that reach the method:
instance.jexcel.getData()

**Comment by gargri** [comment]
i want that when i change any cell value then automatically it will change end cell value from 0 to 1

**Comment by gargri** [comment]
so that i am able to know how many rows i  change

**Comment by GBonnaire** [comment]
Maybe, you can use custom formula and event onbeforechange ?

Example for count change by column

```Javascript
    var changeCell = {};
    var COUNTCHANGE = function(col) {
        if(!changeCell[col]) {
            changeCell[col] = 0;
        }
        return changeCell[col];
    }
```

and on option of JExcel 
```Javascript
var Table1 = jexcel(document.getElementById('spreadsheet'), {
...
         footers: [
             ["=COUNTCHANGE(COLUMN())", "=COUNTCHANGE(COLUMN())", "=COUNTCHANGE(COLUMN())", "=COUNTCHANGE(COLUMN())", /*... as many as you have column */ ]
         ],
         onbeforechange: function(el, cell, x, y, value) {
             var col = parseInt(x)+1;
             changeCell[col]++;
         }
...
}
```
