### ISSUE TITLE
working with index column

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#1127]
First of all, thank you very much for your great work.
I have several doubts after reading the documentation. 
Right now the first column is the index and has the following structure "_", "1", "2", "3", etc.

1. How can I add a title to that column so that it is not a blank space?
2. I want to change the numbering. That is to say that instead of 1,2,3, it is the hour for example. I have seen that you have responded in the following post [https://github.com/paulhodel/jexcel/issues/1005](https://github.com/paulhodel/jexcel/issues/1005), but I don't know if I understood the answer. If all the cells in the table have 2 values ​​(x, y), how is it that to modify the numbering you only need 1 value?
3. If I modify the indexes, do I still access the cell values ​​with "a1", "a2", etc?
4. If the first cell is A1, what is the numbering of the headers in the columns and rows to be able to work with / modify them?

In case it influences, I am using VueJs.
Thank you very much and sorry if you have already answered these questions, but after a while I was not able to find those answers.

**Comment by GBonnaire** [comment]
Hi,

1) for Add text to header of column index use this
```
var table = jexcel(YourElement, YourOptions);
...

var HeaderIndex = table.el.querySelector('.jexcel_selectall');
if(HeaderIndex) {
  HeaderIndex.innerText = "Your custom text";
  HeaderIndex.style.textAlign = "center";
}
```
2) Coord it's data of cell and it's different that cell show
for your example
```
for (var j = 0; j < table.rows.length; j++) {
    table.rows[j].firstElementChild.innerText = (j % 24) + ":00"; // 24 for 24h set 12 for 12h
}
```

3) Yes, coord different of value of cell
4) A1 = (x=0 , y=0) (Coord) 
`table.getValue("A1") = table.getValueFromCoord(0,0)`
