### ISSUE TITLE
Feature request: Set readOnly values programmatically

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#113]
**Replicate**
Consider:

```.javascript
$("#sheet").jexcel({
      colHeaders: [ 'Day', 'Began', 'Ended', 'Shift', 'Total', 'Description' ],
      columns: [
        { type: 'calendar', options: { format: 'DD' }, readOnly: true },
        { type: 'text' },
        { type: 'text' },
        { type: 'numeric', readOnly: true },
        { type: 'numeric', readOnly: true },
        { type: 'text' }
      ]
    });
```

This prevents the user from setting the value, which is desired. However, it appears to prevent setting the value programmatically:

``` .javascript
$('#sheet').jexcel( 'setValue', 'D2', 10 );
```

**Expected Results**
Calling setValue programmatically should always set the result, even if the cell is read-only. (Read-only fields are mean to prevent humans from changing the value, but a program can change the value, which is useful for showing the result of calculations.)

**Actual Results**
Calling setValue programmatically does not set the result.

**Additional Information**
I think this is because of the following line:

https://github.com/paulhodel/jexcel/blob/master/dist/js/jquery.jexcel.js#L1847

``` .javascript
 $(this).jexcel('updateCells', records);
```

The call is passing `force` as false by default, which means the following line prevents the field from being set:

``` .javascript
 } else if ($(v.cell).hasClass('readonly') == true && force == false) {
```

**Work Around**
It may be possible to work around the issue by calling removeClass, setting the value, then calling addClass to reinstate the readonly class, but this has its own disadvantages.

**Addendum**
As a side note:

https://bossanova.uk/jexcel/docs/programmatically-changes

The example for **setValue** does not show passing in a new value.

**Comment by pphod** [comment]
To perform this action, update your repository from the master.

// This will force the change:
$('#my').jexcel('setValue', 'D2', 10, true);

**Comment by ghost** [comment]
There's a good chance I'm doing something wrong, but I'm unable to get this to work when adding the readonly class to specific cells using updateTable. 

updateTable: function(el, cell, x, y, source, value, id) {
          if (x == 4 && y <= 10) {
              cell.classList.add('readonly');
          }
      }

The line below only sets the value successfully when my updateTable readonly code is disabled

$('#spreadsheet').jexcel('setValue', 'E1', 100, true)

I tried removing the updateTable code and setting the column property to readonly:true instead as a test, but got the same results.
