### ISSUE TITLE
Multi select with checkbox

### ISSUE THREAD

**Issue by faizinkholiq** [jspreadsheet/ce#1130]
Hey bro, can we do multi select row with checkbox like this?

![Screenshot_2020-09-03_13-51-40](https://user-images.githubusercontent.com/42163856/92081008-a2f12980-edec-11ea-8ad7-e7a713ea7959.png)

**Comment by pphod** [comment]
Yes, you can do that. There is a type checkbox and you can create a method to know which of checkboxes are selected.
