### ISSUE TITLE
jexcel setstyle() function not working  properly in  merge cell?

### ISSUE THREAD

**Issue by ibalaji777** [jspreadsheet/ce#1134]
jexcel style working good in normal td cell but it does not apply style into merge cell.

`table.setStyle(mycell,'text-align','center')`

**Comment by fredchengfei** [comment]
do u konw how  to setStyle of whole table

**Comment by ibalaji777** [comment]
> do u konw how to setStyle of whole table
```

        <div style="width:100%;height:100%" id="spreadsheet"></div>



        var options = {
            data: [[]],
            minDimensions: [39, 40],
        };


        spreadsheet = jexcel(this.$el, options);
        Object.assign(this, spreadsheet);


```

THIS WHAT I TRY IN MERGE CELL NOT WORKING BUT NORMAL CELL WORKING GOOD
table.setStyle('A3','text-align','center')

**Comment by ibalaji777** [comment]
i tryied this also not working in merge cell but working in normal td

table.setStyle({A3:'text-align:center'})

**Comment by pphod** [comment]
I have tested and seems to be working fine.

1) Go to and open the console.
https://bossanova.uk/jexcel/v4/examples/merged-cells

2) Click in the table to focus, them on the console enter the following example.
jexcel.current.setStyle('A1', 'text-align', 'right');

**Comment by ibalaji777** [comment]
> I have tested and seems to be working fine.
> 
> 1. Go to and open the console.
>    https://bossanova.uk/jexcel/v4/examples/merged-cells
> 2. Click in the table to focus, them on the console enter the following example.
>    jexcel.current.setStyle('A1', 'text-align', 'right');



> I have tested and seems to be working fine.
> 
> 1. Go to and open the console.
>    https://bossanova.uk/jexcel/v4/examples/merged-cells
> 2. Click in the table to focus, them on the console enter the following example.
>    jexcel.current.setStyle('A1', 'text-align', 'right');

Thank u I tested working fine but something problem in my forked file.
