### ISSUE TITLE
How to set value of checkbox

### ISSUE THREAD

**Issue by Aliansyah5** [jspreadsheet/ce#1136]
i want to select all my checkbox and submit into db, but when i click submit the checbox checked but the value still false.

this is my select all code

 if(this.checked) {
      $(this).prop('checked', false); 
        $(':checkbox').each(function() {
            this.checked = true;                        
        });
    } else {
        $(':checkbox').each(function() {
            this.checked = false;                       
        });
    }

thank you in advance

**Comment by pphod** [comment]
Sorry, I am not sure what you trying to do. Do you mind to create an example on jsfiddle and share?
