### ISSUE TITLE
Feature request: Leave edit mode using up or down arrow key

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#114]
**Replicate**
1. Visit https://bossanova.uk/jexcel/examples
1. Double-click B2 (`Classe B`)
1. Change to `Class`
1. Press `Down` arrow.

**Expected Results**
The current cell is saved as `Class` and the active cell moves one cell down.

**Actual Results**
The up and down arrow keys have no effect.

**Additional Details**
1. Start Excel or OpenOffice Calc
1. Edit a cell.
1. Press the `Down` arrow key.

The editor leaves edit mode and moves the active cell one cell down.

**Comment by pphod** [comment]
This is already available in the last commit to the master repo.
