### ISSUE TITLE
is it possible to set cell has dropdown alone?

### ISSUE THREAD

**Issue by benci042** [jspreadsheet/ce#1143]
Hello there,
I'm using jexcel V4, and I'm wondering if there is way to change some cell has dropdown only?

jexcel(document.getElementById('my-spreadsheet'), {
    data:data,
    columns:[
        { title:'Model', width:300 },
        { title:'Price', width:80 },
        { title:'Model', width:100 }
    ]
});

such as A2 can be using dropdown function. thanks.

**Comment by an-amin** [comment]
This feature is very much needed.
And `Data Source` is only working in column level, need row level support as well.

**Comment by pphod** [comment]
This feature is available on the JExcel Pro v5+

jexcel(document.getElementById('my-spreadsheet'), {
data:data,
columns:[
{ title:'Model', width:300 },
{ title:'Price', width:80 },
{ title:'Model', width:100 }
]
cells: {
   'A1': { type:'dropdown', source:['Apples','Pear'] }
});

Real time example:
https://jexcel.net/v7/cases/payment-calculator
