### ISSUE TITLE
Dropdown column filter

### ISSUE THREAD

**Issue by jamesargent-contexcity** [jspreadsheet/ce#1146]
Is it possible to add some sort of pre-loaded filter for the dropdown column? I have the following situation:

Two dropdown columns:
- Group
- Objects with a group ID

I save my data to a database and display this in a jexcel table.

I can filter the objects column when a group is selected as shown in the documentation. However what I need to do is load only the right objects based on the group when the page first loads. For example something like this:

{ type: 'dropdown', url: 'json/objects/groupID=<the id of the group in the previous column>'.

At the moment I can only specify a single group ID for the column, for example:
{ type: 'dropdown', url: 'json/objects/groupID=1'.

As far as I can tell the dropdown url is set on a column basis. Is it possible for this to work on a row by row basis?

**Comment by pphod** [comment]
I have a impression that the conditional dropdown on the page below might help you.
https://bossanova.uk/jexcel/v4/examples/dropdown-and-autocomplete
