### ISSUE TITLE
Search / filtering bug

### ISSUE THREAD

**Issue by adidottxt** [jspreadsheet/ce#1147]
Hi there -- I'm using the search option within my jexcel table and found a potential bug. This is reproducible with the table in the datatables example [here](https://bossanova.uk/jexcel/v4/examples/datatables).

This is the first page:

![Screenshot from 2020-09-18 13-44-19](https://user-images.githubusercontent.com/29982667/93629128-c94ec180-f9b5-11ea-958e-2865631899aa.png)

If I wanted to, say, remove all rows with exchange NYQ, my first step would be to search for NYQ, which gives me this:

![Screenshot from 2020-09-18 13-44-32](https://user-images.githubusercontent.com/29982667/93629149-cf44a280-f9b5-11ea-931e-1ceb345ed107.png)

![Screenshot from 2020-09-18 13-44-48](https://user-images.githubusercontent.com/29982667/93629160-d23f9300-f9b5-11ea-885d-d0d11cb07763.png)

Once I select all, right click, and hit delete, it becomes clear that rows _in between_ the first row with NYQ and the last row with NYQ, even if they do not have the same exchange, are deleted as well (for example, Amazon and Alphabet are now missing despite not having NYQ in their row):

![Screenshot from 2020-09-18 13-48-20](https://user-images.githubusercontent.com/29982667/93629172-d966a100-f9b5-11ea-850b-5650aa27c41b.png)

Essentially the search bar seems to do a filter only visually, but it does not _actually_ filter the rows down to the point where anything useful can be done in bulk with said rows. I know there's an open issue WRT this [here](https://github.com/paulhodel/jexcel/issues/732), wondering if this will be implemented soon? As it stands it seems like the search bar is only useful to look for specific rows, but not to do anything with said rows.

Thanks!

**Comment by pphod** [comment]
In future releases this the behavior expected should be included. Currently, the behavior you are expecting is part of the Pro distribution only (www.jexcel.net).

**Comment by zehguilherme** [comment]
Has this behavior already been added?
