### ISSUE TITLE
Can we integrate Vuejs custom component in the jexcel cell

### ISSUE THREAD

**Issue by VivekSharmaTechM** [jspreadsheet/ce#1149]
I have created a vuejs custom component now I want to integrate it in jexcel cell. Can you please guide how we can do this

**Comment by klren0312** [comment]
like this ? https://bossanova.uk/jexcel/v4/examples/column-types
![image](https://user-images.githubusercontent.com/10903843/93962308-26b78980-fd8d-11ea-9d0d-743cbd5e3524.png)
