### ISSUE TITLE
Bug: Undo does not update cell index within the model

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#115]
**Replicate**
1. Visit https://bossanova.uk/jexcel/examples
1. Double-click `Classe B`
1. Change value to `Class`
1. Press `Tab` three times
1. Press `Ctrl+z` to undo
1. Type `T`

**Expected Results**
The visibly activated cell value changes from `Classe B` to `T`.

**Actual Results**
The calendar appears.

![undo](https://user-images.githubusercontent.com/2131950/37381984-6e48a7d4-26fd-11e8-8613-dd37d9812f37.png)

**Additional Details**
Firefox 58.0.2 (64-bit) on Linux.

**Comment by pphod** [comment]
It has been fixed. It will be in the repository later today.
