### ISSUE TITLE
Custom Column Type and Custom Cell in React

### ISSUE THREAD

**Issue by rvieracds** [jspreadsheet/ce#1150]
Hi everyone!

I want to create a spreadsheet with a **custom column type in React** but I can't find in the documentation how to do that. I created a custom component (with some input fields) and I want to open/show it when the user clicks on a cell of the custom column and after the user finish with that, show an image with a text in the cell clicked.

In the documentation there is an example using jQuery, but I want to know if anyone has any example in **React** (preferably using hooks).

Thanks in advance.

**Comment by pphod** [comment]
On CE you have a property editor where you pass the method to handle the editor. A second example on this page can do that, of course, you need to adapt the code to React where is necessary.
https://bossanova.uk/jexcel/v4/examples/column-types
