### ISSUE TITLE
disable the dates in the calendar

### ISSUE THREAD

**Issue by debamishra14** [jspreadsheet/ce#1153]
First of all thanks for this great library. I have been using this for the last two weeks but couldn't find a way to give styles to the calendar, as well as the way to disable the dates. 

@paulhodel is there any way we can disable the dates and give some styles to the calendar with hiding the buttons provided with the calendar.

**Comment by GBonnaire** [comment]
You can see all options of calendar of JExcel on https://bossanova.uk/jsuites/javascript-calendar/valid-range

and for style, use a file CSS for change color, position :
you have lot of class use for calendar : jcalendar, jcalendar-reset, jcalendar-confirm etc.

Use console developper of your JExcel for test and construct new theme CSS for calendar 😉

**Comment by pphod** [comment]
You can see this example on how to do that.
https://jexcel.net/v7/examples/javascript-calendar

**Comment by debamishra14** [comment]
@paulhodel @Guillaume-Bo, I tried with `validRange: [ '2020-09-20', '2020-09-30' ]` but no success. FYI  I am using jexcel where one of my column is of type calendar.
```
{
            type: 'calendar',
            title: 'Due Date',
            width: '250px',
            options: { format: 'DD-MM-YYYY' },
            name: 'endDate',
            validRange: [ '2020-09-20', '2020-09-30' ],
          },
```

**Comment by GBonnaire** [comment]
Try

```
{
            type: 'calendar',
            title: 'Due Date',
            width: '250px',
            options: { format: 'DD-MM-YYYY', validRange: [ '2020-09-20', '2020-09-30' ]},
            name: 'endDate',
          },
```

**Comment by debamishra14** [comment]
yes, @Guillaume-Bo thank you so much, it's working fine now. :+1:

**Comment by DebaPrasad14** [comment]
@Guillaume-Bo Is there any way we can hide the update button in the calendar ?

**Comment by debamishra14** [comment]
It would be better @Guillaume-Bo  if we can bring Reset and done button to the footer level. can we do that? But again thank you so very much for your response and appreciate your quick response.
![image](https://user-images.githubusercontent.com/30753467/94658335-49fbaf00-0320-11eb-8e48-a9c78de9cb53.png)

**Comment by GBonnaire** [comment]
it's not possible with this version of jSuites.

But you can override calendar for make as you want.

Download this file : https://github.com/paulhodel/jsuites/blob/master/src/calendar.js
And add this after file jsuites.js, and change code directory on calendar.js for make as you want 😉
