### ISSUE TITLE
change background color of dropdown elements.

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#1154]
Hi. i have a table like this one: 
![image](https://user-images.githubusercontent.com/55595063/94255165-1b4c9580-ff28-11ea-8876-0685e5b2c059.png)
And i want to set a diferent background color for each flag in the dropdowns of the flag columns.  For example, to the "T" flag,  a blue background, a green for "V", etc.
I tried to follow the following example [https://bossanova.uk/jexcel/v2/examples/table-styling](https://bossanova.uk/jexcel/v2/examples/table-styling) but it use Jquery and have some bugs/error that i was unable to fix. 
i tried to follow the example and got the following error:
![image](https://user-images.githubusercontent.com/55595063/94263906-1858a180-ff36-11ea-9d3d-9483d4ee8bff.png)

Can someone show me a sample on how to change the background color of the dropdown items please ( without jquery) ? Thanks a lot !

( by the way, stackoverflow limits questions to 3 if you dont have reputation and block the user from doing more questions, so this is the only place to get an answer).

**Comment by pphod** [comment]
You should upgrade to v4 (CE) or v7 (Pro). But you can customize the dropdown classes only using CSS. This error is because you are not initiating the table properly, there are tons of examples on how to do that.

updateSettings has been replaced by updateTable on v3+

**Comment by GBonnaire** [comment]
Hi, 

If you use JExcel Pro, you have a plugin for that (conditional style like Excel) : https://repo.gbonnaire.fr/product/jexcel-plugin-conditionalstyle

But for JExcel CE, you can make style like this :

```
var myTableElement = document.getElementById('myTable');

var myTable = jexcel(myTableElement, {
      ... your setting ...
      updateTable: function (instance, cell, col, row, value, label, cellName) {
           if(col==1) { // Col Flag, first col = 0
               if(value == "T") { // Value of cell
                    // here cell is an elementHTML
                    cell.style.backgroundColor = "orange"; // color in hexa or name
               } else {
                   cell.style.backgroundColor = "#FFF"; // Blank
               }
          }
      },
});

// example out of jexcel options
myTable.setStyle('B2', 'background-color', 'orange'); // For set style specifics on cell
```
