### ISSUE TITLE
keys of columns are not coming in getJson()

### ISSUE THREAD

**Issue by debamishra14** [jspreadsheet/ce#1155]
I am working with a table where at the time of initialization there are no data and I am allowing the user to enter data and there is a submit button so once the user clicks on the submit button, I am fetching all the data user entered. But the problem is getJson() doesn't provide me data as key-value pair.

Suppose the user enters data in the 1st and 2nd row then how can I get data as key-value pair? Now if I call getJson() I will be not be getting as required.
@paulhodel @Guillaume-Bo is there any way I can get header title as keys and column value as value? that will be something like {"Car": "Jazz", "Make": "Honda", "Available": "01/01/2019"}

![image](https://user-images.githubusercontent.com/30753467/94279883-5c659980-ff6a-11ea-8158-762e475905b6.png)

**Comment by GBonnaire** [comment]
Hi,

In your initialization of columns, did you set name property of column ? it's necessary for JSON with name for export JSON (or import)

```
columns: [{
            type:'text',
            title: 'Car',
            width:'200',
            name:'Car'
        },
        {
            type:'text',
            title: 'Make'
            width:'200',
            name:'Make'
        },
        {
            type:'calendar',
            title: 'Available'
            width:'200',
            name:'Available'
        }],
```
