### ISSUE TITLE
source in the column of type dropdown is not getting assigned

### ISSUE THREAD

**Issue by debamishra14** [jspreadsheet/ce#1156]
I am working with a column of type dropdown and I want to assign the value coming from API to the source of the column, but unfortunately, this is not working.

sample code for reference: (here if I assign productList to the source then it won't work and if I assign a static list then it will work fine.)
I am receiving these productList data in created hook, so is there any way I can achieve this?
```
columns: [
          { type: 'text', title: 'User', width: '250px' },
          {
            type: 'dropdown',
            title: 'Owner',
            width: '250px',
            autocomplete: true,
            multiple: true,
            // source: this.productList,
            source: [
              'apple',
              'banana',
              'Cherries',
              'donuts',
            ],
          },
    ]
```

**Comment by pphod** [comment]
Yes, that should work fine.

**Comment by debamishra14** [comment]
@paulhodel sorry to say it is not working, I have tested it multiple times. so what can I do? I can see clearly data are coming but when I am doing source: this.productList then the dropdown list is not showing

**Comment by pphod** [comment]
You can create a example on codesandbox and share. I am happy to that a look on that.
