### ISSUE TITLE
Cell and RowClick (with Touch partner events mapped also) Events please

### ISSUE THREAD

**Issue by excel-vba-course** [jspreadsheet/ce#1157]
Would be good to have these events officially supported and exposed - any plans ?

Additionally if the amendment to achieve this could be advised until supported, that'd be most appreciated 👍 

Steve

**Comment by GBonnaire** [comment]
Hi,

You have event onselection for cell click, and row click or column click

More information on : https://bossanova.uk/jexcel/v4/docs/events
or here https://jexcel.net/v7/docs/events (Pro version)

onselection support ontouch mobile too

**Comment by excel-vba-course** [comment]
Great thanks Guillaume :-)

Steve
