### ISSUE TITLE
reset jexcel table to the initial state

### ISSUE THREAD

**Issue by debamishra14** [jspreadsheet/ce#1158]
@paulhodel @Guillaume-Bo Is there any way we can do reset or bring the table to the initial state using Vue or any generic method available for that? I was trying to achieve that using setData() but no success. initial state in the sense initial configurations, initial data.

If I reload then jexcel table will come to the initial state otherwise it won'.t

**Comment by deftdawg** [comment]
If you load your data from an external CSV file, then you could delete everything and load it again.  

My guess is data that is inlined is pretty much gone as soon as you start changing it.

**Comment by debamishra14** [comment]
@deftdawg no this is not the case, I am opening this in a modal so when the modal opens up this table is showing, and if I add extra rows or add some data then if I open the modal after closing that modal then still same table comes up (same as old)

**Comment by GBonnaire** [comment]
Hi,

for reset you can use setData but with this param [[]].

`MyTable.setData([[]]);`

After, you can destroy and recreate JExcel : 

```
MyTable.destroy();
MyTable = Jexcel(Element, Options);
```

Or, you can reset each setting manually like remove all Row/Column and Add 10 Row/Column blank

```
MyTable.setData([[]]);
MyTable.deleteRow(0, MyTable.options.data.length);
MyTable.deleteColumn(0, MyTable.headers.length);
MyTable.insertRow(0,10);
MyTable.insertColumn(0,10);
```
