### ISSUE TITLE
Feature request: Insert row after a given row

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#116]
**Replicate**
The following code activates when the user presses the `Insert` key:

``` .javascript
// Insert row after selected cell using the insert key.
document.addEventListener( "keyup", function( event ) {
  if( event.which === 45 ) {
    var cell = $.fn.jexcel.selectedCell;
    var cr = get_coordinates( cell );

    // cr[1] contains the row number for the currently selected cell.
    $(TIMESHEET).jexcel( 'insertRow', 1, cr[1] );
  }
});
```

**Expected Results**
The row is added after the currently selected cell.

**Actual Results**
The row is added to the end of the table.

**Additional Details**
Having a way to insert cells into the middle of the table would be convenient, such as:

``` .javascript
    $(TIMESHEET).jexcel( 'insertRowAfter', 1, cr[1] );
    $(TIMESHEET).jexcel( 'insertRowBefore', 1, cr[1] );
```

**Comment by pphod** [comment]
This feature has been implemented in the new version 1.5.0 (not in the master). We are in test phase... you insert a row, column related to another... with default data in. The insertColumn, insertRow, deleteRow, deleteColumn, and moveRow are now included in the history. Basically, you can undo and redo those changes without reloading the table.
