### ISSUE TITLE
Adding styles to readonly columns dynamically not working

### ISSUE THREAD

**Issue by debamishra14** [jspreadsheet/ce#1161]
I am trying to apply some styles and comments for readonly columns but somehow these styles are not getting applied dynamically. can we add styles to the readonly columns dynamically? 
Thanks.

some lines of my code are-
```
this.spreadsheet.resetStyle([F1]);
this.spreadsheet.setComments(F1, '');
if (success) {     // value of success comes from API
   this.spreadsheet.setValue(F1, 'S', true);
   this.spreadsheet.setStyle({
     F1: 'font-weight:bold; color:green;', //not working
   });
   this.spreadsheet.setComments(F1, 'Success');
}
```
cc: @Guillaume-Bo  @paulhodel

**Comment by GBonnaire** [comment]
try

```
this.spreadsheet.setStyle("F1", "font-weigh", "bold");
this.spreadsheet.setStyle("F1", "color", "green");
```

if that work, try

`this.spreadsheet.setStyle({'F1': 'font-weight:bold; color:green;'});`

**Comment by GBonnaire** [comment]
With option : i don't know.

But with CSS yes
you can try this with this CSS to add on your page : 

```CSS
.jcalendar .jcalendar-controls {
     display: none;
}
```

**Comment by debamishra14** [comment]
> this.spreadsheet.setStyle("F1", "font-weigh", "bold");
> this.spreadsheet.setStyle("F1", "color", "green");

yes this one is working but if I do like the second approach then it is not working.
