### ISSUE TITLE
Bug: Dropdown not working properly in Firefox

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#1163]
Dropdown items are not showing properly in Firefox. 
![image](https://user-images.githubusercontent.com/55595063/94784101-f3e54500-03cd-11eb-8d83-a7dfa2b51a73.png)
I thought my "updateTable" function was wrong, but after commenting it, I saw that the problem still remained.
It's a big project with Vue and it doesn't give me any kind of error. I honestly don't know where to look or what it could be. Any guidance on where to look would be helpful. ( i used the most updated version of Firefox, Chrome and Edge ).
this is my table object:
```
{

            columns: [],
            data: [],

            tableHeight: '100%',
            tableWidth: '100%',
            tableOverflow: true,
            loadingSpin: true,
            columnSorting: false,
            updateTable: function (instance, cell, col, row, value, label, cellName) {

                for (const key in enviraConfig.flags.flagColorList) {
                    if (key === value) {
                        cell.style.backgroundColor = enviraConfig.flags.flagColorList[key];
                        console.log('cell color:',cell.style.backgroundColor);
                        if (cell.style.backgroundColor === 'rgb(0, 0, 0)') {
                            cell.style.color = 'white';
                        }else{
                            cell.style.color = 'black';
                        }
                        break;
                    }
                }  
            }
        }
```

there you have my [full project](https://codesandbox.io/s/mystifying-curran-reome?file=/src/assets/js/enviraConverter.js).

EDITED:
After several hours of research, I have located the problem in the CSS "overflow" property of ".jdropdown-description". With "hidden" or "auto", the value disappears (only in Firefox). With other values it works. Can you tell me how I can fix this in javascript?

![image](https://user-images.githubusercontent.com/55595063/94810407-40dc1200-03f4-11eb-9427-ae476b33c86d.png)

**Comment by pphod** [comment]
Hi,

I tried to access your project but was not able. But I have the impression that is a problem in the font color. Here is a screenshot of the dropdown working fine on FF.

![image](https://user-images.githubusercontent.com/6019713/95376749-76dc3300-08d9-11eb-8602-7ee7c8d60142.png)


If you send more instructions on how to access your code I am happy to take a look.

**Comment by ghost** [comment]
i tried the link i sent you and it worked. The only thing that doesnt work is the backend Rest service because codepen dont let me upload all this stuffs.  
You say that the problem can be in the font color, can you tell me how to manually set this?
Its pretty weird that eveythin works fine everywhere except Firefox.

**Comment by pphod** [comment]
Add in your CSS:
.jdropdown { color:#000 !important; }

**Comment by ghost** [comment]
still doesnt work. T_T
![image](https://user-images.githubusercontent.com/55595063/95972776-24d46980-0e13-11eb-91cc-0e02aade06b8.png)
also tried:
`.jdropdown-description {
  color: #000 !important;
}`
and
`.jdropdown-description {
  overflow: visible;
}`
and
`.jdropdown-description {
  overflow:visible !important;
}`
and 
`.jdropdown-item {
  overflow:visible !important;
}`
and
`.jdropdown-item {
  color: #000 !important;
}`
