### ISSUE TITLE
How can we use If condition ? any example or jsfiddle would do sir

### ISSUE THREAD

**Issue by SujinRajak** [jspreadsheet/ce#1164]
Hello sir, thank u for bringing such an amazing javascript plugin into use, sadly i am facing reference loop error.. it seems that in the formula we cant reference the same cell two times... i.e while executing the if formula i have caught this reference loop error
eg: =IF(V1>X1,X1*R1,V1*R1)
        in this formula V1 and X1 is checked once in the execute formula and then it is again checked then it gives referencee loop error 
is there any fix sir?

**Comment by GBonnaire** [comment]
Can you give more information like :

- V1 content
- X1 content
- R1 content 

or example on jsfiddle ?

**Comment by SujinRajak** [comment]
Thank u For replying sir , i solved the following issue by getValue sir took V1 content and X1 content and did comparision then applied the formula sir
