### ISSUE TITLE
Sheets Selection

### ISSUE THREAD

**Issue by excel-vba-course** [jspreadsheet/ce#1165]
Hi,

What would be the way to determine which sheet (aka tab) is actually the currently selected one ?

I guess I could use onClick for the sheet (aka tabs) buttons but would be good if there was something from the control which occurred when the newly selected one had been rendered.

Any ideas ?

Thanks,
Steve

**Comment by GBonnaire** [comment]
On version Pro : you can use :

`jexcel.current.getWorksheet()`

on version CE, you can get with querySelector

```Javascript
var tab = document.querySelector(".jexcel_tabs .jexcel_tab_link.selected");
var tabId = tab.getAttribute("data-spreadsheet");
```
