### ISSUE TITLE
Download as xlsx file

### ISSUE THREAD

**Issue by pablosolar** [jspreadsheet/ce#1168]
Hello, 

Is it possible to download the table as xlsx file? I am currently using:

csvFileName:'filename',
csvHeaders:true,

but I didn't found anything for xslx.

Thanks in advance!

**Comment by pphod** [comment]
Hi Pablo,

Jexcel does not export to excel natively. So, you need to use a backend service or a frontend plugin.

We are offering some services (free and paid) on https://jexcel.net/

In this example, you can create an export using Jexcel.net services, which is currently free.
https://jsfiddle.net/paulhodel/1zf82mj6/

Regards,

**Comment by pablosolar** [comment]
Hello Paul,

Thank you for your quick response

The truth is that I am very interested in the functionality of several tabs in the same spreadsheet.

Is this functionality free ?? In the event that it is not, how much does it cost? I have not found the prices for any site on the web.

Thank you very much!
