### ISSUE TITLE
Is there an event handler for handing comments? i.e onCommentInsert, or onCommentUpdate

### ISSUE THREAD

**Issue by rawandhawez** [jspreadsheet/ce#1169]

**Comment by GBonnaire** [comment]
Not currently

**Comment by pphod** [comment]
This will be included in the next release in all distributions.

**Comment by pphod** [comment]
That has been added to the Pro distribution and should be brought to the CE eventually.

**Comment by rawandhawez** [comment]
> That has been added to the Pro distribution and should be brought to the CE eventually.

@paulhodel , Perfect, I can access ```oncomments``` event in both Pro and CE distributions.
May I suggest including **col number** and **row number** in the callback.

**Comment by hodeware** [comment]
You can extract that based on the cellName. That is because the event can return multiple columns. ;)
