### ISSUE TITLE
Edit table column header by using on click event

### ISSUE THREAD

**Issue by cosmomathieu** [jspreadsheet/ce#117]
Hi, after looking at the documentation I could not find a way to add a click event to the table header columns. What I'm hoping to achieve is click on header title to trigger a `prompt()` with a text field to rename the column title.

Something like this perhaps: 
```
$('#my tr td:first-child').click(function() {
  var headerId = $(this).attr('id').replace('col-', '');
  $('#my').jexcel('setHeader', headerId, prompt('Column title'));
});
```

Is there a callback that I could tie into after JExcel runs? It would be great if this feature already existed.

Thanks!

**Comment by pphod** [comment]
We have decided not to include this feature in a native version. We have already the click in the header to select all cells in that column, the double click will reorder the column. So, in our option it will create confusion to the user. I guess your case should be treated as an exception and your workaround should work fine for your case.

**Comment by cosmomathieu** [comment]
Is there a callback that I could tie into? Or an event I could listen for, in order to trigger my own function?
