### ISSUE TITLE
Copy paste dropdown value names having key value pair

### ISSUE THREAD

**Issue by dollychhabriya** [jspreadsheet/ce#1170]
Is this possible to paste the name of the dropdown having key value pair. 
For eg I have a dropdown with options as [{id:1,name:'black'},{id:2,name:'white'}] 
I want to paste white and jexcel should automatically select the value currently it is not working but if I am pasting an id it is working but it should also work with name as well. Is there a way to achieve this?

**Comment by pphod** [comment]
That is an available feature on the Pro distribution. It should be included in the CE in future releases.
