### ISSUE TITLE
Issue with jexcel filter, filter dropdown is showing id instead of name for column type dropdown

### ISSUE THREAD

**Issue by dollychhabriya** [jspreadsheet/ce#1172]
For jexcel column filters, The filter is showing ids instead of name for the dropdowns having key value pair but for filtering I want to show names in column filters. Can you please help me achieve this?

**Comment by pphod** [comment]
Did you have a chance to try that on the Pro distribution? I understand you have sent a question, and the major of those are already features of the Pro.

**Comment by dollychhabriya** [comment]
Yes I tried this on pro distribution itself but that is not working over there

**Comment by dollychhabriya** [comment]
Yes I did tried this on pro version itself but that didn't work.

**Comment by pphod** [comment]
I have just tested on both distributions and both seem to be working fine. Are you working on the most recent versions?

if you wish to create a jsfiddle and send me, I am happy to take a look.
