### ISSUE TITLE
Jexcel table loses ability to re-size columns

### ISSUE THREAD

**Issue by jamesargent-contexcity** [jspreadsheet/ce#1175]
Follow these steps.

1) Page loads, I can re-size columns.

2) Click on page outside of the table. Hover on/between columns where you expect to be able to re-size the column(s).

The ability to re-size the columns is missing. You can only get this back by selecting a cell within the table.

**Comment by pphod** [comment]
Actually, the cursor is not changing when the table loses the cursor, but you can resize it. That has already been fixed on the Pro distribution (www.jexcel.net), and it would be included in the next version of Jexcel CE.
