### ISSUE TITLE
表格复制跳转到顶部

### ISSUE THREAD

**Issue by znh0503** [jspreadsheet/ce#1179]
当在ie执行单元格copy操作时，网页会回到顶部，我应该如何解决呢

**Comment by GBonnaire** [comment]
in english please ?

**Comment by pphod** [comment]
我無法重現相同的行為。我建議您更新瀏覽器和最新軟件。

**Comment by znh0503** [comment]
> 我無法重現相同的行為。我建議您更新瀏覽器和最新軟件。

IE浏览器才会，可能是不兼容，但我的项目是老项目需要IE支持

**Comment by znh0503** [comment]
> in english please ?

https://github.com/paulhodel/jexcel/issues/980#event-3867743766  
here.
