### ISSUE TITLE
Feature request: Add row over and/or under

### ISSUE THREAD

**Issue by felixvandal** [jspreadsheet/ce#118]
Hello Paul!
We talk last year about a feature to add row over and under a selected row.
Is this feature still in your road map?

**Comment by ghost** [comment]
Duplicate of #116 ?

**Comment by pphod** [comment]
We are working in a new version will be released in the next few weeks. It will have that feature, I will let you know as soon as available.

**Comment by freizag** [comment]
Brilliant - will this work if there is a formula in any of the cells too? That would elevate you to hero status.

**Comment by pphod** [comment]
This feature has been implemented in the new version 1.5.0 (not in the master). We are in test phase... you insert a row, column related to another... with default data in. The insertColumn, insertRow, deleteRow, deleteColumn, and moveRow are now included in the history. Basically, you can undo and redo those changes without reloading the table.
