### ISSUE TITLE
how can I change de row index by my item id from server?

### ISSUE THREAD

**Issue by joneldiablo** [jspreadsheet/ce#1180]
Hi!! 
good day!
I have some question:
how can I change de row index by my item id from server?
ej.
```
|   ||   name  |  price | 
------------------------------
| 1 ||    X    |  20.00 |
| 2 ||    Y    |  22.00 |
| 3 ||    Z    |  30.00 |
| 4 ||    A    |  25.00 |

```

I want to change 1, 2, 3, 4 ...... 
for 20,45, 87.....
something like that, those are the IDs of my items, is it possible?

------------------

and other question, its possible refer to another cell with custom name?
ej
the column *B* is renamed by *"Price"*, and in column *C* I have this formula: `=5*B1`
its possible refer to *B1* with the "alias" `=5*{Price}1` or something like that?

------------

even better, if the row index could be changed, can I refer to a cell with the new index/id and column alias? ej. `=5*{Price}23` (if row 1 becomes to 23 id)

**Comment by GBonnaire** [comment]
If you use jExcel pro, you can use this plugin : https://jexcel.net/plugins/rowheaders

**Comment by GBonnaire** [comment]
whenever,

hideIndex and use an other column ?

```Javascript
myTable = jexcel(element, {
   column: [
     {title: "index", type:"hidden"}, // For Id
     {title:"name"},
     {title:"price", type:"number"},
   ],
   data:[[/*your data*/]],
};
myTable.hideIndex();
```

**Comment by pphod** [comment]
You have access to the index:

instance.rows[rowNumber].id = updateYourId.

Or on Pro

instance.setRowId(y, id);
