### ISSUE TITLE
Disable toolbar items

### ISSUE THREAD

**Issue by krisz168** [jspreadsheet/ce#1186]
Hi Paul! 

My app will be used by  different users with different privileges,  editing function not enabled for "simple" user. 
Is it possible to disable some elements on toolbar and/or  disable context menu? 
Thanks :-)

**Comment by GBonnaire** [comment]
Yes: example on this page :

https://bossanova.uk/jexcel/v4/examples/contextmenu

https://bossanova.uk/jexcel/v4/examples/spreadsheet-toolbars
