### ISSUE TITLE
how to show a local image in jexcel column?

### ISSUE THREAD

**Issue by smishra11** [jspreadsheet/ce#1188]
Hi, I am just using jexcel table and want to show local images dynamically based on some condition, I have gone through some examples where base64 images are used there so how can I use a local image (path will be like /assets/image/tick.png)

@paulhodel

**Comment by pphod** [comment]
Using type: 'image' you can load images from your local computer to jexcel.

**Comment by smishra11** [comment]
Hey @paulhodel plz don't close from ur side bcoz my issue is not solved
yet. Whatever u understood based on that u closed this.

My concern was how can I  set value of a column dynamically where column type is Hidden. I am using setValue() but couldn't find a way to add image from my local project folder dynamically.
And the value i want to set is a image. So plz look into it.

**Comment by pphod** [comment]
You do a script to load the file from the machine and use setValue to add the based64 to the hidden column. That is outside the jexcel scope since you cannot resolve that using jexcel.

**Comment by pphod** [comment]
The direction would be: create an external <input type='file'> and add onchange to it: onchange = function(e) {
            var reader = new FileReader();
    
            reader.addEventListener("load", function () {
                yourtableinstance.setValue('A1', reader.result);
            }, false);
    
            reader.readAsDataURL(this.files[0]);
        }
