### ISSUE TITLE
Is there a way where we can specify each cell type as calendar specific to data ?

### ISSUE THREAD

**Issue by SweetyKothari** [jspreadsheet/ce#119]
Hi ,

Is there a way where we can specify each cell type as calendar specific to data ?
Also is formula supported for date cell type ?
=E3+1  //date will get increment by 1

**Comment by pphod** [comment]
No, this is not supported  by jexcel.

**Comment by pphod** [comment]
Alternative 1
https://jsfiddle.net/paulhodel/03d5rhzo/

Alternative 2
https://jsfiddle.net/paulhodel/wk8kq4r5/7/

You can create you custom methods:

=customMethod(A1)

function customMethod(cell)
{
    // your operations with cell
}
