### ISSUE TITLE
Can you please add an example for month and year picker using custom column type

### ISSUE THREAD

**Issue by dollychhabriya** [jspreadsheet/ce#1191]
Can ypu please create a new example for custom column type which opens month and year picker.

**Comment by pphod** [comment]
Are you using CE Or PRO distribution?

**Comment by dollychhabriya** [comment]
I am using pro distribution

**Comment by dollychhabriya** [comment]
I am using pro distribution

**Comment by pphod** [comment]
We don't have an off the self which does that. But, we are working to implement that on the jSuites. If you need that sooner you can integrate any JS plugin to create a custom column:

https://jexcel.net/v7/examples/custom-column-type

The best way to request technical support on Pro: contact@jexcel.net

**Comment by GBonnaire** [comment]
On version Pro you have an custom editor for date, datatime or time : https://repo.gbonnaire.fr/product/jexcel-editor-date

maybe can help you

**Comment by pphod** [comment]
There are new options on Jsuites calendar picker.
