### ISSUE TITLE
change readonly property dynamically when onselection is ran.

### ISSUE THREAD

**Issue by cybertron288** [jspreadsheet/ce#1195]
I am using jexcel v4. i want to make whole row readonly when any particular cell is selected from that row and again want to make that editable when that cell is selected. I found the way to make row read only and found onselection event but i am not able to link both of them, i tried storing y position using onselection and using it to UpdateTable property to make it readonly and tried making new function with same sheet and after selecton i am calling it at so it will pass updateTable value what i selected  but it is showing error in console that whatever function i created that is not function so both of them doesn't seem to work. is there any way to do this and make this work.

**Comment by GBonnaire** [comment]
Can you create a jsFiddle for see your code ?

**Comment by cybertron288** [comment]
Yes sure, Give me some time I started working on something else as soon as done with that I will create it.
