### ISSUE TITLE
Issue with column filter in pro version

### ISSUE THREAD

**Issue by dolly-chhabriya-altius** [jspreadsheet/ce#1196]
Issue with column filters with the pro version. If there is pagination allowed than the filter for drop down column type is showing id for page 2 rows when I am on page 1 and if I change the page no to page 2 than its showing names. Attaching some screenshots and sample code
![Screenshot from 2020-10-20 18-12-52](https://user-images.githubusercontent.com/56764298/96587461-fddcd280-12ff-11eb-8717-953bca61031e.png)
![Screenshot from 2020-10-20 18-12-47](https://user-images.githubusercontent.com/56764298/96587474-003f2c80-1300-11eb-97d3-c7f85c6ee320.png)

Below is the sample code:

        var dataArr = []
        dataArr[0] = ["2020-10-01", 1];
        dataArr[1] = ["2020-11-01", 1];
        dataArr[2] = ["2020-12-01", 1];
        dataArr[3] = ["2020-01-01", 1];
        dataArr[4] = ["2020-02-01", 1];
        dataArr[5] = ["2020-03-01", 1];
        dataArr[6] = ["2020-04-01", 1];
        dataArr[7] = ["2020-05-01", 1];
        dataArr[8] = ["2020-06-01", 1];
        dataArr[9] = ["2020-07-01", 1];
        dataArr[10] = ["2020-08-01", 2];
        dataArr[11] = ["2020-09-01", 2];
        dataArr[12] = ["2020-10-01", 1];
        dataArr[13] = ["2020-11-01", 2];
        dataArr[13] = ["2020-12-01", 2];

        var options = {
            data: dataArr,
            columnDrag: true,
            columns: [
                { title: 'date', type: 'calendar', options: { format: "MON-YY" }, width: 85 },
                { type: 'dropdown', title: 'type', source: [{ id: 1, name: 'actual' }, { id: 2, name: 'forcast' }], width: 100 },
            ],
            pagination: 10,
            paginationOptions: [10, 25, 100],
            search: true,
            columnSorting: true,
            tableOverflow: true,
            wordWrap: true,
            allowInsertColumn: false,
            allowManualInsertColumn: false,
            allowDeleteRow: true,
            allowManualInsertRow: false,
            allowExport: false,
            copyCompatibility: true,
            filters: true,
            onchange: this.changed,
            license: 'YjQzMzdlOTRiOGY3ZTQ0ZDQ4ZTI1YWU3MDFjMDI0ZWJmOTNjODA1NWFiZTRiNDJhNmRiYTJlZjkwODQ3N2IwMWRmNWRjYWUwZDViM2VhMmI3NzVjOTcwMzVlN2ZhODI1Y2EyMmE3NDI0ZmE0ZjVmNGQ2MWEzN2M3MTA4MThhMDUsZXlKdVlXMWxJam9pY0dGMWJDNW9iMlJsYkNJc0ltUmhkR1VpT2pFMk16SXdPVEkwTURBc0ltUnZiV0ZwYmlJNld5SnFjMlpwWkdSc1pTNXVaWFFpTENKcVpYaGpaV3d1Ym1WMElpd2lZMjlrWlhOaGJtUmliM2d1YVc4aUxDSnFjMmhsYkd3dWJtVjBJaXdpTVROemQyMHVZM05pTG1Gd2NDSXNJbXh2WTJGc2FHOXpkQ0pkTENKd2JHRnVJam9pTXlKOQ==',
            editable: true
        }
        this.el = jexcel(document.getElementById("consumptionTable"), options);

**Comment by pphod** [comment]
That has been fixed.
