### ISSUE TITLE
Can we use icon along with text in header

### ISSUE THREAD

**Issue by VivekSharmaTechM** [jspreadsheet/ce#1198]
Hi,

Can we use icons along with text inside headers in jexcel. I have added <span style="float:right;"><i class="fa fa-toggle-on"></i></span> inside td in innerhtml but icons or image nothing works there. Can you suggest how can we add an icon next to the header text.

**Comment by pphod** [comment]
stripHTML: false  works to prevent innerHTML. So, you can use external references.

yourInstance.headers[columnNumber].innerHTML = xx
