### ISSUE TITLE
Is there any way we can add tooltip to the disabled dates in jcalendar (jexcel column type calendar)

### ISSUE THREAD

**Issue by smishra11** [jspreadsheet/ce#1199]
Hi I am using jexcel and trying to add one message in the tooltip on the disabled dates in the jcalendar, so is there any way we can do that ? Any hacky solution or any suggestion will be highly appreciated.
@Guillaume-Bo @paulhodel @CyrilKrylatov @tylerchen

**Comment by GBonnaire** [comment]
With options of calendar, currently no.

But, you can get all elements with this selector on onopen event of jCalendar
`.jcalendar td.jcalendar-set-day.jcalendar-disabled`

For example for CE :

```HTML
<html>
<script src="https://bossanova.uk/jexcel/v4/jexcel.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jexcel/v4/jexcel.css" type="text/css" />

<script src="https://bossanova.uk/jsuites/v3/jsuites.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jsuites/v3/jsuites.css" type="text/css" />

<div id="spreadsheet"></div>

<script>

jexcel(document.getElementById('spreadsheet'), {
    minDimensions:[3,3],
    columns: [
        { type: 'text', title:'Price', width:'200px' },
        { type: 'numeric', title:'Qty', width:'200px' },
        { type: 'calendar', title:'Date', width:'200px', 
           options: {
              format: 'DD-MM-YYYY',
              validRange: ['2020-10-20', '2020-10-31'],
              onopen: function() { // Is called on open calendar
              	  var AllDaysDisabled = document.querySelectorAll(".jcalendar td.jcalendar-set-day.jcalendar-disabled");
                  for(i_day=0; i_day<AllDaysDisabled.length; i_day++) { // ForEach Day							 
                      AllDaysDisabled[i_day].setAttribute("title", "Not in valid range");
                  }
              }
            },
        },
     ],
});

</script>
</html>
```

**Comment by smishra11** [comment]
@Guillaume-Bo How is it working? can you plz explain a bit as you are setting the title attribute but how can it show in a tooltip?

**Comment by smishra11** [comment]
Thank you so much, awesome @Guillaume-Bo this is what I needed.

**Comment by smishra11** [comment]
@Guillaume-Bo this is working only for the current month. But if I go to next or previous month's then the tooltip is not showing. 🤔

**Comment by pphod** [comment]
If you have the most recent version, you can use onupdate

**Comment by smishra11** [comment]
Hey, @paulhodel it's not working. can you plz give an example of how can we use it as I am using jexce/4.4.1 I can see onupdate() triggers when we click on any date valid dates? FYI I'm experimenting with it but found a lot of bugs.
@Guillaume-Bo any comment on it?

**Comment by pphod** [comment]
There is no native implementation for that. You need to manipulate the DOM to include that.
