### ISSUE TITLE
How to select the columns which contain values when click on header to select whole columns ? 

### ISSUE THREAD

**Issue by gulshan-escalon** [jspreadsheet/ce#12]
As you asked me to add the minDimensions feature to pre populated some columns , so I added but I am facing a single problem, when try to click on the header to select whole columns then the range of selection contain the blank cell also
**For Exm . suppose I have 3 items in a first three columns and I have setup the minDimensions of [10,10] then if I click on the header it select or highlight 10 cells which is incorrect it should highlight 3 cells selected which contains the values . If you can do the solution for me , it would be appreciable.**

**Comment by pphod** [comment]
This is the correct behaviour. If you would like filter the blank options you should get rid of the nulls on the back end side of it.
