### ISSUE TITLE
How to modify table data before exporting CSV

### ISSUE THREAD

**Issue by znh0503** [jspreadsheet/ce#1204]

**Comment by znh0503** [comment]
I want to deal with scientific counting

**Comment by pphod** [comment]
You implement your own method. You can getData, then process the data and create the CSV file.

**Comment by znh0503** [comment]
> You implement your own method. You can getData, then process the data and create the CSV file.
> 
> 您可以实现您自己的方法，您可以获得数据，然后处理数据并创建 CSV 文件。

jexcel own ctrl+s to export csv,How to modify table data before ctrl+s
