### ISSUE TITLE
Context Menu Not working in IE11

### ISSUE THREAD

**Issue by rjmmc** [jspreadsheet/ce#1205]
When i am selecting the option from context menu like Insert Row, Insert Column or anything, nothing is happening in the grid in IE11, however same code is working in Chrome

**Comment by pphod** [comment]
a) I have opened: https://bossanova.uk/jexcel/v4/
b) Right click in any cell. It seems to be working fine for me.

**Comment by rjmmc** [comment]
Hi Paul,

Context menu opens whenever clicked on any cell perfectly in IE as well, however it does not perform the selected action.

**Comment by rjmmc** [comment]
> a) I have opened: https://bossanova.uk/jexcel/v4/
> b) Right click in any cell. It seems to be working fine for me.

Context menu opens whenever clicked on any cell perfectly in IE as well, however it does not perform the selected action.

**Comment by pphod** [comment]
I am able to perform the actions. Not sure what happened on your side. Are you trying that on your environment or the website?

**Comment by rjmmc** [comment]
Could you please share an working example where on selecting an item from the context menu the desired action is performed like insert row, because on click of the item it is not firing the on click event. So if you could provide an working example where the on click event is triggered in IE 11 would be really helpful.

**Comment by pphod** [comment]
I have just tested
https://bossanova.uk/jexcel/v4/examples/import-data

It is including executing all options from the contextMenu. Not sure what happens on your side. Any error in the console?

**Comment by rjmmc** [comment]
I have just tried the same URL, sorry but it is not working on IE 11 for me. I have tried on couple of machines. When i have selected the insert new row before option nothing is happening

**Comment by pphod** [comment]
Yes, just test it again, and seems to be working fine on our side.
![image](https://user-images.githubusercontent.com/6019713/97319038-67129780-1864-11eb-9eb0-d52013e61728.png)

Sorry, but without more information, there is not much we can do. I would suggest you update your browser to a more recent one considering Microsoft deprecated IE and the support is no longer provide.

**Comment by rjmmc** [comment]
i am using the below version of IE

![image](https://user-images.githubusercontent.com/73520797/97399017-486ada00-1912-11eb-997f-7742a1e47d0f.png)


As you could see in the background i was suing the same URL which you have provided (Import-data one) . It is not even working on that

**Comment by rjmmc** [comment]
[jexcelcontextmenu.zip](https://github.com/paulhodel/jexcel/files/5450145/jexcelcontextmenu.zip)
Hi

I have attached the file, i have copied the file from the URL which you have shared earlier (https://bossanova.uk/jexcel/v4/examples/import-data). This is not working IE11

**Comment by rjmmc** [comment]
Hi Paul,

I need your help mate, we are performing actions on selection of the context menu items.
Context menu is opening in the Internet Explorer, however we are unable to get the action triggered in IE, the same is working in Chrome.
Could you please help us in this.

Regards,
Roman Jain
