### ISSUE TITLE
How to avoid clear the selection on click outside of jexcel

### ISSUE THREAD

**Issue by ceritium** [jspreadsheet/ce#1209]
I would like to add controls apart of the "custom toolbar" but I lost the selection on click outside of the table.

There is any option for that? Thanks.

**Comment by pphod** [comment]
Currently, on the CE, your controls should be inside the DOMElement you initiate. On the PRO distribution, you can have external controls by adding jexcel_object class to the external element. That solution should be brought to future CE releases.
