### ISSUE TITLE
In React implementation, the new instance is added for any change in options value.

### ISSUE THREAD

**Issue by kunalshewale** [jspreadsheet/ce#1211]
In React integration, the code given in the example is used, it keeps on adding new `jexcel` instance on change of options; specifically, on data update within `options`. Please refer to the example on the below link. 

https://codesandbox.io/s/jexcel-and-react-forked-iebp7?file=/src/index.js 

To solve this, I added `this.wrapper.current.innerHTML = '';` as first-line within `useEffect` hook. But, now the styles applied for the changed cell and all the edits made to the cell is lost.

**Comment by pphod** [comment]
A better solution:

if (! this.wrapper.current.innerHTML) {
// them you execute jexcel.
}

**Comment by kunalshewale** [comment]
@paulhodel We have to reinitialise the `jExcel` with respect to updated `options` value. If we use the above solution then it won't serve the purpose as we will never reinitialise the `jExcel` even if the `options` value change.
