### ISSUE TITLE
How to freeze formula footer column.

### ISSUE THREAD

**Issue by kallaguntaashok** [jspreadsheet/ce#1213]
Hi,

I am using the formula footer to display the total sum of the respective column.

code:
footers: [['', '', '', 'Total', '=ROUND(SUM(G1:G' + ic + '),2)', '=ROUND(SUM(H1:H' + ic + '),2)]]
output
![image](https://user-images.githubusercontent.com/26366259/98103055-70ca7980-1eba-11eb-8eb6-7b3a773e6743.png)

The problem is my table is has a fixed height, I use scrollbar to view the remaining rows information, to see the total I have to screen to the bottom of the table and see the total, is there any way I can freeze the footer? 

Please help me

**Comment by GBonnaire** [comment]
Hi

try to add this style on your page 

```CSS
.jexcel>tfoot>tr>td {
    position: sticky;
    bottom: 0;
}
```

**Comment by ricardoperroni** [comment]
Thx!
Work for me.
