### ISSUE TITLE
Where can i find context menu item object structure properties ?

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#1215]
Hi. I would like to know all the properties that exist for the object that is in the context menu. I have looked at the source code, but I have not been able to find where they are declared to know all the ones there are and all their possible configurations.
![image](https://user-images.githubusercontent.com/55595063/98230498-82b02900-1f5b-11eb-96c6-1c57d1fbf86f.png)

**Comment by pphod** [comment]
You can find that information here:
https://bossanova.uk/jsuites/contextmenu/quick-reference
