### ISSUE TITLE
How to modify the selected data of the table from the context menu?

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#1216]
I am trying to modify some selected data from the table. To do this, I have an option in the context menu (for example multiply x2). So what I want to do is retrieve the selected data (each cell with its x-axis, y-axis and value), be able to modify them and put the result in the same position(x,y). I have been looking at how to do that, but I have seen that it is quite complicated since I have not found a method that gives me that full data.

- getjson (): gives me the data, but does not give me the x and y positions.
- selectedCell: it returns me where my selection begins and where it ends, but it does not give me the structure, that is, I have no idea in what order the values are within that selection.

Is there any way to easily recover this data with its positions? Can someone help me on how to do that? Thanks a lot.

**Comment by pphod** [comment]
If you have x1, y1, x2, y2 you can do a loop to get all select cells. Another way is to use getData(true) - this will bring you the data of the selected cells only.

**Comment by ghost** [comment]
I have created the following method that uses various existing JExcel methods to gather the cell data. And what it does is return an array with the selected cells. In each of them comes the information of the X axis. Y axis, title of the column in which it is located and the value of the cell. Hope that helps others. To save the data again in the table you just have to use the method "setValueFromCoords (x, y, value)": 

```
    getCellData(obj) {
        let array = []
        class CellInfo {
            constructor(colHeader, xAxis, yAxis, value) {
                this.colHeader = colHeader;
                this.xAxis = xAxis;
                this.yAxis = yAxis;
                this.value = value;
            }
        }

        let json = obj.getJson(true);
        let selectedRows = obj.getSelectedRows();
      
        for (let i = 0; i < json.length; i++) {

            let y = selectedRows[i].sectionRowIndex; // aquí tenemos el eje y

            for (let [key, value] of Object.entries(json[i])) {

                let header = obj.getHeader(key);
                let c = new CellInfo(header, parseInt(key, 10), y, value)

                array.push(c);
            }
        }
        return array;
    }
```
it returns an array like this: 
![image](https://user-images.githubusercontent.com/55595063/98573602-55df7700-22b7-11eb-920f-4af1bcd96e0c.png)
