### ISSUE TITLE
How to freeze 2nd and 4th column in the table.

### ISSUE THREAD

**Issue by kallaguntaashok** [jspreadsheet/ce#1218]
I am using the Jexcel table, is it possible to freeze the required columns, in my scenario I would like to freeze the 2nd and 4th columns.

![image](https://user-images.githubusercontent.com/26366259/98364848-7f9a6300-2057-11eb-8899-34039dec130a.png)

same time, I would like to freeze the 2nd and 4th column filters to

**Comment by pphod** [comment]
Sorry, that is not possible in none of the distributions.
