### ISSUE TITLE
Search input positioning

### ISSUE THREAD

**Issue by RobinWalmsley** [jspreadsheet/ce#1219]
Hi Paul, 
I bought the Jexcel Pro version last week, and I'm enjoying learning and developing with this great tool.

I have a question about the Search input. It looks like you are positioning this against the right side of the viewport by calculating the width of the viewport. 
I use a static menu on the left hand side of the screen, and so the search input almost disappears off the right of the screen when I resize the viewport.
Is there a way I can offset the search input?
The menu is exactly 200px wide, so I could amend the code to deduct 200 from your viewport width calculation.
I don't mind adjusting your js for my use case, if you can let me know where this is done in the code.

Thanks
Robin Walmsley

**Comment by pphod** [comment]
Hi Robin,

The most straightforward way to customize the search box is using CSS:

The class to access that is: jexcel_filters_search

So, for example change the position:

.jexcel_filters_search {
    margin-left: 200px;
}

There are other ways to do that. The best way to get technical support for Pro is via email: contact@jexcel.net, so if the CSS does not resolve your issue, please let me know and I am happy to suggest other alternative ways.

Best regards,
