### ISSUE TITLE
Disable to create new columns on paste from Excel

### ISSUE THREAD

**Issue by developez** [jspreadsheet/ce#122]
I have a new issue, I don't if this is possible. Is possible to disable the behaviour that creates automatically new columns when user paste cells from excel? Around where is there this behaviour in the code??

(Congratulation of this awesome plugin, this gives easy way to build fast interface that works with excel and nothin more)

**Comment by pphod** [comment]
I am going to include that in the new release is going to be release soon. I will let you know when is ready.

**Comment by pphod** [comment]
You can use the parameter to block new columns from the paste.
allowInsertColumn: false
