### ISSUE TITLE
getConfig() not save event functions

### ISSUE THREAD

**Issue by benci042** [jspreadsheet/ce#1220]
Hi Paul
I need save all info of table .but all the event are "null" (like onchange,onblur)when i got value of getconfig().
is it possbile to get all info of table with same table when i load it .

**Comment by GBonnaire** [comment]
try to use 

`var myConfig = instance.options`

instance is instance of jExcel 

`var instance = jexcel(DOMElement, {...});`

**Comment by pphod** [comment]
You can, but the problem would be if you have methods (references) to save in the database. You might need to save the source code of those methods and convert it back to methods on the frontend. Or, maybe you can save those methods in a different way, so you just call the method references by its name (method names).
