### ISSUE TITLE
headers doesn't download

### ISSUE THREAD

**Issue by adrianbercapeerconcept** [jspreadsheet/ce#1222]
I've set table.download(true); but still the headers don't show in my downloaded table.

Below is some of the code that you might want to see:

		// function to setup table configuration
      function setTableSettings() {
				var onChangeHandler = function(obj, cell, column, row, val) {
					// cut input value to 8 symbols
					val = String(val).slice(0, 8);

					// check if value is number
					if (utils.isNumber(val)) {

						// format value like '00', '000', '0000' to '0'
						if (Number(val) === 0) {
							val = 0;
						}

						// value range should be from 1000 to -1000
						if (val >= 1000) {
							val = 999.9999;
						} else if (val <= -1000) {
							val = -999.9999;
						}

					// if value not number
					} else {
						val = 0;
					}

					// convert value into integer
					val = +val;

					// assign value to table data's in programm and view
					tableInstance.options.data[row][column] = +val.toFixed(4);
					$(cell).html(val);

					updateTotalRow();

					// get the parameters and segments key, to save changes in storage
					var rowKey = tableParameters[row].name;
					var columnKey = tableSegments[column - 1];

					if (!tableStorage[rowKey]) {
						tableStorage[rowKey] = {}
					}

					tableStorage[rowKey][columnKey] = val;
					saveToLocalStorage(tableStorage);

					var tableData = tableInstance.getData();
					tableInstance.updateSelectionFromCoords(1, 0, tableData[0].length - 1, tableData.length - 2);

					// save changed data to cache in service
					var tempData = projectService.getQfactorsTableData().cache;
					tempData[1].parameters.items = tableInstance.getData(true);
					tableInstance.updateSelection(cell, cell);
					projectService.setQfactorsPageOptions({buttonsLock: false});
					EventBusService.publish(EVENTS.qFactors.enableButtons);
				};

				var onUpdateTableHandler = function(obj, cell, column, row, val, label, cellName) {
					var rowNumber = tableItems.length;
					var checkRow = $('.jexcel_row');

					// Format numbers, adding a '%' sign
					if (column > 0) {
						var txt = parseFloat($(cell).text()) + '';

						if (!utils.isNumber(txt) || Number(txt) === 0) {
							txt = '0';
						}

						if (!~txt.indexOf('%') && txt !== '') {
							txt += ' %';
						}

						if (txt.length > 11) {
							txt = parseFloat(txt).toFixed(4);
						}

						$(cell).html(txt);
					}

					// update table style on specific cells
					if (rowNumber === row) {
						$('td[data-y="' + rowNumber + '"]').css('font-weight', 'bold');
						$('td[data-y="' + rowNumber + '"]').addClass('readonly');

						checkRow.css('font-weight', 'normal');
						checkRow.removeClass('readonly');
					}

					if ($(cell).hasClass('readonly')) {
						$(cell).css('color', 'black');
						$(cell).css('text-align', 'center');
						$(cell).css('background-color', '#f3f3f3');
					}

					if (column == 0) {
						$(cell).css('text-align', 'left');
					}

					if (column > 0 && row < rowNumber) {
						$(cell).css('background-color', '#ffffff');
						$(cell).css('text-align', 'center');
						$(cell).css('font-weight', 'normal');
					}
				}

				var onPasteHandler = function(instance, changes) {};

				var onBeforeChangeHandler = function(obj, cell, val) {};

				var tableSettings = {
					data: setTableData(tableItems, tableParameters),
					allowInsertRow: false,
					allowInsertColumn: false,
					allowDeleteRow: false,
					allowDeleteColumn: false,
					allowRenameColumn: false,
					columnDrag: false,
					columnSorting: false,
					columnResize: false,
					csvHeaders: true,
					rowDrag: false,
					contextMenu: false,
					tableWidth: $scope.screenMode === 'lg' ? '1888px': '1140px',
					columns: setColumnSettings(tableSegments),
					colHeaders: setTableHeaders(tableSegments),
					colWidths: setColWidths(tableSegments),
					updateTable: onUpdateTableHandler,
					onbeforechange: onBeforeChangeHandler,
					onchange: onChangeHandler,
					onpaste: onPasteHandler,
				};

				return tableSettings;
      };

// function to setup column widths, default and custom values
			function setColWidths(columns) {
				var defaultColWidth = [290];

				columns.forEach(function(value) {
					defaultColWidth.push(140);
				})
				return defaultColWidth;
			};

			// function to setup column settings, type and format
			function setColumnSettings(columns) {
				var columnSettings = [{
					type: 'text',
					align: 'left',
					readOnly: true
				}];

				columns.forEach(function(value, index) {
					columnSettings.push({
						type: 'numeric',
						align: 'center',
					});
				});

				return columnSettings;
			};

			// function to setup column headers
			function setTableHeaders(columns) {
				var colHeaders = [' '];

				columns.forEach(function(value) {
					colHeaders.push(value);
				});

				return colHeaders;
			};

**Comment by GBonnaire** [comment]
use title property on columnSetting

```javascript
var columnSettings = [{
				type: 'text',
				align: 'left',
				readOnly: true
                                 title: 'Column custom'
			}];
```

like this example:
```
columns: [
        {
            type: 'text',
            title:'Car',
            width:90
        },
        {
            type: 'dropdown',
            title:'Make',
            width:120,
            source:[
                "Alfa Romeo",
                "Audi",
                "Bmw",
                "Chevrolet",
                "Chrystler",
                // (...)
              ]
        },
        {
            type: 'calendar',
            title:'Available',
            width:120
        },
        {
            type: 'image',
            title:'Photo',
            width:120
        },
        {
            type: 'checkbox',
            title:'Stock',
            width:80
        },
        {
            type: 'numeric',
            title:'Price',
            mask:'$ #.##,00',
            width:80,
            decimal:','
        },
        {
            type: 'color',
            width:80,
            render:'square',
        },
     ]
```

**Comment by adrianbercapeerconcept** [comment]
Hi Guillaume,

Thanks for answering me. It still doesn't work.
Below is a screenshot of how my table looks.
Are you able maybe to have a short call, to share my screen and to help me solve this, please?
I'm was struggling with this for few days.
![image](https://user-images.githubusercontent.com/22965875/98844888-a7256d00-2455-11eb-828c-3af6581efffa.png)

This is how my code looks like:

![image](https://user-images.githubusercontent.com/22965875/98845156-f79cca80-2455-11eb-9a3c-20dbee24221b.png)

Thankss,
Adrian

**Comment by GBonnaire** [comment]
Ok verify if you are in last version.

Defined all settings column in property columns: (with, title, type, etc,) and remove all old properties colXXXX (colWidth, colHeaders)

For support, no, if you want this support, buy jexcel Pro v7 and contact paul. Me i help voluntarily when i have a time

**Comment by adrianbercapeerconcept** [comment]
I am at version 4.4.1.
I will pay you for the support hours that you are offering me, I just have to finish this for my client.
I would appreciate a lot if any of you can help me.

Thanks,
Adrian Berca
    On Thursday, November 12, 2020, 10:23:20 AM GMT+2, Guillaume Bonnaire <notifications@github.com> wrote:  
 
 


Ok verify if you are in last version.

Defined all settings column in property columns: (with, title, type, etc,) and remove all old properties colXXXX (colWidth, colHeaders)

For support, no, if you want this support, buy jexcel Pro v7 and contact paul. Me i help voluntarily when i have a time

**Comment by pphod** [comment]
You can define on initilalization:
includeHeadersOnDownload: true

Or instance.download(true);
