### ISSUE TITLE
Bug: submenu onClick going crazy

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#1224]
Good Morning. I have been working with the context menu for a few days and I have encountered some strange behavior. It doesn't give an error, but it behaves strangely. I have implemented a menu to change the "flags" of my table. When I change them, it works perfectly a certain number of times, but suddenly, on a glitch and instead of changing the flags, it selects other cells. This happens randomly. I have debugged and I have seen that the failure does not come from my methods since **it does not even get to enter them** when the behavior fails. So by dismissal, it must be failing the onClick event. Then I put a gif of what it does and I copy the code of my methods. Any help is welcome. Thanks a lot

JExcel version : 4.4.1
In google chrome it fails only sometimes.
In Edge it fails only sometimes.
In Firefox it always fails.

Extra info/updates at the end.

Gif:
![2020-11-11_9-55-183](https://user-images.githubusercontent.com/55595063/98793139-c1385e80-2407-11eb-8670-9d3005784983.gif)
This is my table config object:

```
        // inporting some methods from outside
        let mGetCellData = this.getCellData;
        let mChangeFlagValue = this.changeFlagValue;
        let mIsNumeric = this.isNumeric;

let tableObj = {

            columns: [],
            data: [],

            tableHeight: '100%',
            tableWidth: '100%',
            autoIncrement: false,
            tableOverflow: true,
            loadingSpin: true,
            columnSorting: false,
            freezeColumns: 2,


            updateTable: function (instance, cell, col, row, value, label, cellName) {

                for (const key in enviraConfig.flags.flagColorList) {
                    if (key === value) {
                        cell.style.backgroundColor = enviraConfig.flags.flagColorList[key];

                        if (cell.style.backgroundColor === 'rgb(0, 0, 0)') {
                            cell.style.color = 'rgb(255, 255, 255)';
                        } else {
                            cell.style.color = 'rgb(0, 0, 0)';
                        }
                        break;
                    }
                }
            },
            contextMenu: function (obj, x, y, e) {


                let flagSubmenu = []; 
               
                enviraConfig.flags.allFlags.forEach(flag => {

                    flagSubmenu.push(
                        {
                            title: flag,
                            onclick: function () {
                                mChangeFlagValue(flag, mGetCellData(obj), obj);
                            }
                        }
                    );

                });

                var items = [];
                // Copy
                items.push({
                    title: obj.options.text.copy,
                    shortcut: 'Ctrl + C',
                    onclick: function () {
                        obj.copy(true);
                    }
                });

                // Paste
                if (navigator && navigator.clipboard) {
                    items.push({
                        title: obj.options.text.paste,
                        shortcut: 'Ctrl + V',
                        onclick: function () {
                            if (obj.selectedCell) {
                                navigator.clipboard.readText().then(function (text) {
                                    if (text) {
                                        obj.paste(obj.selectedCell[0], obj.selectedCell[1], text);
                                    }
                                });
                            }
                        }
                    });
                }
                 // Line
                 items.push({ type: 'line' });

                 
                 items.push(
                     {
                         title:'operaciones',
                         submenu:[
                            { title:'Sumar' },
                            { title:'Restar' },
                            { title:'Multiplicar' },
                            { title:'Dividir' }
                         ]
                     }
                 )

                // Line
                items.push({ type: 'line' });
                // Flags
                items.push( //FIXME: Some flags not changing properly
                    {
                        title: 'Flags:',
                        submenu: flagSubmenu
                    }
                );

                // Line
                items.push({ type: 'line' });

                // Save
                if (obj.options.allowExport) {
                    items.push(
                        {
                            title: obj.options.text.saveAs,
                            shortcut: 'Ctrl + S',
                            onclick: function () {
                                obj.download(true);
                            }
                        }
                    );
                }
                return items;
            }

        }
```
There you have some methods i use in the changing flag process:

```
getCellData(obj) { 

        let array = []
        class CellInfo {
            constructor(colHeader, xAxis, yAxis, value) {
                this.colHeader = colHeader;
                this.xAxis = xAxis;
                this.yAxis = yAxis;
                this.value = value;
            }
        }

        let json = obj.getJson(true); // devuelve un array de objetos con ejex y valor
        let selectedRows = obj.getSelectedRows();//devuelve array de filas. Dentro usamos la propiedad sectionRowIndex para el eje Y

        for (let i = 0; i < json.length; i++) {

            let y = selectedRows[i].sectionRowIndex; // aquí tenemos el eje y

            for (let [key, value] of Object.entries(json[i])) {

                let header = obj.getHeader(key);
                let c = new CellInfo(header, parseInt(key, 10), y, value)

                array.push(c);
            }
        }
        return array;
    },
```

```
    changeFlagValue(newValue, cellArray, obj) {

        cellArray.forEach(el => {

            if (typeof (el.value) === "string"
                && isNaN(el.value)
                && isNaN(parseFloat(el.value))) {

                obj.setValueFromCoords(el.xAxis, el.yAxis, newValue);

            }

        });
    },
```
Update 1: 
I just used GIT to go back to a previous point where I have not put the submenus and everything works perfectly. I even use the same methods. The only difference is that I have not placed the flags in the submenus. I suspect that there is some error in the "onclick" event when I put the flags in a submenu. I attach a gif to show you that when i dont use "submenu" it works fine:
![Untitled Project](https://user-images.githubusercontent.com/55595063/98802513-b683c680-2413-11eb-8fa5-3b717ae1843d.gif)

**Comment by GBonnaire** [comment]
Hi,

I try to reproduct error, but with Chrome and Firefox i don't success reproduct.

A problem showed in your exemple do not stop propagation of click and Jexcel keep click for him before context.

the question is why.. maybe because windows considere is out of contextmenu ? Can you test with exclusive flag on bottom of submenu. but is it more present ?

i try on other PC for try to reproduct error

**Comment by GBonnaire** [comment]
Ok i reproduct error on all navigator : 

When you keep mouseup (only on submenu) make this behavior.

Now i search how fix that 😊  

next soon :+1:

**Comment by GBonnaire** [comment]
i find a fix

i have create a PR for fix that on contextmenu 😉 

Wait and see 😊   : https://github.com/paulhodel/jsuites/pull/60

**Comment by ghost** [comment]
Thank you ! I really appreciate it. Many thanks to you and Paul for that constant work. Let me know when the fix will be implemented and how I can include it in my Vue project ("npm install jexcel" or another).

**Comment by ghost** [comment]
Since I don't know when Paul is going to deploy the new version with the contextual menu bug resolved, I have seen that lines of code have changed and I have tried to implement them manually in my Vue project. I have gone to Node packages, but I have not been able to find "contextMenu.js". I have also looked inside "jsuites.js" and I have not found where to modify it. Could you tell me where I can find the file to modify?

**Comment by GBonnaire** [comment]
jsuites is compiled only on jsuites.js, i have just make a PR on source (src) on github. Paul should recompiled all file

You can change compiled file : Find in this file (jsuites.js) : `jSuites.contextmenu =` and change line directly in this file

**Comment by pphod** [comment]
That was deployed to the NPM and website.
