### ISSUE TITLE
total value is not working after applying the row filter

### ISSUE THREAD

**Issue by kallaguntaashok** [jspreadsheet/ce#1225]
Hi,

I am using Jexcel formula to display the total of each row, also I am using filters, the issue is when if filter the table it sill shows the total value of all the rows it's not showing the filtered result. 

footers: [['', '', '', '', '', '', '', 'Total', '=ROUND(SUM(K1:K' + ic + '),2)', '=ROUND(SUM(L1:L' + ic + '),2)', '=ROUND(SUM(M1:M' + ic + '),2)', '=ROUND(SUM(N1:N' + ic + '),2)', '=ROUND(SUM(O1:O' + ic + '),2)', '=ROUND(SUM(P1:P' + ic + '),2)', '=ROUND(SUM(Q1:Q' + ic + '),2)', '=ROUND(SUM(R1:R' + ic + '),2)', '=ROUND(SUM(S1:S' + ic + '),2)', '=ROUND(SUM(T1:T' + ic + '),2)', '=ROUND(SUM(U1:U' + ic + '),2)', '=ROUND(SUM(V1:V' + ic + '),2)']],

above code "ic" it will show total rows in the table.

![image](https://user-images.githubusercontent.com/26366259/98956968-ac062180-2526-11eb-8c56-63bb8284b423.png)

I filtered may month data but the total is showing a different value ( it is the entire total value)

how to sync total with filter

**Comment by pphod** [comment]
You can change your totalizer to exclude the hidden columns.

**Comment by kallaguntaashok** [comment]
do you have any sample code this do this?
