### ISSUE TITLE
how to get all the comments based on row information.

### ISSUE THREAD

**Issue by kallaguntaashok** [jspreadsheet/ce#1226]
![image](https://user-images.githubusercontent.com/26366259/98982579-9f44f600-2545-11eb-8901-4aaa1faa7344.png)

i am adding comments to specific cell, when I use "obj.getConfig().comments" I am able to get all the comments in excel cell format.

![image](https://user-images.githubusercontent.com/26366259/98982902-14b0c680-2546-11eb-9c89-9aa755f308da.png)

my problem is, for example, if I add a comment in F1 column, later user my add different data in the F1 cell or they may delete the F1 column and add a new row in that place, in this case, if I rebind the comments based on excel tag like F1, it will update comments to the wrong column, is there any way I can update the column to row data.

**Comment by pphod** [comment]
That actually should not happen. If you delete F1 and F1 has comments, your comments would be deleted. If you remove E1, then your F1 column will become E1 and will bring the comments.
