### ISSUE TITLE
Bug: change cell type to checkbox

### ISSUE THREAD

**Issue by benci042** [jspreadsheet/ce#1227]
Hi Paul
as my issule ,i need change cell type to checkbox by programming.
table1.options.cells['A19']={type:'checkbox'};
it's working when i using table1.options verified.

In fact ,the cell not have checkbox symble. and got error when i check cell .
Uncaught TypeError: Cannot read property 'checked' of undefined

**Comment by pphod** [comment]
I suppose that is on PRO distribution. So, you add the following line after you doing this one.

jexcel.editors.checkbox.createCell(table1.records[18][0], '', 0, 18, table1, {});

**Comment by benci042** [comment]
Hi Paul
i got some error msg when i using your code.
Uncaught TypeError: _0x13234[_$_7c29[106]] is not a function

**Comment by benci042** [comment]
Btw, is it possible to add Text within checkbox cell?
