### ISSUE TITLE
Can I disable contextMenu for first n columns only?

### ISSUE THREAD

**Issue by AK3727** [jspreadsheet/ce#1228]
I used       
```
contextMenu: function(obj, x, y, e) {

        if(x<5){         
          return false;
        }
...
}

```
to disable contextMenu for the first few columns and it works. But the problem is when I right-click on columns after 5th column  contextMenu appears as it should be, but then it also starts to appear on right-clicking columns which are < 5.

**Comment by GBonnaire** [comment]
Change `return false;` to `return [];`
