### ISSUE TITLE
How to specify the cell to change the background color of the table header by using jexcel's setStyle function?

### ISSUE THREAD

**Issue by semihagursoy** [jspreadsheet/ce#1229]
Hi,

On the website, there are examples about changing the background color of a specific cell like A1, B2 etc. but I couldn't find an info about changing the styling of the table **headers.**

On the table, which you can find an attached image of it, what I want to do is to change the header's (**Product Origin, Description etc**) colors. How can I specify them like we do for the cells of A1 or B2? 

 
![jexcel](https://user-images.githubusercontent.com/26065232/99230751-fbcb3e00-27ef-11eb-87b8-7a293a83412d.JPG)

**Comment by GBonnaire** [comment]
Hi,

On onload property of JExcel you can defined that with this code 
```
var instance = el.jexcel;
var x = 0; // column number 0 = first (Index)
instance.thead.firstElementChild.children[x].style.backgroundColor = "red";
```

**Comment by semihagursoy** [comment]
![jexcel](https://user-images.githubusercontent.com/26065232/99531380-ec402680-29a2-11eb-965e-c5913bd4186f.png)

Hi, 

Thank you for your reply! 

I am using jquery and I am able to find the cell I want using this: 
`var cell = $('table > thead').children().find("[data-x=0]");`
and I'd like to use the jexcel's setStyle function like this: 
`table.setStyle('A1', 'background-color' , 'red');`  but when I pass the "cell" variable to the function, it doesn't work. 

so how should I pass the cell to this function?

**Comment by GBonnaire** [comment]
Hi,

the function setStyle of JExcel is only for cell of tbody (not header), first parameter is an string not an DOMElement (i.e A1, B12, ...).

If you use jquery, you can use code of the first answer or this jquery code :

```
var table = jexcel(DOMElement, {
    onload: function(el, instance) {
           var x = 0; // column number 0 = first (Index)
           instance.thead.firstElementChild.children[x].style.backgroundColor = "red";
           
           // Or in JQUERY
           x = 1 // column A
           $(instance.thead).find("tr").first().children().eq(x).css("background-color", "blue");
        },
};
```

**Comment by semihagursoy** [comment]
Hi @Guillaume-Bo,

It solved my problem! Thank you so much!
