### ISSUE TITLE
Context Menu not showing on right click on tabName in sheet.

### ISSUE THREAD

**Issue by AK3727** [jspreadsheet/ce#1230]
To open the Context Menu of a tab (maybe to rename a tab name), a user simply right-clicks on the sheet's tab name, but instead of opening Jexcel tab's Context menu it opens the browser's context menu .
To open the tab's Context Menu first User must left-click on the tab, and then he needs to right-click.
And If the user clicks (left-click) out of Jexcel sheet, again tab will start to show the browser's context menu.

**Comment by GBonnaire** [comment]
Hi, 

This bug it's on Pro version ?

@paulhodel

**Comment by pphod** [comment]
The CE version does not support the contextMenu at this moment. It would be included in version 5.

**Comment by pphod** [comment]
Those are available in the PRO distribution
https://jexcel.net/v7/examples/worksheets

**Comment by AK3727** [comment]
My Version is jExcel v5.7.2
jexcel-pro.

**Comment by pphod** [comment]
I am testing on v5.7.4 but was not able to replicate your issue.
https://jexcel.net/v5/examples/tabs

Please consider migrating for v7, which has much better support for tabs, including

- Drag and drop sorting;
- Rename, delete tabs on the context menu;
- New events and methods to programmatically manage that.
- etc.

Here is some working example.
https://jexcel.net/v7/examples/worksheets

**Comment by amritpal-singh** [comment]
Hi There, 
I am also facing this problem, @paulhodel I also checked the page you added for referance in you answer 
https://jexcel.net/v5/examples/tabs

but I am also facing same problem in example
please refer to attahced file 
![mPj1BNW](https://user-images.githubusercontent.com/2912868/101981092-6a38da00-3c90-11eb-8c12-9d297da9b3ce.gif)
file

try to make multiple tabs and focus on some other element and then right on tab, you will not be able to access context menu

**Comment by pphod** [comment]
Please update to v7
https://jexcel.net/v7/examples/worksheets
