### ISSUE TITLE
how to delete JExcel tab from worksheet?

### ISSUE THREAD

**Issue by AK3727** [jspreadsheet/ce#1232]
This is what I am trying, my JExcel Version is 5.
```
this.worksheet.nativeElement.jexcel.splice(sheetIndex-1, 1);
jexcel(this.worksheet.nativeElement.jexcel)
```

**Comment by pphod** [comment]
Can you upgrade JExcel to v7? The support for tabs is much better, and the migration should be very straight forward.

**Comment by pphod** [comment]
Property | Description
-- | --
createWorksheet(object) | Create a new table worksheet based on a given configuration.createWorksheet(configuration: object)
getWorksheet(object) | Get the worksheet position based on a table instance.getWorksheet(instance: object) => number
openWorksheet(number) | Set worksheet as active by worksheetNumber starting in zero.openWorksheet(worksheetNumber: number)
renameWorksheet(number, string) | Change a worksheet title.renameWorksheet(worksheetNumber: number, worksheetName: string)
deleteWorksheet(number) | Delete worksheet.deleteWorksheet(worksheetNumber: number)

**Comment by pphod** [comment]
https://jexcel.net/v7/examples/worksheets

**Comment by pphod** [comment]
If you further questions about this one you can send us a message at contact@jexcel.net
