### ISSUE TITLE
Issue while Rendering HTML tags in cell

### ISSUE THREAD

**Issue by ravikant2986** [jspreadsheet/ce#1233]
![download](https://user-images.githubusercontent.com/4242189/100110737-54a37200-2e93-11eb-842a-08024ab6f57a.png)
Hi,

I am trying to set cell value dynamically using table.setValue(cell, '<b>Test</b>'); which was working fine with V3. Now I am upgrading my code to V4 and setValue function does not render html tags. I also tried to update cell directly on example link "https://bossanova.uk/jexcel/v4/examples/table-style" which also don't render tags.  

Can you please suggest me the solution for this issue?

Thanks in Advance,

**Comment by GBonnaire** [comment]
Hi,

For "execute" HTML tag in cell, you should add property `stripHTML` in options of JExcel : 

```
var mytable = jexcel(DOMElement, {
     ...
     stripHTML:false,
     ...
});
```

**Comment by ravikant2986** [comment]
Thanks @Guillaume-Bo  it's working now.
