### ISSUE TITLE
filter issue.

### ISSUE THREAD

**Issue by kallaguntaashok** [jspreadsheet/ce#1234]
I have created functionality to duplicate the row, whenever I duplicate the row I have to refresh my table to display duplicated data, at this movement, if the user selects any filter and click on duplicate, my table is removing filter conditions. 

is there any way I can apply the filters through coding after refresh the table?

![image](https://user-images.githubusercontent.com/26366259/100134128-bd97e380-2ead-11eb-8294-1852cef02be1.png)

**Comment by GBonnaire** [comment]
Answer on #1246 

Please not duplicate topic for same problem, just up, and close duplicated topic 😉

**Comment by kallaguntaashok** [comment]
the duplicate issue, that's why I am closing this
