### ISSUE TITLE
getSelectedColumns function has not a boolean parameter to get only ids as mentioned in the guide

### ISSUE THREAD

**Issue by AndreaLombardo** [jspreadsheet/ce#1239]
Unlike what is reported in the guide, the getSelectedColumns function does not include the boolean parameter

https://github.com/paulhodel/jexcel/blob/c009cf1d9ccd27e30f2e00cc42fd52008e0d134d/src/js/jexcel.core.js#L4502

https://bossanova.uk/jexcel/v4/docs/programmatically-changes

**Comment by pphod** [comment]
Thanks, it has been fixed.
