### ISSUE TITLE
like this component, some questions

### ISSUE THREAD

**Issue by daonsh** [jspreadsheet/ce#124]
Hi,

We like this spreadsheet and consider using it for our project. Thanks for the good work.
We'd love to ask a few questions:

1. Is it possible to have multiline cells? Preferably each row with a different height according to content inside it.

2. When do you plan to release the pagination/bigdata feature? at the current way it works, how many rows are reasonable to have in the spreadsheet before it becomes too slow?

3. Is it possible to allow the user to change the names of the headers? (and perhaps types as well)

4. Is it possible to have expandable rows? for example in our product Yoman we have something like 
in this image, that you can expand a row to get another "mini-spreadsheet" to add more details.
We don't need the full solution, we can work it out, just to understand whether it'd be possible to create such a "gap" between rows and add our our stuff there.

![yoman-shot-explained](https://user-images.githubusercontent.com/15046011/38766234-cdb5f4cc-3fd7-11e8-8635-7b885d1a0ef8.png)

Thanks for the good work.

**Comment by pphod** [comment]
Thank you ;)

1: Yes, you can allow the wrap function.

2: We are releasing the version 1.5.0 with a lot of new features, but the
lazy method will be not included.

3: Yes you can change column name and types dynamically.

4: Yes, you can build something custom. But, I guess an overlay / floating
div is going to be easier to build.


jExcel works as a simple HTML table, so you can do pretty much anything
with the HTML using javascript. There are a lot of ways to customize your
features, for example:

Double click in a cell to open a custom editor, etc...

Regards,

**Comment by daonsh** [comment]
Thanks:)
