### ISSUE TITLE
not able to delete last row in version 4.4

### ISSUE THREAD

**Issue by kallaguntaashok** [jspreadsheet/ce#1244]
How to delete the last row in the table version 4.4 not allowing me to delete the last row, the same thing is happening in the portal also.

![image](https://user-images.githubusercontent.com/26366259/101053844-426db600-35ae-11eb-8927-f9feb07354a2.png)

**Comment by pphod** [comment]
If you delete the last row, the user cannot add new rows or columns manually. The user experience is not nice, that's why you have that restriction. Currently, you have a property you can use to change this behavior:

allowDeletingAllRows: true,
