### ISSUE TITLE
init data will be change after Jexcel changed.

### ISSUE THREAD

**Issue by benci042** [jspreadsheet/ce#1245]
Hi
I found that Init data will be change after table changed.  is it possibel to change data only in table?

var data = [
    [ '1', '2', '3', '4', '5', '6' ],
];
jexcel(document.getElementById('spreadsheet'), {
    data: data,
});

**Comment by GBonnaire** [comment]
Hi,

In this case, not passing argument immuable, but cloned. 

for cloned array use this :
```
   function cloneArray(currentArray) {
        return currentArray.map(function(arr) {
            return arr.slice();
        });
    }
```

in your example
```
var Table = jexcel(DOMElement, {
    data: cloneArray(data),
});
```

**Comment by benci042** [comment]
thanks.
