### ISSUE TITLE
How to duplicate a row.

### ISSUE THREAD

**Issue by kallaguntaashok** [jspreadsheet/ce#1246]
I would like to create a duplicate row functionality on top of filtered data, is there any way I can create duplicate row logic without effecting the filters. 

For example: if I have more than 1000 rows in a table, I will filter data based on the specific condition, then I would like to duplicate the row without removing the filter condition.

is it possible or any suggestion on this.

**Comment by GBonnaire** [comment]
HI,

How want you start duplicate ? By on click on contextMenu of column or row ?

You have a object with index of Row filtered `instance.results` 
And you can use `instance.insertRow(Array:data, ont:Position, Boolean: true for Before or fasse after)`

Instance is a variable with instance of JExcel passing by arguments on contextMenu or set on init

**Comment by kallaguntaashok** [comment]
I would like to click on context menu to duplicate the selected rows.

**Comment by kallaguntaashok** [comment]
Duplicating the selected row, I can do server side based on selected information, problem is if I do server side duplication, i have to reupdate table data using set data, it is removing filters.

If I follow " instance.insertRow(Array:data, ont:Position, Boolean: true for Before or fasse after) " this approach, filters will remain same?

**Comment by GBonnaire** [comment]
Ok.

Your problem is not duplicate row, but duplicate row without remove filter applied ?

For that try this in property contextMenu : 
```
var table = jexcel(DOMElement, {
     contextMenu: function(obj, x, y, e) {
            var items = [];
            
             /* ... */
            if(x==null && obj.getSelectedRows().length) {
                items.push({
                     title:"Duplicate selected row(s)",
                     onclick:function() {
                         // Init var
                         var Flagfiltered = false; // Flag for know if filter is apply
                         var filters = obj.filters.map(function(arr) {if(arr==null) {return null;} else {Flagfiltered = true; return arr.slice();}});
                         var search = obj.searchInput.value;
                         
                         var indexLastRow = parseInt(obj.getSelectedRows()[obj.getSelectedRows().length-1].getAttribute('data-y'));
                         
                         var dataRowsSelected = obj.getData(true);
                          
                         // Reset Search
                         obj.resetFilters();
                         obj.resetSearch();
                         
                         // Duplicate rows
                         dataRowsSelected.forEach(function (row) {
                             obj.insertRow(row, indexLastRow);
                             indexLastRow++;
                         });
                         
                         // Reapply filters
                         if(Flagfiltered) {
                            obj.filters = filters;
                            obj.closeFilter();
                         }
                        
                         // Reapply Search
                         if(search) {
                            obj.searchInput.value = search;
                            obj.search(search);
                        }
                     }
                 });
            }

             /* ... */
            return items;
       },
   });
```

**Comment by kallaguntaashok** [comment]
Thank you so much, an amazing piece of code, I really appreciate it.

**Comment by kallaguntaashok** [comment]
The above code is working fine with the main filter if I use the column-wise filter after adding a new row column filter showing blank it is loosing filtered values in filter dropdown.

for example: if I filter Xyz value data, after adding new rows, Xyz will not appear in the filter section, but it is working fine. 

// Reapply filters
                            if (Flagfiltered) {
                                obj.filters = filters;
                                obj.closeFilter();
                            }
above code is not able to display selected filtered values in the filter dropdown.  
![image](https://user-images.githubusercontent.com/26366259/103138867-9b87c000-46fc-11eb-95f9-2ff46197ec43.png)

**Comment by kallaguntaashok** [comment]
I found the solution.
