### ISSUE TITLE
Filters are not hiding if I use table.hideColumn(colNumber).

### ISSUE THREAD

**Issue by kallaguntaashok** [jspreadsheet/ce#1247]
I am creating a functionality to hide columns, I am using table.hideColumn(colNumber) to hide the columns, and I am able to hide the columns, but filters are mapped to next available cell.

For example if I hide A column, A filter data will show in B column.

Also if I add new row to table after hiding few collection, A cell information will show in B cell, same like filters.

Kindly suggest some solution

**Comment by GBonnaire** [comment]
Hi,

@paulhodel : I think with hideColumn who not hide filter.

@kallaguntaashok for give you a solution temporaly.
when you apply `obj.hideColumn(index); `apply `obj.filter.children[index+1].style.display = "none";`

**Comment by kallaguntaashok** [comment]
hi,

I guess it's not working "obj.filter[index]", could you please check the below screenshot. 

![image](https://user-images.githubusercontent.com/26366259/101287873-f7a3a680-3818-11eb-93df-e34fc49c5101.png)

![image](https://user-images.githubusercontent.com/26366259/101287916-43eee680-3819-11eb-95ca-d162274037f8.png)

**Comment by GBonnaire** [comment]
Ok, i have not test my code. But if you check obj.filter, you can see is DOMElement.

In this case you must use "children" for access element

Code updated : (index is index of column)
`obj.filter.children[index+1].style.display = "none";`

**Comment by kallaguntaashok** [comment]
Thank you so much it is working fine.
