### ISSUE TITLE
issue with filter after upgrading framework 4.2.1 to 4.4.2

### ISSUE THREAD

**Issue by kallaguntaashok** [jspreadsheet/ce#1248]
after changing the framework from 4.2.1 to 4.4.2 I can see a text "blank" item in the filter dropdown, the table doesn't have any blanks but it is showing blank in each filter of the table. 

![image](https://user-images.githubusercontent.com/26366259/101339115-fc616c80-38a3-11eb-8520-e37ad2cc9aaa.png)

**Comment by pphod** [comment]
This has been fixed.
