### ISSUE TITLE
issue with table dropdown.

### ISSUE THREAD

**Issue by kallaguntaashok** [jspreadsheet/ce#1250]
![image](https://user-images.githubusercontent.com/26366259/101670301-fec8ef80-3a78-11eb-8dcf-8ce8f949eb06.png)

I am using the above line of code to bind data into the dropdown, but unfortunately, this piece of code is not working, am I missing anything here? 

I have to bind more than 10 dropdowns in the table, if the above code works it will be a great help.

Jexcel 4.4.2 version & Jsuite v3.8.2 I am using.

**Comment by pphod** [comment]
The code seems fine to me. The dropdown documentation:
https://jsuites.net

Do you have any error?
