### ISSUE TITLE
Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by Tammerabi** [jspreadsheet/ce#1251]
Hello,

I'm trying to incorporate jexcel into our Next.js based React project, but I'm running into this issue right from the get-go.

```
./node_modules/jsuites/dist/jsuites.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/jexcel/dist/jexcel.js
```

Next's proposed solution as mentioned in that link is to reach out to the maintainer and ask for them to publish a compiled version of their dependency. 

Could you assist with this?

**Comment by jonnjasperejoc** [comment]
I'm also having this problem with the jsuites.

**Comment by kstulgys** [comment]
Same issue :(

**Comment by ramaadhiguna** [comment]
same issue

**Comment by gorpher** [comment]
> Hello,
> 
> I'm trying to incorporate jexcel into our Next.js based React project, but I'm running into this issue right from the get-go.
> 
> ```
> ./node_modules/jsuites/dist/jsuites.css
> Global CSS cannot be imported from within node_modules.
> Read more: https://err.sh/next.js/css-npm
> Location: node_modules/jexcel/dist/jexcel.js
> ```
> 
> Next's proposed solution as mentioned in that link is to reach out to the maintainer and ask for them to publish a compiled version of their dependency.
> 
> Could you assist with this?

have resolved ？

**Comment by jaywcjlove** [comment]
I created a nextjs package [`next-remove-imports`](https://www.npmjs.com/package/next-remove-imports) to solve the problem. Best solution :) 

Example: https://codesandbox.io/s/nextjs-example-react-md-editor-qjhn7?file=/pages/index.js


@IDlOT @gorpher

**Comment by brianjoseff** [comment]
This worked for me:
```
import '../node_modules/jspreadsheet-ce/dist/jspreadsheet.css';
import '../node_modules/jsuites/dist/jsuites.css';
import '../node_modules/jsuites/dist/jsuites.js';
const jRef = useRef(null);
...

(async () => {
        if (typeof window !== 'undefined') {
            // import module for side effects
            const { default: jspreadsheet } = await import('jspreadsheet-ce');
            jspreadsheet(jRef.current, options);
        }
    })();
```
    
And set `ref={jRef}` on the div you're mounting spreadsheet on in your component.
 (Using Next.js / React / jspreadsheet-ce)

**Comment by hodeware** [comment]
Create an online XLSX reader with NextJS and Jspreadsheet Pro.
https://codesandbox.io/s/jspreadsheet-and-nextjs-6fhsz
