### ISSUE TITLE
Copy and paste multiple columns inserts empty columns every other column

### ISSUE THREAD

**Issue by x0nium** [jspreadsheet/ce#1252]
Using jExcel v2.0.4

When I copy several columns paste them, it will insert an empty column in between every column with value.

When pasting, for example, a 3 column table.

Value from A1 ends up in A1.
A2 gets empty.
Value from A2 ends up in A3.
A4 gets empty.
Value from A3 ends up in A5.

It's the same no matter whether I copy from jExcel to jExcel or from Microsoft Excel to jExcel.

Is this a known issue in this old version of jExcel that has been fixed since, or is it just me having this issue?

**Comment by pphod** [comment]
Sorry, Jexcel 2 is deprecated, please consider updating to the most recent versions.

**Comment by x0nium** [comment]
Well. That's why I asked... Is this issue fixed in newer versions?

**Comment by pphod** [comment]
Did you have a chance to test?
https://bossanova.uk/jexcel or https://jexcel.net
