### ISSUE TITLE
bug with removeMerge and destroyMerged

### ISSUE THREAD

**Issue by benci042** [jspreadsheet/ce#1253]
Hi 
I need removemerge and destroy by programmlly.  and both funtion are has problem when same row has two or more cell with merged.
example.
https://jexcel.net/v7/examples/merged-cells
after merge this action,table.setMerge('C3', 1, 2);
then **Destroy merge from A3** and  **Destroy all merged** will not work .

**Comment by GBonnaire** [comment]
@paulhodel A problem for you 😊

**Comment by pphod** [comment]
That has been fixed. v7.8
