### ISSUE TITLE
sticky for thead does not work

### ISSUE THREAD

**Issue by hyh888** [jspreadsheet/ce#1255]
when toolbar is added in jexcel, sticky for    ".jexcel > thead > tr > td" doesn't work. But toolbar is sticky.
![image](https://user-images.githubusercontent.com/963838/101871026-c41c9f80-3bbd-11eb-81ff-55e9e719d235.png)
if without toolbar, the sticky function of ".jexcel > thead > tr > td" is OK.
In Chrome and in Edge, there are same problems.

**Comment by GBonnaire** [comment]
stiky work, but with toolbar, the heads is hide bottom toolbar

for fix that add on style page :
```
.jexcel_container.with-toolbar .jexcel > thead > tr > td {
      top: 42px;
}
```

**Comment by hyh888** [comment]
thank you  very much.
