### ISSUE TITLE
Table sum issue.

### ISSUE THREAD

**Issue by kallaguntaashok** [jspreadsheet/ce#1256]
I have an issue with table sum, I am using a formula with "footers" to calculate the sum, below are the issues that I am facing with the sum.

![image](https://user-images.githubusercontent.com/26366259/101882528-080ea500-3bbc-11eb-9f28-8c63cbf7168d.png)

1.  =SUM(B1:B8) using this formula it will sum only 1 to 8 rows, the sum is not working if we added more than 8 rows in the tables,  how to add this sum dynamically, it should work even after inserting a new row. 

2. if I filter the rows sum is showing for the total row, how to eliminate the hidden rows and sum only apply to filtered rows, is there any event I can trigger on filter change? 

3. I tried creating custom logic for a filtered data sum, but there is no event related to filters. 

any solution to these issues?

**Comment by pphod** [comment]
You must do some coding using an event such as onafterchanges or updateTable. 

A better experience is available in the Pro version with better support to formulas and ranges.

**Comment by pphod** [comment]
Just for references.
https://jexcel.net/v7/examples/spreadsheet-formulas
