### ISSUE TITLE
how to add filter settings back after page the refresh.

### ISSUE THREAD

**Issue by kallaguntaashok** [jspreadsheet/ce#1257]
Hi,

once the user refreshes the page all the filters will remove automatically, is there a way to store filter value and re-apply those filter settings after a page refresh. 

I am planning to create a user profile, using profile users can permanently hide some columns and apply some filters, these setting should apply automatically once the user opens the page at any time, the above information can help in creating the profile.

**Comment by pphod** [comment]
On the CE you can do that:
yourInstance.filter[columnNumber] = ['value1', 'value2', 'value3'];
yourInstance.closeFilter(columnNumber);
