### ISSUE TITLE
jexcel breakdowned after updating a cell.

### ISSUE THREAD

**Issue by hyh888** [jspreadsheet/ce#1259]
jexcel breakdowned after updating a cell.

![image](https://user-images.githubusercontent.com/963838/102029289-daf30a00-3de8-11eb-9c9b-c0637c578548.png)
there is a error for    " var value = cell.children[0].value;", it seems that updated cell has not children, but in watch window, there is childnodes for cell, but no children for the updated cell. And then the excel breakdown, unless change to another page.

**Comment by pphod** [comment]
That seems due an blur event. Are you using custom columns?
