### ISSUE TITLE
title index

### ISSUE THREAD

**Issue by znh0503** [jspreadsheet/ce#1260]
how to make title first?

![1607935912(1)](https://user-images.githubusercontent.com/42962580/102060245-e7995180-3e2c-11eb-9e9f-d602e016abcc.png)
![1607935829](https://user-images.githubusercontent.com/42962580/102060221-dfd9ad00-3e2c-11eb-9ae1-1ed0f5b61f01.jpg)

**Comment by GBonnaire** [comment]
if you use jexcel pro : you can use this plugin : https://jexcel.net/plugins/rowheaders

if you use jexcel CE you can get DOMElement with this code :
`elSelectAll = instance.table.querySelector('.jexcel_selectall')`

**Comment by znh0503** [comment]
> 如果您使用jexcel pro：可以使用此插件：[https](https://jexcel.net/plugins/rowheaders) ://jexcel.net/plugins/rowheaders[](https://jexcel.net/plugins/rowheaders)
> 
> 如果您使用jexcel CE，则可以使用以下代码获取DOMElement：
> `elSelectAll = instance.table.querySelector('.jexcel_selectall')`

thanks,but doesn't seem to support IE /(ㄒoㄒ)/~~（ i use pro)

**Comment by znh0503** [comment]
> 如果您使用jexcel pro：可以使用此插件：[https](https://jexcel.net/plugins/rowheaders) ://jexcel.net/plugins/rowheaders[](https://jexcel.net/plugins/rowheaders)
> 
> 如果您使用jexcel CE，则可以使用以下代码获取DOMElement：
> `elSelectAll = instance.table.querySelector('.jexcel_selectall')`

I got the solution.
` onchangepage: function () {

            $("tbody tr").each(function () {
                var td = $(this).find("td:eq(0)");
                var datay=td.attr("data-y");
                td.text(parseInt(datay) + 2);
            })
        },`

but search action did not work,so what is a search event callback

**Comment by GBonnaire** [comment]
plugin not work on IE ? which version ?

what do you mean by "search not work" ?

Do you want hide column header ? for to have only content ?

**Comment by znh0503** [comment]
> 插件在IE上不起作用？哪个版本？
> 
> “搜索无效”是什么意思？
> 
> 是否要隐藏列标题？为了只有内容？

1. jExcel v5.7.0
1. sorry,bad english/(ㄒoㄒ)/~~
Look at the picture please.
![1](https://user-images.githubusercontent.com/42962580/102191315-352cc180-3ef4-11eb-8ff1-c3c520acb3f1.png)
![2](https://user-images.githubusercontent.com/42962580/102191457-64433300-3ef4-11eb-93b0-8e5e1196e7b8.png)


changepage
![3](https://user-images.githubusercontent.com/42962580/102191559-8ccb2d00-3ef4-11eb-9349-3a0700cfb13c.png)
![4](https://user-images.githubusercontent.com/42962580/102191676-b421fa00-3ef4-11eb-814e-58bc9e7b28fe.png)

but search...
![5](https://user-images.githubusercontent.com/42962580/102191862-f6e3d200-3ef4-11eb-8def-e468dd995a3e.png)

so i need search callback event ,like changepage

**Comment by GBonnaire** [comment]
don't worries for English, it's same for me 😊 

first : try to migrate to last version of JExcel Pro (v7.9), i think this bug is fixed in last version.

Be careful : data-y is different of IndexRow, indexRow = data-y + 1

@paulhodel : Can you help on jexcel Pro ? i think you have more information in this case

**Comment by pphod** [comment]
It would be helpful to migrate to v7.
Regards,

**Comment by znh0503** [comment]
> don't worries for English, it's same for me 😊
> 
> first : try to migrate to last version of JExcel Pro (v7.9), i think this bug is fixed in last version.
> 
> Be careful : data-y is different of IndexRow, indexRow = data-y + 1
> 
> @paulhodel : Can you help on jexcel Pro ? i think you have more information in this case

emm..thank you

**Comment by znh0503** [comment]
> It would be helpful to migrate to v7.
> Regards,

thank you...
