### ISSUE TITLE
Copy values from dropdown v7

### ISSUE THREAD

**Issue by vik17ag** [jspreadsheet/ce#1262]
Hi,
In v7, when we copy from a dropdown with ids like in this example - [https://jexcel.net/v7/examples/dropdown-and-autocomplete](url), it pastes ids and not values.
For example, Copy United States from 1st col and paste it any other cell, it pastes US and not the displayed value.

How can we configure to copy and paste the displayed values? This behaves as we want when pasted to other application like notepad.
Thx in advance.

**Comment by pphod** [comment]
But, that's the correct behavior. If you have key-value dropdown you always copy the ID internally, if you are pasting to an external software them you will bring the LABEL not id. If you wish to bring the label in both cases, you need to use arrays, example:

source: ['United States','United Kingdom'];
