### ISSUE TITLE
Get pasted id in dropdown v7

### ISSUE THREAD

**Issue by vik17ag** [jspreadsheet/ce#1263]
Hi
V7 version allows paste of id as well as value of a key-value pair of a dropdown column. 
But, in **_onbeforechange_**  event, we want to always save the ID in our server. 

Can you guide us how to do it? 

We use Firebase SDK to save in server.

Thx in advance

**Comment by pphod** [comment]
To save, it is better to use onafterchanges so you trigger just one action by time.

**Comment by vik17ag** [comment]
Thanks for the great tip! We ll use onafterchanges.
But, we still have to loop through the column.source to get the ID of the pasted value in the above event. 
Code increases in case of multi-select dropdowns. The `,` is added in case of cell drag and ` ;` is added in case of copy.

```
``

  if (column.type === 'dropdown'){

        if (value.includes(';') || value.includes(',')){
          console.log(value)
          if (value.includes(';')){
            value = value.replaceAll('; ',';')
            value = value.split(';')
          } else {
            value = value.replaceAll(', ',',')
            value = value.split(',')
          }

          const items =  column.source.filter(item=> {
            return  value.includes(item.value)
          })

          //If value found in source list, then fetch id, else save value
          if (items && items.length > 0){
            value =  items.map(item=>item.id)

          }
        } else {
          const item =  column.source.find(item=> item.value === value)
          //If value found in source list, then fetch id, else save value
          if (item){
            value = item.id
          }
        }

      }

``
```

If we can give out the value and id in the onafterchange or onbeforechange or any other event, it will make it simpler. Although, I am not sure if it would put extra load on the library.
