### ISSUE TITLE
Dropdown with remote search and lazy loading with jExcel v4 and jSuites v3

### ISSUE THREAD

**Issue by jeremycook** [jspreadsheet/ce#1264]
Hi @paulhodel I took a shot at using remote search with jExcel 4.5.0 and jSuites 3.9.1, but could not get it to work in a spreadsheet. I did get it working with just the dropdown by itself (no spreadsheet) like in [these docs](https://bossanova.uk/jexcel/v4/examples/dropdown-and-autocomplete). Based on this comment (https://github.com/jspreadsheet/jexcel/issues/798#issuecomment-569546046) it seems like this was at least supported by an older combination of jExcel+jSuites.

Here's an example of me trying to get it working in the spreadsheet. The `url` and `autocomplete` options are working as expected but setting `remoteSearch` and `lazyLoading` does not seem to change anything, "?q=INPUTTEXT" does not get added to the query string. I also tried tucking the those options in an `options: { ... }` object like in the calendar examples I've seen and that didn't change anything either.

```javascript
var table = jexcel(root, {
    data: data,
    columns: [
        { type: 'dropdown', title: 'Things', width: 200, source: [], url: '/things/dropdown', autocomplete: true, remoteSearch: true, lazyLoading: true },
    ],
    minDimensions: [1, 1],
});
```

**Comment by jeremycook** [comment]
The following configuration works in jExcel v7:

```
{ type: 'dropdown', title: 'Things', width: 200, source: [], autocomplete: true, options: { url: '/things/dropdown', remoteSearch: true, lazyLoading: true } },
```

I assume this is correct since it is working. An example of this would be nice. Also, it isn't clear to me when I should put settings in the `options` object vs. top level of the column object. To my surprise I had to move the `url` into the options object for example. Do you have some documentation that explains when settings should be placed in the options object vs directly in the column object?

**Comment by pphod** [comment]
Did you find the solution?

**Comment by jeremycook** [comment]
jExcel v7 seems to be the solution. Should it work with v4?
