### ISSUE TITLE
Scrollbar starts wobbling when lazyLoad=true

### ISSUE THREAD

**Issue by lzoubek** [jspreadsheet/ce#1267]
When using lazyLoading: true and container height is quite big (it looks like spreadsheet displays more than 30 rows) its impossible to scroll down. Scrollbar starts wobbling

This example works fine
[https://bossanova.uk/jexcel/v4/examples/lazy-loading](https://bossanova.uk/jexcel/v4/examples/lazy-loading)

But when you open Dev console and try to set `max-height: 900px` of `<div class=" jexcel_content">`

I'd be happy to provide PR, but question is .. what is the best way to go.

Possible solution may be to provide `lazyLoadConfig` config property, where consumers can override number of  rendered rows (currently is 130), this would mean basically extracting constants `100` and `30` from `loadUp` or `loadDown` functions

**Comment by GBonnaire** [comment]
For table height, use property of jexcel : tableHeight: '900px'

**Comment by sanjayAdhikari** [comment]
Hi @paulhodel, I have used the Jexcel table and it's really good and easy to use. But I am stuck at the closure property on `onafterchanges function`. How do I access the state inside onAfterChanges? I am getting old state value and the div which jexcel referenced does not work with the key property; i.e when key changes, jexcel table hides.

**Comment by pphod** [comment]
onafterchanges: (DOMElement el, Array records);

the record is an array of objects, which brings you the x, y, newValue, oldValue. for all updated records.
