### ISSUE TITLE
How to allow only numbers (Ex: 123, 0.23,1.23,22.33,45600) in jexcel table cells.

### ISSUE THREAD

**Issue by kallaguntaashok** [jspreadsheet/ce#1270]
How to add a logic to allow cell only numbers, I used the below code to do this, but it is causing performance issues. 
is there anyway, I can create a logic to allow only numbers in the cell. 

if (col == 9 || col == 10 || col == 11 || col == 12 || col == 13 || col == 14 || col == 15 || col == 16 || col == 17 || col == 18 || col == 19 || col == 20 || col == 21) {

                    cell.onkeypress = function isNumberKey(evt) {
                        var charCode = (evt.which) ? evt.which : evt.keyCode;
                        if (charCode != 46 && charCode != 45 && charCode > 31 && (charCode < 48 || charCode > 57)) {
                            return false;
                        }
                        else {
                            return true;
                        }
                    };

                }

**Comment by pphod** [comment]
The most straight forward is to use type:'number' and in your data, you have the only number for those columns you will probably reach the results you are expecting.

**Comment by kallaguntaashok** [comment]
> The most straight forward is to use type:'number' and in your data, you have the only number for those columns you will probably reach the results you are expecting.

I am using the type number, still, it is allowing characters, for your reference, I am adding the code below. 

{ type: 'number', title: 'MAY', width: 45 },
                { type: 'number', title: 'JUN', width: 45 },
                { type: 'number', title: 'JULY', width: 45 },
                { type: 'number', title: 'AUG', width: 45 },
                { type: 'number', title: 'SEP', width: 45 },
                { type: 'number', title: 'OCT', width: 45 },
                { type: 'number', title: 'NOV', width: 45 },
                { type: 'number', title: 'DEC', width: 45 },
                { type: 'number', title: 'JAN', width: 45 },
                { type: 'number', title: 'FEB', width: 45 },
                { type: 'number', title: 'MAR', width: 45 },

I am using "jExcel v4.4.2" version.

**Comment by ogisetiawan** [comment]
> > The most straight forward is to use type:'number' and in your data, you have the only number for those columns you will probably reach the results you are expecting.
> 
> I am using the type number, still, it is allowing characters, for your reference, I am adding the code below.
> 
> { type: 'number', title: 'MAY', width: 45 }, { type: 'number', title: 'JUN', width: 45 }, { type: 'number', title: 'JULY', width: 45 }, { type: 'number', title: 'AUG', width: 45 }, { type: 'number', title: 'SEP', width: 45 }, { type: 'number', title: 'OCT', width: 45 }, { type: 'number', title: 'NOV', width: 45 }, { type: 'number', title: 'DEC', width: 45 }, { type: 'number', title: 'JAN', width: 45 }, { type: 'number', title: 'FEB', width: 45 }, { type: 'number', title: 'MAR', width: 45 },
> 
> I am using "jExcel v4.4.2" version.

that is already fix? maybe you can use mask as property 
type: 'number', title: 'MAY', width: 45 , mask: '#,##'

but i dunno when you use without sparator thousand
