### ISSUE TITLE
Range selection in formula not working

### ISSUE THREAD

**Issue by ilmistra** [jspreadsheet/ce#1278]
It seems that range selection in a SUM formula is not working with row index > 9. SUM(A1:A9) is working, SUM(A1:A10) not.
Tested with Chrome and Brave on my demo and your example as well.

**Comment by GBonnaire** [comment]
Hi,

I have test on https://bossanova.uk/jexcel/v3/examples/spreadsheet-formulas and his work.

Have you last version of JExcel ?

**Comment by ilmistra** [comment]
It works on v3 version, yes! But still a problem on v4 version.
If you try to add few rows on https://bossanova.uk/jexcel/v4/examples/spreadsheet-formulas example, and try a SUM(B1:B11), it will consider as a SUM(B1:B1), and B1:B12 will be like B1:B2...

**Comment by GBonnaire** [comment]
Ok, ty, i have make a fix for that

**Comment by GBonnaire** [comment]
Is fixed
