### ISSUE TITLE
Url alias

### ISSUE THREAD

**Issue by vik17ag** [jspreadsheet/ce#1284]
Can an alias be given to the URL type column?

For example, in the LINK type column,
url = www.google.com
alias = Google

The aim is to not show the actual url but an alias name instead.

Thx in adv

**Comment by GBonnaire** [comment]
column tyep LINK ? maybe do you mean column type HTML ?

can you show your code / init jexcel

**Comment by vik17ag** [comment]
Apologise for using the wrong term. it is [URL ](https://jexcel.net/v5/examples/email-and-links)column type.

![image](https://user-images.githubusercontent.com/14138472/105025135-ef26c880-5a72-11eb-9146-e06fb43cbd33.png)

Referring to the documentation - https://jexcel.net/v5/examples/email-and-links , how can we display GOOGLE instead of https://www.google.com

**Comment by GBonnaire** [comment]
Ok, it’s on version Pro, i see only on version CE.

And i don’t know if on pro version you have a feature for make a label. I don’t think so.

**Comment by vik17ag** [comment]
Ok, Shall i make this issue in pro github?

**Comment by vik17ag** [comment]
Ok, I created this issue in pro-version. Thx!
