### ISSUE TITLE
Event - How to get Row and Column Number 

### ISSUE THREAD

**Issue by azrulharis** [jspreadsheet/ce#1285]
Hello,

anyone can explain how to get the row and column number?

Ie: onkeyup on some column, it will return A8 

Thank you in advance

**Comment by GBonnaire** [comment]
for transform A8 to 0,7 (x, y) use : jexcel.getIdFromColumnName(cellName, returnArrayFormat)

from cell you can read x,y position with read attribute.
```javascript
var x = parseInt(cell.getAttribute("data-x"));
var y = parseInt(cell.getAttribute("data-y"));
```
