### ISSUE TITLE
Freeze column in ie

### ISSUE THREAD

**Issue by whyJoe** [jspreadsheet/ce#1286]
Hi Paul,
  When i use freeze column in IE, content  can be freezed ,but the header can't.
  I think it may be that the IE  does not support css(**postion:sticky**).

  Please help and provide solution for this issue, thx.

**Comment by GBonnaire** [comment]
Hi,

I think the better solution it's override `updateFreezePosition` when sticky not supported

code not tested
```javascript
MyTable = jexcel(DOMEl,{});
if (!(CSS && CSS.supports && CSS.supports("position", "sticky"))) {
   MyTable.updateFreezePosition = function() {
            var obj = MyTable;
            scrollLeft = obj.content.scrollLeft;
            var width = 0;
            if (scrollLeft > 50) {
                for (var i = 0; i < obj.options.freezeColumns; i++) {
                    obj.headers[i].classList.add('jexcel_freezed');
                    obj.headers[i].style.position = 'relative';
                    var shifted = (scrollLeft + (i > 0 ? obj.headers[i].style.width : 0)) - 51 + 'px';
                    obj.headers[i].style.left = shifted + 'px';
                    for (var j = 0; j < obj.rows.length; j++) {
                        if (obj.rows[j] && obj.records[j][i]) {
                            var shifted = (scrollLeft + (i > 0 ? obj.records[j][i-1].style.width : 0)) - 51 + 'px';
                            obj.records[j][i].classList.add('jexcel_freezed');
                            obj.records[j][i].style.left = shifted;
                        }
                    }
                }
            } else {
                for (var i = 0; i < obj.options.freezeColumns; i++) {
                    obj.headers[i].classList.remove('jexcel_freezed');
                    obj.headers[i].style.position = '';
                    obj.headers[i].style.left = '';
                    for (var j = 0; j < obj.rows.length; j++) {
                        if (obj.records[j][i]) {
                            obj.records[j][i].classList.remove('jexcel_freezed');
                            obj.records[j][i].style.left = '';
                        }
                    }
                }
            }

            // Place the corner in the correct place
            obj.updateCornerPosition();

   } 
}
```

**Comment by whyJoe** [comment]
> Hi,
> 
> I think the better solution it's override `updateFreezePosition` when sticky not supported
> 
> code not tested
> 
> ```js
> MyTable = jexcel(DOMEl,{});
> if (!(CSS && CSS.supports && CSS.supports("position", "sticky"))) {
>    MyTable.updateFreezePosition = function() {
>             var obj = MyTable;
>             scrollLeft = obj.content.scrollLeft;
>             var width = 0;
>             if (scrollLeft > 50) {
>                 for (var i = 0; i < obj.options.freezeColumns; i++) {
>                     obj.headers[i].classList.add('jexcel_freezed');
>                     obj.headers[i].style.position = 'relative';
>                     var shifted = (scrollLeft + (i > 0 ? obj.headers[i].style.width : 0)) - 51 + 'px';
>                     obj.headers[i].style.left = shifted + 'px';
>                     for (var j = 0; j < obj.rows.length; j++) {
>                         if (obj.rows[j] && obj.records[j][i]) {
>                             var shifted = (scrollLeft + (i > 0 ? obj.records[j][i-1].style.width : 0)) - 51 + 'px';
>                             obj.records[j][i].classList.add('jexcel_freezed');
>                             obj.records[j][i].style.left = shifted;
>                         }
>                     }
>                 }
>             } else {
>                 for (var i = 0; i < obj.options.freezeColumns; i++) {
>                     obj.headers[i].classList.remove('jexcel_freezed');
>                     obj.headers[i].style.position = '';
>                     obj.headers[i].style.left = '';
>                     for (var j = 0; j < obj.rows.length; j++) {
>                         if (obj.records[j][i]) {
>                             obj.records[j][i].classList.remove('jexcel_freezed');
>                             obj.records[j][i].style.left = '';
>                         }
>                     }
>                 }
>             }
> 
>             // Place the corner in the correct place
>             obj.updateCornerPosition();
> 
>    } 
> }
> ```

Thanks for your idea! And I  made a change to determine whether to support sticky.

`var sticky = (function () {
        var vendorList = ['', '-webkit-', '-ms-', '-moz-', '-o-'],
            vendorListLength = vendorList.length,
            stickyElement = document.createElement('div');
        for (var i = 0; i < vendorListLength; i++) {
            stickyElement.style.position = vendorList[i] + 'sticky';
            // console.log('stickyElement', stickyElement)
            if (stickyElement.style.position !== '') {
                return true;
            }
        }
        return false;
    })();`

**Comment by whyJoe** [comment]
Thanks for your idea! And I made a change to determine whether to support sticky.

```
var sticky = (function () {
        var vendorList = ['', '-webkit-', '-ms-', '-moz-', '-o-'],
            vendorListLength = vendorList.length,
            stickyElement = document.createElement('div');
        for (var i = 0; i < vendorListLength; i++) {
            stickyElement.style.position = vendorList[i] + 'sticky';
            if (stickyElement.style.position !== '') {
                return true;
            }
        }
        return false;
    })();
```
