### ISSUE TITLE
Feature request : Images in cell

### ISSUE THREAD

**Issue by vik17ag** [jspreadsheet/ce#129]
Hi,

Can we add images instead of text inside any cell via url? Or can we assign 'Image' type to any column? Something like the following - 

![image](https://user-images.githubusercontent.com/14138472/39093618-ce360bee-463f-11e8-878d-b77849fda749.png)

Would be great to have this feature.Thanks!

**Comment by pphod** [comment]
Please, take a look on this example:
https://jsfiddle.net/paulhodel/9296zmpf/

**Comment by liyanyan1994** [comment]
Hello,
    I have the same requirement. I would like to insert an image in each line of the table, but I cannot open the website you gave. Could you provide another link to jsfiddle？ Thanks.
