### ISSUE TITLE
Grouping rows or sum across different spreadsheets 

### ISSUE THREAD

**Issue by francescob73** [jspreadsheet/ce#1293]
Hi,

I'm tryin to create gorup of rows with jexcel but I can't find ingormation. I want to create in the same spreadsheet different categories (groups), make the subtotal of each group and then make the Grand Total adding each subtotoal. It is possible with Jexcel? Someone can help me? 

Many thanks

**Comment by GBonnaire** [comment]
Hi,

For help, i think it's better to create 1 sheet per groups (categories) and make a total with footer. After manage this different case :
- Create a custom formula for read this other sheet -> type of : =READTOTAL("SHEETNAME", "COLUMN")
- Event for Update data on sheet with all total -> use onafterchanges

With JExcel Pro you can use formula cross sheet more easier (like excel)

**Comment by hodeware** [comment]
There are no native methods for that currently.
