### ISSUE TITLE
SUM formular just works with single digits

### ISSUE THREAD

**Issue by luke10001** [jspreadsheet/ce#1296]
Hello all,
if I enter for example **=SUM(B1:B24)**, then it just counts from B1 to B4. It ignores the first digit. B1:B12 would count from B1 to B2. It's always the same bug...Edit: It seems that double digit numbers can never be calculated with, regardless of the SUM function

Anybody heard from that before?

I have these files included:

_<script src="js/jquery-3.5.1.js"></script>
 <script src="js/bootstrap.bundle.js"></script>
<script src="https://bossanova.uk/jexcel/v4/jexcel.js"></script>
<script src="https://bossanova.uk/jsuites/v3/jsuites.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jexcel/v4/jexcel.css" type="text/css" />
<link rel="stylesheet" href="https://bossanova.uk/jsuites/v3/jsuites.css" type="text/css" />	
<script src="https://jexcel.net/v5/jsuites.js"></script>
<script src="js/custom_functions.js"></script>

<link rel="stylesheet" href="https://jexcel.net/v5/jexcel.css" type="text/css" />
<link rel="stylesheet" href="https://jexcel.net/v5/jsuites.css" type="text/css" />
<link rel="stylesheet" href="https://bossanova.uk//templates/jexcel-v4/js/themes.js" type="text/css" />
<link href="css/width100.css" rel="stylesheet">
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />__

thanks a lot

**Comment by GBonnaire** [comment]
Hi, 

Have you test with last version in GitHub ? If you use version of bossanova, it's not include last fix in formula.

@paulhodel Maybe it's possible to update jexcel.js in bossanova ?

**Comment by luke10001** [comment]
Hey,
thank you. if I take the github jexcel.js it works!
