### ISSUE TITLE
Embedded image in the sheet

### ISSUE THREAD

**Issue by JeanF77** [jspreadsheet/ce#1297]
With jExel v4.0, is it possible to embed images in the sheet ("base64" image format) ?

Is it possible to export a sheet with these embedded images ?

Regards.

Jean-François.

**Comment by hodeware** [comment]
Yes, you can do that.

A few options:
https://bossanova.uk/jexcel/v4/examples/image-upload

**Comment by JeanF77** [comment]
Nice and thank you, but about the second part of my question "Is it possible to export a sheet with these embedded images ?" (export to XLS, for example), is it possible with the jExcel CE edition or only with the jExcel Pro edition ?

 I have made some tests with the jExcel.download plugin, with the CE edition, but that fails.
