### ISSUE TITLE
V4 Change background color of readonly cell

### ISSUE THREAD

**Issue by jpsarno** [jspreadsheet/ce#1298]
Hello.

I have a code like this:
grid.setStyle('H' + lineNum, 'background-color', '#FF0000');
grid.setStyle('H' + lineNum, 'color', '#FFFFFF');

It works fine in the v3, the background of readonly changed ok. But in the v4 not.

Exists something to do to change the background color of readonly cell?

**Comment by hodeware** [comment]
grid.setStyle('H' + lineNum, 'background-color', '#FF0000', true); // where true is to force the updates over the readonly columns.
