### ISSUE TITLE
how to add footer by programmly ?

### ISSUE THREAD

**Issue by benci042** [jspreadsheet/ce#1299]
Hi 

I'm try using setFooter function to create footer .it's not working when i use it .(pro v7)

BTW, is is possible to merge cell when i using init data on table footer ?

thanks.

**Comment by GBonnaire** [comment]
Hi,

How you initialised your Footer ? like this : https://jexcel.net/v7/examples/footers ?

in footer, i think you can't merge cells. But with DOM manipulation, you can make like merge (colspan)

**Comment by benci042** [comment]
Hi.
First ,table without footer when i initialized. 
How can i  create footer using table.setFooter  function ?

**Comment by GBonnaire** [comment]
```javascript
var options = {/* ..your options.. */} 
var DomElement = document.getElementById('MyElement'); // DomElement
MyTable = jexcel(DomElement, options);
MyTable.setFooter([
        [
            '', // Empty Cell
            'Total',
            '=SUM(B1:B10)',
            '=SUM(C1:C10)'
        ]
    ]);
```

**Comment by benci042** [comment]
Thanks. it's working.
