### ISSUE TITLE
Not an issue but a column / cell question with MASK

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#1300]
Hello.
Is it possible to assign a mask to a cell and not the whole column OR assign the mask to a column then using the update table function remove specific masks from cells?
I am trying to use a column layout which contains :
A1 = Text
A2 = Number
A3 = Number with Mask of £ #,##.00
A4 = Text
Many thanks

**Comment by GBonnaire** [comment]
Hi,

If you use Jexcel Pro : Yes
in version CE : No

Good luck 😉

**Comment by ghost** [comment]
Hello
Thanks for that. Found the appropriate code that shows that. Guess a purchase is in order.
