### ISSUE TITLE
allowManualInsertRow and allowManualInsertColumns problems

### ISSUE THREAD

**Issue by ilmistra** [jspreadsheet/ce#1302]
In Jexcel v4

allowInsertRow: true,
allowInsertColumn: true,
allowManualInsertRow: false,
allowManualInsertColumn: false,

I can insert rows and columns from the code, but even manually right-clicking the table. Is it a bug?

**Comment by GBonnaire** [comment]
Hi, 

I think no:

allowInsertRow it's global authorization to insertRow.
allowManualInsertRow it's just automaticaly insertRow when you type Enter in end of file.


But, if you use custom contextMenu, you can insert condition (If) for not authorization insertRow by contextMenu if you allowManualInsertRow : false.

Same behavior for Column

**Comment by hodeware** [comment]
To block from code and from the contextMenu. You define everything as false. If you wish to keep from code, you should customize the contextmenu.

**Comment by ilmistra** [comment]
Gotcha! Thank's
