### ISSUE TITLE
Automatically scroll when selected rows are outside of the view

### ISSUE THREAD

**Issue by leopsidom** [jspreadsheet/ce#1304]
When there are many rows of data, some rows will be outside the current view. How can I select elements outside the view in the column if I have already started from a cell in the view ? In microsoft excel, when we move mouse towards the end of the sheet, it will automatically scroll up so that you can select elements while scrolling. But it doesn't seem like the behavior in Jexcel, as it doesn't do auto scroll. This behavior is a little inconvenient. Is it possible to make the behavior default ?

Example jsfiddle: https://jsfiddle.net/ryudz73n/. Let's say if I started from row 5, and I want to select all rows below and I won't be able to do this via the mouse dragging behavior.

**Comment by GBonnaire** [comment]
it's an feature of Pro version

**Comment by leopsidom** [comment]
Thanks for the response. It looks like the differences between pro and ce listed here are quite limited then: https://jexcel.net/v7/

**Comment by hodeware** [comment]
Leo, 

The list there is a more an overview summary. We have developed the products a lot and now we should give more attention to the documentation updates. That is ongoing and there lot of new things coming in the next few weeks. The event you are referring to is currently available on the Pro distribution only, but we have plans to make it wider available in future releases.

**Comment by JanithaS-cv** [comment]
Hi @GBonnaire,
may I know the documentation for Pro version feature that you have mentioned above.

**Comment by GBonnaire** [comment]
Hi, 

You have all information here : https://jspreadsheet.com/v9/

Have good day

**Comment by hodeware** [comment]
https://jspreadsheet.com/v9/docs/viewport (pagination, fullscreen or tableOverflow)
