### ISSUE TITLE
Drag row line is very thin and most of the time user is getting confused with select a row and drag row 

### ISSUE THREAD

**Issue by kallaguntaashok** [jspreadsheet/ce#1307]
is it possible to give a symbol or some indication to the user to drag the row so that it will not confuse the user. 

as of now, it is working if the user keeps the mouse over on the right border of the first cell then it will show the drag option, most of the time user is struggling to get the drag option as it is a very thin line.

**Comment by kallaguntaashok** [comment]
I got the solution.

![image](https://user-images.githubusercontent.com/26366259/106738505-fedf0900-663d-11eb-8c8e-c8cb0175076a.png)

I added the symbol to move the row, it is working fine.

**Comment by rvieracds** [comment]
@kallaguntaashok I'm facing the same... could you provide an example or some code to see how to do the same? I mean, adding a button to indicate the dragging action and how do you handle it? Thanks1
