### ISSUE TITLE
there is an error output in console when right click on column's header

### ISSUE THREAD

**Issue by StrongAndyZhang** [jspreadsheet/ce#1308]
![image](https://user-images.githubusercontent.com/19901968/106687963-21562f80-6608-11eb-85c7-2d54ceee8d9a.png)

![image](https://user-images.githubusercontent.com/19901968/106687648-8198a180-6607-11eb-87f8-87a18ec91044.png)

**Comment by GBonnaire** [comment]
I have propose a fix for that,

thanks

**Comment by Ruan-Miguel** [comment]
This error has been resolved on v4
