### ISSUE TITLE
cell scrolled offscreen not being scrolled on screen with arrow keys

### ISSUE THREAD

**Issue by kathrynlmclark** [jspreadsheet/ce#131]
my table is too wide to fit on the screen so i'm using overflow-y:scroll.

when i use the arrow keys to move between the cells i was hoping that the table would auto scroll left to right to guarantee that the newly selected cell was visible.  

is there a switch to enable that or a callback that i can use to signal when to check if current cell is offscreen and scroll myself?  

thx

**Comment by pphod** [comment]
Yes, onselection is available.

**Comment by morgunder** [comment]
@paulhodel cool - what's the best way to get the current selection in window coordinates ?

**Comment by pphod** [comment]
The event should give you that. Take a look on this

https://bossanova.uk/jexcel/examples/tracking-changes-on-the-spreadsheet
