### ISSUE TITLE
lazyLoading freezes table when scroll reaches to bottom

### ISSUE THREAD

**Issue by yldrmali** [jspreadsheet/ce#1313]
Initial conditions:
```js
minSpareRows:1,
lazyLoading:true,
tableOverflow:true,
```
I added 130 row to table.

When scrollling down with mouse, page stucks when it reaches to bottom(generally when row count reaches 100) and this is a problem about clientHeight,scrollHeight and scrollTop calculation I think.

**Comment by GBonnaire** [comment]
Hi,

I have test, and i can't reproduct you problem, can you make a jsfiddle with your problem and we look that.

**Comment by yldrmali** [comment]
Sure, here is the link. When it's a 100, it stucks and it's also arbitrary.
[lazyLoading stuck](https://jsfiddle.net/yldrmali/xcf8avm9/6/)

- scroll up is flawless
- scroll down has some problems

**Comment by yldrmali** [comment]
> Sure, here is the link. When it's a 100, it stucks and it's also arbitrary.
> [lazyLoading stuck](https://jsfiddle.net/yldrmali/xcf8avm9/6/)
> 
> * scroll up is flawless
> * scroll down has some problems

Interesting, I tried to reproduce it in another computer. It works flawlessly now.

**Comment by GBonnaire** [comment]
With which navigator have you problem ?

i check with Chrome, and it's work, when you scroll down, you have light freeze for load row, but not stuck

**Comment by yldrmali** [comment]
I tried it again, here are my results:

- comp1- chrome-15 inch - 1920*1080 resolution - stuck
- comp2- chrome-15 inch - 1920*1080 resouluton -  stuck
- comp2 (hdmi connection) -chrome- 27 inch - 1920*1080 resolution-not stuck

It seems arbitrary. Even in the same application , while one table is stuck another is not and I've encountered this situation many times. Conditon below sometimes not met. In one case, left side was 3489px and right side is 3490 px so it stucks. 


```js
obj.wheelControls=function(e){
//...
  if (obj.content.scrollTop + obj.content.clientHeight >= obj.content.scrollHeight) {
  //do some magic here
}
```
Light freeze you mentioned is timeout time (100 ms) probably and it's expected.

![ss](https://user-images.githubusercontent.com/52608518/108458231-4b088b00-7285-11eb-94d9-55d0d87d8bd0.png)

**Comment by GBonnaire** [comment]
I search to reproduct in my PC.

In waiting, can you test in https://jexcel.net/v7/examples/lazy-loading if you have a same problem ?

**Comment by GBonnaire** [comment]
@paulhodel do you have an idea ? or have know a same problem ?

**Comment by yldrmali** [comment]
I've tried in v7 jexcel and can't reproduce there because logic is different there. Lazy loading happens before scrollbar hits bottom so it works flawlessly. Same lazy loading logic can be applied for Jexcel CE

**Comment by GBonnaire** [comment]
Hi,

I have success to reproduct, only 1 time, but is not only on bottom, but on top too. and when i move mouse (some pixel), scroll not freezed. i think that jexcel CE should considerate mouse is out of table.

Can you try to reproduct, and when it's freezed, move mouse on table and scroll again ?
