### ISSUE TITLE
auto resize cell width when text width over default width

### ISSUE THREAD

**Issue by jhlee910609** [jspreadsheet/ce#1316]
auto resize width when innerText over default width(origin width).
I wanna make this new feature for me and us!

**Comment by GBonnaire** [comment]
for jExcel Pro. This feature already exist : https://github.com/Guillaume-Bo/jexcel-plugins-and-editors/tree/master/plugins/autoWidth

**Comment by jhlee910609** [comment]
could I develop this feature for CE version?...?

**Comment by GBonnaire** [comment]
Yes, 😊 

But wait, new version 8 coming soon (in few week) With feature "plugins". In this version you can integrate plugins, plugins autoWidth will be compatible v8 (Free and Pro).

But the version CE continue, you can inspired by my plugin for integrate to CE version 😉

**Comment by jhlee910609** [comment]
Thanks! I'll waiting for this feature. Could I get your repo url about plugins you mention above? I'm interested in it, just now. And I always thank you for jexcel. I Love it!

**Comment by GBonnaire** [comment]
My repository : https://github.com/Guillaume-Bo/jexcel-plugins-and-editors/

Official repository for Jexcel v7 and v8 : https://github.com/jspreadsheet/plugins

My premium repository : https://repo.gbonnaire.fr

**Comment by methnen** [comment]
@jhlee910609 Did you ever end up with a good autoWidth column method that worked within Jspreadsheet CE?
