### ISSUE TITLE
remove all value of selected cells when multi-cell selected and space key pressed

### ISSUE THREAD

**Issue by jhlee910609** [jspreadsheet/ce#1317]
remove all cell when multi-cell selected and space key pressed.
I wanna clear this issue by developing new feature.

**Comment by GBonnaire** [comment]
Hi,

You can overwrite jexcel.keyDownControls

And extract of code for del touch (46) :
space is which code 32

```javascript
if (e.which == 46) {
  // Delete
  if (jexcel.current.options.editable == true) {
          // Change value
          jexcel.current.setValue(jexcel.current.highlighted, '');
   }
}
```

**Comment by jhlee910609** [comment]
Thankx :) I love it!
