### ISSUE TITLE
calendar popup is not aligned with cell when using relative position

### ISSUE THREAD

**Issue by kathrynlmclark** [jspreadsheet/ce#132]
trying to align the calendar popup with the cell.  but the calendar is not very interested in playing along.  any tips on positioning the calendar that i could try?

![screen shot 2018-04-26 at 3 44 27 pm](https://user-images.githubusercontent.com/24375939/39328242-bf253284-4968-11e8-9ea6-711a5cf40ab6.png)

**Comment by morgunder** [comment]
(switched github accounts - this is my primary one) we have a position = relative in tabs content, and jexcel insert the calendar inside the cell (td) with position absolute. and get its show position as if it was inserted in body.

**Comment by pphod** [comment]
Try to remove position relative from where your table is being placed

**Comment by morgunder** [comment]
@paulhodel thought that would be needed.  will see what i can do there.  might be worth a doc note

**Comment by pphod** [comment]
This has been fixed in the latest update in the master repository.

**Comment by morgunder** [comment]
@paulhodel thank you
