### ISSUE TITLE
Formulars don't work with Thousands separator in europe format

### ISSUE THREAD

**Issue by luke10001** [jspreadsheet/ce#1320]
Hello everybody,
I see that there are very strange things going on when using thousand separators (europe).
The cells are defined as follows:
 **{ type: 'numeric', title:header_array[iter],width:'150px',mask:'#.##,00',decimal:','};**

I tried different JS files/versions from JExcel and the results are always different. Sometimes, if you copy-In the number from an external sheet, the thousand points are converted to commas. Sometimes they are displayed correct but the formulars do not work with it. 
With the following combination of js and css files the numbers are displayed right in the european format. But if I use the SUM formular on that numbers, the result is completely wrong.
I used the jexcel.js  from the master as local file.

<script src="js/jexcel.js" type="text/javascript"></script>
<script src="https://jsuites.net/v3/jsuites.js"></script>
<link rel="stylesheet" href="https://jsuites.net/v3/jsuites.css" type="text/css" />
<link href="css/jexcel.css" rel="stylesheet">

Is that issue known? Thank you

**Comment by GBonnaire** [comment]
Hello luke,

i have same problem before passed to Pro version with jSuite v3. With format Europe # ###,00 coma not work fine.

test in v4 of jSuites and in your example : test with no point, only coma, it's work better.

**Comment by hodeware** [comment]
There are two aspects. First, the raw data should be a number (integer or double). Second, you must upgrade jSuites v4 which processes the number correctly (mask).
