### ISSUE TITLE
How to hide and show button based on other cell value?

### ISSUE THREAD

**Issue by lodhaneha7** [jspreadsheet/ce#1322]
I want to hide and show  two different buttons in a single cell based on other cell value. I used **updateTable** function but didn't get the results. Is there any other way to do this?

Image Description: Here I want Create Role Button if DepartmentID equals to 10.
![2021-02-18](https://user-images.githubusercontent.com/54946128/108390475-baa35980-7236-11eb-85b6-5472f813d03d.png)
@paulhodel

**Comment by hodeware** [comment]
Make sure you have stripHTML disabled them you can add HTML code to the cell, updateTable is also an option (slower). Third option is to create a custom editor.
