### ISSUE TITLE
[BUG] IF allowInsertColumn: false, ignore center columns, instead last columns.

### ISSUE THREAD

**Issue by Ajtak** [jspreadsheet/ce#1323]
If used allowInsertColumn: false, 
If copy table, and paste to jspreadsheed, is ignored middle colums, instead of latest columns.

![image](https://user-images.githubusercontent.com/4963819/108595431-1b8a7900-7380-11eb-995e-53d65118144b.png)
## Expected result:
![image](https://user-images.githubusercontent.com/4963819/108595619-2eea1400-7381-11eb-908b-9a050bf77ed8.png)

See https://jsfiddle.net/Ajtak/kp1wzLuj/

**Comment by Ruan-Miguel** [comment]
This error has been resolved on v4
