### ISSUE TITLE
How to access jexcel object globally

### ISSUE THREAD

**Issue by AL-Kateb** [jspreadsheet/ce#1325]
Hi, even though this is probably not an issue, I looked everywhere including the documentation, and I could not find an answer.

What I want is, to place buttons outside of the table, where I can access the highlighted data and export it or do whatever, but I cannot seem to find a way to access this data globally.

Any help? Thanks.

**Comment by GBonnaire** [comment]
Hi,

You can set in variable on init

var myTable = jexcel(DOMElement, options);

After, you can call with this variable myTable.getJson(true);

if your jexcel (or jspreadsheet) is active, you can use jexcel.current. And after jexcel.current.getJson(true);

Other way :

Get DOMElement of Jexcel : 
var myTable = document.getElementById(‘yourID’).jexcel;

**Comment by GBonnaire** [comment]
If you use last version, replace jexcel by jspreadsheet
