### ISSUE TITLE
jQuery example doesn't work.

### ISSUE THREAD

**Issue by jvmap** [jspreadsheet/ce#1326]
Hello there,

Just letting you know that this example doesn't work in Chromium 88.
https://bossanova.uk/jspreadsheet/v4/examples/jquery

Click Add New Row or Add New Col gives this error in the developer console:

```
Uncaught TypeError: $(...).jspreadsheet is not a function
    at HTMLInputElement.onclick (jquery:224)
onclick @ jquery:224
```

**Comment by GBonnaire** [comment]
Hey,

Yes, in waiting, you can use $(...).jexcel('insertRow');

@paulhodel paul, i think there is a problem with migration to jspreadsheet 😊

**Comment by hodeware** [comment]
That has been fixed.
