### ISSUE TITLE
can fomular get values outside of jexcel and update automatically?

### ISSUE THREAD

**Issue by flywalt** [jspreadsheet/ce#1327]
for example, there is a value X using inputbox
A3=min(X*A1,A2)
and if a user changes X by typing a new value, i want the A3 to update automatically.
is this possible so far? thx

**Comment by GBonnaire** [comment]
Hi,

Yes, but after change value, you must refresh JExcel :

jexcel.current.refresh();

or

MyTable.refresh();//MyTable is an instance of JExcel

**Comment by hodeware** [comment]
Yes, you can do that. But, to change the value back in the spreadsheet, you must do:
instance.setValue('A3', min(X*A1,A2); // to update the value on the table.
