### ISSUE TITLE
React Example is not working for the latest version

### ISSUE THREAD

**Issue by muserxu** [jspreadsheet/ce#1329]
Dear Developers of the jspreadsheet,

Since the jexcel has been rename to jspreadsheet, the react example is deprecated. It show `Module not found: Can't resolve 'jexcel'`.

Which variable should I use to import jspreadsheet into React Functional Components?

**Comment by hodeware** [comment]
Please use this basic project as a reference.
https://codesandbox.io/s/jspreadsheet-ce-and-react-dzpqj

**Comment by muserxu** [comment]
Thank you!
