### ISSUE TITLE
how to get auto complete control to not be constrained to the column?

### ISSUE THREAD

**Issue by morgunder** [jspreadsheet/ce#133]
ideally i'd like the popup typeahead to be able to float over the table and be any size - is there a trick to making that happen?

![screen shot 2018-04-26 at 3 42 24 pm](https://user-images.githubusercontent.com/3998336/39328170-7a429012-4968-11e8-8b33-415419d815f6.png)

**Comment by pphod** [comment]
Sorry, I did not quite understand what you want to do.

**Comment by morgunder** [comment]
@paulhodel was able to work around this.
