### ISSUE TITLE
Column types not working with React

### ISSUE THREAD

**Issue by muserxu** [jspreadsheet/ce#1330]
I have tried setting the columns in configs as `columns: [{title: 'A', type: 'number'}]`, however, I can still enter text input for the column. Is there a way to check the user input type or force users to input numeric values only?

**Comment by muserxu** [comment]
I tried setting `columns: [{title: 'A', type: 'numeric'}]`, but it didn't work either

**Comment by GBonnaire** [comment]
in numeric, you must define a mask in properties of column for force users to input only numeric

mask:'#,#', decimal:","  // For float
mask:'#' // For int

**Comment by muserxu** [comment]
@Guillaume-Bo Thank you for the reply. However, there is a weird problem. In North America, people tend to use "." as the decimal break point. Therefore, I set the column type as `{type: 'numeric' , mask:'#.#', decimal:"." }`. When I tried to input the decimal break point using the "." from numpad, it doen't work. Only the "." from the main keyboard section is allowed.  

Code sandbox example: https://codesandbox.io/s/jspreadsheet-ce-and-react-forked-w8vlp?file=/src/App.js

**Comment by pphod** [comment]
#.## or #,## or #'##

**Comment by GBonnaire** [comment]
Yes in fact, it's not good working with "."

@paulhodel with this masks, it's not working good, you must add 4 number for add ".", and you can not enter "." with keyboard

**Comment by hodeware** [comment]
That has been fixed in jSuites v4.2.5+
