### ISSUE TITLE
Extract pattern from a text column using formulas

### ISSUE THREAD

**Issue by leopsidom** [jspreadsheet/ce#1332]
I'm trying to extract number from a text column using `REGEXEXTRACT` function. And my formula looks like: `=REGEXEXTRACT(C2, '[0-9]+')` But this is giving me an error. It works on a literal string `=REGEXEXTRACT('50 views', '[0-9]+')`.

Is it possible to use this formula on a column ?

**Comment by GBonnaire** [comment]
Hi,

can you make a jsfiddle ?

In JExcel you can use custom formula, your formula must declare in global (i.e. window.MYFORMULA = function(arg1, arg2, ...) {}
If your formula work with string, try to make a console.log with typeof of first args, it's possible JExcel give you a number not a string

**Comment by leopsidom** [comment]
Sure, I created a jsfiddle here: https://jsfiddle.net/opa2mL0e/. You can see that I have an error in B1 which contains the `regexextract` formula. I'm not declaring any formula but just using the built in `REGEXEXTRACT` method.

**Comment by leopsidom** [comment]
Maybe a better example with here: https://jsfiddle.net/u8erhmsp/. I'm seeing it works for one cell but not the other 3.

**Comment by hodeware** [comment]
The problem here is, the autoCasting is true for default. So, it already extracts the number from the text by default, which means the method will receive a number and that generates an error. To make sure your example works, just change autoCasting to false, and everything will work fine.

jexcel(document.getElementById('spreadsheet'), {
    data:data,
    autoCasting: false,
    columns: [
        { type: 'text', title:'views', width:120 }
     ],
     minDimensions: [20, 10]
});

**Comment by leopsidom** [comment]
Thanks. `autoCasting` solves the problem.
