### ISSUE TITLE
Cell name with the html table

### ISSUE THREAD

**Issue by bilalCatic** [jspreadsheet/ce#1333]
Is it possible to keep the cell name property when jspreadsheet is created from a static HTML table?

I am trying to POST data from the table without copying data from the jspreadsheet table to the hidden HTML table

With this approach, cell name is removed:
(ASP.NET Razor syntax)

```html
<td name="someProperty[@i]">@someProperty[i]</td>
```

**Comment by hodeware** [comment]
I will recommend you get the data from spreadsheet, using getData:
var dataToBeSubmited = JSON.Stringify(yourInstance.getData());

But if you wish to add the names, you can use the onload event. The internal properties would be something like this:
for (var j = 0; j < instance.records.length; j++) {
for (var i= 0;i < instance.records[j].length; i++) {
     instance.records[j][i].setAttribute('name', 'xxxx');
}
}
