### ISSUE TITLE
How to freeze the nested header while scrolling down?

### ISSUE THREAD

**Issue by jlzhou** [jspreadsheet/ce#1335]
Thanks, it is great to have sample code.

**Comment by hodeware** [comment]
Sorry, that feature is not possible natively in none of the current distributions. But, I believe you can use some CSS to make that happen using position: sticky. That will be present in future releases (v8+)

**Comment by jlzhou** [comment]
@hodeware Thanks, I made it frozen by adding the following css code:

.jexcel > thead > tr > td {
  z-index: 31;
  top: -1px;
}

.jexcel > thead > tr:nth-of-type(2) > td {
  top: 24px;
}

.jexcel > thead > tr:nth-of-type(3) > td {
  top: 48px;
}

.jexcel > thead > tr:nth-of-type(4) > td {
  top: 72px;
}

.jexcel > thead > tr:nth-of-type(4) > td {
  top: 96px;
}
