### ISSUE TITLE
Hide decimal places but retain value with mask?

### ISSUE THREAD

**Issue by metford** [jspreadsheet/ce#1339]
Perhaps my understanding of JQuery Mask is wrong; but is it possible to format the cells to take a decimal value; mask it without any decimal places, but keep the original value? 

`mask:'£ #,##0.00', decimal:'.',

So input is, 150.45
Cell should show 150
Entering the cell / double click shows 150.45 and enables you to edit.
Any changes display new value without decimal places visilble.

Has anyone achieved this?

thanks

`

**Comment by hodeware** [comment]
You can perform that using onchange or using a customColumn.

Basically, you change the innerText of the cell, that won't affect what is the raw data since that is stored internally.
