### ISSUE TITLE
[TypeScript] publish new package name to DefinitelyTyped

### ISSUE THREAD

**Issue by davidroeca** [jspreadsheet/ce#1340]
There is currently a package named [@types/jexcel](https://www.npmjs.com/package/@types/jexcel) and it is probably worth adding a new version that matches the name here (`@types/jspreadsheet-ce`). I may get around to this later this week; for now, I'm just using a declaration within the app I'm working on:

```d.ts
declare module "jspreadsheet-ce" {
  // Not sure all declarations here are necessary
  export * as jexcel from "jexcel"
  export * as jspreadsheet from "jexcel"
  export default jexcel
}
```

**Comment by averybross** [comment]
this was done, right?

**Comment by davidroeca** [comment]
I believe so, yes :+1:
