### ISSUE TITLE
Cannot use with NextJS

### ISSUE THREAD

**Issue by davidroeca** [jspreadsheet/ce#1341]
When attempting to use this package with NextJS, the following error occurs:

```
Failed to compile

./node_modules/jsuites/dist/jsuites.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/jspreadsheet-ce/dist/index.js
```

The root of the issue is that there is a CSS import within this package, which NextJS does not support.

NextJS recommends the following: `Reach out to the maintainer and ask for them to publish a compiled version of their dependency.` Would this be possible? Would probably just be a matter of having a separate JS file that does not import the CSS file but does everything else the same way.

**Comment by davidroeca** [comment]
Related:
* https://github.com/fullcalendar/fullcalendar/issues/5393
* https://github.com/vercel/next.js/issues/706

**Comment by hodeware** [comment]
I will be working on a solution this week.

**Comment by hodeware** [comment]
Ok, that has been removed. From v4.7.3 the CSS should be the handler on the application.

**Comment by karanYC** [comment]
hey @hodeware was there a solution for this? I am facing the same problem
