### ISSUE TITLE
Changing Default Font & Size

### ISSUE THREAD

**Issue by frommyuk** [jspreadsheet/ce#1342]
Hi Paul,

I have been playing with this wonderful tool for a couple of days and have managed to get it working through FileMaker on Windows, which is not simple what with the interface being based in IE11! Anyway, I am stuck and unable to get the correct syntax to change the font on installation. Nowhere in the css seems to point to the font-family that is used, and having tried changing everything. Can you point me in the right direction please?

Many thanks

James

**Comment by rawandhawez** [comment]
Hello James

You can try something like the below, it worked for me.
```
.jexcel {
  font-size: 9px;
  font-family: 'Courier New', Courier, monospace;
} 
```

**Comment by frommyuk** [comment]
Oh my word - it's all in the syntax and knowing where to put it!

Thank you so much Rawand - you've saved me hours!!


   <http://www.storganise.co.uk/>
If you think we are worth 5 stars on Google, Click Here <http://search.google.com/local/writereview?placeid=ChIJM5bAf5N730cRsM2EPT58EO8> If not, please tell us how we can be.

**Comment by hodeware** [comment]
Thanks
