### ISSUE TITLE
Column calendar with DD/MM/YYYY... Modified wrongly after editing

### ISSUE THREAD

**Issue by jk-12345** [jspreadsheet/ce#1347]
Hi,

I can't use the date format for "french" language... DD/MM/YYYY.

All dates can be displayed properly but when I edit one date, the calendar transformed it into a strange formating including wrong numbers into it.

https://jsfiddle.net/937jpqs1/

This is the code of the fiddle... Am I missing / doing something wrong here ?

Thks for your help !

<html>
var data = [
    {
        'title': 'Jazz',
        'brand': 'Honda',
        'date': '02/03/2021',
    },
    {
        'title': 'Civic',
        'brand': 'Honda',
        'date': '02/03/2021',
    },
];

jexcel(document.getElementById('spreadsheet'), {
    data:data,
    columns: [
        {
            type: 'text',
            title: 'Car',
            width: '120px',
            name: 'title'
        },
        {
            type: 'dropdown',
            title:'Make',
            width:'200px',
            source:[ "Alfa Romeo", "Audi", "Bmw", "Honda" ],
            name: 'brand',
        },
        {
            type: 'calendar',
            title:'Available',
            width:'200px',
            name: 'date',
            options:{format:"DD/MM/YYYY"}
        }
    ]
});

**Comment by hodeware** [comment]
A working example:
https://jsfiddle.net/spreadsheet/htcy350z/

The raw dates should be "without" format (YYYY-MM-DD HH:MM:SS).

**Comment by jk-12345** [comment]
Great, thanks.

So... We keep the raw data in the shape "YYYY-MM-DD HH:MM:SS"... Ok
