### ISSUE TITLE
filter: dropdownFilter

### ISSUE THREAD

**Issue by Shinobilex** [jspreadsheet/ce#1348]
is there a way to have the first value of the dropdown menu selected by default instead of empty (see example in 2 
CONDITIONAL DROPDOWN) or if it's possible to be equal to a specific value as the default selected option?

**Comment by GBonnaire** [comment]
For defined default value, you must set value of cell.

You can user oninsertrow event for defined defautl value on new row

**Comment by Shinobilex** [comment]
> For defined default value, you must set value of cell.
> 
> You can user oninsertrow event for defined defautl value on new row

hi thanks for getting back.
is there also a way to get the selected value from the dropdown menu? which event do you use? 

thanks

**Comment by GBonnaire** [comment]
Yes, with first argument you have access to all data with method getValue (example : `el.jspreadsheet.getValue(‘A1’);`)

You have other event if you want reset dropdown 2 with first dropdown (onchange)

See online documentation for get all events 😉
