### ISSUE TITLE
How to modify source of dropdown list

### ISSUE THREAD

**Issue by dmiron** [jspreadsheet/ce#1349]
Hi

I have two drop down list.  Dropdown 1 and dropdown  2.  Once "dropdown 1" is selected "dropdown 2" is updated with content to reflect the selected item in "dropdown 1".

I have followed the example for conditional dropdowns  and it works if the "dropdown 2"  list are built off a super list which is the "source" for the "dropdown 2".  

Currently, when I select an item from "dropdown 1" the correct list appears in "dropdown 2" but upon selection of an item from the list a corresponding item from the original "source" of  "dropdown 2" is selected .  

The reason been that the dropdown list in the application I am working on are all very different and do not work off a super list as in the examples provided.  It seems the "source" for "dropdown 2" is not updated though what appears in the list is.  

Any help much appreciated.

Is there a work around for this?

Kind regards

David

**Comment by GBonnaire** [comment]
Hi, 

i think understand your problem. Dropdown keep current value in item, it's why you have old value selected.

For fix that, you can use event of jexcel onchange and when first dropdown it's call, set value empty in second cell with dropdown 2

```javascript
jspreadsheet(el, {
    onchange(instance, cell, x, y, value) {
          if(x==0 && y==0) { // coordinate of cell dropdown 1
              instance.jspreadsheet.setValue('A2','');
         }
    },
});
```

**Comment by hodeware** [comment]
Hi David,

If you have a dropdown for the column, the source should include all possible answers. When the user opens the dropdown you can filter what items from the source you will show to the user and what items should be hidden. 

If you wish different options for your dropdown, but you cannot declare all possible options you have potentially two options. 
1) Remote searching (this means, your source only contains selected answers in the table). As soon as the user starts typing something options will be shown from a remote server, and as soon the user selects one item, that item will be included in the column as default.

2) Define a dropdown editor on the cell level. It means you can have an editor definition different from whatever you have defined on the column level.

This example might show an example using the cells:{} attribute.
https://jspreadsheet.com/v7/cases/payment-calculator
