### ISSUE TITLE
copy / paste doesn't copy the read only cells.

### ISSUE THREAD

**Issue by morgunder** [jspreadsheet/ce#135]
while this seems like it is probably default behavior for form controls.  when calculated rows or other read-only calls are in place, still need to be able to copy / paste from them.  any tips on how to do that?

**Comment by pphod** [comment]
You can copy data from the table all selected cells, including the readonly cells. But, you can't paste on a readyonly cell. If you want to do that, you should treat your cells (remove the CSS class readonly) with an event: onbeforechange.
