### ISSUE TITLE
Is there an event listener that triggers whilst cells are edited?

### ISSUE THREAD

**Issue by Geddes-C** [jspreadsheet/ce#1351]
Firstly - many, many thanks for making jspreadsheet - it has been invaluable.

I would like to trigger a JavaScript function on each keypress whilst cells are being edited - similar to :

document.getElementById("... some HTML input box ...").addEventListener("input", function() {...}

Is this possible?

Many thanks and best wishes.

**Comment by hodeware** [comment]
Yes, you can use oneditionstart or oncreateeditor to implement that to add the native JS to the editor.

**Comment by Geddes-C** [comment]
Many thanks for your response. Would you be able to post a code snippet for that please - I am just a beginner...!
Best wishes.

**Comment by hodeware** [comment]
oneditionstart or oncreateeditor
