### ISSUE TITLE
Save as... How to add table title and do not include hidden columns

### ISSUE THREAD

**Issue by Shinobilex** [jspreadsheet/ce#1352]
Hi,

based on the documentation, I can't find any event handler regarding the Save as... (export). I was hoping to find something like "onsaveas" or "onexport" and from there give it a custom function where I can work my way around with the instance.

so how I can achieve that? which is to include the titles of each columns and do not include the hidden columns when saving to CSV file.

Thanks

**Comment by GBonnaire** [comment]
Hi,

yes you have no event for download function.

Download function based on copy function. for add header on download use `myTable.download(true);`

for option hiddenColumn, currently is not possible without rewrite download and copy function
