### ISSUE TITLE
I see a rectangle symbol when I paste

### ISSUE THREAD

**Issue by Shinobilex** [jspreadsheet/ce#1353]
Hi 
There's a strange symbol that appears when I paste the copied row?
How can I get ride of it?
![image](https://user-images.githubusercontent.com/81335933/113443713-82a83e00-93c0-11eb-87e3-4586b553377b.png)

**Comment by gitizen1** [comment]
New to this, but this is what I did... It looks like copied clipboard data has some sort of trailing null.
<pre>
var beforechange = function (instance, cell, x, y, value) {
    if (value == "\u0000") {
      return cell.innerHTML = "";
    }
 }
</pre>

**Comment by Shinobilex** [comment]
that did the trick! thanks
