### ISSUE TITLE
Can I programmatically blur jspreadsheet? 

### ISSUE THREAD

**Issue by Geddes-C** [jspreadsheet/ce#1355]
I would like to programmatically blur jspreadsheet then focus on another HTML element, such as:

document.getElementById("spreadsheet").blur()
document.getElementById( ... ).focus();

However, this does not seem to work. Is it possible?

Many thanks and best wishes.

**Comment by GBonnaire** [comment]
hi

yes it's possible :

for blur use
`myTable.resetSelection(true);` or` document.getElementById("spreadsheet").jspreadsheet.resetSelection(true);`

for focus use :
`myTable.updateSelectionFromCoords(0,0,0,0)` or `document.getElementById("spreadsheet").jspreadsheet.updateSelectionFromCoords(0,0,0,0)`

**Comment by Geddes-C** [comment]
Great - thanks for your help.
Best wishes.
