### ISSUE TITLE
Multi selection of  rows(non consecutive)

### ISSUE THREAD

**Issue by Ashwin2488** [jspreadsheet/ce#1358]
Is there a way to select multiple rows that are not consecutive?

Steps to reproduce.

1. click on a row (row 1) to select it.
2. Hold Ctrl key and click on row 3.
3. The expected behavior is that only row 1 and row 3 are selected.

But the actual behavior is that rows 1,2,3 gets selected. Is there a way to achieve the desired behavior?

**Comment by GBonnaire** [comment]
currently no.

**Comment by Ashwin2488** [comment]
Will close this issue since there is already a feature request on this.

**Comment by anaspsi** [comment]
> Will close this issue since there is already a feature request on this.

I try on 

- jspreadsheet  Pro ==> available
- jspreadsheet CE ==> not available
