### ISSUE TITLE
Add "hidden" or html row attributes/data

### ISSUE THREAD

**Issue by TiagoSilvaPereira** [jspreadsheet/ce#136]
Hi, thanks for this awesome lib!

I need a way to add attributes to the row because my data is provided by the backend and I need to identify changes to existent data using an identifier (ex: id, email, etc), to send an update ajax request.

At this moment I'm using a readOnly column to set the ID, but I want a more dynamic way like set a data-id attribute on the row, etc

Is there a way to make it?

Thanks!

**Comment by pphod** [comment]
You already have a hidden type for that purpose.

**Comment by TiagoSilvaPereira** [comment]
Thank you @paulhodel , the 'hidden' type works very well. I did not find it in the documentation.

Thanks!

**Comment by pphod** [comment]
Hi Tiago, if you have problem with the borders (when the hidden is the last one the border is not closing properly. So, I have commited a new version 1.5.1 you can get a fix on that.
