### ISSUE TITLE
How to make conditional updateTable scripts

### ISSUE THREAD

**Issue by kunalshewale** [jspreadsheet/ce#1360]
**Requirement**: To update the table initially for cell-specific classes and format the input numerical value for decimals. Later best on the user change to the row, only each cell within that row need to be updated.

**Current Implementation**: I have written the logic in the `updateTable` method. The code is as follows,

```
updateTable: (
      instance: any,
      cell: HTMLDivElement,
      col: number,
      row: number,
      val: string,
      label: string,
      cellName: string
    ) => {
      if (
        instance.jexcel.options.data[row][1] === 'CONTRACTS' &&
        columnsDetails.includes(col)
      ) {
        cell.classList.add('readonly');
      } else {
        cell.classList.remove('readonly');
      }
      
      if (col > 1) {
        const colVal = +String(val).replace(/,/g, '').replace('^0+(?!$)', '');
        if (isNaN(colVal) || colVal < 0) {
          cell.innerText = '$ 0';
          instance.jexcel.options.data[row][col] = 0;
        } else {
          cell.innerText = `$ ${new Intl.NumberFormat('en-US', {
            maximumFractionDigits: 2,
          }).format(colVal)}`;
          instance.jexcel.options.data[row][col] = colVal
            ? colVal.toFixed(2)
            : 0;
        } 
      }
    }
```

**Issue**:  The update script runs for each change and makes the rendering of the table component very slow (makes the webpage unresponsive at a time).

**Expectation**: The formatting code needs to be run only once the data is loaded and later only the affected row should be updated.
Please suggest, how to make sure certain update script run initially and other on the respective changes.

**P.S.** - I am using the `jspreadSheet` with React.

**Comment by GBonnaire** [comment]
Hi,

if you want, you have my plugin (required v7 pro)

https://repo.gbonnaire.fr/product/jexcel-plugin-conditionalstyle
https://demo.gbonnaire.fr/jExcel/plugin.conditionnalstyle.php

**Comment by MartinDawson** [comment]
You should be using mask to format the decimals. Not doing it manually. See here: https://jspreadsheet.com/v7/cases/payment-calculator

**Comment by hodeware** [comment]
Please take a look at this one:
https://jsfiddle.net/spreadsheet/84sLr52b/2/
