### ISSUE TITLE
oncomments Callback: how to get the cell id?

### ISSUE THREAD

**Issue by wwandreww** [jspreadsheet/ce#1365]
I found a non-documented `oncomments` callback that I would like to use in my project.

It looks like the library provides the comment data itself and the column title (which is null for unnamed columns):
```javascript
obj.dispatch('oncomments', el, comments, title);
```

Is there any way how to get the cell id (e.g. "C5" for example) or cell coordinates?
It will be really helpful to catch this callback and save the comment into the database.
Thanks

**Comment by hodeware** [comment]
I have just changed to:
obj.dispatch('oncomments', el, comments, title, cellName, x, y); 

You can find the changes on the master repository.

**Comment by wwandreww** [comment]
Great! Thank you for your quick reply!

**Comment by hodeware** [comment]
No worries, if you are open to an upgrade take a look at the Pro version... there are a lot of great features. Such as onsorting, onbeforesorting, onbeforesearch, you can bring a great level of customization to your products.
