### ISSUE TITLE
html editor is not working in jexcel table.

### ISSUE THREAD

**Issue by kallaguntaashok** [jspreadsheet/ce#1366]
I am trying to add an Html editor, I want to disable a toolbar, to do that I added the below condition in the jexcel.js file, it's not working, I added "allowToolbar: false" still it shows the tool bar and also tool bar icons not loading properly. 

jSuites.editor(div, {
                            focus: true,
                            allowToolbar: false,
                            value: value,
                        });

![image](https://user-images.githubusercontent.com/26366259/117158603-2f6d4500-addd-11eb-85b5-0e8d76b69099.png)

please let me know how to configure this.

1. I want to disable the toolbar, I just need a plain edit option.
2.  how to load icons in the editor.

**Comment by klren0312** [comment]
need add `<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Material+Icons" />`
to show the icon
