### ISSUE TITLE
Keyboard navigation out of the grid

### ISSUE THREAD

**Issue by brockfanning** [jspreadsheet/ce#1369]
I was wondering if anyone could point me to documentation of how to use the keyboard to navigate out of the grid. I was expecting to be able to tab out, but tab seems to move to the next column, and then create new columns. Thanks for any help!

**Comment by GBonnaire** [comment]
Hi,

You can use addEventListener on instance.el with `preventDefault()` and `stopPropagation()` and execute an blur of jspreadsheet

Example :

```javascript
var myTable = jspreadsheet(DOMElement, {/* your options */});

myTable.el.addEventListener('keydown', function(e) {
     if(myTable && !myTable.edition) { // Check if you note in edition mode
          if(e.which == 9) { // Tab - you can choose your key(s)
                 myTable.resetSelection(true); // Blur of myTable
                 e.preventDefault();
                 e.stopPropagation();
          }
     }
});
```

code no checked
