### ISSUE TITLE
I'm going to implement a new type of lazy loading...

### ISSUE THREAD

**Issue by Byloth** [jspreadsheet/ce#1370]
Hi, @paulhodel! 🙃

I'm currently working on a large application that use `jspreadsheet` to show simultaneously a large amount of data.  
The current behaviour of the lazy loading is pretty odd and it compromises the app UX.

For this reason, I'm going to implement a new type of lazy loading... A more "conventional" one.

I'll try to explain how this will work:  
The main goal of this implementation is to give the user a way to move around the sheet smoothly by simply dragging the scrollbar to the position he wants to see.

No more resizing of the scrollbar; no more replacing the scrollbar to the top.  
It'll simply be as it should be; properly sized from the beginning and once dragged to the bottom, the sheet will show the last rows.

- Is this implementation something that could be useful to the whole community?  
- Should I implement this feature just for me or outside this library?
- If this could be something interesting to you, should we agree on something?
- Can I start developing this and simply open a PR to this repo?

Thanks for your time. 😉

---

# Implementation details

### Required features:

- [ ]  Property sized table content.

### Nice-to-have features:

- [ ] Modular function to fetch data from other sources. (@Alex-Monahan)

**Comment by Alex-Monahan** [comment]
I would definitely be interested! The other use case I have for that type
of feature is to actually move the loading of rows all the way back to the
database (Ex: fetch new data as the user scrolls). If you could make the
"get more rows of data" function modular, that would help me!

Thanks,
Alex

**Comment by Byloth** [comment]
Beautiful, @Alex-Monahan!  
I'll update the Issue description! 😉

**Comment by hodeware** [comment]
Hi Byloth, that sounds interesting. It would be interesting to discuss a few options with you, if you would like to share your contacts with contact@jspreadsheet.com we can book something.

There are also a few things I will make sure is available. For example, onchangepage and onlazyloading events, that will help to intercept and change the behavior. Some developers use that to fetch data from the database.

**Comment by taifu** [comment]
This is a great idea! @Byloth keep us updated
