### ISSUE TITLE
Update cell with another input

### ISSUE THREAD

**Issue by kevinirlen** [jspreadsheet/ce#1371]
Hi

I don't know if this has been asked yet. Basically, I have an input field, when I click on a cell, the content of the cell shows up in the input field. (Similar to google sheet)

But when I try to edit the cell value from this input field, it doesn't work. Somehow the focus stays on the cell itself. 

How do I fix this this please ?

**Comment by GBonnaire** [comment]
maybe i don't understand your problem. If it is a case, can you create a jsfiddle for explain your probleme ?

If you want make a custom editor, you have an example here : https://bossanova.uk/jspreadsheet/v4/examples/column-types

if you want set value of cell with input out of spreadsheet, please use `myTable.setValue('A1', 'myValue');`

**Comment by fireclw** [comment]
> maybe i don't understand your problem. If it is a case, can you create a jsfiddle for explain your probleme ?
> 
> If you want make a custom editor, you have an example here : https://bossanova.uk/jspreadsheet/v4/examples/column-types
> 
> if you want set value of cell with input out of spreadsheet, please use `myTable.setValue('A1', 'myValue');`

I guess I know what his question is and I'm sharing same question:

For example, I'm creating a formula for my sheet, what I want to do is in Cell A1, create formula "=SUM(B1,C33,K3)".

But instead of type in the formula string, can I just type in “=SUM(" -> click on B1 -> String "B1" added to my Cell A1 formula "=SUM(B1," -> click on C33 -> String "C33" Add to formula, etc

Hope it clear the question and looking for your reply and help. 
Best

**Comment by GBonnaire** [comment]
like this : https://demo.gbonnaire.fr/jExcel/plugin.formula.php
But this plugin it's only for jSpreadsheet Pro

**Comment by hodeware** [comment]
There is no native implementation for that feature. But, you can implement that using third-party extensions.

**Comment by kevinirlen** [comment]
> There is no native implementation for that feature. But, you can implement that using third-party extensions.

Hmmm, do you have any third party in mind ?

**Comment by hodeware** [comment]
https://demo.gbonnaire.fr/jExcel/plugin.formula.php

**Comment by fireclw** [comment]
Thanks!

H. Paul ***@***.***>于2021年6月4日 周五下午2:36写道：
