### ISSUE TITLE
Edit header directly in table

### ISSUE THREAD

**Issue by html5maker** [jspreadsheet/ce#1372]
How is it possible to disable sort functionality and simply allow to edit header directly using the input?

**Comment by GBonnaire** [comment]
Hi,

for disable sorting, use `columnSorting:false`in option

```javascript
var myTable = jspreadsheet(DOMElement, {
    columnSorting:true,
}
```

for header rename, if you want not use prompt system, you can make your form and use `myTable.setHeader(columnIndex, "My new name");`
