### ISSUE TITLE
Custom component in column header

### ISSUE THREAD

**Issue by sdehaedocds** [jspreadsheet/ce#1373]
Hello! 
Is there any way to add a custom component to a column header? 
For example, allow to put a name and a button with an Icon?

**Comment by GBonnaire** [comment]
Hi,

on version CE, you can use HTML in header of column, and add button

example :

```javascript
var myTable = jspreadsheet(DOMElement, {
        columns: [
            {title:"Column <br> <button onclick='myFunction()'>Click me</button>", type:"text"}
        ],
        stripHTML: false,
});

function myFunction() {
   alert('Hello world!');
}
```

**Comment by sdehaedocds** [comment]
Awesome! Thanks

**Comment by sdehaedocds** [comment]
@GBonnaire I have one last question. Is it possible to use JSX instead of HTML? As I'm working with React, I tried something like this:
` stripHTML: false,
    columns: [
      {
        type: 'text',
        title: <button onClick={() => alert('ok')}>Click me</button>,
        width: 134,
      },`
      
But the output was: [object Object].
      
Thanks for the help!

**Comment by GBonnaire** [comment]
No only string value in titre with quote (simple or double) or « ` »

**Comment by gutofurlan** [comment]
Good morning, I understand the idea and I will apply it, but I would like to know how I can make the default add column already come with this button, it would be a default ...
How can I do it ...

**Comment by GBonnaire** [comment]
> Good morning, I understand the idea and I will apply it, but I would like to know how I can make the default add column already come with this button, it would be a default ...
> How can I do it ...

Hello,

You can use event `oninsertcolumn` and modify header on insert column programmaticaly or manually 😊 

```javascript
oninsertcolumn: function(el, columnNumber, numOfColumns, historyRecords, insertBefore) {
      var obj = el.jspreadsheet;
      for(var ite_col=0; ite_col < numOfColumns; ite_col++) {
           var column = +columnNumber+ite_col;
           if(obj.headers[column]) {
                   // Change header here
                   obj.headers[column].innerHTML ="My New title"; // You can use append with HTMLElement
                    // Keep the title property
                    obj.headers[column].setAttribute('title', obj.headers[column].innerText); // Title without HTML
                    // Update title
                    obj.options.columns[column].title = obj.headers[column].innerHTML;
           }
      }
},
```

Code not tester, and you should test with insertBefore, i think index column is wrong in my script with insertBefore 😉

**Comment by gutofurlan** [comment]
Perfectt but my problem is html not hender, only change text, html not render...

**Comment by GBonnaire** [comment]
Sorry, i don't understand your problem, can you make a jsfiddle ?

**Comment by gutofurlan** [comment]
I actually wanted to understand how you do it to be able to render the html

**Comment by GBonnaire** [comment]
Actually, `MyTable.headers` is an array (container) of DOMElement of all header. By this way, you modify directly HTMLElement (DOM) and the render is automaticaly 

in `MyTable.options.columns` contains all properties for generate DOM, but in your case, you want user can insert column and add this for all columns added. With `onbeforeinsertcolumn` you can't modify properties, with `MyTable.setHeader() `you can insert HTML in header, well, i use directly DOM container and modify directly HTML.

**Comment by gutofurlan** [comment]
Got it, thank you very much, would you know how I can do the same but for the line number?
Thanks

**Comment by GBonnaire** [comment]
Hi,

You have same object for row :
`MyTable.rows`

For Header (DOM) of specifics row
`MyTable.rows[RowIndex].children[0]`

And you have same event :
Event : `oninsertrow: function(el, rowNumber, numOfRows, rowRecords, insertBefore) { /* ... */ }`

You not have properties in options for row used in initialization, you should change all rows in `onload` event
Event : `onload: function(el, obj) { /* ... */ }`

Good luck 😉
