### ISSUE TITLE
Implement jexcel on nextjs

### ISSUE THREAD

**Issue by jeremywicaksana** [jspreadsheet/ce#1374]
Since jspreqdsheet CE using window i need to import the function through dynamic(). It works fine. However, when i did the same thing as in the integration on react example. It says the jspreadsheet is not a function. Is there any examples on how to implement it on nextjs?

**Comment by hodeware** [comment]
https://codesandbox.io/s/jspreadsheet-nextjs-6fhsz

**Comment by hodeware** [comment]
```
import { useRef, useEffect } from "react";
import jspreadsheet from "jspreadsheet-ce";

import "../node_modules/jspreadsheet-ce/dist/jspreadsheet.css";

export default function IndexPage() {
  const jRef = useRef(null);
  const options = {
    data: [[]],
    minDimensions: [10, 10]
  };
  useEffect(() => {
    if (!jRef.current.jexcel) {
      jspreadsheet(jRef.current, { minDimensions: [10, 10] });
    }
  });
  //jspreadsheet(jRef.current, options);
  return (
    <div>
      <div ref={jRef} />
    </div>
  );
}

```

**Comment by ohabash** [comment]
![Screen Shot 2022-10-03 at 11 15 24 AM](https://user-images.githubusercontent.com/15847500/193627359-dfc6283a-0aa5-4e91-bda0-78f3bb84e082.png)

How do i import like that? Im currently in version `"jspreadsheet-ce": "^4.11.1",`
