### ISSUE TITLE
In Jexcel v3.9.1 not able to restrict row dragging

### ISSUE THREAD

**Issue by dviswanathreddy** [jspreadsheet/ce#1378]
Is it possible to restrict Row dragging in jexcel 3.9.1.I tried to set rowDrag=false but not working. Please help us any possibility to restrict dragging.

**Comment by GBonnaire** [comment]
Hi,

Can you show how you set option rowDrag ? 

If you set rowDrag after loading, maybe it's why that not work.

**Comment by dviswanathreddy** [comment]
jexcel(document.getElementById('spreadsheet'), {
                        data: data1,
                        contextMenu: function () { return false; },
                        tableOverflow: true,
                        tableWidth: '1000px',
                        tableHeight: '380px',
                        // Allow new rows
                        allowInsertRow: false,
                        // Allow new rows
                        allowManualInsertRow: false,
                        // Allow new columns
                        allowInsertColumn: false,
                        // Allow new rows
                        allowManualInsertColumn: false,
                        // Allow row delete
                        allowDeleteRow: false,
                        // Allow column delete
                        allowDeleteColumn: false,
                       rowDrag:false,

                        columns: [

**Comment by GBonnaire** [comment]
Ok is good.

But, have you a possiblity to use last version V4.7.4 ?

**Comment by GBonnaire** [comment]
I checked on version v3.9.1 with rowDrag:false, row can't move.

For double check, when page is loaded with jexcel. Can you, click on 1 cell, open your console and tape :
`jexcel.current.options.rowDrag`
the result should be false

**Comment by dviswanathreddy** [comment]
is it possible  selectionCopy: false for particular columns. i need to disable for checkbox columns

**Comment by dviswanathreddy** [comment]
Need to disable selectionCopy:false for few columns in jexcel v3.9.1

**Comment by GBonnaire** [comment]
Hi,

No selectionCopy for few columns is not possible.

But if you want, you can stop copy only for some column, use `onbeforepaste` function in property

```javascript
jexcel(DOMElement, {
   onbeforepaste: function(el, data, x, y) {
           if(x == 2) { // Column C
                  return false; // Disable paste data on this columns
           }
   },
});
```

This function is to improve if you want manage more case

Please open issue for each question/problem 😊

**Comment by dviswanathreddy** [comment]
While doing selection copy checkbox to numeric column it showing as 1 while checkbox checked, is it possible to true or false instead of 0 or 1

**Comment by dviswanathreddy** [comment]
<img width="327" alt="Checkbox drag" src="https://user-images.githubusercontent.com/84698978/121712919-e4400380-caf9-11eb-8b6b-e3bf57e9c739.PNG">

**Comment by GBonnaire** [comment]
Hi,

on v4.7 you have true or false not 0 or 1. Please update your framework 😊
