### ISSUE TITLE
Writing function in spreadsheet shows the actual logic of the function

### ISSUE THREAD

**Issue by jeremywicaksana** [jspreadsheet/ce#1381]
When write "=SUM" in the cell and enter it. It did not say "#NAME?" like in excel. Instead it shows the actual logic behind "=SUM" function. Is there a way to fix this?

**Comment by GBonnaire** [comment]
Hi,

On this version, no is a behavior of javascript (native)

`var function test() { alert('OK'); }`
`console.log(test); // show in console function () {alert('OK');}`

**Comment by hodeware** [comment]
On most recent versions, it will show an error...

**Comment by hodeware** [comment]
Now there is a Formula Pro, an extension that can be used with CE.
https://jspreadsheet.com/products/formulas
