### ISSUE TITLE
Rounded icon for dropdown

### ISSUE THREAD

**Issue by blenezet** [jspreadsheet/ce#1382]
Hello,
By default, the icons/images that can be shown on the dropdown "column" are cropped/rounded (see screenshot attached). I suppose this default behaviour can be overridden by some CSS. I could not find this in documentation, could someone point me to the right direction?

![jexcel_icons_rounded](https://user-images.githubusercontent.com/64902620/119951324-1b5fd200-bf9c-11eb-9ea1-a9cc0e2126f5.png)

Many thanks in advance
Regards

**Comment by GBonnaire** [comment]
Hi,

try to add in CSS after jsuites.css : 
```CSS
.jdropdown-image {
   border-radius: none;
}
```

**Comment by blenezet** [comment]
Thanks/Merci Guillaume but unfortunately it still does not work. Note that I'm 100% sure that the CSS property .jdropdown-image applies (I'm tried other attributes and it does have an impact. See screenshot attached that shows these icons with border-radius set to none and another component using same icon (where icon are displayed in rectangular shape). thanks
![jexcel_icon_rounded2](https://user-images.githubusercontent.com/64902620/120197432-3a22ca80-c221-11eb-99d7-e171944c3721.png)

Bertrand

**Comment by GBonnaire** [comment]
De rien 😊 

Try with flag important

```CSS
.jdropdown-image {
   border-radius: none!important;
}
```

After other possibility : if selector is different, that not work. For check that, can you write your version of Jspreadsheet and jsuites, please ?

**Comment by blenezet** [comment]
unfortunately, still not working. Here is the product/version + dependencies that I use. Thanks

"name": "jspreadsheet-ce",
 "version": "4.7.1",
  "dependencies": {
    "jsuites": "^4.3.0"
  }

**Comment by GBonnaire** [comment]
Arf.. Try something :

Use Chrome,
Open dropdown not working
Open DevTools (CTRL + i)
Select element (Image on dropdown) with selector (top right button with cursor)
On the right, you have a style detail (Style tab), can you screenshot that or copy/paste ?


Thanks

**Comment by blenezet** [comment]
thanks a lot. this helped me to troubleshoot this. For reference, the following end up working:
.jdropdown-image {
  border-radius: 0px!important;
}

Mille mercis!
