### ISSUE TITLE
how to get data in json format with out using variable.

### ISSUE THREAD

**Issue by kallaguntaashok** [jspreadsheet/ce#1388]
I am using jexcel table between each row in the html table, each jexcel has ID, how to get this data in json format.

![image](https://user-images.githubusercontent.com/26366259/120796479-7c694600-c558-11eb-8cd7-03d05e6f8293.png)

 var obj = jexcel(document.getElementById(item)) : if I use single jexcel I can get data from obj variable, in above case I don't store it in obj object, as it will contain last row object instance.

is it possble to get jexcel data using div ID of jexcel table.

**Comment by GBonnaire** [comment]
Hi,

yes, try this :

`document.getElementById(item).jexcel`
