### ISSUE TITLE
After edit then use function getJson to get  the context, the number would be transformed to String 

### ISSUE THREAD

**Issue by aneathesia** [jspreadsheet/ce#1390]
![transbefore](https://user-images.githubusercontent.com/32892218/121476683-8e843200-c9f9-11eb-8290-9b1d978bce9c.png)
![transformed](https://user-images.githubusercontent.com/32892218/121476687-8fb55f00-c9f9-11eb-8a61-fb2fbc987e88.png)
How do I keep the data type unchanged？

**Comment by GBonnaire** [comment]
You can use event `onbeforechange(element, cell, x, y, value)` and return your data casted as you want
 
for example 
```javascript
onbeforechange: function(el, cell, x, y, value) {
     if(el.jspreadsheet.options.columns[x].type == "number") {
             return new Number(value);
     }

    return value;
}
```
code not tested

**Comment by aneathesia** [comment]
Your method really works, and this problem have noted in the document i missed that. 
![note](https://user-images.githubusercontent.com/32892218/122397747-d7188e00-cfab-11eb-963b-4200f1a074c8.png)
In addition, even set the column type to number but after edit the output data type will still mismatch, the problem may in this new return value type. 
Your code is definitely helpful.Thanks!

**Comment by GBonnaire** [comment]
Try with that:
 maybe it's new Number is not good.

```
onbeforechange: function(el, cell, x, y, value) {
            if(el.jspreadsheet.options.columns[x].type == "numeric") {
                    return +value;
            }

           return value;
       },
```

I have checked and i have good result in JSON
