### ISSUE TITLE
Missing custom cell type's creation hook `createCell` in document.

### ISSUE THREAD

**Issue by StephenChips** [jspreadsheet/ce#1394]
Please add it's definition and usage to the webside.

Plus, it seems the `setValue()` and `getValue()` hooks are specifically for internal types, please specifies this in the doc.

**Comment by GBonnaire** [comment]
The functions CreateCell, CreateRow, ... are private function for jspreadsheet for have more information, i invite you to read code directly

And in doc the bracket is used for explain type to use, is not an array 😉 

You want more professional system, please use : [JSpreadsheet pro](https://jspreadsheet.com/)

**Comment by hodeware** [comment]
createCell is for internal use, and should not be used. getValue and setValue on the other hand are for normal usage.
