### ISSUE TITLE
column type numeric can't auto increment

### ISSUE THREAD

**Issue by FangHanZreo** [jspreadsheet/ce#1397]
**Describe the bug**
column type numeric can't auto increment

**To Reproduce**

**Expected behavior**
At source code line 2613,  add  `obj.options.columns[i].type == 'numeric'` ?

Thanks!

**Comment by GBonnaire** [comment]
I think you not have autoincrement to Jspreadsheet CE, it's only on version pro with column type autonumber

**Comment by FangHanZreo** [comment]
> I think you not have autoincrement to Jspreadsheet CE, it's only on version pro with column type autonumber

Thanks!
