### ISSUE TITLE
Refrence to cell which has alphanumeric value returns only numeric value

### ISSUE THREAD

**Issue by Krishna111704** [jspreadsheet/ce#1398]
Scenario 1:
if the cell "A1" has value "Test123"
if i add reference of cell A1 in A2. example in A2 cell "=A1".
in A2 cell i get only value "123"

**Comment by GBonnaire** [comment]
Hi,

Yes, jspreadsheet try to extract number of string. (if you use mask for example).
If you don't use this feature try with option `autoCasting:false,`
