### ISSUE TITLE
color picker in header

### ISSUE THREAD

**Issue by gutofurlan** [jspreadsheet/ce#1399]
Hi guys.
I need to put a color selector in the header, so the user chooses.
An example is in the image as I want.
Anyone have an idea?
<img width="214" alt="Captura de Tela 2021-06-23 às 09 57 40" src="https://user-images.githubusercontent.com/6179871/123100384-7654df80-d409-11eb-9844-a49c868a39f0.png">
thanks

**Comment by GBonnaire** [comment]
Hi,

Yes, you can insert HTML in header. See this issue : https://github.com/jspreadsheet/ce/issues/1373

For color, use jSuites color picker for integrate in header : https://jsuites.net/v4/color-picker/basic
