### ISSUE TITLE
setData function

### ISSUE THREAD

**Issue by orsonok** [jspreadsheet/ce#14]
What is the correct way to assign data from an external source?
How to use setData(data) function?

Two important improvements:
- Drag & drop rows / reordering rows
- JSON import-export

Thanks!

**Comment by pphod** [comment]
Please get the most recent updates from the repository.

You can find a example below:
http://bossanova.uk/jexcel/remote-updates

Basically, the example will load from a external JSON file, and you can download the data as a JSON string. In regards to sorting, as default you can double click on the Column Headers. Drag and drop is the road map, hope to get this done as soon as we can.

```
<html>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<script src="http://cdn.bossanova.uk/js/jquery.jexcel.js"></script>
<link rel="stylesheet" href="http://cdn.bossanova.uk/css/jquery.jexcel.css" type="text/css" />

<div id="my"></div>

<script>
$('#my').jexcel({
    url:'/jexcel/data',
    colHeaders: ['Model', 'Year', 'Price', 'Date'],
    colWidths: [ 300, 80, 100, 100 ],
    columns: [
        { type: 'text' },
        { type: 'text' },
        { type: 'text' },
        { type: 'calendar' },
    ]
});
</script>

<p><textarea style='width:600px;height:100px;' id='test'></textarea></p>
<p><input type='button' onclick="$('#test').html(JSON.stringify($('#my').jexcel('getData')))" value="Get json data"></p>

</html>
```

**Comment by pphod** [comment]
Just to let you know, I have just commit a new version with the dragRow feature.
