### ISSUE TITLE
Issues:How to Filter JExcel Like Microsoft Office Excel

### ISSUE THREAD

**Issue by doom189** [jspreadsheet/ce#140]
(zh-CN问题:如何像Microsoft Office Excel一样过滤JExcel
每列可以过滤当前列的值，
或者过滤器可以过滤所有行，如以下连接实例中所示：)
Each column can filter the value of the current column,
Or a filter can filter all the rows, as in the following connection instance:
https://codepen.io/chriscoyier/pen/tIuBL

**Comment by pphod** [comment]
You can implement that to filter your data them call setData() to refresh your table with the new content of your source variable.
