### ISSUE TITLE
Applying formula on the numbers with negative sign and comma separated is showing wrong value. 

### ISSUE THREAD

**Issue by GOPALAKRISHNAYM** [jspreadsheet/ce#1401]
First thing Thanks you so much for jspreadsheet .

Please help,

i have three columns as shown below 
```
|     A                   |      B                 |     C          |
| -12,34,56,789.00        | 12,34,56,789.00        | =(A1+B1)       |
```

Ideally value of C1 cell should be 0 but the value in the cell after applying formula is -12,34,56,789123456789.
Im using V4 jspreadsheet.

Thank you.

**Comment by GBonnaire** [comment]
Hi,

Yes in column A value is considered like string, and in JS string+other = stringother

You can try to cast value in column A with onbeforechange for remove coma separator or use try to use mask

**Comment by hodeware** [comment]
You must have your number as FLOAT in the raw data, and you can use the mask to format the number.
