### ISSUE TITLE
How do I get and set field data using tabs?

### ISSUE THREAD

**Issue by andre-gasparin** [jspreadsheet/ce#1402]
How do I get and set field data using tabs?

i tried:
https://codepen.io/andre-gasparin/pen/qBreErg

Thanks !

**Comment by GBonnaire** [comment]
Hi

use this :
`document.getElementById("spreadsheet").children[1].children[0].jspreadsheet.getValue("A1");`

explain :
get Tab element :
`document.getElementById("spreadsheet")`
in tab element, you have 2 div (1st for button tab, 2nd for content tab), here 2nd tab is required
`.children[1]`
in content tab select your spreadsheet 0 = first, 1 = second, ....
`.children[0] // For first spreadsheet`
after you get instance jexcel or jspreadsheet 
`.jspreadsheet`
and after you can make your command script
`.getValue('A1');`
