### ISSUE TITLE
Entire page freezes (and remains frozen) after ending edit of html-type cell if the Console is open or opened afterwards

### ISSUE THREAD

**Issue by jaapmurre** [jspreadsheet/ce#1403]
[BUG] Entire page freezes (and remains frozen) after ending edit of html-type cell if the Console (debug) window is open or if it is opened after having successfully edited an html cell. On Firefox, it seems there is a timeout problem around line 10081 in jsuites.js:

            // Available space
            var available = el.parentNode.offsetWidth - 60;
            // Move to the floating option
            while (available < toolbarContent.offsetWidth) { // line 10081
                if (toolbarContent.lastChild) {
                    toolbarFloating.insertBefore(toolbarContent.lastChild, toolbarFloating.firstChild);
                }
            }

It seems the code never moves past line 10081 and causes a permanent freezing of the page. Perhaps, this is caused by the page coordinates being altered by the open console window.

**Comment by hodeware** [comment]
Thanks, we are going to upload a patch in a few hours.

**Comment by jaapmurre** [comment]
That is fast! Jaap
