### ISSUE TITLE
Custom component in row

### ISSUE THREAD

**Issue by gutofurlan** [jspreadsheet/ce#1404]
Hi guys
I need to put an icon next to the line number, how could I do that?
NOTE: As shown in the image
Thanks
<img width="60" alt="Captura de Tela 2021-06-28 às 11 27 08" src="https://user-images.githubusercontent.com/6179871/123653773-d7165a80-d803-11eb-9932-a6feaf4728e7.png">

**Comment by quanghm27** [comment]
I think you shouldn't touch the row number. Leave it as default and try to add icon in the next column.
Because jspreadsheet coordinate mark (x, y) = (0,0) from the first cell of this column.

**Comment by GBonnaire** [comment]
Hi,

On version pro you can use this plugin : https://jspreadsheet.com/plugins/rowheaders

otherwise i have explain method for column and row on issue #1373
