### ISSUE TITLE
Invoke auto complete

### ISSUE THREAD

**Issue by Niranjanvelu** [jspreadsheet/ce#1406]
I had a scenario when a user enter into a drop-down or auto complete cell ,the drop-down have to open automatically.

  TIA

**Comment by GBonnaire** [comment]
Hi,

yes, dropdown open when you enter / edit cell.

**Comment by Niranjanvelu** [comment]
Hi, GBonnaire,

I want to invoke the drop-down when focus the cell.

**Comment by GBonnaire** [comment]
Hi,

You can use event onselection, on selection, you open editor

`onselection: function(el, x1, y1, x2, y2, origin) {...} `

Example :
```javascript
onselection: function(el, x1, y1, x2, y2, origin) {
      if(x1 == x2 && y1 == y2) { // Check if one cell is selected
               el.jspreadsheet.openEditor(el.jspreadsheet.records[x1][y1], false);
      }
} 
```
(code not tested)
