### ISSUE TITLE
Column Type html is not behaving properly when I paste some data in the cell

### ISSUE THREAD

**Issue by GOPALAKRISHNAYM** [jspreadsheet/ce#1407]
please help,
i have column which is having of type as shown
{
        "title": "Abc",
        "align": "left",
        "type": "html",
        "wordWrap": true,
        "readOnly": false,
}
data =[
        [" <span> hi please help</span>"]
    ]
But When i paste some value in the cell it is creating an extra div tag which causing to move to next line as

![Screenshot from 2021-07-04 12-32-52](https://user-images.githubusercontent.com/49530827/124376309-0aedf600-dcc4-11eb-8440-b9b5c9f3283f.png)

![Screenshot from 2021-07-04 12-24-47](https://user-images.githubusercontent.com/49530827/124376079-db8ab980-dcc2-11eb-94e1-f8ea4960cb60.png)

Here i pasted the value "hi" in the beginning of the line but extra line got added.can any one help where im going wrong.

**Comment by GBonnaire** [comment]
Hi,

which version are you using of jSuites and CSS jSuite ?

**Comment by GOPALAKRISHNAYM** [comment]
hi @GBonnaire ,
im using latest bootstrap scss(V4.4.1) with react
JSuites 3.5.4
Thank you.

**Comment by GBonnaire** [comment]
Hi,

Can you update to jSuites v4 and last version of jSpreadsheet ? This bug fixed on this version 😊

**Comment by GOPALAKRISHNAYM** [comment]
Hi @GBonnaire 

Thanks for your reply,
This issue is working as expected now.

But upgrading to jSpreadsheet 4.7.3 , navigating using navigation keys from keyboard  is moving two cells ahead.do we have any flag for this to stop navigating 2 cells?

**Comment by GBonnaire** [comment]
Hi,

Maybe see if you not load 2 times libraries. Because navigation by keys is global, and i try on demo website, and is OK, then i think you a issue on load or create new instance.

**Comment by GOPALAKRISHNAYM** [comment]
hi @GBonnaire 
Undo and redo option in cell type html is broken in this version i guess , can you please tell why undo and redo options are not working.
[url for documentation with HTML cell type](https://bossanova.uk/jspreadsheet/v4/examples/richtext-html-editor)
Thank you.

**Comment by avinash0208** [comment]
hi  Team. I  have observed that copy paste is not working fine for Windows user but working fine for ubuntu users. Can you please follow up on same and let me know is this true. Thanks

**Comment by GBonnaire** [comment]
> hi @GBonnaire
> Undo and redo option in cell type html is broken in this version i guess , can you please tell why undo and redo options are not working.
> [url for documentation with HTML cell type](https://bossanova.uk/jspreadsheet/v4/examples/richtext-html-editor)
> Thank you.

Hi,

For me, it's work, check your version, maybe you have in cache an old version ?

**Comment by GBonnaire** [comment]
> hi Team. I have observed that copy paste is not working fine for Windows user but working fine for ubuntu users. Can you please follow up on same and let me know is this true. Thanks

Hi, please open new issue

For answer, how you make a copy paste, with keybord or contextmenu ? There is maybe 1 way who work bad on windows with Chrome and firefox (when you are on website without SSL)
