### ISSUE TITLE
Navigating using navigation keys is not working as expected. 

### ISSUE THREAD

**Issue by GOPALAKRISHNAYM** [jspreadsheet/ce#1408]
Please help,

I recently updated my jspreadsheet to **4.7.3 .**
Navigation using navigation keys is moving 2 cells forward , and every right click is taking two clicks.

**example :** 
Issue 1:  if cell pointer is in **A1** cell and then click on right arrow then cell pointer is moving to **A3** instead of **A2.**
Issue 2:  if i right click on column header then it is taking it as two clicks and selecting options by itself and performing action. 

please help on above issues,
Thank you.

**Comment by GBonnaire** [comment]
Hi,

Maybe see if you not load 2 times libraries. Because navigation by keys is global, and i try on demo website, and is OK, then i think you a issue on load or create new instance.

**Comment by avinash0208** [comment]
Hey, to your above response , is there any way to remove the previous instance?

**Comment by GBonnaire** [comment]
Check if jexcel.build == null in console after loading instance of JSpreadsheet. If yes do you use property "root" ?

Can you reproduct a problem on codepen or jsfiddle ?
How much of spreadsheet in your page ?

**Comment by RajendraMalya** [comment]
Yes, we use property of root and  jexcel.build == null.
can't we initialise this?

**Comment by GBonnaire** [comment]
build is initialised and after call is set to null.

But i think why. You have 2 instance of jss on same root ? like 2 tabs ? try to not set root property in this case or just set to first instance
