### ISSUE TITLE
Custom menu css is affected and showing something like this

### ISSUE THREAD

**Issue by avinash0208** [jspreadsheet/ce#1409]
Hey team , all of a sudden my context menu is seen like this. Can you help with this
![Screenshot from 2021-07-06 15-29-37](https://user-images.githubusercontent.com/35329694/124582570-c0a97800-de6f-11eb-85ac-6bc184463547.png)

**Comment by GBonnaire** [comment]
do you use submenu in context menu ?

**Comment by avinash0208** [comment]
Yes

**Comment by avinash0208** [comment]
we use submenu

**Comment by hodeware** [comment]
It looks like you need to load the CSS from jsuites.

**Comment by hodeware** [comment]
import '/node_modules/jsuites/dist/jsuites.css';

**Comment by avinash0208** [comment]
Great it worked. Thanks a lot
