### ISSUE TITLE
fill down square and relative positioning

### ISSUE THREAD

**Issue by morgunder** [jspreadsheet/ce#141]
i am using relative positioning in my jexcel and the fill down square isn't showing up in the correct location.  this is why i asked earlier if there was a fill down option at all as i didn't see it.  you were able to correct the relative position issue with the calendar popup, can you also correct the positioning of the fill down square?  thx

**Comment by pphod** [comment]
I am happy to help, but in this case I am not sure the cause. If you would like to share something I might help you.

**Comment by morgunder** [comment]
i was able to fix it with a z-index adjustment.  i think that's all that is needed.  not sure if it affects other layouts.
```
.jexcel_corner {
z-index:1;
}
```

**Comment by pphod** [comment]
I have incorporate that on the current version.
