### ISSUE TITLE
Dropdown with "newOptions: true" doesn't work.

### ISSUE THREAD

**Issue by erados** [jspreadsheet/ce#1411]
https://github.com/jspreadsheet/ce/blob/cd6f46689fde8ebae63e39f0812eb068f7037e64/src/js/jexcel.core.js#L1906-L1920

Hi!

For now, there is no handler for "newOptions" option.
I think there should be some code like 

`newOptions: obj.options.columns[x].newOptions ? true : false,`

Thanks.

**Comment by hodeware** [comment]
obj.options.columns[x].options = { newOptions: true };

**Comment by erados** [comment]
I can't find the line from this repo and it would be unable to turn off the option with the line.

**Comment by erados** [comment]
https://jsuites.net/v4/dropdown-and-autocomplete/quick-reference

According to the link above, there exists `newOptions` option and my trial for that option is here

https://codepen.io/erados-the-vuer/pen/RwVYBGX

and it does not work.

**Comment by erados** [comment]
@hodeware

https://jsuites.net/v4/dropdown-and-autocomplete/quick-reference

According to the link above, there exists newOptions option and my trial for that option is here

https://codepen.io/erados-the-vuer/pen/RwVYBGX

and it does not work.

**Comment by hodeware** [comment]
We started a sequence of updates to improve several parts of the JSS CE. Today, we have uploaded the new masking system. Eventually, that will be implemented with the new editors on version 5.

**Comment by hodeware** [comment]
You can also take a look at the Pro options.
https://jspreadsheet.com/v7/examples/dropdown-and-autocomplete
