### ISSUE TITLE
cell's keydown double entry when set a mask

### ISSUE THREAD

**Issue by carltin0315** [jspreadsheet/ce#1415]
I'm using angular and the spreadsheet-ce version is 4.7.3
When I setup a column like this:
`{ type: 'numeric', title: 'price', mask: '#,##.00 %', decimal: '.' },`
Only the first key I press is input one time, after that all keys input twice.

I tried to fix it myself, but I only can trace it till here:
`                            var editor = createEditor('input');
                            // Mask
                            if (obj.options.columns[x].mask) {
                                editor.setAttribute('data-mask', obj.options.columns[x].mask);
                            }`

So it's the html5 problem or can fix by the team?

**Comment by GBonnaire** [comment]
Hi,

Can you create a jsfiddle for reproduct problem ?

**Comment by hodeware** [comment]
You have Jsuites loaded twice.
