### ISSUE TITLE
First character is wrongly handled when using IME

### ISSUE THREAD

**Issue by AutumnSun1996** [jspreadsheet/ce#1417]
When use IME, type after seletion will cause the first character wrongly handled.

### How To Reproduce:

At [demo page](https://bossanova.uk/jspreadsheet/v4/).

Select a cell (not in edit mode), and type `t e s t`:
![image](https://user-images.githubusercontent.com/20429502/126818023-573a5b99-dcbf-46a4-85cf-bdee843cfbb3.png)

The first character `t` is not handled by IME, so I often have to delete all chars and re-input.

### Expected:

Act like already in edit mode:

Type `t e s t` in edit mode:
![image](https://user-images.githubusercontent.com/20429502/126818695-c26181f3-83d9-47e5-9d55-60e23d6f27f0.png)

All charaters are handled by IME.

### Some Other Info:

Google docs and handsontable can handle IME correctly.

I found that handsontable keeps a textarea (hide with `z-index: -1`), and jspreadsheet create a new textarea/input every time.

The different behavior may be related to this bug.

Is there any way to fix this?

**Comment by klren0312** [comment]
That is fixed on the v8 distribution (Pro & Home), which should be released soon.
https://github.com/jspreadsheet/ce/issues/935#issuecomment-751874076

**Comment by hodeware** [comment]
That is fixed on v8.
