### ISSUE TITLE
header returns same value as first cell on select

### ISSUE THREAD

**Issue by baconsi** [jspreadsheet/ce#1418]
I am trying to load a modal with more data when cells in a specific row are clicked,  I have

var selectionActive = function(instance, x1, y1, origin) {
     var subdomain= mysheet.getValueFromCoords("1",y1);
     if (x1==8 && y1 >=0) {
                $.ajax( 
                    ..............
this works apart from it loses clicking the header to sort the column as clicking the header returns the same value for x1 and y1 as the first row.

if i change to the following the sort work when clicking on the header but the first row does not work when clicking it.
    if (x1==8 && y1 >0 ) {
         
any hints on where i am going wrong would be great

**Comment by hodeware** [comment]
y1 is the first row, you should use y1 >= 0

**Comment by baconsi** [comment]
x1 == 8 is so it works on column 8,  i am using y1 >= 0 so its any data row,  problem is this includes the header

**Comment by baconsi** [comment]
if i add alert(y1) clicking on first row gives me 0 and clicking on the header gives me 0

**Comment by hodeware** [comment]
That's correct. When you click in the headers all cells in the column would be selected starting on row 0 (y1) to the last row (y2)

**Comment by baconsi** [comment]
thanks that helped a lot,  i added a check to make sure y2 == y1 so only that one cell is selected and not all with selecting header and it works.
