### ISSUE TITLE
Problem on getJson

### ISSUE THREAD

**Issue by andre-gasparin** [jspreadsheet/ce#1419]
When I use "getJson" on a column that was added after the table was created, it doesn't get the data.

When I use getData it works normally

![image](https://user-images.githubusercontent.com/55391441/127140765-6e3f73d0-0843-47c2-9ee6-4f18829e56a4.png)

**Comment by GBonnaire** [comment]
Hi,

I have try, and i can't reproduct your error. Can you create a jsfiddle with this error ?
