### ISSUE TITLE
Multiple Date Selection on Calendar

### ISSUE THREAD

**Issue by Hcumali** [jspreadsheet/ce#1420]
Hello, 

I am planning to implement multiple date selection to spreadsheet but i can not find any property about that subject. Is there any option for selecting for example 10 seperate days in a month? 

Am i missing something in documentation? It's very important for me because i progress too much for changing spreadsheet lib. 

Thanks

**Comment by hodeware** [comment]
You can create a custom column for that. Example:
https://bossanova.uk/jspreadsheet/v4/examples/column-types (second example)

**Comment by Hcumali** [comment]
Thank you very much for your quick response.
I'm in the middle of a project right now and I absolutely need to use this feature.
Could you share a small example for selecting multiple dates on the calendar? 

Thanks

**Comment by hodeware** [comment]
Multiple dates are not implemented. But, you can integrate a third-party JS plugin or find someone to do that for you.

For example:
http://www.daterangepicker.com/
