### ISSUE TITLE
Using jspreadsheet for a symmetric weighted matrix (travel distance between points)?

### ISSUE THREAD

**Issue by kpagcha** [jspreadsheet/ce#1421]
I need to introduce travel time between venues in my app and I thought using a table to enter values would be the easiest method. This would be a symmetric weighted matrix then, where I need row headers to be exactly like column headers. And updating `(x,y)` should automatically update the mirror pair `(y,x)`, which should be easy enough with the onchange listener.

An example:

```
+---------+---------+---------+---------+---------+
|         | Venue 1 | Venue 2 | Venue 3 | Venue 4 |
+---------+---------+---------+---------+---------+
| Venue 1 |       0 |       3 |       7 |      10 |
| Venue 2 |       3 |       0 |       1 |       6 |
| Venue 3 |       7 |       1 |       0 |       4 |
| Venue 4 |      10 |       6 |       4 |       0 |
+---------+---------+---------+---------+---------+
```

However there doesn't seem to be a way to have row headers? I've tried adding a dummy ready only column as row headers but it's not ideal. The header still shows an autogenerated title ("A"), you can't have it blank and you can still interact with it, when you shouldn't. This is what I tried:

```
const columns = [
  {type: 'text', readOnly: true}, 
  {type: 'numeric', 'Venue 1'},
  {type: 'numeric', 'Venue 2'},
  {type: 'numeric', 'Venue 3'},
  {type: 'numeric', 'Venue 4'},
];

const data = [
  ['Venue 1', 0, 3, 7, 10],
  ['Venue 2', 3, 0, 1, 6],
  ['Venue 3', 7, 1, 0, 4],
  ['Venue 4', 10, 6, 4, 0],
];

element.jexcel({
  columns: columns,
  data: data
});
```

**Comment by GBonnaire** [comment]
Hi,

for rename header row on version CE : read #1005 
for rename header row on version Pro : https://jspreadsheet.com/plugins/rowheaders

**Comment by kpagcha** [comment]
> 
> 
> Hi,
> 
> for rename header row on version CE : read #1005
> for rename header row on version Pro : https://jspreadsheet.com/plugins/rowheaders

Well, a "working" response would be the following:

```
Array.from(jexcel.el.getElementsByClassName('jexcel_row')).forEach((rowHeader, i) => {
    rowHeader.innerText = "Custom Row Header";
});
```

However that just changes the inner text. Row headers won't get rendered properly if the title is "too" long.

**Comment by GBonnaire** [comment]
ok

you change header row size : 
```javascript
table.colgroupContainer.firstElementChild.width=100;
```

**Comment by kpagcha** [comment]
How can I deal with text overflow though?

**Comment by GBonnaire** [comment]
After for overflow, you can change CSS of table

.jexcel tbody tr td:first-child {
    word-wrap: break-word;
}
