### ISSUE TITLE
resetStyle not working

### ISSUE THREAD

**Issue by kpagcha** [jspreadsheet/ce#1423]
I'm applying some background color to any cell: `jexcel.current.setStyle('A1', 'background-color', 'blue')`. 

But then when I try to remove it with `jexcel.current.resetStyle('A1')` it just isn't working at all. 

I've also tried `jexcel.current.setStyle('A1', 'background-color', '')` or `jexcel.current.setStyle('A1', 'background-color', null)` to no avail. I've tried passing a fourth argument called `force` in the source but it's not working either:

```
jexcel.current.setStyle('A1', 'background-color', '', true);
```

**Comment by GBonnaire** [comment]
Yes, maybe it will be fixed with new version.

In waiting you can use this tips : 
`jexcel.current.setStyle("A1","background-color", jexcel.current.getStyle("A1","background-color"));`

setStyle remove style if already existing
