### ISSUE TITLE
Updating data from numeric fields

### ISSUE THREAD

**Issue by zehguilherme** [jspreadsheet/ce#1427]
- It only occurs on `Google Chrome` and only with `numeric` values (column type -> numeric)
- [Version 4.7.3](https://bossanova.uk/jspreadsheet/v4/jexcel.js)

## First error
```
Uncaught TypeError: Cannot read property 'substr' of undefined
    at Object.obj.closeEditor (jexcel.js:2075)
    at HTMLDocument.jexcel.mouseDownControls ([jexcel.js:7574](https://bossanova.uk/jspreadsheet/v4/jexcel.js))
```

### jexcel.js:2075

![image](https://user-images.githubusercontent.com/36301054/129416550-08a46842-c081-4429-b113-395a3b29a097.png)

### jexcel.js:7574

![image](https://user-images.githubusercontent.com/36301054/129416695-2919a2b8-e1c5-4e01-99e5-ed61512f1faf.png)

## Second error

```
Uncaught TypeError: Cannot read property 'substr' of undefined
    at Object.obj.closeEditor (jexcel.js:2075)
    at HTMLTextAreaElement.editor.onblur ([jexcel.js:2031](https://bossanova.uk/jspreadsheet/v4/jexcel.js))
```

### jexcel.js:2075

![image](https://user-images.githubusercontent.com/36301054/129417208-3a817a06-8002-4bb6-8cac-a0ee27fe072b.png)

---

When I change the column's value, the table simply crashes and I can't do anything else.

![image](https://user-images.githubusercontent.com/36301054/129415713-5f846ea5-23c3-48b5-a578-32d7c4874801.png)

**Comment by GBonnaire** [comment]
Do you have a same problem with last version v4.9 ?

Can you share columns declaration, for i can reproduct the problem ?

**Comment by zehguilherme** [comment]
I don't tested this latest version because when I started doing the project in question, the latest version was v4.7.3.

In the company that I am, we use .NET Core Framework with Razor.

The other programmers already tested in their Google Chrome and all works perfect. This issue just occurs in my Chrome, maybe because of some extension installed, making conflicts, I don't know.

**Comment by GBonnaire** [comment]
For test if it's your extensions, open your chrome in guest mode est try to reproduct problem.

If you can, that is not caused by extension. otherwise you can disable each extensions and retest. 

Be carefull on extensions on HTMLElement/DOMElement

**Comment by hodeware** [comment]
I believe that is fixed now.
