### ISSUE TITLE
 String comparison doesn't work

### ISSUE THREAD

**Issue by rnlwneh** [jspreadsheet/ce#1428]
It's my source code

var data = [
    ['AAA',1,123,'=B1*C1','=IF(A1=="AAA", true, false)']
]

but it is not working
so I was try this

var data = [
    ['AAA',1,123,'=B1*C1','=IF(A1="AAA", true, false)']
]

but it is return false
how can I solve this problem?

**Comment by GBonnaire** [comment]
Hi,

try : 
`=IF(A1="Jazz", TRUE(), FALSE())`

You need to use return TRUE() for true and FALSE() for false
