### ISSUE TITLE
Page Unresponsive  

### ISSUE THREAD

**Issue by Krishna111704** [jspreadsheet/ce#1429]
While copy pasting data of 500 rows and column of 10 , page get unresponsive from chrome browser. 
![unresponsive](https://user-images.githubusercontent.com/86351006/130054075-ad1ae326-511d-4559-984a-9aa14718eb2e.png)

**Comment by GBonnaire** [comment]
Do you have try to clear cache ?

I have try to copy/paste same range of data on jspreadsheet, no problem on my chrome.

**Comment by hodeware** [comment]
Take a look at your events, do you trigger events?
