### ISSUE TITLE
How to navigate to the specified worksheet？

### ISSUE THREAD

**Issue by zy-design** [jspreadsheet/ce#1430]
hi, I use tabs, but every time I render data, I always locate the last worksheet. I try to add jtabs-selected attribute to the first worksheet, but I still locate the last one, so what do I do？

**Comment by GBonnaire** [comment]
Hi,

can you make a JSFiddle with your problem ?

And Maybe you can read this issue, you can found a solution : 
https://github.com/jspreadsheet/ce/issues/1174
https://github.com/jspreadsheet/ce/issues/1165

**Comment by zy-design** [comment]
Thank you. I've solved it, like this：
      var table = jspreadsheet(document.getElementById('spreadsheet'), data);
       table[0].worksheet.jexcel.openWorksheet(0)
