### ISSUE TITLE
the method 'getColumnNameFromId' is return Strange columnName

### ISSUE THREAD

**Issue by rnlwneh** [jspreadsheet/ce#1431]
this is my source
![1](https://user-images.githubusercontent.com/72964367/130745256-7e2f6a7d-82ec-4045-a11b-664dc7f4120b.PNG)

I think It should be return column 'C'

![2](https://user-images.githubusercontent.com/72964367/130746159-e655f4fe-5d73-4d5e-ab03-b4c756efb87a.PNG)

But It's return column 'L' .....
I don't know why..

**Comment by GBonnaire** [comment]
I think L is a column 11

c+1 not return 2 but 11.

Try `+c + 1`

**Comment by hodeware** [comment]
Please make sure C is a integer
