### ISSUE TITLE
If function Reference loop detected error

### ISSUE THREAD

**Issue by didi9417** [jspreadsheet/ce#1432]
It's my code

![1](https://user-images.githubusercontent.com/89561822/130892590-66624727-59f1-4e99-9279-111c519594b6.PNG)

It's return Reference loop detected error

![2](https://user-images.githubusercontent.com/89561822/130892622-bb3ec3e6-2322-4af4-978c-eedc08c77799.PNG)

How can we use If function?

**Comment by GBonnaire** [comment]
Hi,

Tr is why on your code ?
You set this formula on which cellName ?

if you set in U1. ==> =IF(U1<0,TRUE(),FALSE()) 
that not work, you need to set on U2 this formula

**Comment by hodeware** [comment]
You need to send more information, create a demo on jsfiddle, or something.
