### ISSUE TITLE
add a callback for Persistance result

### ISSUE THREAD

**Issue by nopchok** [jspreadsheet/ce#1437]
Hello friends, how are you?

Due to some update result maybe error.
Please add callback function in Persistance (obj.save)

i see the result from obj.save
https://github.com/jspreadsheet/ce/blob/master/src/index.js#L6974
but the result after post to target url, did not return,

Please add the result return.
https://github.com/jspreadsheet/ce/blob/master/src/index.js#L6993

the code something like this
`
obj.dispatch('onsave', el, obj, data, ` `result` `);
`

Thanks

**Comment by nopchok** [comment]
One more issue.
The Persistance did not get the updated value after function `updateTable` executed.
https://github.com/jspreadsheet/ce/blob/master/src/index.js#L10779

Please correct it.

Thanks.

**Comment by GBonnaire** [comment]
Hi,

Can you make a PR ? or if you want you can use pro version with the full system on persistence

**Comment by mariano-escalera-85** [comment]
@GBonnaire what you mean "with the full system on persistence" what exact features for persistence are in the pro version?, I'm interested

**Comment by hodeware** [comment]
https://jspreadsheet.com/docs/persistence
