### ISSUE TITLE
Problems with Formula

### ISSUE THREAD

**Issue by mawsu3a** [jspreadsheet/ce#144]
Hi,

I am using Jexcel with 4 tables, each on 1 Tab.
For each of these 4 tables, I am using formula.
I noticed that the formula written in 1 table was rewriting the formulas of the 3 other tables.

Understand my problem ?

**Comment by pphod** [comment]
It has been fixed in the new release v1.5.2 (available in the master repo)

**Comment by mawsu3a** [comment]
Thanks a lot
