### ISSUE TITLE
IE11 issues - not seeing grid likely relative positioning issue + cell spacing issues

### ISSUE THREAD

**Issue by morgunder** [jspreadsheet/ce#145]
IE11 - hoping you still support this.  my site needs to support it.  grid not appearing under headers.  relative positioning is in play.  thx

![screen shot 2018-05-17 at 11 41 45 am](https://user-images.githubusercontent.com/3998336/40188159-500248fa-59c7-11e8-83e6-bd241a0ee9ee.png)

also when looking at stock samples in IE11 i'm seeing columns not lined up in grid.
![virtualbox_ie11___17_05_2018_16_44_36](https://user-images.githubusercontent.com/3998336/40188212-727e37a4-59c7-11e8-8f9b-8555f126716e.png)

**Comment by pphod** [comment]
In the CSS jquery.jexcel.css remove the display:flex option. It happens in some conditions in IE, we are trying to fix that. Meanwhile you can get the solution by remove that.

.jexcel > thead > tr, .jexcel > tbody > tr
{
    display:flex;
}

**Comment by morgunder** [comment]
paul - thank you . will give that a whirl.  side note display: initial would have unwound it but IE 12 is needed to support : initial.  ha. :(

**Comment by morgunder** [comment]
paul - i got it working to display correctly.  thinking it is worth checking this in.  no idea why table-footer-group worked.  but hey, if anything works in IE11 i'm happy.  

CSS:
```
    @media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
       .jexcel > tbody {
            display:table-footer-group;
        }

      .jexcel > tbody > tr, .jexcel > thead > tr {
            display:table-row;
        }
    }

```
JS:
needed to prevent the forced inline style display:block on the table itself.  
line 1323...

 ```
       // Scrolls
        if ($.fn.jexcel.defaults[id].tableOverflow == true) {
            // $(tbody).css('display', 'block');
            $(tbody).css('overflow-y', 'scroll');
            $(tbody).css('height', 'auto');
            $(tbody).css('max-height', $.fn.jexcel.defaults[id].tableHeight);
        }

```

**Comment by pphod** [comment]
I have commit some very similar couple hours ago ;)
