### ISSUE TITLE
contextMenu Example

### ISSUE THREAD

**Issue by KMcCracken** [jspreadsheet/ce#147]
I'm currently reviewing jExcel. It looks great! Do you have an example of how to modify the context menu to add custom functionality?

**Comment by KMcCracken** [comment]
I found that simply adding a jQuery UI context menu to the jExcel table accomplished what I needed. It gave me the flexibility to customize my own context menu for each cell in the table.

**Comment by JDGHHou** [comment]
Can you please explain how one simply adds a jQuery UI context menu to the table?

**Comment by KMcCracken** [comment]
Sure...

```
    var myControl = $('someHtmlTag');

    myControl.jexcel({
        "whatever parameters you want here"
        ,contextMenu: function() {
            return null;
        }
        ,onselection: function(obj, cell, val) {
            set_contextmenu(cell);
        }
    });

    function set_contextmenu(sender) {
        $.contextMenu({
            selector: '#' + sender[0].id
            ,items: {
                "jQuery UI context parameters here"
            }
        })
    }

```
