### ISSUE TITLE
copy | paste to | from excel issues with dates

### ISSUE THREAD

**Issue by morgunder** [jspreadsheet/ce#148]
using this example: https://bossanova.uk/jexcel/examples/using-a-calendar-column-type

step 1 - to excel
in jexcel: i selected all 4 cells in the date column
in excel: pasted into excel.  
result: excel swapped m/d and shrunk year to 2 digits.  
  - excel shows 12/1/16, 12/2/16 ... where jexcel shows 01/12/2016, 02/12/2016 ...

step 2 - from excel
in excel: i moved the top date to the bottom and selected all 4 dates again
in jexcel: pasted into top date cell
result: jexcel didn't put any data in, if i start in a lower cell it expands downward with blank cells

expectation - need to be able to paste dates back and forth from excel without swapping day-month.
hopefully this isn't too hard.

**Comment by morgunder** [comment]
related - pasting multiple cells from excel, the first date field is ending the paste operation.  that is most obvious when pasting into blank cells and subtlely wrong when pasting over old cells.

repro - copy all the cells from the initial calendar example to excel and paste back into new cells without the date column = :)  and with the date column = :(


![screen shot 2018-05-23 at 11 24 25 am](https://user-images.githubusercontent.com/3998336/40434250-f31dcf4c-5e7b-11e8-90bc-d8d8aa608993.png)

**Comment by morgunder** [comment]
paul - best part - works just fine from numbers.  gotta love excel.  or not.

**Comment by pphod** [comment]
jCalendar uses a fixed format 'yyyy-mm-dd hh:mm:ss' when you copy from jexcel you going to see that. This happens independent of what format the user is seeing. That's quite trick when you paste different formats on jexcel, since jexcel must receive the  'yyyy-mm-dd hh:mm:ss'.

**Comment by morgunder** [comment]
wow that does sounds ugly.  unfortunately its the core use case i'm dealing with right now.  being able to copy several rows including dates from excel and paste into the web page and back again.

**Comment by pphod** [comment]
One easy solution is create a custom based date using any other datepicker plugin.

**Comment by morgunder** [comment]
did a quick search for other date pickers and paste was pretty broken in them too.  any one come to mind?
On Jun 14, 2018, 2:02 PM -0400, Paul Hodel <notifications@github.com>, wrote:

One easy solution is create a custom based date using any other datepicker plugin.

**Comment by pphod** [comment]
Maybe this one?
https://eonasdan.github.io/bootstrap-datetimepicker/

**Comment by morgunder** [comment]
i'll have a look and let you know how it works.  being that it crashes the paste operation hopefully you can merge in and replace jcalendar...

**Comment by pphod** [comment]
Data is a little trickier since it can have different formats. Planning to take a look in the next version.
