### ISSUE TITLE
Not displaying correct on IE 11

### ISSUE THREAD

**Issue by tbnovaes** [jspreadsheet/ce#150]
JExcel table is not displaying correct on IE 11. I saw a hack for IE 11 Flex was done on the master branch. Is there any plans to when it will be released?

**Comment by morgunder** [comment]
i'm using the hack and its resolving a couple IE 11 issues . there are still a few like the header isn't multi-line when the <th> contents get wordy...  but its better.

**Comment by tbnovaes** [comment]
@morgunder is the hack released already?

**Comment by pphod** [comment]
Yes, it has been released.
