### ISSUE TITLE
select2 default to current cell value

### ISSUE THREAD

**Issue by morgunder** [jspreadsheet/ce#152]
not quite sure how to phrase this...

have a select2 that uses ajax to fetch data.  type in a number and it fetches number + description.
when i double click on the cell to edit it, the select2 pops up but it doesn't default to the current cell contents.  select2 is a bit tricky to get default values into.  was hoping you knew a way to connect the dots to get the current cell contents into the typing field of the select2.

thx

**Comment by pphod** [comment]
Please share an example in Jsfiddle.

**Comment by pphod** [comment]
https://jsfiddle.net/xcmjkuyf/25/

Unfortunately this example is not fully working (editor is not closing) since the blur event from select2 is not working. But, I left there in case you can finish it.

Regards,
