### ISSUE TITLE
Formulas getting displayed instead of the value

### ISSUE THREAD

**Issue by debrajgh** [jspreadsheet/ce#155]
I mentioned a formula for a cell. But I cant see the data. Its displaying the formula itself

**Comment by pphod** [comment]
Please, make sure you have loaded those files:

<script src="https://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.6/numeral.min.js"></script>
<script src="../dist/js/excel-formula.min.js"></script>

**Comment by debrajgh** [comment]
Issue solved. I was referring wrong excel-formula.min.js
