### ISSUE TITLE
Insert new row/column not working

### ISSUE THREAD

**Issue by debrajgh** [jspreadsheet/ce#156]
Right clicking on the table opens up the hidden menu where it shows insert new row/column. But clicking it, nothing happens

**Comment by debrajgh** [comment]
Also, I want to display the table with 200 rows initially

**Comment by pphod** [comment]
You can use the minDimensions: [numCol, numRows]

About the right click, I am not sure what is happening on your side. Is there any error on the console?

**Comment by debrajgh** [comment]
While right clicking, I found 2 errors in the console

TypeError: $(...).prop(...) is undefined
TypeError: jQuery(...).jexcel is not a function

I am using the following libraries

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.6/numeral.min.js"></script>

<script src="http://cdn.bossanova.uk/js/excel-formula.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jexcel/1.5.0/js/jquery.jexcel.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jexcel/1.5.0/css/jquery.jexcel.min.css" type="text/css" />

**Comment by pphod** [comment]
can you paste the whole code here?
