### ISSUE TITLE
insert new row/coumn throws error in console

### ISSUE THREAD

**Issue by debrajgh** [jspreadsheet/ce#158]
While right clicking, I found 2 errors in the console
While clicking insert new row/coumn throws error in console

TypeError: $(...).prop(...) is undefined
TypeError: jQuery(...).jexcel is not a function

I am using the following libraries
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script> <script src="https://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.6/numeral.min.js"></script> <script src="http://cdn.bossanova.uk/js/excel-formula.min.js"></script> <script src="https://cdnjs.cloudflare.com/ajax/libs/jexcel/1.5.0/js/jquery.jexcel.js"></script>

**Comment by pphod** [comment]
DO you have the prop ID in your DIV?

**Comment by debrajgh** [comment]
This is the full script. The following runs fine when placing this in a html file. However, we are using an application development tool named Oracle Apex, where it throws error

`<html>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.6/numeral.min.js"></script>

<script src="http://cdn.bossanova.uk/js/excel-formula.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jexcel/1.5.0/js/jquery.jexcel.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jexcel/1.5.0/css/jquery.jexcel.min.css" type="text/css" />
<div id="annualexp"></div>

<script>
data = [
    [ 'SLT-001', 'CC2-Operations', 'CP-603 Sepulvada Pass', 'Task1', 'E9003-Contracts', 25000, 15000, 30000, 30000, '=SUM(F1:I1)',''],
    [ 'SLT-002', 'CC2-Operations', 'CP-603 Sepulvada Pass', 'Task1', 'E9003-Contracts', 25000, 15000, 30000, 30000, '=F2+G2+H2+I2',''],
	[ 'SLT-002', 'CC2-Operations', 'CP-603 Sepulvada Pass', 'Task1', 'E9003-Contracts', 25000, 15000, 30000, 30000, '=F3+G3+H3+I3',''],
	[ 'SLT-002', 'CC2-Operations', 'CP-603 Sepulvada Pass', 'Task1', 'E9003-Contracts', 25000, 15000, 30000, 30000, '=F4+G4+H4+I4',''],
	[ 'SLT-002', 'CC2-Operations', 'CP-603 Sepulvada Pass', 'Task1', 'E9003-Contracts', 25000, 15000, 30000, 30000, '=F5+G5+H5+I5',''],
	[ 'SLT-002', 'CC2-Operations', 'CP-603 Sepulvada Pass', 'Task1', 'E9003-Contracts', 25000, 15000, 30000, 30000, '=F6+G6+H6+I6',''],
	[ 'SLT-002', 'CC2-Operations', 'CP-603 Sepulvada Pass', 'Task1', 'E9003-Contracts', 25000, 15000, 30000, 30000, '=F7+G7+H7+I7',''],
	[ 'SLT-002', 'CC2-Operations', 'CP-603 Sepulvada Pass', 'Task1', 'E9003-Contracts', 25000, 15000, 30000, 30000, '=F8+G8+H8+I8',''],
	[ 'SLT-002', 'CC2-Operations', 'CP-603 Sepulvada Pass', 'Task1', 'E9003-Contracts', 25000, 15000, 30000, 30000, '=F9+G9+H9+I9',''],
];

$('#annualexp').jexcel({
    data:data,
	tableOverflow:true,
    tableHeight:'300px',
	minDimensions:[20,15],
    colHeaders: [ 'SLT', 'Cost Center', 'Project Number', 'Task#', 'Expenditure Type', 'Q1 Request', 'Q2 Request', 'Q3 Request', 'Q4 Request', 'Annual Request', 'Justification'],
    colWidths: [ 200, 200, 200, 100, 100, 100, 100, 100, 100, 100, 300 ],
    columns: [
        { type: 'autocomplete', source:[ 'SLT-001', 'SLT-002', 'SLT-003', 'SLT-004', 'SLT-005'] },
        { type: 'autocomplete', source:[ 'CC1-Programs', 'CC2-Operations', 'CC3-Vendors', 'CC4-Communications'] },
        { type: 'autocomplete', source:[ 'CP-601 Airport Connector', 'CP-602 Regional Connector', 'CP-603 Sepulvada Pass', 'CP-604 Systems Wide'] },
        { type: 'text' },
        { type: 'autocomplete', source:[ 'E9001-Labor', 'E9002-Acquisitions', 'E9003-Contracts', 'E9004-Materials'] },,
        { type: 'number' },
		{ type: 'number' },
		{ type: 'number' },
		{ type: 'number' },
		{ type: 'number' },
		{ type: 'text' },
    ]
});
</script>
</html>`

**Comment by pphod** [comment]
It seems to be fine, are you using the latest version? Hum, sorry I am not sure what is happening with this tool...

**Comment by debrajgh** [comment]
Yes
