### ISSUE TITLE
How do I freeze first few columns?

### ISSUE THREAD

**Issue by venkat-oss** [jspreadsheet/ce#161]
Hi Paul,
I have successfully implemented a CRUD application UI with MySQL and Oracle.
But, I have been trying to freeze few columns at the start and have not reached a desirable solution.
Can you please suggest some possible ways to do this with jexcel? 
Thanks.

**Comment by pphod** [comment]
Sorry, we don't have that option on the current version. You should be able to do that by customize that behavior of a HTML table.

**Comment by keyug** [comment]
Please use this library to fix columns
https://www.jqueryscript.net/demo/jQuery-Plugin-For-Fixed-Table-Header-Footer-Columns-TableHeadFixer/

**Comment by venkat-oss** [comment]
thanks :+1:

**Comment by pphod** [comment]
https://jexcel.net/v4/examples/freeze-columns

**Comment by ae-udarag** [comment]
> https://jexcel.net/v4/examples/freeze-columns

Is this only for Paid version ? Also this is for columns only ?
@paulhodel

**Comment by pphod** [comment]
We freeze just columns on jExcel Pro.

**Comment by ae-udarag** [comment]
Hi @paulhodel ,

I have issue in tab/mobile cell need to double click to enter values. But I want to enter values only clicking once. Is there any fix for this or another way to do this ?
