### ISSUE TITLE
how to use destroy method?

### ISSUE THREAD

**Issue by droymanz** [jspreadsheet/ce#165]
Destroy method was not in the documentation of this plugin.
I checked the js code and I found that there is a destroy method but, how can I use it? I already tried this though `"$('#mytbl').jexcel('destroy'`)" but no luck. 

Hope you can help me with this.

**Comment by pphod** [comment]
https://bossanova.uk/jexcel/docs/how-it-works (second topic).

$('#my').jexcel('destroy'); is correct. Please, bear in mind to update your repository from master.
