### ISSUE TITLE
Contextmenu conflict

### ISSUE THREAD

**Issue by droymanz** [jspreadsheet/ce#166]
I created two jexcel tables. The first one has the default contextmenu but on the second I added a custom contextmenu. Here is the fiddle [https://jsfiddle.net/9huygpoj/1/](https://jsfiddle.net/9huygpoj/1/) 

P.S. Try to comment the first table then the custom contextmenu will show

**Comment by pphod** [comment]
This has been fixed. Please download that from the master repo.
