### ISSUE TITLE
Checkbox ticked using fill down returns value 1 and not true 

### ISSUE THREAD

**Issue by grahams777** [jspreadsheet/ce#167]
Thanks for a very good and easy to use plugin

Grid with multiple rows with one column of type checkbox
1. Tick any row checkbox returns true
2. Fill down from row with checked checkbox - all filled checkboxs return 1 and not true

**Comment by pphod** [comment]
Do you have the most recent version installed?

**Comment by grahams777** [comment]
Yes I believe I do - downloaded 5 days ago. Can check & advise by Fri?

**Comment by pphod** [comment]
Please, make sure you have v1.5.4

**Comment by grahams777** [comment]
Hi 

 

Just checked – installation is 1.5.3 – 1.5.4 was released some minutes ago – will install & advise 

 

Thank you so much for your prompt reply and great support

**Comment by grahams777** [comment]
Upgraded - the problem is not resolved 
 * (c) 2013 Jexcel Plugin v1.5.4 | Bossanova UI
 * http://www.github.com/paulhodel/jexcel
 *
 * @author: Paul Hodel <paul.hodel@gmail.com>
 * @description: Create light embedded spreadsheets on your webpages

**Comment by spdrman** [comment]
The checkbox isn't working for me either. My formula in another cell referencing the checkbox cell doesn't return a true / false, nor does the returned result change with the change of the checkbox.

**Comment by pphod** [comment]
This has been fixed on v3 master repository.

**Comment by spdrman** [comment]
I confirm that after upgrading from 3.4.4 to 3.4.5 the issue is resolved!
Paul, this is an awesome project, and I will definitely be contributing to it in the future. Thanks for keeping it OSS !
