### ISSUE TITLE
fixed footer

### ISSUE THREAD

**Issue by morgunder** [jspreadsheet/ce#169]
is it possible to make the footer row sticky?  i have need to put totals there.  thx

**Comment by pphod** [comment]
You need to work the CSS, but this can give you an direction.

https://jsfiddle.net/z5Lnkqem/

**Comment by morgunder** [comment]
paul - i appreciate the attempt but there are similar issues to those affecting multi-line headers.  most importantly that cell resizing will not affect the footer.  i'll postpone what i was thinking of using the sticky footer for and have a think about official options for sticky headers and footers for an updated jexcel version
