### ISSUE TITLE
How to programmatically select a cell? 

### ISSUE THREAD

**Issue by saranchockan** [jspreadsheet/ce#170]
I want to navigate to the first cell through a keyboard shortcut. I was wondering how to trigger a click on on the cells and be able to type w/o using the mouse.

**Comment by pphod** [comment]
I am not sure if I understood correctly, but let me try:

$('#my').jexcel('updateSelection', $('#my').jexcel('getCell', 'A1'), $('#my').jexcel('getCell', 'B1'));

**Comment by herutaslim** [comment]
I want to use similar functionality. When the user move the cursor to an empty row, I want the cursor to move to the first column of the row. Using updateSelection, I successfully move the cursor to the first column. However, when I start typing a letter, it fills another column (the previous column before the cursor was moved to first column with 'updateSelection').

I also have tried $.fn.jexcel.selection with no luck.

Any help or suggestion is appreciated. Thank you in advance.

**Comment by pphod** [comment]
onload: function(instance) {
   instance.updateSelection(x1,y1,x2,y2); // coords of first cell and last cell - last cell is optional
}
