### ISSUE TITLE
Should hidden cells be copied/pasted?

### ISSUE THREAD

**Issue by dexterouschen** [jspreadsheet/ce#174]
Technically they are part of the table, yet they are not visible to users, when users copy/paste in the table, those hidden cells will consume data respectively just like normal cells, and it may be confusing to the users.

Can we at least provide an option in the copy/paste function to skip hidden cells?

I can certainly append this to my pull request if you think it's reasonable.

**Comment by pphod** [comment]
If you would like to skip my suggestion maybe is to leave the hidden columns as last columns? But, it is something to consider.
