### ISSUE TITLE
$('#my').jexcel('getData', true) is not working for current cell value.

### ISSUE THREAD

**Issue by gulshan-mittal** [jspreadsheet/ce#175]
How do we get the current cell value?

**Comment by pphod** [comment]
// Bring all highlighted cells
$('#my').jexcel('getData', true); 

// Bring data from the current focus
$('#my').jexcel('getValue', $.fn.jexcel.selectedCell);

**Comment by ak868308** [comment]
```
var listTbl = jspreadsheet(document.getElementById('student-list'), {
        search: true,
        pagination: 100,
        data: [],
});
var tableData = listTbl.getJson(true);

```
This returns empty array. Here I am setting the table data dynamically (Programmatically) while it return full table data without boolean parameter. Please help
