### ISSUE TITLE
Question about functionnality

### ISSUE THREAD

**Issue by felixvandal** [jspreadsheet/ce#18]
Hello!
i have tried jexcel for a couple hours and so far i love it
i'm doing a BOM (bill of material) web application for my company
working with it, i realise that i could not find some functionnality
could you tell me if i missed them?

-delete row
-prevent user from adding row and column
-responsive column width

i think those are the functionnality i need for the moment
can you help me?

thank you and have a nice day

**Comment by felixvandal** [comment]
also
is there a scroll functionnality?
like you limit with a max height and beyond that height the overflow stay hidden?
keeping the header frozen on top could be nice too

**Comment by felixvandal** [comment]
To prevent the adding row and column from the context menu, i have commented those line in jquery.jexcel.js
but i can still add a column when i TAB from the last column

**Comment by pphod** [comment]
Get the most recent updates, and add these properties in your configuration.
            allowInsertRow:false,
            allowInsertColumn:false,

To delete records right click on the record and then delete the full row.

About the overflow, it is in progress and should be released soon.

Responsive resizing won't be available soon, sorry ;(

Regards

**Comment by felixvandal** [comment]
thank you for your answer
i can live with the responsive for now
for the overflow, in the past i worked with DataTable @https://datatables.net/examples/index
i am "getting inspired" by how they do the scrollable part
i would recommand you to check it out (i am not developping that library)
for the moment i use jexcel to create 2 tables, one that i hide the tbody and the other i hide the thead
its as guetto as it can be XD but it work for now
loocking forward for that excellent plugin

do you also plan on adding a add row over and under feature?
