### ISSUE TITLE
Save Jexcel to Mysql Database

### ISSUE THREAD

**Issue by gitalvininfo** [jspreadsheet/ce#181]
Hi. is it possible to save the Jexcel CSV to mysql database? Please let me know if this is the right place for me to ask. Thank you.

**Comment by pphod** [comment]
https://bossanova.uk/jexcel/examples/getting-data-from-table

**Comment by iFrogLab** [comment]
Dear paulhodel

The url link is empty,
how could I save data  or get all data array ?

**Comment by torafat** [comment]
jexcel table data inserted successfully with PHP MYSQL

![jexcel-file](https://user-images.githubusercontent.com/3815582/96690486-6039df80-13a1-11eb-9970-ec9934a664f8.png)

**Comment by pphod** [comment]
We have created a PHP class to help users on the persistence side of things.

https://github.com/jexcel/jexcel-database-base
