### ISSUE TITLE
Jexcel with database

### ISSUE THREAD

**Issue by gitalvininfo** [jspreadsheet/ce#182]
it is possible to save the csv in JEXCEL to MYSQL database? Please reply...

**Comment by pphod** [comment]
Yes, it is possible. jExcel is a 100% frontend tool. You need a backend to support your database operations, you can choose PHP or NodeJS. And you can export the data from jExcel to your database through an ajax post request.

https://bossanova.uk/jexcel/examples/getting-data-from-table

**Comment by 3s-sports** [comment]
Is there the possibility the data directly to the database via ajax, php?

**Comment by pphod** [comment]
Yes, this might help:
https://github.com/jexcel/jexcel-database-base
