### ISSUE TITLE
Issue when cutting cells from grid with a checkbox defined to clipboard

### ISSUE THREAD

**Issue by SpecmoComptonJames** [jspreadsheet/ce#183]
After upgrading to Version 1.5.4, I have run into an issue when copying (I.E. select rows and ctrl-c) from an jexcel grid instance to the clipboard.  Looks like the jexcel library was updated to escape double quotes recently which appears to fail if the cell is a checkbox type.  This appears to have started to occur with the most recent update.  Can you confirm this is a coding issue?

My work around is as follows by testing if ‘val’ has a method 'match' defined:
Console shows the following error message:

> Uncaught TypeError: val.match is not a function @ 2632

My work around...
Changed: 

> 2632: if ((val.match(/,/g) || val.match(/\n/) || val.match(/\"/))) {

to

> 2632: if ((val.match) && (val.match(/,/g) || val.match(/\n/) || val.match(/\"/))) {

I have forked the library and applied a fix to accommodate errors we are receiving until we better understand what is happening.

https://github.com/SpecmoComptonJames/jexcel/commit/6f29a14c61c6ac7401f1139453ce63302121b0f7

Example Code:

```
 _initExcel: function () {
        let _self = this;
        return new Promise(function (resolve, reject) {

            $('#itemsToScrapGrid').jexcel({
                colHeaders: ['Material Number', 'Serial Number', 'Valid', 'Message'],
                colAlignments: ['left', 'left', 'center', 'left'],
                columns: [
                    {type: 'text'},
                    {type: 'text'},
                    {type: 'checkbox', readOnly: true},
                    {type: 'text', readOnly: true}],
                allowInsertColumn: false,
                allowDeleteColumn: false,
                selectionCopy: true,
                data: [['MAT', 'SERIAL', false, 'Is Not Valid'][,
                ignoreEvents: true,
                colWidths: [200, 200, 50, 450],
                onafterchange: function () {
                    inventoryBulkScrap._data.state.gridIsValid = false;
                },
                onload: function() {
                    _self.enableGrid();
                }
            });
            resolve();
        });
    },

```

Thanks for a great Library!

**Comment by pphod** [comment]
Thanks for spotting that. I have included that in the master repo and it will be released soon.
