### ISSUE TITLE
use ajax to load the grid table page, maybe cause trouble

### ISSUE THREAD

**Issue by xins2018** [jspreadsheet/ce#184]
Thanks for your great job !
  The library is vary useful, and I'm trying to learn it.
  In my project, I use ajax to load page, and get some problem, i must call the destroy of every grid before empty the old content. And the 'remove other objects' in destroy part, I had shield off it, because it cause new page error. Then, I add $.fn.jexcel.current=null into destroy part. And It seems to work well now, but it's not good to change the sources
Or are there any other better options for partial refresh？

 Looking forward to your reply.

**Comment by pphod** [comment]
thanks, I have added that.
