### ISSUE TITLE
Pasting from excel creates a blank space in the last cell of the last row

### ISSUE THREAD

**Issue by apazadevlegacy** [jspreadsheet/ce#186]
Hi Paul, 

I've noticed a strange behaviour: in pasting data from excel it creates an additional space in the last cell of the last column in the last row, it doesn't matter how many columns are pasted, the last one is affected with this additional space, even if it's only one cell.

Here a photo of the data I'm pasting from excel: [data without spaces](http://i1142.photobucket.com/albums/n604/raiskai/2018-07-08%2016_23_17-Libro1%20-%20Excel.jpg)
And here a photo of the data pasted to a jexcel table: [data with a unwanted space](http://i1142.photobucket.com/albums/n604/raiskai/2018-07-08%2016_25_07-jExcel%20_%20Examples%20_%20Data%20table%20with%20fixed%20headers%20and%20scrolling.jpg)

If this can be solved, it could be amazing. By the way, great work man, very helpful!

PS: The capture is from one of the latest examples from your site https://bossanova.uk/jexcel/examples/table-with-fixed-headers
In local development I have the same issue.

**Comment by pphod** [comment]
It has been fixed. It is updated on the master repo.
