### ISSUE TITLE
Request (load remote data from excel )

### ISSUE THREAD

**Issue by ssutar934** [jspreadsheet/ce#189]
How can i load remote data from excel (xls, xlsx) file ?
(same like csv file).

**Comment by pphod** [comment]
No, you can't load xls into jExcel directly. You can use CSV or JSON.

Creating a javascript spreadsheet based on an external JSON file
In a similar way, you can create a table based on an external JSON file format by using the url: directive as below.

```
<html>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-csv/0.8.3/jquery.csv.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jexcel/1.5.0/js/jquery.jexcel.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jexcel/1.5.0/css/jquery.jexcel.min.css" type="text/css" />

<div id="my"></div>

<script>
$('#my').jexcel({
    // The URL from your data file in JSON format.
    url:'/jquery/json'
});
</script>
</html>
```

**Comment by pphod** [comment]
Sorry, it is. It possible to load xls or xlsx. You need to convert to CSV
or JSON.

Regards

**Comment by ssutar934** [comment]
Thanks, 
Yes i'm going to convert it in JSON.

**Comment by ssutar934** [comment]
Hi,
I tried with JSON data.
My JSON structure is 
var d =  [ 
                 {
                  "Column1":"架電結果",
                  "Column2":"総件数",
                  "Column3":"携帯電話件数",
                  "Column4":"性別（男）",
                  "Column5":"性別（女）"
                  }
               ]

and code is

$('#my').jexcel({
                          data: d,
                   });

but result is not correct. Is something i miss ? Please have look.
![result](https://user-images.githubusercontent.com/32446767/43118775-66affbe4-8f4e-11e8-9589-f43a9e80102b.PNG)


Thanks.

**Comment by ssutar934** [comment]
It's working now.  :)
convert JSON to array
