### ISSUE TITLE
Checkbox copy paste

### ISSUE THREAD

**Issue by ravi99249** [jspreadsheet/ce#190]
Hi,
I saw jexcel demos today. Loved it.
I have been using handsontable for a while in many of my projects.
I found jexcel to have some features that handsontable does not have.
However, one feature of handsontable that I did not find on jexcel is:
In handsontable, you can copy a checkbox column (or range of checkbox cells) and paste. On paste, the states of copied checkbox cells is applied in the destination. I loved this feature. It helps in copying configurations very easily.
Do you have any plans of adding this feature in jexcel, or can it be added?

**Comment by pphod** [comment]
It supposed to happen, but using ones and zeros.

Regards

**Comment by ravi99249** [comment]
I did a little testing on the first example on https://bossanova.uk/jexcel/examples and on the jsfiddle link (https://jsfiddle.net/paulhodel/kgmcav01/)

Outcomes:

a) On the examples page, copying of checked checkbox does not work. Unchecked checkbox cells can be copied and pasted well. This issue is not there on jsfiddle page.

b) On the examples page, with a checkbox cell selected (not the checkbox), hitting spacebar does not toggle the checkbox. 

c) On the jsfiddle page, selected cell does not "highlight" correctly for checkbox type cells (when you select a cell with mouse click).

d) On the jsfiddle page, "sometimes" the checkbox toggles even if you click outside the checkbox in the checkbox cell. I was trying to select a checkbox cell - but it toggled the checkbox.

e) There appears to be some issue, when I navigate using arrow keys, in / around checkbox cells.

f) Selecting a checkbox cell should be same as selecting the checkbox - means (1) hitting spacebar with checkbox cell selected should toggle the checkbox and (2) directly clicking the checkbox in a checkbox cell should select the cell containing the checkbox.

**Comment by pphod** [comment]
I am going to improve this option very soon following your suggestions.

**Comment by ravi99249** [comment]
Glad to hear. Could you please let me know once done - I am considering replacing handsontable with jexcel in my projects. I do not know if Github will notify me once you mark this issue as resolved. Thanks.

**Comment by pphod** [comment]
It has been done. Please, you can download from the master repository. I will update the site documentation later on.

**Comment by ravi99249** [comment]
Hello,

3 more things please:

a) When I double click an empty dropdown cell, the first option in the
dropdown gets autoselected. It should just open the dropdown options
without populating the cell.
b) When I click a range of checkbox cells or a column of checkbox cells,
and hit spacebar, only the first cell's checkbox toggles. All should toggle
as all are selected.
c) When I select a value, copy it and then select a range of cells and hit
Ctrl+V (paste), the copied value gets set only in the last cell. It should
apply to all selected cells (like MS Excel)

I am planning to switch to jexcel from handsontable. If things workout, I
will certainly donate.
