### ISSUE TITLE
reset jexcel.current in destroy method

### ISSUE THREAD

**Issue by grumiq** [jspreadsheet/ce#191]
I love jExcel and it works well in my application! However, I have multiple instances on one page and deleting and creating new instances regularly produces errors; the destroy method seems not to reset the jexcel.current variable. This leads to invalid indices in references to the defaults-array. I could repair this in my case by adding 

if ($.fn.jexcel.current == id) $.fn.jexcel.current = null; 

in the destroy method after the source is deleted ( delete $.fn.jexcel.defaults[id]; )

**Comment by pphod** [comment]
It has been done. Available in the master repo. It will be released soon...

**Comment by grumiq** [comment]
Cool, thanks!
