### ISSUE TITLE
Is there a way to programatically focus/unfocus the table?

### ISSUE THREAD

**Issue by apazadevlegacy** [jspreadsheet/ce#196]
Hi Paul,
I'm working on a modal that opens only when a cell value follows a condition, my problem is that even when I gave focus to the first field of the modal after is opened with $("first_field_id").focus(), and it's visually focused if I keep pressing some keys (numbers or letters) what is really focused is the table, and if I press Tabulator when the modal is open the navigation in the table is active behind the modal. 

If I get to pass this behaviour, when I save data with the modal I'll need to focus the next cell of the table, that's why I ask for a way to focus.

Can you give an insight on how to approach this problem.

Here is a demo https://jsfiddle.net/alcidesapaza/9p2js06o/7/

**Comment by pphod** [comment]
https://jsfiddle.net/9p2js06o/8/
