### ISSUE TITLE
Change color many rows is very slow

### ISSUE THREAD

**Issue by MAP-Akamae** [jspreadsheet/ce#198]
In my scenario I need change back color row,  depends with one value in cell. I try many options and all the result is very slow and freezing browser. 

How can optimize change background color for many rows "more one hundred"?

I try change direct in table "dom" and  using event updateSettings , but both is very slow.

**Comment by pphod** [comment]
You can customize your table with pure CSS. For example:

As classes: .c0, .c1, .c2 or .r0, r1, r2 . to apply for all columns or rows. Or specific to one cell using id: #0-0, #0-1, #0-2 (where 0-0 is first column and first row).



<style>
.c1
{
}
.r3
{
}
#3-4
{
}
</style>
