### ISSUE TITLE
Search option for grid 

### ISSUE THREAD

**Issue by primeO** [jspreadsheet/ce#199]
Any option for in build search filter / pivoting the spread sheet !!

**Comment by pphod** [comment]
This is going to be included in the next release. v1.6.0... should be available in the next couple of weeks...

**Comment by contactjavas** [comment]
Great!
The built-in search/ filter functionality would complete this library

**Comment by PragnaBrahmbhatt** [comment]
> This is going to be included in the next release. v1.6.0... should be available in the next couple of weeks...

When this functionality will available?

**Comment by maurorappa** [comment]
@paulhodel, is the search function present in the dev branch?
Cheers!

**Comment by pphod** [comment]
Not yet, but it will be included in the next release. This should be
deployed next Sunday.

Regards

**Comment by pphod** [comment]
Sorry guys, we have deploy the new version. But, this feature is not included. There are several problems in regards to hide values... this is a very complex feature, and we should do that in future versions that will include pagination, lazy loading, conditional loading, dealing with hidden rows, etc.

**Comment by muhdkhokhar** [comment]
When will you release new version?
Without filtering its not complete.

**Comment by pphod** [comment]
Search is available in the v3.

https://bossanova.uk/jexcel/v3/examples/datatables
