### ISSUE TITLE
CSS Breaking when used with twitter bootstrap 3.3.6

### ISSUE THREAD

**Issue by rafaelvascc** [jspreadsheet/ce#2]
Hi, i am trying to used jExcel on an application that uses Bootstrap 3.3.6.
I am loading jExcel``s css after bootstrap`s css and i still having jExcel being rendered as bellow:

![image](https://cloud.githubusercontent.com/assets/2701532/23757306/69eb271e-04b4-11e7-94a1-757060585b9c.png)

When i remove bootstrap.css from the page, jExcel renders normally:

![image](https://cloud.githubusercontent.com/assets/2701532/23757419/c9d7b39a-04b4-11e7-8728-7fa5ce29a654.png)

Thanks for you awesome component btw.

**Comment by paulhodel** [comment]
Hi Rafael,

I have created a fiddle to test and I have just added the box-sizing to fix the corner symbol. I am going to incorporate that in the next commit. One think you should try to do is to load the jExcel css after the boostrap css. Let me know if this helps you.

Please take a look on this:
https://jsfiddle.net/t61bgwf2/1/

**Comment by pphod** [comment]
Hi Rafael,

Thanks for your inquire. I have updated the plugin to avoid conflict with Bootstrap 3. I have tested and it is working fine. I have already commit the changes. https://jsfiddle.net/t61bgwf2/2/
