### ISSUE TITLE
Why & auto converting to &amp;

### ISSUE THREAD

**Issue by umairali** [jspreadsheet/ce#202]
I am adding & and its auto converting to &amp; when i double click on cell. Please give me any suggestion how to remove this.

**Comment by pphod** [comment]
You can use this example to amend the content of the cells after been set.
https://bossanova.uk/jexcel/examples/currency-and-masking-numbers

**Comment by shamshi1988** [comment]
I am also facing the same problem but found a solution after a lot of struggle that will help to other person.

```
jspreadsheet(document.getElementById('spreadsheet'), {
   tabs: true,
   toolbar: true,
   worksheets: [{
       minDimensions: [8,8],
   }],
   oncreatecolumn:function(worksheet, columnNumber, td) {
                if(td.innerHTML.indexOf("&amp;amp;") != '-1'){
                    td.innerHTML=td.innerHTML.replace("&amp;amp;", "&");
                }                
            },
});
```

**Comment by hodeware** [comment]
This code is only applicable for Jspreadsheet Pro v9 or later.
