### ISSUE TITLE
Edit headers

### ISSUE THREAD

**Issue by kickbox** [jspreadsheet/ce#203]
Is it possible to edit the headers while loading from a csv?

**Comment by pphod** [comment]
You can use csvHeaders:true to consider the first line of your CSV as the headers.

**Comment by kickbox** [comment]
No, actually i meant - can we edit the default headers after loading the csv.. Eg. By clicking on the headers in front end.

**Comment by pphod** [comment]
Programatically yes, using setTitle...

**Comment by kickbox** [comment]
Thank you. I think you meant setHeader..
