### ISSUE TITLE
Feature Request: Paste Special

### ISSUE THREAD

**Issue by FL0WL0W** [jspreadsheet/ce#204]
I would like the ability to paste special, such as paste add, paste multiply, and other custom formulas.

Thanks

**Comment by FL0WL0W** [comment]
I got no traction on this in the past 3.5 years. Not even a reply. I ended up implementing my own javascript table for anyone else looking for something similar https://github.com/FL0WL0W/JavascriptTable

**Comment by klren0312** [comment]
why not give pr

**Comment by FL0WL0W** [comment]
It is a whole new implementation, not just a modification to this repository.
