### ISSUE TITLE
drag columns for v1.5.3 (in internet explorer 11)

### ISSUE THREAD

**Issue by bradley-simmons** [jspreadsheet/ce#209]
Hello,

I am generally curious about compatibility with Internet Explorer 11-- More specifically, it seems the drag and paste function for columns works in jexcel version 1.3.3 and IE 11, but does not work with v1.5.3 and IE 11.  I would like to use the fixed headers and scroll from v1.5.3, and I am wondering if you have any suggestions to get the drag and paste function working for v1.5.3 in internet explorer?  

Also, in a more general sense, do you intend to support IE 11, or would you recommend looking for another library if I want to build something compatible with chrome and ie?

v1.3.3 drag working, fixed headers and scroll not available - IE 11
https://jsfiddle.net/gyst8cjL/15/show

v1.5.3 drag not working, fixed headers and scroll working, tbody width not calculated properly (styled with css to fix) - IE 11
https://jsfiddle.net/4w7nuqr8/91/show

Thank You.

**Comment by pphod** [comment]
Please download the most recent version in the master repo. This has been fixed.

**Comment by bradley-simmons** [comment]
thank you paul!
