### ISSUE TITLE
Delete row when header not visible

### ISSUE THREAD

**Issue by felixvandal** [jspreadsheet/ce#21]
If you delete the first and only row when the header is not visible, it is not possible to recreate a row after that row is deleted
is it possible to forbid the user to remove a row when there is only one row?

**Comment by pphod** [comment]
Let me know if it helps you.
https://jsfiddle.net/swL0cya8/

**Comment by felixvandal** [comment]
as a workaround i think ill use the method insert row and put it in my top menu
thanks

**Comment by pphod** [comment]
You can use the minDimensions to define the min numbers of rows and cols for your table.
https://jsfiddle.net/swL0cya8/1/

**Comment by felixvandal** [comment]
that does it thank you
