### ISSUE TITLE
Couple of things

### ISSUE THREAD

**Issue by ravi99249** [jspreadsheet/ce#211]
Hello,

Couple of things please:

a) When I double click an empty dropdown cell, the first option in the
dropdown gets autoselected. It should just open dropdown showing options
without populating the cell.

b) When I click a range of checkbox cells or a column of checkbox cells,
and hit spacebar, only the first cell's checkbox toggles. All should toggle
as all are selected.

c) When I select a value, copy it and then select a range of cells and hit
Ctrl+V (paste), the copied value gets set only in the last cell. It should
apply to all selected cells (like MS Excel)

Thanks

**Comment by pphod** [comment]
I will take a look on these in the next release...

**Comment by pphod** [comment]
a) we have changed the way things works in the dropdown column;
 
the other only available in future versions...

**Comment by ravi99249** [comment]
Thanks for letting me know.

**Comment by pphod** [comment]
Could you please try the new version?
