### ISSUE TITLE
Save data to server ?

### ISSUE THREAD

**Issue by fred2088** [jspreadsheet/ce#214]
is there any way to load csv from local server and save back to local server ?
using formdata, httppost or jquery fileupload ?
any sample to do that ?
Thanks a lot

**Comment by tejcirkulate** [comment]
Take a look at this example:
https://bossanova.uk/jexcel/examples/getting-data-from-table

If you can use this approach to produce the CSV string, next step is easier. Just form-post this string or upload to a server.

I imagine you're trying to save CSV to server on each change. This can be easily accomplished by doing the above inside the onchange handler.

**Comment by pphod** [comment]
Use the getData method to get the data convert to a JSON string and them upload to your server.

**Comment by fred2088** [comment]
Got it work with CSV and JSON using POST function, Thanks

	var data = $('#my').jexcel('getData');
	$('#txt').val(JSON.stringify(data));
	$.post('http://'+window.location.host+"/custom",{text:JSON.stringify(data)});
	$.post('http://'+window.location.host+"/custom",{text:$.csv.fromArrays(data)});

**Comment by AllanCoinaski** [comment]
just to complement it is possible to use getJson too
