### ISSUE TITLE
Why on tab key table is not showing horizontal scrollbar?

### ISSUE THREAD

**Issue by NithinKulal** [jspreadsheet/ce#215]
Scroll bar issue

**Comment by pphod** [comment]
The jExcel is created inside a DIV, you can easily allow a overflow-x in this DIV in order to limit the width and get the scroll happening when desired.

**Comment by tniemann** [comment]
Hi,

I did the same (overflow-x: scroll) but drop downs which are not in the viewport are not displayed.
Any fix es for that?
