### ISSUE TITLE
Enter value and move away with arrows

### ISSUE THREAD

**Issue by ondramu** [jspreadsheet/ce#216]
Hi,
as in Excel, it is more convenient to put value to the cell and move for example with key right arrow to another cell to enter next value and so on.

Today, you have to put value and press enter which get you to cell below and you have to navigate with arrows to cell on the right.

Thanks for the advice how to get this done or if you would plan to do it in future updates

OM

**Comment by tejcirkulate** [comment]
Not sure if this will work but may be you can use onafterchange and in this handler, set the focus on the right cell. It may happen fast enough for the user to not notice the focus on cell below, then onafterchange's refocus on cell-right.

**Comment by pphod** [comment]
The current behaviour is similar to excel, when you double click a cell for edition you use arrows to move the cursor inside the open text editor, not to move from one cell to the other.
