### ISSUE TITLE
types not working

### ISSUE THREAD

**Issue by charlieabela** [jspreadsheet/ce#217]
Hi
I'm building a table with dynamically added headers, widths and column types. Generated headers, widths and relevant types are pushing into arrays (headers, widths, cols) and passed to jexcel:
 `$('#mytable').jexcel({
	minDimensions:[ncols,10],
    	colHeaders: headers,
    	colWidths: widths,
	columns : cols
	});`
while headers and widths are displayed correctly, the types do not seem to be working. Some of the fields are dropdowns and checkboxes, but they are not being rendered. 
Any ideas as to what I'm doing wrong?
thanks in advance.

**Comment by charlieabela** [comment]
issue solved, was not a jexcel issue

**Comment by pphod** [comment]
Great ;)
