### ISSUE TITLE
Fix header and scroll does not work on IE 11

### ISSUE THREAD

**Issue by laysovann** [jspreadsheet/ce#218]
Seems like fix header and scroll does not work on IE 11 :
https://bossanova.uk/jexcel/examples/table-with-fixed-headers

Table width becomes very small that even the row number cannot be seen..

**Comment by TPOborne** [comment]
I've managed to solve this by adding the following CSS: 

```
.jexcel > thead > tr > td {
	display: block;
}

.jexcel > tbody > tr > td {
	display: block;
}

@media screen and (-ms-high-contrast:active), all and (-ms-high-contrast:none)
.jexcel > tbody > tr, .jexcel > thead > tr {
	display: flex;
}

.jexcel > thead {
	float: left;
}

.jexcel > tbody {
	overflow-y: scroll;
	max-height: 400px;
	display: block;
	float: left;
}
```

**Comment by pphod** [comment]
This should be fixed in the most recent version in the master repo.

**Comment by Excel880** [comment]
Excuse me

In IE11 frozen header failure with this code,  not how to solve?

**Comment by pphod** [comment]
Frozen headers only works on browsers that support CSS position: sticky.
