### ISSUE TITLE
Dynamic data

### ISSUE THREAD

**Issue by felixvandal** [jspreadsheet/ce#22]
Hello again Paul
first of all i would like to report some broken pages on the Jexcel website.
All titles of section return on blank page and some are just not found.

second, i would like to know if there is a way to dynamiclly set data in the table
as i previously explain to you, i am doing a BOM application.
when i enter data on a certain column i want to update the entire row with the data i fetch in my database via ajax.
is there a way to refeed data to the jexcel after the initial initialisation
i tried something like this
`$("#datagridContent").jexcel("setData", arrayItem);`
but i get a typeError: Cannot set property data of undefined
on line 1072 of jquery.jexcel.js, the [id] is null because the `var id = $(this).prop('id');` on line 1064 return nothing

is there a way to collect all data from the table?
a function that return the table content?
i run up and down the script and i can't find anything like this

thank you again for your time
have a nice day

**Comment by felixvandal** [comment]
i have begin to look around some method that i have not tried already
i found that if i add data programmatically, the data are removed from the row that move up
i found that setValue is working well, but i have to assign data one by one
i was wondering if there was a better way since my table have 12 columns

**Comment by pphod** [comment]
The correct method is setData. Here is one example of updating the entire table data and one loading remote data via a CSV file.

http://jsfiddle.net/rzr3gL8c/
http://jsfiddle.net/ruvu0895/

**Comment by pphod** [comment]
I have checked and the website seems to be OK. Could you let me know which link you are trying to access?

**Comment by pphod** [comment]
the setData should be use to reload some data into an existing jExcel table.

**Comment by felixvandal** [comment]
i keep on getting the Cannot set property 'data' of undefined
same spot in the jquery.jexcel.js
i have fellowed the fiddle and i keep getting the error
here is how i proceed, maybe i missed something and you will be able to point it out

i use the onchange event of the jexcel creation on a div
in the function referenced by the onchange event i have an ajax that go pump data from my database
on success, i call a function to import those data to a multidimension array
after that, in the same function, i call `$("#datagridContent").jexcel("setData", arrayItem);`
for some reason i keep getting the same error

i even created an array with only simple string and keep getting that error
i continue to dig on my side

thank you again for your time

**Comment by felixvandal** [comment]
i found some reasons to some of my troubles
when you want to setData from the onchange, you must use the object pass in parameter (lesson learn)
second, my trouble is apparent when you copy paste data in the cell
when you copy paste the object pass is the cell, when you manually write data, the object pass is the table
whatever the way you are doing it, the moment you copy paste, the onchange event fire and the cell is pass instead of the table
i will take a look in the script to try to found the problem, i will keep you posted 

Edit:
found the problem (if its a problem)
the paste function pass the cell to setValue 
the setValue call onchange($(this), $(v), value), so basically the onchange receive 2 reference to the cell and the value of the cell
would it be a good idea to always pass object, cell, value instead of caller, cell value?

**Comment by pphod** [comment]
There are two parameters in the onchange event first is the object table,
second is the cell changed.

**Comment by felixvandal** [comment]
i have fixed my problem by getting the object by my own method instead on relaying on the jexcel to pass me the right object

**Comment by tejcirkulate** [comment]
Hi Paul,

I am trying to do something similar for subset of the entire table.

Lets say a table consists of (10 rows, 10 cols).

An Ajax call fetches new data for cells starting from (row 3, col 2) to (row 6, col 7).

I would like to be able to call setData as show in this example:
http://jsfiddle.net/ruvu0895/

But,specify that the data is set of cells starting from (row 3, col 2) like:

$('#my').jexcel('setData', data, 3, 2);

Is there a way to accomplish this please?

**Comment by pphod** [comment]
The method insertRow can give you the option to add new row with default data. If this is not what you are looking for, you can change your data variable and call setData again without any argument, this going to refresh the data.

**Comment by stanleliu** [comment]
Is there function such as setRowData (corresponding to getRowData)  so I can update a row with an array instead of using setValue to assign data one cell by one cell in a row?
