### ISSUE TITLE
Styling jcalendar popup for Jexcel calendar data?

### ISSUE THREAD

**Issue by JDGHHou** [jspreadsheet/ce#221]
I've been trying to change the colors on the jcalendar popup for calendar data types. It's impossible to inspect the jcalendar window because it disappears when I try to use the built-in inspector in Chrome (even when I pause javascript function). I've tried adding CSS rules for .jcalendar. I've tried editing the jcalendar.css file directly. Nothing works. 

I even deleted the link to the jcalendar.css stylesheet and the style is somehow still the same.

Is there a hidden file where the styles are being set?

**Comment by pphod** [comment]
On the jCalendar you can change the header column by overwriting the class:
.jcalendar thead td

I imagine you have some kind of cache problem...
