### ISSUE TITLE
How to append new json data ?

### ISSUE THREAD

**Issue by ssutar934** [jspreadsheet/ce#223]
I want to append new data, if scroll reach to bottom. please suggest how to append new data ?

**Comment by pphod** [comment]
Do you mean blank columns? One option is the minSpareRows for example give you the number of blank rows in the end...

**Comment by ssutar934** [comment]
Thank you for response.
but i want to append new rows with value.
I used 'insertRow' method but it's becomes very slow.
Is any efficient way to insert bulk of records once ?
