### ISSUE TITLE
weird copy-paste behaviour when first copied cell is empty

### ISSUE THREAD

**Issue by magdute** [jspreadsheet/ce#226]
When first copied cell is empty, parseCSV "shifts" first row one cell to left.

Suggested fix of parseCSV function:

Replace:
            if (matched_delimiter.length && matched_delimiter !== delimiter) {
              // Since this is a new row of data, add an empty row to the array.
              rows.push( [] );
            }
To:

	    if (matched_delimiter.length)
            if (matched_delimiter !== delimiter) {
              // Since this is a new row of data, add an empty row to the array.
              rows.push( [] );
            }else // if first comes delimiter, means first copied cell was empty
		rows[rows.length - 1].push('');

**Comment by pphod** [comment]
This has been fixed.
