### ISSUE TITLE
Another weird copy-paste behaviour: when overwriting selection, data are passed to end instead of start of selection

### ISSUE THREAD

**Issue by magdute** [jspreadsheet/ce#227]
Shouldn't be pasted to start?
Suggested fix:

Replace:
// Selected cell will be the first in the row
$.fn.jexcel.selectedCell = $(o2);

To:
// Selected cell will be the first in the row
$.fn.jexcel.selectedCell = $(o1);

at line 661

**Comment by pphod** [comment]
It was not possible to merge that. Could you check if the behavior is still not desired in the most recent version?
