### ISSUE TITLE
Nested headers

### ISSUE THREAD

**Issue by cevc96** [jspreadsheet/ce#23]
Hi, I'm looking for property nested header like handsontable, has anyone used it in jexcel?

![image](https://user-images.githubusercontent.com/11530293/29948352-ef2eb848-8e73-11e7-858e-5efc96965756.png)

**Comment by pphod** [comment]
Same examples:
https://jsfiddle.net/sngz3q4a/
https://jsfiddle.net/7metkm8s/

**Comment by felixvandal** [comment]
I was writting an answer when you answered Paul XD
[https://jsfiddle.net/fvandal/j8ttmnvd/](url)
