### ISSUE TITLE
Display Issue in Internet Explorer (11)

### ISSUE THREAD

**Issue by sebastianraese** [jspreadsheet/ce#231]
Hey,

while doing my first steps with JExcel, I came across a strange display issue in IE. The library is working like a charm in Firefox but when loading the same page in IE, I get the following result:

![samples](https://user-images.githubusercontent.com/40124201/46034243-77456f00-c100-11e8-8222-e81cec6ec671.png)

Is this a known issue? Did I forget to link or setup anything (after linking JQuery 3.1.1, I refferenced to 'jquery.jexel.js' and 'jquery.jexcel.css'?

Thanks for your support!

**Comment by pphod** [comment]
Remove the display:flex on the css and will be fine.

**Comment by sebastianraese** [comment]
Cool, thanks! Works as expected.

**Comment by pphod** [comment]
The new version that will be released soon will have that fixed.
