### ISSUE TITLE
Feature Request: Keep formulas on Insert Row

### ISSUE THREAD

**Issue by vsdotnetguy** [jspreadsheet/ce#232]
As far as we can tell when Inserting Rows, formula based cells are not copied like would normally happen in Excel.  Is it possible for this to be an option on the Insert Row method?

We realize this can probably be done manually in the oninsertrow event but would like to see it be an option on the insertrow method.

Please advise.

Thanks in advance,
Bob Baldwin
Trabon Solutions

**Comment by pphod** [comment]
Unfortunately there is not such native option in our roadmap at this moment. You should do that with the oninsertrow column or with the updateSettings option.
