### ISSUE TITLE
Populate dropdown with data coming from an ajax request based on other dropdown selection

### ISSUE THREAD

**Issue by matteopoile** [jspreadsheet/ce#233]
I'm trying to use filter to show data coming from an ajax request
`columns: [
        { 
          type: 'dropdown',
          source:[],
          filter: getPossibleChoices
        },`

in getPossibleChoices I need to return a source array created asyncronously from the response of an ajax request.
I tried to set to async the jQuery ajax request but it didn't work.

Have you got some example with an ajax request of this kind?

**Comment by pphod** [comment]
The method in filter is to Filter whatever you have loaded in source. It is not possible to get remote data everytime the editor is opened. So, you should say what are your options on the source and use the filter to do whatever you want within the source.
