### ISSUE TITLE
How to access $(cell) in contextMenu?

### ISSUE THREAD

**Issue by tejcirkulate** [jspreadsheet/ce#234]
Hi,

I see from the sources that only row number or col number is passed as argument to the context menu function, along with a string to say whether the number is row or col.

How then should one access $(cell) in the context menu? or get both the row and col for a right-clicked cell?

**Comment by pphod** [comment]
This is going to be included in the next release...

**Comment by tejcirkulate** [comment]
Wonderful. Thank you.

**Comment by pphod** [comment]
In the new version in the master repo, you can get the third argument the event the generates the contextMenu. So you can get the cell by $(e.target).
