### ISSUE TITLE
context menu operates (deletes ir inserts rows/columns) on selected cell, not on cell, where context menu was called - shouldn't it work were it was called? Maybe it should select cell too

### ISSUE THREAD

**Issue by magdute** [jspreadsheet/ce#235]
context menu operates (deletes ir inserts rows/columns) on selected cell, not on cell, where context menu was called - shouldn't it work were it was called? Maybe it should select cell too

**Comment by tejcirkulate** [comment]
I agree. I think this is similar to what I just filed earlier today.

https://github.com/paulhodel/jexcel/issues/234

**Comment by pphod** [comment]
You will be able to customize the behavior using the contextMenu initialization directive. Please, bear in mind the new version you can get the event so you can have all information you need.
