### ISSUE TITLE
API Change Request: Pass event object to open editor

### ISSUE THREAD

**Issue by tejcirkulate** [jspreadsheet/ce#236]
I am trying to show a HTML blob hovering around cell when the cell is in open editor mode.

The aim is to do something like what happens in the context menu:

$("#jexcel_contextmenu").css({
                                    display: 'block',
                                    top: e.pageY + 'px',
                                    left: e.pageX + 'px'
                                });

This requires the event object to be passed into the editor. Is there any other way to accomplish this?

**Comment by pphod** [comment]
You have the event being passed to the contextMenu method, third argument. Please try the new version.
