### ISSUE TITLE
Feature Request: Autocomplete filter using StartWith instead of Contains

### ISSUE THREAD

**Issue by sharon-elihis** [jspreadsheet/ce#237]
I would like to request a feature for the Autocomplete column.
Currently an Autocomplete column uses "contains"(indexOf), meaning if the input text exists **anywhere** in the strings in the source array
It would be nice also to have the option for it to use "startWith", meaning only if the input text exists at the **very beginning** of the the strings in the source array. 

Current workaround: 
```
$.ui.autocomplete.filter = function (array, term) {
	var matcher = new RegExp("^" + $.ui.autocomplete.escapeRegex(term), "i");
	return $.grep(array, function (value) {
		return matcher.test(value.label || value.value || value);
	});
};
```
found [here](https://stackoverflow.com/questions/3148195/jquery-ui-autocomplete-use-startswith)

Thank you in advanced for reading and **Thank you for the wonderful plugin**

**Comment by pphod** [comment]
Please try the new version. Autocomplete works in a different way now... including multiple options, etc.
