### ISSUE TITLE
Fire onchange

### ISSUE THREAD

**Issue by felixvandal** [jspreadsheet/ce#24]
I was wondering if it was a feature done on purpose or a mistake
deleteRow and insertRow does not fire the onchange event
let me know what you think about this
would it be a good idea to pass the name of who fire the onchange event?

**Comment by pphod** [comment]
I have added the events, including oninsertrow and ondeleterow. You can
keep using the onchange and onbeforechange or onafterchange. Please get the
most recent updates from the repository.

**Comment by felixvandal** [comment]
i will check it out
thanks

**Comment by pphod** [comment]
Take a look on this:
https://jsfiddle.net/6u58w7dL/1/
