### ISSUE TITLE
chrome and safari timeout from iphone ?

### ISSUE THREAD

**Issue by fred2088** [jspreadsheet/ce#240]
Dear Sir,
I have try Jexcel with 8 column of dropdown to external JSON lookup, but Chrome and safari got timeout from iphone and can't look the list, but chrome on android without any problem ?

Regards

**Comment by pphod** [comment]
Have you tried to look on the console? Any error? Are you trying to get a json from a different domain?

**Comment by fred2088** [comment]
this happen seem when using a local web server without internet connection

solved by removing  the following file :
run_prettify.js
found that http: URL is refer within from the script file while no internet connect for standard web server ...

**Comment by pphod** [comment]
Great! ;)
