### ISSUE TITLE
Context menu "Save as CSV" is not working on FireFox (though works on Chrome). On Chrome utf-8 csv does not have BOM prepending, resulting in garbage on Excel

### ISSUE THREAD

**Issue by magdute** [jspreadsheet/ce#248]
Context menu "Save as CSV" is not working on FireFox (though works on Chrome). On Chrome utf-8 csv does not have BOM prepending, resulting in garbage on Excel. BOM can be added by replacing
_var blob = new Blob([data], {type: 'text/csv;charset=utf-8;'});_
with
_var blob = new Blob([new Uint8Array([0xEF, 0xBB, 0xBF]),"Text",data], {type: 'text/csv;charset=utf-8;'});_

but what to do with FireFox?

**Comment by magdute** [comment]
Ok, for Firefox need to attach thsi created anchor to DOM

**Comment by pphod** [comment]
It has been fixed on v3.
