### ISSUE TITLE
Is paging possible or partial load data ?

### ISSUE THREAD

**Issue by ssutar934** [jspreadsheet/ce#252]
Hello Paul,
Is paging possible ? Please suggest the version no.

**Comment by pphod** [comment]
It will be in the future. You can subscribe us:

https://www.patreon.com/bePatron?u=17038338&redirect_uri=https%3A%2F%2Fbossanova.uk%2Fjexcel%2Fexamples%2Fincluding-formulas-on-your-spreadsheet&utm_medium=widget

To help improve our library. New nice features in the future if we can get enough support...
