### ISSUE TITLE
cells's navigation 

### ISSUE THREAD

**Issue by ygss3614** [jspreadsheet/ce#253]
On a smaller screen when my worksheet is larger than the maximum width of div and scrolling is active, 
you can not use the arrow to navigate to the right to see the last cells, the user needs to use the scroll bar.
Is there a way to navigate using the arrows?

**Comment by cardozoarmando** [comment]
Dealing with the same thing here, any suggestions?

**Comment by pphod** [comment]
There is a new option tableOverflow with tableWidth

This will give scrolls in the whole table in the x-axis.

**Comment by sasha-x** [comment]
I see good horisontal+vertical scrolling behavior on FF with settings:

```js
        var selectionActive = function(instance, x1, y1, x2, y2, origin) {
            var cellName2 = jexcel.getColumnNameFromId([x2, y2]);
            var cellTo = mySpreadsheet.getCell(cellName2);
            cellTo.scrollIntoView({
                block:"nearest", 
                inline:"nearest"
            });
        };
        var options = {
            allowInsertRow: true,
            allowManualInsertRow: true,
            tableOverflow: false,
            data: data,
            columns: columns,
            onselection: selectionActive
        };
        window.mySpreadsheet = $('#spreadsheet').jexcel(options);
```
