### ISSUE TITLE
maximum number of rows (minSpareRows)

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#254]
Hi Paul,
Great job! A minimalist and high performing spreadsheet control is a great contribution to the community!

We are planning to use a spreadsheet control in order to copy paste data from excel and then save it to a database. The average number of rows will be around 10k. When I set minSpareRows to 9000, I am getting a "maximum call stack size exceeded" error, while 1600 rows are created. 

Do you think this bug can be easily resolved? What would you recommend?

Thanks

**Comment by pphod** [comment]
No, large tables is a limitation of DOM. To fix that we need to implement some kind lazy loading, or any other methods. We have plans to implement that but won't be in the next version. Do you know handsontable? It is a similar plugin and they have that implemented.
