### ISSUE TITLE
Formula and decimal precision

### ISSUE THREAD

**Issue by beruken** [jspreadsheet/ce#259]
I'm trying to use simple formula =Sum(C1-C3) and the visual shows about 10 decimal places. I tried this with both numeric and text field types. This happens when initializing and loading data. I tried text based values and number prior to bringing in the data. What could be causing this?

Also, why does getData return everything as string as opposed to evaluating the type?

Thanks for all your work!

**Comment by beruken** [comment]
added line in function executeFormula line 3821  if($.isNumeric(value)) value = Number(value).toFixed(2);
worked for my purposes. For some reason the eval() function  was inconsistent on the return value precision
` // Convert formula to javascript
        try {
            var value = eval(excelFormulaUtilities.formula2JavaScript(formula));
            if($.isNumeric(value)) value = Number(value).toFixed(2);
        } catch (e) {
            var value = null;
        }`

**Comment by pphod** [comment]
You don't need to update jExcel source code. You have a updateSettings method you can perform actions out of the jExcel code. So, you can customize your tables without changing the native code.

In the following example we add formatting.

https://bossanova.uk/jexcel/examples/including-formulas-on-your-spreadsheet

**Comment by cbeltrangomez84** [comment]
Hi, the link is broken, thanks
