### ISSUE TITLE
Is possible edit cell in mobile?

### ISSUE THREAD

**Issue by cevc96** [jspreadsheet/ce#26]

**Comment by pphod** [comment]
I have updated the master repo. You just need to sync and get the most recent version. The touch in mobile will edit the cells now and re-order if you click in the headers.

**Comment by kristofvass97** [comment]
Hi @paulhodel,
I'm trying to edit the cells on mobile (Safari and Chrome as well, using jExcel v2.0.0) but after touching a cell nothing happens. After touching the header and long-touching then that column, the first row will change but nothing more. Do you have any solution for this?

**Comment by pphod** [comment]
Did you try long touch in the cells

**Comment by kristofvass97** [comment]
@paulhodel Yes, I did but sadly nothing. It's not working either with the examples on your website.

**Comment by kristofvass97** [comment]
@paulhodel Now i tried with jExcel v1.5.7 and touching working nice with that.
