### ISSUE TITLE
Update data (insertRow/setData) from background/SignalR response

### ISSUE THREAD

**Issue by SFoster84** [jspreadsheet/ce#260]
I'm trying to update a sheet by adding rows or updating the entire set from a signalr message and it doesn't appear to update the table. Is this because it's not happening from a call using the UI?

**Comment by SFoster84** [comment]
Issue on my side.

**Comment by 0xyy** [comment]
@SFoster84 can u share how you did it please, i am struggling to add rows dynamically, when i clikc the table is not updating
