### ISSUE TITLE
Formulas don't get calculated when only contain hardcoded values

### ISSUE THREAD

**Issue by Miki-AG** [jspreadsheet/ce#263]
See [codepen](https://codepen.io/_miki_/pen/VVXpvK
):

=MAX(A1,B1) --> 44 
=MAX(21,22) --> !!!

If the formula depends on other cells it gets correctly calculated. If there are only hardcoded values, the formula is not calculated.

**Comment by pphod** [comment]
The formulas were written by third party collaborators. jExcel just call external methods. We are planning in the future to rewrite all basic methods. I suggest you rewrite this method on your side (the method should be in the global scope).

function MAX(a,b) {
// your code here
}
