### ISSUE TITLE
Cell content overflow in IE

### ISSUE THREAD

**Issue by ikinner-ch** [jspreadsheet/ce#265]
Hi Paul! Thanks for jExcel - it's a great bit of code that I have enjoyed working with!

I can't seem to prevent cell overflow in IE to save my life. If the cell content exceeds the size of the column width, it spills into the adjacent cell. I blame IE by default, but I'd really like to know if you have any ideas. Thanks for your help!

**Comment by pphod** [comment]
Sorry, in this case we are working with a HTML table. So, there will be certain limits when compare to the excel user experience. But, check the new version out. There are lot of nice features ;)

**Comment by ikinner-ch** [comment]
So jExcel isn't compatible with IE?

Ian Kinner
Colburn Hill Group

________________________________

**Comment by pphod** [comment]
We use jquery, so should have a great level of compatibility. We have improved a lot in the new version. So, please check it out...

**Comment by ikinner-ch** [comment]
Just fyi – I fixed this issue with "$(cell).css('display','inline-block');”

IE doesn’t consider a td a block-level element, and so therefore doesn’t respect overflow:hidden. Setting the td to display as inline-block allows the cell width to be fixed in IE. I’m not sure if this could break any other applications of jexcel, but it has no side-effects in my implementation.
