### ISSUE TITLE
Loader not display when I show it on delete or some long process

### ISSUE THREAD

**Issue by PragnaBrahmbhatt** [jspreadsheet/ce#268]
Hello, I am trying to add loader because when I remove multiple fields then for user experience screen is hang. but actually in it doing process like update cell etc..
So here I add the loader in **updateCells** function in **jquery.jexcel.js** 
The issue is I can see in console that loader is in hide/show but can not see it in display.
I also check if there is any z-index or some other process but can not find.
I remove 5 column/2 row and the result will display to chart and during that process I am trying to display loader.
Please help me how can I show the loader.

**Comment by pphod** [comment]
Sorry, you need to send same example. But this seems out of the jExcel scope... ;(
