### ISSUE TITLE
Column sorting options are shown while right click of the column headers

### ISSUE THREAD

**Issue by Ilayaraja-n** [jspreadsheet/ce#272]
Even though the “columnSorting” property set to false, still it shows the column sorting options (i.e. Order ascending and Order descending) on right click of column headers.
![column-sorting](https://user-images.githubusercontent.com/46338652/50626015-c85fcd00-0f51-11e9-9737-f50055aa85f8.png)

**Comment by pphod** [comment]
This has been fixed in the new version 2.0.0
