### ISSUE TITLE
Can I load JExcel from Webpack project using require('jexcel') or import?

### ISSUE THREAD

**Issue by hugeps** [jspreadsheet/ce#274]
trying 
window.$ = require("jquery")
window.$.jexcel = require('jexcel');

Maybe there's an alternative way ?

**Comment by adamdehaven** [comment]
Yes, you can. I'm also using Babel and some other things, but, this should get you going. In my example, jQuery already exists in my environment. If you're including jQuery with npm/webpack, you'll need to modify a bit (likely with [ProvidePlugin](https://webpack.js.org/plugins/provide-plugin/?_sm_au_=iVVJVsLVZB2HR2nM#usage-jquery)). 

Here's my setup:

```javascript
// webpack.config.js

const webpack = require('webpack');
const path = require('path');

const config = {
    // other config...
    externals: {
        jquery: 'jQuery', // already exists in environment
    },
}

module.exports = (env, argv) => {

    if (argv.mode === 'development') {
        // dev settings
    }

    else if (argv.mode === 'production') {
        // prod settings
    }

    return config;
};
```

```javascript
// app.js

import $ from 'jquery';
import './vendor/jquery.jexcel-v1.5.7.js';
```
