### ISSUE TITLE
Add sorting icon bydefault in thead

### ISSUE THREAD

**Issue by PragnaBrahmbhatt** [jspreadsheet/ce#275]
Hello,
How to change style of thead -> td ? 
In below link here is functionality to change style of tbody td.
I need to add basic sorting icon in thead->td
Please help me if there is any pre build funciton or any other way to do this.
Thank you

https://bossanova.uk/jexcel/examples/table-styling

**Comment by PragnaBrahmbhatt** [comment]
I found one solution as below but still not exact solution. I added css for thead->td.  I put this comment here so it can help other users or it can give any idea to other users.
`table.jexcel thead td {
    background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABMAAAATAgMAAAAPPt5fAAAACVBMV…djwAYEwGQKiGDsBJFsTA5AUoJhAqZaiDhEDVg9RC/MHEwAANsMA91AQfd/AAAAAElFTkSuQmCC) no-repeat center right;
}`

**Comment by pphod** [comment]
This works fine!
