### ISSUE TITLE
formulas in data return text. Cell references using "=" return error

### ISSUE THREAD

**Issue by pythonBerg** [jspreadsheet/ce#276]
I have carefully followed directions wrt to required libraries. When typing sum(range) in cell, it returns correct value. When placing =b3/b4 in data, results is not interpretted. 

 data = [
	[1, 834000],
	[2, 834000],
	[3, 834000],
	[4, 834000,,'Cap Rates',.06,'7%','8%','9%','10%' ],
	[5, 834000,,'Value',"=b1*2",'=b2','=e4','=e5',834000/.1],
	[6, 834000],    ];

1	834000							
2	834000							
3	834000							
4	834000		Cap Rates	0.06	7%	8%	9%	10%
5	834000		Value	=b1*2	=b2	=e4	=e5	8340000
6	834000							
7	834000							
8	834000	

I have done my diligence looking for my error. Please 	point me in right direction

<script type="text/javascript" src="{% static 'node_modules/jexcel/dist/js/jquery.jexcel.js' %}"></script>
<script type="text/javascript" src="{% static 'node_modules/jexcel/dist/js/excel-formula.min.js' %}"></script>
<script type="text/javascript" src="{% static 'node_modules/numeral/numeral.js' %}"></script>
Using jquery 3.1.1
Thanks

**Comment by pphod** [comment]
Please, update your version to  3.5.7 and use capital letters.

B1*2, B2, E4, etc...

Regards,

**Comment by pythonBerg** [comment]
The capitalization makes big difference. Did you mean 3.5.7 or 1.5.7 for
version? Should I be able to type into a cell =B4+B5? Any reference to
other cells using '=' returns error in grid, thought it now works in data.
I see the same in online examples so perhaps I am making too many
assumptions about functionality.

Thanks

**Comment by pphod** [comment]
Type  =B4+B5  should work fine in the most recent version. Sorry, I meant
v1.5.7

Regards,

**Comment by pythonBerg** [comment]
That does work, thanks.
