### ISSUE TITLE
'getData' function returns inaccurate value in Nested header case

### ISSUE THREAD

**Issue by Jooh34** [jspreadsheet/ce#277]
i added nested header on my project based on the document sample
(https://jsfiddle.net/paulhodel/hpv4anat/)

![2019-01-15 9 30 40](https://user-images.githubusercontent.com/15865928/51150112-46a06580-18a8-11e9-880a-06294f9b304f.png)

![2019-01-15 9 12 25](https://user-images.githubusercontent.com/15865928/51149543-e7d9ec80-18a5-11e9-8ce5-ffbcf96a9df7.png)

nested header works well but when i call the function 'getData', it returns more values than i expected.

for example, in this case 'getData' is expected to return list with 3 elements
but it actually returns extra null more
[
[Mazda,2001,2000,2006-01-01 00:00:00,null,null],
[Pegeout,2010,5000,2005-01-01 00:00:00,null,null],
[Honda Fit,2009,3000,2004-01-01 00:00:00,null,null],
[Honda CRV,2010,6000,2003-01-01 00:00:00,null,null]
]

after some research i found that 'getData' function doesn't work well in nested header case

![2019-01-15 9 35 53](https://user-images.githubusercontent.com/15865928/51150290-fd9ce100-18a8-11e9-8d46-3b53a4d19997.png)

var x = $(this).find('thead tr td').not(':first').length;
x is number of columns, but in nested header case, this code aggregate all headers including nested header. so the size of returned list is longger than we expected

so i think that this line should be changed like this,
var x = $(this).find('thead:last tr td').not(':first').length; 

this code calculate only last header's column size. i think this code would reflect user's intent better

**Comment by pphod** [comment]
This has been fixed in the new version. Please download the new version 2.0.0
