### ISSUE TITLE
How do I get the headers in the output?

### ISSUE THREAD

**Issue by sady143** [jspreadsheet/ce#278]
I get output as
[["2008-12-12 8:8:8","10"],["2008-12-12 8:8:8","30"],["2008-12-12 8:8:8","50"],["2008-12-12 8:8:8","60"]]

What I need is something like
[{Date: "2008-12-12 8:8:8", Quantity : "10"},{Date: "2008-12-12 8:8:8", Quantity : "30"},{Date: "2008-12-12 8:8:8", Quantity : "50"},{Date: "2008-12-12 8:8:8", Quantity : "60"}]

    var gotData = $("#my-spreadsheet").jexcel('getData', false);
    $(".printData").html(JSON.stringify(gotData))

**Comment by pphod** [comment]
There is no native facility to do that. You should right a method to convert jExcel output in your desirable format.
