### ISSUE TITLE
In Header Set 'getHeader' method is not found

### ISSUE THREAD

**Issue by ashraftalib** [jspreadsheet/ce#28]
Hi,
i was setting header title so for this first i will take old value by using getHeader method but jquey is showing error this method is not found even looked in js file it is not there. Please help me.

**Comment by felixvandal** [comment]
Hello ashraftalib
can you provide some code?
like how you initialise your table with jExcel and how you set the header?
thanks

**Comment by pphod** [comment]
http://jsfiddle.net/paulhodel/2cxmato7/

**Comment by ashraftalib** [comment]
In your example can you autopopulate  old value in promptbox as you are editing first header. I mean already input box should  have old value that will come to 'getHeader' method for index 0

**Comment by pphod** [comment]
http://jsfiddle.net/paulhodel/t876uvbc/

**Comment by pphod** [comment]
To get the changes, please download the file from the repository. I have updated the library.
