### ISSUE TITLE
Load local csv from input file

### ISSUE THREAD

**Issue by AmirinNS** [jspreadsheet/ce#280]
Hi, it is possible to load a local csv in jexcel? From [example](https://bossanova.uk/jexcel/examples/creating-a-table-from-an-external-csv-file) code below, 
```javascript
$('#my').jexcel({
  csv:'http://cdn.bossanova.uk/demo/demo1.csv',
  csvHeaders:true,
});
```
My attempt is to load csv from user input file, 
```javascript
$('#my').jexcel({
   csv:inputFileFromUser,
   csvHeaders:true,
});
```
It produce GET request 404 error which is it try to load an url instead 

![snap345](https://user-images.githubusercontent.com/23518901/51252487-ec51f280-19d6-11e9-9290-5d6c05ecbdff.PNG)

**Comment by pphod** [comment]
Unfortunately, CSV only can be loaded by within a remote file. In the case you want to load data from a variable in the initialization, you should use data:[[]]. 

Regards,

**Comment by AmirinNS** [comment]
Hi, I able to solve this anyway. For those who wants to load local csv file, if you notice there is a csv plugin in jExcel distribution folder. 
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-csv/0.8.3/jquery.csv.min.js"></script>
```
By following the jquery.csv [github ](https://github.com/evanplaice/jquery-csv), you can read csv file locally. This is example code that I produced, note that I already initialize the excel table
```html
<input type="file" id="csvInput"/>
```
```javascript
var reader = new FileReader();
$("#csvInput").change(function(){
csvFile= this.files[0];
 if (csvFile) {
    reader.readAsText(csvFile, "UTF-8")
    reader.onload = function (evt) {
      data = $.csv.toArrays(evt.target.result)
      $('#excelTable').jexcel('setData',data, false);
    }
  }
}
```

**Comment by Auxiliary-android-asynct** [comment]
@AmirinNS https://stackdev.space/questions/is-it-possible-to-fetch-a-jsp-page-using-ajax
