### ISSUE TITLE
Delete row, get row number

### ISSUE THREAD

**Issue by cwewells** [jspreadsheet/ce#282]
How can I get the currently selected row number? When using jquery in the tbody, the class='selected' changes when I click the button I'm using to remove a row. I need to use a button as a mouse cannot be assumed to be in use on the table,

Thanks

**Comment by pphod** [comment]
The problem is, you can get that by a method getSelectedCells for example. But, if you click in the button outside jExcel, your cells will be deselected. You can use an event onselection to keep those cells you are interested in to use in your button.

 ```
   var selectedRow = [];

    $('#my').jexcel({
        data:data,
          onselection:function(a, b, c) {
            var d = $(b).prop('id').split('-');
            var e = $(c).prop('id').split('-');
            if (d[1] && e[1]) {
                selectedRow = [d[1], e[1]];
            }
        }
    });

function deleteRows()
{
    if (parseInt(selectedRow[0]) > parseInt(selectedRow[1])) {
        i = parseInt(selectedRow[1]);
        f = parseInt(selectedRow[0])
    } else {
        i = parseInt(selectedRow[0]);
        f = parseInt(selectedRow[1]);
    }

    $('#my').jexcel('deleteRow', i, f-i+1);
}
```

**Comment by cwewells** [comment]
Thank you. I will incorporate that approach into my code. BTW, thanks for the great library, works great.

**Comment by pavan-cs** [comment]
> The problem is, you can get that by a method getSelectedCells for example. But, if you click in the button outside jExcel, your cells will be deselected. You can use an event onselection to keep those cells you are interested in to use in your button.
> 
> ```
>   var selectedRow = [];
> 
>    $('#my').jexcel({
>        data:data,
>          onselection:function(a, b, c) {
>            var d = $(b).prop('id').split('-');
>            var e = $(c).prop('id').split('-');
>            if (d[1] && e[1]) {
>                selectedRow = [d[1], e[1]];
>            }
>        }
>    });
> 
> function deleteRows()
> {
>    if (parseInt(selectedRow[0]) > parseInt(selectedRow[1])) {
>        i = parseInt(selectedRow[1]);
>        f = parseInt(selectedRow[0])
>    } else {
>        i = parseInt(selectedRow[0]);
>        f = parseInt(selectedRow[1]);
>    }
> 
>    $('#my').jexcel('deleteRow', i, f-i+1);
> }
> ```

this code is not working for v3

**Comment by pavan-cs** [comment]
@paulhodel  is there any solution for same issue, version-3
