### ISSUE TITLE
Formula not being applied to the column when there is change in the value in read-only table.

### ISSUE THREAD

**Issue by avidsouza** [jspreadsheet/ce#286]
I have 3 tables and i changed the value of the cell of editable table and after calculations i have set the value to the cell of a read-only table. But the column has formula but not auto-calculated due to change but remains the same value.
var cell = $('#myId').jexcel('getCell','B1');
$(cell).html(value);

Value has been set in the particular cell but the total column shows the old total , but didn't recalculate based on the new cell value.

**Comment by pphod** [comment]
This has been fixed in previous versions.
