### ISSUE TITLE
Issue in selecting multiple cells

### ISSUE THREAD

**Issue by PragnaBrahmbhatt** [jspreadsheet/ce#289]
Hello,
If the table width is 100%, the page is **responsive** and there are **multiple columns** then there is issue in **cell selection** of multiple columns.

Please check below link, in which I created same scenario with this issue. 
https://jsfiddle.net/brahmpragya/1Ljkp0mq/11/

**Comment by pphod** [comment]
There are still room for improvement, but you can use something like that in regards to the scrolls follow the arrows and the corner to be hidden correctly.
https://jsfiddle.net/paulhodel/2aecp8rd/

**Comment by PragnaBrahmbhatt** [comment]
@paulhodel , 
Yea there is improvement that I can use arrows for selecting cells but the corner still not hidden correctly. 
Thank you.
