### ISSUE TITLE
Make some column/row fixed

### ISSUE THREAD

**Issue by PragnaBrahmbhatt** [jspreadsheet/ce#291]
_How to freeze row/column fixed in table?_

By using current functionality we can freeze headers but can not freeze any row / columns. 

I tried [**TableHeadFixer**](https://www.jqueryscript.net/table/jQuery-Plugin-For-Fixed-Table-Header-Footer-Columns-TableHeadFixer.html) but, If I use this plugin then I am getting multiple errors in JExcel functionality. 

So I can not merge both the functionality of **TableHeadFixer** and **JExcel**

**Comment by pphod** [comment]
This is already included in the roadmap. So, I am going close this one.

**Comment by spdrman** [comment]
I would propose allowing sticky-rows... Here is a rough specification:

1. Sticky to bottom
This would need to then be bypassed by the COLUMN SORT function, and also the "ENTER" key that allows adding new rows... so if the row is sticky to bottom, any time you get to the bottom and hit enter to create a new row at the bottom, the new row will show up above the "sticky to bottom" row. This would also require the formula inside the cell for the bottom row to automatically update to include the additional row in the formulas like SUM, etc.

2. Sticky to top
This would need to then be bypassed by the COLUMN SORT function

3. Sticky to top/bottom of group of rows
This would need to then be incorporated into the COLUMN SORT function, to sort rows inside each group, but not to mix them together, and to maintain the sticky row at the top/bottom of the group. 

**OPTION TO ADD TO FUNCTIONALITY OF #3 ABOVE**
I propose modifying the "ENTER" key function when you are at the bottom of a group (before the sticky row), to add a new row to the group, similar to "sticky to bottom" functionality, except specific to each group. Then, to navigate without adding a new row, the user would rather use the arrow keys.
