### ISSUE TITLE
Autocomplete cells in scrolling tables

### ISSUE THREAD

**Issue by italba** [jspreadsheet/ce#293]
The options lists for autocomplete cells does not follow the table scroll position, it appears far away from select cell
![schermata del 2019-02-12 15-51-38](https://user-images.githubusercontent.com/47567079/52644850-e836c900-2edf-11e9-9b37-9e644c19a4b9.png)

**Comment by pphod** [comment]
You can add position:relative in the jexcel style. This will fix the problem for now... I am going to rethink a better solution for that.

.jexcel-content {
position:relative;
}

**Comment by caotoanbk** [comment]
I'm using jexcel v3, and have same issue, add position: relative to .jexcel-content not work for me

**Comment by pphod** [comment]
Can I have a jsfiddle, please?
