### ISSUE TITLE
Do not show warning alert during column or row deletion

### ISSUE THREAD

**Issue by alexis86** [jspreadsheet/ce#299]
We do not allow user to delete column or row. This is configuration: 
                var jExcelParams = {
                editable: true,
                allowInsertRow: false,
                allowInsertColumn: false,
                allowDeleteRow: false,
                allowDeleteColumn: false,
            }
but when user select column or row and click "delete" button the alert warning is appeared ("Are you sure to delete the selected rows?"). How we can avoid this alert message and does not show?

**Comment by pphod** [comment]
It has been fixed, please download the updated version from the master repository.
