### ISSUE TITLE
Options using right click doesnt work!

### ISSUE THREAD

**Issue by jeduarz** [jspreadsheet/ce#3]
I tryed from demo page and I checked that right click show menu but it is hided immediately
I was thinking in use it but, sorry

Updated: Ok I checked that it shows only while press right click. I'm using trackpad on MacOS El Sierra

**Comment by pphod** [comment]
I can't test in the same conditions you have. But, I have tested in several different browsers and conditions and it seems it is working fine. I would be happy to help, but it seems in this case, I am sorry to say I can't do much from my side. I don't know if will help, but did you try to check something like this out? https://support.apple.com/kb/PH25085?viewlocale=en_US&locale=ro_RO
