### ISSUE TITLE
In Case of Multiple Sheets While creating Row and Column in each Sheet is not working 

### ISSUE THREAD

**Issue by ashraftalib** [jspreadsheet/ce#30]
Hi @paulhodel ,

While I am working on Multiple sheets in a page it is not working: If you create Rows and Columns in each sheets after creating, again creating Rows and Columns then it is thronging an error: Cannot read property 'split' of undefined
You can also check on your Demo [page ](http://bossanova.uk/jexcel/multiple-spreadsheets-in-the-same-page) also and check browser console after repeating in every sheet. Meanwhile I also got data in both tables or sheets  by using '**getData**' , some arrays are coming array of null like[null,null,null] not as blank array of ["","",""] .In Case of single sheet it is working fine. 

I am also attaching a screenshot for this

![error_multiple_sheet](https://user-images.githubusercontent.com/31342456/30100738-637d6d2e-9307-11e7-91b7-7b9239f052a8.PNG)

Please help me Thank you

**Comment by pphod** [comment]
There was a problem in the website that was fixed. Thanks for spotting that out.
http://www.bossanova.uk/jexcel/multiple-spreadsheets-in-the-same-page

The problem: we can't use the same data source to different tables, each table must have their own data source. There was a typo in the website and it is working now.
