### ISSUE TITLE
Excel Formula  and Cell ColumnSpan or RowSpan

### ISSUE THREAD

**Issue by NickCong** [jspreadsheet/ce#300]
Thanks for your great job. The  plugin is very awesome. I am using this spread sheet to develop our APP. In our case the Excel Formula "SUMPRODUCT" is a very popular formula, Can you support the formula in next version? Maybe support more formula. Another request about the column span or rowspan, I am using the css class to control the span. Can you support the feature in next version.

I also use insert row/column menucontext, but I have found the formula auto updated has some mistake. This operate only updates the row/column below. I have override the updateTableReferences in my development.

**Comment by pphod** [comment]
jExcel is built in a way you can develop and share your own implementations for formulas. Take a look on this example
https://bossanova.uk/jexcel/examples/including-formulas-on-your-spreadsheet

`
<html>
<script src="http://cdn.bossanova.uk/js/excel-formula.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jexcel/2.0.0/js/jquery.jexcel.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jexcel/2.0.0/css/jquery.jexcel.min.css" type="text/css" />

<div id="my2"></div>

<script>
var data2 = [
    ['Furnace','=CUSTOM(A1)', 10],
    ['Tower','=CONSOLE(A2)', 9],
    ['Drum','=CONCAT_COLUMNS(A1,A3)', 3],
    ['Pump','=CONSOLE(A4)', 7],
    ['Total','', '=AVG(C1:C4)'],
]

$('#my2').jexcel({
    data:data1,
    colWidths: [ 400, 200 ],
});

function CUSTOM(cell) {
    return 'alert: ' + cell;
}

function CONSOLE(cell) {
    console.log(cell);
    return cell;
}

function CONCAT_COLUMNS(a, b) {
    return a + ', ' + b;
}

function AVG(v)
{
    var sum = v.reduce(function(a, b) { return a + b; });
    var avg = sum / v.length;

    return avg;
}

</script>
</html>`
