### ISSUE TITLE
Autofill number

### ISSUE THREAD

**Issue by lep1986** [jspreadsheet/ce#301]
hell guys, how i can autofill like in picture?
![autofill-product-names](https://user-images.githubusercontent.com/40227247/53288052-dab5f480-37a5-11e9-8354-766d24f36eaa.png)
now autofill work like this:
![111](https://user-images.githubusercontent.com/40227247/53288080-40a27c00-37a6-11e9-8aeb-88c26c8f9ae2.PNG)

**Comment by pphod** [comment]
This is not implemented, and I am afraid this will take same time to be incorporated in the official release.
