### ISSUE TITLE
returning hidden input html markup while editing number cell

### ISSUE THREAD

**Issue by ak868308** [jspreadsheet/ce#304]
Whenever I am going to edited pre-populated number type cell it shows me `<input type="hidden" value="0">` and if I return without any change it set 0 to the cell instead of keeping old value.

Please update 
See the following two images before and after edit

![1](https://user-images.githubusercontent.com/7982249/53551670-cdab5380-3b5f-11e9-9d41-30a0dd71fea2.png)

![2](https://user-images.githubusercontent.com/7982249/53551703-e156ba00-3b5f-11e9-8542-846a731962b7.png)

**Comment by pphod** [comment]
I could not replicate the same error in my side. Could you please provide an full example on jsfiddle for example? Are you using the most recent version of jExcel?

**Comment by wiknez** [comment]
Here also same problem. Can it be solved with css or jquery ?

**Comment by ak868308** [comment]
> I could not replicate the same error in my side. Could you please provide an full example on jsfiddle for example? Are you using the most recent version of jExcel?

Yes I am using the latest version. Sure I will try to provide an full example on jsfiddle.
Also found one more issue with `setHeader` method

Suppose if your header exist html markup like `Length <br/><small>(in inch)</small>` and if you triggered the method `setHeader` with new html markup it never changed the header due to following line.` colHtml.replace($(col).text(), title);` on line no 3672 and also the value for `title` attribute also remains the old.

I modified the following lines now it works fine for me.

```
setHeader : function (column, title) {
        var col = $(this).find('thead #col-' + column);
        if (col.length) {
            if (! title) {
                title = prompt('Column name', $(col).text())
            }
            //var colHtml = $(col).html();
            //colHtml = colHtml.replace($(col).text(), title);
            $(col).html(title);
            $(col).attr('title',title);
        }
    },
```

Thanks

**Comment by pphod** [comment]
If you double click in your header, and try to change the title you will have problems. So, this code won't work for all cases.

**Comment by ak868308** [comment]
> I could not replicate the same error in my side. Could you please provide an full example on jsfiddle for example? Are you using the most recent version of jExcel?

https://jsfiddle.net/ak868308/m5npfkse/7/

**Comment by pphod** [comment]
Please, download the most recent version. v2.0.2 the version in your jsFiddle is v1.5.0

You can download from the master repository.

**Comment by ak868308** [comment]
Sorry but I already have v2.0.2, I am not updated in jsFiddle
I found the issue

See these lines here is the issue: line no 1621 & 1622 in jquery.jexcel.js
 ```
$.fn.jexcel.edition = $(cell).html();
 $.fn.jexcel.editionValue = $(this).jexcel('getValue', $(cell));
```

If you edit the cell with double click it returns the hidden input html markup to cell instead of 0 or null because of `$(cell).html();`

![screenshot from 2019-03-01 22-21-24](https://user-images.githubusercontent.com/7982249/53653221-d9d30600-3c70-11e9-8b8d-9b42e8300ebf.png)

Thanks

**Comment by pphod** [comment]
Those variables are used when the user give up any changes of during the edition, press ESC.. for example. This variables will return the previous state of the cell.
