### ISSUE TITLE
Unable to set the values for dropdown type column using 'setData'

### ISSUE THREAD

**Issue by ak868308** [jspreadsheet/ce#305]
Hello,
Runtime set/unset configuration works too good, but in some cases it fails with its behaviour. lets see the example of `setData` below:
`setData` method works like a charm for all default column types `text` & `number`. but, if we sets the column type other than this (suppose we sets` type: 'dropdown'`), `setData` not works for such specific column. While it sets the values for the rest of column perfect.

**Replicate this issue:**
1) Create empty jexcel without data property. (Means empty excel)
2) Add column type `dropdown` to any one of the specified columns with `autocomplete:true `and `url:'/js/options.json'` options
3) Add `text` and `number` type columns too.
4) Create a button and add listener to load the data from `json` file or `json string.` to table

After click on button try to append or set the `json data ` to jexcel using `setData` method. 
You will see all the columns having type `text` or `number` should gets filled successfully with the values but, the value for column having type `dropdown` with `url:'/js/options.json'` and `autocomplete: true` options is not gets filled from the provided `json`. while if I change the type of the same column as text it works fine.

Thanks

**Comment by debamishra14** [comment]
@ak868308 hey did you find a way to select a default value of dropdown?
