### ISSUE TITLE
numeric formula displayed instead of result

### ISSUE THREAD

**Issue by bennyzr** [jspreadsheet/ce#306]
Cells are displaying =25+25 and =50+50. Yet when I type in the same formula it displays properly.

The following is my initialization code:
data = [  ['=25+25', '=50+50'] ];
$('#my_jexcel').jexcel({
    		data: data,
		onchange: updateValues,
    		colHeaders: [],
		columns: [
        	{ type:'numeric' },
        	{ type:'numeric' }
    		],
    		colWidths: [100, 100],
		allowInsertRow: false,
		toolbar: false
});

**Comment by pphod** [comment]
I cannot replicate this problem. Please, bear in mind to load all necessary scripts. 
Example:
https://bossanova.uk/jexcel/examples/including-formulas-on-your-spreadsheet

**Comment by bennyzr** [comment]
Adding a call to $(this).jexcel('updateCells', records, true); before the $(this).jexcel('updateAllCellsWithFormulas'); does solve my issue.
