### ISSUE TITLE
updateSetting getting wrong value instead of current value.

### ISSUE THREAD

**Issue by sujathavts** [jspreadsheet/ce#307]
![jexcel](https://user-images.githubusercontent.com/29447554/53697055-1dee1400-3df3-11e9-9bb6-827e32a4a372.png)

On UpdateSettings function, value is fetching old value, but i have update the value using (td).html method.

**Comment by pphod** [comment]
The .html does not change the value of the cell. You must performed that.

$(instance).setValue(id, newValue);
