### ISSUE TITLE
Sorting column issue with custom formula

### ISSUE THREAD

**Issue by frankcrissalem** [jspreadsheet/ce#308]
The sorting function when you double click the table header or column name doesn't work well if the row values are created with custom formula. The values are not sorted accordingly and found out that the formula name was the one that was sorted.

Example: custom formula name: getHost(cell). The formula values would become like this:
=getHost(B1)
=getHost(B10)
=getHost(B11)
... 
=getHost(B19)
=getHost(B2)
=getHost(B20)
=getHost(B21)

I already look into the documentation and tried to make it work with custom type but no luck. 
Is it possible to sort the values return by the custom formula and not the formula name itself?

Thanks! :)

**Comment by pphod** [comment]
This feature is available in the Pro version only.
