### ISSUE TITLE
Issue while Rendering HTML tags in cell

### ISSUE THREAD

**Issue by vishalpatil14287** [jspreadsheet/ce#313]
Hi,

I have data something like "&lt;abcd&gt;Default Test&lt;/abcd&gt;" in one of my column/cell.
But when I try to render this data, it treats this as HTML tag and makes that column/cell disabled.

Can you please suggest me the solution for this issue?

Thanks in Advance,
VP

**Comment by vishalpatil14287** [comment]
Any solution for this?

**Comment by pphod** [comment]
This has been fixed, it will be available soon in the master repository.

**Comment by vishalpatil14287** [comment]
Cool! Thank you Paul!
Will check & confirm soon!

Cheers

**Comment by helenchristina** [comment]
Please post the solution for reference. Thanks in advance
