### ISSUE TITLE
Small Settings Changes

### ISSUE THREAD

**Issue by Luismvm** [jspreadsheet/ce#314]
For a new development i'm doing i needed to add a couple of new features, so i added the following settings to my local version:

1. allowHorizontalCorners: true --> enables / disables dragging horizontally (locks dragging to that column only)
2. allowRenameColumn: true 
3. allowExport: true

Can you add these to the plugin in whatever way you prefer, i'll just update my local version when you do =) 

Many Thanks

**Comment by pphod** [comment]
2,3 are included in v3.
