### ISSUE TITLE
Clicking checkbox doesn't trigger change event

### ISSUE THREAD

**Issue by Luismvm** [jspreadsheet/ce#315]
Pretty self explanatory, i added this piece of code as workaround locally

`    $(td).html('<input type="checkbox">');
                    $(td).find("input").bind('change', function () {
                        $('#' + $.fn.jexcel.current).jexcel('setValue', $(this.parentNode), this.checked);
                    });`

**Comment by randy-johnson** [comment]
@Luismvm can you elaborate a bit on where to put this?  I am noticing that the checkbox works every few clicks.  Not sure why.. I am hoping this fix solves it.

**Comment by randy-johnson** [comment]
I am going through the source code and I found that using the space bar to toggle the checkbox makes the   update event fire each time.

I also found where to add the bit of code, stubled upon it when researching:

https://github.com/paulhodel/jexcel/blob/master/dist/js/jquery.jexcel.js#L4302

**Comment by pphod** [comment]
On v3 I am pretty sure this is better implemented.
