### ISSUE TITLE
Checkbox value is not updating into the data model

### ISSUE THREAD

**Issue by Ilayaraja-n** [jspreadsheet/ce#317]
Hi,
Checking or unchecking the check box, it is not updating the value into the data model. 
Note: Observed in jquery.jexcel.js file the line number 744, if condition(i.e. if ($(e.target).parent().parent().parent().parent().hasClass('jexcel-content'))) is failing.
![Checkbox Issue](https://user-images.githubusercontent.com/46338652/55077314-6f6d8400-50bd-11e9-9944-d163884837de.png)

**Comment by pphod** [comment]
This has been fixed, will be available soon in the master repository.
