### ISSUE TITLE
Nested header selection is not working properly with hidden columns

### ISSUE THREAD

**Issue by Ilayaraja-n** [jspreadsheet/ce#318]
Hi,
If i use hidden column(i.e. In my scenario first column is hidden) in the jExcel, then the nested header selection is not proper.
On click on the Nested header, it does not select all the columns belong to the nested header.
Please find attached screenshot.

![Uploading Nested Header selection.png…]()

**Comment by Ilayaraja-n** [comment]
![Nested Header selection](https://user-images.githubusercontent.com/46338652/55079914-24566f80-50c3-11e9-913f-0413b577cda3.png)

**Comment by pphod** [comment]
Would you mind to upload an example in jsFiddle, please? I tried a few examples in my side and can't replicate this error.

**Comment by Ilayaraja-n** [comment]
Thank you Paul. Keeping the hidden columns at the end, nested header selection is working fine so closing this issue.

**Comment by lotsofish** [comment]
Moving the hidden columns is a work around, however it's still an issue. An example can be found here: https://jsfiddle.net/zLupabh3/3/

To see the issue, click on the "Group 1" or "Group 2" header. The selected columns are not the columns directly under the nested header.

**Comment by pphod** [comment]
This has been fixed in 3.5.2+ (available in the master at this moment)
