### ISSUE TITLE
method getData fails with version 2.03

### ISSUE THREAD

**Issue by beruken** [jspreadsheet/ce#319]
I recently downloaded and changed my project references from version 1.5.3 to 2.03 and all of a sudden getData returns an empty array. After debugging I found line below in getData results in undefined and there appears to be no .length property to data[0] despite 9 items in the array. I reverted back to the previous version and it work fine again. 

`
var x = $.fn.jexcel.defaults[id].data[0].length

// and my setup
$('#sheet1').jexcel({
	    data: jdata,
	    columns: [ { type: 'text'}, { type: 'number'},{ type: 'number' }, { type: 'number'},{ type: 'number'}, { type: 'number'},{ type: 'number'},{ type: 'number'},{ type: 'number'} ],
	  	colWidths: [300, 120,120,120,120,120,120,120,120],
	    colHeaders: [
			    '<strong>A</strong><br /><br />Resource Types',
			    '<strong>B</strong><br /><br />Carry Over',
			    '<strong>C</strong><br />Current Approved <br />FY '+fy+' Funds <br />(Not For FY'+(fy+1)+' Ramp Up)',
			    '<strong>D</strong><br />New (Delta) FY '+fy+' <br />Funds Request',
			    '<strong>E</strong><br />Spend Plan <br />FY '+fy+' ',
			    '<strong>F</strong><br />New Funds to be<br /> requested for <br />FY '+ (fy+1),
			    '<strong>G</strong><br />Spend Plan <br />FY '+(fy+1),
			    '<strong>H</strong><br />New Funds to be<br /> requested for <br />FY '+(fy+2),
			    '<strong>I</strong><br />New Funds to be<br /> requested for <br />FY '+(fy+2)
			     	  ]		
});

`

**Comment by beruken** [comment]
So I updated the line 'var x = $.fn.jexcel.defaults[id].data[0].length' in getData() to 
`var x = $.fn.jexcel.defaults[id].columns.length` and it seemed to work well as it appears that was the goal of the assignment.

**Comment by pphod** [comment]
Yes, I am going to follow your suggestion and deploy that later. This is supposed to get the some result, since the data[0] should has the some length of columns.
