### ISSUE TITLE
OnChange Event is not fired while copying one column(cell) data to other column(cell) data by using drag(Right Bottom '+' icon in cell) 

### ISSUE THREAD

**Issue by ashraftalib** [jspreadsheet/ce#32]
HI,
"OnChnage" Event is only firing when I am writing into cell or Copying(Ctrl+C to Ctrl+v etc) to other cell. But in case of drag copying from one cell to other cell it is not working even in this case also data is changing to other cell initially it is not there but after dragging same data comes from one cell to other. I think Onchange should also fire in this case.
In Case of adding new column it should work but it is not working while in case of adding new row OnChange is working fine. Please refer this below gif 

1- Add Row(working) 2- Drag copy(not working) 2- Insert Column(not working).

![dragcopy_inseercolumn_onchnage_issue](https://user-images.githubusercontent.com/31342456/30116388-052d6a06-933b-11e7-96fb-57cffbc7fab5.gif)

Please help thank you so much.

**Comment by pphod** [comment]
Please update from Branch 1.3.0, the example can be visualized here.
http://jsfiddle.net/paulhodel/o9fkky2x/

**Comment by pphod** [comment]
A new version including new events.
http://jsfiddle.net/paulhodel/0dyms2b9/

**Comment by wlaryeanii** [comment]
Hi Paul, please I have created a table with JSON data loaded from my database. I have tried all the event functions sited in your examples here : http://jsfiddle.net/paulhodel/0dyms2b9/ but the **beforechange** event doesn't get triggered. I wanted to know if there any possible causes why it may not get triggered?
