### ISSUE TITLE
Copy and Paste is not working properly while copying date from single column and pasting

### ISSUE THREAD

**Issue by Ilayaraja-n** [jspreadsheet/ce#320]
Hi,
Copy and Paste is not working properly with empty cell values. Copy data from single column and make sure few cell values are empty. While pasting the data empty cells are ignored. 

![Copy Paste Issue](https://user-images.githubusercontent.com/46338652/55132622-02073500-5149-11e9-82bb-ebfd74c36fab.png)

**Comment by pphod** [comment]
Thanks for spotting that out. It has been fixed and will be available in the master repo this evening.
