### ISSUE TITLE
Cell navigation is not working properly, if hidden column is available

### ISSUE THREAD

**Issue by Ilayaraja-n** [jspreadsheet/ce#321]
Hi,
While navigating to cell using arrow keys, cell selection is getting set for the hidden columns also. Kindly set cell selection only for the visible columns.

**Comment by SFoster84** [comment]
How would you approach this, something like detect on entry when you're in a hidden cell and repeat the last keyboard action (such as arrow-right)?

**Comment by Ilayaraja-n** [comment]
Thank you so much for your response. As you said while navigation we need to identify the previous/next visible elements. We can use the jQuery methods to get the previous/next visible elements. I have modified few changes in the “keyDownControls” method to make it work. Please check attached screen shot. We need to do similar changes for Home and End key also.
![Keyboard_Navigation](https://user-images.githubusercontent.com/46338652/55537926-dd780380-56da-11e9-9df0-3a6ef86a2d98.png)

**Comment by Ilayaraja-n** [comment]
Thank you so much for your response. As you said while navigation we need to identify previous/next visible elements. We can use the jQuery methods to get the previous/next visible elements. I have modified few changes in the “keyDownControls” method to make it work. Please check attached screen shot. We need to do similar changes for Home and End key also.
![Keyboard_Navigation](https://user-images.githubusercontent.com/46338652/55541057-d3a5ce80-56e1-11e9-879e-eea8168b7862.png)

**Comment by SFoster84** [comment]
Thanks for adjusting the code, could you start a branch with those changes or provide a text version as an attachment?  (I'd like to try it out)

**Comment by pphod** [comment]
Could you kindly send a pull request, I am happy to merge it to the master.

**Comment by Ilayaraja-n** [comment]
Thank you. I have attached the modified jquery.jexcel.js file. The changes are done in the keyDownControls method.

[jquery.jexcel.zip](https://github.com/paulhodel/jexcel/files/3052829/jquery.jexcel.zip)
