### ISSUE TITLE
TAB adds column although allowInsertCol:false

### ISSUE THREAD

**Issue by wsat** [jspreadsheet/ce#322]
Hi,
I have set all these:
allowInsertRow: 'false',
allowDeleteRow: 'false',
allowInsertCol: 'false',
allowDeleteCol: 'false',
allowManualInsertRow: 'false',
allowManualDeleteRow: 'false',
allowManualInsertCol: 'false',
allowManualDeleteCol: 'false',
editable: 'false'
yet, if a cell in the last col is selected and TAB is pressed, a column is added. Can this be prevented?
Many thanks

**Comment by pphod** [comment]
The correct way:
allowManualInsertColumn
allowManualDeleteColumn
etc.

**Comment by wsat** [comment]
Thank you, this solved the problem!
