### ISSUE TITLE
hide/show column

### ISSUE THREAD

**Issue by avidsouza** [jspreadsheet/ce#323]
I need to hide and show the column dynamically based on the header values. What is the best way to approach.

**Comment by avidsouza** [comment]
I need to hide and show the column dynamically based on the header values. What is the best way to approach.

**Comment by pphod** [comment]
You can use $('.c1').hide(); for example, but you must be careful to hide the headers as well. jExcel is very close to a pure HTML table, so you can apply css. But, this depends on what you really want to do.
