### ISSUE TITLE
More instances of jexcel table

### ISSUE THREAD

**Issue by kaddhuzzu93** [jspreadsheet/ce#324]
Hi, 
there are some problems with more instances of jexcel table in a single page.
I can't separate the formulas among tables, this is my issue:

// This instruction allows the plugin to store variables of cells in order to be used in formulas
 window[i] = new $.fn.jexcel.factory(i, $.fn.jexcel.defaults[id].values[i]);

With more tables this variables are overwritten by each other, so just the last table values are considered in the forulas of all tables!

Can you provide a solution?
Thank you

**Comment by pphod** [comment]
Which version are you using? Please make sure you are running the most recent version.

**Comment by pphod** [comment]
jExcel will treat that to get the correct value. I believe you are facing other problem... unless you are using a very old version.
