### ISSUE TITLE
pasting with thousand seperator

### ISSUE THREAD

**Issue by wsat** [jspreadsheet/ce#325]
I have a sum formula in the last cell of a column, which is adding up the numbers above. When I paste or enter numbers into the cells above the formula without thousand separators, the sum is correct. If I paste or enter numbers with thousand separator the formula is not calculated correctly but shown as concatenated string.

**Comment by pphod** [comment]
Javascript must consider your input as Number, if for any reason consider a string the result would be concatenation. Sorry, I am not sure we can do something about that, one possible is MASKING the input to remove any character.

http://localhost:8002/jexcel/examples/currency-and-masking-numbers
