### ISSUE TITLE
Single Dropdowns

### ISSUE THREAD

**Issue by kaddhuzzu93** [jspreadsheet/ce#326]
Hi Paul,
I want to define a dropdown in a cell without specify the entire column type as a dropdown...
The rows of my column can contain decimals, texts, dropdowns, calendars etc...
How can I proceed?

Thank you

**Comment by pphod** [comment]
you need to create a customEditor.
https://bossanova.uk/jexcel/examples/integrating-a-third-party-plugin-into-your-spreadsheet
