### ISSUE TITLE
Csv separator

### ISSUE THREAD

**Issue by BDominik** [jspreadsheet/ce#329]
How to change csv column separator?
In my csv files the column separator is ;
So the plugin showing every column in one cell.

**Comment by pphod** [comment]
Use the delimiter property as below.

$('#my').jexcel({
    csv:'https://bossanova.uk/components/bossanova-ui/demo/demo1.csv',
    csvHeaders:true,
    delimiter:';',
    colWidths: [70, 200, 300],
});

**Comment by medamineb** [comment]
Hello, 
delimiter property doesn't work 
[https://i.imgur.com/U97M9ob.png](url)

**Comment by OlivierMartineau** [comment]
I confirm that 'csvDelimiter' property doesn't work here neither in v. 4.10.7

Note : the auto-detection of csv separator has been addressed here:
https://stackoverflow.com/a/49273276/1563072
You might want to check this :)

**Comment by franciscofinc** [comment]
In version v4.10.1 the property is working correctly, but the correct string is "csvDelimiter" and not "delimiter" as suggested by @pphod 

> Use the delimiter property as below.
> 
> $('#my').jexcel({ csv:'https://bossanova.uk/components/bossanova-ui/demo/demo1.csv', csvHeaders:true, delimiter:';', colWidths: [70, 200, 300], });
