### ISSUE TITLE
Undo Redo on setData

### ISSUE THREAD

**Issue by felixvandal** [jspreadsheet/ce#33]
I was wondering if you were planning on supporting the setData function with the undo and redo
i know its a lot of work to support version of the table
so i was wondering if using the updateCell we previously talk about could be a viable option instead of doing a setData everytime i update the data in a row

**Comment by pphod** [comment]
setData clear history and reset the table. If you wish to update your table and keep history I suggest you use setValue or updateCells (Using the latter you can update multiple cells).

**Comment by felixvandal** [comment]
close to what i had in mind
thank you again!
