### ISSUE TITLE
Download doesn't include updated headers

### ISSUE THREAD

**Issue by liamshanny** [jspreadsheet/ce#331]
When generating a download, when the header option is true only the original header setting is included in the export.
Would it be possible to have the download function grab the latest headers and include that in the export?

I can imagine doing it by looping through the getHeader values until an 'undefined' header is returned, but perhaps there is a better way?

https://github.com/paulhodel/jexcel/blob/625591573352c82177facc31079284b11481c7fc/dist/js/jquery.jexcel.js#L4048

**Comment by pphod** [comment]
It has been fixed, it will available in the master repo this evening.
