### ISSUE TITLE
how to add fixed column with new header/body seperation format

### ISSUE THREAD

**Issue by amfazlani** [jspreadsheet/ce#339]
Thank you for this plugin. When i was using version 1.5.7 I was able to achieve fixed columns using https://www.jqueryscript.net/table/jQuery-Plugin-For-Fixed-Table-Header-Footer-Columns-TableHeadFixer.html but with 2.0.0 and up - I believe there is a new format with header and content separated and I am not able to get fixed column working. I need to use 2.0.0 and up because of new dropdown additions. Any suggestions?  Thank you.

**Comment by fernandarodriguesh** [comment]
Did you try tableOverflow property?

**Comment by pphod** [comment]
You can try the tableOverflow with tableHeight, or you can try the CSS position:stick option.
