### ISSUE TITLE
Bind events to document only for the first grid added 

### ISSUE THREAD

**Issue by zemagnifique** [jspreadsheet/ce#340]
This avoids to bind the same event to document multiple times.
This can be done by adding this line before binding events.
`if (Object.keys($.fn.jexcel.defaults).length == 1)`

or if you don't want to put the code in the big if you can do this when binding the events:
`$(document).off('keydown').on('keydown', function(e) {
    // put your logic in here 
  });`

This fixes a bug you can reproduce by adding and destroying grids in the same view. and keeps the same logic used when unbinding the events

**Comment by pphod** [comment]
All bind happens only if the CORNER element does not exists, so should be executed only once.
Line: 515
if (! $('.jexcel_corner').length) {
}
