### ISSUE TITLE
Authorization Headers

### ISSUE THREAD

**Issue by phuze** [jspreadsheet/ce#341]
I am loading data from an external JSON source, as described [here](https://bossanova.uk/jexcel/examples/creating-a-table-from-an-external-csv-file), using the `url` parameter.

Example:

```js
$('#excelTest').jexcel({
    url: 'https://example.com/jexcel/test',
    ...
});
```

However, I secure my API endpoints using JWT tokens, and as such, all requests require an appropriate `Authorization` header.

Is it possible to define the headers in the jExcel reqest?

**Comment by pphod** [comment]
Try to do that:

```
$.ajax(url, your param, function(data) {
   $('id').jexcel({
     data:data,
     // other initial params.
   })
});
```
