### ISSUE TITLE
Update dropdown source

### ISSUE THREAD

**Issue by gfbagel** [jspreadsheet/ce#342]
Is there a way to update the source of a dropdown? 
```
{ type: 'dropdown', source: [1,2,3]}
```
Since a value not in the source (4) was recently added to the data, the dropdown cell for it would be blank.
```
data = [
    ['Mazda','2006-01-01', 1],
    ['Pegeout','2005-01-01', 2],
    ['Honda Fit','2004-01-01', 3],
    ['Honda CRV','2003-01-01', 4],
];
```
I have a basic jsfiddle to demonstrate for clarity
http://jsfiddle.net/h4sL1dw3/1/

**Comment by pphod** [comment]
$.fn.jexcel.defaults[id].columns.source = [1,2,3,4];

where the id is the id of your table.

**Comment by gfbagel** [comment]
Hmm that does seem to change the columns.source value, but the changes aren't reflected on the dropdowns in the table...
Anything else I'm missing after that?

https://jsfiddle.net/y4L7fg65/2/

**Comment by gfbagel** [comment]
Nevermind, found out I had to add the column # after poking around the source
`$.fn.jexcel.defaults[id].columns[x].source = [1,2,3,4];` where x is an int
