### ISSUE TITLE
How to make alias for functions SUM() -> SUMA()

### ISSUE THREAD

**Issue by shakaran** [jspreadsheet/ce#344]
I am trying to add an alias for the function SUM() since when I export to CSV and I open the CSV with LibreOffice, I have the UX in Spanish, and the SUM() is not being interpreted, but like SUMA it should, but doing that, it doesn't work for the excel rendering:

I write this:

```
function SUMA(v)
    {
        return SUM(v);
    }
```

Old code:
`$('#my_table').jexcel('setValue', 'B2', '=SUM(B3:B11)'); // Work`

New code:
`$('#my_table').jexcel('setValue', 'B2', '=SUMA(B3:B11)'); // Don't work, "Error" in the cell showed`

**Comment by pphod** [comment]
The problem is the SUM(B3:B11) is parsed to SUM(B3,B4,B5...) automatically by an internal method. When you do SUMA(B3:B11) you need to parse yourself. Or you can implement SUMA...

    exports.SUM = function() {
        var result = 0;
        var argsKeys = Object.keys(arguments);
        for (var i = 0; i < argsKeys.length; ++i) {
            var elt = arguments[argsKeys[i]];
            if (typeof elt === 'number') {
                result += elt;
            } else if (typeof elt === 'string') {
                var parsed = parseFloat(elt);
                !isNaN(parsed) && (result += parsed);
            } else if (Array.isArray(elt)) {
                result += exports.SUM.apply(null, elt);
            }
        }
        return result;
    };
