### ISSUE TITLE
Feature Request: Download CSV with formulas executed

### ISSUE THREAD

**Issue by shakaran** [jspreadsheet/ce#346]
I am having problems with the CSV which are downloaded with the formulas.

I would like an option to download the CSV with all the cel rendered and executed as values.

For the moment I am forcing with: 

```
	try {
            var value = eval(excelFormulaUtilities.formula2JavaScript(cell));
        } catch (e) {
            var value = 0;
        }
```

But probably a parameter in CSV download will be better. Since I cannot find a getContents() for each cell or so.

**Comment by pphod** [comment]
In v3 you have an option that affects the copy and export to CSV. It will parse the formulas and get labels instead of ids, and formatted dates...

copyCompatibility:true,
