### ISSUE TITLE
Uundo and redo

### ISSUE THREAD

**Issue by cevc96** [jspreadsheet/ce#35]
In undo an redo onchange event not working; Is possible to get all changes of table in one array?

**Comment by pphod** [comment]
This feature is available in the new version 1.3.0 available in a different
repository. (beta testing)

**Comment by cevc96** [comment]
I saw that you update the repository, can i see this feature?, that really help me so much.
Thanks

**Comment by pphod** [comment]
bossanova.uk/jexcel
