### ISSUE TITLE
Correct orderBy docs

### ISSUE THREAD

**Issue by aml2610** [jspreadsheet/ce#351]
Looking at the docs for orderBy:

```
orderBy: will reorder a column asc or desc
@Param integer columnNumber - column number starting on zero
@Param smallint sortType - Zero will toggle current option, one for desc, two for asc |
$('#my').jexcel('orderBy', 2);
```

but when I use it that does not work as expected. And looking at the code for version 2.0.2 I see:
```
            // No order specified then toggle order
            if (! (order == '0' || order == '1')) {
                var d = $(c).find('.arrow-down');
                if ($(d).length > 0) {
                    order = 1;
                } else {
                    order = 0;
                }
            }
```
and 
```
                    if (! o) {
                        return (valueA > valueB) ? 1 : (valueA < valueB) ? -1 : 0;
                    } else {
                        return (valueA > valueB) ? -1 : (valueA < valueB) ? 1 : 0;
                    }
```

So this tells me it actually works like this (and the docs should reflect that):
`@Param smallint sortType - One will order DESC, zero will order ASC, anything else will toggle the current order`
I tested and that is how the functionality actually is.

This is a very small change to do (I'm not sure you're using anything to generate docs so I wasn't able to find the source for the docs, otherwise I would've opened a PR with it directly) and will help people.

**Comment by pphod** [comment]
Updated! Thank you for that.
