### ISSUE TITLE
TypeError: $.fn.jexcel is undefined

### ISSUE THREAD

**Issue by shrutiakki** [jspreadsheet/ce#353]
I have just copied and pasted code in my script it is giving error like TypeError: $.fn.jexcel is undefined

<script src="cssjs/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jexcel/2.0.0/js/jquery.jexcel.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jexcel/2.0.0/js/jquery.jdropdown.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jexcel/2.0.0/js/jquery.jcalendar.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jexcel/2.0.0/css/jquery.jexcel.min.css" type="text/css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jexcel/2.0.0/css/jquery.jdropdown.min.css" type="text/css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jexcel/2.0.0/css/jquery.jcalendar.min.css" type="text/css" />
<script type="text/javascript">
  
data1 = [
    ['US', 'Cheese', '2019-02-12'],
    ['CA', 'Apples', '2019-03-01'],
    ['CA', 'Carrots', '2018-11-10'],
    ['BR', 'Oranges', '2019-01-12'],
];

$('#my1').jexcel({
    data:data1,
    colHeaders: [ 'Product Origin','Description','Best before' ],
    colWidths: [ 300, 200, 100 ],
    columns: [
        { type: 'text' },
        { type: 'text' },
        { type: 'calendar' },
    ],
    allowComments:true,
});
$('#my1').jexcel('setComments', 'A1', 'This is the comments from A1');  
$('#my1').jexcel('setComments', 'A1', '');  
$('#my1').jexcel('getComments', 'A1');
</script>
<script type="text/javascript">
$(document).ready(function($) {
  $('.sidebar-mini').addClass('sidebar-collapse');
  $('#showhide').hide();
  $('#example2').css('padding-top',0);
  $('.jexcel-header').find('table').css('width','100%');
  $('.jexcel-content').find('table').css('width','100%');
$('#my1').jexcel('setComments', 'A1', 'This is the comments from A1');  
$('#my1').jexcel('getComments', 'A1');  

});

**Comment by x0nium** [comment]
I thought I was having a brain fart because I couldn't get below code to work. Now I see it's not only me.

Uncaught TypeError: $(...).jexcel is not a function
    at jexcel.html:24

```
<html>
<head>
<title>jExcel demo</title>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jexcel/2.0.4/js/jquery.jexcel.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jexcel/2.0.4/css/jquery.jexcel.css" >
</head>
<body>
    <div id='my-spreadsheet'></div>
    <script type="text/javascript">
    data = [
        ['Mazda', 2001, 2000],
        ['Pegeout', 2010, 5000],
        ['Honda Fit', 2009, 3000],
        ['Honda CRV', 2010, 6000],
    ];

    $('#my-spreadsheet').jexcel({
        data:data,
        colHeaders: ['Model', 'Price', 'Price' ],
        colWidths: [ 300, 80, 100 ]
    });
    </script>
</body>
</html>

```

**Comment by pphod** [comment]
It seems 2.0.4 is not live, please use:


<html>
<head>
<title>jExcel demo</title>
<script type="text/javascript"
src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script type="text/javascript"
src="https://cdnjs.cloudflare.com/ajax/libs/jexcel/2.0.2/js/jquery.jexcel.js
<https://cdnjs.cloudflare.com/ajax/libs/jexcel/2.0.4/js/jquery.jexcel.js>"></script>
<link rel="stylesheet" type="text/css"
href="https://cdnjs.cloudflare.com/ajax/libs/jexcel/2.0.2/css/jquery.jexcel.css
<https://cdnjs.cloudflare.com/ajax/libs/jexcel/2.0.4/css/jquery.jexcel.css>"
>
</head>
<body>
    <div id='my-spreadsheet'></div>
    <script type="text/javascript">
    data = [
        ['Mazda', 2001, 2000],
        ['Pegeout', 2010, 5000],
        ['Honda Fit', 2009, 3000],
        ['Honda CRV', 2010, 6000],
    ];

    $('#my-spreadsheet').jexcel({
        data:data,
        colHeaders: ['Model', 'Price', 'Price' ],
        colWidths: [ 300, 80, 100 ]
    });
    </script>
</body>
</html>

**Comment by x0nium** [comment]
I noticed this just after I wrote the message, and then deleted it. Thanks for the answer however.
Probably the same problem was for 2.0.0 when shrutiakki wrote this entry.
Hopefully it helps others :)
Thanks for the awesome jexcel!

**Comment by pphod** [comment]
Two new versions will be release tomorrow 2.1.0 CE Edition (Free) - MIT, and the 3.0.1 Pro Edition (Commercial) - The 3 will be a vanilla javascript and will be release under www.jexcel.net/v3
