### ISSUE TITLE
Nested Headers class problem

### ISSUE THREAD

**Issue by tomturner** [jspreadsheet/ce#357]
I am using version 2.0.2

Hi I am using nested headers which work great apart from the class that they get given.

`<td class="h1 h2 h3 h4 h5" colspan="5" align="center">Monday</td>`

As you can see they get given h1 h2 etc which results in 

![image](https://user-images.githubusercontent.com/1792640/58164164-3268dc80-7c7d-11e9-9198-b77505dfd3d7.png)

Why do they need to be given a class at all or am I doing something wrong?

If I remove the following  it will look correct.

`// Header classes for this cell
                    for (var x = 0; x < nestedInformation[i].colspan; x++) {
                        if (headerClasses) {
                            headerClasses += ' ';
                        }
                        headerClasses += 'h' + headerIndex;
                        headerIndex++;
                    }`

**Comment by pphod** [comment]
This class is important so you can click in the nested header and select the correct columns. You should have some kind of className conflicts to some other library.
