### ISSUE TITLE
How to "unselect" or blur() the whole table?

### ISSUE THREAD

**Issue by x0nium** [jspreadsheet/ce#358]
Do you have any function to unselect the whole table so that keyboard input doesn't get written to a field?

It seems to be very hard to do this with code.

When I write to a field and hit ENTER. I do not want it to select the colum below to receive keyboard input next.

I've tried to update/remove any selection completely and put focus on another element. See code below.
Visibly the column loses it's selection, and the #dummyfocus input gets focused, but as soon as there are any keyboard input, it still goes to the column in the table.

function clearSelection() {
    var sel;
    if ( (sel = document.selection) && sel.empty ) {
        sel.empty();
    } else {
        if (window.getSelection) {
            window.getSelection().removeAllRanges();
        }
        var activeEl = document.activeElement;
        if (activeEl) {
            var tagName = activeEl.nodeName.toLowerCase();
            if ( tagName == "textarea" ||
                    (tagName == "input" && activeEl.type == "text") ) {
                // Collapse the selection to the end
                activeEl.selectionStart = activeEl.selectionEnd;
            }
        }
    }
}

function table_data_change(obj, cel, val){
    $('#products_table').jexcel('updateSelection');
    clearSelection();
    $('#dummyfocus').focus();
}

**Comment by pphod** [comment]
This is only possible by change the original behaviour. The only think you can do block the manualRowInsert to avoid create a new row when hit enter in the last row.

**Comment by x0nium** [comment]
After trying alot, it turns out you can easily do it. 
Simply trigger a **mousedown** event on any element outside of the jexcel table. It must be **mousedown**! click doesn't work, focus doesn't work. Example:

`$('#dummyfocus').trigger('mousedown');`

You can add this to jexcel's onchange event:
`onchange:table_data_change,`

```
function table_data_change(obj, cel, val){
    setTimeout(function(){
        $('#dummyfocus').trigger('mousedown');
    }, 25);
}
```
