### ISSUE TITLE
Changes to parseCSV breaks pasting from Google Sheets/Excel/LibreOffice

### ISSUE THREAD

**Issue by lotsofish** [jspreadsheet/ce#359]
The changes to parseCSV in commit 1b9c270 breaks pasting data from Sheets, Excel and LibreOffice. It also fails to correctly parse comma separated values. It is pushing extra empty string elements to the array. The end result is the data pasted is separated by an extra column.

Examples (console window):
`$(document).jexcel('parseCSV', "2\t3\r2\t3", "\t")`
```
(2) [Array(3), Array(3)]
   0: Array(3)
      0: "2"
      1: ""
      2: "3"
      length: 3
   1: Array(3)
      0: "2"
      1: ""
      2: "3"
      length: 3
```
`$(document).jexcel('parseCSV', "1,2,3,4,5", ",")`
````
[Array(9)]
   0: (9) ["1", "", "2", "", "3", "", "4", "", "5"]
````

**Comment by pphod** [comment]
I am working in a new version. It will be released soon... thanks for that.

**Comment by pphod** [comment]
This has been fixed, and you will be available in the repository later on.
