### ISSUE TITLE
Paste Issue from Google Spreadsheet or MS Excel. Data breaks and added into new columns.

### ISSUE THREAD

**Issue by ashraftalib** [jspreadsheet/ce#36]
Issue is while pasting from MS Excel or Google Spreadsheet cell data to jexcel cell.
Data have some break lines in data-content. In Jexcel while pasting it is making extra new column for every break-line and is putting data into new column with braked data. But it should have to be in one single cell same as in Google Sheet or MS Excel. I am attaching two screenshots :
1-one is source from Google Spreadsheet or MS Excel.
2-other one is after pasting into jexcel cell.

**Source Data from Google spreadsheet**
![1](https://user-images.githubusercontent.com/31342456/30237988-a0b9086e-955b-11e7-9934-a8066e176d34.PNG)
**After pasting data into jsexcel**
![2](https://user-images.githubusercontent.com/31342456/30237989-a6088358-955b-11e7-9b53-6e191e6175ac.PNG)

Please help me thank you very much.

**Comment by pphod** [comment]
This feature is available in the version 1.3.0 in a different repository while we are testing this new version.

**Comment by ashraftalib** [comment]
@paulhodel  Thanks for this
Actually I was using from 1.3.0 branch with JS version 1.3.1 so it was not there but now in 1.3.0 branch with latest version 1.3.2 js is working fine. Thanks again 👍

**Comment by pphod** [comment]
The new features are now described in our new documentation website.
http://bossanova.uk/jexcel
