### ISSUE TITLE
 onchange event set formulas

### ISSUE THREAD

**Issue by TsePakKwan** [jspreadsheet/ce#360]
hi Paul,
please give a sample as below.

I want to set a formulas to cell when 'dropdown' use 'onchange' event.
I don't know why the formula didn't respond.

![1559025763835](https://user-images.githubusercontent.com/51103712/58458229-a1ee3880-8163-11e9-80bd-131d98842cb8.gif)

my code
https://jsfiddle.net/tsepakkwan/djm03fua/2/

**Comment by pphod** [comment]
You should use setValue or setRowData to set the formula correctly. Are you doing here is just updating the cell as text.

http://localhost:8002/jexcel/v3/examples/spreadsheet-formulas
