### ISSUE TITLE
Jexcel formula calculation with large data

### ISSUE THREAD

**Issue by guruganesh26** [jspreadsheet/ce#363]
HI, 

I love jexcel, it solves my problem, thanks for the wonderful library.
but i have one issue, i have data of 316 rows * 26 columns nearly 8500 cells, in those some 1000 cells are having formulas, when i load, it takes more time nearly 2 minutes.
Is there any way i can save the loading time?

my data will be like

var data1 = [
    ['Furnace', 10, 'AVERAGE', '=AVERAGE(B1:B4)'],
    ['Tower', 9, 'STDEVA', '=STDEVA(B1:B4)'],
    ['Drum', 44, 'MAX', '=MAX(B1,B2,B3,B4)'],
    ['Pump', 12, 'COUNT', '=COUNT(B1:B4)'],
];

**Comment by pphod** [comment]
Hi, this is a limitation from the CE version. Please, try the PRO VERSION. www.jexcel.net

If you like and would like to use, I can give you a 100% free license.

Best regards,

**Comment by Louise-Huang** [comment]
Hi,

I have same problem, and I'm using the pro version.

I have two worksheets, and each worksheet has 40 columns * 300 rows nearly 12000 cells. There are about 9100 cells with formulas and the formulas for each cell are different. Now I use 15 columns * 30 rows to test, the calculation will end immediately when I enter one cell, but if I use 30 columns * 30 rows, it takes more time nearly 2 minutes. I tried to use hideColumn, but it doesn't work.

Is there any way to save the calculating time?
