### ISSUE TITLE
Enabling events on undo / redo

### ISSUE THREAD

**Issue by TheNeverK** [jspreadsheet/ce#365]
From what I've noticed, when it comes to undo and redo actions in version 2.0.2, the `ignoreEvents` variable is set to true, so for example onchange event is never fired. To avoid this you have to comment out `$.fn.jexcel.ignoreEvents = false;` on lines 4092 and 4198 and change lines 4178 and 4247 from 
```js
$(this).jexcel('loadCells', records);
$(this).jexcel('loadCells', historyRecord.cellChanges);
```
to, respectively 
```js
$(this).jexcel('updateCells', records);
$(this).jexcel('updateCells', historyRecord.cellChanges);
```

I think it would be very nice to be able to decide whether or not events should fire without the need for this modification. So maybe to preserve compatibility it could be added as an option when creating the spreadsheet?

PS. Incredible work with the plugin, it saved me so much time. Thank you for sharing it.

**Comment by pphod** [comment]
Actually, in the most recent version we have available onundo & onredo
