### ISSUE TITLE
Adding row and deleting them

### ISSUE THREAD

**Issue by felixvandal** [jspreadsheet/ce#37]
Hello Paul, i hope i find you well.
I was wondering if you were planning on building a feature to add row over and/or over.
We have the possibility to add a row at the bottom on the right click.
I like the functionnality to add a row in excel that add on top of the row selected.
Also, i was wondering if there is a way to bind lets say the delete key to the delete row action.
As alway, thank you in advance and have a nice day

**Comment by pphod** [comment]
The delete column and row can be performed by the delete key. Updates on the master repository.

**Comment by pphod** [comment]
add column and row on the bottom/right side on the right click is already implemented on the context menu. Relative will be supported in the next version.

**Comment by ppingliu** [comment]
Hi Paul, i hope you have nice day
I have some question,  I have 3 rows, A, B, C，
1,   how can i add a new row between A and B 
2,   how can i  add a new row before the first row.

**Comment by ppingliu** [comment]
I already download the newest version

**Comment by felixvandal** [comment]
roger roger for the relative add of row and column
thank you for the multi delete the feature work as requested!

**Comment by ArulRozario** [comment]
Hi, Please provide me some sample code to add custom column type to have buttons and other elements.

**Comment by pphod** [comment]
http://www.bossanova.uk/jexcel/examples/integrating-a-third-party-plugin-into-your-spreadsheet
