### ISSUE TITLE
Dropdown Value Disappears After Tabbing Then Click

### ISSUE THREAD

**Issue by PRISMAY** [jspreadsheet/ce#370]
When you select multiple items from a multi-select dropdown then hit [tab] to move to the next cell.  Any click that follows will remove the value from the dropdown field.  This also happens on the sample pages.

If I don't use [tab] but select the items and then just click outside of the dropdown, the values are committed and no issues with any follow-up clicks.

You can duplicate this by going to https://bossanova.uk/jexcel/examples/working-with-dropdowns.  Pull down any of the fields under Product Origin and select more items then hit [tab]. Now click once anywhere in the spreadsheet or outside of it.

[edit] As a temporary workaround, I added the two reset lines below to closeEditor after the value var is assigned.  As I looked at the code, it looks like jexcel is closing the editor but it thinks the dropdown is still active. By resetting the jdropdown current and currentIndex that ensures the click event doesn't do anything that will reset the value.

```
		// Do nothing
	} else if (options.columns[position[0]].type == 'dropdown' || options.columns[position[0]].type == 'autocomplete')
	{
		// Get value
		if ($.fn.jdropdown)
		{
			var value = $(cell).find('.jdropdown').jdropdown('getValue');
			// Reset jdropdown
			$.fn.jdropdown.current = null
			$.fn.jdropdown.currentIndex = null;
		} else
		{
			if (options.columns[position[0]].type == 'autocomplete')
			{
```

**Comment by pphod** [comment]
I imagine you are going to have that fixed on v3.
