### ISSUE TITLE
Dropdown Scrolling Causes List To Close/Disappear

### ISSUE THREAD

**Issue by PRISMAY** [jspreadsheet/ce#371]
If you pull down a dropdown list and grab the scrollbar handle and drag it to quickly move down the list, the list just goes away and disappears.  The same happens if you click on the scroll area that allows you scroll one page at a time if you click and hold the mouse to scroll pages.

There are enough items under Product Origin on the sample page link below to reproduce this issue.
https://bossanova.uk/jexcel/examples/working-with-dropdowns

**Comment by pphod** [comment]
This problem has been fixed in the new v3 version. Would you like to give you a try?

**Comment by PRISMAY** [comment]
Thank you. We're not planning on upgrading to v3. Can the fix be applied to v2?

**Comment by PRISMAY** [comment]
I was able to find the issue and put a fix in place.  If anyone else is still using v2.x and wants to apply the fix, here you go.  In jquery.jexcel inside $.fn.jexcel.mouseDownControls, I wrapped the code in this conditional:
```
	// fix scroll issue where content box disappears when scrolling the content
	// list too quickly by holding down mouse or dragging scrollbar handle.
	if (!$(e.target).hasClass('jdropdown-content'))

```
i.e.,
```
// Edition 
$.fn.jexcel.touchControls = setTimeout(function()
{
	// fix scroll issue where content box disappears when scrolling the content
	// list too quickly by holding down mouse or dragging scrollbar handle.
	if (!$(e.target).hasClass('jdropdown-content'))
	{
		if ($.fn.jexcel.defaults[$.fn.jexcel.current].editable == true)
		{

```
