### ISSUE TITLE
Column types other than text and numeric are not working in 2.1.0

### ISSUE THREAD

**Issue by MarcoGiancarli** [jspreadsheet/ce#373]
In both my code and in jsfiddles using example code from the jexcel docs the column types that require external js files seem not to be working properly.

See https://jsfiddle.net/fp4oduvq/1/ for code from the column mask example.
See https://jsfiddle.net/sz9be7qa/1/ for code from the column types example. Oddly enough, the calendar column seems to work here while the dropdown doesn't, though neither seems to work in my project.

---

While writing this, I tried downloading and using the source files used on the example page itself. To my surprise, everything seemed to work! Nonetheless, I figured I'd add this issue since it seems that cdnjs is loading bad files and the example pages don't have working code as a result. I haven't tried running the source from the 2.1.0 branch in the repo itself.

**Comment by pphod** [comment]
Which browser: I have tested your jsfiddles, and seems to be working fine. I have just deployed the v3, would you like to give you a try?
