### ISSUE TITLE
Publish Typescript Type Definition

### ISSUE THREAD

**Issue by mohammed90** [jspreadsheet/ce#375]
This adds additional correctness validation, and eases inter-operation with Typescript projects.

**Comment by arx-8** [comment]
This package is very very useful.
So, I submitted a pull request.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43837

I am happy if this helps you.

**Comment by pphod** [comment]
Thank you! ;)

**Comment by arx-8** [comment]
Published!
https://www.npmjs.com/package/@types/jexcel

There are many "any" type and still incomplete, so I hope anyone will contribute.
