### ISSUE TITLE
Support für cell formulas in lowercase 

### ISSUE THREAD

**Issue by klehmann** [jspreadsheet/ce#376]
This looks like an amazing project!!

In my first test, I tried a formula "=a1+a2" and got an error message in the cell, because the cell names must be written in uppercase.
So if possible, you could make it a bit easier for users if you supported lowercase names as well.

**Comment by pphod** [comment]
Thanks! I will take a look, but I am not sure if this will be feasible.

**Comment by pphod** [comment]
Sorry, but you will need an external custom method to do that. I would suggestion onbeforechange, you can do an uppercase in the column you expect formulas. You can intercept what the user has entered and return the modified uppercase value instead.

**Comment by klehmann** [comment]
Ok, thanks for checking and for the workaround.

**Comment by pphod** [comment]
Sure, Let me know if you have any questions.
