### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by noyessie** [jspreadsheet/ce#378]
Hello

Please, it is possible to use **jexcel** with **angular 8**. I always see that is **vanilla** plugins.

**Comment by pphod** [comment]
I am sure this can work together. I don't have an example yet, but I would ask if someone can prepare an example for us. I will definitely upload to the website and give the proper credits. For now you can see examples integrating jExcel with React, Vue and Jquery.

https://bossanova.uk/jexcel/v3/examples/react
https://bossanova.uk/jexcel/v3/examples/vue
https://bossanova.uk/jexcel/v3/examples/jquery
