### ISSUE TITLE
Columns Widths dynamically

### ISSUE THREAD

**Issue by cevc96** [jspreadsheet/ce#38]
Hello, I have this table 

![image](https://user-images.githubusercontent.com/11530293/30816036-798139fc-a1da-11e7-9544-7f972c234573.png)

Is possible to resize column dynamically in all browser screen.
Thanks.

**Comment by pphod** [comment]
You can try a method to count the number of characters and create a formula to estimated width is required. You can use something like that: http://www.bossanova.uk/jexcel/examples/currency-and-masking-numbers

**Comment by dfloresgonz** [comment]
Why is this closed? that wasn't the solution, there should be an option such as resizeLastColumn = true or assign % as width, hope that can be achieved.

**Comment by pphod** [comment]
This is a possible solution:
http://jsfiddle.net/paulhodel/eht0q91s/
