### ISSUE TITLE
Jexcel Row Update

### ISSUE THREAD

**Issue by stanleliu** [jspreadsheet/ce#380]
Is there function in JEXCEL such as setRowData (corresponding to getRowData) so I can update a row with an array instead of using setValue to assign data cell by cell?

**Comment by pphod** [comment]
I am going to prepare that, it will be included in the next released.

**Comment by stanleliu** [comment]
Thanks a lot, wonderful job, paulhodel! Look forward to it.

**Comment by pphod** [comment]
It has been done. Already in the master repository ;)

**Comment by bibibala** [comment]
(vue 2.6.3) (jspreadsheet-ce 4.10.2)
My logic here is that when I enter two values and then judge the type, and then reassign the data of this row, but my table is not updated by using setRowData, but when I print getData after the assignment, I find that the data has changed , but the dom is not refreshed, how to solve this change, looking forward to your reply

`      // info ['长链/短链接'，'Number'，'Number' ，'Number']

      // get currentRow data
      let info = this.$refs.excel.excel.getRowData(this.current.row - 1)
      if (validate.number(info[1]) === true && validate.number(info[2]) === true) {
        if ((info[2] - info[1]) > 0) {
          info[0] = `长链`
          info[3] = Math.abs(info[2] - info[1])
          console.log(info)
          this.$refs.excel.excel.setRowData(this.current.row, info)
        } else if ((info[2] - info[1]) === 0) {
          this.$msg.warning(`长链和断链数值不能相同`)
        } else {
          info[0] = `短链`
          info[3] = Math.abs(info[2] - info[1])
          console.log(info)
          this.$refs.excel.excel.setRowData(this.current.row, info)
        }
      } else {
        this.$msg.warning(`输入的数据不符合格式`)
      }
    `
