### ISSUE TITLE
Delete column, but <col> isn't deleted from <colgroup>

### ISSUE THREAD

**Issue by komorihi** [jspreadsheet/ce#381]
I want to get table size of jexcel when the table is resized.
But in the 'ondeletecolumn' case, it didn't work because of `<col>` didn't delete from `<colgroup>`.
 For the same cause, if I delete the in-between column, the width of the right next column becomes the width of the deleted column. This is not expected behavior.

**Comment by pphod** [comment]
I have tested that on v3 (available in the master repository) and it is working fine. Could you kindly update to the newest version, please?
