### ISSUE TITLE
Formula doesn't update properly in some cases

### ISSUE THREAD

**Issue by Nedlinin** [jspreadsheet/ce#382]
https://bossanova.uk/jexcel/v3/examples/spreadsheet-formulas

If you click in Total column row 1 and change the formula to =B1*C2 the total at the bottom updates.  However, if you click in Total column row 1 again and use the quick copy anchor (the block box in the bottom right) and drag it down to fill D1:D8, the total at the bottom does not update even though the values above do.

**Comment by syedfahadjalali** [comment]
During the drag and pasting the values the formula is not updating.
but if you click on formula cell in edit view and press enter it will take the new calculations.

**Comment by pphod** [comment]
A lot of improvements on the PRO distribution in regards to that. CE has some improvements and eventually will get all.
https://jexcel.net
