### ISSUE TITLE
For elements, jQuery object not supported (jexcel wants DOM Object)

### ISSUE THREAD

**Issue by gfbagel** [jspreadsheet/ce#385]
`$('#CompatibilityTable')[0].jexcel.setData(tableData);` OK
`$('#CompatibilityTable').jexcel.setData(tableData);` doesn't work...
Same thing for stuff like jexcel.destroy, getData, etc...

I was trying to follow similar to the jquery example @ https://bossanova.uk/jexcel/v3/examples/jquery

**Comment by pphod** [comment]
You can refer to the version 2 documentation to get the correct jquery syntax. There are a lot examples using jquery. https://bossanova.uk/jexcel/v2/examples

The correct way following your example should be:
$('#CompatibilityTable').jexcel('setData', tableData);
