### ISSUE TITLE
Fixed cell size

### ISSUE THREAD

**Issue by shreyapandit** [jspreadsheet/ce#386]
Is it possible to have cell size fixed, and not based on the length of the column name?
For example, a layout like so where column names can be written vertically so that the cell width is always the same?

Thanks!

<img width="470" alt="Screen Shot 2019-06-21 at 1 47 55 PM" src="https://user-images.githubusercontent.com/836757/59941453-3712e300-942b-11e9-81c2-a0e7494ff2cf.png">

**Comment by pphod** [comment]
This requires a custom implementation. jExcel deals with normal HTML tables though DOM manipulation. So, basically you can use an onload:function() { }  to apply any changes to the headers.
