### ISSUE TITLE
Sorting issue

### ISSUE THREAD

**Issue by rc183** [jspreadsheet/ce#39]
Hello,

There is an issue with the sorting. It works very well if the fields are strings but it doesn't works with numeric field because all field are sorted like a string so if I try to sort 1, 2, 10, 3 the results will be 1, 10, 2, 3 instead of 1, 2, 3, 10.

I think we just have to check the column type and update the sortBy method depending of this type.

I can submit a patch if you want.

Thanks,
 Régis

**Comment by rc183** [comment]
I have pushed the fix if you want

**Comment by pphod** [comment]
I has been approved. Thank you for your collaboration.
