### ISSUE TITLE
japp: import/require for webpack from npm

### ISSUE THREAD

**Issue by Zireael** [jspreadsheet/ce#392]
Hi,
I'm trying to follow Vue integration guide: https://bossanova.uk/jexcel/v3/examples/vue

I'm using webpack to bundle liblaries in .vue components instead of hardcoding .js/.css imports from cdn/bossanova.uk
One problem I have is that japp.js is not included in your npm bundle and the link to https://bossanova.uk/jexcel/v3/japp.js does not work - file might not exist?
Would be nice if japp.js was included in npm module for jexcel or at least had it's own npm.
When used with Vue/React/Angular,  libraries can be code spitted and imported only when needed in components/views rather than being declared for download upfront.

Thank you for taking time to make a version without jQuery! ^^

**Comment by pphod** [comment]
jApp has been included in the dist folder in the npm v3.0.4

**Comment by luastoned** [comment]
Please re-open this issue based on the following issues:

jExcel

- adds event listeners before being called

jExcel adds event listeners before being called, assumes "document" is always available and requires jApp to be globally available. Those issues pretty much prevent it from being used in any larger environment/project that relies on clean imports or has SSR.

jApp has no module structure and pollutes the global namespace, which means you can't even import it properly.

The framework looks really nice but those issues should be resolved before claiming npm/webpack support.

**Comment by luastoned** [comment]
Please re-open this based on the following issues:

**jExcel**
- adds event listeners before being called
- assumes `document` is available, bad for Angular and other frameworks that have SSR
- requires `jApp` to be globally available, big nono for any larger environment/project that relies on clean imports, code splitting etc.

**jApp**
- has no module structure, thus can't be imported properly
- pollutes the global namespace

The framework looks really nice but those issues should be resolved before claiming npm/webpack support.

**Comment by pphod** [comment]
@luastoned Absolutely right. I am tackling those issues, the new version will be released this weekend.

**Comment by Zireael** [comment]
Sorry to be a pain @paulhodel - I tried adding internal jApp import within jexcel.js myself, but it is a bit beyond me. Don't feel pressure on this, but I believe with webpack import support your app will get much more adoption. \o.o/

Another thing is attached japp.css file: it contains universal selectors like body{}, input, select, textarea, div {}, * {-webkit-stuff} or even --active-color (I bet it's a popular name with lotsa people). If jExcel/jApp is used as a component on a page, it might bleed out into other element styles.

NB; Vue compiler (when importing into a .vue component) is complaining a bit that <TableExcel> is unrecognized custom element (normally Vue would expect any custom element popping up on it's turf to be a registered/imported .vue component), but it's not really breaking anything.

**Comment by pphod** [comment]
Sure, I share the same concerns. I am working hard to get those
improvements in the next release.

Thanks for the suggestions.

Regards

**Comment by pphod** [comment]
Ok, I resolved major issues related to that, and create a small sample project using React.
https://github.com/paulhodel/jexcel-with-react

The jApp has been changed to jsuites and now it is a dependency in the jExcel npm package.

I hope that solves major issues.

**Comment by Zireael** [comment]
~Seems npm/yarn don't import/install the latest bundle version yet and I get console error that jSuites is not defined. But when I downloaded the latest zips for both jExcel/jSuites and unpacked into respective folders in `node_modules`, everything works.~

Here is example of using jExcel in a Vue component file (.vue)
https://codesandbox.io/embed/vue-default-template-p4hwn
~At the moment it's failing because Codesandbox can't import the latest package versions form npm, but once that starts pulling the correct version, all should work just like on my local machine.~

Code below for .vue component example:

**jexcel.vue**
```
<template lang="html">
  <div class="wrapper-jexcel">
    <div class="introduction"><span>This is a list of my cars</span></div>
    <input
      type="button"
      value="Add new row"
      @click="jExcelObj.insertRow()"
    /><br />
    <div id="spreadsheet" ref="spreadsheet"></div>
  </div>
</template>

<script>
import jexcelStyle from "jexcel/dist/jexcel.css"; // eslint-disable-line no-unused-vars
import jexcel from "jexcel"; // eslint-disable-line no-unused-vars

export default {
  name: "jexcel",
  data() {
    return {
      myCars: [
        ["Jazz", "Honda", "2019-02-12", "", true, "$ 2.000,00", "#777700"],
        ["Civic", "Honda", "2018-07-11", "", true, "$ 4.000,01", "#007777"],
        ["Z4", "BMW", "2017-11-24", "", false, "$ 324.072,58", "#700d0d"],
        ["Boxter S", "Porshe", "2019-08-24", "", true, "$ 307.839,45", "#0e0438"]
      ]
    };
  },
  computed: {
    jExcelOptions() {
      return {
        data: this.myCars,
        columns: [
          { type: "text", title: "Car", width: "120px" },
          {
            type: "dropdown",
            title: "Make",
            width: "250px",
            source: ["Alfa Romeo", "Audi", "BMW", "Honda", "Porshe"]
          },
          { type: "calendar", title: "Available", width: "250px" },
          { type: "image", title: "Photo", width: "120px" },
          { type: "checkbox", title: "Stock", width: "80px" },
          {
            type: "numeric", title: "Price", width: "120px", mask: "$ #.##,00", decimal: ","
          },
          { type: "color", width: "100px", render: "square" }
        ]
      };
    }
  },
  methods: {
  },
  mounted: function() {
    //console.log(this.jExcelOptions);
    //console.log(this.$refs["spreadsheet"]);
    const jExcelObj = jexcel(this.$refs["spreadsheet"], this.jExcelOptions);
    // Object.assign(this, jExcelObj); // pollutes component instance
    Object.assign(this, { jExcelObj }); // tucks all methods under jExcelObj object in component instance
    // console.log(this.jExcelObj);
  }
};
</script>

<style lang="css" scoped>
.introduction {
  font-size: 14px;
  padding: 0.5em;
  margin-bottom: 0.3em;
  color: gold;
  background: #111;
}
</style>

```

**Comment by Zireael** [comment]
Not a big deal, but I'm getting this advisory from Chrome console:
> Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by Zireael** [comment]
Big deal, I suppose:
In my Vue implementation, as above, copying cells doesn't work. (possibly other methods as well)
Copy:

> jexcel.js?0179:5262 Uncaught ReferenceError: hash is not defined
>     at Object.obj.hash (jexcel.js?0179:5262)
>     at Object.obj.copy (jexcel.js?0179:4816)
>     at HTMLDocument.jexcel.copyControls (jexcel.js?0179:6412)
Paste:

> jexcel.js?0179:5262 Uncaught ReferenceError: hash is not defined
>     at Object.obj.hash (jexcel.js?0179:5262)
>     at Object.obj.paste (jexcel.js?0179:4834)
>     at HTMLDocument.jexcel.pasteControls (jexcel.js?0179:6433)
DragandDrop Copy:

> jexcel.js?0179:1780 Uncaught ReferenceError: value is not defined
>     at Object.obj.copyData (jexcel.js?0179:1780)
>     at HTMLDocument.jexcel.mouseUpControls (jexcel.js?0179:6178)

Is it possibly because jExcel is imported into Vue component and not the main Vue instance? I'm also assigning all jExcel properties/methods under a single object in component instance:
```
    const jExcelObj = jexcel(this.$refs["spreadsheet"], this.jExcelOptions);
    // Object.assign(this, jExcelObj); // pollutes component instance
    Object.assign(this, { jExcelObj }); // tucks all methods under jExcelObj object in component instance
    // console.log(this);
    // console.log(this.jExcelObj);
```
I tried with all methods assigned to main component instance (polluting) as well, but getting same errors.

**Comment by Zireael** [comment]
Thanks @paulhodel 
The latest version is now on npm/yarn and imports correctly.
If it looks suitable, feel fee to add my .vue example above to documentation - the example in your docs is for when Vue is being added to an existing page as a widget through render function etc. The .vue (above) is an example for folk creating a single page application.

Also, for the error with copy/paste
> jexcel.js?0179:1780 Uncaught ReferenceError: value is not defined
> at Object.obj.copyData (jexcel.js?0179:1780)
> at HTMLDocument.jexcel.mouseUpControls (jexcel.js?0179:6178)
it seems it is not specific to only Vue, as I saw it also on your documentation pages with example jExcel tables embedded.

I hope you've had a cold weekend, cheers!

**Comment by pphod** [comment]
> Thanks @paulhodel
> The latest version is now on npm/yarn and imports correctly.
> If it looks suitable, feel fee to add my .vue example above to documentation - the example in your docs is for when Vue is being added to an existing page as a widget through render function etc. The .vue (above) is an example for folk creating a single page application.
> 
> Also, for the error with copy/paste
> 
> > jexcel.js?0179:1780 Uncaught ReferenceError: value is not defined
> > at Object.obj.copyData (jexcel.js?0179:1780)
> > at HTMLDocument.jexcel.mouseUpControls (jexcel.js?0179:6178)
> > it seems it is not specific to only Vue, as I saw it also on your documentation pages with example jExcel tables embedded.
> 
> I hope you've had a cold weekend, cheers!

It has been fixed.
