### ISSUE TITLE
v3 issue: allowRenameColumn not working when false

### ISSUE THREAD

**Issue by PRISMAY** [jspreadsheet/ce#393]
Setting allowRenameColumn to false does NOT remove/hide "Rename this column" header context menu item.

**Comment by PRISMAY** [comment]
I've temporarily fixed this by wrapping the items.push code in the conditional below.
```
        if (obj.options.allowRenameColumn == true)
        {
            items.push({
                title: obj.options.text.renameThisColumn,
                onclick: function onclick()
                {
                    obj.setHeader(x);
                }
            }); // Line
        }

```

**Comment by pphod** [comment]
It has been fixed in my side. It will be in the repository in 10 minutes. Thanks for that.

**Comment by PRISMAY** [comment]
Thank you and you're welcome. :)
