### ISSUE TITLE
V3 Context Menu Still Not Popping Up At Mouse In Dialog

### ISSUE THREAD

**Issue by PRISMAY** [jspreadsheet/ce#395]
Looks like the fix for the context menu is fine on a normal page, however, it's still not popping up in right location when using jQuery UI dialog.

I can't duplicate on jsFiddle because the jexcel & japp resources need to be updated first.  Here's the [jsFiddle link](https://jsfiddle.net/AYSabre/mft57vs0/) with just a basic "dialog" that should reproduce the issue once the resources are updated.

It basically now pops up relative to where the dialog is on the page and the distance from the mouse is the offset between the browser content area and the current dialog position.

**Comment by pphod** [comment]
I have checked and it seems a problem related to the jquery UI.

this is the style applied in the dialog: 
position: relative; height: auto; width: 800px; top: -124.588px; left: -7.99716px; display: block;

And it seems if you remove that all works fine. It seems a few 404 happening...

In that case it is related to the dialog. jApp already brings you a dialog, I am not sure if would help you.
https://bossanova.uk/jtools/modal

**Comment by PRISMAY** [comment]
I grabbed the master branch this morning and the context menu is working perfectly.  Not sure what the difference between master and what npm pulls down but master works great.  I use "npm install jexcel" and it showed 3.0.4 (comments in jexcel.js show 3.0.3 though).
