### ISSUE TITLE
colWidths not Working with React

### ISSUE THREAD

**Issue by Zackhardtoname** [jspreadsheet/ce#396]
Windows 10,
"react": "^16.8.6",
"react-dom": "^16.8.6"

I want to confirm that certain functionalities don't work with React. In particular, colWidths in options and the ability to drag the column width. Thank you!

**Comment by Zackhardtoname** [comment]
My code for reference
```

function App() {
    var data = [
        ['Jazz', 'Honda', '2019-02-12', '', true, '$ 2.000,00', '#777700'],
        ['Civic', 'Honda', '2018-07-11', '', true, '$ 4.000,01', '#007777'],
    ];

    var options = {
        data:data,
        colHeaders: ['Model', 'Price', 'Price' ],
        // colWidths: [ 300, 300, 300 ],
        columns: [
            { type: 'text', title:'Car', width:120 },
            { type: 'dropdown', title:'Make', width:120, source:[ "Alfa Romeo", "Audi", "Bmw" ] },
            { type: 'calendar', title:'Available', width:200 },
            { type: 'image', title:'Photo', width:120 },
            { type: 'checkbox', title:'Stock', width:80 },
            { type: 'numeric', title:'Price', width:100, mask:'$ #.##,00', decimal:',' },
            { type: 'color', width:100, render:'square', }
        ]

    };

    return (
        <div className="App">
            <Navbar title="Confounder Matrix"/>
            <Panel />
            <Chart options={options} />
        </div>
    );
}
```

```
class Chart extends React.Component {
    constructor(props) {
        super(props)
        this.options = props.options
        this.chart = props.chart
    }

    componentDidMount = function() {
        this.el = jexcel(ReactDOM.findDOMNode(this).children[0], this.options)
    }

    addRow = function() {
        this.el.insertRow()
    }

    render() {

        return (
            <div>
                <div></div><br/>
                <input type='button' value='Add new row' onClick={() => this.addRow()}></input>
            </div>
        );
    }
}
```

**Comment by pphod** [comment]
Can you try the following?
```
function App() {
    var data = [
        ['Jazz', 'Honda', '2019-02-12', '', true, '$ 2.000,00', '#777700'],
        ['Civic', 'Honda', '2018-07-11', '', true, '$ 4.000,01', '#007777'],
    ];

    var options = {
        data:data,
        colHeaders: ['Model', 'Price', 'Price' ],
        // colWidths: [ 300, 300, 300 ],
        columns: [
            { type: 'text', title:'Car', width:120 },
            { type: 'dropdown', title:'Make', width:'120px', source:[ "Alfa Romeo", "Audi", "Bmw" ] },
            { type: 'calendar', title:'Available', width:'200px' },
            { type: 'image', title:'Photo', width:'120px' },
            { type: 'checkbox', title:'Stock', width:'80px' },
            { type: 'numeric', title:'Price', width:'100px', mask:'$ #.##,00', decimal:',' },
            { type: 'color', width:'100px', render:'square', }
        ]

    };

    return (
        <div className="App">
            <Navbar title="Confounder Matrix"/>
            <Panel />
            <Chart options={options} />
        </div>
    );
}
```

**Comment by Zackhardtoname** [comment]
Hi paulhodel,

I tried your suggestion, but it still doesn't work. The overall code is here: https://github.com/hicsail/confound/tree/jexcel-react

I also created a codepen here: https://codepen.io/Zackhardtoname/pen/LKjBMM
The interesting thing is that the table almost doesn't render on codepen.

I am really sorry for this trouble. I sincerely appreciate your help!

**Comment by pphod** [comment]
Hi,

You are loading a old CSS style that is conflicting with the new one.
Please remove this line.
<link rel="stylesheet" href="
https://cdnjs.cloudflare.com/ajax/libs/jexcel/1.5.7/css/jquery.jexcel.min.css
">

**Comment by Zackhardtoname** [comment]
Thank you!
I removed as you instructed, but the original problem was still unresolved. The code is still here: https://codepen.io/Zackhardtoname/pen/LKjBMM
1. the attribute `width:120` as in the first column in your example or `width:'120px'` is still not working. I assume the missing quotes in the first one are a type?
2. the option `colWidths: [ 300, 300, 300 ]` doesn't work
3. when the column name or cell text is too long, the cell table does not scale to match the length. (You can see it in the example) Is it expected behavior or is there any way to change that?

Thank you so much for your help! By the way, my non-react approach is working well.

**Comment by pphod** [comment]
You have the variable options twice in your code. The second one does not define width, just remove the second declaration and it will work for you.

var options = {
    data: data,
};

**Comment by Zackhardtoname** [comment]
It is working! Thank you so much for your patience.
