### ISSUE TITLE
Valid JSON Support

### ISSUE THREAD

**Issue by manattweb** [jspreadsheet/ce#399]
I see several closed issues about JSON data as source, but the responses have been inconclusive about whether or not a valid JSON file can be used as import.

What is meant by valid JSON (at least to me) is that there are key/value pairs and braces. Providing something like below doesn't work and I'm wondering if it is on the roadmap to implement. If not, that's cool, I think datatables can do it, but I like what you've started here.

I'm wanting to create a spreadsheet from dynamic data from SQL Server, which has built-in JSON utilities.

Sample JSON generated from SQL Server:
{"data": [{"campaignname": "New Basketball Gym","campaigngoal": 1000000},{"campaignname": "New Library","campaigngoal": 2000000}]}

**Comment by pphod** [comment]
You must generate that without the keys:

{["New Basketball Gym",1000000},{"New Library",2000000}]}

**Comment by manattweb** [comment]
Then I think it's important to modify your documentation to omit the mention of JSON imports as the JSON specification implicitly is defined as a set of Key/Value pairs.

I do think that it would be great to allow a user to specify keys as column headers and jexcel parse the JSON file to get the values for that column. I figured that's what you intended when I read that jexcel allowed JSON as a data source.

Keep up the good work - a useful tool for sure.

**Comment by pphod** [comment]
I am going to reopen and add your suggestion in the next release.

**Comment by l0ckm4** [comment]
I would like this functionality extended to be able to pass parameters to the URL serving the JSON file as most of the time you need to be able to generate the JSON on the fly based on whatever you want to display.

Example:-

```
jexcel(document.getElementById('spreadsheet2'), {
    jexcel(document.getElementById('spreadsheet2'), {
        url:'/v3/test.json',
        parameters: { id: "3", action: "retrieve" },
        columns: [
            { type:'text', width:300 },
            { type:'text', width:100 },
         ]
    });
});
```

**Comment by manattweb** [comment]
> I would like this functionality extended to be able to pass parameters to the URL serving the JSON file as most of the time you need to be able to generate the JSON on the fly based on whatever you want to display.

That's something you need to do on the code that generates the JSON, not on the display side. In my case, I've written code that queries a SQL Server and returns the results as JSON that is then (hopefully) going to be consumed and displayed in jexcel. I could add URL parameters to url call in jexcel that could manipulate the JSON output, but again, not something jexcel should concern itself with.

Two layers - 1) data generation (JSON) and 2) data display (jexcel). Layer 1 is independent of layer 2 and can be due to the universal structure the JSON specification allows for. Layer 1 is your responsibility and layer 2 is handled by jexcel.

Make sense?

**Comment by l0ckm4** [comment]
> > I would like this functionality extended to be able to pass parameters to the URL serving the JSON file as most of the time you need to be able to generate the JSON on the fly based on whatever you want to display.
> 
> That's something you need to do on the code that generates the JSON, not on the display side. In my case, I've written code that queries a SQL Server and returns the results as JSON that is then (hopefully) going to be consumed and displayed in jexcel. I could add URL parameters to url call in jexcel that could manipulate the JSON output, but again, not something jexcel should concern itself with.
> 
> Two layers - 1) data generation (JSON) and 2) data display (jexcel). Layer 1 is independent of layer 2 and can be due to the universal structure the JSON specification allows for. Layer 1 is your responsibility and layer 2 is handled by jexcel.
> 
> Make sense?

I think we can agree to disagree. Being able to pass parameters to a what is essentially an AJAX JSON request in my eyes is pretty fundamental.  I am not a fan of passing parameters using GET and of course the server servicing the request needs to know what it is going to deliver.  We cannot have a separate page serving separate JSON  strings.  Re-usable code is a must of course.

That said, I hope you dont mind me adding my request onto your thread.  It was just the most obvious place to add it considering Paul said he will be re-writing the portion of the code that handles the JSON to allow properly structured data.

Take care.

**Comment by manattweb** [comment]
I guess I won't speak (any longer) for the developer, but it seems like jexcel is a presentation tool - concerned with ingesting the data and displaying it on a web page.

I guess I can see you wanting to add params like you would with an AJAX call to an API, but I would think you do that somewhere else and then reference the JSON file you get from said AJAX call.

**Comment by pphod** [comment]
JSON with k=>v is now support:
https://jsfiddle.net/paulhodel/jv7sth0z/
