### ISSUE TITLE
Which event fire when release the mouse from the cells selection ? 

### ISSUE THREAD

**Issue by gulshan-escalon** [jspreadsheet/ce#4]
Hi, 

I am using your plugin and its great to use it. Now i have a requirement to get the range of cells when mouse released from the selection of cells. Actually I have to store that range in database and that range should be  pre-selected when user comes next time.  Please give me a solution.

Thanks

**Comment by pphod** [comment]
Hi Gulshan, thank you for sharing your experience. The following example will show you how to programmatically select columns on jExcel. http://jsfiddle.net/b9kj4ouq/1/

**Comment by gulshan-escalon** [comment]
No This is not what i wanted . I want that which event occur when i released the mouse after cells selection ?

**Comment by gulshan-escalon** [comment]
I want to select the columns manually and store those in database after releasing the mouse selection. Please give any solution ?

**Comment by pphod** [comment]
I have added the onselection and oncellselection events. For a callback after the onmouseup event you should follow the example: http://jsfiddle.net/s1ef8do1/1/

Please bear in mind you should update your local version to the new version available on the master branch.

**Comment by gulshan-escalon** [comment]
Its not working here , Please check it again

**Comment by paulhodel** [comment]
It is not working because you get the old file in cache.

**Comment by gulshan-escalon** [comment]
yes its working now thanks Paulhodel , Aswm
