### ISSUE TITLE
is it typescript supported?

### ISSUE THREAD

**Issue by JayatirthaJoshi** [jspreadsheet/ce#401]
Hi,

can we integrate jExcel with Angular and Type Script ?
Please share some examples

Regards
Jay

**Comment by jainpradeep** [comment]
Hi Jay,

Please find a working example for using jexcel with angular,
[link](https://github.com/jainpradeep/ex-angular/blob/master/README.md)

Jexcel is wrriten in pure javascript. For using jexcel in angular (typescript), necessary type definations are added in the example.

**Comment by pphod** [comment]
https://www.npmjs.com/package/@types/jexcel
