### ISSUE TITLE
V2 Copy Not Working When Worksheet In jQuery UI Dialog

### ISSUE THREAD

**Issue by PRISMAY** [jspreadsheet/ce#402]
We use dialogs in our application and the use of this worksheet is working well using version 2 with Copy as an exception right now.  I was able to reproduce the issue in a [jsFiddle](https://jsfiddle.net/AYSabre/c7Lts08k/).

**Comment by pphod** [comment]
Sorry, what is the problem? The table seems to be working fine in the example you sent. Can you explain the problem?

**Comment by PRISMAY** [comment]
Sorry about that.  If you highlight cells and then either use Ctrl+C or the Copy context menu nothing gets copied to the clipboard.

**Comment by pphod** [comment]
It seems jquery UI prevents the event... I have tested without jquery ui and it is working fine. Sorry, but in this instance, I am not able to help.

**Comment by PRISMAY** [comment]
I did find a solution to it by adding a 'copy' event listener on document that uses the function below.
```
document.addEventListener('copy', worksheet_OnCopy);
...
worksheet_OnCopy = function(ce)
{
   ce.clipboardData.setData('text/plain', $('#jexcel_textarea', $(document)).val());
   ce.preventDefault();
}
```
Thank you.

**Comment by pphod** [comment]
That's really great! ;)

**Comment by PRISMAY** [comment]
Thanks. Hopefully, someone else can benefit too. ;)

BTW, running in a dialog is also breaking the selection corner handle. If you look at the jsFiddle, you'll see the corner handle is missing from the selected cell.  Below is what we should be seeing for example. Do you think this is related to a similar issue as above? I haven't yet dug into the code to see how you deal with the corner handle. Let me know if you want me to submit this as a separate issue.
![2019-06-28 08_51_58-jExcel v2 - missing corner handle in jquery ui dialog](https://user-images.githubusercontent.com/3864368/60347244-805eb780-9982-11e9-8179-fd5d7f8656e6.png)

**Comment by PRISMAY** [comment]
It looks like the issue with the corner selector is due to the z-index.  In my worksheet, it's there but it's under some other object.  I just took a shot at the html and noticed it was there and then set the z-index to a high number above our overlay and it showed it.

**Comment by pphod** [comment]
I am going to update the project.

**Comment by PRISMAY** [comment]
Thank you.  In the meantime, am using JavaScript to set the z-index.
