### ISSUE TITLE
Erroneous cell value change

### ISSUE THREAD

**Issue by Lockey45** [jspreadsheet/ce#405]
Using your example and numeral.js I have formatted a cell as 23,583.00.  When I double click on the cell and then click on another cell, without making any changes, the first cell values changes to 0.00.  The issue occurs due to line 1846 in jquery.jexcel.js: value = Number(value) || 0.  This evaluates to 0 since Number("23,583.00") is NaN.  Other than  modifying the source code, is there something I can do to fix this?  I am using jexcel v2.1.

**Comment by pphod** [comment]
Can you create a jsfiddle?

**Comment by Lockey45** [comment]
https://jsfiddle.net/johnlock42/wLq5j1m2/3/

**Comment by pphod** [comment]
Change your column types to text and it will solve your problem.

```
            columns: [
                { type:'text'},
                { type:'text'},
                { type:'text'},
            ],
```
