### ISSUE TITLE
minor: right-click menu <a> tags inherit style from global page css

### ISSUE THREAD

**Issue by Zireael** [jspreadsheet/ce#406]
Right-click menu gets affected by CSS for `<a>` tags if set somewhere else in CSS for the page. Please consider adding more specificity to your `<a>` tags so that your CSS settings take precedence. maybe add a class to them, like `a.jexcelmenu {color: #000000;}`
![image](https://user-images.githubusercontent.com/3856578/60402002-4ad3ed00-9b81-11e9-99fd-e26991f36c89.png)

If you like my CSS from the screenshot above, here it is :)

```
a {
  font-family: 'Inconsolata';
  color: #132d6a;
  background-color: #f5f5f5;
  background: linear-gradient(rgba(244, 244, 244, .9), rgba(#e0e0e0, .9));
  text-decoration: none;
  white-space: nowrap;
  font-size: 1em;
  border: thin solid rgba(0, 0, 0, .25);
  border-radius: 4px;
  padding-left: .2em;
  padding-right: .2em;
  box-shadow: inset 0 0 4px 1px rgba(0, 0, 0, .025);
}
```
Well, I admit it is also my fault for setting up a global default CSS for `<a>` tags for the entire site. :)

**Comment by pphod** [comment]
There are too much custom ones to add to the jExcel library. Can you please edit in your side, please?
