### ISSUE TITLE
Cannot read property 'contextmenu' of undefined

### ISSUE THREAD

**Issue by meteerogl** [jspreadsheet/ce#407]
`$(document).ready(function () {
            handler = function(obj, cell, val) {
                console.log('My table id: ' + $(obj).prop('id'));
                console.log('Cell changed: ' + $(cell).prop('id'));
                console.log('Value: ' + val);
            };

            insertrow = function(obj) {
                alert('new row added on table: ' + $(obj).prop('id'));
            }

            deleterow = function(obj) {
                alert('row excluded on table: ' + $(obj).prop('id'));
            }

            data = [
                ['Mazda', 2001, 2000, '2006-01-01 00:00:00'],
                ['Pegeout', 2010, 5000, '2005-01-01 00:00:00'],
                ['Honda Fit', 2009, 3000, '2004-01-01 00:00:00'],
                ['Honda CRV', 2010, 6000, '2003-01-01 00:00:00'],
            ];

            $('#my').jexcel({
                data:data,
                colHeaders: ['Model', 'Date', 'Price', 'Date'],
                colWidths: [ 300, 80, 100, 100 ],
                onchange:handler,
                oninsertrow:insertrow,
                ondeleterow:deleterow,
                columns: [
                    { type: 'text' },
                    { type: 'numeric' },
                    { type: 'numeric' },
                    { type: 'calendar', options: { format:'DD/MM/YYYY HH24:MI', time:1 } },
                ]
            });
        })`

**Comment by JayatirthaJoshi** [comment]
you need to refer jsuites js and css.

**Comment by pphod** [comment]
I guess you have no included jsuites. There are several examples in the website. Please make sure you include that in your project.
