### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by chemscobra** [jspreadsheet/ce#408]
![image](https://user-images.githubusercontent.com/2581610/60455086-8a431d80-9c03-11e9-8ba6-f30e429fcebd.png)

when I set the pagination number option, it displays the table without the page numbers and the console throws this error
 jexcel.js:4634 Uncaught ReferenceError: startNumber is not defined.

**Comment by pphod** [comment]
Can you send me the sample code you are using?

**Comment by chemscobra** [comment]
https://jsfiddle.net/5vexmyb7/

**Comment by pphod** [comment]
Thanks, it is working now. Update on the master repository.

**Comment by chemscobra** [comment]
Awesome!, thanks you so much!
