### ISSUE TITLE
Data Attribute in Each Cell

### ISSUE THREAD

**Issue by mfakhrys** [jspreadsheet/ce#41]
How to put data attribute in each cell? For example, data-student-id and data-quiz-id? So that onchange, I can retrieve those data and send ajax request to update the database.

**Comment by pphod** [comment]
If you are looking for the ID, all cells already have ID and CLASS
following the logic below:

For ID is a coordinate from x, y starting on zero, example:
id='1-0' = column B1
id='2-0' = column C1
id='0-0' = column A1
id='0-3' = Column A4

And all cells have at least two classes, one for column and one for row as
follow.
c0, c1, c2, c3 and r0, r1, r2, r3, etc.

But, if you would like to have a custom property you can create that using
this example:
http://www.bossanova.uk/jexcel/examples/currency-and-masking-numbers

Regards,

**Comment by mfakhrys** [comment]
Yes, I successfully gave unique attributes to each cell with your method.
But, when the header is clicked and table is resorted,
the attribute is reset and wrong attributes are given to each cell.

For example, 3 students with 3 quiz score:

STUDENT | QUIZ SCORE
--------- | ------
Cole | 70 (attr: data-student-id = 1, data-quiz-id=1)
Andy | 80 (attr: data-student-id = 2, data-quiz-id=1)
Zack | 90 (attr: data-student-id = 3, data-quiz-id=1)

But when resorted by name, it became:

STUDENT | QUIZ SCORE
--------- | ------
Andy | 80 (attr: **data-student-id = 1**, data-quiz-id=1)
Cole | 70 (attr: **data-student-id = 2**, data-quiz-id=1)
Zack | 90 (attr: data-student-id = 3, data-quiz-id=1)

When it was supposed to be: (notice the bold texts)

STUDENT | QUIZ SCORE
--------- | ------
Andy | 80 (attr: **data-student-id = 2**, data-quiz-id=1)
Cole | 70 (attr: **data-student-id = 1**, data-quiz-id=1)
Zack | 90 (attr: data-student-id = 3, data-quiz-id=1)

How do we make the attributes unique and unchangeable even after sorting?
Or if you don't have that feature yet, how do we disable sorting?

Thank you..

**Comment by pphod** [comment]
Why don't you save the id in one hiddden cell?

**Comment by mfakhrys** [comment]
I'm sorry but I don't understand what you mean..

Can you please elaborate it? With example perhaps..

Thank you for your time..

**Comment by pphod** [comment]
Use one column to keep your ids. You can define as readOnly so the user can't change it.
