### ISSUE TITLE
Formula feature not working

### ISSUE THREAD

**Issue by NinjaChristopher** [jspreadsheet/ce#411]
Hi,

When use the formula feature it keeps showing #ERROR. I noticed that the [examples](https://bossanova.uk/jexcel/v3/examples/spreadsheet-formulas) in the documentation are showing #ERROR as well.  So I am assuming it is an issue in the source code? Is this something that will be resolved shortly?

Btw, really appreciate your work, great tool!

**Comment by pphod** [comment]
It has been fixed ;)
