### ISSUE TITLE
V2 Deleting Rows Behavior

### ISSUE THREAD

**Issue by PRISMAY** [jspreadsheet/ce#413]
I ran into several issues with deleting a row or rows and can reproduce on the sample site linked below.
- I'm able to remove ALL rows (but not clear now to then insert a new row).  This can only be done when 2 or more rows exist and you highlight all and remove.
- Provide a clear way to insert a new row once all rows are removed or to NOT allow removal of all rows, i.e., one row must always exist.
- Cannot remove row at all if only row that exists.  I like this but should be consistent with above, i.e., don't allow removing all rows.

[jexcel example page](https://bossanova.uk/jexcel/v2/examples/working-with-the-data)

On the sample page above, if you remove all rows and then use the "Create ten rows at the end of the table" link, you won't see the new rows get created.  They're there but you have to sort a column before you see them.

**Comment by pphod** [comment]
Do you consider migrating to v3? The support v2 will be ceased no long from now.

**Comment by PRISMAY** [comment]
Hi Paul, yes, eventually we'll move to v3.  We actually tried v3 but ran into many issues in how we needed to implement it which is why we reverted back to v2. We figured we'd wait until v3 gets more stable. Thanks.
