### ISSUE TITLE
V3 GetData whitespace or zero being removed

### ISSUE THREAD

**Issue by jiwom** [jspreadsheet/ce#414]
If I enter in my table cell like "0000123" and run getData() it will just resturn the value "123" only.
This also applies with spaces like "         test      " will return "test".

**Comment by pphod** [comment]
Can you send a sample code you are using? If you are using column type: number, try to change to text.

**Comment by jiwom** [comment]
```
jexcel(document.getElementById('spreadsheet'), {
        data: data,
        columns: [
            {type: 'text', title: 'Rec'},
            {type: 'text', title: 'Pg'},
            {type: 'text', title: 'Months'},
            {type: 'text', title: 'Issueage'},
            {type: 'text', title: 'Split'},
        ],
        oninsertrow: insertRow,
        onselection: selectionActive,
        onchange: changed,
        allowInsertColumn: false,
        editable: true
    });
```

but when I enter inside the cell with leading zeros (ex.'000123') or spaces and call the jexcel.getData.. it is being cutoff (ex.'123'). It has the same behavior in you examples. I think it is a bug.

**Comment by pphod** [comment]
Ok, sorry understood. Well, actually it is not a bug. But, it is an automatic casting to Number. This is necessary to allow users to users formulas properly in text columns. In your case ' 00000123' will be converted to a number because of that.

**Comment by jiwom** [comment]
Is there a way to retain the '00000123' data from the cell? I have change the type to text and number but still same results. Thanks.
