### ISSUE TITLE
Updating data for formula's leading to Uncaught TypeError

### ISSUE THREAD

**Issue by NinjaChristopher** [jspreadsheet/ce#415]
![image](https://user-images.githubusercontent.com/47814808/60573712-7ec53300-9d78-11e9-981b-96675d5a735c.png)

The image above shows the table I am currently using where the yellow columns contain formula's. Updating the values in the white columns should therefore update the yellow column values. This works, up to a certain point. When I try to update some of the white cells I get the error:

Uncaught TypeError: Cannot read property '0' of undefined [jexcel.js:1558](https://bossanova.uk/jexcel/v3/jexcel.js) 
    at updateFormulaChain (jexcel.js:1558)
    at Object.obj.setValue (jexcel.js:1569)
    at Object.obj.closeEditor (jexcel.js:1446)
    at HTMLInputElement.editor.onblur (jexcel.js:1379)
    at HTMLDocument.jexcel.keyDownControls (jexcel.js:5736)

I wasn't able to figure out what was causing the error, I was hoping you could tell me whether it is something wrong on my end (although I think I did everything according to your documentation) or whether it is something that has to be fixed in the source code?

EDIT: The '0' changes depending on the cell I try to update. So e.g. sometimes it gives the error Uncaught TypeError: Cannot read property '5' of undefined

**Comment by pphod** [comment]
Can you create a jsfiddle with your table, please?

**Comment by NinjaChristopher** [comment]
https://jsfiddle.net/NinjaChristopher/ywjbn5s3/18/

**Comment by pphod** [comment]
It was due the readOnly directive. I have changed one thing and this will work fine. It will be in the master repository in 30 minutes.

**Comment by NinjaChristopher** [comment]
@paulhodel Really appreciate you looking into it! 

Unfortunately I am still encountering the issue, as you will be able to see in the JS fiddle. Is it already in the master repository? If so, maybe there is something else going on as well.

**Comment by NinjaChristopher** [comment]
@paulhodel Could you please reopen this issue and take another look at what may be causing this. I saw you made some changes, but unfortunately those did not resolve the problem as you can see in the JSFiddle. The same error appears.


`// Update formula chain
        var updateFormulaChain = function(x, y) {
            var cellId = jexcel.getColumnNameFromId([x, y]);
            if (obj.formula[cellId] && obj.formula[cellId].length > 0) {
                for (var i = 0; i < obj.formula[cellId].length; i++) {
                    var cell = jexcel.getIdFromColumnName(obj.formula[cellId][i], true);
                    // Update cell
                    var value = ''+obj.options.data[cell[1]][cell[0]]; <-- Uncaught TypeError: Cannot read property '0' of undefined
                    if (value.substr(0,1) == '=') {
                        records.push(obj.updateCell(cell[0], cell[1], value, true));
                    } else {
                        // No longer a formula, remove from the chain
                        Object.keys(obj.formula)[i] = null;
                    }
                    updateFormulaChain(cell[0], cell[1]);
                }
            }
        }
        updateFormulaChain(x, y);`

![image](https://user-images.githubusercontent.com/47814808/60789898-831a9300-a160-11e9-8a7f-7e24f6c91504.png)


Not sure whether this helps, but this is the line where I keep getting the uncaught type error. 

Really appreciate all the time and effort you're putting into this!

EDIT: Added screenshot

**Comment by pphod** [comment]
It has been fixed now.

**Comment by NomanChali** [comment]
> Not sure whether this helps, but this is the line where I keep getting the uncaught type error.

i am getting the same error

**Comment by NomanChali** [comment]
i got the cause of issue 
this is what i have done to fix the issue locally if by chance anyone wants to refer
```
var cell = jexcel.getIdFromColumnName(obj.formula[cellId][i], true);
if(obj.options.data[cell[1]]){ // added if condition to check obj.options.data[cell[1]]
	// Update cell
	var value = ''+obj.options.data[cell[1]][cell[0]];
	if (value.substr(0,1) == '=') {
		records.push(obj.updateCell(cell[0], cell[1], value, true));
	} else {
		// No longer a formula, remove from the chain
		Object.keys(obj.formula)[i] = null;
	}
}
```

**Comment by zehguilherme** [comment]
# I'm having a similar error
- It only occurs on `Google Chrome` and only with `numeric` values (column type -> numeric)
- [Version 4.7.3](https://bossanova.uk/jspreadsheet/v4/jexcel.js)

## First
```
Uncaught TypeError: Cannot read property 'substr' of undefined
    at Object.obj.closeEditor (jexcel.js:2075)
    at HTMLDocument.jexcel.mouseDownControls ([jexcel.js:7574](https://bossanova.uk/jspreadsheet/v4/jexcel.js))
```

### jexcel.js:2075

![image](https://user-images.githubusercontent.com/36301054/129416550-08a46842-c081-4429-b113-395a3b29a097.png)

### jexcel.js:7574

![image](https://user-images.githubusercontent.com/36301054/129416695-2919a2b8-e1c5-4e01-99e5-ed61512f1faf.png)

## Second

```
Uncaught TypeError: Cannot read property 'substr' of undefined
    at Object.obj.closeEditor (jexcel.js:2075)
    at HTMLTextAreaElement.editor.onblur ([jexcel.js:2031](https://bossanova.uk/jspreadsheet/v4/jexcel.js))
```

### jexcel.js:2075

![image](https://user-images.githubusercontent.com/36301054/129417208-3a817a06-8002-4bb6-8cac-a0ee27fe072b.png)

---

When I change the column's value, the table simply crashes and I can't do anything else.

![image](https://user-images.githubusercontent.com/36301054/129415713-5f846ea5-23c3-48b5-a578-32d7c4874801.png)

**Comment by 0Chan-smc** [comment]
In my case, remaining formula was the problem.

So I cleared formula by `sheet0.formual = []` when chnaging sheet data.
