### ISSUE TITLE
How to use Formulas in multisheets?

### ISSUE THREAD

**Issue by hqianbao** [jspreadsheet/ce#416]
How to use Formulas in multisheets? I want to do some formulas in multi sheets like excel. Is there some way to do it? Thanks a lot.

**Comment by pphod** [comment]
Do you mean cross formulas? If yes, that's not available in the CE version.

**Comment by ghost** [comment]
Paul, are cross-sheet formulas currently available in the pro version? If so, do you have an example?

**Comment by pphod** [comment]
Yes, this feature has been included in the new release that will be available in the next couple of weeks on Jexcel Pro v7 (www.jexcel.net/v7)

It will work just like excel:
=A1*Sheet1!B2

**Comment by ghost** [comment]
Perfect. Thanks, Paul!

**Comment by pablolima1** [comment]
How to use multisheets in HTML table?
