### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by seth-shaw-unlv** [jspreadsheet/ce#418]
The search example in [the documentation](https://bossanova.uk/jexcel/v3/examples/datatables) isn't working, nor does it work in my local test case.

On the documentation page my searches for 'Apple' and 'Delta' (both of which can be seen in the table) return no results.

Local tests fared no better. Searching for 'Monkey', 'Jazz', and 'Civic' on the spreadsheet created by the code below returned no results either.
```
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>jexcel Test</title>
    <script src="https://bossanova.uk/jexcel/v3/jexcel.js"></script>
    <script src="https://bossanova.uk/jsuites/v2/jsuites.js"></script>
    <link rel="stylesheet" href="https://bossanova.uk/jsuites/v2/jsuites.css" type="text/css" />
    <link rel="stylesheet" href="https://bossanova.uk/jexcel/v3/jexcel.css" type="text/css" />
  </head>
  <body>
    <div id="spreadsheet"></div>
    <script>
      var data = [
          ['Jazz', 'Honda', '2019-02-12', '', true, '$ 2,000.00', '#777700'],
          ['Civic', 'Honda', '2018-07-11', '', true, '$ 4,000.01', '#007777'],
          ['Civic', 'Honda', '2018-07-11', '', true, '$ 4,000.01', '#007777'],
          ['Monkey', 'Honda', '2018-07-11', '', true, '$ 4,000.01', '#007777'],
          ['Civic', 'Honda', '2018-07-11', '', true, '$ 4,000.01', '#007777'],
      ];
      spreadsheet = jexcel(document.getElementById('spreadsheet'), {
          data:data,
          search:true,
          columns: [
              { type: 'editor', title:'Car', width:120 },
              { type: 'dropdown', title:'Make', width:200, source:[ "Alfa Romeo", "Audi", "BMW", "Honda" ] },
              { type: 'calendar', title:'Available', width:200 },
              { type: 'image', title:'Photo', width:120 },
              { type: 'checkbox', title:'Stock', width:80 },
              { type: 'numeric', title:'Price', width:100, mask:'$ #,##.00', decimal:'.', multiple:true },
              { type: 'color', width:100, render:'square', }
           ]
      });
    </script>
  </body>
</html>
```

Is there some other configuration step I'm missing?

**Comment by upperleft** [comment]
I loaded it up as is and search works fine for me!

**Comment by seth-shaw-unlv** [comment]
Perhaps it is a browser version problem:

![Screen Shot 2019-07-03 at 9 20 54 AM](https://user-images.githubusercontent.com/29869988/60608249-dd3be280-9d73-11e9-85e3-9d8812d8952a.png)

OS X Version 10.14.5; Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by seth-shaw-unlv** [comment]
Also not working on Safari Version 12.1.1 (14607.2.6.1.1):

![Screen Shot 2019-07-03 at 9 22 09 AM](https://user-images.githubusercontent.com/29869988/60608348-1bd19d00-9d74-11e9-95d2-58bb480070be.png)

**Comment by seth-shaw-unlv** [comment]
Just tested Chrome Version 70.0.3538.77 (Official Build) (64-bit) on Windows 10 via Parallels which also did not work:

![Screen Shot 2019-07-03 at 9 25 44 AM](https://user-images.githubusercontent.com/29869988/60608640-c5b12980-9d74-11e9-80b5-bc12dacf01ab.png)

Chrome then auto-updated to Version 75.0.3770.100 (Official Build) (64-bit) and still did not work.

**Comment by seth-shaw-unlv** [comment]
@upperleft which browser/OS worked for you?

**Comment by pphod** [comment]
It has been fixed, will be available in the master repo in 30 min.
