### ISSUE TITLE
Feature Request: Long-text or HTML editor column type support

### ISSUE THREAD

**Issue by seth-shaw-unlv** [jspreadsheet/ce#419]
We have spreadsheets that often have very long text values such as titles and descriptions of images. I haven't found an obvious way to have a column wrap text or adjust the row height to display the full field value.

Also, since the existing columns are based on jSuite input types, it would be great to support the [mini text editor](https://bossanova.uk/jsuites/text-editor).

As a work-around I'm currently considering using a separate stand-alone field to act like Excel's formula bar for long-text entry that will copy in the value of the currently active field and save the value back  on a cell change. Do you know of any examples where others have done similar?

Thanks!

**Comment by pphod** [comment]
Long texts, please use wordWrap:true in the column directives. Instead of a input will be render a textarea.

https://bossanova.uk/jexcel/v2/examples/text-wrapping

This works in version 3 as well.

**Comment by pphod** [comment]
In regards to the HTML editor, I will consider for future releases. Thanks for the suggestion.

**Comment by pphod** [comment]
This has been implemented in both distributions with type: html

**Comment by pphod** [comment]
https://bossanova.uk/jexcel/v4/examples/richtext-html-editor
