### ISSUE TITLE
Using a calculated cell value in a formula cell

### ISSUE THREAD

**Issue by steveo2001** [jspreadsheet/ce#42]
http://bossanova.uk/jexcel/examples/including-formulas-on-your-spreadsheet

In cell C2 add:

=SUM(B1*C1)

C2 becomes 10000 which is great.

But then the total (cell C5) now has # ERROR

Looks like it can't calculate because there is a calculated cell in its range to calculate.

**Comment by pphod** [comment]
Try to change to

=B1*C1

SUM requires a second parameter, such:

=SUM(X1:X2)

**Comment by jets-** [comment]
Seems that # ERROR is because of the '=' character on C2.
C2 became a text and the formula cannot resolve reference

Sorry, my english isn't good
