### ISSUE TITLE
Clicking the top left cellshould select all cells

### ISSUE THREAD

**Issue by Pluckerpluck** [jspreadsheet/ce#420]
Excel has this functionality where by you can select all cells very quickly and easily.

You simply click the top-left most cell (i.e. the column header for the row numbers) and every cell should then be selected.

In my use case, this particularly makes copying out large amounts of data into Excel that little bit simpler.

**Comment by l0ckm4** [comment]
If you are using jquery in your code then you can target the first td and then use jexcel to select the cells.

```
$('#devplan table.jexcel tr:first td:first').click(function() {
    var mydata = devplan_table.getData();
    devplan_table.updateSelectionFromCoords(0,0,mydata[0].length-1,mydata.length-1);
});
```
where devplan is my div id and devplan_table was the javascript object from creating the jexcel table.

**Comment by pphod** [comment]
It has been done, it will available in the master repo in 30 min
