### ISSUE TITLE
Delete wrong selected row when jexcel have merged-cells .

### ISSUE THREAD

**Issue by TsePakKwan** [jspreadsheet/ce#422]
hi @paulhodel ,
I try to use jexcel v3 Merged cells function, then find a bug. 
delete wrong selected row when jexcel have merged-cells .
could you solve it?
https://bossanova.uk/jexcel/v3/examples/merged-cells

detail please refer below image.
![1562373245291](https://user-images.githubusercontent.com/51103712/60749181-52582380-9fd1-11e9-9fca-1ab706c3b47f.gif)

I think fix this error should be the cancel the merged-cells selection when on selection.

**Comment by qiuyinglanshan** [comment]
**+1**
I got the same problem.

When there are some merged cells in my spreadsheet, many columns or rows have the incorrect "**selected**" class.
eg.
`<td data-x="2" title="C" class="selected" style="text-align: left;">C</td>`

In addition, when the method **_getSelectedColumns(asIds)_** is called, all incorrect "**selected**" columns will be returned.

Therefore, when I delete some columns, the incorrect "**selected**" columns will be deleted at the same time.

**Comment by pphod** [comment]
Yes, I got the some here. I am working to fix that this weekend. thanks for spotting that out.

**Comment by pphod** [comment]
It has been fixed, it will be available in the master repo in 30min

**Comment by qiuyinglanshan** [comment]
Hi @paulhodel, thanks for your hard work, but there may be still some problems I think~
-- jExcel v3.3.1 copied from the master branch.

<img width="1437" alt="WechatIMG391" src="https://user-images.githubusercontent.com/6293093/60780302-73a34600-a170-11e9-890d-4620ac219b3e.png">

<img width="949" alt="WechatIMG392" src="https://user-images.githubusercontent.com/6293093/60780578-a7cb3680-a171-11e9-8b70-102565c1e186.png">

**Comment by pphod** [comment]
I found one other issue, that has been fixed. Hope all fine now.

**Comment by qiuyinglanshan** [comment]
> I found one other issue, that has been fixed. Hope all fine now.

Yes, it works.
Thanks a lot for your nice work and quick response.

**Comment by soinalastudio** [comment]
Inuse the last CE version. I have issue too with merged cells vertically, cannot remove all data or replace with setData.
