### ISSUE TITLE
Exporting json and csv data in textarea

### ISSUE THREAD

**Issue by D-Groenewegen** [jspreadsheet/ce#424]
Dear Paul Hodel,

First of all, thanks for this excellent feature/plugin. I was rather pleased to see that you released a major update.  

I was wondering if you could provide an updated example of the following, for v3

https://jsfiddle.net/paulhodel/62mwzknn/ 
(probably not working because of x-origin issues)

Also, can we include the headers in the export?

**Comment by pphod** [comment]
```
var my = jexcel(document.getElementById('my'), {
    csv:'https://bossanova.uk/components/bossanova-ui/demo/demo1.csv',
    csvHeaders:true,
    colWidths: [70, 200, 300],
});

$('#upload').on('click', function () {
  var data = my.getData();
	$('#txt').val($.csv.fromArrays(data));
})

$('#json').on('click', function () {
  var data = my.getData();
	$('#txt').val(JSON.stringify(data));
})
```

**Comment by pphod** [comment]
To export the headers:
my.getHeaders();

**Comment by D-Groenewegen** [comment]
Thanks. I haven't checked the headers yet, but using <...>.getData() works.
