### ISSUE TITLE
lazy-loading demo not working on Firefox

### ISSUE THREAD

**Issue by waldenn** [jspreadsheet/ce#426]
I see this error in the console (maybe not related) when running the [lazy-loading](https://bossanova.uk/jexcel/v3/examples/lazy-loading) demo:
```js
TypeError: window.dojoRequire is not a function    lazy-loading:203:8
```

Thanks for a great library!

**Comment by paulhodel** [comment]
It seems this message is not related to jExcel. ;)

**Comment by waldenn** [comment]
> It seems this message is not related to jExcel. ;)

What do you mean, this is your demo not working right? Should it not work across browsers?

**Comment by pphod** [comment]
It seems you are right, I have tested and there is something wrong on FF... I am on that. Thanks for spotting that out.

**Comment by waldenn** [comment]
Great thanks!

**Comment by pphod** [comment]
it has been fixed.
