### ISSUE TITLE
Disabling undo, redo

### ISSUE THREAD

**Issue by illyamarinov** [jspreadsheet/ce#427]
Hello, is there a way to disable the undo, redo functions due to the inability to manage them? (v3)

**Comment by pphod** [comment]
What do you mean by "inability to manage them"? I guess we can incorporate that in the next release

**Comment by TsePakKwan** [comment]
I think you can use ignoreHistory.
just like below example.
line 31>>table.ignoreHistory = true;
https://jsfiddle.net/tsepakkwan/tqhxuwpd/


> Hello, is there a way to disable the undo, redo functions due to the inability to manage them? (v3)

**Comment by illyamarinov** [comment]
> What do you mean by "inability to manage them"? I guess we can incorporate that in the next release

In my case, after creating the table, I set the comments for the cells, which shouldn't be editable, but it can be deleted simply by pressing "ctrl+z".

**Comment by ilyamarinov** [comment]
> I think you can use ignoreHistory.
> just like below example.
> line 31>>table.ignoreHistory = true;
> https://jsfiddle.net/tsepakkwan/tqhxuwpd/
> 
> > Hello, is there a way to disable the undo, redo functions due to the inability to manage them? (v3)

I tried your way, thanks, but unfortunately, it doesn't work, comments are still deleted by "ctrl+z"

**Comment by TsePakKwan** [comment]
> > I think you can use ignoreHistory.
> > just like below example.
> > line 31>>table.ignoreHistory = true;
> > https://jsfiddle.net/tsepakkwan/tqhxuwpd/
> 
> @TsePakKwan
> I tried your way, thanks, but unfortunately, it doesn't work, comments are still deleted by "ctrl+z"

@ilyamarinov 
Can you create a jsfiddle example?

**Comment by illyamarinov** [comment]
> @ilyamarinov
> Can you create a jsfiddle example?

@TsePakKwan 
 My bad, thanks a lot!) It works, I just set the comments after disabling the property.
