### ISSUE TITLE
The console show error while delete the row when the first column type  is"hidden".

### ISSUE THREAD

**Issue by TsePakKwan** [jspreadsheet/ce#428]
hi @paulhodel ,
I try to use jexcel v3 'hidden' type column.
The console show error while delete the row.
This happens is occur by when the first column type is "hidden" .
Could you solve it?

jexcel.js:2071 Uncaught TypeError: Cannot read property 'type' of undefined
    at Object.obj.updateSelectionFromCoords (jexcel.js:2071)
    at Object.obj.conditionalSelectionUpdate (jexcel.js:1850)
    at Object.obj.deleteRow (jexcel.js:3100)
    at HTMLLIElement.onclick (jexcel.js:5460)

detail please refer below example
https://jsfiddle.net/tsepakkwan/0xucfrah/10/
![1562741428701](https://user-images.githubusercontent.com/51103712/60948404-cc6c0d80-a32d-11e9-871a-539402c0c3c3.gif)

thanks your amazing project.

**Comment by pphod** [comment]
This has improved, and u removed the error. But I would suggest for better navigation hidden cells be placed in the end of the table.
