### ISSUE TITLE
[BUG][v3.0.1] Insert value starting with zero in column type: "text"

### ISSUE THREAD

**Issue by naseouser** [jspreadsheet/ce#429]
**Step to reproduce**

1. Go to [https://bossanova.uk/jexcel/v3/examples/column-types](https://bossanova.uk/jexcel/v3/examples/column-types)
2. In the first example, insert in cell A1 any value starting with 0 (example 012345)
3. Click anywhere outside the table
4. Double click on cell A1, as you would do if you want to edit it
5. The first zero will be dropped (example 012345 -> 12345)

Also, if you call jexcel.getData(), it will return the value as a number instead of as a string

**Comment by pphod** [comment]
This is not a bug, you come overcome that with a configuration

{ type: 'text', title: 'Your table', autoCasting: false } // The default is true

**Comment by naseouser** [comment]
I tried to use `autoCasting: false`, but when I double click on the cell it still drops the first zero
