### ISSUE TITLE
Validation of time, hours, days and totals

### ISSUE THREAD

**Issue by papyr** [jspreadsheet/ce#43]
Hi,  this is very nice.

I am trying to make an online version of the spreadsheet for a time card. The workers enter their hours, how can I ensure in a weekly time card:
 -------          `Cols->  Day1, day2,.. Sat.. Sun `  total hours by proj
Proj1                                                       
Proj2
..
totals by day `mondaytotal..`  `tudaytotal..` etc

1. Totals? how I can show totals on the right col for each project, and for days at the bottom
2. Validation? how to validate at 2 levels. _1)_ in each cell the only max of 23:99 number/time format can be entered.., and _2)_ the totals for each day cannot exceed 24 hours
3. Events, totals are auto updated as numbers are typed keyup?

**Comment by pphod** [comment]
Please find attach a example using numeralJs.
https://jsfiddle.net/paulhodel/7gsns0ny/

**Comment by papyr** [comment]
Hi @paulhodel  numerals does not work,

- [ ] How to do `HH:MM` **hours** and **mins** validation/formatting?


![image](https://user-images.githubusercontent.com/12733414/34328635-338b47a2-e8b2-11e7-818d-db2208b5e6fe.png)

**Comment by pphod** [comment]
Sorry, I don't know what happen but the link I have sent was a wrong one. Could you please try this.

https://jsfiddle.net/paulhodel/03d5rhzo/
