### ISSUE TITLE
F2 clears a cell?

### ISSUE THREAD

**Issue by Taapo** [jspreadsheet/ce#431]
I'm testing v3, and whenever I load data in the cell, and press F2 to "edit" the cell - the cell value is cleared, and I have to type in everything - which is different from for example Excel where the the original value is still visible and you can edit that value.

Am I overlooking a setting the documentation?

**Comment by Taapo** [comment]
I just tested compared to v2 - and where v3 clears the cell, in v2 the cell is acting like it should.

**Comment by pphod** [comment]
It has been fixed.
