### ISSUE TITLE
how to show both original column title(A, B, C, D....) and name title column we defined

### ISSUE THREAD

**Issue by caotoanbk** [jspreadsheet/ce#432]
Hi team
I'm new to jexcel v3.
I want to show  original column(A, B, C, D...) above named title column i defined, how i can do that?
Thank

**Comment by TsePakKwan** [comment]
> Hi team
> I'm new to jexcel v3.
> I want to show original column(A, B, C, D...) above named title column i defined, how i can do that?
> Thank

I think you can use NESTED HEADERS, example as below.
https://jsfiddle.net/tsepakkwan/25xv9tu8/

NESTED HEADERS doc.
https://bossanova.uk/jexcel/v3/examples/headers

**Comment by caotoanbk** [comment]
Many thanks!
