### ISSUE TITLE
Data entry won't start when the shift key is down

### ISSUE THREAD

**Issue by seth-shaw-unlv** [jspreadsheet/ce#433]
When on a selected cell of a spreadsheet I can start typing to invoke the editor _unless_ the shift key is down. For example, typing 'abc' will invoke the editor and start receiving the value 'abc' but if I start typing 'ABc' the editor is invoked only for the 'c' value (because I was holding the shift to type the first two as capital letters). This occurs with any character that uses the shift key (e.g. !,@,#,$,% and "). It requires me to type a lower-case character and then delete it (or use the mouse to double-click) before I can enter my text.

Side note, the spacebar doesn't invoke the cell editor either.

**Comment by TheNeverK** [comment]
This bug still occurs on current master. It happens because of the check on line 5841
https://github.com/paulhodel/jexcel/blob/2a4acea8337041c9bd9fb1387b36743292214935/dist/jexcel.js#L5840-L5843
Is it possible to change this bit to something like this 
```js
            } else {
                if ((e.ctrlKey || e.metaKey) && !e.shiftKey) {
                    if (e.which == 65) {
```
It seems to solve the problem.
