### ISSUE TITLE
Error occurs when undoing a deletion of a merged column.

### ISSUE THREAD

**Issue by qiuyinglanshan** [jspreadsheet/ce#439]
Hi @paulhodel , I got another issue about merged cells when undoing the deletion of a merged-cell column.
![bug_undo](https://user-images.githubusercontent.com/6293093/61045524-99994680-a40d-11e9-9f7a-abf3b0ba5b2a.gif)

In the function **historyProcessColumn(type, historyRecord)**:
I think `historyRecord.records[j][index]` for all records in a merged-cell may equal each other, but I'm not sure if it is the reason.

![image](https://user-images.githubusercontent.com/6293093/61046760-7f149c80-a410-11e9-83a6-751790be15c4.png)

**Comment by remi-crypto** [comment]
It would seem removeMerge is not being recorded in the history record. Thus when an undo is called, it does the last action pervious to the removeMerge.

One of my programers discovered that removeMerge is not supported with 'undo'.

**Comment by pphod** [comment]
That has been fixed on v4+, but v7 has a better approach for that. 
https://jexcel.net
