### ISSUE TITLE
How to get calculated value from a formula 

### ISSUE THREAD

**Issue by mchendriks** [jspreadsheet/ce#444]
getValue or getData gives for example "=B8*C8"  but I would like the calculated value of have an option wich one.

**Comment by pphod** [comment]
If you initiate the spreadsheet with copyCompatibility:true, it will behave export, copy, with values not formulas.

**Comment by Koushikphy** [comment]
I'm having the same problem, used `copyCompatibility:true` but still `getData()` giving the formula string

**Comment by Koushikphy** [comment]
```
var tab = jexcel(document.getElementById('spreadsheet'), {
    data:[[1,2,3,'=C1+10'],[1,2,3,4],[1,2,3,4]],
    copyCompatibility:true,
});
console.log(tab.getData()[0][3])
```
This prints `=C1+10` not `13`

**Comment by pphod** [comment]
Please, update from the master repository to use the getData. To get one cell only you can use:
tab.getValue('D1', true);

**Comment by Koushikphy** [comment]
But now with the updated version I can't use the corner drag to autofill/copy formulas

**Comment by pphod** [comment]
Yes, you can. Please take a look on the examples.
https://bossanova.uk/jexcel

**Comment by pphod** [comment]
Bear in mind to update jsuites as well.

**Comment by Koushikphy** [comment]
Okay, I used this https://github.com/jspreadsheet/ce/blob/master/dist and https://github.com/jsuites/jsuites/blob/master/dist files and used this 
`var tab = jexcel(document.getElementById('spreadsheet'), {
    data:[[1,2,3,'=C1+10'],[1,2,35,4],[1,2,12,4]],
    copyCompatibility:true,
});`
But now if I drag down from the corner of last column of the first row it fills as 14 and 15 instead of 45 and 22

**Comment by Koushikphy** [comment]
So, I kept `copyCompatibility:false` and used `myTable.records.map(x=>x.map(y=>y.innerHTML))` which gives the data for now.

**Comment by arif98741** [comment]
> So, I kept `copyCompatibility:false` and used `myTable.records.map(x=>x.map(y=>y.innerHTML))` which gives the data for now.

it works. thanks for the solution
