### ISSUE TITLE
Security related question - innerHTML

### ISSUE THREAD

**Issue by TheNeverK** [jspreadsheet/ce#447]
Hi, 
I have noticed that in v3, cell values are set using innerHTML. While this is a simple and flexible way, it also allows for very easy code execution. For example, entering this
```html
<span onclick="alert('test')">some text</span>
```
into a cell will call an alert every time it's clicked and hides this fact, because of the way it's rendered. Even more, to edit the cell and see that it may contain something suspicious a click is required. Have you considered any changes regarding this? Maybe just escaping characters would be enough?

**Comment by pphod** [comment]
[EDITED]
There are two new flags to deal with security.
stripHTML: true // will strip all HTML except when the column is the HTML type. Default: true
secureFormulas: true // will deal only with uppercase formulas/variables.

Those are just the first step to bring more security to the table when dealing with persistence. It is important never to trust any data that will be sent to the server-side.

Available on v4.2+
