### ISSUE TITLE
jExcel 3: Issue when using with Angular

### ISSUE THREAD

**Issue by vasicvuk** [jspreadsheet/ce#451]
Helper function **Array.prototype.injectArray** that is added to Array prototype causes Angular Observable Subscriptions to add injectArray function into existing collections.

For example i have API returning two items:
```
this.sampleService.getItems().subscribe((res) => {
console.log(res.items);
});
```

Before creating jExcel it retuns:
```
[{ "prop": "item1", "prop": "item 2"}, { "prop": "item1", "prop": "item 2"}]
```
After jExcel is initiated i get:
```
[{ "prop": "item1", "prop": "item 2"}, { "prop": "item1", "prop": "item 2"}, Function, Function, Function ...]
```
Where Function is pointing to injectArray.

As a temporary workaround i switched injectArray to local function and that resolved a problem but it would be better if jExcel does this also so i can use CDN version.

Destoying jExcel does not help.

Thanks

**Comment by pphod** [comment]
This has been fixed. Thanks for that.

Can I ask you a favor? Can you send us an example of jexcel + angular? We would love to add that on the documentation with all credits to you. ;)

**Comment by vasicvuk** [comment]
Is this released with version 3.0.1 or it will be in next version?

**Comment by pphod** [comment]
I have just deployed to the master repo. It will be a new tag soon.

**Comment by Mekonom** [comment]
Hi, I  implemented with angular 6.
in angular.json add 

` "scripts": [
...
              "node_modules/jexcel/dist/jexcel.min.js",
              "node_modules/jsuites/dist/jsuites.js"
            ]
   "styles": [
            ...
              "node_modules/jexcel/dist/jexcel.min.css",
              "node_modules/jsuites/dist/jsuites.css"
            ],`

in any component.ts  add 
`declare var jexcel: any; //declare jexcel type`
then you can use 
`    tubuExcel = jexcel(document.getElementById('my-spreadsheet'), {
      onchange : this.save,
      oninsertrow: this.insertrow,
      ondeleterow: this.deleterow,
    });
`
Also in component.html add
 `<div id="my-spreadsheet"></div>`

**Comment by sminch88** [comment]
what is tubuExcel? it's a const?

**Comment by pphod** [comment]
Sorry, I am not sure what do you mean.

**Comment by pphod** [comment]
Example using Angular
https://codesandbox.io/s/jexcel-and-angular-ej4u2
