### ISSUE TITLE
V2.1.0 Equals operation returns #ERROR when a cell is referenced as an operand

### ISSUE THREAD

**Issue by lucBoillat** [jspreadsheet/ce#452]
When using an **equals** operation in a formula, such as **=(A1==1)**, where A1 has the value 1, the cell with the formula returns #ERROR. This is reproducible on the website's [V2](https://bossanova.uk/jexcel/v2/docs/programmatically-changes) example table, whereas it returns 'true' in the [V3](https://bossanova.uk/jexcel/v3/examples/programmatically-updates) example.
**Steps to reproduce:**
- Add a new column in both examples using the button below the table
- In **E1** insert the value **1**
- In **E2** insert the expression **=(E1==1)**

**Outcome**
- V2 table returns **#ERROR**
- V3 table returns **true**

When not referencing a cell, but 2 numbers, the formula returns 'true' in the V2 example, so I assume using '==' as an operator is correct. When using another operator such as '<' it works as expected when referencing a cell, so it has to come down to the equal operator not working completely.

With this problem being on V2 and switching to V3 is currently out of scope for my project, is there a way to manually fix or patch this in one of the js files on my end? (excel-formula.min.js, formulas.js, jquery.jexcel.js)

**Comment by pphod** [comment]
in V2 there are third party libs that's does the parse from Excel-like formulas to JS formulas. You can try to take a look at those libs. I would recommend you migrate to jExcel. You can still use jQuery on v3.

https://bossanova.uk/jexcel/v3/examples/jquery

Depending on the level of customizations this can be easy or not. ;(
