### ISSUE TITLE
Context Menu in JQuery Tabs is too low

### ISSUE THREAD

**Issue by l0ckm4** [jspreadsheet/ce#453]
I think this was resolved about 23 days in version 3.0.5 detailed in issue #394 .  I have just downloaded v3.3.1 and the context menu is again too low when the table is created in a jquery tab.

![image](https://user-images.githubusercontent.com/5492828/61391400-89251800-a8b4-11e9-9c65-9122eca004b6.png)

**Comment by pphod** [comment]
It has been fixed (again).

**Comment by l0ckm4** [comment]
Thanks :-)
