### ISSUE TITLE
How to invoke column cell display refresh on dropdown/autocomplete update (v3)?

### ISSUE THREAD

**Issue by seth-shaw-unlv** [jspreadsheet/ce#454]
I need some way to tell the spreadsheet to refresh the display for a specific column.

Use Case: I have a spreadsheet and associated columns that are constructed from a series of calls to a REST API. As a result the source arrays for the dropdowns and autocompletes end up being populated or updated after the jExcel spreadsheet object has already been initialized. 

I've mocked up an example of this case ([github link](https://github.com/seth-shaw-unlv/islandora-jexcel-scratchpad/blob/rest-csv/autocomplete_quirk.html)):
```html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Test jExcel Dropdown Quirk</title>
    <script src="https://bossanova.uk/jexcel/v3/jexcel.js"></script>
    <script src="https://bossanova.uk/jsuites/v2/jsuites.js"></script>
    <link rel="stylesheet" href="https://bossanova.uk/jsuites/v2/jsuites.css" type="text/css" />
    <link rel="stylesheet" href="https://bossanova.uk/jexcel/v3/jexcel.css" type="text/css" />
  </head>
  <body>
    <div id="spreadsheet"></div>
    <script>
    // autoSource = [ {'id':'1', 'name':'Fruits'}, {'id':'2', 'name':'Legumes'}, {'id':'3', 'name':'General Food'} ];
    autoSource = [ {id:'1',name:'Fruits'} ];
    spreadsheetDiv = document.getElementById('spreadsheet');
    spreadsheet = jexcel(spreadsheetDiv, {
        data: [
                  ['Displays correctly because value is in source already.','1'],
                  ['Only "Fruits" displays at first. "Legumes" will appear after envoking the dropdown.','1;2'],
                  ['"General Food will appear after envoking the dropdown."','3'],
              ],
        columns: [
                    {
                        type: 'text',
                        title: 'Title',
                        width: 400,
                        wordWrap: true,
                        align: 'left'
                    },
                    {
                        type: 'autocomplete',
                        title: 'Test 1',
                        width: 200,
                        multiple: true,
                        source: autoSource
                    }
                ],
        minSpareRows: 1
    });
    //Mocking an async addition of dropdown values.
    autoSource.push({'id':'2', 'name':'Legumes'});
    autoSource.push({'id':'3', 'name':'General Food'});
    // **What can I do here to make the 'Test 1' column refresh cell displays?**

    // Example Async load of the dropdown. Even if the fetch is initiated 
    // at the top of the script, before the spreadsheet is, the fetch is still
    // slow enough that the dropdown additions will appear in the array after 
    // the spreadsheet is.
    // fetch('http://localhost:8000/jsonapi/taxonomy_term/subject')
    //     .then( (response) => response.json() )
    //     .then(function (terms) {
    //         terms.data.forEach(function (term) {
    //             // Add the term if it is NOT already in the dropdown.
    //             if (autoSource.findIndex( (existingTerm) => existingTerm.id === term.attributes.drupal_internal__tid) === -1) {
    //                 term = {
    //                     'name': term.attributes.name,
    //                     'id': term.attributes.drupal_internal__tid
    //                 };
    //                 autoSource.push(term);
    //             }
    //         });
    //     });
    </script>
  </body>
</html>
```

If you load the example in your browser you will see three populated rows. However, only the first one is correct. The other two populated rows include values in their autocomplete cells for items that are loaded _after_ the spreadsheet initializes. By double-clicking on the cells you will see that the relevant items are already selected, but they won't appear until the editor is opened and then closed.

So, how would I go about prompting the spreadsheet to update display for this column after executing the post-spreadsheet-initialization source array pushes?

**Comment by pphod** [comment]
Have you this? jExcel accepts remote json for remote dropdown source. If you have multiple remote source for dropdown jExcel will wait for all source being downloaded before render the table.

The second option you render the table in a callback of your ajax call.

```
    spreadsheet = jexcel(spreadsheetDiv, {
        data: [
                  ['Displays correctly because value is in source already.','1'],
                  ['Only "Fruits" displays at first. "Legumes" will appear after envoking the dropdown.','1;2'],
                  ['"General Food will appear after envoking the dropdown."','3'],
              ],
        columns: [
                    {
                        type: 'text',
                        title: 'Title',
                        width: 400,
                        wordWrap: true,
                        align: 'left'
                    },
                    {
                        type: 'autocomplete',
                        title: 'Test 1',
                        width: 200,
                        multiple: true,
                        url: 'http://localhost:8000/jsonapi/taxonomy_term/subject'
                    }
                ],
        minSpareRows: 1
    });
```

**Comment by seth-shaw-unlv** [comment]
The URL option doesn't work because the objects returned by the REST API don't use the same object properties for the options.

So, to do a column source update, I need to store the jExcel config object somewhere and export the current table data so that I can destroy and rebuild the whole table? (That seems a bit heavy handed.) Or is there a way to re-render specific cells?

**Comment by pphod** [comment]
Can you call your API and after you have all in memory you do a callback and render jexcel?

**Comment by seth-shaw-unlv** [comment]
There are several calls going out, although the mock-up doesn't reflect the complexity, and I don't know how to ensure they all complete before triggering the render.

I have three initial calls that I do and process together (one for the columns, another for additional column configurations, and another for the data). The call for the column definitions kicks off additional calls to populate the dropdowns (there can be several). I don't know how many fetches will be sent before hand to catch them all in the Promise object before the final render. (Granted, it could be that I just don't know the fetch and promise structure well enough. This is my first  Javascript project; most of my previous work is backend development.)

If you want to look at what I have going on right now (this is all still very experimental) you can see it [on github](https://github.com/seth-shaw-unlv/islandora-jexcel-scratchpad/tree/rest-csv). More specifically (since there are several proofs-of-concept included in that repo) see the [HTML](https://github.com/seth-shaw-unlv/islandora-jexcel-scratchpad/blob/rest-csv/restcsv.html) and the [initialize.js](https://github.com/seth-shaw-unlv/islandora-jexcel-scratchpad/blob/rest-csv/initialize.js). The [loadViewsFields function](https://github.com/seth-shaw-unlv/islandora-jexcel-scratchpad/blob/rest-csv/initialize.js#L154-L282) sends the first three fetches I mentioned and based on what fields it finds it calls my [updateDropdown function](https://github.com/seth-shaw-unlv/islandora-jexcel-scratchpad/blob/rest-csv/initialize.js#L27-L44) [here](https://github.com/seth-shaw-unlv/islandora-jexcel-scratchpad/blob/rest-csv/initialize.js#L247), which kicks off a number of fetches.

Although, now that I look at it again at your prompting, maybe I can have the updateDropdown function return an array of fetches and then do another Promise.all() call on them before the initial render.... I'm gonna need a spinner icon, I think.

Anyway, thanks for helping me think through this some more.

**Comment by seth-shaw-unlv** [comment]
I modified my code to [return promises from updateDropdown and then render the spreadsheet after they all complete](https://github.com/seth-shaw-unlv/islandora-jexcel-scratchpad/commit/0e4c3e1767fc4343a86c6e83b3ce904ae3a9b8ac). That did the trick. Thanks again, @paulhodel!

**Comment by pphod** [comment]
The spin icon is already include on the jsuites.

jSuites.loading.show()

After the callback you can invoke the hide
