### ISSUE TITLE
traceback when you use tableWidth in settings

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#455]
When you configure a `tableWidth` in settings you get a traceback:

> desktop.bundle.dll.js:311907 Uncaught TypeError: Cannot read property 'style' of undefined
>     at Object../node_modules/jexcel/dist/jexcel.js.obj.createTable (desktop.bundle.js:1340)
>     at Object../node_modules/jexcel/dist/jexcel.js.obj.prepareTable (desktop.bundle.js:1147)
>     at Object../node_modules/jexcel/dist/jexcel.js.obj.init (desktop.bundle.js:6166)

The problem lies in line 509 in `dist/jexcel.js`

> if (obj.options.tableWidth) {
>   el.content.style['overflow-x'] = 'auto';
>   el.content.style['width'] = obj.options.tableWidth;
> }

should be with `obj` instead of `el`

> if (obj.options.tableWidth) {
>   obj.content.style['overflow-x'] = 'auto';
>   obj.content.style['width'] = obj.options.tableWidth;
> }

**Comment by ghost** [comment]
I made a fix on my own fork. I am happy to make a PR if you like. However I assume there are other source files that you use to create the dist files. 

PR: https://github.com/saschal-j5int/jexcel/pull/1

**Comment by pphod** [comment]
Thanks, I will include that in our side.

**Comment by pphod** [comment]
It has been fixed. Thank you ;)

**Comment by ghost** [comment]
Great thanks however I just realized another difference

For tableHeight you use `obj.content.style.height` for tableWidth you use `obj.content.width` (Not the `style` property. Maybe you could change it to also use the `style` object to be consistent. 

Thanks:

```
if (obj.options.tableHeight) {
   obj.content.style['overflow-y'] = 'auto';
   obj.content.style.height = obj.options.tableHeight;
}
if (obj.options.tableWidth) {
  obj.content.style['overflow-x'] = 'auto';
  // use here obj.content.style instead of just obj.content
  obj.content.width = obj.options.tableWidth;
}
```
