### ISSUE TITLE
Inserting new rows twice causes Uncaught TypeError: Cannot read property '2' of undefined

### ISSUE THREAD

**Issue by l0ckm4** [jspreadsheet/ce#457]
Hi,

I have written a custom function called upon insertrow that merges some cells after the insert (to match the merge state currently in the table).

It works for the first insert but subsquent inserts generates an Uncaught TypeError and the merge fails.

```
Uncaught TypeError: Cannot read property '2' of undefined
    at Object.obj.updateTableReferences (jexcel.js:3625)
    at Object.tbl_tnd_ly_insertRow [as oninsertrow] ((index):230)
    at Object.obj.insertRow (jexcel.js:3000)
    at HTMLLIElement.onclick (jexcel.js:5451)
```

I have created a jsfiddle to demonstrate.  Try inserting rows two or more times after row 7 to see what I mean.

https://jsfiddle.net/fwmjat32/1/

**Comment by pphod** [comment]
This is what you want. I would suggest something: onbeforeinsertrow to avoid the undo thing.
https://jsfiddle.net/0ehtmgr3/

**Comment by pphod** [comment]
I have implement the onbeforeinsertrow when you can check your conditions and return false to block the progress of the method. One other thing I have change the method when calling the event, so you will be able to remove the set timeout. This will be available in the repository during this weekend.

**Comment by l0ckm4** [comment]
Stunning thank you :-)
