### ISSUE TITLE
F2 to replicate excel behaviour

### ISSUE THREAD

**Issue by felixvandal** [jspreadsheet/ce#46]
Hello Paul.
I would like to know if it was possible to press F2 to edit a cell like in Excel.
If not, will it be a futur feature?

**Comment by NithinKulal** [comment]
yess..

**Comment by pphod** [comment]
It has been done, updates on the master repository.

**Comment by felixvandal** [comment]
Hello paul thank you for the feature
when i press f2 the content of the cell is deleted
in your exemple the content is not deleted when you press f2
is there something i am missing?

**Comment by pphod** [comment]
The master repository has been updated to match excel behaviour.

**Comment by felixvandal** [comment]
the match for excel behaviour is good to go
thank you!

**Comment by NithinKulal** [comment]
But when I press F2, the whole content of the cell is removed.








*-------------------------------------    Thanks & Regards*
*       Nithin Kumar D*

**Comment by pphod** [comment]
You don't have the most recent version. Please update from the repository.
