### ISSUE TITLE
Feature Request: Marching Ants on Copy

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#460]
**Replicate**
1. Visit https://bossanova.uk/jexcel/v2/examples
1. Click **Classe A**.
1. Hold `Shift` and tap `Down` arrow twice to select the first three rows.
1. Release the `Shift` key.
1. Press `Ctrl+C`.

**Actual Results**
All three rows are copied.

**Expected Results**
All three rows are copied and copied cells display marching ants to indicate what cells have been copied.

**Additional Details**
See the following for CSS marching ants styling examples:

* https://www.codeseek.co/pixelass/pure-css-marching-ants-border-cdrwI ([view demo](https://www.codeseek.co/preview/cdrwI))
* https://codepen.io/danichk/pen/PPRxrR

Dashed lines (not animated) are also another way to visually depict the copied cells.

**Comment by pphod** [comment]
Great idea! We should bring that onboard soon. Thanks

**Comment by Zireael** [comment]
SCSS example:
https://codepen.io/stg/pen/YGRpkJ

simple CSS example:
https://codepen.io/danichk/pen/PPRxrR

**Comment by pphod** [comment]
I have implement that in Both v4 and v5. In v5, with some animation. www.jexcel.net/v5
