### ISSUE TITLE
Downloading with headers.

### ISSUE THREAD

**Issue by illyamarinov** [jspreadsheet/ce#464]
Hello, @paulhodel. I got issue when need to download a table with headers. I checked the example (https://bossanova.uk/jexcel/v3/examples/import-data), but even in that example headers don't download with the table.
Example in the second version (https://bossanova.uk/jexcel/v2/examples/creating-a-table-from-an-external-csv-file) works fine.
I'm using "download()" method and "csvHeaders: true" property, but it not works.
Please help)

**Comment by pphod** [comment]
Please use:
table.download(true);

Please bear in mind: if you are using formulas THIS can cause problems in the formulas references since the first ROW should be not counted.

**Comment by NomanChali** [comment]
yes if we are using formulas THIS can cause problems in the formulas references since the first ROW should be not counted.

so if we change the copy method return statement like below.

line no `5247` 
`return str;` to `return strLabel` 
then it works fine.
It return calculated value not formula which resolved the problem

**Comment by pphod** [comment]
You don't need to change the code. You can use copyCompatibility: true to parse the formulas before downloading.

**Comment by NomanChali** [comment]
yes i i tried by setting copyCompatibility: true but still i face formula parsing problem

you check here : https://jsfiddle.net/e6nbajfk/

**Comment by NomanChali** [comment]
> You don't need to change the code. You can use copyCompatibility: true to parse the formulas before downloading.

yes i i tried by setting copyCompatibility: true but still i face formula parsing problem

you check here : https://jsfiddle.net/e6nbajfk/
