### ISSUE TITLE
get number of rows

### ISSUE THREAD

**Issue by lerdalaa** [jspreadsheet/ce#466]
Is there a way to do something like this?

=SUM(A1:A(n-1)) where n is the total number of rows

**Comment by pphod** [comment]
No, that's not possible, but you can create a custom method that can does the trick.
=SUMALL()

In the global namespace you can define

function SUMALL() {
   var numRows = yourinstance.options.data.length;

   var total = 0;
   for (var i =0; i < numRows; i++) {
       total += yourinstance.getValue('A'+i);
   }

   return total;
}

**Comment by lerdalaa** [comment]
Thanks! table.options.data.length was what I was looking for!

**Comment by jiangxiaoqiang** [comment]
I have tried this way but did not get the rows count:


```
const rowNum = spreadsheet.row.length;
        const rowCount = spreadsheet.getRowData.length;
        const r = spreadsheet.table.rows.length;
```


how to get the rows count? I am using `"jspreadsheet-ce": "^4.13.4"`
