### ISSUE TITLE
Error when trying to replay results from getMerge

### ISSUE THREAD

**Issue by l0ckm4** [jspreadsheet/ce#469]
I am storing the table data, styles and merge information from the getData(), getStyles() and getMerge() functions in a SQL database. When I try to restore the table I can setData (after having to destroyMerge), setStyle without issues.  BUT, as I had to destroyMerge I need to replay the results from getMerge and this is where I am struggling. I am trying to iterate over the object by using the following code:-

```
tbl_eoy_ly.destroyMerged();
tbl_eoy_ly.setData(msg["EOY_LY"]["Data"]);
tbl_eoy_ly.setStyle(msg["EOY_LY"]["Style"]);
for (let [i, element] of Object.entries(msg["EOY_LY"]["Merge"])) {
   console.log("Setting "+i+' - '+element[0]+':'+element[1]);
   tbl_eoy_ly.setMerge(i,element[0],element[1]);
   console.log("Completed "+i);
}
```
The first few records work but then I get the following uncaught error.
```
Setting A1 - 15:2
Completed A1
Setting A3 - 15:1
Completed A3
Setting A4 - 2:2
Completed A4
Setting C4 - 5:2
jexcel.js:1620 Uncaught TypeError: Cannot read property 'classList' of undefined
    at Object.obj.updateCell (jexcel.js:1620)
    at Object.obj.setMerge (jexcel.js:1079)
    at Object.<anonymous> (<anonymous>:35:17)
    at fire (jquery-3.4.1.js:3291)
    at Object.fireWith [as resolveWith] (jquery-3.4.1.js:3421)
    at done (jquery-3.4.1.js:9533)
    at XMLHttpRequest.<anonymous> (jquery-3.4.1.js:9785)
```
my line numbers may be a little out as I have made a couple of amendments but line 1620 on my version is 

`if (obj.records[y][x].classList.contains('readonly') == true && ! force) {`

If I separate and call setMerge manually (i.e. not in a loop) then it works fine weirdly although the console.log's suggest I am trying to set the same and in the same order.

```
tbl_eoy_ly.setMerge("A1",15,2);	tbl_eoy_ly.setMerge("A3",15,1); tbl_eoy_ly.setMerge("A4",2, 2); 
tbl_eoy_ly.setMerge("C4",5, 2);  tbl_eoy_ly.setMerge("A6",2, 2); tbl_eoy_ly.setMerge("C6",5, 2);
tbl_eoy_ly.setMerge("A8",2, 2); tbl_eoy_ly.setMerge("C8",5, 2); tbl_eoy_ly.setMerge("H4",3, 2); 
tbl_eoy_ly.setMerge("K4",5, 2); tbl_eoy_ly.setMerge("H6",3, 2); tbl_eoy_ly.setMerge("K6",5, 2);
tbl_eoy_ly.setMerge("H8",3, 2); tbl_eoy_ly.setMerge("K8",5, 2); tbl_eoy_ly.setMerge("A10",7,1);
tbl_eoy_ly.setMerge("H10",8,1); tbl_eoy_ly.setMerge("A11",15,1);tbl_eoy_ly.setMerge("A12",15,1);			
tbl_eoy_ly.setMerge("A13",15,1);tbl_eoy_ly.setMerge("A14",15,1);tbl_eoy_ly.setMerge("A15",9,1);  
tbl_eoy_ly.setMerge("J15",6,1); tbl_eoy_ly.setMerge("A16",9,1); tbl_eoy_ly.setMerge("J16",6,1);
tbl_eoy_ly.setMerge("A17",9,1); tbl_eoy_ly.setMerge("J17",6,1); tbl_eoy_ly.setMerge("A18",9,1);  
tbl_eoy_ly.setMerge("J18",6,1); tbl_eoy_ly.setMerge("A19",9,1); tbl_eoy_ly.setMerge("J19",6,1);
tbl_eoy_ly.setMerge("A20",9,1); tbl_eoy_ly.setMerge("J20",6,1); tbl_eoy_ly.setMerge("A21",9,1);  
tbl_eoy_ly.setMerge("J21",6,1); tbl_eoy_ly.setMerge("A22",15,1);tbl_eoy_ly.setMerge("A23",15,4);
tbl_eoy_ly.setMerge("A27",15,1);tbl_eoy_ly.setMerge("A28",15,1);tbl_eoy_ly.setMerge("A29",5,2);  
tbl_eoy_ly.setMerge("F29",5,2); tbl_eoy_ly.setMerge("K29",5,2); tbl_eoy_ly.setMerge("A31",5,4);  
tbl_eoy_ly.setMerge("F31",5,4); tbl_eoy_ly.setMerge("K31",5,4); tbl_eoy_ly.setMerge("A35",5,4);  
tbl_eoy_ly.setMerge("F35",5,4); tbl_eoy_ly.setMerge("K35",5,4); tbl_eoy_ly.setMerge("A39",5,3);  
tbl_eoy_ly.setMerge("F39",5,3); tbl_eoy_ly.setMerge("K39",5,3); tbl_eoy_ly.setMerge("A42",5,4);  
tbl_eoy_ly.setMerge("F42",5,4); tbl_eoy_ly.setMerge("K42",5,4); tbl_eoy_ly.setMerge("A46",15,1);			
tbl_eoy_ly.setMerge("A47",15,1);tbl_eoy_ly.setMerge("A48",15,1);tbl_eoy_ly.setMerge("A49",15,1); 		
tbl_eoy_ly.setMerge("A50",15,1);tbl_eoy_ly.setMerge("A51",15,1);tbl_eoy_ly.setMerge("A52",15,1);
tbl_eoy_ly.setMerge("A53",3,1); tbl_eoy_ly.setMerge("A54",3,2); tbl_eoy_ly.setMerge("D53",12,3);
tbl_eoy_ly.setMerge("A56",15,1);tbl_eoy_ly.setMerge("A57",3,3); tbl_eoy_ly.setMerge("D57",12,3);
tbl_eoy_ly.setMerge("A60",15,1);
```

What would be nice is to have the same functionality as setStyle and setData where you can supply a table wide object/array to set all in one call but if someone can help with the error I am currently getting then that would be great.

**Comment by pphod** [comment]
Please use getConfig it will bring everything you need.

**Comment by l0ckm4** [comment]
Thanks, How would I apply the whole config to the existing table ie once retrieved from the database?

**Comment by pphod** [comment]
jexcel(element, config)

**Comment by l0ckm4** [comment]
Thank Paul,  I wrote a little function to simply get the config, wipe the current table and then rebuild it.

```
function testme() {
   var config = tbl_eoy_ly.getConfig();
   tbl_eoy_ly.destroyMerged();
   tbl_eoy_ly = null;
   $('#eoyr_ly').html('');
   tbl_eoy_ly = jexcel(document.getElementById('eoyr_ly'),config);
 }
```
Without the destroyMerged I get an error for each Merged Cell in the table and the end result is a lot of clicks on alerts and then a table with no merged cells.

With the destroyMerged, the end result is the same although I do not get any alerts.

Am I doing something wrong here?

**Comment by l0ckm4** [comment]
I have created a jsfiddle to demonstrate if it helps :-)

https://jsfiddle.net/l0ckm4/h8bpdutj/24/

**Comment by pphod** [comment]
I found the problem and have fixed. The correct way to do it.

var config = yourtable.getConfig();
jexcel(document.getElementById('id'), config);

You don't need to destroy, destroyMerge nothing. It will be in the master repo in 30 min.

**Comment by l0ckm4** [comment]
Hi Paul.

It works but I still need to destroy the table otherwise I get two tables with the original locked.

https://jsfiddle.net/l0ckm4/h8bpdutj/27/

If i do a destroy before the re-initialise then it works.

https://jsfiddle.net/l0ckm4/h8bpdutj/28/

Thanks for the great code and the amazing support - it is much appreciated.
