### ISSUE TITLE
Select Multiple Dropdowns

### ISSUE THREAD

**Issue by zbyte64** [jspreadsheet/ce#47]
Want to add a dropdown option to allow selecting multiple values. The data for the column will be treated as an array filled with the selected values.

**Comment by TiagoSilvaPereira** [comment]
+1 is there a way to make it?

**Comment by sharon-elihis** [comment]
+1 ; I don't need it at the moment but sounds useful.

**Comment by pphod** [comment]
This will be released included in the next release. Should be available in the next couple of weeks... v1.6.0

**Comment by kcdbaba** [comment]
+1 looking forward to v1.6.0

**Comment by pphod** [comment]
We have jump to the version 2.0.0 because several other features including the multiple dropdown option. ;)
