### ISSUE TITLE
jexcel not update formula when delete row

### ISSUE THREAD

**Issue by caotoanbk** [jspreadsheet/ce#471]
Hi, I have cell have value "=SUM(F1:F23)", when i insert new row the formulas automatic change to "=SUM(F1:F24)", but when I delete a row it still "=SUM(F1:F23)", and because row 23 not exists, it causes error "too many excecutions..." in debug console and jexcel stop working
Anyone help me! Thanks

**Comment by pphod** [comment]
Can you create that on jsfiddle?

**Comment by caotoanbk** [comment]
Hi Paul, i don't understand when i created on jsfiddle, it doesn't happen (it doesn't update the formulas and sometimes in my side ), but i found alternative solution for my problem. Thanks!
