### ISSUE TITLE
Cannot resize column on firefox

### ISSUE THREAD

**Issue by jbl2024** [jspreadsheet/ce#472]
Hello,

on firefox (68.0.1 (64 bits) for Mac), the resize column feature is broken : you can shrink a column but cannot expand it.

**Comment by ghost** [comment]
1. Visit https://bossanova.uk/jexcel/v2/docs/programmatically-changes
1. Resize **Date** column.

Works in Firefox 68.0.1 (64-bit) on X11 (Linux/XFCE4).

**Comment by jbl2024** [comment]
You are right, but in your example, the version of jexcel is v2, not v3 (which is as far as i know a complete rewrite from previous version)

Can you confirm this issue with https://bossanova.uk/jexcel/v3/examples/datatables ?

**Comment by pphod** [comment]
it has been fixed. Available in the master repo as pre 3.3.4
