### ISSUE TITLE
Update quick reference page to indicate tableHeight/tableWidth are CSS properties

### ISSUE THREAD

**Issue by jniles** [jspreadsheet/ce#473]
The [quick reference page](https://bossanova.uk/jexcel/v3/docs/quick-reference) states that the `tableHeight` and `tableWidth` properties take an integer, when they actually take a CSS property.  Putting `300` won't do anything, but `300px` will, as will `75vh`, for example.

Not sure where to update the documentation or I'd put in a PR for it.

**Comment by pphod** [comment]
Great, thanks! It has been updated. It will available online in 30 min
