### ISSUE TITLE
The tableWidth property is broken

### ISSUE THREAD

**Issue by jniles** [jspreadsheet/ce#474]
It looks like the `tableWidth` property is broken.  [This line (L518)](https://github.com/paulhodel/jexcel/blob/master/dist/jexcel.js#L518) should set the style width, not the content width.  The current and fix are pasted below:
```js
// current
 obj.content.width = obj.options.tableWidth;

// fixed
 obj.content.style.width = obj.options.tableWidth;
```

For comparison, this is how the `tableHeight` is set in [L514](https://github.com/paulhodel/jexcel/blob/master/dist/jexcel.js#L514).

**Comment by pphod** [comment]
Brilhant! Thank you for spotting that. It should be updated in 30 min in the master repository.
