### ISSUE TITLE
Feature request: Extend keycodes from number pad (plus, minus, decimal point)

### ISSUE THREAD

**Issue by debrouchee** [jspreadsheet/ce#475]
Hi, great plugin, nice work!

I suggest to extend the keycodes for inputs. The keys "plus", "minus" and "decimal point" on the number pad are not included.

The keycodes are:
plus: 107
minus: 109
decimal point: 110

Add the following line to jexcel.js, row 6025 (Version 3.3.2):

`(e.keyCode >= 107 && e.keyCode <= 110) ||`

**Comment by seitenschaffer** [comment]
In addition to my request you could at another key-support:

backspace: 8

Replace the following line in jexcel.js, row 5929 (Version 3.3.2):

`} else if (e.which == 8 || e.which == 46) {`

**Comment by pphod** [comment]
it has been done, it will be in 30 min in the master repository
