### ISSUE TITLE
Freeze first two columns in jexcel table

### ISSUE THREAD

**Issue by Suragala** [jspreadsheet/ce#476]
Hi Paul,

I want to freeze the first two columns in my jexcel table.
Please let me know how can I do it?

Also, I want to set the back ground color for my jexcel table. How to do this?

I want to download the jexcel table data as an excel file. Is there any option in jexcel for the same?

**Comment by pphod** [comment]
Sorry, the freeze columns are not available. Change color of the table you can see a few examples here:

https://bossanova.uk/jexcel/v3/examples/table-style

**Comment by pphod** [comment]
You can download a CSV file. An example:
https://bossanova.uk/jexcel/v3/examples/import-data

**Comment by Suragala** [comment]
Hi Paul,
The download functionality is still not working.
When I click on the download button, I get the below url :
http://localhost:5000/67f3ca53-5c16-4d4b-8aa8-6141edde25f5

and nothing downloads.

Can you let me know what is failing here?

**Comment by pphod** [comment]
Sorry, I do not have access to your localhost.

**Comment by pphod** [comment]
https://jexcel.net/v4/examples/freeze-columns
