### ISSUE TITLE
is there any event for insert row before or insert row after?

### ISSUE THREAD

**Issue by caotoanbk** [jspreadsheet/ce#478]
Hi, how i can handle event when insert row after or insert row before?

**Comment by TsePakKwan** [comment]
please read doc. 
https://bossanova.uk/jexcel/v3/docs/events
has event when insert row after `oninsertrow `

oninsertrow | After a new row is inserted.

**Comment by caotoanbk** [comment]
hi, i means "Insert a row after", "Insert a row before" when right-click on jexcel table .Thanks

**Comment by pphod** [comment]
You have two 2 methods:

onbeforeinsertrow
oninsertrow

You can define a method that will handle your event in case an insertMethod is invoked.

The onbeforeinsertrow should return true or false. The latter in case you would like to cancel the insert command.
