### ISSUE TITLE
Can't freeze column headers as well as selected column

### ISSUE THREAD

**Issue by NithinKulal** [jspreadsheet/ce#48]
Freezing column headers as well as selected column is not available in this plugin.. Please add this feature

**Comment by avj2352** [comment]
Hi,
I am facing the same issue with jExcel plugin. Cannot fix/limit the rows and columns to what i retrieve from my data array. Also, on right-clicking the cell I see the options
1. Add New Row
2. Add New Column

Is there a workaround/configuration to prevent this ?

**Comment by pphod** [comment]
You can initiate your table with options like that.

            allowInsertRow:true,
            // Allow new rows
            allowManualInsertRow:true,
            // Allow new columns
            allowInsertColumn:true,
            // Allow new rows
            allowManualInsertColumn:true,
            // Allow row delete
            allowDeleteRow:true,
            // Allow column delete
            allowDeleteColumn:true,
