### ISSUE TITLE
Disable Tab and Enter Click Events in Jexcel Grid

### ISSUE THREAD

**Issue by JayatirthaJoshi** [jspreadsheet/ce#486]
Dear All,

For Ex: if i have a grid with 2 Columns Column1, column2, and mouse is focused on Column2,
and when we click tab a new column is getting created, let me know how to disable this

and on clicking Enter a new Row is getting is created, let me know how to disable this.

Regards
Jay

**Comment by pphod** [comment]
You can initiate your table using the following:

        // Allow new rows
        allowInsertRow:true,
        // Allow new rows
        allowManualInsertRow:true,
        // Allow new columns
        allowInsertColumn:true,
        // Allow new rows
        allowManualInsertColumn:true,
