### ISSUE TITLE
How to make some columns fixed when scroll horizontally?

### ISSUE THREAD

**Issue by caotoanbk** [jspreadsheet/ce#488]
Hi, I want to fix some column when scroll horizontally like in excel, how i can do that? Thanks

**Comment by caotoanbk** [comment]
Sorry, I found the same issue at #161, thanks

**Comment by Suragala** [comment]
Hi caotoanbk,

Can you tell me how you implemented column freeze using table header fixer.
Can you provide some jsfiddle code that you used?
