### ISSUE TITLE
executeFormula

### ISSUE THREAD

**Issue by javg15** [jspreadsheet/ce#493]
When I execute setValue with a negative value, if exists some formula containing the cell affected, then the result is positive, only until enter in edit mode to the cell previously asigned with setValue, is when correctly updated correctly the cell contanining the formula

I edited the file: jexcel.js in the line 4036

number[0] = number[0].match(/[0-9]*/g).join('');
to
number[0] = number[0].match(/[+-]?[0-9]*/g).join('');

**Comment by pphod** [comment]
Make sense, it has been included in the master repository.

**Comment by javg15** [comment]
Then, the line 4041 too

if (number[0] != ''  && Number(number[0]) >= 0){
to
if (number[0] != '' ) {
