### ISSUE TITLE
update column type dropdown cause error 'cannot read property getAttribute from undefined'

### ISSUE THREAD

**Issue by caotoanbk** [jspreadsheet/ce#494]
Hi, when i chooses different value of a column type: dropdown, it causes the error like in the image show below
![jexcel-error](https://user-images.githubusercontent.com/10071017/62097622-9e854380-b2b1-11e9-9333-d003e5fa8736.png)
Can anyone tell me what i am doing wrong?Thanks (Sorry about my english)

**Comment by pphod** [comment]
Can you create a jsFiddle of that, please?

**Comment by caotoanbk** [comment]
thank you, i found my problem , i created array data by use php function json_encode data  get from json file, it also encoded some character in my language so the value in array data pass to jexcel different from dropdown source, when i used `url: 'somefile.json`, it worked. Thanks
