### ISSUE TITLE
bug: keyboard navigation after doing search

### ISSUE THREAD

**Issue by daonsh** [jspreadsheet/ce#495]
In the search and pagination example:

https://bossanova.uk/jexcel/v3/examples/datatables

if we make a search (e.g. type ELEC in search box),
and then try to navigate down using the keyboard, the selected cell  disappears, spreadsheet becomes empty, and we can see negative page numbers.

![image](https://user-images.githubusercontent.com/15046011/62112490-7b5f9180-b2bb-11e9-987e-372d6ce69da5.png)

**Comment by pphod** [comment]
Thanks for spotting that out. It has been fixed.
