### ISSUE TITLE
Update table for dynamic data

### ISSUE THREAD

**Issue by Swechhya** [jspreadsheet/ce#498]
Is there a way to update the whole table including number of rows and columns, column headers etc. for dynamic data?

**Comment by pphod** [comment]
jexcel(domId, options)

You can save options and then use again later to recreate the table. To get options, you call xxx.getConfig()

**Comment by Swechhya** [comment]
The following is the code that I am using:
```
<html>
<script src="https://bossanova.uk/jexcel/v3/jexcel.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jexcel/v3/jexcel.css" type="text/css" />

<script src="https://bossanova.uk/jtools/v2/japp.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jtools/v2/japp.css" type="text/css" />

<div id="spreadsheet"></div>

<script>
var data = [
    ['Mazda', 2001, 2000],
    ['Pegeout', 2010, 5000],
    ['Honda Fit', 2009, 3000],
    ['Honda CRV', 2010, 6000],
];


jexcel(document.getElementById('spreadsheet'), {
    data:data,
    columns:[
        { title:'Model', width:300 },
        { title:'Price', width:80 },
        { title:'Model', width:100 }
    ],
});
</script>
<input type='button' value='Update data' onclick="jexcel(document.getElementById('spreadsheet'),{
data: [
['A', 10],
['B', 20],
],
 columns:[
        { title:'Letter', width:300 },
        { title:'Number', width:80 }],
})">

</html>
```
On clicking the update data button, instead of the data being updated on the table I get two tables as follows:
<img width="651" alt="Screen Shot 2019-07-30 at 18 06 26" src="https://user-images.githubusercontent.com/6251412/62128783-de214f00-b2f4-11e9-90f8-6bdf140df23b.png">

**Comment by pphod** [comment]
Sure you must clear your table first. document.getElementById('spreadsheet').innerHTML = '';

**Comment by Swechhya** [comment]
Actually, clearing the innerHTML and then updating the table would remove currently selected cell which from user perspective is slightly inconvenient. I was wondering if there was any method that could be called to update the table.

**Comment by pphod** [comment]
There is a method to re-apply the selection.

Before destroy the table
var  selection  = yourtable.selectedCell;

// After you create the table (consider that on the onload method)
yourtable.updateSelectionFromCoords(selection);

**Comment by Swechhya** [comment]
Thanks @paulhodel , that's a great solution. I was hoping if there could be a function like `setTable` that would clear the replace the current table with a new table.

**Comment by pphod** [comment]
You don't need to change the whole table if you change only the data. For that you have setData.

Regards,

**Comment by shroffritesh** [comment]
Hi paul,
Is there any way, when we insert data into excel sheet that time data will store dynamically into : 
 jexcel(document.getElementById('spreadsheet'){
        data : data ,   <------------------
 }

**Comment by data-handler** [comment]
> You don't need to change the whole table if you change only the data. For that you have setData.
> 
> Regards,

When I use setData to update an existing table instance, the correct number of columns and rows are rendered, but the cell contents are empty. I've tried the refresh method but same result. What am I doing wrong?
