### ISSUE TITLE
autocomplete flicker occurs / and solution!

### ISSUE THREAD

**Issue by Quero86** [jspreadsheet/ce#50]
Autocomplete:

You clear the HTML , then call the Ajax. Better clear the HTML after you have some Returns. Otherwise you have some flicker occurs.

Example:
Move Line 1447 : $(result).html('');  to Line 1451 inside the getJSON , before you call showResult. Or just move it to "showResult".

**Comment by pphod** [comment]
You are right. The behaviour has been changed, please update from master.
