### ISSUE TITLE
jexcel v3 fails in IE 11

### ISSUE THREAD

**Issue by Lockey45** [jspreadsheet/ce#500]
It appears v3 does not work with IE 11.  The spreadsheet on the v3 main documentation page (URL: https://bossanova.uk/jexcel/v3/ ) does not render in IE 11.

I have verified this failure by copying the code on this page to a local page.  I also get the same error in IE on any webpage referencing Jexcel 3.

The IE Developer tool always reports 2 errors:

SCRIPT1002: Syntax error
File: jsuites.js, Line: 2826, Column: 72

SCRIPT5007: Unable to get property 'contextmenu' of undefined or null reference
File: jexcel.js, Line: 451, Column: 9

**Comment by pphod** [comment]
This has been fixed. You should update both jexcel and jsuites. Both are going to be available in the respective master repositories.
