### ISSUE TITLE
feature request: numeric input as <input type='number'>

### ISSUE THREAD

**Issue by daonsh** [jspreadsheet/ce#501]
How about making better mobile experience for numeric columns by simply using the default html5 number input type?

By putting <input type='number'> we should have small arrows to increase/decrease the number in the field by 1. Should automatically work on mobile.

See for example
https://www.tjvantoll.com/2012/07/15/native-html5-number-picker-vs-jquery-uis-spinner-which-to-use/

**Comment by pphod** [comment]
Sorry, but his won't be possible due problems with mask for example or any special characters might be found numbers.

**Comment by jimmywarting** [comment]
+1 for number input
