### ISSUE TITLE
Bug Incorrect Cell updated with SetValue via numeric IDs

### ISSUE THREAD

**Issue by AO-TERRA** [jspreadsheet/ce#503]
With the update from V2 to V3 there does not appear to be a way to reliably update cells based on column + row numerical IDs anymore.

While setValue seems to work well enough with single-digit updates (I.E updating col 2 with row 5 will update the correct cell), as soon as you get to double-digit ID's it splits the value wrong and updates the wrong cell, (I.E updating col 2 row 15 will update col 2 in row 1).

As far as I can tell this seems to stem from the new system relying on Excel formatted cell IDs (I.E C15) instead of both like V2.
If this is intended, perhaps a setValue equivalent of getValueFromCoords is required?

**Comment by pphod** [comment]
Sorry, I have tested now. It seems to be working fine. I was not able to see any problem. Can you create a jsfiddle so it will be easy to replicate any possible problem, please?

**Comment by pphod** [comment]
Just in case, setValueFromCoords seems a good and simple idea. So, it has been done.

**Comment by AO-TERRA** [comment]
Thank you very much for implementing setValueFromCoords, I've just had a chance to implement it and its done exactly the trick

I get a feeling I was/am using setValue wrong if you are unable to replicate it, regardless I have included a JSFiddle example of my previous implementation as requested just in case:
[https://jsfiddle.net/qyz0fpah/](https://jsfiddle.net/qyz0fpah/)

**Comment by pphod** [comment]
This will not work since 016 does not exist. Please use more excel like column names.
```
function Numeric() {
  table.setValue('016', 'update')
}

```
