### ISSUE TITLE
jexcel rendering issues in IE 11

### ISSUE THREAD

**Issue by Lockey45** [jspreadsheet/ce#506]
After having downloaded the latest jsuites.js and jexcel.js from the repository the spreadsheet still failed to render in IE 11. IE 11 developer tools is still showing these errors:
 
demo_IE_1.html
HTML1300: Navigation occurred.
demo_IE_1.html
SCRIPT1002: Syntax error
jsuites.js (1962,18)
SCRIPT5007: Unable to get property 'contextmenu' of undefined or null reference
jexcel.js (451,9)

demo_IE_1.html
SCRIPT5007: Unable to get property 'contextmenu' of undefined or null reference
jexcel.js (451,9)
SCRIPT5007: Unable to get property 'contextmenu' of undefined or null reference
jexcel.js (451,9)

On a hunch, I downloaded the actual source code files (jexcel.js and jsuites.js) from the following web page URLS :

https://bossanova.uk/jexcel/v3/jexcel.js
https://bossanova.uk/jsuites/v2/jsuites.js

Finally, the jexcel spreadsheet rendered in IE 11.  

I discovered that the versions of jexcel.js and jsuites.js referenced by your website examples are different from the latest repo versions of these files.  I have confirmed this by performing a file compare.  I am attaching both versions so you can see what I am talking about.  
Also, I am attaching the sample html page I used to demonstrate this.

For reference I am using Windows 10 and IE 11 version 11.829.1734. This is the most recent version of IE11 which was released in the Cumulative security update for Internet Explorer: June 11, 2019.

[demo_IE.zip](https://github.com/paulhodel/jexcel/files/3459852/demo_IE.zip)

[Repo versions.zip](https://github.com/paulhodel/jexcel/files/3459823/Repo.versions.zip)
[Web Page versions.zip](https://github.com/paulhodel/jexcel/files/3459825/Web.Page.versions.zip)

**Comment by pphod** [comment]
I have sync both site and master, please make sure you have no cache problems  ;)
