### ISSUE TITLE
getValue() and getValueFromCoords returning formula and not computed data

### ISSUE THREAD

**Issue by Lockey45** [jspreadsheet/ce#507]
Invoking getValue() and getValueFromCoords() on a cell containing a formula always returns the formula and not the computed data. 

I tried setting the copyCompatibility:true in options, however, this didn't change anything.

From looking at the jexcel.js source neither getValue() or getValueFrom Coords() tests the value of the copyCompatibility option before returning the value.  I have updated your source code to correct for this as shown below.

    /**
     * Get the value from a cell
     * 
     * @param object cell
     * @return string value
     * 
     * Modified to return either cell value or formula depending
     * upons value of copyCompatibility option
     */
    obj.getValue = function(cell) {
        if (typeof(cell) == 'object') {
            var x = cell.getAttribute('data-x');
            var y = cell.getAttribute('data-y');
        } else {
            cell = jexcel.getIdFromColumnName(cell, true);
            var x = cell[0];
            var y = cell[1];
        }

        if (x != null && y != null)
        {
            if (obj.options.copyCompatibility == true)
            {
                return obj.records[y][x].innerHTML;
            }
            else{
               return obj.options.data[y][x]; 
            }
        }
        return null;
    }

    /**
     * Get the value from a coords
     * 
     * @param int x
     * @param int y
     * @return string value
     * 
     * Modified to return either cell value or formula depending
     * upons value of copyCompatibility option
     */
    obj.getValueFromCoords = function(x, y) {
        if (x != null && y != null) {
            if (obj.options.copyCompatibility == true)
            {
                return obj.records[y][x].innerHTML;
            }
            else{
               return obj.options.data[y][x]; 
            }
        }
    }

**Comment by pphod** [comment]
Thank for your suggestion, I have implemented that and It will be available in the master repo soon.

```
    obj.getValueFromCoords = function(x, y, processedValue) {
        if (x != null && y != null) {
            if (processedValue || obj.options.copyCompatibility == true) {
                return obj.records[y][x].innerHTML;
            } else {
                return obj.options.data[y][x];
            }
        }
    }
```

**Comment by mopena** [comment]
Hi Paul,

The Jexcel Pro v7 I download here (https://jexcel.net/v7/jexcel.zip) is showing the same behavior as it is returning the formula and not the computed data. 

Thanks.

**Comment by pphod** [comment]
I have replied to you there.
