### ISSUE TITLE
Unable to call getValue() within updateTable function

### ISSUE THREAD

**Issue by Lockey45** [jspreadsheet/ce#508]
Within a custom updateTable function I am trying to obtain the value of a different cell than is being targeted using row= or col =.  For example when targeting row=0, col=0 I want to obtain the value of the cell at 'D3'.

I have tried using:
worksheet.jexcel.getValue('D3');
and I get the following exception:
Uncaught ReferenceError: spreadsheet is not defined

Using:
jexcel.getValue('D3')
I get this exception.
Uncaught TypeError: jexcel.getValue is not a function.

Is it possible to do this?  If so, can you tell me how.
Thanks.

**Comment by pphod** [comment]
var mytable = jexcel(domId, options);

then

mytable.getValue('D3')
