### ISSUE TITLE
Feature Request: Text cell with optional value selection by dropdown

### ISSUE THREAD

**Issue by thraizz** [jspreadsheet/ce#509]
Hi, first of all thank you for this great plugin, I used it a lot as jQuery plugin and appreciate the port as vanilla js. 
What I'm not happy with is the way how dropdowns are used. Currently, the user will open the dropdown, choose one of the options and therefore set the cell's value to the selected option. But if the dropdown misses an option, the user has no way to set the cell to his desired value.
To solve this problem, I modified the behaviour of a dropdown when text is entered. Instead of opening the dropdown, `openEditor` and later on `closeEditor` are called with an extra argument, which triggers the default text edition state. After closing, I update the source and remove duplicates.
Is there a reason why dropdowns are implemented as "One out of N values" ? If yes, I would love to hear about the reasoning. If not, I could open a PR after merging to v3 and some polishing.

**Comment by pphod** [comment]
I am going to add a feature in the roadmap of Jsuites. The possibility to add a new value in your dropdown.

**Comment by pphod** [comment]
This has been implemented, you can allow the user to enter new options, remoteSearch, and many other options.
