### ISSUE TITLE
Reduce url ajax request on "static" json files.

### ISSUE THREAD

**Issue by Quero86** [jspreadsheet/ce#51]
I Have a static json file. So no need to refetch the URL again and again.
I add the data option "static" and write something like this at Line 1450:

> if (options.columns[position[0]].static && options.columns[position[0]].json) {
                                        $(result).html('');
                                        showResult(options.columns[position[0]].json, str);
                                    }
                                     else {
                                        $.getJSON(options.columns[position[0]].url + '?q=' + str + '&r=' + $(main).jexcel('getRowData', position[1]).join(','), function (data) {
                                            $(result).html('');
                                            if (options.columns[position[0]].static) {
                                                options.columns[position[0]].json = data;
                                            }
                                            showResult(data, str);
                                        });
                                    }

**Comment by pphod** [comment]
If you content is static you can defined your source as an object
{ type:'dropdown', source:[xxxxxxx] }

http://bossanova.uk/jexcel/examples/working-with-dropdowns
