### ISSUE TITLE
TypeError: $.fn.jexcel.defaults[id] is undefined

### ISSUE THREAD

**Issue by sugiarto-dvd** [jspreadsheet/ce#510]
Hi, Mr Paul, I use your plugin but got this error. 

TypeError: $.fn.jexcel.defaults[id] is undefined

I always have this error, but only after a while, at first its nothing wrong, but after a while this message show up 
Can you suggest me how to check where it goes wrong ?? Thanks 
![image](https://user-images.githubusercontent.com/20536906/62357864-123b8080-b53e-11e9-9f2e-c16ad0a119e5.png)

**Comment by pphod** [comment]
Sorry, I can help you with the provided information. Can you create a jsfiddle? One other think, would you consider upgrate to v3? The jquery version will be deprecated soon.
