### ISSUE TITLE
How to set value and formula

### ISSUE THREAD

**Issue by eiso** [jspreadsheet/ce#513]
I would like to be able to capture formulas, and return the value without needing to set a constant JS function for each. 

I am trying to figure out how to do the following:

* To use `beforeChange` to capture the Value & Formula of the cell. 
* If the formula is present in my list of predefined formulas, do some actions (send the formula and the values referenced off with gRPC to another service)
* When my calculated value is returned, update the cell with value (but keep the formula there)

I have in particular been struggling on how to set a value & formula and bypass the current formula executor.

p.s. Thank you for this incredible library!

**Comment by pphod** [comment]
getValue('A1', true); // will return value from a formula
getValue('A1') // will return a formula

Is this help?

**Comment by eiso** [comment]
Thank you for the very fast response! That does help. It seems though that my problem isn't with your library but with Typescript & React. Where I am unable to call `getValue` and `setValue` from within `beforeChange` (onbeforechange). Going to figure that out now.

**Comment by eiso** [comment]
@paulhodel which is the right way to modify the value that is to be set, without getting into an infinite loop in the callbacks? And can I set both the value and the formula?

**Comment by pphod** [comment]
The only way to avoid an infinite loop when call setValue inside a callback of setValue is:

onchange: function() {
   yourtable.ignoreEvents = true;
   yourtable.setValue('A1', 'xxx');
   yourtable.ingoreEvents = false;
}

But, I am not sure if this is the more elegant solution. Depends on what you would like to do. There is a method you can use as a middleware to manipulate the table and its cells, as below:

```
<html>
<script src="https://bossanova.uk/jexcel/v3/jexcel.js"></script>
<script src="https://bossanova.uk/jsuites/v2/jsuites.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jexcel/v3/jexcel.css" type="text/css" />
<link rel="stylesheet" href="https://bossanova.uk/jsuites/v2/jsuites.css" type="text/css" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.6/numeral.min.js"></script>

<div id="spreasheet2"></div>

<script>
var data2 = [
    ['BR', 'Cheese', 1, 3.99],
    ['CA', 'Apples', 0, 1.00],
    ['US', 'Carrots', 1, 0.90],
    ['GB', 'Oranges', 0, 1.20],
    ['CH', 'Chocolats', 1, 0.40],
    ['AR', 'Apples', 1, 1.10],
    ['AR', 'Bananas', 1, 0.30],
    ['BR', 'Oranges', 1, 0.95],
    ['BR', 'Pears', 1, 0.90],
    ['', '', '', '=ROUND(SUM(D1:D8), 2)'],
];

var table2 = jexcel(document.getElementById('spreasheet2'), {
    data:data2,
    columnSorting:false,
    columns: [
        { type: 'autocomplete', title:'Country', width:'250', url:'/jexcel/countries' },
        { type: 'autocomplete', title:'Food', width:'150', source:['Apples','Bananas','Carrots','Oranges','Cheese','Kiwi','Chocolats','Pears'] },
        { type: 'checkbox', title:'Stock', width:'100' },
        { type: 'number', title:'Price', width:'100' },
    ],
    updateTable:function(instance, cell, col, row, val, label, cellName) {
        // Number formating
        if (col == 3) {
            // Get text
            txt = cell.innerText;
            // Format text
            txt = numeral(txt).format('0,0.00');
            // Update cell value
            cell.innerHTML = '$ ' + txt;
        }

        // Odd row colours
        if (row % 2) {
            cell.style.backgroundColor = '#edf3ff';
        }

        // Total row
        if (row == 9) {
            if (col < 3) {
                cell.innerHTML = '';
            } 

            if (col == 2) {
                cell.innerHTML = 'Total';
                cell.style.fontWeight = 'bold';
            }

            cell.className = '';
            cell.style.backgroundColor = '#f46e42';
            cell.style.color = '#ffffff';
        }
    }
});
</script>
</html>
```

**Comment by pphod** [comment]
But, can you explain what you trying to achieve? I am can give you the best answer if you describe better your problem.

**Comment by eiso** [comment]
Thank you so much for the very fast replies. What I am trying to achieve is to catch a cell that contains =FORMULA, if FORMULA is defined in my list, to call my function and return its value. The reason I am not implementing FORMULA in a JS function is that it is dynamic (different users, can set different formulas during runtime) and the results are processed in Python.

**Comment by eiso** [comment]
When I use setValue though on a cell, I lose the formula. Is there a way to set both the value and the formula?

**Comment by pphod** [comment]
No, you can't set value and formula. When setting a cell with a formula, the formula will be executed the result will be set to the cell.

**Comment by pphod** [comment]
What I can do, I am planning to change the onbeforechange, so if the user returns a value... you can overwrite the initial value by something else

**Comment by pphod** [comment]
It will be a way to intercept the user setValue do some process and confirm the change or not.

**Comment by eiso** [comment]
That would be amazing!

**Comment by pphod** [comment]
Ok, I will be doing that tomorrow. Let you know once it is available in the master repository.

**Comment by pphod** [comment]
It has been done.

**Comment by eiso** [comment]
Thank you @paulhodel! That is amazing, on which branch can I find it (I had a look but couldn't see it). Also do you maintain a "master"/HEAD version on NPM as well or just release versions?

**Comment by pphod** [comment]
I have just pushed to the master. Please, let me know if is working fine.

Regards,

**Comment by eiso** [comment]
Will do! 

p.s. Where can I reach you privately, would love to show you what I am working on. I think you'll like it.

**Comment by pphod** [comment]
My skype: paul.hodel

**Comment by pphod** [comment]
Hi Eiso,

I have sent you a message on skype.

**Comment by JassonGithub** [comment]
Saludos, podrían ayudarme? necesito crear formulas para llamar desde una celda en REACT, no se en donde inicializarlas

**Comment by JassonGithub** [comment]
En Javascript es muy facil de hacer, pero intento seguir la misma estructura en REACT y no me funciona

**Comment by SujinRajak** [comment]
hello sir, is there a better way to implement formula ?
