### ISSUE TITLE
Overflow (how to round to x decimal places?)

### ISSUE THREAD

**Issue by lerdalaa** [jspreadsheet/ce#518]
In a calculation '=SUM(A1:A3)' i get 0.3000000000004 instead of the correct 0.3.

When i use Math.round('=SUM(A1:A3)') I get the answer NaN.

Is there a way to round in jExcel?

Thank you

**Comment by pphod** [comment]
=ROUND(SUM(A1:A3))

**Comment by lerdalaa** [comment]
Thank you but now I get "Error: #VALUE!"

**Comment by harshdesai991** [comment]
You need to specify decimal places you want e.g.  =ROUND(SUM(A1:A3), 2)
