### ISSUE TITLE
Feature request: Add 'Copy as values' menu to context menu

### ISSUE THREAD

**Issue by fureweb-com** [jspreadsheet/ce#519]
Currently, We can get the original formula rather than values when copy and paste the area of ​​the selected sheet.

So I wanna new feature like below.

![image](https://user-images.githubusercontent.com/22983900/62512473-09ef8800-b853-11e9-8557-8d1597ce18cb.png)

I think this feature will help many people.

**Comment by pphod** [comment]
You can change the behavior by using copyCompatibility: true in the innitalization.

**Comment by fureweb-com** [comment]
Oh, I got it. Thanks! :)
