### ISSUE TITLE
Export / Save as CSV (Delimiter)

### ISSUE THREAD

**Issue by Quero86** [jspreadsheet/ce#52]
i found this function to export to CSV.

console.log($('#myJTable').jexcel('copy', false, ',', true));

But some csv not work.

Like this:

>                     if (val.match(/,/g) || val.match(/\n/)) {
                        val = '"' + val + '"';
                    }

- You search for a comma, but not for the delimiter?
- You remove this char: " instead, escape them. (But this is an overall problem!)

**Comment by pphod** [comment]
http://bossanova.uk/jexcel/examples/creating-a-table-from-an-external-csv-file
