### ISSUE TITLE
Locking/freezing columns?

### ISSUE THREAD

**Issue by quasipickle** [jspreadsheet/ce#520]
Is there functionality to freeze columns?  By that I mean: if I have 40 columns with 10 visible and I scroll the table to the right, can I set the first 5 columns to stay in place?  Like one would do with a `position:sticky` or `position:fixed` element?

**Comment by pphod** [comment]
No, we don't have that option.

**Comment by pphod** [comment]
https://jexcel.net/v4/examples/freeze-columns
