### ISSUE TITLE
Uncaught TypeError: element.getAttribute is not a function when within a table

### ISSUE THREAD

**Issue by Chrsab** [jspreadsheet/ce#524]
I'm using the latest version of jexcel v3. When using a jexcel spreadsheet within a table I get Uncaught TypeError: element.getAttribute is not a function at GetCellCoords when using pagination etc. See example below:

&lt;table&gt;
	&lt;tr&gt;
		&lt;td&gt;
			&lt;div id="spreadsheet"&gt;&lt;/div&gt;
		&lt;/td&gt;
	&lt;/tr&gt;
&lt;/table&gt;

&lt;script&gt;
jexcel(document.getElementById('spreadsheet'), {
    csv:'/demo.csv',
	csvHeaders:true,
    search:true,
    pagination:5,
	paginationOptions:[10,25,50,100],
    columns: [
        { type: 'text', width:120, readOnly:true },
        { type: 'text', width:100, readOnly:true },
        { type: 'text', width:100, readOnly:true },
        { type: 'text', width:100, readOnly:true },
        { type: 'text', width:100, readOnly:true },
     ]
});
&lt;/script&gt;

When it's outside a table it works perfectly. Anyway I can resolve without having to take out of the table?

**Comment by pphod** [comment]
Did you try the most recent version? I guess this has been fixed. If not can you create a jsfiddle to explain more about the problem?

**Comment by alberto-ita** [comment]
Hi Paulhodel I'm using your jexcel v4. 
First Thanks you for your work, I really appreciate. 
I tested jexcel on the local server, and on a "normal" page everything works normally. 
Then I put the page in a job I'm doing; the situation is this: 
I have a Parent page that makes load() calls and loads the pages into a DIV (as you normally do). 

`$('#mybutton').click(function(){
$("#myDiv").load("my-jexcel-page.php"); 
});`

The page loads normally and jexcel works "almost" normally. 
If I click in the column header or pagination buttons, I receive this error (on the console):
**Uncaught TypeError: element.getAttribute is not a function
refered to line 6807 on jexcel.js**

Please note that the jquery and the jexcel are on the parent page and the script work well if the page is not loaded by jquery.
Can you have some suggestions to solve ? Thanks
Alberto

**Comment by alberto-ita** [comment]
Hello Paulhodel
for now i found a solution, little dirth, not your solution.
The problem maybe was caused by some conflict with jQuery;
at the line 6807 i changed the code

```
var x = element.getAttribute('data-x');
var y = element.getAttribute('data-y');
```
with

```
var x = $(element).attr('data-x');
var y = $(element).attr('data-y');
```
Thanks again, and if you have a clean solution, please write.
Regards.
