### ISSUE TITLE
Upload file like text,doc,csv, images etc for each row

### ISSUE THREAD

**Issue by Rajinderimpinge** [jspreadsheet/ce#526]
Hi ,

I want to option for file upload for each row.
For example I have tasks list row by row and what I want is that I want to add a doc file for the each task that will contain the instruction related to that task.

Please let me know the way how can I upload file in the Jexcel table cell.

Thanks

**Comment by pphod** [comment]
Can you send an email to paul@jexcel.net 

Thanks.

**Comment by Rajinderimpinge** [comment]
I send the email please check

**Comment by rohitkriitkgp** [comment]
Hi,

Can you please share the solution for this issue. 

Thanks

**Comment by afifalfiano** [comment]
@paulhodel If you are not too bussy, maybe you can check  your email. I sent email to request this feature. Thanks

**Comment by afifalfiano** [comment]
@Rajinderimpinge Excuse me, Could you got solution from this problem?
