### ISSUE TITLE
Custom column type init

### ISSUE THREAD

**Issue by luca69** [jspreadsheet/ce#529]
Hi
I try the new version of jexcel but i have a problem with custom editor
In the previous version the setValue function was call when JExcel create the cell, but now 
IExcel write directly the data value

In my project, My cell must process the SetValue everytime becouse in data field i write an object that must process an translate in text
is possible to execute the setValue when the call is create?

my example:

data[0][0]=JSON.stringify("Listino prezzi")
columns[0]={ type: "text",title: "testo" , editor:TextEditor}

var TextEditor = {
    // Methods 
    closeEditor : function(cell, save) {
           var value =   $(cell).find(".jqte").find(".jqte_editor").html() ; // Take the value from my editor
	   $(cell).attr("data-valore",JSON.stringify(value));
           $(cell).html(value);
  	return JSON.stringify(value);
    },
    openEditor : function(cell) {
 	var html =JSON.parse( $(cell).attr("data-valore"));
        var editor = document.createElement('textarea');
         ...........
	},
    getValue : function(cell) {
	       var valore=$(cell).attr("data-valore")
		return  (valore);
    },
    setValue : function(cell, value) {
 		var testo=JSON.parse(value)
		returnT=_BOOK_UNSERIALIZZA_TESTO(testo) //My function that translate the object in HTML text
		$(cell).attr("data-valore", JSON.stringify(returnT) );
 		cell.innerHTML = returnT;
        return true;
    }
}	

thanks
Luca

**Comment by pphod** [comment]
you can try to implement that on onchange
