### ISSUE TITLE
V3: Formulas return #ERROR if no cells are referenced

### ISSUE THREAD

**Issue by lucBoillat** [jspreadsheet/ce#532]
I am trying to port my application from the V2 library to V3. However the new parsing mechanism seems to require at least one cell reference in a formula to work, e.g. **=SUM(1,1)** returns #ERROR, whereas in V2 it would return 2. In V3, either the first or second argument has to reference a cell such as A1 or B3 for example.
Is this by design or a bug?

**Comment by pphod** [comment]
We are going to fix that to keep the compatibility.

**Comment by pphod** [comment]
It has been fixed.
