### ISSUE TITLE
hideIndex

### ISSUE THREAD

**Issue by thumbert** [jspreadsheet/ce#534]

**Comment by thumbert** [comment]
Hi, 

I'm trying to only show the headers, and hide the row numbers of my table.  I found the obj.hideIndex() method, but it doesn't do what I want.   See below.

![image](https://user-images.githubusercontent.com/392827/62988848-ce852880-be13-11e9-94b0-e1133385e93f.png)

Oddly, the row numbers show up in the cells.   Any suggestions?

Thank you,
Tony

**Comment by pphod** [comment]
It has been fixed.
