### ISSUE TITLE
Calling the getHeight method reported an error

### ISSUE THREAD

**Issue by Zecio** [jspreadsheet/ce#537]
When I set the initial height of the line, I made a mistake in calling the getHeight () method. Then I looked at the source code and found that there were some problems in getting the style height of the current element from the source code.
![WX20190814-162955](https://user-images.githubusercontent.com/33150774/63006279-c62efb00-beb0-11e9-9647-a7c5df8ac2b8.png)

![1565771339670](https://user-images.githubusercontent.com/33150774/63006212-a7306900-beb0-11e9-8050-0f2c0d9964ab.jpg)

the source code:

![1565771744089](https://user-images.githubusercontent.com/33150774/63006743-caa7e380-beb1-11e9-8f30-1490b08685b2.jpg)

` data = obj.rows[row].getAttribute('height')`

It should be changed to

` data = obj.rows[row].style.height`

Finally, a suggestion is made: when the parameter row is empty or null, can we return the row height of all rows, similar to the getWidth method? Thanks!

**Comment by pphod** [comment]
It has been done. Thanks.
