### ISSUE TITLE
Formula with input mask gives wrong results

### ISSUE THREAD

**Issue by strainovic** [jspreadsheet/ce#542]
https://bossanova.uk/jexcel/v3/examples/spreadsheet-formulas

If you enter 1000 in some Price column, value will be converted to 1,00 and result will be wrong. If you enter number with decimal, result will be correct. Numbers less then 1000 work fine.

If you double click on field and try to select all with CTRL+A, comma character will be stripped and instead of 1,20 you will get 120.

Without input mask, formula gives correct results.

Does anyone have any idea what can be the problem and how we can solve it?

Thanks and keep up good work! :)

**Comment by pphod** [comment]
It has been resolved in the master repository.
