### ISSUE TITLE
Disabling context menu 

### ISSUE THREAD

**Issue by TsePakKwan** [jspreadsheet/ce#545]
Hi, @paulhodel 
May I know Jexcel V3 Can disable right click context menu?
Now, I tried the code below, but when I press the right click, there are still something will show.
Any idea?
https://jsfiddle.net/tsepakkwan/fg49xdLa/
![1566181062195](https://user-images.githubusercontent.com/51103712/63235065-0e646980-c273-11e9-9ea5-ff5c500335db.gif)

**Comment by seoanalyze** [comment]
`contextMenu: false,
`
is your way to go :)

**Comment by pphod** [comment]
Yes, that's correct.

contextMenu: false;
