### ISSUE TITLE
Feature Request: check all function on Column types 'checkbox'

### ISSUE THREAD

**Issue by TsePakKwan** [jspreadsheet/ce#546]
hi @paulhodel ,first of all thank you for this amazing project.

Could you add 'check all' function on Column types 'checkbox' Header ?

below is my testing code, but this is not my hope layout.
https://jsfiddle.net/tsepakkwan/s5h7628a/
On my hope layout just like as below gif.
![1566186922667](https://user-images.githubusercontent.com/51103712/63238280-a452c100-c280-11e9-824f-7183326213cf.gif)

to go a step further, I hope that in addition function ’check all' ,it will be more perfect to be able to customize headers.

**Comment by pphod** [comment]
You can create that by update the innerHTML from the column after the load, using onload.
