### ISSUE TITLE
Default text alignment

### ISSUE THREAD

**Issue by seoanalyze** [jspreadsheet/ce#547]
Hey,
when I initiate the plugin I can set the alignment with
          
`colAlignments: ['left', 'left', 'left]
`
But I'm having trouble when I add a new column in the Browser. The default value seems to be 'center'. Is there an option to set it to 'left' by default?
Thank you!

**Comment by pphod** [comment]
You can define the init configuration:

defaultColAlign:'left',
defaultColWidth:'50px',

Avaiable on v3.5.2 (in the master).

**Comment by minhdq0709** [comment]
hi,
How do I want to set style "text-align: right" for column have attribute data-x = "5"?

Thank's
