### ISSUE TITLE
Option to disable Series for calendar cell when using jexcel_corner

### ISSUE THREAD

**Issue by AO-TERRA** [jspreadsheet/ce#548]
When using the black square (jexcel_corner is what I believe it is called) to drag duplicate out selected cells for the calendar cell type it will increase the date by one day for each row.

While I understand this is likely useful in some cases it is not so in my implementation, could this be a toggleable option for the calendar cell setting rather then forcefully enabled, even if it's enabled by default?

This behaviour can be seen here:
[https://bossanova.uk/jexcel/v3/examples/date-and-datetime-picker](https://bossanova.uk/jexcel/v3/examples/date-and-datetime-picker)
Steps to replicate:
1. Select the top cell for last visited
2. Using the jexcel_corner drag the cell down to the bottom cell
3. The row will now have a date range of 01/01/2019 through 06/01/2019 instead of just duplicating out 01/01/2019

As seen here this was not present in V2 and only duplicates out the cell when the above actions completed:
[https://bossanova.uk/jexcel/v2/examples/using-a-calendar-column-type](https://bossanova.uk/jexcel/v2/examples/using-a-calendar-column-type)

Cheers

**Comment by pphod** [comment]
Please use

autoIncrement: false,
