### ISSUE TITLE
Autocomplete with functionality to create new if not present in auto complete list

### ISSUE THREAD

**Issue by jason-guru** [jspreadsheet/ce#550]
Hi, first of all thanks for the wonderful package it has my life a lot easier. :)

Now, coming to the point. I was wondering if there's any possibility of enabling autocomplete alongside ability to create new entry, if not present in the auto complete list. like what is done in excel or google spreadsheet. 

Any suggestion would be much appreciated. Thanks!

**Comment by jorgegvallejo** [comment]
This would be a great feature, please make it happen. The current offered methods and callbacks don't really allow it.

**Comment by pphod** [comment]
What is your opinion for the KEY => VALUE dropdown?

**Comment by jorgegvallejo** [comment]
In the docs I saw you mention a "value or key-value selectbox" being available, but I didn't really understand what you meant and I didn't find an example. Could you elaborate a bit?

**Comment by pphod** [comment]
For example, add a new option in the dropdown is straight forward when you are dealing with dropdown like that: ['Apples', 'Bananas', 'Pears']. In this case, you just add new options to the array.

The problem is when you dealing with K=>V dropdown, what is your option in terms of the user interface. Do you think should ask the key for the user?

**Comment by flywalt** [comment]
This is exactly what I‘m looking for.
sometimes the key should come from user, since I can't assure that my database is complete.
better if jexcel can mark those new keys for me, so I can update my database afterwards.
THX!

**Comment by flywalt** [comment]
eg. the dropdown has a list of a,b,c,d
now when i type in e, i want it could be possible to do the input, while now the autocomplete only allows me to choose within a,b,c,d.
what's more,  it would be better to mark those new "e" or add "e" into the list of a,b,c,d,e

**Comment by pphod** [comment]
Something custom implementation for Jexcel Pro v5.
https://jsfiddle.net/paulhodel/482931bp/
