### ISSUE TITLE
v3 Copy and Paste for IE 11

### ISSUE THREAD

**Issue by PRISMAY** [jspreadsheet/ce#551]
We still have users using IE11 so we need copy/paste to function.  We have a new reactjs app and have a workaround in the source that would help fix the paste issue.

This first snippet is how we implement the context menus for paste so we have IE support:
```
if (navigator)
{
   items.push({
      title: obj.options.text.paste,
      shortcut: 'Ctrl + V',
      onclick: () =>
      {
         if (obj.selectedCell)
         {
            if (navigator.clipboard)
            {
               navigator.clipboard.readText().then(function (text)
               {
                  if (text)
                  {
                     obj.paste(obj.selectedCell[0], obj.selectedCell[1], text);
                  }
               });
            }
            else // IE fix
            {
               let ta = document.getElementById('jexcel_textarea');
               ta.focus();
               ta.select();
               document.execCommand('Paste');
               obj.paste(obj.selectedCell[0], obj.selectedCell[1], ta.value);
            }
         }
      }
   });
}
```
The issue we run into when running in IE is we get an error due to use of strict mode (_assignment to read-only properties is not allowed in strict mode_).  This occurs in the paste function where the style is being assigned.
`obj.records[rowIndex][colIndex].style = style[styleIndex];`

This can be fixed by assigning to the style.cssText instead, so:
`obj.records[rowIndex][colIndex].style.cssText = style[styleIndex];`

This works in both IE11 and Chrome.  I did NOT test Firefox as I don't have it handy.

Would love to see this fixed officially so our modules stay up to date with the fix and our customers can use the copy/paste.  Thank you and please let me know if you need any other info.

**Comment by pphod** [comment]
It has been fixed.

**Comment by PRISMAY** [comment]
Thank you.
