### ISSUE TITLE
There is still a 'pagination error'-jExcel v3

### ISSUE THREAD

**Issue by Thomas-Kang** [jspreadsheet/ce#552]
Hi,
It seems that 'pagination error' has not been resolved yet in jExcel v3.

If the total number of pages is six, the process will be processed normally. However, if the number of pages exceeds 7 pages, the following bug occurs.

1.If the total page is 6 pages, the last 6 pages are processed normally.

![img0](https://user-images.githubusercontent.com/30923132/63480356-8f6a6d80-c4cc-11e9-9b05-19d67f8bd2bf.png)

2.If the total page is 7 pages, a bug occurs on the last 7 pages.

![img1](https://user-images.githubusercontent.com/30923132/63480126-b5dbd900-c4cb-11e9-821e-76bc32aa9033.png)

I'm always grateful for your very useful work.
Good luck...

**Comment by pphod** [comment]
It has been fixed in the master repository.
