### ISSUE TITLE
v3 Delete Rows in IE11 Crashes

### ISSUE THREAD

**Issue by PRISMAY** [jspreadsheet/ce#553]
I found another issue in IE.  Looks like it doesn't support the .remove() function in the deleteRow function called on obj.rows[row].  I found an interim fix that checks for .remove per changes below:
```
    if (obj.rows[row].remove === undefined) // IE fix
    {
        obj.rows[row].parentNode.removeChild(obj.rows[row]);
    }
    else
    {
        obj.rows[row].remove();
    }
```

**Comment by AnaOrtega1** [comment]
Could this fix be included in the code?

**Comment by PRISMAY** [comment]
Are you asking the author Paul or asking me to make the fix in the code and create a pull request?

**Comment by pphod** [comment]
I will include that soon, thanks

**Comment by PRISMAY** [comment]
Thank you sir.

**Comment by pphod** [comment]
It has been deployed along with other similar fixes.

**Comment by PRISMAY** [comment]
Thanks much. :)
