### ISSUE TITLE
'Context Menu' did not show all when spreadsheet on windows bottom

### ISSUE THREAD

**Issue by TsePakKwan** [jspreadsheet/ce#555]
hi @paulhodel ,
I find some layout problem.
Go to 
1. https://bossanova.uk/jexcel/v3/examples/programmatically-updates
2. scroll spreadsheet near to bottom then right click (please refer below image)

Expected Result(I used the editor of the chrome browser to force the display.):
![1566536302924](https://user-images.githubusercontent.com/51103712/63567845-1c392800-c5ae-11e9-9488-30d14b7ba7cb.jpg)

Actual Results:
![1566535823142](https://user-images.githubusercontent.com/51103712/63567516-f9f2da80-c5ac-11e9-91f9-4ba2f2ae359d.gif)

**Comment by julianullrich99** [comment]
Is there a fix/workaround to this?
I'm facing the same problem

**Comment by pphod** [comment]
This has been fixed. And it will be deployed soon in the new jSuites version.
