### ISSUE TITLE
Character Set Input Error

### ISSUE THREAD

**Issue by rsauto9311** [jspreadsheet/ce#557]
![image](https://user-images.githubusercontent.com/54504666/63651709-acd05d80-c792-11e9-8662-760b525b74e4.png)

If you are in Korean at the time of texting, the first input will be entered in English.

**Comment by pphod** [comment]
It has been fixed in the master repository

**Comment by flywalt** [comment]
Hi, this problem also occurs in Chinese input

**Comment by QiuXiangYong** [comment]
> 
> 
> Hi, this problem also occurs in Chinese input

You can follow this thread [ magdute commented on Oct 10, 2018](https://github.com/paulhodel/jexcel/issues/248)

or

replace the function download in  jexcel.js :
     //     var blob = new Blob([data], {type: 'text/csv;charset=utf-8;'});
	    var blob = new Blob(["\uFEFF"+data], {type: 'text/csv;charset=utf-8;'});

**Comment by flywalt** [comment]
Thanks for your replyHowever, this thread is not related to downloading. It is about text input.

**Comment by pphod** [comment]
This has been included in the master repo:
var blob = new Blob(["\uFEFF"+data], {type: 'text/csv;charset=utf-8;'});

**Comment by flywalt** [comment]
Hi Paul, thanks for your reply. Please refer to this issue https://github.com/handsontable/handsontable/issues/839     This problem is not only about set input, but input method.
