### ISSUE TITLE
jExcel 3: Suming empty value causes two sum strings instead of value

### ISSUE THREAD

**Issue by vasicvuk** [jspreadsheet/ce#558]
If i have three values in formula if one of the values is empty (empty string) it will sum strings instead of value for example

A1 = 200
A2 = 
A3 = 200
A4 = A1+A2+A3

A4 shows 200200.
![image](https://user-images.githubusercontent.com/5639877/63675265-b5538300-c7e8-11e9-891f-6749edaf17f0.png)

You can test on following table:
https://bossanova.uk/jexcel/v3/examples/meta-information

on jExcel 2 it works correctly.

**Comment by pphod** [comment]
It has been resolved on the master repository.
