### ISSUE TITLE
Copying of cells from a large table

### ISSUE THREAD

**Issue by Arkzv** [jspreadsheet/ce#56]
Hi Paul,
if the JExcel applied to the large table there is a performance issues while copying the data.
Current copying mechanism goes through all the cells, checking the "highlighted" property of each cell...
May be reasonable to have an array with coordinates of all the selected cells? (and than take the values only out of it)

**Comment by pphod** [comment]
We are considering working a new version with a slightly different engine. Thank you for your suggestion.

**Comment by Arkzv** [comment]
Paul, does it make sense to commit here than..?

**Comment by pphod** [comment]
Depends on what the way you are doing things. This change should be consistent with a few new features, such gradual loading, pagination, etc... ;)
