### ISSUE TITLE
Sticky Toolbar

### ISSUE THREAD

**Issue by juan-fuentes** [jspreadsheet/ce#560]
Historically Toolbars stick to the container they are created on to perform operations over the scrolling document. Office is the typical example of productivity app and is the average user expected behaviour.

Options for the other behaviours are welcome, sure there is other use cases, I just can't come with them now.

Separating the toolbar manually, as shown below results on the section being lost when clicking the button.
var jexcel_toolbar = $containerBody.find(".jexcel_toolbar");
$containerToolbar.append(jexcel_toolbar);

**Comment by pphod** [comment]
sticky toolbar has been enabled.
