### ISSUE TITLE
search - cannot read property 'innerHTML' of undefined

### ISSUE THREAD

**Issue by dvdsndr** [jspreadsheet/ce#562]
On a 1000 row table, the search fails with the above error.
<img width="1226" alt="Screen Shot 2019-08-27 at 8 58 04 am" src="https://user-images.githubusercontent.com/13637075/63773487-412ce400-c8a9-11e9-97f9-a3fad2af1c34.png">

**Comment by pphod** [comment]
Which version are you using?

**Comment by pphod** [comment]
Please make sure you are using the latest version. I have tested and seems to be working fine.
