### ISSUE TITLE
Numeric Values: Use commas as decimal places and fullstop as thousand separator

### ISSUE THREAD

**Issue by tahirghaffar** [jspreadsheet/ce#564]
Numeric Values: Can we use Western European numbering style i.e. comma as decimal places and full-stop as thousand separator. This JExcel is exactly meeting all my needs but I need this feature. 

Can you guide how can we format the numeric fields like this "One Thousand Three hundres fifty point thirty three" as 1.350,33 instead of 1,350.33.

Thanks in advance :)

**Comment by pphod** [comment]
One example to do that:

jexcel(document.getElementById('spreadsheet'), {
    data:data,
    columns: [
        { type: 'text', title:'Car', width:120 },
        { type: 'dropdown', title:'Make', width:200, source:[ "Alfa Romeo", "Audi", "Bmw" ] },
        { type: 'calendar', title:'Available', width:200 },
        { type: 'image', title:'Photo', width:120 },
        { type: 'checkbox', title:'Stock', width:80 },
        { type: 'numeric', title:'Price', width:100, mask:'$ #.##,00', decimal:',' },
        { type: 'color', width:100, render:'square', }
     ]
});
