### ISSUE TITLE
Why is mouseMoveControls event listener is attached to document?

### ISSUE THREAD

**Issue by alarm9k** [jspreadsheet/ce#569]
Is there a reason the `mouseMoveControls` event listener is attached directly to `window.document`? That way it captures all mouse move events (with an obvious impact on the performance) and, what's more important in my case, it clears the cursor style of every event target it encounters, be it the spreadsheet or totally unrelated DOM elements:
`if (e.target.style.cursor) {
    e.target.style.cursor = '';
}`

If there is no particular reason the listener cannot be attached to the spreadsheet itself instead, I can provide a fix/pull request.

Thanks.

**Comment by pphod** [comment]
Yes, there are other reasons, but one of the reasons is to control the resize when mouse is no longer over the jExcel element for example. This can happen when the user is dragging the border of the cell outside the jExcel elements.

**Comment by pphod** [comment]
I can double check if we can bypass that in case no jExcel function is ongoing....

**Comment by alarm9k** [comment]
Or we can at least check if the e.target belongs to jexcel DOM tree. Otherwise it clears the styles on the DOM outside of the spreadsheet.

**Comment by alarm9k** [comment]
Shall I open a new issue with a more clear description of the problem?

**Comment by pphod** [comment]
I have reopened. You can add any further description here.

**Comment by pphod** [comment]
This has been fixed
