### ISSUE TITLE
How to let enter key for next cell in edit mode?

### ISSUE THREAD

**Issue by winsonet** [jspreadsheet/ce#571]
It's need to use the mouse to click  to go to next cell in edit mode, can I just use the enter key for next cell (like in excel) ?

Thanks!!

**Comment by pphod** [comment]
In v3, both enter and tab will go to the cell below or next respectively.

**Comment by winsonet** [comment]
I am using V3 but I mean when I was editing the cell it can't use the enter to go to next one :(

if I just click the cell with mouse not in edit mode, then it can go to next by enter...

**Comment by winsonet** [comment]
any updates?

thanks!

**Comment by pphod** [comment]
I have tested that and when press enter I can jump to the cell below. If I press tab I go to the cell in the right as expected.

**Comment by winsonet** [comment]
oh~~~sorry, I tried in your demo also is working, hum...maybe there are some other issue in my project, because I uses a lot of other plugins in my project :(

ok, I will check it myself, thanks a lot!

**Comment by winsonet** [comment]
ok, I found that's why I have that problem, if I set to use the custom column, then will be cacuse my issue, and I also try your demo [here](https://bossanova.uk/jexcel/v3/examples/column-types), it also can't use the enter or tab key

another difference in the custom column, if you edit it and it will just append the content and not replace it.

**Comment by winsonet** [comment]
I really want to solve this problem, thanks a lot! 

because there is another big problem that if use the custom column, when user in editor mode and he click the 'Save' button, I can't get this editing column's value :(
