### ISSUE TITLE
insertColumn issue

### ISSUE THREAD

**Issue by CraigSheppardSec** [jspreadsheet/ce#573]
Hi,

Thanks for this, great script so far!  I am having an issue with the insertColumn, in a nutshell I'm building the data array from PHP and wanting to add a column with checkboxes for the user to select rows which I'll be dealing with when I export the data again.

I'm using ...

table1.insertColumn(1, 0, 1, {title:'Available', width:80, type:'checkbox'})

... after the sheet is loaded and it's inserting the column in the right place but the parameters are ignored.

It's been a long week so I probably doing something daft, any guidance would be appreciated.

Thanks!

**Comment by pphod** [comment]
This should work.

var prop = [{title:'Available', width:80, type:'checkbox'}];
table1.insertColumn(1, 0, 1, prop);

**Comment by CraigSheppardSec** [comment]
Thanks Paul,

It should, but....  Here's the full script if it helps, any guidance much appreciated;

```
    data = <?php print_r(json_encode($_SESSION['gigimport'])); ?>;
    table1 = jexcel(document.getElementById('gigspreadsheet'), {
        data:data,
        colHeaders: [<?php echo $selrow; ?>], //using this because the columns are variable and also putting a dropdown in there so the user can define what's in the column
        colWidths: [<?php echo $widths; ?>], //because variable number of columns
    });

var prop = [{title:'Available', width:80, type:'checkbox'}];
table1.insertColumn(1, 0, 1, prop);
```
As mentioned the table draws perfectly, one column gets added where it should but title, width and type is ignored.

Thanks again.

**Comment by pphod** [comment]
Please update from the repository. This issue has been fixed.

**Comment by CraigSheppardSec** [comment]
Awesome, works perfectly. Thanks so much Paul.
