### ISSUE TITLE
Formula Questions

### ISSUE THREAD

**Issue by bnmnetp** [jspreadsheet/ce#576]
HI,

I'm using jExcel in an introductory online data science textbook.  A couple of challenges that I'm trying to solve include:

1.  How to show a formula with its = as a string?  In Excel you can quote it with a single quote but the single quote shows up in jExcel.  I can use  the character entity`&#61` but then that is what shows up if you edit the cell.

2.  I guess it is not necessary in jExcel since you don't copy and paste ranges, but is there a way to make it ignore $ in cell references?

**Comment by pphod** [comment]
1) One option is to set parseFormulas: false, so no formula will be executed and shown as a string.
2) It will ignore $ if part of a string, I am not sure if I understood your question correctly.

If you wish to discuss further, I am happy to support your project.  My skype: paul.hodel
