### ISSUE TITLE
setMeta over data?

### ISSUE THREAD

**Issue by camilom** [jspreadsheet/ce#577]
I can setMeta on data? like:
data = [
    [1, 'Classe C', '{"meta":"3","value":"Oranges"}', 0, '2017-01-12'],
];
how i can recover this meta i think something like: 
var d = table.getData();
d[0][2].getValue();
// Oranges
d[0][2].getMeta();
// 3

**Comment by pphod** [comment]
You have two different variables, as below:

`<html>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jexcel/2.1.0/js/jquery.jexcel.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jexcel/2.1.0/css/jquery.jexcel.min.css" type="text/css" />

<div id="my"></div>

<script>
data1 = [
    ['US', 'Cheese', 'Yes', '2019-02-12'],
    ['CA;US;UK', 'Apples', 'Yes', '2019-03-01'],
    ['CA;BR', 'Carrots', 'No', '2018-11-10'],
    ['BR', 'Oranges', 'Yes', '2019-01-12'],
];

$('#my1').jexcel({
    data:data1,
    colHeaders: [ 'Product Origin','Description', 'Stock', 'Best before' ],
    colWidths: [ 300, 200, 100, 100 ],
    columns: [
        { type: 'dropdown', url:'/jexcel/countries', autocomplete:true, multiple:true }, // Remote source for your dropdown
        { type: 'text' },
        { type: 'dropdown', source:['No','Yes'] },
        { type: 'calendar' },
    ],
    meta:[
        { A1: { myMeta:'this is just a test', otherMetaInformation:'other test'} },
    ],
});
</script>
</html>`

More information
http://bossanova.uk/jexcel/v3/examples/meta-information
