### ISSUE TITLE
How to disable multi selection of rows and columns

### ISSUE THREAD

**Issue by jiwom** [jspreadsheet/ce#579]
Hello, I just want to ask if there is a way to disable multi column/row selection of cells and only allow selection of cells horizontally or vertically.

Disable selection of both rows and columns:
<img width="595" alt="Screen Shot 2019-09-08 at 10 03 22 AM" src="https://user-images.githubusercontent.com/22045242/64482242-97424580-d220-11e9-9739-5688ad4d312a.png">

Allow rows or column only:
<img width="578" alt="Screen Shot 2019-09-08 at 10 03 34 AM" src="https://user-images.githubusercontent.com/22045242/64482250-e5efdf80-d220-11e9-8167-967b3a9ae5b0.png">
<img width="588" alt="Screen Shot 2019-09-08 at 10 03 40 AM" src="https://user-images.githubusercontent.com/22045242/64482251-e5efdf80-d220-11e9-9cb4-c962fc126bc0.png">

Thanks.

**Comment by pphod** [comment]
Sorry, this is not supported at this moment.

**Comment by ahsan2489** [comment]
still not available?

**Comment by hodeware** [comment]
That is not going to be available natively. But, you can implement that using onselection event.

**Comment by ahsan2489** [comment]
Please get me a hint, I was trying to do so and still not able to do it.
onSelection event is not unselecting the current selection.

**Comment by hodeware** [comment]
Inside onselection you need to create a promise or something to call

instance.updateSelectionFromCoords(x1,y1,x2,y2) which has the new coordinates
