### ISSUE TITLE
how to set table readonly

### ISSUE THREAD

**Issue by ppingliu** [jspreadsheet/ce#58]
Hello Paul, I hope you well
I have a questions? how to set the table readonly? or where i can see APi

**Comment by saviourofdp** [comment]
use `editable: false` in options or `readOnly: true` in column config

**Comment by pphod** [comment]
http://www.bossanova.uk/jexcel/examples/readonly-options

**Comment by ppingliu** [comment]
can i set a row readOnly?

**Comment by pphod** [comment]
$('yourId').find('#row-NUMBER td').addClass('readonly');

**Comment by ppingliu** [comment]
yes 
 i used this way "$('yourId').find('#row-NUMBER td').addClass('readonly');" 

but when i  double click table header td, the all "readonly" can be removed.

**Comment by debamishra14** [comment]
@Guillaume-Bo can we add styles to the readonly columns ? I am trying to achieve that but somehow styles are not getting applied. can you plz help me out here? Thanks
cc: @paulhodel

**Comment by GBonnaire** [comment]
Please open new issue. And expose your problem, with example and code
