### ISSUE TITLE
v3 "Use strict" and "Let" identifier

### ISSUE THREAD

**Issue by rom-melnik** [jspreadsheet/ce#580]
We want to initialize jExcel script dynamically (not in the `<head>` tag) and it creates a error.

jExcel uses `"use strict"` directive.
In [code](https://github.com/paulhodel/jexcel/blob/master/dist/jexcel.js#L1298), jExcel have the declaration of the variable with `let` identifier.

According to [Mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode):
> But strict mode code on the web, loaded with <script src=""> or <script>...</script>, won't be able to use let/yield as identifiers

**Solution:**
Change `let` identifier to `var` in [line](https://github.com/paulhodel/jexcel/blob/master/dist/jexcel.js#L1298).

**Comment by pphod** [comment]
It has been fixed.
