### ISSUE TITLE
Cell Level Picklists/Dropdown Lists

### ISSUE THREAD

**Issue by BrentHackers** [jspreadsheet/ce#582]
@paulhodel Is there currently a way to have two pick-lists on the same column in specific cells with different available values?  If this can be / has been done in a jexcel spreadsheet, could someone share how?  If this is not supported, is it an outside case or would it be useful to others as an enhancement?

Work Type | Resource
-- | --
Room A | List Values: Machine 1, Machine 2, Machine 3
Room B | Machine 4, Machine 5
Room C | Machine 6, Machine 7

EDIT:
I could easily be wrong (do correct me) but it looks like what I'm asking about isn't possible with the available functions.  Seems like e.g. the cell _type_ property is always set at the **column** level with no way to change drop-down values etc. at the **cell** level?  And... it seems like it would be mega far from trivial to change that.  Altering core objects and functions, shifting properties and amending countless specific references to the column type, and likely a bunch of stuff I haven't even thought of?

**Comment by pphod** [comment]
You need to use the filter method column definition:

```
var data2 = [
    ['Cheese', true],
    ['Apples', true],
    ['Carrots', true],
    ['Oranges', false],
];

dropdownFilter = function(instance, cell, c, r, source) {
    // This method populate the dropdown with what is the return array
    if (c == 1 && row == 2) {
        return ['Apples','Bananas','Oranges'];
    } else if (c == 1 && row == 3) {
        return ['Carrots'];
    }
}

var allPossibleDropdownOptions = [ 'Apples', 'Bananas', 'Carrots', 'Oranges', 'Cheese' ];

jexcel(document.getElementById('spreadsheet2'), {
    data:data2,
    columns: [
        { type:'dropdown', title:'Food', width:'200', source: allPossibleDropdownOptions, filter:dropdownFilter },
        { type: 'checkbox', title:'Buy', width:'100' },
    ]
});

```

**Comment by pphod** [comment]
If you would like to show the values in a dropdown column based on the value in another column.

```
<html>
<script src="https://bossanova.uk/jexcel/v3/jexcel.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jexcel/v3/jexcel.css" type="text/css" />

<script src="https://bossanova.uk/jsuites/v2/jsuites.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jsuites/v2/jsuites.css" type="text/css" />

<div id="spreadsheet2"></div>

<script>
var data2 = [
    [3, 'Cheese', true],
    [1, 'Apples', true],
    [2, 'Carrots', true],
    [1, 'Oranges', false],
];

dropdownFilter = function(instance, cell, c, r, source) {
    var value = instance.jexcel.getValueFromCoords(c - 1, r);
    if (value == 1) {
        return ['Apples','Bananas','Oranges'];
    } else if (value == 2) {
        return ['Carrots'];
    } else {
        return source;
    }
}

jexcel(document.getElementById('spreadsheet2'), {
    data:data2,
    columns: [
        { type:'dropdown', title:'Category', width:'300', source:[ {'id':'1', 'name':'Fruits'}, {'id':'2', 'name':'Legumes'}, {'id':'3', 'name':'General Food'} ] },
        { type:'dropdown', title:'Food', width:'200', source:['Apples','Bananas','Carrots','Oranges','Cheese'], filter:dropdownFilter },
        { type: 'checkbox', title:'Buy', width:'100' },
    ],
    onchange:function(instance, cell, c, r, value) {
        if (c == 0) {
            var columnName = jexcel.getColumnNameFromId([c + 1, r]);
            instance.jexcel.setValue(columnName, '');
        }
    }
});
<script>
</html>
```

More examples:

https://bossanova.uk/jexcel/v3/examples/dropdown-and-autocomplete

**Comment by BrentHackers** [comment]
Thanks.  I'll give it a go.

EDIT:
@paulhodel 
Ok.  Not only did that work just fine straight away, but it was scarily easy and intuitive...  

![Gratitude](https://user-images.githubusercontent.com/54025495/64694059-b0512d80-d490-11e9-91e8-41f547e4bf62.PNG)

Thanks very much for the (embarrassingly) much needed help!

With that, I think I could use jExcel to replace the majority of the spreadsheet solutions that I support, but Is there a similar example somewhere for doing the same thing but pivoted so that I can have drop-downs across rows rather than in columns?  I have use cases where the number of fields is rather immense (mock example below) and pivoting would make for a nightmarish UI.

![EXAMPLE](https://user-images.githubusercontent.com/54025495/64696189-b5fd4200-d495-11e9-8186-bb1426f7bbe4.PNG)

I promise I did try to find one and I'm trying to figure this out for myself.  I'm daft, not lazy...
