### ISSUE TITLE
Toolbar icon color not working

### ISSUE THREAD

**Issue by ponyEdp** [jspreadsheet/ce#595]
Good morning
If I do this 
// toolbar
            toolbar: [
                { type: 'i', content: 'undo', onclick: function () { mySheet.undo(); }, tooltip: 'Annullare' },
                { type: 'i', content: 'redo', onclick: function () { mySheet.redo(); }, tooltip: 'Ripetere'},
                { type: 'i', content: 'cloud_download', onclick: function () { mySheet.download(); }, k: 'color', v: '#0099ff;', tooltip: 'Salva in excel' }, // download
                { type: 'i', content: 'refresh', onclick: function () { mySheet.setData(null); }, k: 'color', v: '#00cc00;', tooltip: 'Aggiorna' }  // ricarica la finestra con quello che c'è in memoria attualmente
            ],
the color of the icon will not change.
To change che icon color I must modify the jexcel.js like this:
 if (toolbar[i].type == 'i') {
                var toolbarItem = document.createElement('i');
                toolbarItem.classList.add('jexcel_toolbar_item');
                toolbarItem.classList.add('material-icons');
                /*  code with bug
                toolbarItem.setAttribute('data-k', toolbar[i].k);
                toolbarItem.setAttribute('data-v', toolbar[i].v);   */
                toolbarItem.setAttribute("style", toolbar[i].k + ": " + toolbar[i].v); // right code

**Comment by pphod** [comment]
I am not even sure which version are you using. But, I have tested now, and the color is being applied correctly.

http://localhost:8002/jexcel/v3/examples/spreadsheet-toolbars

Regards,
