### ISSUE TITLE
error when calling getData on empty array

### ISSUE THREAD

**Issue by apanagio** [jspreadsheet/ce#598]
If you populate the grid with empty data ( data: [ ] ) and later you call getData() on the grid, an error is thrown.
This doesn't happen with data: undefined, or data: [[ ]]

https://jsfiddle.net/zat8e4d7/2/

**Comment by pphod** [comment]
data: null,
data:[[]],

should be valid.

data:[] // invalid

**Comment by apanagio** [comment]
data: null 
throws an error on the creation of the grid (as well as data: undefined that i wrongly said it didn't)

IMHO 
if a value is invalid like data: [ ] then the error should be thrown at the creation of the grid. However I don't see a way to create a grid with 0 lines.
Moreover data: [ ] is very handy since it can be the result of a chain of operations like array1.filter(...).map(...)

**Comment by pphod** [comment]
I am going to follow your suggestion and be more flexible on the data init directive. I am going to reopen the issue to incorporate that in the next release.

**Comment by pphod** [comment]
It has been done.
