### ISSUE TITLE
Using showIndex(), hideIndex()

### ISSUE THREAD

**Issue by ScottishDarren** [jspreadsheet/ce#599]
Hi,

This is probably a stupid question but how do I actually use showIndex(), hideIndex()? I've tried it in the instance settings (`hideIndex:false`), and also as a callback feature (which throws an error _hideIndex is not a function_) eg:

```
var loaded = function(instance) {
    console.log('New data is loaded');
    instance.hideIndex();
}
```

It's probably something obvious but I'm going around in circles here.

Thanks in advance for any pointers.

**Comment by pphod** [comment]
This is to hide the Autonumerical index column. This is a demo how to use it.
https://jsfiddle.net/2zyL3utf/1/

```
<html>
<script src="https://bossanova.uk/jexcel/v3/jexcel.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jexcel/v3/jexcel.css" type="text/css" />

<script src="https://bossanova.uk/jsuites/v2/jsuites.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jsuites/v2/jsuites.css" type="text/css" />

<div id="spreadsheet"></div>

<script>
var data = [
    ['Jazz', 'Honda', '2019-02-12', '', true, '$ 2.000,00', '#777700'],
    ['Civic', 'Honda', '2018-07-11', '', true, '$ 4.000,01', '#007777'],
];

var table = jexcel(document.getElementById('spreadsheet'), {
    data:data,
    columns: [
        { type: 'text', title:'Car', width:120 },
        { type: 'dropdown', title:'Make', width:200, source:[ "Alfa Romeo", "Audi", "Bmw" ] },
        { type: 'calendar', title:'Available', width:200 },
        { type: 'image', title:'Photo', width:120 },
        { type: 'checkbox', title:'Stock', width:80 },
        { type: 'numeric', title:'Price', width:100, mask:'$ #.##,00', decimal:',' },
        { type: 'color', width:100, render:'square', }
     ]
});
</script>

<input type='button' onclick='table.hideIndex()' value='Hide index column'>
<input type='button' onclick='table.showIndex()' value='Show index column'>
</html>
```

**Comment by ScottishDarren** [comment]
Thanks Paul - makes perfect sense now. This would be great as a config option.

For reference if anybody needs it in the future, and following the examples on https://bossanova.uk/jexcel/v3/ I used the `onload: loaded` parameter to call this function:

```
var loaded = function(instance) {
    console.log('New data is loaded');
    maintool.hideIndex();
}
```
Also works fine with nestedHeaders.

As an aside, this library is utterly fantastic, the work that must have went into it is incredible - thank you!

**Comment by pphod** [comment]
Just as reference:

var loaded = function(instance) {
    console.log('New data is loaded');
    instance.jexcel.hideIndex();
}

In the next version, you also can do that:

var loaded = function(instance, obj) {
    console.log('New data is loaded');
    obj.hideIndex();
}
