### ISSUE TITLE
can we use the excel file directly to show on web page ? 

### ISSUE THREAD

**Issue by gulshan-escalon** [jspreadsheet/ce#6]
Hi Paul,

Currently I am using the csv file to show the data but I also I want to integrate that jexcel with the spreadsheet also. So if you have any solution ?

Thanks

**Comment by pphod** [comment]
In the server side you can use an API to convert your spreadsheet into JSON or CSV. There is a very good library it might help: PHPExcel.

**Comment by gulshan-escalon** [comment]
Ok , I will try , One more thing there is any event when user click on the excel_label like (A,B). I want to pick all the values for that columns and store it to database. But If I add one new column then It will automaticaly reflect into the range of graph . 
For Example : Initially Column A have 3 values, Now user click on the A label then I do store three value in the database. But after some time csv file is changed with 4 value in the end then i want graph show the 4th value as well. Any solution for that ?

**Comment by pphod** [comment]
You can use: oncellselection as shown on the link below. If you click on the header, it will select all cells on the column and the method a method will be triggered, sending the first and last cell coordinates.
http://jsfiddle.net/wwvvygxv/1/

**Comment by gulshan-escalon** [comment]
Yes , I have also implemented this but my question is to how can i know if weather the click is on header(labels) or its manually cells selections ?

**Comment by pphod** [comment]
http://jsfiddle.net/dght8v59/ Please update from repository, you can find a new argument in the method to inform you when the click come from headers.

**Comment by gulshan-escalon** [comment]
Hi Paul , 

I am using the jquery.jexcel.js file but Now I checked in the repository there is no file of that name. so what should i change it ?
