### ISSUE TITLE
Fixed header & columns

### ISSUE THREAD

**Issue by Arkzv** [jspreadsheet/ce#60]
Paul,
There is a nice cross browser plugin that works well with your one. It is able to fix columns and header simultaneously and performs nice on the large datasets ( > 10k cells). May make sense to integrate it instead of developing the same again..
https://github.com/configit/sticky-table

It works out of the box
```
var loaded = function(instance) {
      $('#spreadsheet' ).sticky( {
          cellWidth: 100,
          columnCount: 1
      } );
   };
```

**Comment by mtnburgos** [comment]
Hi Arkzv, 
This is a very important feature, I hope it will take into account.
¿Do you have any notes (HTLM + JS) on how to do that?

Thanks in advance.

**Comment by pphod** [comment]
The new version 1.5.1 includes this feature, please see the example:
https://bossanova.uk/jexcel/examples/table-with-fixed-headers

**Comment by PragnaBrahmbhatt** [comment]
Paul, In above example it fix the header but what about to fix the column?
 If we wants to do below thing with JExcel then which method needs to use?
`$('table').sticky( {columnCount: 2} );`
