### ISSUE TITLE
Update scroll position based on the selection

### ISSUE THREAD

**Issue by AilsaLe** [jspreadsheet/ce#600]
Hello~
 tried to select multiple cells， but I found that the scrollLeft could't slide automatically when  mouse moves to the right edge of the container. can you help me？

**Comment by pphod** [comment]
Are you using tableOverflow: true?

**Comment by AilsaLe** [comment]
Yes,but it does't work...

**Comment by rcris92** [comment]
Hi there,

I'm having the same issue and I also need the same functionality when scrolling vertically.
Do you have any solution or can you suggest any workaround?

Thanks.
