### ISSUE TITLE
jExcel logo not appearing

### ISSUE THREAD

**Issue by seth-shaw-unlv** [jspreadsheet/ce#602]
The jExcel logo is not appearing when using the library on other sites because [the logo URL is relative](https://github.com/paulhodel/jexcel/blob/master/dist/jexcel.js#L476) rather than absolute. I.e. `<img src="//bossanova.uk/jexcel/logo.png">` should be `<img src="http://bossanova.uk/jexcel/logo.png">`.

That stated, I would rather have a smaller badge. Somewhere in the 20x90 px size like the [Github/Travis build status bage](https://camo.githubusercontent.com/090cf723c9e1f4a345104dabea3ebe12495a1965/68747470733a2f2f7472617669732d63692e6f72672f49736c616e646f72612d434c41572f69736c616e646f72612e706e673f6272616e63683d382e782d312e78).

Sure, I don't _need_ this issue fix (I just get a twinge when I see the error in my console during dev); but hey, credit where credit is due.

**Comment by pphod** [comment]
Thanks seth, we decided to keep all visible reference in the right-click for now. Today is an JS alert, but we can move to a modal, with a logo a briefy description with a better looking.

Regards,
