### ISSUE TITLE
Error displaying search results in IE11

### ISSUE THREAD

**Issue by prwvm** [jspreadsheet/ce#606]
IE11 produces unexpected behaviour when using the search.
When a search is performed the table is cleared and the expected results are not always appended.

Current:
```
// Hide all records from the table
obj.tbody.innerHTML = '';
```

Solution:
```
// Hide all records from the table
// Comment out/ remove to resolve in IE11
// obj.tbody.innerHTML = '';
```

**Comment by AnaOrtega1** [comment]
I commented that line and replaced it with the code below
//obj.tbody.innerHTML = '';
while (obj.tbody.childNodes.length > 1) {
            obj.tbody.removeChild(obj.tbody.childNodes[0]);
        }

**Comment by pphod** [comment]
Thanks, I have fixed that. It will be available in the repository soon.

**Comment by prwvm** [comment]
Many thanks.
