### ISSUE TITLE
'setData' function with 0 didn't show.

### ISSUE THREAD

**Issue by TsePakKwan** [jspreadsheet/ce#607]
hi @paulhodel 
I have some problem about 'setData' function.

please refer as below jsfiddle.
https://jsfiddle.net/tsepakkwan/fo4wx32j/2/
when I press set my data button, then will set the data with use 'setData' function.
some cell value is zero, value do not show on cell. 
However, when I double click the cell talent to display the value. 
How can I fix it?

![1569396704692](https://user-images.githubusercontent.com/51103712/65579102-04d8ca80-dfb2-11e9-91e9-0eb0e6a5d426.gif)

PS
when I remove below setting, then will normally show the zero value, is it BUG?
```
        {
          mask: ' #,##',
          decimal: '.',
        },
```

**Comment by pphod** [comment]
Try to add quotes on the data.

Best regards,
