### ISSUE TITLE
working directly with JSON

### ISSUE THREAD

**Issue by cstarling** [jspreadsheet/ce#61]
Hello! I am starting out with jexcel and I love it! I am wondering is there any support to load data into the table as json? If this is not the correct place for this please let me know!

I have tried the following code:
```
$('#my').jexcel({
    url:'http://localhost:8080/partners.json',
    colHeaders: ['a' ,'b', 'c', 'd', 'e']
  });
```

and it seems to only show the amount of json objects that are located at that url.  I have dug into your example [of programmatically-changes](http://www.bossanova.uk/jexcel/docs/programmatically-changes) specifically this example:
```
setData: Update the table data
@Param json newData - New json data, null will reload what is in memory.
@Param boolean ignoreSpare - ignore configuration of minimal spareColumn/spareRows
```

In the console I dug down and see that button is tied to this:

```
$('#setDataButton').click(function () {
    data2 = [
        ['My car', 2001, 2000, '2006-01-01'],
        ['Test', 2010, 5000, '2005-01-01']
    ];
    $('#my').jexcel('setData', data2);
});
```

Which isn't json.

In the end I really like this plugin but curious as to if it is possible to load JSON data into the table?

**Comment by pphod** [comment]
This should work, but bear in mind to CROSS-DOMAIN issues.

**Comment by cstarling** [comment]
Thanks for the response, it is much appreciated!  I have control over the service that serves http://localhost:8080/partners.json and have enabled CORS on that endpoint.  I can get the data to the javascript/html no problem, but it seems like the table doesn't want to table the data.  

For reference the the /partners url is returning a list of 7 partner objects that look like this:

```
{
"partnerId": 25,
"partnerEntitlementTier": "rghrh",
"partnerMediaIdHome": 234,
"partnerMediaIdMobile": null,
"partnerName": "345",
"partnerProductName": "345",
"partnerStationIdHome": 345,
"partnerStationIdMobile": 234,
"prodBucket": "345",
}
```
And initializing the spreadsheet (slightly changed from above): 

```
$('#my').jexcel({
    url:'http://localhost:8080/partners.json',
    colHeaders: ['1' ,'2', '3', '4', '5', '6', '7', '8', '9']
  });
```


and the resulting table looks like this:
![screen shot 2017-10-25 at 5 50 15 pm](https://user-images.githubusercontent.com/14315532/32025195-455035b2-b9ad-11e7-8468-d92baefb3905.png)

So it seems like the table knows there are 7 objects but is not tabling their properties.  Is there something simple I missed?

**Comment by pphod** [comment]
Your data has the wrong format. Example:

[
["Tokyo",7,6.9,9.5,14.5,18.2,21.5,25.2,26.5,23.3,18.3,13.9,9.6],
["New York",-0.2,0.8,5.7,11.3,17,22,24.8,24.1,20.1,14.1,8.6,2.5],["Berlin",-0.9,0.6,3.5,8.4,13.5,17,18.6,17.9,14.3,9,3.9,1],["London",3.9,4.2,5.7,8.5,11.9,15.2,17,16.6,14.2,10.3,6.6,4.8]
]

**Comment by cstarling** [comment]
What you just posted is not json.  That is an array of arrays, which is different than json. I will assume json is not supported then?

**Comment by paulhodel** [comment]
[["Tokyo",7,6.9,9.5,14.5,18.2,21.5,25.2,26.5,23.3,18.3,13.9,9.6],["New York",-0.2,0.8,5.7,11.3,17,22,24.8,24.1,20.1,14.1,8.6,2.5],["Berlin",-0.9,0.6,3.5,8.4,13.5,17,18.6,17.9,14.3,9,3.9,1],["London",3.9,4.2,5.7,8.5,11.9,15.2,17,16.6,14.2,10.3,6.6,4.8]]

**Comment by vik17ag** [comment]
Hi,

Regarding the Json format, Can't it be in a key - value format? 

The order of columnHeader  array elements could be in a different order than that of row data. Having a key-pair format would take of the situation.

**Comment by manattweb** [comment]
Wondering if this issue has been addressed to allow regular JSON integration. My JSON data looks like this:

[{"campaignname": "New Basketball Gym","campaigngoal": 1000000},{"campaignname": "New Library","campaigngoal": 2000000}]

Do we need to programmatically convert the braces to brackets and strip out the keys?

**Comment by carson-nr** [comment]
Also arriving here under the same illusion.

Recommend explicitly saying in your examples:
"Accepts a two dimensional array of values defined in JSON format".

Just saying "It takes JSON" is not a complete explanation

With that being said, since this was closed, I guess I'm going to:
1. manually fetch the data from my server
2. get an array of keys from my column definition
3. convert array of JSON objects into 2d array of values, with the order being defined by my columns definition

Please understand that this is VERY misleading

**Comment by pphod** [comment]
We will include in the next release the support for that.

**Comment by carson-nr** [comment]
You're the man, Thank you!

**Comment by carson-nr** [comment]
Bonus points if you also accept xml format using the same concept, but that is just an idea

**Comment by pphod** [comment]
FINAL Solution, available on v3.5.1+

You can get the data from a local, or remote source. To get the data back in JSON.

table.getJson([boolean highlightedOnly]);

The name property in the columns directive is important and does not matter the order. If the name is not defined, the order would be numerical from 0 to whatever number of columns.

```
var table = jexcel(document.getElementById('spreadsheet'), {
        data:[
            { name:'Jorge', id:'3', age:'40' },
            { name:'Robert', id:'4', age:'48' },
            { name:'Santos', id:'5', age:'32' },
        ],
        columns: [
            { type:'text', width:300, name:'id' },
            { type:'text', width:100, name:'name' },
            { type:'text', width:100, name:'age' },
         ]
    });
```

**Comment by pphod** [comment]
The version is now available in the master repository and will be later on npm. Thank you for the suggestions. Let me know about any problems.

**Comment by pphod** [comment]
> Bonus points if you also accept xml format using the same concept, but that is just an idea

Hi Carson, thank you for the suggestion. I will keep that in mind for future releases.

**Comment by kira-07** [comment]
Hi Paul, I wish to work with Json data, an example:
![Sans titre1](https://user-images.githubusercontent.com/51085729/77421874-e4f15a80-6dcc-11ea-8095-e33c0af8262b.png)

I want to get:

![Sans titre](https://user-images.githubusercontent.com/51085729/77421789-b96e7000-6dcc-11ea-8c68-d7018fb14539.png)

Author columns contains two columns name and url. I see the nested header but I don't know combine with json.
It's possible? How I can do it?
