### ISSUE TITLE
Version 1.5.5 are very slow with large data

### ISSUE THREAD

**Issue by jpsarno** [jspreadsheet/ce#610]
Hello.

I know the version I'm using is obsolete, but would it be possible for this version to load large data faster? Or is the updated version recommended? Thank you very much. Your plugin is awesome.

Regards,
João

**Comment by pphod** [comment]
If you migrate to v3 you can use lazyLoading or pagination to help with that.
https://bossanova.uk/jexcel/v3/examples/lazy-loading

But, all depends on how many columns you are looking for, it will require different strategies.

**Comment by jpsarno** [comment]
Hello Paul.

Well, I have static 24 columns . And lines, 413 for more. Do you think update to the V3 is the best alternative?

I have another case with 788 lines.

Thanks a lot for your reply.

Regards,
João

**Comment by pphod** [comment]
Yes, the refactor is not big and there is so much advantage of using v3.

Regards,
