### ISSUE TITLE
input mask decimal setting problem

### ISSUE THREAD

**Issue by TsePakKwan** [jspreadsheet/ce#614]
hi @paulhodel 
relate #607 
> Try to add quotes on the data.
> 
> Best regards,

thank you, 'add quotes on the data' can fixed problem on numeric column. 
However, I have find other problem relate this case,when I use input mask 'decimal' setting will cause below problem.

1. if the cell value is negative values, it removes the negative sign. And formula column will show wrong result.
when I double click the cell talent to display the value with negative sign.
please refer below jsfiddle
https://jsfiddle.net/tsepakkwan/z5dqhLwm/
![03](https://user-images.githubusercontent.com/51103712/65732489-1a123e00-e105-11e9-9638-54b014c1bcc9.gif)

2. formulas column still do not show zero value on cell.
please refer below jsfiddle
https://jsfiddle.net/tsepakkwan/7vgnzo5p/
![01](https://user-images.githubusercontent.com/51103712/65732044-0665d800-e103-11e9-8cc9-3872370b3c9c.gif)

And also when I remove below input mask decimal setting, then will normally show the zero value.
![02](https://user-images.githubusercontent.com/51103712/65732081-301eff00-e103-11e9-955e-58eb72246ef8.gif)

**Comment by pphod** [comment]
This will be fixed soon.

**Comment by NomanChali** [comment]
i was also facing the same negative sign issue when using masking

below is the solution i have implemented

in the run of mask function which is in jsuites.js 
`obj.run = function (value, mask, decimal) {`

add below code block
```
if (value + valueDecimal < 0)
  values.unshift('-');
```
before below code
`return values.join('');`

or 

```
//add negative sign if value less then zero
                var sign = (value + valueDecimal < 0) ? -1 : 1;
                return sign * values.join('');
```

![image](https://user-images.githubusercontent.com/22465153/66027383-65b75400-e518-11e9-816a-615be98c5e46.png)

**Comment by NomanChali** [comment]
in the run of mask function which is in jsuites.js 
`obj.run = function (value, mask, decimal) {`

add below code block
```
if (value < 0)
  values.unshift('-');
```
before below code
`return values.join('');`

below is the whole code block
```
obj.run = function (value, mask, decimal) {
            if (value && mask) {
                if (!decimal) {
                    decimal = '.';
                }
                if (value == Number(value)) {
                    var number = ('' + value).split('.');
                    var value = number[0];
                    var valueDecimal = number[1];
                } else {
                    value = '' + value;
                }
                index = 0;
                values = [];
                // Create mask token
                obj.prepare(mask);
                // Current value
                var currentValue = value;
                if (currentValue) {
                    // Checking current value
                    for (var i = 0; i < currentValue.length; i++) {
                        if (currentValue[i] != null) {
                            obj.process(currentValue[i]);
                        }
                    }
                }
                if (valueDecimal) {
                    obj.process(decimal);
                    var currentValue = valueDecimal;
                    if (currentValue) {
                        // Checking current value
                        for (var i = 0; i < currentValue.length; i++) {
                            if (currentValue[i] != null) {
                                obj.process(currentValue[i]);
                            }
                        }
                    }
                }

               
> //added below code 
>  // Formatted value
>                 if (value < 0) 
>                     values.unshift('-');

                return values.join('');
            } else {
                return '';
            }
        }
```

**Comment by pphod** [comment]
This has been fixed. The mask should include: [-] as a signal number. More information
https://bossanova.uk/jsuites

**Comment by TsePakKwan** [comment]
> This has been fixed. The mask should include: [-] as a signal number. More information
> https://bossanova.uk/jsuites

hi @paulhodel 

could you please create a jsfiddle example for fix my problem?
I try to include: [-] as a signal number as below jsfiddle.  But I can't see any problem fixed.
https://jsfiddle.net/tsepakkwan/z5dqhLwm/6/

**Comment by TsePakKwan** [comment]
I already read 
https://bossanova.uk/jsuites
If my understanding is correct, This setting only turn all cells into negative numbers, not read data and if data is negative numbers to give a negative sign. but this cannot fix this issue, It is because no one knows whether the user entered a positive or negative number.
