### ISSUE TITLE
how to add a button in the first column

### ISSUE THREAD

**Issue by ppingliu** [jspreadsheet/ce#62]
hi Paul
 how can i add a button in the first column.
 because  i find i can add a checkbox, but can not add a button;

**Comment by pphod** [comment]
You can do something like:
$('#my').find('#1-2').html('\<button><\/button>');

Where 1-2 = second column, third row (since starting with in the zeros).

**Comment by ppingliu** [comment]
Thank you Paul
 so i need to create a cell  for insert button?
 can do this like insert a checkbox?

**Comment by pphod** [comment]
Unfortunately not.

**Comment by sasha-x** [comment]
Currently it works:

```js
var data3 = [
            ['Mazda', 2001, 2000],
            ['Pegeout', 2010, 5000],
            ['Honda Fit', 2009, 3000],
            ['Honda CRV', 2010, 6000],
        ];

        $('#my').jexcel({
            data: data3,
            colHeaders: ['Model', 'Year', 'Price', 'Action'],
            colWidths: [300, 80, 100, 200],
            onload: function(instanse){
                //for column №2
                $(instanse).find('td[data-x="1"][data-y]').html('<button>test</button>');
            }
        });
```

May be add to examples?
