### ISSUE TITLE
Undo and Redo

### ISSUE THREAD

**Issue by ponyEdp** [jspreadsheet/ce#620]
Good morning
Undo and Redo do not save information in the History records in case these changes the value in a cell.
Or also Undo and Redo do not fire onchange event.
I need do know the cells modified and the cells that are undo or redo to save in the database the only cells modified and not save all the cells that will take long time because the sheet has many cells.
Did you have a solution for this problem ?
Thanks.
Regards

**Comment by pphod** [comment]
I need to create a new event for that. It will be ready soon...

**Comment by pphod** [comment]
It is available onundo & onredo
