### ISSUE TITLE
Freeze Column

### ISSUE THREAD

**Issue by bilencekic** [jspreadsheet/ce#623]
Is there a way to freeze the column (aka pinning) ? I want to freeze first 4 column for example during scrolling, is it possible ? Here is a sample for AG grid, you can pin a column and it is fixed there during horizontal scrolling https://ag-grid.com/javascript-grid-pinning/ 
Thank you.

**Comment by pphod** [comment]
Sorry, unfortunately not available in the current version. We are considering that to be part of next releases.

**Comment by bilencekic** [comment]
perfect thanks :) also if you can add a visible attribute for a column, that would be great.
