### ISSUE TITLE
Import files from excel(xlsx). Cannot adjust width

### ISSUE THREAD

**Issue by sxmny123** [jspreadsheet/ce#624]
![image](https://user-images.githubusercontent.com/8567263/65842611-550fae00-e35f-11e9-87e1-c39f003bfa70.png)
![image](https://user-images.githubusercontent.com/8567263/65842614-57720800-e35f-11e9-82ef-4a8b86f8ce0f.png)
![image](https://user-images.githubusercontent.com/8567263/65842616-5b058f00-e35f-11e9-9aa0-4817055310c3.png)

**Comment by TsePakKwan** [comment]
you can use setWidth() function.
detail please see relate doc
https://bossanova.uk/jexcel/v3/docs/quick-reference

**Comment by pphod** [comment]
The XLSX importer is through a third party library SheetJS. Basically, this third party plugin gets the width and create an object to be inject in jExcel. At your side, it seems sheetjs were unable to parse the width from the original excel file. So, in this case the only thing I can do is prevent the error if the object is blank to avoid the error in the console.

For more options, I suggest you go through their documentation.
