### ISSUE TITLE
Custom column type with 'Enter' key / 'Tab' key

### ISSUE THREAD

**Issue by TsePakKwan** [jspreadsheet/ce#625]
Hi, @paulhodel 

I try to use Jexcel V3 Custom column type, then have some custom problem need your help.
on default column type when press  'Enter' key / 'Tab' key then will auto close current cell editor then go to Next Row/Column. 
However, on custom column type, when I open editor then do below action
1. press  'Enter' key , then will no any action,
2. press  'Tab' Key then will scroll to top.

How can I do the same action in the "Enter" / "Tab" keys of the default column type and custom column type?Is custom  'keyDown' Controller?

refer your example, first open the editor, then press 'Enter' key and press 'tab' key.
https://bossanova.uk/jexcel/v3/examples/column-types

![1569814700908](https://user-images.githubusercontent.com/51103712/65848075-518c1f00-e37f-11e9-9296-4de0feac9ec7.gif)

**Comment by javiercani** [comment]
I have same issue with my custom column. Also, when i copy from excel and paste it in jexcel table, values does not update on custom column. Did you solve this?

**Comment by pphod** [comment]
I guess this has been fixed on the pro Distribution and improved on the CE, which should get a new custom editor template soon.
