### ISSUE TITLE
Preventing users from deleting data from selected cells?

### ISSUE THREAD

**Issue by ScottishDarren** [jspreadsheet/ce#627]
I've been playing with various settings but haven't quite got this working. Is it possible to prevent users from deleting data from a selection?

The use case being a user selects a range of cells then hits delete, potentially wiping out a lot of important data. Is there a combination of settings or a method that prevent users from deleting data from multiple cells at once? A short 1 minute video is here to try and explain:  https://www.screencast.com/t/cmwaWlr8z6

Many thanks.

**Comment by pphod** [comment]
You can use onbeforechange to overwrite user action. Basically, when deleted is pressed the cells are set to BLANKS, so if you use onbeforechange you can return overwrite the BLANK to keep the same values. Let me know if this is clear.
