### ISSUE TITLE
formula problem

### ISSUE THREAD

**Issue by TsePakKwan** [jspreadsheet/ce#629]
hi @paulhodel 

please refer below jsfiddle.
https://jsfiddle.net/tsepakkwan/sL8fa2tq/
on D3 formula 
'=B3*C3' =>  128.2 * 1800 expected result is 230760.
but actual results is 230759.99999997

I think this is [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754) problem,
you can use BigNumber.js lib ([github](https://github.com/MikeMcl/bignumber.js)) to fixed this problem.

**Comment by pphod** [comment]
Sorry, jExcel will only take the formula and eval that. If you want to customize and use a library you should do that by a custom formula.
