### ISSUE TITLE
onblur and onfocus handlers?

### ISSUE THREAD

**Issue by b747fp** [jspreadsheet/ce#63]
I am able to get onchange  handler working, but "onblur: function(){ .... }"   and   "onfocus: function(){ .... }"  are not doing anything... How do i go about utilizing onblur and onfocus event handling?

**Comment by pphod** [comment]
Do you have the most recent version? It is working as example below:
http://www.bossanova.uk/jexcel/examples/tracking-changes-on-the-spreadsheet
