### ISSUE TITLE
Bug :  Cannot enter a decimal point with the numeric keypad

### ISSUE THREAD

**Issue by Lockey45** [jspreadsheet/ce#630]
I am need to mask a cell for dollars and cents.  I want the number, a decimal point, and 2 decimal digits such as : 454.27

I can enter a value with a decimal point using the main keys on the keyboard.  However, I cannot
enter a decimal point using the decimal point key from the numeric keypad.  I have verified that this is not a hardware or numlock issue.  

I have created a JSFiddle at https://jsfiddle.net/johnlock42/ek20uzqc/1/

To demonstrate the issue, run the fiddle and try to enter a value such as 25.45 in the price column.

**Comment by Lockey45** [comment]
When using a <b>mask</b> as shown in my sample jsfiddle https://jsfiddle.net/johnlock42/ek20uzqc/1/  I was unable to enter a decimal digit and a 0digit from the numeric keypad.

After debugging the code I discovered the following:

(1) a keypress on the 0digit in the numeric keypad was ignored.  
(2) a keypress on the decimal point key on the numeric keypad was ignored.


Issue (1) The  fromKeyCode method in jsuites.js (line 3327) was missing a KeyCode mapping for the decimal key on the numeric key pad .

Fix: Added the following mapping:

    obj.fromKeyCode = function(e) {
        var _to_ascii = {
            '188': '44',
            '109': '45',
            '110': '46',    //added this line to detect the decimal key
            '190': '46',
            '191': '47',
            '192': '96',
            '220': '92',
            '222': '39',
            '221': '93',
            '219': '91',
            '173': '45',
            '187': '61', //IE Key codes
            '186': '59', //IE Key codes
            '189': '45'  //IE Key codes


Issue(2) In the keydownControls method of jexcel.js, the 0digit key was not being tested so the cell editor would never open.

Fix:  Added the test condition (e.keyCode <=96)  to the if block below:

               } else {
                    if (jexcel.current.selectedCell) {
                        if (jexcel.current.options.editable == true) {
                            var rowId = jexcel.current.selectedCell[1];
                            var columnId = jexcel.current.selectedCell[0];

                            // If is not readonly
                            if (jexcel.current.options.columns[columnId].type != 'readonly') {
                                // Characters able to start a edition
                                if (e.keyCode == 32) {
                                    // Space
                                    if (jexcel.current.options.columns[columnId].type == 'checkbox' ||
                                        jexcel.current.options.columns[columnId].type == 'radio') {
                                        e.preventDefault();
                                    } else {
                                        // Start edition
                                        jexcel.current.openEditor(jexcel.current.records[rowId][columnId], true);
                                    }
                                } else if (e.keyCode == 113) {
                                    // Start edition with current content F2
                                    jexcel.current.openEditor(jexcel.current.records[rowId][columnId], false);
                                } else if ((e.keyCode == 8) ||
                                           (e.keyCode >= 48 && e.keyCode <= 57) ||  
                                           (e.keyCode <=96)  ||
                                           (e.keyCode == 187) ||
                                           (jexcel.validLetter(String.fromCharCode(e.keyCode)))) {
                                    // Start edition
                                    jexcel.current.openEditor(jexcel.current.records[rowId][columnId], true);
                                    // Prevent entries in the calendar
                                    if (jexcel.current.options.columns[columnId].type == 'calendar') {
                                        e.preventDefault();
                                    }
                                }
                            }
                        }
                    }
                }

**Comment by pphod** [comment]
it will be fixed now.

**Comment by solsticesurfer** [comment]
In the suggested fix above, the line `(e.keyCode <=96)  ||` should be `(e.keyCode ==96)  ||`

The `<=` check causes the escape key to be ignored

**Comment by pphod** [comment]
it has been fixed.

**Comment by krosoftware** [comment]
Hello, using same Jsfiddle (https://jsfiddle.net/johnlock42/ek20uzqc/1/) I can not enter decimal using numeric keypad.

**Comment by jordan-lumley** [comment]
Any know of a good fix for this? Currently running into the same issue.

**Comment by krosoftware** [comment]
Same here, still can not use keypad..

**Comment by lestradar11** [comment]
I think your code is to poor in all aspects
