### ISSUE TITLE
Lost the cells styles after call mySheet.setData(null);

### ISSUE THREAD

**Issue by ponyEdp** [jspreadsheet/ce#631]
Good morning
After i call this:
mySheet.setData(null);

the data are refreshed but I lost all the cell styles that I have set when I load Jexcel with the function:
updateTable: function (instance, cell, col, row, val, label, cellName) {
....
}
May you tell me what am I do to setup again the cells styles ?
Thanks
Regards

**Comment by pphod** [comment]
First, can you explain why you need to call setData(null)?

**Comment by ponyEdp** [comment]
I need to refresh jExcel and I'm using this command in the toolbar
toolbar: [
{ type: 'i', content: 'refresh', onclick: function () { RefreshData(); }, k: 'color', v: '#00cc00;', tooltip: 'Aggiorna' },   
],
to refresh it.

function RefreshData() {
            mySheet.setData(null);
        }


![localhost_53473_PrivatePU_IndexTranslate - Google Chrome 2019-10-03 15-04-38](https://user-images.githubusercontent.com/55495773/66129266-db422380-e5ef-11e9-9549-d731a6e5c0ea.gif)

**Comment by pphod** [comment]
I am not sure why will refresh your data to the same data. But, if you want to do that. You can get the style and apply it back.

var currentStyle = yourTable.getSyle();
yourTable.setData(null);
// after loading the data
yourTable.setStyle(currentStyle);
