### ISSUE TITLE
Issue related to getting data corresponding to header in jexcel v3

### ISSUE THREAD

**Issue by Harsh-baghel** [jspreadsheet/ce#633]
Hi Paul,

How can i get the particular row data corresponding to the header using jexcel v3 plugin.
Like my header are company name, website,email so i want data like this company name-Ideapoke Technology, website- www.ideapoke.com , email- info@ideapoke.com in the json format.
Is there any way to get data like this please suggest me any idea related to my query.

Thanks in advance

**Comment by pphod** [comment]
You can get the header by:

var myHeaders = yourTableInstance.getHeaders();
