### ISSUE TITLE
B3 value=A1, but B3 only displays numbers, others are filtered out? The V2 version does not have this problem. Is this a bug?

### ISSUE THREAD

**Issue by sxmny123** [jspreadsheet/ce#635]
B3 value=A1, but B3 only displays numbers, others are filtered out? The V2 version does not have this problem. Is this a bug?
![image](https://user-images.githubusercontent.com/8567263/66211187-188cdb00-e6ee-11e9-9e6f-a5ada6a948c7.png)
![Uploading QQ图片20191004213230.png…]()

**Comment by pphod** [comment]
do you have the most recent version?

**Comment by sxmny123** [comment]
I am testing on your Examples；You should be the latest here.
Https://bossanova.uk/jexcel/v3/examples/jquery
![image](https://user-images.githubusercontent.com/8567263/66214332-162d7f80-e6f4-11e9-83cf-b26231143bff.png)

**Comment by pphod** [comment]
You can use autoCasting: false to avoid that.
