### ISSUE TITLE
About custom formula

### ISSUE THREAD

**Issue by TsePakKwan** [jspreadsheet/ce#636]
hi @paulhodel 
relate case #629.

I am going to try custom formula,please refer below jsfiddle
https://jsfiddle.net/tsepakkwan/apdsv4Lg/14/
I try to modify your [example](
https://bossanova.uk/jexcel/v3/examples/spreadsheet-formulas) to my case.However, this features cannot suitable for my case.
for example,when I custom my sum formula, data is 'CUS_SUM (A1:A3)',then your parser will gen three value(A1,A2,A3) to my custom function.
But how many values will be used on the custom formula is not fixed, it may be 4, maybe 20.
![01](https://user-images.githubusercontent.com/51103712/66280376-64f43880-e8f1-11e9-91f8-73eb20dbbe2e.png)

Could you improve this to given more data for custom formula using?
 just like below.

```
var CUS_SUM = function(values) {
      /**
       * vaules just like as below
       *  values = [
       *  0 : [ cellName: 'A1', value: '1.1' ],
       *  1 : [ cellName: 'A2', value: '2.1' ],
       *  2 : [ cellName: 'A3', value: '3.5' ],
       *  3 : ..............
       *  ]
       */
      if ($.isArray(values) && values.length) {
        var v = 0;
        for (var i = 0; i < values.length; i++) {
          //use BigNumber.js
          v = new BigNumber(v).plus(values['value']);
        }
        return v + '';
      } else {
        return '#ERROR';
      }
    }

```

**Comment by pphod** [comment]
Please, refer to the original SUM:

```
    exports.SUM = function() {
        var result = 0;
        var argsKeys = Object.keys(arguments);
        for (var i = 0; i < argsKeys.length; ++i) {
            var elt = arguments[argsKeys[i]];
            if (typeof elt === 'number') {
                result += elt;
            } else if (typeof elt === 'string') {
                var parsed = parseFloat(elt);
                !isNaN(parsed) && (result += parsed);
            } else if (Array.isArray(elt)) {
                result += exports.SUM.apply(null, elt);
            }
        }
        return result;
    }
```

**Comment by TsePakKwan** [comment]
> Please, refer to the original SUM:
> 
> ```
>     exports.SUM = function() {
>         var result = 0;
>         var argsKeys = Object.keys(arguments);
>         for (var i = 0; i < argsKeys.length; ++i) {
>             var elt = arguments[argsKeys[i]];
>             if (typeof elt === 'number') {
>                 result += elt;
>             } else if (typeof elt === 'string') {
>                 var parsed = parseFloat(elt);
>                 !isNaN(parsed) && (result += parsed);
>             } else if (Array.isArray(elt)) {
>                 result += exports.SUM.apply(null, elt);
>             }
>         }
>         return result;
>     }
> ```

oh, I got it, thanks.
