### ISSUE TITLE
Issue related to toolbar

### ISSUE THREAD

**Issue by Harsh-baghel** [jspreadsheet/ce#641]
![Screenshot (247)](https://user-images.githubusercontent.com/54663901/66571613-3a261080-eb8d-11e9-8ca6-458db96a8ea5.png)
When i click to fill the background color for cell or row than color are not displaying but coloirng is happening only color is not showing insted its showing blank white space.Refer the schreenshot.

**Comment by pphod** [comment]
I am not sure if I understood that correctly. Can you kindly rephrase it, please? Can you check for errors in the console?

**Comment by Harsh-baghel** [comment]
When i going to fill the color then in toolbar i am click on format_color_fill. Than its showing white space No error is showing in console.Refer the image 1 and 2
1.![image](https://user-images.githubusercontent.com/54663901/66572441-9a698200-eb8e-11e9-8ef1-025968c90129.png)
2.
![Untitled](https://user-images.githubusercontent.com/54663901/66572661-00560980-eb8f-11e9-8c42-16fa95b92265.png)

**Comment by pphod** [comment]
It seems something related on your side. Take a look on this one.
https://bossanova.uk/jexcel/v3/examples/spreadsheet-toolbars

Please make sure you are using the most recent version, and all files are included correctly in your side.

**Comment by Harsh-baghel** [comment]
> It seems something related on your side. Take a look on this one.
> https://bossanova.uk/jexcel/v3/examples/spreadsheet-toolbars
> 
> Please make sure you are using the most recent version, and all files are included correctly in your side.
I check it is conflicting with my bootstrap.min.css.If i commenting my bootstrap.min.css than color is comming.

**Comment by Harsh-baghel** [comment]
I check it's conflicting with my bootstrap.min.js.If i removing the bootstrap.min.js than color is displaying.
Is there any idea to avoid the conflict.
