### ISSUE TITLE
Set cell focus issue

### ISSUE THREAD

**Issue by pramodsalian** [jspreadsheet/ce#643]
Hi Paul,
 following option allowed me to set the cell selected programatically table.updateSelectionFromCoords(x1,y1,x1,y1);

But problem it faces is, i cannot move to next cell using tab  or edit focused cell?. To make it work proper need to click that cell in order to move or edit.

Can we make cell directly editable by programmatically ?

**Comment by pphod** [comment]
For example, if you are calling table.updateSelectionFromCoords(x1,y1,x1,y1); using a onclick in a button. You must include "user-select: none;" on this button to avoid remove the focus from the table.

**Comment by sanju-js** [comment]
table2.updateSelectionFromCoords()
jexcel.current=table2;
