### ISSUE TITLE
Drag and drop columns Not Working on jExcel v3

### ISSUE THREAD

**Issue by jsue919** [jspreadsheet/ce#644]
Hi - I'm uisng jExcel v3. I'm not able to drag a column from position C to Position A. The drag and drop from rows works fine. Please help.

**Comment by pphod** [comment]
I have just tested, and it is working fine. Are you using the most recent version?

https://bossanova.uk/jexcel/v3/examples/events

**Comment by jsue919** [comment]
I see it the attribute now. Thanks.

Question- how do I freeze column A for better mobile usage?

**Comment by pphod** [comment]
Sorry, but freeze columns are not available at this point.
