### ISSUE TITLE
LazyLoading issue with multiple instance

### ISSUE THREAD

**Issue by bilencekic** [jspreadsheet/ce#646]
I have an issue with multiple instance jexcel on my page. On initial load of screen, lazy loading is working fine. Then i switch to tab2 and tab2 has another jexcel grid also working fine. When i come back tab1, i am destroying the jexcel and re-creating. In this case lazloading is stuck at 100. it doesn't move down. 
![Error](https://i.imgur.com/STOXSDE.png)

When i check above data-y it shows me 799 even i can see the row as 50 on screen. Due to wrong calculation, page does not scroll. Where can be the issue ?

**Comment by bilencekic** [comment]
i removed destroy event but put div clear for now it is working fine. IF you have a better solution please let me know.
	$("div_id").empty();
* <<<< init jExcel again here >>>>

**Comment by pphod** [comment]
Which method to destroy are you using?

**Comment by bilencekic** [comment]
i was using this one 
` jexcel.destroy(document.getElementById("div_id"));`
i am trying to display divs in a different way (by changing visibility). This is a workaround only, if there is a solution it would be perfect. It looks there is a variable or an element still not cleared and causing this issue. (if i never destroy and re-create jexcel, it is fine. LazyLoading is working fine on both grids)

**Comment by pphod** [comment]
I would recommend not to use destroy if you need just to hide and show.  Is there a way you just hide and show the tabs?

**Comment by bilencekic** [comment]
Alright, hide and show also works for me.
Thanks.
