### ISSUE TITLE
Get specific column and row value

### ISSUE THREAD

**Issue by krosoftware** [jspreadsheet/ce#647]
Hello
I have 5 rows and 4 columns where 4th column is hidden
4th column contains ID's: 10,20,30,40,50
How to get ID from 4th column if I click anywhere (on any cell)?
With other words, if I click on A2, I need to get 20
If I click on C4, I need to get 40 etc.
Thank you.

**Comment by pphod** [comment]
Use the event, onselection.

Inside the event you can use getValue to get the forth column value, split by comman and you can use your value.

**Comment by krosoftware** [comment]
Thanks but what means "str compatible with excel, or as object"? Thank you.

**Comment by pphod** [comment]
sorry, I did not understand your question.

**Comment by krosoftware** [comment]
From the help:
getValue: get current cell value
@Param mixed cellIdent - str compatible with excel, or as object.
myTable.getValue([string]);

my question is - what I need to put instead of [string] to get fourth column value?
Thank you.

**Comment by pphod** [comment]
myTable.getValue('A1'); // for example

**Comment by krosoftware** [comment]
OK my fourth row is in D column so it would be
myTable.getValue('D1');
but how to get row ID (in your example it is 1)?

**Comment by krosoftware** [comment]
OK found it: console.log(table1.getValue('D'+y1));
Thank you.
