### ISSUE TITLE
Feature request - Set default height for all rows

### ISSUE THREAD

**Issue by krosoftware** [jspreadsheet/ce#648]
Please create option to set default height for all rows.
Thank you.

**Comment by pphod** [comment]
Actually, you can easily do that using CSS.

**Comment by krosoftware** [comment]
Yes, I see. Your component is amazing.

**Comment by lyassa** [comment]
Even though it is not difficult to set the rows height using CSS, I think it is still very convenient to have a "rowHeight" attribute. 

Here is how I set the row height using CSS:
```
<style>
#myTableDiv > div.jexcel_content > table > tbody > tr
{
  height: 50px;
}
</style>
```

compare that to:
```
rowHeight: "50px"
```
