### ISSUE TITLE
How to change the column type programatically..?

### ISSUE THREAD

**Issue by NithinKulal** [jspreadsheet/ce#65]
Can anyone help on this..?

**Comment by pphod** [comment]
$.fn.jexcel.defaults['yourTableId'].columns[0].type = 'text'; // Change first column to text.
// You must to adapt the data if is necessary and then reload the data.
$('#yourTableId').jexcel('setData');

**Comment by NithinKulal** [comment]
*Hi,*


Thanks, for the support..(y)








*-------------------------------------    Thanks & Regards*
*       Nithin Kumar D*

**Comment by Koushikphy** [comment]
How to do the same in version 3? I also need to update the column sources for drop-down dynamically.

**Comment by pphod** [comment]
instance.options.columns[colNumber].type
instance.options.columns[colNumber].source
