### ISSUE TITLE
wrong display about 'custom toolbar' when use 'tableOverflow' setting

### ISSUE THREAD

**Issue by TsePakKwan** [jspreadsheet/ce#650]
hi @paulhodel ,

I try to use custom toolbar, then find some wrong display about 'custom toolbar' . 
![1571104220318](https://user-images.githubusercontent.com/51103712/66793743-aad87e80-ef39-11e9-86fd-ee5b71bfd1bc.jpg)

please refer below jsfiddle, this is based of your [example ](https://bossanova.uk/jexcel/v3/examples/spreadsheet-toolbars) and only add
		`tableOverflow: true,` on setting.
https://jsfiddle.net/tsepakkwan/nyj8s30c/3/

**Comment by TsePakKwan** [comment]
I think can  fixed this problem when remove jexcel.css:80
![1571104220318](https://user-images.githubusercontent.com/51103712/66796580-1115cf00-ef43-11e9-90c8-7c28f25c46a9.jpg)

**Comment by pphod** [comment]
Thank you for that. It has been fixed in the master repo.
