### ISSUE TITLE
Issue Related to custom toolbar

### ISSUE THREAD

**Issue by Harsh-baghel** [jspreadsheet/ce#653]
I am using custom toolbar to color the particular row or column.But when i click format_color_fill then color is not displaying only white space is displaying.It is happening because of conflict of bootstrap.min.js. If i commenting my bootstrap.min.css than color is displaying.
![Screenshot (2)](https://user-images.githubusercontent.com/54663901/66819348-73c79480-ef5c-11e9-8cf5-6ae9c0d9a6a1.png)
Can u give suggestion how to avoid the conflict.

**Comment by pphod** [comment]
Can you please create jsfiddle? I can try to work in a general solution.

**Comment by TsePakKwan** [comment]
hi @paulhodel 

I have another question related to custom toolbar.
on custom toolbar type'i' ,How can I use my own icon?

tank you.

**Comment by pphod** [comment]
at this point is very couple with Google Material Icons. So, only if you customize jExcel code.

**Comment by Harsh-baghel** [comment]
Yes i find solution.
