### ISSUE TITLE
V3 - insertedRow Event /After and Before

### ISSUE THREAD

**Issue by jpsarno** [jspreadsheet/ce#657]
Hello.

In the V3 it is possible to differ the lines added after and before the selected row?

And it is possible to get  the number of  the new row added?

Thank you very much.

Regards,
João

**Comment by pphod** [comment]
Yes, you have onbeforeinsertrow you can use to get the current data. And
you have the oninsertrow after new rows being added. The latter will
provide several arguments. Numrows, num of the line, insert before flag, etc

**Comment by jpsarno** [comment]
Hello Paul, thanks for answer.

And the arguments for the oninsertrow, I can find them in the documentation?

**Comment by pphod** [comment]
Yes, and you can find examples in the website.

**Comment by jpsarno** [comment]
Sorry, I didn't find the examples with the parameters :(

Could you indicate?

Thanks a lot.

**Comment by jpsarno** [comment]
Sorry again Paul, now I guess I understood your explanation. 

But I still have a doubt. If I choose to include a new row After or Before, it is possible to differ the choose in the function event?

**Comment by pphod** [comment]
oninsertrow(el, rowNumber, numOfRows, rowRecords, insertBefore);

**Comment by jpsarno** [comment]
Thank you very much Paul. It will works for me. I will said again, the plugin is amazing!

BR,
João

**Comment by pphod** [comment]
Legal João! Qualquer coisa estamos por aqui.
Abraços,
