### ISSUE TITLE
Issue related to merge cells 

### ISSUE THREAD

**Issue by divyasreegopal** [jspreadsheet/ce#658]
While passing dynamic values to mergeCells:{mercellvalues} then it showing Cannot read property '6564177417250814' of undefined.
eg:-
mercellvalues=A2:[1,2],B3:[1,2]
But if i am hard coding merged cell value its taking can you give any suggestion how we can solve

**Comment by pphod** [comment]
To do that dynamically after the onload, you must apply the method setMerge.

table.setMerge('A3', 2, 2);
table.setMerge('D3', 2, 2);
etc...
