### ISSUE TITLE
Make possible to disable adding double quote when string includes comma

### ISSUE THREAD

**Issue by heiwais25** [jspreadsheet/ce#659]
Hello, I wonder if there is any chance to add option to enable or disable feature that adding double quote when string includes comma. 

Whenever I copy directly from the sheet, additional double quote makes me hard to handling the data even though I don't need csv formatting.

I search the code of jexcel and found if there is conditional statement in the `jexcel.js` 5163 line obj.copy function.

I always love this fantastic library. thank you.

**Comment by pphod** [comment]
Sorry, that won't be possible since will break compatibility with other software. But, to workaround is using oncopy event?
