### ISSUE TITLE
Requirements Definition

### ISSUE THREAD

**Issue by CME64** [jspreadsheet/ce#66]
please add the minimum requirements for your plugin as well as supported browser versions in the description.

**Comment by CME64** [comment]
I read your code, you should update the docs. there are really good things that need to be known to the user like hidden columns and row/column insert restrictions.

**Comment by pphod** [comment]
https://www.bossanova.uk/jexcel/docs/quick-reference

**Comment by CME64** [comment]
I have seen your docs already, I was talking about the features that were never mentioned like type: "hidden" or like how you can prevent column and row inserts ...etc
those things that I just knew from the source code not from the docs
