### ISSUE TITLE
Number formatting (mask)

### ISSUE THREAD

**Issue by krosoftware** [jspreadsheet/ce#660]
Hello
how to use numeric type to display number as
123.00
instead of
123?
Thank you

**Comment by pphod** [comment]
You can mask the column:

```
<html>
<script src="https://bossanova.uk/jexcel/v3/jexcel.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jexcel/v3/jexcel.css" type="text/css" />

<script src="https://bossanova.uk/jsuites/v2/jsuites.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jsuites/v2/jsuites.css" type="text/css" />

<div id="spreadsheet"></div>

<script>
var data = [
    ['Jazz', 'Honda', '2019-02-12', '', true, '$ 2.000,00', '#777700'],
    ['Civic', 'Honda', '2018-07-11', '', true, '$ 4.000,01', '#007777'],
];

jexcel(document.getElementById('spreadsheet'), {
    data:data,
    columns: [
        { type: 'text', title:'Car', width:120 },
        { type: 'dropdown', title:'Make', width:200, source:[ "Alfa Romeo", "Audi", "Bmw" ] },
        { type: 'calendar', title:'Available', width:200 },
        { type: 'image', title:'Photo', width:120 },
        { type: 'checkbox', title:'Stock', width:80 },
        { type: 'numeric', title:'Price', width:100, mask:'$ #.##,00', decimal:',' },
        { type: 'color', width:100, render:'square', }
     ]
});
</script>
</html>
```

**Comment by krosoftware** [comment]
Yes, I saw that, but if you write 123 (without .00) you will see 123
I expect that .00 is added automatically.
Thank you.

**Comment by pphod** [comment]
Example using ROUND.
https://jsfiddle.net/paulhodel/7xpLv1ow/3/

**Comment by krosoftware** [comment]
Thank you for example, it works when data is loaded, but if you write 123 (after load) it display 123 again (and I expect 123.00 because column have defined mask:'$ #,##.00'

**Comment by pphod** [comment]
In the example given if you clear the formula and place an integer, yes. But, you have a format processor you can use to customize behavior.

Example:
https://jsfiddle.net/paulhodel/zsg0mhLp/

**Comment by krosoftware** [comment]
Thank you again. 
Now column A display decimal values correctly but is there option that Total column (formula column) is displayed on same way (to display 123.00 instead of 123)?

**Comment by pphod** [comment]
Yes, just follow the logic and you have all the flexibility you are looking for.
https://bossanova.uk/jexcel/v3/examples/table-style

**Comment by krosoftware** [comment]
Thanks!
