### ISSUE TITLE
Sorting issue with 0 value rows

### ISSUE THREAD

**Issue by bilencekic** [jspreadsheet/ce#661]
I noticed an issue, during sorting if a value is 0. My case it is 0.00  ( i changed below condition result to 6 to see which condition is causing the issue)
![Sort issue](https://i.imgur.com/u29E3to.png)
I noticed when it is zero, in the first condition statement  was returning without checking if smaller or bigger. Actually it was treating it as '' only and this was leading to zero values not being sorted correctly. 

same issue you can find here, change some cells to zero and sort
https://bossanova.uk/jexcel/v3/examples/sorting

I added typeof check to make it correct;
![Sort issue](https://i.imgur.com/LdMZO4C.png)
now my sorting is working fine. Is that approach correct ?
Thank you.

**Comment by Ruan-Miguel** [comment]
This error has been resolved on v4
