### ISSUE TITLE
Merge Cells

### ISSUE THREAD

**Issue by MaDianYue** [jspreadsheet/ce#665]
Hi Paul.
I have a question for you. 
'HelloWorld' in 'D0'.There is data after the merger.
But 'HelloWorld' in 'E0' or 'F0',There is no data after the merger.
 I do not know how it is caused.

- [ ] <script>
- [ ]     var data = [ ['Jazz', '', '', 'HelloWorld', '', ''] ];
- [ ]     var table = jexcel(document.getElementById('spreadsheet'), {
- [ ]         data: data,
- [ ]         columns: [{ width: 120 }, { width: 120 }, { width: 120 }, { width: 120 }, { width: 120 }, { width: 120},]
- [ ]     });    
- [ ]     var firstMerge = 'A0';
- [ ]     var secondMerge = 'D0';    
- [ ]     table.setMerge(firstMerge, 3, 1);
- [ ]     table.setMerge(secondMerge, 3, 1);
- [ ] </script>

**Comment by pphod** [comment]
D0 does not exists. All starts with A1, B1, C1, D1, etc.

**Comment by MaDianYue** [comment]
if  'HelloWorld' in 'E1' or 'F1',There is no data after the merger.

var data = [
        ['Jazz'/*A1*/, ''/*B1*/, ''/*C1*/, ''/*D1*/, 'HelloWorld'/*E1*/, ''/*F1*/]
    ];
......
table.setMerge('D1', 3, 1);

**Comment by MaDianYue** [comment]
I don't know if it's bug, or that's what it was designed to be.

**Comment by pphod** [comment]
This is how was designed to be.

**Comment by MaDianYue** [comment]
Thank you for your help,Paul.
