### ISSUE TITLE
V.1.5.5 - InsertRowEvent - Callback

### ISSUE THREAD

**Issue by jpsarno** [jspreadsheet/ce#666]
Hello.

In the version 1.5.5 it is possible to get the number of the new row added?

Something like that: 

oninsertrow: insertedRow

var insertedRow = function (instance, rowNumber) {}

Thank you very much.

BR,
João

**Comment by pphod** [comment]
Joao, please update to the most recent versions.

Example:
https://bossanova.uk/jexcel/v3/examples/events

Thanks,

**Comment by jpsarno** [comment]
Hello Paul.

Yes, I´m using the latest version on a new page. But I have an old page with this version. The users still using that page and I would like to solve this little problem until the new page starts to work.

Thanks

**Comment by pphod** [comment]
Joao, I am not sure if the version has this event. But you can try.

**Comment by jpsarno** [comment]
Paul, the event is returning only one parameter.

Inside the code of JExcel v 1.5.7 exists the function:

 /**
     * Insert a new row
     * 
     * @param mixed - number of blank lines to be insert or a single array with the data of the new row
     * @param rowNumber
     * @return void
     */
    `insertRow : function(mixed, rowNumber) {`
        `// Main`
        `var main = $(this);`

        // Id
        var id = $(this).prop('id');

The function have two parameters, but when I try to use the function in my code:

`var insertRow = function (instance, rowNumber) `
{
               ` console.log(rowNumber);  `                              
                `executandoExibeResultado = 1;`
                `try `
               {
                   ` console.log('Row added: ' + rowNumber);`

                    AlterarLinhaNova(rowNumber);
                } catch (e) {
                }
                executandoExibeResultado = 0;
}

is returning:
undefined
Row added: undefined

Do you have any ideia what is happening?

**Comment by pphod** [comment]
you can search by: oninsertrow and the support of that was really bad. I really suggest you to move to v3, or to v2 in the most recent versions.
