### ISSUE TITLE
Freeze columns and rows

### ISSUE THREAD

**Issue by ponyEdp** [jspreadsheet/ce#667]
Good morning
I have read in some posts that is already in a roadmap of the feature request. 
May you have an idea when will be available ?
In the meantime we wait is there a solution ?
Thanks 
Regards

**Comment by pphod** [comment]
There is no timeline for freezedcolumns.

**Comment by ponyEdp** [comment]
Ok thanks. 
In a post it was write: 
_**Please use this library to fix columns
https://www.jqueryscript.net/demo/jQuery-Plugin-For-Fixed-Table-Header-Footer-Columns-TableHeadFixer/**_
May you make a jsfriddle, I need to freeze 2 columns and my Jexcel have 2 rows header.
Thanks.
![Immagine](https://user-images.githubusercontent.com/55495773/67373990-dafacf80-f580-11e9-85f2-1b4426601286.png)

**Comment by bilencekic** [comment]
@ponyEdp did you add filter for column header? how did you do that ?

**Comment by ponyEdp** [comment]
in jexcel.js add:

    var defaults = {
        // id table
        id: 'tableJxls',
        // filter on header
        headerfilter: false, 
       ....
        // Texts
        text: {

            okButton: 'Ok',                     
            cancelButton: 'Cancel',             
            orderByAZ: 'Order by ascending',    
            orderByZA: 'Order by descending',    
            filterByCondition: 'Filter by condition', 
            filterByCondition1: 'None',
            filterByCondition2: 'Is empty', 
            filterByCondition3: 'Is not empty',
            filterByCondition4: 'Is equal to',
            filterByCondition5: 'Is not equal to',
            filterByCondition6: 'Begins with',
            filterByCondition7: 'Ends with',
            filterByCondition8: 'Contains',
            filterByCondition9: 'Does not contains',
        },
....
    obj.popupFilter = null;     // Popup filtro sulla colonna: Gabriele 4-10-19
    obj.FilteredColumns = [];
...


Add In the function obj.createTable = function () {
....
        // ############################################
        // popup filter
        var popupFilterHtml = '';   // dim 
        popupFilterHtml += '<form method="post" id="formPopUp" autocomplete="off">';
        popupFilterHtml += '<div class="col-sm-12" style="text-align:left;"><button id="orderByAZ" type="button" class="btn btn-orderByAZ">' + obj.options.text.orderByAZ + '</button></div>';
        popupFilterHtml += '<div class="col-sm-12" style="text-align:left;"><button id="orderByZA" type="button" class="btn btn-orderByZA">' + obj.options.text.orderByZA + '</button></div>';
        // condizione di filtro
        popupFilterHtml += '<div class="dropdown">' + 
                                '<button class="btn dropdown-Filter dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">' + 
                                    obj.options.text.filterByCondition + 
                                '</button>' + 
                                ' <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">' + 
                                    '<li><a class="dropdown-item drp-filter" href="#">' + obj.options.text.filterByCondition1 + '</a></li>' + 
                                    '<li class="dropdown-divider"></li>' + 
                                    '<li><a class="dropdown-item drp-filter" href="#">' + obj.options.text.filterByCondition2 + '</a></li>' + 
                                    '<li><a class="dropdown-item drp-filter" href="#">' + obj.options.text.filterByCondition3 + '</a></li>' + 
                                    '<li class="dropdown-divider"></li>' + 
                                    '<li><a class="dropdown-item drp-filter" href="#">' + obj.options.text.filterByCondition4 + '</a></li>' + 
                                    '<li><a class="dropdown-item drp-filter" href="#">' + obj.options.text.filterByCondition5 + '</a></li>' + 
                                    '<li class="dropdown-divider"></li>' + 
                                    '<li><a class="dropdown-item drp-filter" href="#">' + obj.options.text.filterByCondition6 + '</a></li>' + 
                                    '<li><a class="dropdown-item drp-filter" href="#">' + obj.options.text.filterByCondition7 + '</a></li>' + 
                                    '<li class="dropdown-divider"></li>' + 
                                    '<li><a class="dropdown-item drp-filter" href="#">' + obj.options.text.filterByCondition8 + '</a></li>' + 
                                    '<li><a class="dropdown-item drp-filter" href="#">' + obj.options.text.filterByCondition9 + '</a></li>' + 
                                '</ul>' + 
                        '</div>';
        popupFilterHtml += '<div class="col-sm-12"><input type="text" class="form-control" id="searchId" placeholder="' + obj.options.text.search + '..."></div>';       // textbox di ricerca
        popupFilterHtml += '<div class="col-sm-12"><input type="hidden" class="form-control" id="hdnColumn"></div>';       // cella nascosta che contiene id colonna
        popupFilterHtml += '<div class="col-sm-12"><br>'
        popupFilterHtml += '<button id="okFilter" type="button" class="btn btn-warning">' + obj.options.text.okButton + '</button>&nbsp;&nbsp;';                                   // bottone ok
        popupFilterHtml += '<button id="closeFilter" type="button" class="btn btn-warning">' + obj.options.text.cancelButton + '</button>';                                       // bottone Annulla
        popupFilterHtml += '</div">'    // chiudi col-sm-12
        popupFilterHtml += '</form">'    // il form
        // crea elemento
        obj.popupFilter = document.createElement('div');
        obj.popupFilter.id = "idPopup";
        obj.popupFilter.className = 'popup-filter';
        obj.popupFilter.innerHTML = popupFilterHtml;

        // ############################################


    // ##########################################################################
    $(document).ready(function () {
        $(".dropdown-menu li a").click(function () {
            $(this).parents(".dropdown").find('.btn').html($(this).text());
            $(this).parents(".dropdown").find('.btn').val($(this).data('value'));
        });



        // button close filter
        $("#closeFilter").click(function () {
            // riattiva il click e lo scroll ovunque nella griglia
            $('.jexcel_content').removeClass('stop-scrolling');
            $('.jexcel_filter').removeClass('stop-scrolling2');
            $('.jexcel_toolbar').removeClass('stop-scrolling2');
            $('.jexcel_pagination').removeClass('stop-scrolling2');
            $('.jexcel_contextmenu').removeClass('stop-scrolling2');

            // close popup
            document.getElementById("idPopup").style.display = "none";
        });


        // button ok 
        $("#okFilter").click(function () {
            var myFilterText = document.getElementById("searchId").value;
            obj.filterTextBox = myFilterText;
            var myFilterType = document.getElementById("dropdownMenu1").innerText;
            var myFilterTypeEn = document.getElementById("dropdownMenu1").innerText;
            var myColumnId = document.getElementById("hdnColumn").value;

            // defaults element "text" 
            var property = defaults['text'];
            for (var name in property) {
                var value = property[name];
                // based on language used = al tipo di filtro
                if (value == myFilterTypeEn) {
                    // in english
                    myFilterTypeEn = defaultsTextLang[name];
                }
            }


            // enable click, scroll anuwhere
            $('.jexcel_content').removeClass('stop-scrolling');
            $('.jexcel_filter').removeClass('stop-scrolling2');
            $('.jexcel_toolbar').removeClass('stop-scrolling2');
            $('.jexcel_pagination').removeClass('stop-scrolling2');
            $('.jexcel_contextmenu').removeClass('stop-scrolling2');

            // close popup
            document.getElementById("idPopup").style.display = "none";

            // no filter request 
            if (myFilterType == "Filter by condition") {
                return;
            }

            // save the filter
            var objTemp = new Object();
            objTemp.ColumnId = myColumnId;
            objTemp.FilterType = myFilterType;
            objTemp.FilterTypeEn = myFilterTypeEn;
            objTemp.FilterText = myFilterText;

            // already exist this filter
            var salvaFiltro = false;
            for (var i = 0; i < obj.FilteredColumns.length; i++) {
                if (obj.FilteredColumns[i].ColumnId == myColumnId) {
                    obj.FilteredColumns[i].FilterType = myFilterType;   // filter (es. in italian)
                    obj.FilteredColumns[i].FilterTypeEn = myFilterTypeEn; // filter in english
                    obj.FilteredColumns[i].FilterText = myFilterText;
                    salvaFiltro = true;
                } 
            }
            if (salvaFiltro == false) {
                // dont exist so insert 
                obj.FilteredColumns.push(objTemp);
            }

            // call search
            obj.search("");

            // change icon
            obj.updateFilterIcone(myColumnId);

        });



        // order by AZ
        $("#orderByAZ").click(function () {
            var column = document.getElementById("hdnColumn").value;

            // enable click anywhere
            $('.jexcel_content').removeClass('stop-scrolling');
            $('.jexcel_filter').removeClass('stop-scrolling2');
            $('.jexcel_toolbar').removeClass('stop-scrolling2');
            $('.jexcel_pagination').removeClass('stop-scrolling2');
            $('.jexcel_contextmenu').removeClass('stop-scrolling2');

            // close pop up
            document.getElementById("idPopup").style.display = "none";

            // order by AZ
            obj.orderBy(column, 0);
        });




        // push order by ZA
        $("#orderByZA").click(function () {
            var column = document.getElementById("hdnColumn").value;

            // enable click anywhere
            $('.jexcel_content').removeClass('stop-scrolling');
            $('.jexcel_filter').removeClass('stop-scrolling2');
            $('.jexcel_toolbar').removeClass('stop-scrolling2');
            $('.jexcel_pagination').removeClass('stop-scrolling2');
            $('.jexcel_contextmenu').removeClass('stop-scrolling2');

            // close popup
            document.getElementById("idPopup").style.display = "none";

            // do order by ZA
            obj.orderBy(column, 1);
        });



        // load value
        if (obj.options.searchInput) {
            obj.searchInput.value = obj.options.searchInput;
            // search
            obj.search(obj.options.searchInput);
        }

    })


then...
    /**
     * Update filter icone: Gabriele 17-10-2019
     */
    obj.updateFilterIcone = function () {
        // in base al tipo di filtraggio in lingua inglese
        for (var i = 0; i < obj.FilteredColumns.length; i++) {
            // nr della colonna
            var column = obj.FilteredColumns[i].ColumnId;

            // togli il bottone di filtro
            obj.headers[column].classList.remove('filter-white-icone');
            obj.headers[column].classList.remove('filter-yellow-icone');

            // in base se esiste il filtro oppure no
            switch (obj.FilteredColumns[i].FilterTypeEn) {
                case 'Is empty':
                case 'Is not empty':
                case 'Is equal to':
                case 'Is not equal to':
                case 'Begins with':
                case 'Ends with':
                case 'Contains':
                case 'Does not contains':
                    // esiste il filtro, cambia alcune impostazioni dell'elemento :before
                    obj.headers[column].classList.add('filter-yellow-icone');
                    break;
                default:
                    // non esiste il filtro, cambia alcune impostazioni dell'elemento :before
                    obj.headers[column].classList.add('filter-white-icone');
                    break;
            }
        }
    }


then ...
    /**
     * Search
     */
    obj.search = function (query) {
        // Query
        if (query) {
            var query = query.toLowerCase();
        }

        // Reset selection
        obj.resetSelection();

        // Total of results
        obj.pageNumber = 0;
        obj.results = [];

        // non esiste alcun search o filter
        if ((!query) && obj.FilteredColumns.length == 0) {
            // query è vuoto e la matrice dei filtri è vuota
            obj.results = null;
            return false;
        }

        // Search filter: ricerca solo nella colonna specificata
        // item: è la riga con tutte le celle
        // query: è il valore da ricercarca
        // index: è il nr di riga (parte da 0)
        // Questa funzione viene chiamata qui **##
        var search = function (item, query, index) {
            // loop sulle colonne in caso di ricerca semplice ovvero con valore di search
            if (query) {
                for (var i = 0; i < item.length; i++) {
                    // ricerca in base al valore di search ovvero ricerca semplice
                    if (('' + item[i]).toLowerCase().search(query) >= 0 ||
                        ('' + obj.records[index][i].innerHTML).toLowerCase().search(query) >= 0) {
                        return true;
                    }
                }
            }

            // Esegui la ricerca. Esiste un filtro su una o + colonne ? Gabriele 11-10-2019
            if (obj.FilteredColumns.length != 0) {
                // filtra Gabriele 11-10-2019
                for (var j = 0; j < obj.FilteredColumns.length; j++) {
                    // recupera il nr della colonna e il valore del filtro
                    var myColId = obj.FilteredColumns[j].ColumnId;
                    var myValue = obj.FilteredColumns[j].FilterText.toLowerCase();

                    // in base al tipo di filtraggio in lingua inglese
                    switch (obj.FilteredColumns[j].FilterTypeEn) {
                        case 'Is empty':
                            // la cella è vuota
                            if (obj.records[index][myColId].innerHTML.length == 0) {
                                return true;
                            }
                            break;
                        case 'Is not empty':
                            // la cella è vuota
                            if (obj.records[index][myColId].innerHTML.length != 0) {
                                return true;
                            }
                            break;
                        case 'Is equal to':
                            // la cella è uguale a
                            if (obj.records[index][myColId].innerHTML.toLowerCase() == myValue) {
                                return true;
                            }
                            break;
                        case 'Is not equal to':
                            // la cella diversa da
                            if (obj.records[index][myColId].innerHTML.toLowerCase() != myValue) {
                                return true;
                            }
                            break;
                        case 'Begins with':
                            // la cella inizia con
                            if (obj.records[index][myColId].innerHTML.toLowerCase().startsWith(myValue)) {
                                return true;
                            }
                            break;
                        case 'Ends with':
                            // la cella finisce con
                            if (obj.records[index][myColId].innerHTML.toLowerCase().endsWith(myValue)) {
                                return true;
                            }
                            break;
                        case 'Contains':
                            // la cella contiene
                            if (obj.records[index][myColId].innerHTML.toLowerCase().search(myValue) >= 0) {
                                return true;
                            }
                            break;
                        case 'Does not contains':
                            // la cella non contiene 
                            if (obj.records[index][myColId].innerHTML.toLowerCase().search(myValue) == -1) {
                                return true;
                            }
                            break;
                        default:
                            // è il caso che assume il valore None ovvero nessun filtro sulla colonna
                            return true;
                    }
                }
            }
            return false;
        }

        // Result. Qyesta funzione viene chiamata qui *-+-*
        var addToResult = function (k) {
            if (obj.results.indexOf(k) == -1) {
                obj.results.push(k);
            }
        }

        // Filter
        var data = obj.options.data.filter(function (v, k) {
            // il sorgente di questa funzione è qui **##
            // v oppure item: è la riga con tutte le celle
            // query: è il valore da ricercarca
            // k oppure index: è il nr di riga (parte da 0)
            if (search(v, query, k)) {
                // Merged rows found
                var rows = obj.isRowMerged(k);
                if (rows.length) {
                    for (var i = 0; i < rows.length; i++) {
                        var row = jexcel.getIdFromColumnName(rows[i], true);
                        for (var j = 0; j < obj.options.mergeCells[rows[i]][1]; j++) {
                            addToResult(row[1] + j);
                        }
                    }
                } else {
                    // Normal row found *-+-*
                    addToResult(k);
                }
                return true;
            } else {
                return false;
            }
        });





        // dim locali
        var total = 0;
        var index = 0;

        // Page 1
        if (obj.options.lazyLoading == true) {
            total = 100;
        } else if (obj.options.pagination > 0) {
            total = obj.options.pagination;
        } else {
            if (obj.results) {
                total = obj.results.length;
            } else {
                total = obj.rows.length;
            }
        }

        // Hide all records from the table
        obj.tbody.innerHTML = '';
        for (var j = 0; j < obj.rows.length; j++) {
            if (!obj.results || obj.results.indexOf(j) > -1) {
                if (index < total) {
                    obj.tbody.appendChild(obj.rows[j]);
                    index++;
                }
                obj.rows[j].style.display = '';
            } else {
                obj.rows[j].style.display = 'none';
            }
        }

        if (obj.options.pagination > 0) {
            obj.updatePagination();
        }

        return total;
    }

then 
/**
 * Double click event handler: controls the double click in the corner, cell edition or column re-ordering or column filtering
 */
jexcel.doubleClickControls = function (e) {
    // Jexcel is selected
    if (jexcel.current) {
        // Corner action
        if (e.target.classList.contains('jexcel_corner')) {
            // Any selected cells
            if (jexcel.current.highlighted.length > 0) {
                // Copy from this
                var x1 = jexcel.current.highlighted[0].getAttribute('data-x');
                var y1 = parseInt(jexcel.current.highlighted[jexcel.current.highlighted.length - 1].getAttribute('data-y')) + 1;
                // Until this
                var x2 = jexcel.current.highlighted[jexcel.current.highlighted.length - 1].getAttribute('data-x');
                var y2 = jexcel.current.records.length - 1
                // Execute copy
                jexcel.current.copyData(jexcel.current.records[y1][x1], jexcel.current.records[y2][x2]);
            }
        } else {
            // Get table
            var jexcelTable = jexcel.getElement(e.target);




            // Double click over header for SORTING
            if (jexcelTable[1] == 1 && jexcel.current.options.columnSorting == true && !e.ctrlKey) {        // Gabriele 27-9-19 aggiunto  && !e.ctrlKey
                // Check valid column header coords
                var columnId = e.target.getAttribute('data-x');
                if (columnId) {
                    jexcel.current.orderBy(columnId);
                }
            }



            // #######################################################################################################################
            // Ctrl + Double click over header for filter: Gabriele 27-9-19. Apri un pop-up per eseguire il filtro  
            if (jexcelTable[1] == 1 && e.ctrlKey && jexcel.current.options.headerfilter == true) {
                // Recupera le coordinate
                var myColumn = e.target.getAttribute('data-x');

                // recupera la posizione della colonna myColumn
                var myElem = document.getElementById("idHeader_" + myColumn);
                //var myWidth = myElem.getBoundingClientRect().width;
                //if (myWidth < 300) { myWidth = 300; }

                // blocca lo scroll e la possibilità di cliccare col mouse nella griglia jExcel in vari punti
                $('.jexcel_content').addClass('stop-scrolling');
                $('.jexcel_filter').addClass('stop-scrolling2');
                $('.jexcel_toolbar').addClass('stop-scrolling2');
                $('.jexcel_pagination').addClass('stop-scrolling2');
                $('.jexcel_contextmenu').addClass('stop-scrolling2');

                // Visualizza la finestra di filtro e imposta posizione e dimensioni
                $(".popup-filter").css({ left: myElem.getBoundingClientRect().left });    // in base alla posizione dell'header determina il punto di sinistra della finestra di popup
                $(".popup-filter").css({ top: myElem.getBoundingClientRect().top + myElem.getBoundingClientRect().height });    // in base alla posizione dell'header + altezza header determina il punto top della finestra di popup
                $(".popup-filter").css({ width: 300 });

                // tolgi la selezione sulla colonna. E' importantissimo questa istruzione altrimenti quando si scrive nel filtro il testo finisce nella cella selezionata del jexcel
                jexcel.current.resetSelection();

                // visualizza la finestra di filtro. Altro esempio che non funziona bene...https://jsfiddle.net/9p2js06o/8/
                $(".popup-filter").show();
                $("#searchId").focus();             // metti il focus nella casella di ricerca

                // recupera eventuale textbox col filtro se esiste sulla colonna
                var myTextSrc = "";
                var myTypeFil = "";
                try {
                    // loop sugli elementi presenti in FilteredColumns. Se trova la colonna 
                    for (i = 0; i < jexcel.current.FilteredColumns.length; i++) {
                        if (jexcel.current.FilteredColumns[i].ColumnId == myColumn) {
                            myTextSrc = jexcel.current.FilteredColumns[i].FilterText;
                            myTypeFil = jexcel.current.FilteredColumns[i].FilterType;
                        }
                    }
                }
                catch (err) {
                    // non segnalare errore 
                }

                // se nessun tipo di filtro selezionato presente metti su 
                if (!myTypeFil) {
                    myTypeFil = jexcel.current.options.text.filterByCondition;
                }

                // valore filtro, tipo e cella nascosta con id colonna
                document.getElementById("searchId").value = myTextSrc;
                document.getElementById("dropdownMenu1").innerText = myTypeFil; 
                document.getElementById("hdnColumn").value = myColumn;
                

            }
            // #######################################################################################################################


            // Double click over body
            if (jexcelTable[1] == 2 && jexcel.current.options.editable == true) {
                if (!jexcel.current.edition) {
                    var getCellCoords = function (element) {
                        if (element.parentNode) {
                            var x = element.getAttribute('data-x');
                            var y = element.getAttribute('data-y');
                            if (x && y) {
                                return element;
                            } else {
                                return getCellCoords(element.parentNode);
                            }
                        }
                    }
                    var cell = getCellCoords(e.target);
                    if (cell && cell.classList.contains('highlight')) {
                        jexcel.current.openEditor(cell);
                    }
                }
            }
        }
    }
}

**Comment by ponyEdp** [comment]
Push Ctrl + dblclick on the header to use.
In the example filter column ID = 6
![filter](https://user-images.githubusercontent.com/55495773/67465143-e8798d80-f644-11e9-8041-29dad55bb0b4.gif)

**Comment by pphod** [comment]
https://jexcel.net/v4/examples/freeze-columns
