### ISSUE TITLE
MAJ key when editing

### ISSUE THREAD

**Issue by felixvandal** [jspreadsheet/ce#67]
Hello again Paul!
One of my user reported that you can't edit a cell when you hold the MAJ key.
Ex.: i want to inter Paul in a cell (new or old) and the editable just don't kick in.
Keep up the good work!

**Comment by pphod** [comment]
Sorry could you send details?

**Comment by felixvandal** [comment]
It is a simple issue, i don't know if i can provide anything else.
Let's says you click on a cell. You want to write Paul in it. 
When you press the MAJ key to enter the capital P, you are not able to enter any value in the cell.
Is that clearer?

**Comment by pphod** [comment]
yes, I will check. Is this MAC?

**Comment by felixvandal** [comment]
Nope, good old windows 7 and 10

**Comment by pphod** [comment]
MAJ = Shift key?

**Comment by felixvandal** [comment]
oups yes its the shift key sorry

**Comment by pphod** [comment]
Repo has been updated to include that.
