### ISSUE TITLE
Issue related to IMPORTING FROM A XSLX FILE

### ISSUE THREAD

**Issue by Harsh-baghel** [jspreadsheet/ce#673]
When i importing the XSLX file the data are displaying but if file is containing image then it's showing blank space.Now i want to create new tabs for the same sheet then how can i do that and after that how can i save xslx modified data to the same path. So that next time i can see.
Can u give any suggestion related to this.
Refer the screenshot.

![Untitled](https://user-images.githubusercontent.com/54663901/67545471-d23c0200-f716-11e9-88d4-d1c1ffe7e504.png)

**Comment by pphod** [comment]
Please take a look at the documentation of this LIB. https://sheetjs.com/ it might help you.
