### ISSUE TITLE
header doesn't support wordwrap

### ISSUE THREAD

**Issue by yqgz** [jspreadsheet/ce#674]
My titles of columes are long, and I can't give them too much space. So I need the wordWarp feature for header. Now, the wordWarp only works on data.
![table](https://user-images.githubusercontent.com/21211525/67557448-b0a73e80-f747-11e9-95db-19222da39597.jpg)
Besides, when the mouse hover on headers, it will show a tag tell us the text of the title. However, nestedheaders don't have this feature. 
I really need a way to view whole text of headers. Please help me, Paul~

**Comment by pphod** [comment]
Please, if you would like to do that. I suggest you overwrite the CSS from the headers.

**Comment by yqgz** [comment]
I changed the jexcel.js, added 'td.setAttribute('title',nestedInformation[i].title);' at line 1016. Then it can show a tag of the text of nestedheader.
But I haven't find a way to wrap the text of nestedhheader yet.
