### ISSUE TITLE
Spreadsheet with formula save as appears error

### ISSUE THREAD

**Issue by whilelie** [jspreadsheet/ce#676]
The example is saved as csv error.
[https://bossanova.uk/jexcel/v3/examples/spreadsheet-formulas](url)
![image](https://user-images.githubusercontent.com/8661807/67627631-4949d580-f892-11e9-8323-9612664ffeb3.png)
![image](https://user-images.githubusercontent.com/8661807/67627552-cecc8600-f890-11e9-832a-feabde9d368c.png)
Thank you.

**Comment by pphod** [comment]
The header was shifting down the formulas. I have fixed that, thanks.
