### ISSUE TITLE
don't assume editor exists

### ISSUE THREAD

**Issue by hmzlam** [jspreadsheet/ce#677]
please change this line
` cell.innerHTML = obj.edition[1];`
to
`if(obj.edition && obj.edition.length>1) cell.innerHTML = obj.edition[1];`

because sometimes we get this error

`core.js:7376 ERROR TypeError: Cannot read property '1' of null
    at Object.push../node_modules/jexcel/dist/jexcel.js.obj.closeEditor (jexcel.js:1515)`

**Comment by pphod** [comment]
Which version are you using?

**Comment by pphod** [comment]
I have added that anyway, but it looks like closeEditor is being called twice. I an older version, this was happening with the onblur event call a second time when the editor was already closed.

**Comment by hmzlam** [comment]
v3.5.0
thanks;

**Comment by hmzlam** [comment]
i used last version i get another error 

> core.js:15724 ERROR TypeError: Cannot read property '1' of null
>     at Object.push../node_modules/jexcel/dist/jexcel.js.obj.closeEditor (jexcel.js:1609)
>     at Object.onclose (jexcel.js:1471)
> 

> please change this 
>             // Save value does not affect the table
>             if (obj.edition[1] == value) {
>                 cell.innerHTML = obj.edition[1];
>             } else {
>                 obj.setValue(cell, value);
>             }

to

>             // Save value does not affect the table
>             if (obj.edition && obj.edition[1] == value) {
>                 cell.innerHTML = obj.edition[1];
>             } else {
>                 obj.setValue(cell, value);
>             }

now i have just one problem , the cell get's bigger each time , are you changing highting on editor events?

**Comment by hmzlam** [comment]
i found where all those errors are, the problem is when you have an exception in onchange event, every thing will hang in table, eg. Network errors, for me now i call the job in another thread,

```
>             setTimeout(() => {
>               changefn(instance, cell, x, y, value);    
>             }, 100);
```
 it's up to give any solution to isolate the  table events from oustide or at least run all internal work than call user onchange event at the end
