### ISSUE TITLE
Unable to select nested table column

### ISSUE THREAD

**Issue by RajuMenon** [jspreadsheet/ce#683]
Hi,

In the below code, I have implemented a table inside row 5 - column 3, the problem is when I click on the nested table column, the parent table column gets selected. For example, if I click on the nested table's 2nd column, the parent table's 2nd column gets selected, please check the code and kindly let me know if it has any issues.

`

      var productListData = [
	    	[false, '', '<h4 class="s2b-headline-b">Sample Fundraiser</h4> <div class="s2b-product-primary-info"><div class="row"><div class="col-auto"><b>Link:</b></div>  <div class="col-auto">https://ibuy.bz/aar534</div> </div>  </div>', '$ 2.000,00'],

	    	[false, 'data:image/jpeg;base64,/9j/4QAYRXhpZgAASUkqAAgAAAAAAAAAAAAAAP', '<h4 class="s2b-headline-b">Digitial Oranges</h4> <div class="s2b-product-primary-info"><div class="row"><div class="col-auto"><b>Link:</b></div>  <div class="col-auto">https://ibuy.bz/oranges</div> </div>    <div class="row"><div class="col-auto"><b>SKU:</b></div>  <div class="col-auto">ora</div> </div>  <div class="row"><div class="col-auto"><b>Filename:</b></div>  <div class="col-auto">santu-n14.png</div> </div>  <div class="row"><div class="col-auto"><b>Size:</b></div>  <div class="col-auto">0.01mb</div> </div>   </div>', '$ 4.000,01'],

	    	[false, 'data:image/jpeg;base64,/9j/4QAYRXhpZgAASUkqAAgAAAAAAAAAAAAAAP', '<h4 class="s2b-headline-b">Pocket watch Q6</h4> <div class="s2b-product-primary-info"><div class="row"><div class="col-auto"><b>Link:</b></div>  <div class="col-auto">https://ibuy.bz/aak460</div> </div>    <div class="row"><div class="col-auto"><b>SKU:</b></div>  <div class="col-auto">Q6</div> </div>  <div class="row"><div class="col-auto"><b>Stock:</b></div>  <div class="col-auto">Unlimited</div> </div>  </div>', '$ 4.000,01'],

	    	[false, 'data:image/jpeg;base64,/9j/4QAYRXhpZgAASUkqAAgAAAAAAAAAAAAAAP', '<h4 class="s2b-headline-b">Digital Grapes</h4> <div class="s2b-product-primary-info"><div class="row"><div class="col-auto"><b>Link:</b></div>  <div class="col-auto">https://ibuy.bz/grapes</div> </div>    <div class="row"><div class="col-auto"><b>SKU:</b></div>  <div class="col-auto">gra</div> </div>  <div class="row"><div class="col-auto"><b>Filename:</b></div>  <div class="col-auto">santu-n6.png</div> </div>  <div class="row"><div class="col-auto"><b>Size:</b></div>  <div class="col-auto">0.01mb</div> </div>   </div>', '$ 4.000,01'],

	    	[false, 'data:image/jpeg;base64,/9j/4QAYRXhpZgAASUkqAAgAAAAAAAAAAAAAAP', '<div id="s2b-product-id-5-details"></div>', '$ 4.000,01'],
		];

		var productListTable = jexcel(document.getElementById('s2b-product-table'), {
			pagination:10,
		    data:productListData,
		    columns: [
		    	{ type: 'checkbox', title:' ', width:20 },
		    	{ type: 'image', title:'Product Image', width:80 },
		        { type: 'text', title:'Product Details', width:120 },
		     ]
		});

	

	

		var productItemInfoData = [
			['Link:', 'https://ibuy.bz/redcabbage'],
			['SKU:','dca'],
			['Filename:','santu-n3.png'],
			['Size:','0.01mb'],
		]

		var productItemInfoTable = jexcel(document.getElementById('s2b-product-id-5-details'), {
			data:productItemInfoData,
		    columns: [
		        { type: 'text', title:'Product DetailsA', width:120 },
		        { type: 'text', title:'Product DetailsA', width:120 },
		     ]
		});

`

Thanks

**Comment by pphod** [comment]
Can you kindly create that in a jsfiddle, please?

**Comment by RajuMenon** [comment]
Please check the link below:

[https://jsfiddle.net/iRajM/a94js6gL/4/](url)

**Comment by pphod** [comment]
Sorry, It is not possible to handle a nested jexcel table.
