### ISSUE TITLE
Incorrect number of columns in 'real JSON' binding

### ISSUE THREAD

**Issue by glinkot** [jspreadsheet/ce#684]
I noticed the discussion and Jsfiddle for allowing columns to refer to JSON key names.  That was exactly what I'm after!  However I find that jExcel creates an extra column for columns that arent referred to in the column config.  See below:

https://jsfiddle.net/glinkot/xtv376ub/35/

- It seems ID and 'another' have resulted in another column each.
- I can't see a way to override number of visible columns, to hide them.  Deleting the number of extra columns doesn't seem wise.
- Finally, I was trying to get the data but didn't get that happening.  I was trying to confirm that the data returned was the same as the incoming JSON except with modified values changed.  Not sure if this is too much to ask, I guess newly created rows would just have no values in any non-visible columns.

I realise it's not released yet but thought I'd raise it.

Thanks

Mark

**Comment by pphod** [comment]
I have duplicated your JSON and fix it.
https://jsfiddle.net/paulhodel/aL807ukn/

**Comment by glinkot** [comment]
Many thanks Paul.  Thanks for fixing getData; that one raises another question I'll ask separately.

**Comment by pphod** [comment]
I am not sure if I can guess, but there is a new method available in this version:

table.getJson()

Best regards,

**Comment by glinkot** [comment]
Lol you did indeed guess!  Sorry I didn't see this in the meantime :)
