### ISSUE TITLE
Not using topological sort? O(n^2) to solve formulas

### ISSUE THREAD

**Issue by techknowfile** [jspreadsheet/ce#686]
We have a table with 90 columns and three rows that have formulas that rely on the data from the preceding columns. Instead of doing a topological sort, jExcel evaluates the cells in the wrong order, causing a repeating cascade of re-evaluations on previously evaluated cells. The result is a O(n^2) update on each change, which quickly becomes unusably slow with more columns.

**Comment by pphod** [comment]
which version?

**Comment by techknowfile** [comment]
Tested with 3.0.1, 3.5, and 2.1

**Comment by pphod** [comment]
Do you mind to create a jsfiddle and share with us? I can take a look to see any possible optimization.

**Comment by techknowfile** [comment]
Yeah man, I'll definitely do that, hopefully later today for ya. In the meantime, we basically sidestepped the formulas functionality by building a DAG, solving the topo sort for the subgraph reachable from the changed cell, then using `setValue(executeFormula())` to control the formula execution ourselves. This is, of course, less than ideal, and doesn't optimize over changing multiple cells at once (and the graph is static, requiring all cells with equations to be readonly)

**Comment by pphod** [comment]
Hi, just to let you know before you go ahead. The latest version v3.6.0 implements a LOOP control, and avoid recalculations, so it might impact your side in a positive way.
