### ISSUE TITLE
pressing escape on responsive dropdown error

### ISSUE THREAD

**Issue by hmzlam** [jspreadsheet/ce#687]
even on official examples website pressing escape on "full screen responsive dropdown" gives this error

> Uncaught TypeError: Cannot read property '1' of null
>    at Object.obj.closeEditor (jexcel.js:1605)
>    at HTMLDocument.jexcel.keyDownControls (jexcel.js:6259)

regards

**Comment by pphod** [comment]
This has been fixed v3.6.0+
