### ISSUE TITLE
issue of formula at V3.5.2

### ISSUE THREAD

**Issue by TsePakKwan** [jspreadsheet/ce#688]
Hi @paulhodel ,

Today I update jexcel version v3.5.1 to v3.5.2, than find a formula bug(version 3.5.1 not this issue).
My Situation : 
E1 : SUM(G2:G8) <<<<< wrong calculation result
G2: MULTIPLY(E2,F2)
G3: MULTIPLY(E3,F3)
G4: ......   (same to G3)

gif image when use v3.5.1 <<<<< correct calculation result
![3 5 1](https://user-images.githubusercontent.com/51103712/67828720-cfc31900-fb17-11e9-99a5-f96fb1775215.gif)

gif image when use v3.5.2 <<<<< wrong calculation result
![3 5 2](https://user-images.githubusercontent.com/51103712/67828726-d5b8fa00-fb17-11e9-9c2b-b139a9cb57e6.gif)

Sorry I cannot create a jsfiddle for you ref. It is because on https://bossanova.uk/jexcel/v3/jexcel.js still in v3.5.1 version and v3.5.1 didn't have this issue.

**Comment by pphod** [comment]
Yes, sorry. This has been fixed in the master v3.6.0
