### ISSUE TITLE
double SUM not get the right result 

### ISSUE THREAD

**Issue by antdesigner** [jspreadsheet/ce#692]
A1=1,A2=2
I set =SUM(A1,A2) in A3,   set =SUM(A1,A2) in B3 ,  A4=SUM(A3,B3)  .
will get the result： A3=3, B3=3,A4=6

When I set  B3  =SUM(A1,A2)+1
will get ：A3=3, B3=4, A4=6(A4 shoud be 7)
This problem didn't appear in the early version 3.5.0

**Comment by pphod** [comment]
Yes, sorry. This has been fixed in the master v3.6.0
