### ISSUE TITLE
Doubt: V3 onchange event

### ISSUE THREAD

**Issue by jpsarno** [jspreadsheet/ce#693]
Hello.

I´m using the event to send a Ajax Request when specifics cells has your value changed. My doubt is, why when I changed a value of the cell x = 5 the event are checking to cells #´s 19, 20, 21, 22... This comporament is correct?

Thank you very much.

BR,
João

**Comment by pphod** [comment]
It is possible to have other cells trigged, for example when formulas cascade. But, it is difficult to say in your case since I don't have access to any code. I am happy to take a look in any jsfiddle if you would like me to do it.

**Comment by jpsarno** [comment]
Ok I understood. I will try to build an example in jsfiddle and I will put the link here.

Thanks a lot.
