### ISSUE TITLE
JSON object binding: Keys needed in getData JSON

### ISSUE THREAD

**Issue by glinkot** [jspreadsheet/ce#698]
In the same JSFiddle from #684 (https://github.com/paulhodel/jexcel/issues/684) we see that the incoming JSON looks like this: 

`var data = [
		{Id: "d9154404-fa1f-11e9-9800-5f58b1ab7958", FirstName: "Bob", Surname: "Jones", Gender: null, another: 'blah'},`

But when we call getData(), we get only the values:

["d9154404-fa1f-11e9-9800-5f58b1ab7958","blah","Bob","Jones",""],

And the original passed dataset is unchanged (see https://jsfiddle.net/glinkot/xkc90vpq/14/).

Makes sense for the prior use case but I wonder how we'd use this as a bound control and send the updated records back to an API?  Could we either have it change the original data sent in, or most likely a getDataWithKeys() or an 'includeKeys' arg in getData so it returns us the key value structure we originally sent in to send back to an API?

**Comment by pphod** [comment]
Please use:

getJson()

Best regards,

**Comment by glinkot** [comment]
Well that works well, thanks Paul!  Please add that to https://bossanova.uk/jexcel/v3/docs/programmatically-changes !

**Comment by thirstyfish** [comment]
Hi @paulhodel - would it be possible to release a new version to npm with the getJson method support?

Thanks heaps for your work!
