### ISSUE TITLE
Correct approach for modifying column visibility etc

### ISSUE THREAD

**Issue by glinkot** [jspreadsheet/ce#699]
In this fiddle I've tried to change a column from 'text' to 'hidden' by clicking the 'make text invisible' button 

https://jsfiddle.net/glinkot/xkc90vpq/38/

It doesn't change but it's *very* possible I'm doing it wrong.  

What's the recommended method?  I tried setting the columns to a new set of columns with new properties but that didn't do the trick.

A handy helper later on would be to be able to address these Json bound columns by title too so we could say column('firstname').type = hidden or somesuch.

Thanks for your replies!

**Comment by pphod** [comment]
Currently, we don't have a straight forward method to change type after initialization. But, you can force to change from hidden to text using the following script:

table.options.columns[x].type = 'text';
for (var j = 0; j < table.options.data.length; j++) {
    table.options.records[j][x].style.display = '';
}
