### ISSUE TITLE
Firefox or IE not working

### ISSUE THREAD

**Issue by rokai3009** [jspreadsheet/ce#7]
Hi Paul

  I just try it on Firefox and IE, jexcel doesn't work, do you have idea or where can i start for this problem?

Regards

**Comment by pphod** [comment]
What is the problem? I have opened the website and jExcel seems to be working correctly.

I have tested on:
IE 11.0.96.17937
FF 51.0.1

**Comment by rokai3009** [comment]
I have copied multiple cells from excel and open office to jexcel
After change \r\n to \n in paste function for Firefox, it is working now but IE doesn't work
I have not debugged in IE

**Comment by pphod** [comment]
You were right, the repository has been updated. Thanks for your collaboration.
