### ISSUE TITLE
Unable to move row and row select

### ISSUE THREAD

**Issue by felixvandal** [jspreadsheet/ce#70]
Hello Paul i hope you are well
i updated the jexcel to the most recent release and i can't tell is trully a success
Yes now we can edit a cell while pressing the shift key
but my users and i experience now a down feature wise
we cannot drag and drop row anymore and when we try the row is selected
we can even select more then one row
i kept a previous version so for now we are good
i downloaded yesterday the 13 november

**Comment by pphod** [comment]
You are right, sorry about it... it has been fixed.
