### ISSUE TITLE
How to cancel changes to cells?

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#703]
I just learned how to use this library recently and i don't know how to cancel the changes made to the cells when the onchange event occurs.

Please help, i'm using it for a project.

Thank you in advance.

**Comment by pphod** [comment]
I am not sure what you meant. Do you mean, cancel the execution of the change? IF yes, you can use onbeforechange to intercept the change. Or, ESC key during the edition to close the edition and return the correct value. Maybe trigger UNDO after any checking.

**Comment by ghost** [comment]
Yes, how can i intercept the change with onbeforechange?

**Comment by jabis** [comment]
@ViktorVonVN arguments passed to onbeforechange are `el, obj.records[y][x], x, y, value` - if you return anything from it, the new `value` will be what you return

ie following would just fill your edited columns with Hello world every time:
```javascript  
...onbeforechange = function() { return "Hello world"; } 
```
