### ISSUE TITLE
Using sample code causes "Uncaught TypeError: Cannot read property 'appendChild' of null" exceptions

### ISSUE THREAD

**Issue by jamesrwaugh** [jspreadsheet/ce#706]
Hi,

It appears an update to JSuites possibly broke JExcel. When I try to paste this sample code below from the last release ZIP (3.5.0) into a HTML file and open it, I get two exceptions as of today, in the latest Chrome:

```
Uncaught TypeError: Cannot read property 'appendChild' of null
    at jsuites.js:5738
    at jsuites.js:5937
    at jsuites.js:15
    at jsuites.js:19
```
And 
```
Uncaught TypeError: Cannot read property 'contextmenu' of undefined
    at Object.obj.createTable (jexcel.js:470)
    at Object.obj.prepareTable (jexcel.js:343)
    at Object.obj.init (jexcel.js:5768)
    at jexcel (jexcel.js:5981)
    at example.html:16
```

Code:
I updated the first script include so both pull the CDN versions.
```
<html>
<script src="https://bossanova.uk/jexcel/v3/jexcel.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jexcel/v3/jexcel.css" type="text/css" />

<script src="https://bossanova.uk/jsuites/v2/jsuites.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jsuites/v2/jsuites.css" type="text/css" />

<div id="spreadsheet"></div>

<script>
var data = [
    [],
    [],
];

jexcel(document.getElementById('spreadsheet'), {
    data:data,
    columns: [
        { type: 'text' },
        { type: 'text' },
        { type: 'text' },
        { type: 'text' },
        { type: 'text' },
        { type: 'text' },
        { type: 'text' },
     ],
     minDimensions:[5,5]
});
</script>
</html>
```

Could you take a look and see what is going on?

**Comment by pphod** [comment]
This has been already fixed. Can you please download jSuites again? Thanks

**Comment by jamesrwaugh** [comment]
Looks good now, thanks.

**Comment by fengyuanxiao** [comment]
×
TypeError: Cannot read properties of undefined (reading 'contextmenu')
obj.createTable
https://bossanova.uk/jspreadsheet/v4/jexcel.js:6560:21
obj.prepareTable
https://bossanova.uk/jspreadsheet/v4/jexcel.js:6395:21
obj.init
https://bossanova.uk/jspreadsheet/v4/jexcel.js:12903:21
jexcel
https://bossanova.uk/jspreadsheet/v4/jexcel.js:13183:13
(anonymous function)
F:/ms-admin/src/pages/AverageRecruitManager/ProjectManager/components/DetailsPage/components/ListSpreadsheet/index.jsx:176
  173 | const spreadsheet = document.getElementById('spreadsheet');
  174 | console.log(spreadsheet);
  175 | // console.log(window.jspreadsheet(spreadsheet, {}));
> 176 | window.jspreadsheet(spreadsheet, {
  177 |     data: data,
  178 |     columns: [
  179 |         { type: 'text', title: 'Car', width: 120 },
View compiled
▶ 16 stack frames were collapsed.

**Comment by fengyuanxiao** [comment]
Why do I have this problem?

**Comment by fengyuanxiao** [comment]
TypeError: Cannot read properties of undefined (reading 'contextmenu')
obj.createTable
https://bossanova.uk/jspreadsheet/v4/jexcel.js:6560:21
obj.prepareTable
https://bossanova.uk/jspreadsheet/v4/jexcel.js:6395:21
obj.init
https://bossanova.uk/jspreadsheet/v4/jexcel.js:12903:21
jexcel
https://bossanova.uk/jspreadsheet/v4/jexcel.js:13183:13

const spreadsheet = document.getElementById('spreadsheet');
  174 | console.log(spreadsheet);
  175 | // console.log(window.jspreadsheet(spreadsheet, {}));
> 176 | window.jspreadsheet(spreadsheet, {
  177 |     data: data,
  178 |     columns: [
  179 |         { type: 'text', title: 'Car', width: 120 },

**Comment by fengyuanxiao** [comment]
https://jsuites.net/v4/jsuites.js 
I think the certificate has expired. I'll just force access；

**Comment by hodeware** [comment]
The certificate is updated. But, please upgrade to a CDN. It will be much faster.

https://cdn.jsdelivr.net/npm/jsuites@4.17.7/dist/jsuites.min.js
https://cdn.jsdelivr.net/npm/jsuites@4.17.7/dist/jsuites.min.css

**Comment by fengyuanxiao** [comment]
All right. Thank you very much.
