### ISSUE TITLE
JQuery usage of jexcel function does not return the result right after invoking apply

### ISSUE THREAD

**Issue by dwaynetin** [jspreadsheet/ce#709]
https://github.com/paulhodel/jexcel/blob/db4cabae3f513436143fa717b3e8fddaf5496a4d/dist/jexcel.js#L7176

On the following code URL above, it seems that whatever is happening on invoke of the function will not cascade upwards to the caller due to lack of return function.

E.g. calling this: $('#excelContainer').jexcel('getRowData', row) 
will return undefined.

**Comment by pphod** [comment]
Thanks, this has been fixed.
