### ISSUE TITLE
setColumnData is not defined/a function

### ISSUE THREAD

**Issue by ismailpmi** [jspreadsheet/ce#712]
Hello paulhodel,
I must say its a amazing plugin.
I face an issue while using this setColumnData method for storing an array to the particular column, i have tried the same for setRowData method which is working fine. please guide on this.

code: 
table.setColumnData([2],[1,2,3,4]);

Uncaught TypeError: table.setColumnData is not a function
    at HTMLElement

**Comment by pphod** [comment]
I have just included this method. You can download the most recent version from the master repo.
