### ISSUE TITLE
Difference between pro and community edition?

### ISSUE THREAD

**Issue by yhogewind** [jspreadsheet/ce#717]
Please clarify the difference between the pro and community version of JExcel. Are you planning to not release further updates to the community edition? Is this repo the community edition?

**Comment by pphod** [comment]
Up to the current version, both are the same, and the difference is the support level. In the soon future, Pro version will include a few technical differences and some extra features. CE version is active a very important version, and we are constantly improving. The new Pro version will come to help financially the CE version with new updates and constant new releases.
