### ISSUE TITLE
import xlsx and accurately restore the style 

### ISSUE THREAD

**Issue by yoyomule** [jspreadsheet/ce#718]
Hello, I see that the import xlsx adopts sheejs. If I want to import xlsx and accurately restore the style of xlsx on the web page, do I need to buy its commercial version? Or  can use other solutions, such as phpspread, excel JS?
Thanks.

**Comment by pphod** [comment]
This is a very, very good question. I have tried to customize a little the sheetjs open license. Did you see that example? https://bossanova.uk/jexcel/v3/examples/import-data (last example)?

The original version has very bad support for style, and I am not sure if the Pro version will be better. I would suggest you contact the authors. If you get useful information it would be great if you share if us.
