### ISSUE TITLE
jexcel dependency jsuites has CSS that conflicts with Semantic UI

### ISSUE THREAD

**Issue by kevinhalliday** [jspreadsheet/ce#720]
First off, thanks for all of your work on this project. It's very cool. And I, along with a few colleagues, have enjoyed using it so far. Unfortunately, I recently ran into a styling conflict with  [semantic ui](https://semantic-ui.com/) after upgrading my version of `jexcel` to `3.6.1`, which, in turn, upgraded `jsuites` (`jexcel` dependency)  from version `2.1.3` to `2.2.2`.

I've set up a [sandbox](https://codesandbox.io/s/jexcel-semantic-ui-css-conflict-scsv9) to illustrate the issue. It seems `jsuites` uses some class names that overlap with those of semantic ui. In this case, that class name was `warning` (the specific rule causing me issues lives [here](https://github.com/paulhodel/jsuites/blob/master/dist/jsuites.css#L1674)). After looking at `jsuites` code, it seems that other class names are also at risk of conflict (`.app` ?).  

I was able to solve this issue by downgrading `jexcel` to version `3.5.0`, and pinning the version of `jsuites` to `2.1.3` using [version resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/). Still wanted to bring this to your attention. And ask if you are aware of any other solutions. Or if you are open to reviewing a PR that updates classnames in `jsuites` to be a bit more "jsuites specific".

**Comment by pphod** [comment]
Yes, it make sense. I am going to update that.

**Comment by leahein** [comment]
Following up on this -- is this being worked on? If not I can work on submitting a PR for this.

**Comment by pphod** [comment]
There a few updates will be deployed soon.

**Comment by pphod** [comment]
It has been fixed, fixes are available from jExcel v3.6.3 + jSuites v2.3.0
