### ISSUE TITLE
Color and background not working 

### ISSUE THREAD

**Issue by glenoka** [jspreadsheet/ce#726]
I put background and color like this: 
`shift.setStyle('C4', 'background-color', '#32CD32','color', 'white');`

but the only background is working, color font not working. 
this the result: 
![image](https://user-images.githubusercontent.com/52094832/68917263-fb8f0180-079b-11ea-9497-43c28cd88cc3.png)

can you help me?

**Comment by pphod** [comment]
The correct way to apply multiple style properties or cells:

table.setStyle({ A3:'font-weight: bold; color:red;', B3:'background-color: yellow;', C3:'text-decoration: underline;', A4:'text-align:left;' });
