### ISSUE TITLE
dropdown location

### ISSUE THREAD

**Issue by hmzlam** [jspreadsheet/ce#728]
initial dropdown location is good but it's  not correct when we scroll right
![image](https://user-images.githubusercontent.com/14170848/68990107-76652480-084f-11ea-98a4-8a5abacd8312.png)
this is a  test case with master jsuites
[testcase](http://itaa.fr/lte/)

**Comment by pphod** [comment]
This has already been fixed in the most recent jSuites.

**Comment by hmzlam** [comment]
anyone who has this issue wirh fullscreen option you may use this  fix
[https://github.com/hmzlam/jexcel/blob/master/dist/jexcel.js](https://github.com/hmzlam/jexcel/blob/master/dist/jexcel.js)

**Comment by hmzlam** [comment]
anyone who has this issue with fullscreen option you may use this  fix
[https://github.com/hmzlam/jexcel/blob/master/dist/jexcel.js](https://github.com/hmzlam/jexcel/blob/master/dist/jexcel.js)
