### ISSUE TITLE
Data between toolbar and table head make jexcel urgly

### ISSUE THREAD

**Issue by hyh888** [jspreadsheet/ce#730]
Dear Paulhodel,
There are half row  between toolbar and table head when scrolling the spreadsheet upward and make jexcel looked ugly. The attached image is the screenshot. Is there any solution?
If you can combine filter box and tool into one div, it will be more convenient for users. I have manually do it, you can have a look in the attached image.
Thank you very much for your excellent job.
![image](https://user-images.githubusercontent.com/963838/69110256-1b346b80-0ab5-11ea-9ee8-0c0726bca7b0.png)

**Comment by pphod** [comment]
There is a clear visual problem in your CSS. Something is affecting the padding of the table. The correct display is:

![image](https://user-images.githubusercontent.com/6019713/69865506-38c5ba00-1299-11ea-8942-4da3b17674d4.png)

**Comment by hyh888** [comment]
Many thanks. I make this change in jexcel.css, and the problem fixed. Maybe there is a CSS conflict with other JS plugin. Hope this issue can provide help for others.
![image](https://user-images.githubusercontent.com/963838/69898293-693d4f00-1392-11ea-9507-f1f143d5f712.png)
