### ISSUE TITLE
Filtering based on column value.

### ISSUE THREAD

**Issue by thelightbringer** [jspreadsheet/ce#732]
Will there be filtering based on column value be integrated in future roadmap ?

**Comment by pphod** [comment]
We are considering that. Meanwhile, you can find a general search option.
https://bossanova.uk/jexcel/v3/examples/datatables

**Comment by thelightbringer** [comment]
Hi Paul,

I can see this closed issue :
https://github.com/paulhodel/jexcel/issues/140 (Issues:How to Filter JExcel Like Microsoft Office Excel) 
So, filtering the dataset and then using setData to the table  to refresh, is closed enough to column level filtering in terms of usability and  optimization ? What do you recommend ? Should I use it until column level filtering isn't implemented?

**Comment by pphod** [comment]
I guess the search is pretty closer to what you looking for.

**Comment by Ruan-Miguel** [comment]
Column filters are available from v4
