### ISSUE TITLE
Handle nested JSON object

### ISSUE THREAD

**Issue by mssarul361** [jspreadsheet/ce#733]
jexcel(document.getElementById('purpose'), {
                        url: 'resources/temp.json',
                         colHeaders :['name', 'age', 'car', 
                                       'bike','plane'],
                        columns: [
                            {
                                type: 'text',
                                width: '300',
                                name: 'name'
                            },
                            {
                                type: 'text',
                                width: '300',
                                name: 'age'
                            },
                            {
                                type: 'text',
                                width: '100',
                                name: 'car'
                            },
                            {
                                type: 'text',
                                width: '100',
                                name: 'bike'
                            },
                            {
                                type: 'text',
                                width: '100',
                                name: 'plane'
                            },
                        ]
                    });
**/** temp.json**/**

[{
      "name":"Ram",
      "age":27,
      "vehicles": [{
         "car":"limousine",
         "bike":"ktm-duke",
         "plane":"lufthansa"
      },
      {
         "car":"BMW",
         "bike":"Ducati",
         "plane":"Emirates"
      }
    ]
}]

In JExcel V3 If possible to show first-row show name, age with first vehicles and need second to show balance vehicle details only is possible?

**Comment by pphod** [comment]
Sorry, I did not understand your question. But, you can use this example as a reference on how to config nested headers.

https://bossanova.uk/jexcel/v3/examples/headers
