### ISSUE TITLE
Setting data 

### ISSUE THREAD

**Issue by Harsh-baghel** [jspreadsheet/ce#735]
When i am calling setData method than it is not taking style.Is there any way to fix the style while setting data.

**Comment by pphod** [comment]
You can:

resetStyle()

them

setStyle()

**Comment by debamishra14** [comment]
@paulhodel @Guillaume-Bo is there any way we can update a cell's data dynamically outside updateTable:, that is like inside an API call if I get a certain value then I want to update a particular row's particular column value. so can we do it? I am trying with setColumnData() but no success.
Thank you.

**Comment by GBonnaire** [comment]
yes with setValue. See documentation for know how use 😉

**Comment by debamishra14** [comment]
is it with setValue or setColumnData ? @Guillaume-Bo when trying with setValue('F1', 'Text') then that cell is not getting updated which was previously blank or empty.

**Comment by GBonnaire** [comment]
as you want, setValue is for 1 cell, ans setColumnData is for change all
cell of column in 1 time.

**Comment by DebaPrasad14** [comment]
@Guillaume-Bo thank you so much for your response, but when trying with setValue('F1', 'Text') then that cell is not getting updated, am I doing anything wrong?

**Comment by GBonnaire** [comment]
show how you make your setValue ?
