### ISSUE TITLE
Bug: Decimal on keypad

### ISSUE THREAD

**Issue by krosoftware** [jspreadsheet/ce#741]
Hello,
It is not possible to enter decimal using keypad and here is example
https://jsfiddle.net/johnlock42/ek20uzqc/1/
Thank you

**Comment by pphod** [comment]
Your code (mask) is not correct, this is the correct one.

```
mytable = jexcel(document.getElementById('spreadsheet'), {
    data:data,
    columns: [
         { type: 'text', title:'Car', width:120 },
         { type: 'numeric', title:'Price', width:100, mask:' #.##,00', decimal:'.' },
     ],
     updateTable: function (instance, cell, col, row, val, label, cellName) {
        if(row ==0 && col == 1){
            var x= val;
        }
     }  
});
```

**Comment by krosoftware** [comment]
I just pasted your code but it still does not work, please check here:
https://jsfiddle.net/w35xmpv1/
thank you.

**Comment by pphod** [comment]
I have tested your code, and it is working fine for me.

**Comment by krosoftware** [comment]
Strange, because it does not work here. Maybe it is related to East European keyboard I use?

**Comment by pphod** [comment]
What is the key code generate by your keyboard?

**Comment by krosoftware** [comment]
It is 110

**Comment by pphod** [comment]
Yes, 110 is covered.

                                } else if ((e.keyCode == 8) ||
                                           (e.keyCode >= 48 && e.keyCode <= 57) ||
                                           (e.keyCode >= 96 && e.keyCode <= 111) ||
                                           (e.keyCode == 187) ||

**Comment by krosoftware** [comment]
Here it does not work, even number 0 is not entered. Here is image of how it looks like when I try to enter 0,23
https://imgur.com/uHx7DRl

**Comment by pphod** [comment]
Try to clear your cache, different browser, etc.

**Comment by pphod** [comment]
I have checked, and it is definitely cached. This was an issue fix some time ago.

**Comment by krosoftware** [comment]
I cleared cache and checked with 3 browsers, it still does not work (except now I can enter 0 and yesterday I was not able to enter it).
Beside that, mask setting is wrong, please check: https://imgur.com/EdSaOFO

**Comment by javs0188** [comment]
> I cleared cache and checked with 3 browsers, it still does not work (except now I can enter 0 and yesterday I was not able to enter it).
> Beside that, mask setting is wrong, please check: https://imgur.com/EdSaOFO

Try: 
{ type: 'numeric', title:'Price', width:100, mask:' #,##.#', decimal:'.' }

**Comment by krosoftware** [comment]
It still does not work here, I updated jsFiddle
https://jsfiddle.net/8trp7u0c/

**Comment by pphod** [comment]
This is fixed on v4
https://jsfiddle.net/paulhodel/vcthuw2g/

**Comment by krosoftware** [comment]
Please check this:
https://imgur.com/PA9hRAj
I try to write: 12,3
here is source:
https://jsfiddle.net/w1f6n2k5/
Thank you.

**Comment by pphod** [comment]
You can't since you mask the decimal to be point. The comma using this mask will be accepted every 3 numbers only (x,xxx,xxx)

**Comment by pphod** [comment]
The behavior from your message is expected considering the mask you have setup. If you want to have 12,3 (0,30 as decimal you must change your mask).

**Comment by krosoftware** [comment]
Hello
I changed mask to coma s decimal, please check new fiddle:
https://jsfiddle.net/j4vaLdyq/
when using normal coma, it works, but when using coma from keyboard it does not :(

**Comment by pphod** [comment]
Opened your jsfiddle and both is working as expected. Sorry, not sure what is happening on your side.

**Comment by krosoftware** [comment]
Does anybody else have this problem or I'm alone?

**Comment by pphod** [comment]
Have you consider migrating to v5? https://jexcel.net/v5

I can help with that, share screens and make that work for you. My skype: paul.hodel

**Comment by krosoftware** [comment]
Thanks, does it have autocomplete function from database, with option to pick value and to continue to edit?

**Comment by krosoftware** [comment]
@paulhodel does v5 have option to autocomplete function from database, with option to pick value and to continue to edit? Thank you for your answer.

**Comment by pphod** [comment]
CE & Pro will have that soon with the release of Jsuites v3.

**Comment by pphod** [comment]
If you would like, add me on skype and I can give more information.
