### ISSUE TITLE
Number formatting and negative sign

### ISSUE THREAD

**Issue by Krukosz** [jspreadsheet/ce#742]
During implementation of jExcel in my project I'm facing two problems:

1. I have no mask on number column, and I can't type negative sign in a cell (number cell type)
2. How to remove trailing zeros from the value? For example:

`1.000000-> 1
1.210000 -> 1.21`

**Comment by pphod** [comment]
1) If you update jSuites you can use something like that: [-]#,##

2) You can =ROUND or you can use a method to round in JS.

mytable = jexcel(document.getElementById('spreadsheet'), {
    data:data,
    columns: [
         { type: 'text', title:'Car', width:120 },
         { type: 'numeric', title:'Price', width:100, mask:' #.##,00', decimal:'.' },
     ],
     updateTable: function (instance, cell, col, row, val, label, cellName) {
            if (col == 2) { cell.innerHTML = Math.round(val); }
     }  
});
