### ISSUE TITLE
How to export data to JSON when source is in external JSON

### ISSUE THREAD

**Issue by Krukosz** [jspreadsheet/ce#743]
I have my jExcel spreadsheet loaded by external json. Loading JSON from external source make initialization function asynchronous.

I know how to fire functions in sequence, but I can't hook then my spreadsheet to variable to export data.

I want to export data after button click. How to do that?

I have 3 functions: `loadJSON `which loads external JSON to localStorage (i need to calculate datahash basing on downloaded JSON - it's dynamic), then `loadSpreadsheet` which actually initializes spreadsheet and then `hookSpreadsheet`, which is intended to make "hook" to variable of the newly created spreadsheet.

These 3 functions have callbacks and I execute them in the way below:

```
$(document).ready(function() {
    localStorage.clear();

    loadJSON(function() {
        loadSpreadsheet(function() {
            hookSpreadsheet(function(){

            });
        });
    });

                $('#savebtn').click(function(){
//HERE i want to get data from the spreadsheet.

                });
});
```

But I don't know how to make created hook visible to the button.click() function. 
The `hookSpreadsheet` function could be redundant if I could return jexcel object from the initialization.

**Comment by pphod** [comment]
You can do:

Document.getElementById('yourtableid').jexcel.getData();
