### ISSUE TITLE
How can I keep selection when lost focus?

### ISSUE THREAD

**Issue by bwangel** [jspreadsheet/ce#744]
see the source code, 
```
 // from line 6543:
       if (jexcel.current) {
            jexcel.current.resetSelection(true);
            jexcel.current = null;
      }
```
it seems no options can control this behavior?

this makes it difficult to select a big area when i need to drag the scroll bar.

**Comment by pphod** [comment]
Would you like to create a jsfiddle to explain a bit better?

**Comment by alejandroeclair** [comment]
@paulhodel 
I think I know what he's referring to.
When you have a selection on your jExcel table and you click somewhere else in the page, you lose those selected cells. 
It would be great to keep the selection marked because I'm having the same issue. I want to have a selection marked and then I want to be able to click on a button outside the excel table and not loose selected cells.

Is there any way to prevent this?

**Comment by pphod** [comment]
If you click outside you going to lose focus. There is no way to prevent that. In your case, it is different. You want to integrate a button on jExcel and you can do that, but your button must be inside the container. In this case, you won't lose the selection.

```

<html>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<script src="https://bossanova.uk/jexcel/v3/jexcel.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jexcel/v3/jexcel.css" type="text/css" />
<script src="https://bossanova.uk/jsuites/v2/jsuites.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jsuites/v2/jsuites.css" type="text/css" />

<div id="spreadsheet"></div>

<script>
var options = {
    minDimensions:[10,10],
    tableOverflow:true,
}

$('#spreadsheet').jexcel(options); 

$('#spreadsheet').append("<button>Do something</button>");
</script>
</html>

```

**Comment by alejandroeclair** [comment]
Hi @paulhodel ,
I'll give this a try, but my code is in React, not jQuery.

Thanks.

**Comment by alejandroeclair** [comment]
Figured out how to make it appear right before the jExcel table.
`<div id="jExcel" className="jExcel">
                      <Button onClick={(e) => this.transformSelection(e)} variant="contained" color="primary">Transform Data</Button>
                    </div>
`

**Comment by sasha-x** [comment]
My case:
I have wide table with `tableOverflow: false`
I can select entire row by click on row number (at very first column).
Then I click browser's scrollbar and table loose selection. If not click, just use mouse wheel - selection stay in place.
It looks like table loose focus but no any other element receive it.

How can I make selection slightly more stable?

Ubuntu 18, Firefox 70.0.1 x64.
