### ISSUE TITLE
GRID NOT WORKING IN LATEST CHROME BROWSER

### ISSUE THREAD

**Issue by Kalpeshpatelbyk** [jspreadsheet/ce#745]
jexcel file is opening in opera but not in chrome browser
any issues??

**Comment by pphod** [comment]
Can you provide an error from your console?

**Comment by pphod** [comment]
Are you sure is not something in your side?

https://bossanova.uk/jexcel/v3/

**Comment by Kalpeshpatelbyk** [comment]
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at jexcel (jexcel.js:6132)
    at 123.html:20
123.html:1 A cookie associated with a cross-s

**Comment by pphod** [comment]
For the code below. You refer to an non existing element id. If you do that, you should expect this error.
```
<div id="spreadsheet"></div>

jexcel(document.getElementById('spreadsheet_non_exiting_id'), {
    data:null,
    minDimensions:[20,1000],
});
```
