### ISSUE TITLE
Feature Request: get row data in Json format.

### ISSUE THREAD

**Issue by lyassa** [jspreadsheet/ce#747]
Method table.getRowData(row_number) returns the row data in an array. Will be great if we have a similar method that gets the row data in a Json format.

**Comment by lyassa** [comment]
Actually what I suggested above is doable as follows:
``
var jsonRow = table.getJson()[row_number];
``
Closing the request.

**Comment by jabis** [comment]
Here's my implementation if you wish to use the same api as getRowData(num):
```javascript  
    /**
     * Get a row json by rowNumber
     */
    obj.getRowJson = function(rowNumber) {
        var x = obj.options.columns.length
        var row = obj.options.data[rowNumber];
        var ret = {};
        //ret["line"+rowNumber]={};
        if(row){
          for(var j=0; j < x; j++){
            ret[obj.options.columns[j].name]=row[j];
          }
        }
        return ret;
    }
```
