### ISSUE TITLE
making jexcel table styling uneditable by users

### ISSUE THREAD

**Issue by adidottxt** [jspreadsheet/ce#749]
Hello!

Thank you for your work on this project! Been using this with a few colleagues at work and we've enjoyed using it.

I'm currently working on a project where we're populating a Jexcel table using a database, and ideally on render we'd like to set the table's style based on specific values in a column. This is pretty straightforward, however I can't seem to find a way to ensure that users are not able to hit CTRL+Z and undo style changes.

I'd imagine one way around this would be to make the entire table un-editable -- but unfortunately the requirements of our app require the Jexcel table to be editable. Is there any way I can make the table styling permanent?

Thanks again.

**Comment by pphod** [comment]
You might be use events to force certain things.

there is a method for style changes.

onstyle:handler()
