### ISSUE TITLE
how to customize the single cell?

### ISSUE THREAD

**Issue by RophiePan** [jspreadsheet/ce#75]
Hi Paul, I'm using this plugin which is a really awesome plugin and save me lots of time. But now I have a requirement that I need customize the single cell not the whole column. for example, If I only want to one cell has the dropdown function, how to implement this and if I want to one cell has the read only attr and so on.
here is the sample which you provide of the dropdown, but it's not the final implementation I want.
http://bossanova.uk/jexcel/examples/working-with-dropdowns.

Could you do me a favor for this? 
Thanks,
-Rophie

**Comment by pphod** [comment]
This is one example how to do that. You can customize any particular row or cell.

https://jsfiddle.net/paulhodel/8b0q2on7/
