### ISSUE TITLE
fill in additional text with autocomplete

### ISSUE THREAD

**Issue by flywalt** [jspreadsheet/ce#751]
IF the autocomplete is A,B,C
how can i fill in D? i just want to use autocomplete as an aid, not as a limit.
besides, the arrow keys isn't quite like those in  EXCEL, which can change focus during input. you can only change focus when you are not inputting. is it possible to improve it ?
thx!

**Comment by pphod** [comment]
Sorry, I am not sure if I understood your question. But, it is not possible to move from a cell during edition with arrows. Because the arrows will be used to navigate in the editor.
