### ISSUE TITLE
How to merge cell thorugh string value

### ISSUE THREAD

**Issue by mssarul361** [jspreadsheet/ce#752]
I am using Java to construct merge variable data, i.e. **'A1: [2,1], A2:[1,2]**' and next pass variable to javascript function and try to create JEXcel.
My doubt is parameter value to how to set merge cells data.

function JExcelData(mergeData)
{                 
                    
table1 = jexcel(document.getElementById('purpose'), {
 url: '#{request.contextPath}/temp.json',
                      mergeCells:{
	mergeData
    },                    
});
}

**Comment by pphod** [comment]
https://bossanova.uk/jexcel/v3/examples/merged-cells
