### ISSUE TITLE
Add new math function

### ISSUE THREAD

**Issue by yqgz** [jspreadsheet/ce#754]
Hi, Paul!
      In my project, there is a formula with a calculation of 'ln'. However, jexcel doesn't support it.
      I'll be really appreciate If you add the support of advaced Mathematics. Thank you!

**Comment by pphod** [comment]
You can implement your own methods. As a reference you can use the last example in the following URL.
https://bossanova.uk/jexcel/v3/examples/spreadsheet-formulas
