### ISSUE TITLE
Name property not included in new column after insertColumn

### ISSUE THREAD

**Issue by markben77** [jspreadsheet/ce#755]
When inserting a new column the 'name' is not included. That appears to be important for the display of data (ordering of columns). If the data is saved and try to reload on another sheet, it is not showing in the same way. 
From the config:
```
"columns":[
  {"type":"text","name":"0","source":[],"options":[],"editor":null,"allowEmpty":false,"title":"","width":50,"align":"center"},
  {"type":"text","source":[],"options":[],"width":50,"align":"center"},
  {"type":"text","name":"2","source":[],"options":[],"editor":null,"allowEmpty":false,"title":"","width":50,"align":"center"},
  {"type":"text","name":3,"source":[],"options":[],"editor":null,"allowEmpty":false,"title":"","width":50,"align":"center"}

 ],
```
Above the second row was an insert and 'name' is not present

**Comment by pphod** [comment]
This behavior is correct, and the name should be added using oninsertrow() in case you need. This is because the name is not necessarily a sequence number. If you are using it as a number, I suggest you to remove the name at all.
