### ISSUE TITLE
defaultColWidth gets applied to first column of row numbers

### ISSUE THREAD

**Issue by leahein** [jspreadsheet/ce#757]
As of 3.6.3, the `defaultColWidth` also gets applied to the first column of row numbers.  This changes the behavior from all previous versions, and I don't think that's the desired outcome.
![image](https://user-images.githubusercontent.com/15165051/70463375-c9b34700-1a8a-11ea-9b37-16f55428d662.png)

This can be previewed here: https://codesandbox.io/s/jexcel-and-react-8sgbq
It looks like this breaking behavior was introduced in PR #740

**Comment by leahein** [comment]
I'd be happy to work on a PR for this issue.  My thought is that we'll also want to check if i === 0.  Let me know what you think.

**Comment by pphod** [comment]
This has been fixed on v3.7.3+
