### ISSUE TITLE
Customizing lazy loading

### ISSUE THREAD

**Issue by thelightbringer** [jspreadsheet/ce#758]
Hi Paul,
Is there any property to customize lazy loading. For e.g., 
1- Minimum rows increased from 100 to whatever threshold required (E.g., 1000 rows) ?
2- Go to top of the view just by clicking a button.

Thanks in advance.
Cheers :)

**Comment by pphod** [comment]
There is no way for change that for now. You can use CTRL+Home or other key navegation to go to the top, bottom, etc.
