### ISSUE TITLE
Programmatically set selected cell

### ISSUE THREAD

**Issue by ghostwriter9151** [jspreadsheet/ce#760]
Is it possible to set a selected cell?

Like
```
jexcel.setSelectedCell([1,1]);
```
and cell [1,1] is selected then, as it would be, when I click on it?

**Comment by pphod** [comment]
updateSelectionFromCoords(x1,y1,x2,y2);

**Comment by mustantriveni** [comment]
> updateSelectionFromCoords(x1,y1,x2,y2);

When i use this method it works
but now issue is if i tab then i cannot able to go at next cell
is there any way to handle this?
Thank You in advance for helping

**Comment by mustantriveni** [comment]
When i use this method it works
but now issue is if i am at bottom in scroll and the cell is at 0 then scrolling is not done automatically
is there any way to handle this?
Thank You in advance for helping

**Comment by pphod** [comment]
You can use tableOverflow:true or fullscreen:true to activate and use the table scrolling.

**Comment by mustantriveni** [comment]
I have applied but doesn't work
I have added my code you can check this
https://codepen.io/mustanhajibhai/pen/LYEzYpP
case 2 (Important)
Scroll bottom of the page and Click on Focus button and verify the behavior
Output:- It will be focused on that column cell but we cannot see until we have to scroll at top
Expected:- It should automatically scroll at where we have set the focus to cell
case 2 (Not Important)
Click on Focus button and Tab and verify the behavior
Output:- It will not redirect to next column cell
Expected:- It should redirect to next cell 

This is a very nice library to use but I face this roadblock 
can you please look into it and try to give the solution for me
Thank You very much in advance

**Comment by pphod** [comment]
Buttons must be included inside the jexcel container.
https://codepen.io/paulhodel/pen/ZEYXEBm

Please, can you subscribe as a supporter?
https://bossanova.uk/jexcel/v3/support

**Comment by pphod** [comment]
This is other option that works.
`  <button onclick="table2.page(3)" unselectable="on" style="user-select: none;">test</button>`

**Comment by mustantriveni** [comment]
> Buttons must be included inside the jexcel container.

I cannot get this and also I checked https://codepen.io/paulhodel/pen/ZEYXEBm link but there it is not working
I have added the code 
This is another option that works.
<button onclick="table2.page(3)" unselectable="on" style="user-select: none;">test</button>
But it is not working
I am not sure where I have to put this can you please guide me to get this working

**Comment by mustantriveni** [comment]
I want table2.updateSelectionFromCoords(1, 1, 1, 1); this working but with automated scrolling.
can you please provide me any solution to get this working?

**Comment by vigneshbarani24** [comment]
Hi @mustantriveni , were you able to get this working ?

**Comment by mustantriveni** [comment]
> Hi @mustantriveni , were you able to get this working ?

Yes

**Comment by sanju-js** [comment]
table2.updateSelectionFromCoords()
jexcel.current=table2;
