### ISSUE TITLE
Refresh the data in the table

### ISSUE THREAD

**Issue by lyassa** [jspreadsheet/ce#761]
I am populating the table using a url. Is there any method I can call that will requery the url and refresh the data? I know about the setData method, but I don't think it helps here. I also tried to destroy the table and rebuild it, but I get error "Uncaught TypeError: Cannot read property 'apply' of undefined". Thanks in advance for your answer.

**Comment by pphod** [comment]
I have included a new method call: table.refresh(); this will make the trick.

**Comment by pphod** [comment]
Available on v3.7.2

**Comment by lyassa** [comment]
Works like charm. You are awesome. Thank you so much.

**Comment by ghost** [comment]
I'm trying to use this table.refresh and isnt wokring? tried to update to version 3.7.2 but  got an error.
No matching version found for jexcel@^3.7.2.

**Comment by wescrockett** [comment]
Also unsure on how to call this. @lyassa, have any insight?

**Comment by pphod** [comment]
The example is not the best. but if you loading data from a URL makes more sense.

```
<div id="spreadsheet"></div>

<script>
var data = [
    ['Mazda', 2001, 2000, '2006-01-01'],
    ['Pegeout', 2010, 5000, '2005-01-01'],
    ['Honda Fit', 2009, 3000, '2004-01-01'],
    ['Honda CRV', 2010, 6000, '2003-01-01'],
];

var table = jexcel(document.getElementById('spreadsheet'), {
    data:data,
    columns: [
        { type: 'text', width:300 },
        { type: 'text', width:80 },
        { type: 'text', width:100 },
        { type: 'calendar', width:100 },
    ]
});

// After
table.refresh()
</script>
```

**Comment by Louise-Huang** [comment]
@paulhodel  Hi Paul, I can't use "table.refresh()" on v7 pro. It shows "table.fresh is not a function". Is there any other way to update all the datas? Thanks!
