### ISSUE TITLE
Dropdown menu position when used with tableOverflow

### ISSUE THREAD

**Issue by leahein** [jspreadsheet/ce#764]
When the `tableOverflow` is set to `true`, the dropdown menu position remains fixed when scrolling.

![image](https://user-images.githubusercontent.com/15165051/70737069-b77e1680-1cdf-11ea-87cf-dc31a57697f3.png)

[Codesandbox here](https://codesandbox.io/s/jexcel-and-react-quc36)

**Comment by pphod** [comment]
I have tested and not sure why jsuites is loading an older version. Please make sure you have the most recent version v2.3.0+

**Comment by leahein** [comment]
I am using version `2.3.0`, this is still an issue.

**Comment by leahein** [comment]
This is still an issue with `2.3.1`, as can be seen [here](https://codesandbox.io/s/jexcel-and-react-quc36).

**Comment by pphod** [comment]
There is something very strange. It seems codesandbox is loading an old version. This has been fixed on v2.3.0+ I have double checked...

**Comment by leahein** [comment]
I am experiencing the same issue locally, on version 2.3.0
![image](https://user-images.githubusercontent.com/15165051/70741103-9a017a80-1ce8-11ea-8549-297b7e886c5b.png)

**Comment by adidottxt** [comment]
@paulhodel fwiw I'm having the same issue as @leahein locally as well, on version 2.3.1.

JSuites version:
![Image from iOS (1)](https://user-images.githubusercontent.com/29982667/70742598-e9957580-1ceb-11ea-82fd-562a095c7c8d.jpg)

The issue:
![Image from iOS](https://user-images.githubusercontent.com/29982667/70742411-7a1f8600-1ceb-11ea-8bf4-8165b7fb6853.jpg)

**Comment by pphod** [comment]
I am on this. I will keep you posted...

**Comment by pphod** [comment]
I am trying to see any problem with the NPM publication, but you can see that working on the website.
https://bossanova.uk/jexcel/v3/examples/table-overflow

**Comment by paulhodel** [comment]
It is working:
https://codesandbox.io/s/jexcel-and-react-y4thi

I have removed the following code from the index.html, I am going to check the code to support that.
"<!DOCTYPE html>"

**Comment by pphod** [comment]
Ok, I found the problem. It has been fixed. 

v2.3.2+

**Comment by leahein** [comment]
Confirmed this works :tada: 

Thank you for addressing!
