### ISSUE TITLE
Hide Columns

### ISSUE THREAD

**Issue by VictorCandido** [jspreadsheet/ce#765]
Hello. Is there any way of hide a column? When I use $('column').hide(), I loose all my CSS configuration, so could be very nice to have an implementation of an event to hide a column by it's index.

**Comment by GBonnaire** [comment]
Hi,

You can set type of column to hidden ?

```
jexcel(document.getElementById('spreadsheet'), {
    data:data,
    columns: [
        {
            type: 'text',
            title:'Car',
            width:90
        },
        {
            type: 'dropdown',
            title:'Make',
            width:120,
            source:[
                "Alfa Romeo",
                "Audi",
                "Bmw",
                "Chevrolet",
                "Chrystler",
                "Dodge",
                "Ferrari",
              ]
        },
        {
            type: 'hidden',
        },
     ]
});
```

Or defined style with Jquery Selector
 `$( 'table.jexcel tr td[data-x="0"]').css( "display", "none" );`

0 is an index of column

**Comment by VictorCandido** [comment]
The problem in setting the column hidden is that I need the event to be dynamic. I need to set hidden in some cases and other cases be visible. Is there a way to do that?

I'm already doind with jQuery "$( 'table.jexcel tr td[data-x="0"]').css( "display", "none" );", but the problem is that I have a lot custom css on the cells, rows and columns... When I hide the column with this function of jQuery, I destroy all my CSS, so I need to recreate almoast everything.

**Comment by GBonnaire** [comment]
In JExcel, when you set to hidden a column, you set display:none on this column. you give same problem.

can you test with visibilty:hidden and/or width: 0px ?

**Comment by pphod** [comment]
I have created some new methods to dynamically show and hide columns.

table.showColumn(colNumber); // the first column is column 0
table.hideColumn(colNumber); // the first column is column 0

**Comment by VictorCandido** [comment]
Thank you so much!! That's what I needed

**Comment by paulhodel** [comment]
No worries Vitor.

Please consider helping out the project for only 4,20 / month. It will be much appreciated.
https://bossanova.uk/jexcel/v3/support

**Comment by debamishra14** [comment]
@paulhodel @Guillaume-Bo can you guys please comment on issue: https://github.com/paulhodel/jexcel/issues/1162

**Comment by Louise-Huang** [comment]
@pphod Is there any method could hide rows just like hideColumn() ?

**Comment by Louise-Huang** [comment]
I tried to use table.hideRow(rowNum). It seems that there is this method, but no matter what the rowNum is, only the first row will be hidden.

**Comment by GBonnaire** [comment]
Hi, 

i tried, and hideRow hide the complet row not only first column. 
0 = first row

Can you reproduct error on jsfiddle ?

**Comment by Louise-Huang** [comment]
@GBonnaire 

Hi, here is my codepen.
https://codepen.io/LouiseHuang/pen/oNWbjrX

**Comment by GBonnaire** [comment]
Hi, ty

Ok problem is on version Pro. For support for version pro is here : https://github.com/jspreadsheet/pro/issues

I inform team of development of this bug thanks

**Comment by Louise-Huang** [comment]
Hi,

Oh, I'm so sorry that I didn't find this page is support for version CE. Anyway, thank you so much.

**Comment by GBonnaire** [comment]
Don't worries, here we help for version Pro too, but i'm not dev of JSS Pro, only Dev plugins of JSS Pro and i help here when i can 😊  And for bug like this, on page support, Team dev see easier the problems 😊 

Have good day

**Comment by Louise-Huang** [comment]
Hi,
I take the liberty to ask, when will this method be fixed in version pro? Because I'm a bit urgent. Thank you.

**Comment by hodeware** [comment]
That will be fixed today.

**Comment by Louise-Huang** [comment]
@hodeware 
Awesome! Thank you so much! 😄

**Comment by hodeware** [comment]
It has been fixed. v7.9.20+

**Comment by Louise-Huang** [comment]
@hodeware 
First of all, thank you for quickly solving my problem, hideRow can be used normally, but I found that showRow seems to be unavailable. Could you please fix it again? Thank you so much.

**Comment by hodeware** [comment]
Hi Louise,
Both methods are available.
hideRow, showRow

Are you using Pro?

**Comment by Louise-Huang** [comment]
Hi Paul,
Yes, I do use pro v7. And I really can not use showRow 😢 

https://codepen.io/LouiseHuang/pen/oNWbjrX

**Comment by hodeware** [comment]
Please try again:
https://jsfiddle.net/w0co5ngv/

**Comment by Louise-Huang** [comment]
It's available! Thank you so much.

**Comment by chepo92** [comment]
hideColumn doesn't hide respective cell in footer
