### ISSUE TITLE
Does it work with decimal numbers?

### ISSUE THREAD

**Issue by roosalles** [jspreadsheet/ce#77]
Hi Paul, thanks for the effort on the plugin!

Is this scenario supposed to work? http://take.ms/RDWos
I am trying to use the SUM formula with decimal numbers but it doesn't calculate it correctly. Could you help in this case?

Thanks

**Comment by pphod** [comment]
Please update your version from the repo. I have submit a quick fix for that. You can refers to the example below. The use of formulas still on improvement.

https://bossanova.uk/jexcel/examples/including-formulas-on-your-spreadsheet
