### ISSUE TITLE
Use Custom Formula to accept 2 sets of arrays

### ISSUE THREAD

**Issue by jonijimenez** [jspreadsheet/ce#771]
Hi @paulhodel ,

I'm trying to implement `SUMPRODUCT()` functionality into jexcel using a custom formula, 
However when I try to pass 2 sets of columns in to the formula e.g. 
`SUMPRODUCT(A1:A3, B1:B3)`, 
the arguments comes out as a single large array containing all the parameters
e.g. as such : `SUMPRODUCT(A1, A2, A3, A1, A2, A3)` ...

Is there a better solution to this problem?
Thank you very much

**Comment by pphod** [comment]
You can create a custom method for that. This is the code of the original SUM. You should expect to get the arguments and treat those as follow:

```
        exports.SUM = function() {
            var result = 0;
            var argsKeys = Object.keys(arguments);
            for (var i = 0; i < argsKeys.length; ++i) {
                var elt = arguments[argsKeys[i]];
                if (typeof elt === 'number') {
                    result += elt;
                } else if (typeof elt === 'string') {
                    var parsed = parseFloat(elt);
                    !isNaN(parsed) && (result += parsed);
                } else if (Array.isArray(elt)) {
                    result += exports.SUM.apply(null, elt);
                }
            }
            return result;
        };
```

The second example on this page shows a custom method.
https://bossanova.uk/jexcel/v3/examples/spreadsheet-formulas

**Comment by luser** [comment]
For the record I wanted this exact same thing and after realizing that formula evaluation does expansion of ranges like `A1:A3 => A1, A2, A3` and then does the final execution with `eval` I realized I could just pass the ranges as arrays to my function using a cell value like `=MYFUNC([A1:A9], [B2:B9])` and then `function MYFUNC(col1, col2) { ... }`.
