### ISSUE TITLE
rtl adjustment

### ISSUE THREAD

**Issue by chenkamin** [jspreadsheet/ce#774]
hello all,

I have a problem with rtl.
When im trynig to exapnd my columns in rtl mode the column expand in the wrong way.
here's a jsfiddle for you to test

https://jsfiddle.net/amiheines/ocbj9edf/3/

thanks 
chen

**Comment by pphod** [comment]
Hi Chen,
This seems to change how the browser renders and interprets CSS, etc. jExcel is just a HTML table, and it seems the CSS/JS are rendering a little bit different. I will keep this issue to bring that as a new feature in futures releases.

**Comment by chenkamin** [comment]
hey Paul,
my colleague, Ami Heines did some work and research about the RTL issues, 
he will send you a pull request soon.

thanks for the comment and the awesome Jexcel.

**Comment by pphod** [comment]
Thats great news!
