### ISSUE TITLE
AVERAGE function of a does not work when autoCasting is set to false and a cell is referenced

### ISSUE THREAD

**Issue by lucBoillat** [jspreadsheet/ce#775]
The AVERAGE function returns NaN or a wrong value when using a cell reference as an input and autoCasting has been set to false.
Example Config:
_|   **A**   |
**1**   |   1    |
**2**   |   5    |
**3**   |  3  |

=SUM(A1:A3) returns 9, which is correct
=AVERAGE(A1, 3) returns 3, but should return 2
=AVERAGE(A1, A3) returns NaN, but should return 3

Why does SUM seem to work but AVERAGE does not?

**Comment by pphod** [comment]
Sorry, I have tested and seems to be working fine.
https://jsfiddle.net/paulhodel/cwgb9upv/2/
