### ISSUE TITLE
Set a dropdown on a single cell, not an entire column?

### ISSUE THREAD

**Issue by markben77** [jspreadsheet/ce#778]
Is there any way to set a cell to a type that is different than the column? For example, to set a cell to be a dropdown, and that cell exists in a text column?

I've looked through all the docs and examples but I cannot find the answer to this. I was thinking I could create a custom column type and hardcode to look for an individual cell and do something different there. Not sure if that would work, but was wondering if there is a better approach.

This is an incredible piece of software, thanks for putting so much effort into it!

**Comment by pphod** [comment]
This is not available within the native features, but you can create a custom column type, where you can handle different types based on the row.

The second example on this page shows how it works.
http://bossanova.uk/jexcel/v3/examples/column-types

**Comment by pphod** [comment]
This is now possible on Pro.
https://jexcel.net/v5/cases/payment-calculator
