### ISSUE TITLE
getJson(true) return null [] array

### ISSUE THREAD

**Issue by volkansari** [jspreadsheet/ce#779]
getjson (true) returns an empty array backwards. I guess (obj.records [j] [i] .classList.contains ('highlight')) ==> false highlight tag wrong css tag. What can I do.

**Comment by pphod** [comment]
I have tested and it is working fine.
true brings only the highlighted cells. 
false brings all table.

**Comment by volkansari** [comment]
![ornek](https://user-images.githubusercontent.com/58942482/71409229-d9698880-2651-11ea-8bf9-5d5c90cdf0f3.jpg)
all records return as shown in output I want json values of selected records to return

**Comment by volkansari** [comment]
![ornek2](https://user-images.githubusercontent.com/58942482/71409362-539a0d00-2652-11ea-82d6-857c00e2a896.jpg)
getJson(true)

**Comment by pphod** [comment]
https://bossanova.uk/jexcel/v3/examples/import-data
1) Go to example 3
2) Select some cells
3) Open the console
4) table3.getJson(true);

You will get only the selected cells.

**Comment by volkansari** [comment]
![Başlıksız-2](https://user-images.githubusercontent.com/58942482/71418724-08492400-267d-11ea-9b69-9c25aeb41857.jpg)
You say is true. But when you call inside a function or click the button it returns an empty array

**Comment by volkansari** [comment]
Thank you very much for your reply.

**Comment by pphod** [comment]
Ok, the problem is. If you click in the button (outside) the table, you are losing the selection. Your button must be inside the DIV you use to create the table with class: .jexcel_container

**Comment by volkansari** [comment]
OK.I corrected.it runing.Thanks Paul for everything.
