### ISSUE TITLE
error pasting date into calendar cell

### ISSUE THREAD

**Issue by sonofwill** [jspreadsheet/ce#78]
If I paste a date into a cell of type "calendar", the fields (day,month,year) get mixed up. What should be DD-MM-YYYY (as defined in my options->format property), it shows as YYYY-MM-DD.

For example, if I paste the data "19-10-1998", it appears as "1998-10-19" in the cell. And when I bring up the calendar picker it shows the month of Oct and Year of 19.

It works correctly if I type a date in manually.

Here is my code

_$('#my').jexcel({
			            minDimensions:[8,15],
			            colHeaders: ['Last Name','First Name','Middle Name','Birth Date','Grade','Gender','SPED','ELL'],
			            colWidths: [180,180,180,100,80,80,80,80],
			            columns: [
				            { type: 'text'},
			                { type: 'text'},
			                { type: 'text'},
                                        { type: 'calendar', options: { format:'DD-MM-YYYY' }},
			                { type: 'dropdown',source:['K',1,2,3,4,5,6]},
			                { type: 'dropdown',source:['m', 'f'] },
			                { type: 'dropdown',source:['y', 'n'] },
			                { type: 'dropdown',source:['y', 'n'] }
			            ]
		            });_

**Comment by pphod** [comment]
This is not an error, but probably you are not expecting this behaviour. Basically, when you are copying the content of the cell will be not formatted 'yyyy-mm-dd hh:mi:ss'. When you paste, the cell is expecting the content without formatting. This is due different formats that can be pasted on the table. You can customise this behaviour by creating a new calendar column, following this example:

https://bossanova.uk/jexcel/examples/integrating-a-third-party-plugin-into-your-spreadsheet

**Comment by uttara-appu** [comment]
Hi, I'm facing similar issue and the link given above ( https://bossanova.uk/jexcel/examples/integrating-a-third-party-plugin-into-your-spreadsheet ) is not available for me. Please help.

**Comment by pphod** [comment]
This is what you are looking for:
https://bossanova.uk/jexcel/v4/examples/column-types

**Comment by uttara-appu** [comment]
Hi Paul, Thanks for the reply. I had checked this one, but the issue I'm facing is different.
I'm trying to auto-populate a date value (specifically to today's date) upon selecting a dropdown value, and it should be editable.

But after I set the date, the format  that is being shown is : 'DD/MM/DD'
That is, the year is shown as 12 for today. (12/26/12)

My code as below:

For calendar column:
            type: 'calendar',
            options: { format:'MM/DD/YYYY'},
            title:'My Date',
            name:'My Date',
            width:90,

Event is:
onchange: onchanges,

var onchanges = function(instance, cell, x, y, value) {
	if(x == 10){
		var myDate = instance.jexcel.getValueFromCoords(11, y);
		var currentDate = new Date()
		var day = currentDate.getDate()
		var month = currentDate.getMonth() + 1
		var year = currentDate.getFullYear()

		today = month + '/' + day + '/' + year;

		if(value!=null && (myDate=='' || myDate == null)){

			instance.jexcel.setValueFromCoords(11, y, today,true)

		}
	}
}

**Comment by uttara-appu** [comment]
Just after auto-populating:

![image](https://user-images.githubusercontent.com/76616772/103153326-d568cd00-47b5-11eb-8d1c-c7ec346fd0d1.png)

Calendar date-picker is shown as:
![image](https://user-images.githubusercontent.com/76616772/103153342-ec0f2400-47b5-11eb-9ac8-a6916624d9d7.png)

Final value (when clicked outside):
![image](https://user-images.githubusercontent.com/76616772/103153357-00ebb780-47b6-11eb-89fc-c45638413787.png)

**Comment by pphod** [comment]
Try to populate "without" format: 'YYYY-MM-DD'

**Comment by uttara-appu** [comment]
I tried that too. Still facing the same issue.
Correct me if I'm wrong. This is what I did:
I removed - options: { format:'MM/DD/YYYY'}, 
and set today as: 
today = year + '/' + month + '/' + day;

**Comment by uttara-appu** [comment]
Sorry, not the same issue. This time, the value didn't get populated at all.

**Comment by pphod** [comment]
You first code is fine.... just change this:
instance.jexcel.setValueFromCoords(11, y, '2020-12-25 00:00:00', true);

**Comment by uttara-appu** [comment]
Works! But how do I take dynamic value? (today's date whenever I enter)

**Comment by pphod** [comment]
today = date.getFullYear() + '-' + etc... // today must have YYYY-MM-DD HH:MM:SS format, just for setting.

**Comment by uttara-appu** [comment]
Thanks a lot!
Tried this - var today = year + '-' + month + '-' + day +' 00:00:00'; and it's working fine. 👍
