### ISSUE TITLE
Horizontal Scroll position is not proper.

### ISSUE THREAD

**Issue by Ilayaraja-n** [jspreadsheet/ce#780]
Created jExcel grid with the properties of tableOverflow:true, tableHeight:"450px" and tableWidth: "1600px".
Issue: Horizontal scrollbar is not appearing immediately after the table rows. It looks completely disconnected from jExcel grid. 
Resolution: The "jexcel_content" class div is created with the height attribute, hence it is taking full height of 450px. Instead of "height" attribute "max-height" attribute can be used so that this issue will be resolved.
Current html code: <  div class="jexcel_content" style="overflow: auto;height: 450px;width: 1600px;"></div>
Expected html code: <  div class="jexcel_content" style="overflow: auto;max-height: 450px;width: 1600px;"></div>

Note: This issue is not available in the jExcel version 2.1.0

![Horizontal_Scroll_position](https://user-images.githubusercontent.com/46338652/71245811-8931b400-233b-11ea-89bb-bd64123143a4.png)

**Comment by pphod** [comment]
This has been fixed.
