### ISSUE TITLE
Vertical scrollbar is shown on focusing the last row

### ISSUE THREAD

**Issue by Ilayaraja-n** [jspreadsheet/ce#783]
By default vertical scrollbar is not there in my jExcel grid. But while moving focus to the last row, vertical scrollbar is getting shown. Adding style “padding-bottom: 2px” for the “jexcel_content” class div this issue is getting resolved. 

![Vertical_Scrollbar](https://user-images.githubusercontent.com/46338652/71349489-22a7d280-2595-11ea-9134-a039c5ac8a46.png)

**Comment by pphod** [comment]
it has been updated, thanks

**Comment by pphod** [comment]
Please consider subscribe to help out the project. ;)
https://bossanova.uk/jexcel/v3/support

Thanks
