### ISSUE TITLE
Numeric cell is allowing non-numeric values

### ISSUE THREAD

**Issue by Ilayaraja-n** [jspreadsheet/ce#784]
Able to update non-numeric values in numeric cell. Number value check is missing in the jExcel version 3x, whereas this issue is working fine in jExcel version 2.1.0.

**Comment by pphod** [comment]
This is correct due to the capability to accept masked values with non-numeric values on the cell.

**Comment by pphod** [comment]
If you wish to have only numbers you can use the mask to accept only numbers in your cell.
