### ISSUE TITLE
JExcel version on CDN

### ISSUE THREAD

**Issue by felixvandal** [jspreadsheet/ce#79]
Hello Paul!
I hope you are well.
I used JExcel on another projet. 
I took the version on cdnjs.cloudflare.com and they have the 1.2.2 version.
Do you think you could update it there?
Thank you and have a nice day!

**Comment by pphod** [comment]
It has been updated. https://cdnjs.cloudflare.com/ajax/libs/jexcel/1.3.4/js/jquery.jexcel.js

**Comment by felixvandal** [comment]
Awesome thanks
