### ISSUE TITLE
Formula not working into dynamically added row?

### ISSUE THREAD

**Issue by mayankvadia** [jspreadsheet/ce#790]
How can I use formula of previous row into dynamically added row ?

If I have three row in my table, In last column is for total  and I am adding new row by press of `enter` key then How can i add sum formula for 4th row ?

**Comment by pphod** [comment]
You can drop one email to: paul@jexcel.net asking assistance on this one.

**Comment by pphod** [comment]
https://jsfiddle.net/paulhodel/36f1p2nz/
