### ISSUE TITLE
keyboard keys does not work on updateSelectionFromCoords

### ISSUE THREAD

**Issue by msheeraz** [jspreadsheet/ce#792]
hi, i am opening a modal on clicking certain cell and i have achieved this. After the close of modal i want to restore the cell selection with updateSelectionFromCoords and is able to do that, however i cannot move the selected cell with keyboard keys.

Appreciate your help.

Regards

**Comment by pphod** [comment]
If the focus is on any element in the document, the keys should work fine. In your case, you can try to focus in the table element, after the method, just in case.
