### ISSUE TITLE
How to get dropdown ID?

### ISSUE THREAD

**Issue by krosoftware** [jspreadsheet/ce#793]
Hello
you use this file https://bossanova.uk/jexcel/v3/countries to fill your first demo displayed here: https://bossanova.uk/jexcel/v3/examples/dropdown-and-autocomplete
Question is - how to get ID once clicked on combo?
I know for "onchange" event and there I can get newValue but I get only name and not ID.
How to get ID of selected row in dropdown?
Thank you.

**Comment by krosoftware** [comment]
Solved, my mistake..

**Comment by gargri** [comment]
can u tell me how u solved that problem
