### ISSUE TITLE
Spreed sheet is not responsive

### ISSUE THREAD

**Issue by aleza0717** [jspreadsheet/ce#797]
I would like to raise an issue, upon clicking tab or arrow key, the spreed sheet is not responsive or do you have any solution how my spreed sheet will navigate on my active cell?

Thank you,

**Comment by pphod** [comment]
I am not sure what do you meant. But, this is about the initialization without focus, the solution will be:

Please consider subscribing as a supporter. It will help the project...
https://bossanova.uk/jexcel/v3/support

```
<html>
<script src="https://bossanova.uk/jexcel/v3/jexcel.js"></script>
<script src="https://bossanova.uk/jsuites/v2/jsuites.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jexcel/v3/jexcel.css" type="text/css" />
<link rel="stylesheet" href="https://bossanova.uk/jsuites/v2/jsuites.css" type="text/css" />

<div id="spreadsheet"></div>

<script>
var data = [
    ['Jazz', 'Honda', '2019-02-12', '', true, '$ 2.000,00', '#777700'],
    ['Civic', 'Honda', '2018-07-11', '', true, '$ 4.000,01', '#007777'],
];

jexcel(document.getElementById('spreadsheet'), {
    data:data,
    columns: [
        { type: 'text', title:'Car', width:120 },
        { type: 'dropdown', title:'Make', width:200, source:[ "Alfa Romeo", "Audi", "Bmw" ] },
        { type: 'calendar', title:'Available', width:200 },
        { type: 'image', title:'Photo', width:120 },
        { type: 'checkbox', title:'Stock', width:80 },
        { type: 'numeric', title:'Price', width:100, mask:'$ #.##,00', decimal:',' },
        { type: 'color', width:100, render:'square', }
     ],
    onload: function(a,b) {
        b.updateSelectionFromCoords(0, 0);
    }
});
</script>
</html>
```

**Comment by aleza0717** [comment]
What I mean is when I use arrow key or tab key to navigate to other cells
that overflow from the displayed screen the scroll y or x is not auto
scroll where my active cell located.

**Comment by pphod** [comment]
You need to activate the tableOverflow:true or fullscreen:true, to activate the table scrolling.

**Comment by aleza0717** [comment]
I already used tableOverFlow: true but its not solve my problem, when I
used the fullscreen It already fixed but I dont want to use it since I want
to display the spreed sheet in some part of my website.

Thank you for your response ☺️

**Comment by pphod** [comment]
Ok, but what is your problem? jExcel will position the cell in highlighted correctly if the scroll is the jexcel scroll and not the body scroll.

**Comment by aleza0717** [comment]
I already resolved it. I add tableWidth and its works ☺️

**Comment by pphod** [comment]
Glad that it is working for you. Don't forget to become a supporter:
https://bossanova.uk/jexcel/v3/support
