### ISSUE TITLE
Integrating typeheadjs for autosuggest

### ISSUE THREAD

**Issue by msheeraz** [jspreadsheet/ce#798]
Hi,

I am working with jsuites autocomplete feature with a huge json list and it takes substantial amount of time to start searching. Would that be possible to use such a huge list on prefatch method making it easier and workable with jsuites?

Alternatively, typeheadjs (https://twitter.github.io/typeahead.js/) from twitter is great choice while working on such a huge file. can you please help me integrating typeheadjs  in jexcel autocomplete. It would be a huge of help. Thanks in advance.

Regards

**Comment by pphod** [comment]
I have released a new version of jSuites v2.4.0

The performance now is much better. I have tested dropdowns with 10k+. The search is fast and the render is much, much better.

I hope that helps your project.

Please consider subscribe as a supporter. It will help the project...
https://bossanova.uk/jexcel/v3/support

```
<html>
<script src="https://bossanova.uk/jsuites/v2/jsuites.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jsuites/v2/jsuites.css" type="text/css" />

<div id="dropdown0"></div>

<script>
jSuites.dropdown(document.getElementById('dropdown0'), {
    url: '/jsuites/data', // URL TO YOUR EXTERNAL RESOURCE
    autocomplete: true,
    multiple: true,
    width: '280px',
});
</script>
</html>
```

**Comment by msheeraz** [comment]
thanks for the feedback. i am using this json file (https://jsonblob.com/ebf3e006-2aca-11ea-8ff8-430c08718c53)

it seems faster than previous version for sure but not as fast as typeheadjs. 

is there anyway i could search from any part of the string? currently it supports only the start of the string.

Thanks in advance.

**Comment by krosoftware** [comment]
Maybe it is a good time to implement also option to get records from database while typing, with option to edit received value (like you promised [here](https://github.com/paulhodel/jexcel/issues/652)).
Thank you.

**Comment by honey-system** [comment]
> Maybe it is a good time to implement also option to get records from database while typing, with option to edit received value (like you promised [here](https://github.com/paulhodel/jexcel/issues/652)).
> Thank you.

I agree with the comment. @paulhodel  Can you add "searchFn" to the arguments?

**Comment by pphod** [comment]
This has been implemented on Jsuites.
https://bossanova.uk/jsuites/dropdown-and-autocomplete/remote-search

I should add examples with jExcel integration soon.
