### ISSUE TITLE
can you please give an example on how to use "onbeforepaste"

### ISSUE THREAD

**Issue by UrmilaShell** [jspreadsheet/ce#799]
Hi Paul,

I'm working on copy paste feature. I'm trying to copy data from notepad and parse the data and paste into jexcel component. Can you please give example on how to use onbeforepaste. 
i keep getting the below error

ERROR ReferenceError: instance is not defined at Object.obj.paste (webpack-internal:///../../../../jexcel/dist/jexcel.js:5251)

Thanks

**Comment by pphod** [comment]
If you are just want to copy and paste, you don't need to declare this method. This method is to change whatever the user paste on your spreadsheet.

The variable instance is not part of the jExcel source code. Are you using the most recent version?

I'm asking users to subscribe as a supporter? Can you support jExcel?

https://bossanova.uk/jexcel/v3/support

Thanks
