### ISSUE TITLE
Mobile friendly Responsive Tables

### ISSUE THREAD

**Issue by ArulRozario** [jspreadsheet/ce#80]
Hi Paul, I am very happy to be in touch with you and your great plugin. My project has a rapid development just because of your plugin. I have  a need to make this unique plugin responsive on small screens. I found a plugin that turns any html table responsive on small screens. 
 http://johnpolacek.github.io/stacktable.js
Is it possible to combine this with jexcel? . I know nothing about Javascript or jquery. Help me if possible.

**Comment by pphod** [comment]
If you pay attention to what this plugins is doing, basically is creating a new table with only one column, hiding the original table when the size of the screen is lower then a certain value and showing the one column table.

Unfortunately, jExcel considers the structure of the table and won't work properly.
