### ISSUE TITLE
Numeric columns sort order is not working properly

### ISSUE THREAD

**Issue by Ilayaraja-n** [jspreadsheet/ce#800]
Hi,
Numeric columns sort order is not working properly. This is worked fine in jExcel version 2.1.0

![Sort_Issue](https://user-images.githubusercontent.com/46338652/71652728-84aec780-2d4d-11ea-9219-39b83e805db2.png)

**Comment by pphod** [comment]
This will be fix in the next release.

**Comment by pphod** [comment]
That has been fixed on the Pro and should be brought to CE in the next release.
https://jexcel.net
