### ISSUE TITLE
Pagination div is taking extra space, even if pagination is not enabled

### ISSUE THREAD

**Issue by Ilayaraja-n** [jspreadsheet/ce#801]
Hi,
I have not enabled pagination, still it is taking unnecessarily extra space in the bottom of the jExcel grid. Please add the style "display:none" for the "jexcel_pagination" class div, if pagination is not enabled, so that it will not take the extra space.

![Pagination_div_issue_1](https://user-images.githubusercontent.com/46338652/71654326-225ac480-2d57-11ea-8c31-13e5aa375278.png)

![Pagination_div_issue_2](https://user-images.githubusercontent.com/46338652/71654379-8ed5c380-2d57-11ea-89db-d3034a058c4d.png)

**Comment by pphod** [comment]
Make sense. It has been done. It will be available in the next release.
