### ISSUE TITLE
Scrollbar size issue in Chrome

### ISSUE THREAD

**Issue by Ilayaraja-n** [jspreadsheet/ce#802]
Hi,
Scrollbar size is not proper in chrome. Please make the scrollbar size similar to Firefox browser.

![Scrollbar_size_1](https://user-images.githubusercontent.com/46338652/71657261-1e35a380-2d65-11ea-88ba-674cc4c3ef7c.png)

Removing the css classes "jexcel_content::-webkit-scrollbar", "jexcel_content::-webkit-scrollbar-track", "jexcel_content::-webkit-scrollbar-thumb" in jexcel.css file the scrollbar looks nice.

![Scrollbar_size_2](https://user-images.githubusercontent.com/46338652/71657337-74a2e200-2d65-11ea-993e-3d27a158c38e.png)

**Comment by pphod** [comment]
I suspect you have some cache CSS. Can you please confirm, I have just tested on Chrome.

![image](https://user-images.githubusercontent.com/6019713/71850215-b61bf000-30cb-11ea-9ddd-fddd5b7114ac.png)
