### ISSUE TITLE
Headers are not getting download on Saveas

### ISSUE THREAD

**Issue by Ilayaraja-n** [jspreadsheet/ce#803]
Hi,
Headers are not part of the downloaded file. I have set the parameter "csvHeaders:true" still the downloaded file does not the headers.

**Comment by pphod** [comment]
csvHeaders is to load the first line of the data as the header. To download the headers as data you can do by:

table.download(true); // with headers as first line
table.download(false); // without headers

**Comment by Ilayaraja-n** [comment]
Hi,
I am using “Save as…” of jExcel inbuilt option. Please provide some parameter to include or exclude headers while using this option.
Note: in jExcel version 2.1.0, on setting the parameter “csvHeaders:true”, it used to download headers as well.

![SaveAs](https://user-images.githubusercontent.com/46338652/71711493-5998a680-2e27-11ea-8520-f2e5dc655bd8.png)

**Comment by pphod** [comment]
In this case, you need to customize your contextMenu to change the download(true);
https://bossanova.uk/jexcel/v3/examples/contextmenu

**Comment by BeniTasik** [comment]
Hi.. 

I also unable to save the headers on download, but then I found the solution is quite easy:
add **includeHeadersOnDownload: true** to update default setting from **false**:

jexcel(document.getElementById("rencanaProduksi"), {
                    includeHeadersOnDownload:true,
...
}
