### ISSUE TITLE
Edit on iPad Pro

### ISSUE THREAD

**Issue by krosoftware** [jspreadsheet/ce#804]
Hello
Edit of cell on iPad Pro with latest iOS does not work correctly.
If I touch cell and keep for a second, it select cell content (if there is content) and I need to touch one more time and then I can write into cell.
If there is no content in a cell, I also need to touch one more time after 1 sec touch/hold.
Can you please check this?
Thank you.

**Comment by pphod** [comment]
I can't find a solution to open a virtual keyboard on the cell focus. And there is no function to trigger the virtual keyboard thought javascript. I will keep this open to find a workaround for that.

**Comment by krosoftware** [comment]
Thank you.
I will not try to be smart but maybe you missed this:
https://www.outsystems.com/forums/discussion/46409/focus-within-ios-mobile-is-not-opening-keyboard/
https://stackoverflow.com/questions/4609765/manually-triggering-the-iphone-ipad-ipod-keyboard-from-javascript

**Comment by pphod** [comment]
Thanks for that. I have improve the edition on IOS. Now, I need to improve the Color/Image editor to be responsive. I will do that soon.

**Comment by krosoftware** [comment]
Awesome, thank you so much.
