### ISSUE TITLE
Reloading Settings Locks Table

### ISSUE THREAD

**Issue by stevenpeters2020** [jspreadsheet/ce#806]
Hi, I'm using jexcel3. I saved the configuration object using table.getConfig(). I didn't see a corresponding table.setConfig(), so I reinitialized the table using:

settings = table.getConfig()
table = jexcel(document.getElementById('grid'), settings)

The table hangs afterwards. I can successfully set only the data using settings.data. But I'd like to reload the data, font formats, and column widths from a file.

Regards,
SP

**Comment by pphod** [comment]
Can you create your table on jsFiddle?

**Comment by pphod** [comment]
Using your example:

// You create the table
var table = jexcel(document.getElementById('grid'), {
    // Initial configuration
});

// You get the configuration
var settings = table.getConfig();

// You destroy the table
table.destroy();

// You recreate the table
var table = jexcel(document.getElementById('grid'), settings); // This brings everything including the data

**Comment by pphod** [comment]
Steven,
Please consider be a sponsor and get exclusive technical support and special features.
https://www.bossanova.uk/jexcel/v3/support
