### ISSUE TITLE
Border Issues

### ISSUE THREAD

**Issue by chenkamin** [jspreadsheet/ce#807]
Hey,
I cant manage to handle the border width in the table.

![Screenshot from 2020-01-05 15-16-41](https://user-images.githubusercontent.com/40539832/71780703-9226b480-2fce-11ea-8279-492744b2ccb0.png)

If i have 2 adjacent cells with border: 1px solid black; it dosent look good.
I tried to use 
table{border-collapse: collapse;}
table td {border-collapse:collapse}
but it dosent change.
I would like know if it is my lack of experience with HTML or a problem? and of course, do you have an idea how to fix it.

thanks
chen k

**Comment by paulhodel** [comment]
jExcel has already the cell border collapsed. What you are trying to do. I might be able to help you if you give more details, examples, jsfiddle, etc.

**Comment by kevinirlen** [comment]
Sorry to bump in out of the blue

@chenkamin did you find the answer to this problem ?

**Comment by paulhodel** [comment]
Reviewing that request again, the problem is because the border needs to be separated because of the sticky border problem. So, to set up the border correctly on the current distributions CE or PRO you must define left, bottom borders from the current and previous cells. That problem is resolved in future releases. If you wish to leave your email (contact@jexcel.net) I am happy to send you a notification when the new release is available.

**Comment by hodeware** [comment]
Reviewing that request again, the problem is because the border needs to be separated because of the sticky border problem. So, to set up the border correctly on the current distributions CE or PRO you must define left, bottom borders from the current and previous cells.

**Comment by kevinirlen** [comment]
@hodeware do you have an example on how to achieve this?

**Comment by hodeware** [comment]
Sorry, I don't have anything to create that automatically at this point. If you take a look at the jexcel.css in the repository you will see how it is done, it should follow the same principle. You need to define left and tops, where rights and bottoms should be transparent. If you wish, I can notify you when we have something available.

**Comment by kevinirlen** [comment]
@hodeware , that would be great. I'm looking at the css. My use case is, having a button that add borders to a range of cells, that works! But the rendering is like the image in the initial post.

**Comment by kevinirlen** [comment]
I'll post something if I find the solution..Thanks for replying

**Comment by kevinirlen** [comment]
Hi, 

I tried the code below, which solves my problem. Hopfully this can shed some lights for others. Note that the code i'm using is vuejs. But you'll get the idea :)

```
// Get highlited cells to add borders
const cellNames = this.table.getHighlighted().map(el => {
  const x = el.getAttribute('data-x')
  const y = el.getAttribute('data-y')
  return jexcel.getColumnNameFromId([x, y])
})

// Here we get only cells on the left
const leftCellsOnly = this.table.getHighlighted().map(el => {
  if (el.classList.contains('highlight-left')) {
    
    // We substract 1 here to get the cell that needs a right transparent border
    // Means cell C6 won't have a left border, so we grab cell B6 and set the border right to transparent
    const x = el.getAttribute('data-x') - 1
    const y = el.getAttribute('data-y')
    return jexcel.getColumnNameFromId([x, y])
  }
})

const topCellsOnly = this.table.getHighlighted().map(el => {
  if (el.classList.contains('highlight-top')) {
    const x = el.getAttribute('data-x')

    // We substract 1 here to get the cell that needs a bottom transparent border
    // Means cell C6 won't have a top border, so we grab cell C5 and set the border bottom to transparent
    const y = el.getAttribute('data-y') - 1
    return jexcel.getColumnNameFromId([x, y])
  }
})

var update = cellNames.reduce((acc, curr) => {
  acc[curr] = attribut
  return acc
}, {})

// Set the correct styles
if (leftCellsOnly.length > 0) {
  for (let left in leftCellsOnly) {
    if (leftCellsOnly[left]) {
      update[leftCellsOnly[left]] = 'border-right:transparent'
    }
  }
}

var k = 0;

if (topCellsOnly.length > 0) {
  for (let top in topCellsOnly) {
    if (topCellsOnly[top]) {
      update[topCellsOnly[top]] = 'border-bottom:transparent'
    }
  }
}

this.table.setStyle(update)
```

**Comment by kevinirlen** [comment]
![borders](https://user-images.githubusercontent.com/45947370/118146719-f27a0180-b41f-11eb-97f1-bc6f6384707f.png)

This is what I ended up with.
