### ISSUE TITLE
Table footer

### ISSUE THREAD

**Issue by felixvandal** [jspreadsheet/ce#81]
Happy New Year Paul
I was wondering if there was any easy way to do a footer with jExcel.
I need to display a sum and i need a row at the end to show this
any thought?

**Comment by pphod** [comment]
Hey There! Does your table have a fix number of rows?

**Comment by felixvandal** [comment]
No fixed rows
I know i could use formula if the number of rows were fixed to sum in a row
I did find a way to do it.
I used the method suggested for the complex header and used it to create a footer.
I copied the style of the header to the footer and voila!
Could be nice to have a colFooters like colHeaders or to have a way to sumaryse data in a summary row

**Comment by pphod** [comment]
Understood. ;)

Another way to create a totalizer:
https://jsfiddle.net/paulhodel/03d5rhzo/

**Comment by felixvandal** [comment]
Thank you Paul.
Well, in the doc function were experimental, so i didn't look a lot at them.
I will check them out again if i use jExcel again in a near futur.
Have a nice day
