### ISSUE TITLE
Jexcel testing with React Testing Library

### ISSUE THREAD

**Issue by adidottxt** [jspreadsheet/ce#816]
Hi there,

I'm curious if you've had anyone try testing a Jexcel table with [React Testing Library](https://testing-library.com/docs/react-testing-library/intro)? I ask because it seems like the way Jexcel is set up does not allow for, say, a `fireEvent.click()` on a specific cell (this is also true without React Testing Library if I were to open up the console within my browser and try, say, `document.getElementsByTagName('td')[20].click()`) -- I might be wrong but per my understanding this is because the HTML table has the `unselectable` property set to `yes`, and this in the `jexcel.css` file:

```
.jexcel, .jexcel td, .jexcel_corner
{
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
  -webkit-user-drag: none;
  -khtml-user-drag: none;
  -moz-user-drag: none;
  -o-user-drag: none;
  user-drag: none;
}
```

I'm guessing your implementation of JExcel requires this to be handled so that `updateSelectionFromCoords` is used to select the cells instead, but is there any way around this for the sake of testing? In the browser, I've tried removing the `unselectable` attribute and uncheck the `*-user-select: none` css properties, but the `click()` action still does not work.

Thanks again for all your help.

**Comment by pphod** [comment]
The click on TD is working fine. The problem is, there is no event associated directly with the cell element in the DOM. There is one global event link to the document for each mouse event, those handles route the different e.target elements to different actions. I am not sure if this is clear.

**Comment by pphod** [comment]
You should use the NATIVE jexcel methods, but I am not sure what kind of tests you are trying to do.

One of the methods called by click in a TD would be:
updateSelectionFromCoords

How about calling those directly?

**Comment by adidottxt** [comment]
That makes sense - I was just looking into the `jexcel.js` code actually and noticed your `mouseDownControls` event listener, which is where this is all handled. I've been looking into finding a way to construct a MouseEvent with `data-x` and `data-y` attributes so that the `mouseDownControls` handler works, but unfortunately it doesn't seem like there's an easy way to do this (with or without React Testing Library)

WRT using `updateSelectionFromCoords` -- the front-end testing we're setting up with React Testing Library mimics what a user would do. We're mocking click/focus/blur events that mimic interactions with the DOM, so testing using `updateSelectionFromCoords` would not work given we're interacting with the Jexcel table that's presented like it would be in a browser (`<table class='jexcel' ...>`)

The test that I'm trying to set up mimics a user clicking on a cell, changing its value, and then hitting a "Save" button to send the table's new contents to a database. All of this is straightforward to build, but unfortunately recreating this using React testing library doesn't seem to be as simple.

I will continue looking into whether there is a way to construct a MouseEvent that is similar to what is needed to trigger the `mouseDownControls` event listener. Thanks again.

**Comment by pphod** [comment]
I guess you are not using the most appropriate tool since you won't trigger the event itself. Try to customize the event will lead to so many problems. Basically, one event per cell is not pratical since the table is so dynamic.

I would suggest you try that:
https://selenium.dev/

Regards,

**Comment by adidottxt** [comment]
Right, that makes sense.

Last q here -- I'm assuming there is no keyboard shortcut to select a cell? So if a user was to open a page with a Jexcel table + hit tab enough times to select the div with the table, there isn't a way to select the first cell (or any cell given you can move between cells once one is selected) via a keyboard shortcut?

Thanks again.

**Comment by pphod** [comment]
You can define a tabindex programatically to able to do that.

**Comment by adidottxt** [comment]
Ah true. Although I still run into the same issue of not being able to "select" a cell despite being able to tab to a specific cell once I set `tabindex` to 0, which I'm assuming is again down to how `updateSelectionFromCoords` is called, where the key down handlers require a cell to be selected based on [this](https://github.com/paulhodel/jexcel/blob/c404631e3d1762660742cc388523989f0381d23b/src/js/jexcel.core.js#L6284).

**Comment by pphod** [comment]
1) Focus on the table
2) Populate focus on first cell table.selectedCell = [0,0,0,0];
3) move arrows or programmatically table.up() table.down() etc
