### ISSUE TITLE
传入数据，会超出单元格显示，能不能在一个单元格自动换行或者像直接填写一样不超出单元格？

### ISSUE THREAD

**Issue by yanzhentao** [jspreadsheet/ce#818]
![image](https://user-images.githubusercontent.com/32361948/72220339-a5b3bb80-358a-11ea-92d2-d5a9b1e82478.png)

**Comment by pphod** [comment]
?

**Comment by pphod** [comment]
Yes, you can do that via CSS

.jexcel td {
overflow: hidden !important;
}
