### ISSUE TITLE
Feature Request: Merge currently-selected cells

### ISSUE THREAD

**Issue by hchiam** [jspreadsheet/ce#822]
It'd be nice to recreate the functionality that Excel / Google Sheets have where you can right-click and merge the currently-selected cells. As an **option in the context menu**, _instead of_ [programming a custom button](https://bossanova.uk/jexcel/v3/examples/merged-cells). Or is this already possible to customize the context menu (the one that shows upon right-click)?

**Comment by pphod** [comment]
You create that by adding a method in the custom contextMenu.
https://bossanova.uk/jexcel/v3/examples/contextmenu
