### ISSUE TITLE
jExcel grid is not loading in Internet Explorer 11, if text property is available

### ISSUE THREAD

**Issue by Ilayaraja-n** [jspreadsheet/ce#824]
jExcel grid is not loading in Internet Explorer 11, if text property is available as part of the configuration. without text property it is working fine.

![IE_Issue_1](https://user-images.githubusercontent.com/46338652/72512950-98d8e580-3872-11ea-8a10-490683f89c48.png)

![IE_Issue_2](https://user-images.githubusercontent.com/46338652/72512990-a8f0c500-3872-11ea-8788-be0061bc28b1.png)

**Comment by pphod** [comment]
It has been fixed, it will be available in the next release tomorrow.
