### ISSUE TITLE
Header border is not showing in Microsoft Edge

### ISSUE THREAD

**Issue by Ilayaraja-n** [jspreadsheet/ce#825]
Hi 
Header border is not showing in Microsoft Edge.

![Header_border_issue](https://user-images.githubusercontent.com/46338652/72514232-50222c00-3874-11ea-8887-6cf64dc3f2a0.png)

**Comment by pphod** [comment]
https://stackoverflow.com/questions/41882616/why-border-is-not-visible-with-position-sticky-when-background-color-exists/45042852
