### ISSUE TITLE
table.hideIndex() also hides the first column in the calendar widget

### ISSUE THREAD

**Issue by sgtpeppr** [jspreadsheet/ce#826]
Can be seen by adding "table = " to the jexcel junction on any of the examples in the documentation, then issuing table.hideIndex(). First column of the calendar widget disappears on table.hideIndex(), as well as the index column disappearing on the table of course. 

![image](https://user-images.githubusercontent.com/7807860/72583912-ecf8bf80-389c-11ea-8a42-0fd5748dfc76.png)

table.showIndex() redisplays the first column on the calendar - and the table index column. 

![image](https://user-images.githubusercontent.com/7807860/72583871-c470c580-389c-11ea-897b-9849e58c3b21.png)

**Comment by pphod** [comment]
Thanks, it has been fixed.
