### ISSUE TITLE
If the layout is different from English, the editor does not open

### ISSUE THREAD

**Issue by honey-system** [jspreadsheet/ce#828]
Thank you for the plugin, it is very good and I believe that it will develop further and become better.

When you start typing in English - editor opens, but switch to Russian, in my case, the action is ignored.

You can reproduce the problem on any table, for example: https://bossanova.uk/jexcel/v3/examples/column-types

**Comment by pphod** [comment]
Thanks! This is a lit bit hard for me to test. But, I am happy to go to a conference call on zoom or skype to help with that. My skype: paul.hodel
