### ISSUE TITLE
Headers for Save as using keyboard

### ISSUE THREAD

**Issue by smkarthikeee** [jspreadsheet/ce#829]
Hi Paul, Thank you for the wonderful library which does a lot of things out of the box. I understand that we can customize the context menu to download headers for save as option. However, I want to make sure keyboard shortcut Ctrl + S does the same as context menu. Is there way to customize that as well?

**Comment by pphod** [comment]
Please use includeHeadersOnDownload: true on the initialization, in this case will work for all downloads, including the default contextMenu.

**Comment by smkarthikeee** [comment]
Thank you for the quick response.
