### ISSUE TITLE
getHeader not works

### ISSUE THREAD

**Issue by vcxz09876** [jspreadsheet/ce#83]
I use google chrome (Version 62.0.3202.94 (Official Build) (64-bit)) and linux ubuntu 16.04 and try to write code, that acts with table as with array of structures.
I try to use getHeader function, but it not works even on example page https://bossanova.uk/jexcel/docs/programmatically-changes
I receive error in console. Screenshot attached.
![screenshot from 2018-01-08 18-50-31](https://user-images.githubusercontent.com/26848143/34679196-40e43a3a-f4a6-11e7-9568-26f0fae72e23.png)

**Comment by pphod** [comment]
Please find an example how to deal with the headers:
https://jsfiddle.net/paulhodel/xtfq8gw4/
