### ISSUE TITLE
Issue: When Freeze columns is set higher as 1, column names won't freeze.

### ISSUE THREAD

**Issue by RoeradeSolutions** [jspreadsheet/ce#830]
Hi,
At the example page: https://jexcel.net/v4/examples/freeze-columns you can put the property `freezeColumns:'1',` at the jexcel object to enable the first column to be sticky. But when we put the property on '2', then the second column name won't stay freezed at the view although the data will correctly freeze.

Just as the example page, we put freezeColumns at `freezeColumns:'2',` so the code will be:

`mySpreadsheet = jexcel(document.getElementById('spreadsheet'), {
        data:data1,
        minDimensions:[100,40],
        tableOverflow:true,
        tableWidth:'600px',
        freezeColumns:'2',
        columns: [
            { type: 'text', width:'100px', },
            { type: 'text', width:200, },
            { type: 'text', width:200, }
         ],
         allowComments:true,
    });
});`

Example by image:

![example](https://user-images.githubusercontent.com/15732980/72679257-c6f63980-3aad-11ea-8824-7087a4c2080a.png)

Is this something that can be resolved? That when the actual property is set to '2', then the column names itself also stays freezed just like the data. (So in this case A and B).

**Comment by pphod** [comment]
I have updated the website with the most recent version. But, I am not sure are you testing those changes in which browser. Can you check if is working for you?

**Comment by RoeradeSolutions** [comment]
Dear Paul, First of all thank you for you're quick response! The issue seems to be resolved in Firefox! Altough in google chrome 79.0.39 it still seems not to be working correctly. In google chrome with the new example, column name A  stays in place but column name C slides over the B column.

Examples by pictures:
![afbeelding](https://user-images.githubusercontent.com/15732980/72680120-8949de80-3ab6-11ea-99f3-ac218e0071a6.png)

**Comment by pphod** [comment]
It seems you have a cache version on your machine. I know that because you should see a shadow in the floating columns.

![image](https://user-images.githubusercontent.com/6019713/72680190-02ddce80-3aaf-11ea-9e40-a6cb3fbaa54b.png)

**Comment by paulhodel** [comment]
Please bear in mind this won't be working on Edge. Due <td> not accepting relative position. We are trying to find a solution to working in Edge/IE in the near future.

**Comment by RoeradeSolutions** [comment]
Hi Paul,
You are right, after clearing cache the issue seems also be resolved at google chrome. Thanks for you're quick solution!

**Comment by pphod** [comment]
Thanks Perfect! I am on skype, in case you need something else.

Skype: paul.hodel
