### ISSUE TITLE
Copy paste is not working properly

### ISSUE THREAD

**Issue by Ilayaraja-n** [jspreadsheet/ce#831]
Hi,
From the below screenshot I have copied the Nov, Dec and Jan column values and pasting into the Feb and Mar columns. It pasted Nov and Jan column values instead of Nov and Dec. 

![Copy_Paste](https://user-images.githubusercontent.com/46338652/72724243-c8f0f300-3ba8-11ea-9cca-114bafe65b44.png)

**Comment by pphod** [comment]
If you create a jsfiddle withy your example I am happy to take a look
