### ISSUE TITLE
Get comments from JSON along with data

### ISSUE THREAD

**Issue by Krukosz** [jspreadsheet/ce#832]
Is there any oportunity to get/set comments from/to json along with data?
I have "working spreadsheet" on my webpage and all the work is being saved to json and then to database. 
How to "connect" comment with specified cell value? My JSON is just fetched recordset from PHP's mysqli.

I don't have idea how to connect [documentation](https://bossanova.uk/jexcel/v3/examples/comments) with my case.

**Comment by pphod** [comment]
This is actually is a good point. We don't have any initialization for that yet... we will create something soon, but meanwhile, you need to iterate using the setComments to populate the cells. One suggestion is inside the onload event. I am going to leave it open for a reminder to add that in the next release.

**Comment by pphod** [comment]
table.getConfig();

**Comment by vasth** [comment]
table.getConfig();
can get data, but  how to set  config?
