### ISSUE TITLE
lazyLoading with minSpareRows is not working properly (example included)

### ISSUE THREAD

**Issue by tsh356** [jspreadsheet/ce#835]
When both lazyLoading: true and minSpareRows: 1 are set, the table doesn't load more rows on scroll. It loads the last (blank) row and stops.

See example here: 
https://jsfiddle.net/cnsuazj1/

**Comment by pphod** [comment]
I can see what do you mean, and this should be fixed. But, minSpareRows should and x blank rows at the end of the table. I guess we need to decide about that or to disabled spareRows togegher with lazyloading or pagination.

**Comment by tsh356** [comment]
It works fine if I set minDimensions to data.length + 1
https://jsfiddle.net/cnsuazj1/1/

**Comment by pphod** [comment]
In the initialization works, but spare row always creates x blank rows in the end, and this is check after each change. To create in the end of the table, it is just a matter of fixing this bug. This will be done soon... thanks for spotting that out.

**Comment by pphod** [comment]
it has been fixed.
