### ISSUE TITLE
getComments does not get comments for whole table

### ISSUE THREAD

**Issue by hchiam** [jspreadsheet/ce#836]
## Problem
I can't get all comments for the whole table. 
## Tried
I read https://bossanova.uk/jexcel/v3/docs/quick-reference
I can get comment for one cell. The docs say I can get for the whole table, but I can't seem to get it to work. I tried with no params, null, empty string, and empty array. 
## Workaround
For now the nested loop works:
```js
for (let r = 0; r < rows; r++) {
  for (let c = 0; c < cols; c++) {
    const comment = this.el.getComments([c, r])
    if (comment) {
      comments.push({c, r, comment})
    }
  }
}
```

**Comment by pphod** [comment]
I have implemented that natively. You can use

table.getComment(); // to get all comments.

**Comment by hchiam** [comment]
Thanks! I saw [your changes](https://github.com/paulhodel/jexcel/commit/1a0e91ddd96c5fa14e77e476569c971141ab0a16) and I got it working in [my project](https://github.com/hchiam/react-jexcel-redux/blob/master/src/components/Jexcel.js#L43). 

```bash
npm i jexcel # -> "jexcel": "^3.9.0" in package.json
```

```js
const comments = this.el.getComments()
```
