### ISSUE TITLE
Save as is not working in Internet Explorer

### ISSUE THREAD

**Issue by Ilayaraja-n** [jspreadsheet/ce#837]
Hi,
 Save as is not working in Internet Explorer.

In jExcel 2.1.0 found below code and it is missing in jExcel 3.x version.

// IE Compatibility
        if (window.navigator && window.navigator.msSaveOrOpenBlob) {
            window.navigator.msSaveOrOpenBlob(blob, options.csvFileName + '.csv');
        } else {
            var pom = document.createElement('a');
            var url = URL.createObjectURL(blob);
            pom.href = url;
            pom.setAttribute('download', options.csvFileName + '.csv');
            document.body.appendChild(pom);
            pom.click();
            document.body.removeChild(pom);
        }

**Comment by pphod** [comment]
It has been done.
