### ISSUE TITLE
Add event argument to custom openEditor for V3

### ISSUE THREAD

**Issue by honey-system** [jspreadsheet/ce#838]
if (obj.options.columns[x].editor) {
                // Custom editors
                obj.options.columns[x].editor.openEditor(cell, el);
}

this argument was already added in the previous version:

> Hi Guys, thanks for the suggestion.
> For the custom editor, the openEditor(cell, empty, e); will have three arguments.
> 
> cell
> empty : yes/no (means clear the current content)
> e: you can obtain more information about what triggered the editor. For example, get the Key to customize the behavior.
> 
> This change has been applied to the master repo.

_Originally posted by @paulhodel in https://github.com/paulhodel/jexcel/issues/246#issuecomment-459984995_

**Comment by pphod** [comment]
I have changed that:
cell = table cell DOM element
el = Instance of jexcel
empty = empty flag boolean
e = mouse event

openEditor(cell, el, empty, e);
