### ISSUE TITLE
initialize spreadsheet with defined number of rows/columns

### ISSUE THREAD

**Issue by tbnovaes** [jspreadsheet/ce#84]
It would be great to have an option with the number of columns and rows we want.
Also it would be great if we could have it automatically generating the number of rows/columns according to the container size. (to make it more responsive)

**Comment by pphod** [comment]
I guess this is what you are looking for.
https://jsfiddle.net/paulhodel/du585ux2/

**Comment by tbnovaes** [comment]
Oh thanks, I have missed the `minDimensions` property
