### ISSUE TITLE
Contributing to jexcel docs

### ISSUE THREAD

**Issue by leahein** [jspreadsheet/ce#840]
This isn't so much an issue as a question about contributing --

I'm an avid user of the library, and have submitted a few issues in the past as well.  I'd love to contribute to the library and I thought a good way to start would be by improving the docs, starting with React.  
Since React has [added hooks](https://reactjs.org/docs/hooks-intro.html) and is moving away from class components, I thought it might be helpful to add an implementation for that in the docs.  But -- I couldn't find the repository that backs https://bossanova.uk/jexcel/v3/docs.  Is it open-source? Would contributing [to this repo](https://github.com/paulhodel/jexcel-with-react) be helpful?

**Comment by pphod** [comment]
Thanks, I am planning to publish that soon. Meanwhile, you can send me any suggestion and I will make sure to add to the online documentation.

**Comment by natina** [comment]
Hi @leahein, I'm interested to use this library in my next project. Do you have a working example of the library using hooks? I'll be very grateful if you can share it.
Thanks!

**Comment by leahein** [comment]
Sure :)

**You can see the [working code here](https://codesandbox.io/s/jexcel-and-react-tlsw1).**

The code sandbox translates the example provided by the [jexcel docs here](https://bossanova.uk/jexcel/v4/examples/react), but it uses a functional React component with hooks, rather than a class-based one.

It leverages the [`useRef` hook](https://reactjs.org/docs/hooks-reference.html#useref) as a way to access the DOM `div` element, and the [`useEffect` hook](https://reactjs.org/docs/hooks-reference.html#useeffect) to create the jexcel table as a side-effect after the component renders.

Let me know if you have any questions.

@paulhodel Feel free to include this example using hooks in the docs [here](https://bossanova.uk/jexcel/v4/examples/react).
Happy to provide additional documentation as well.

----
For the sake of completeness, here is the code example:

```javascript
import React, { useRef, useEffect } from "react";
import ReactDOM from "react-dom";
import jexcel from "jexcel";

const App = props => {
  const jexcelRef = useRef(null);

  useEffect(() => {
    jexcel(jexcelRef.current, props.options);
  }, [props.options]);

  const addRow = () => {
    jexcelRef.current.jexcel.insertRow();
  };

  return (
    <div>
      <div ref={jexcelRef} />
      <br />
      <input type="button" onClick={addRow} value="Add new row" />
    </div>
  );
};

const options = {
  data: [[]],
  minDimensions: [10, 10]
};

const rootElement = document.getElementById("root");
ReactDOM.render(<App options={options} />, rootElement);
```

**Comment by pphod** [comment]
Thanks, I have included your example in the website. ;)

**Comment by pphod** [comment]
For documentation, examples contributions
https://github.com/paulhodel/jexcel-documentation

**Comment by javier-mora** [comment]
Hi, here is a small fix regarding the use of the library in react + typescript:
```typescript
import { useRef, useEffect } from 'react'
import jspreadsheet from 'jspreadsheet-ce';
 
import '../node_modules/jspreadsheet-ce/dist/jspreadsheet.css';

function App() {
  const jRef = useRef<HTMLDivElement>(null);
 
  useEffect(() => {
    if (jRef?.current && typeof jRef?.current === 'object' && !('jspreadsheet' in jRef.current)) {
      jspreadsheet(jRef.current, {data: [[]], minDimensions: [10, 10]});
    }
  }, []);
 
  const addRow = () => {
    if (jRef?.current && typeof jRef?.current === 'object' && 'jexcel' in jRef.current) {
      (jRef.current as jspreadsheet.JspreadsheetInstanceElement).jexcel.insertRow();
    }
  };
 
  return (
    <div>
      <div ref={jRef} />
      <br />
      <input type='button' onClick={addRow} value='Add new row' />
    </div>
  );
}

export default App
```
