### ISSUE TITLE
Issue with updating formulas value

### ISSUE THREAD

**Issue by VictorCandido** [jspreadsheet/ce#841]
When we have some formula calculating some range of rows and we delete a row in this range, the formula update correctly, but the value doesn't. We can see this in this example of the documentation:

https://jexcel.net/v4/examples/spreadsheet-formulas

Try to delete some row. The total value stays the same.

**Comment by pphod** [comment]
Thanks, I will double check in both v3, v4.

**Comment by VictorCandido** [comment]
I'm happy to help!!!

**Comment by mhstreta** [comment]
@paulhodel I found the cases in which it creates this issue.
You can test the same at url:  [https://bossanova.uk/jexcel/v4/examples/spreadsheet-formulas](https://bossanova.uk/jexcel/v4/examples/spreadsheet-formulas)

Case 1:
- Remove any number of rows containing last row with Product "highlighter" and then check formula for last cell of the last row. Earlier it was "=SUM(D1:D8)" and after removal it stays as it is. 
For ex. if you delete all rows except first row then formula should be "=SUM(D1:D1)".
           if you delete only last row then formula should be "=SUM(D1:D7)".
- Also if you try to change formula with different value then result will be shown as "#ERROR" even if cell ranges exist in the table.

Case 2:
- Remove any row except last row with Product "highlighter" and then check formula for last cell of the last row. Here it is giving correct formula "=SUM(D1:D7)" but the sum is not updated.

I hope this helps you to track down issues

**Comment by pphod** [comment]
Ok, I have checked that. That was a limitation on all current distributions CE and PRO. Now, we are testing a new version of the PRO Distribution (v7) which has that implemented, including a new features such as cross worksheet calculations, copy/paste formulas and a closer behavior with excel and google spreadsheet. This would be available only on future Pro distributions (www.jexcel.net) and will become available in the next few days. If you wish to leave your email paul@jexcel.net I can send you a notification when this is live.

**Comment by mhstreta** [comment]
@paulhodel thanks for the quick response. 

I have couple of questions:
1. Will CE distributions get the updates in the future?
2. Do you have any plans to fix formula issues in CE distributions?

**Comment by pphod** [comment]
Not all updates from Pro would be available in CE and vice verse. There are
a new version on CE on development, but that particular feature is not
included, but might be in feature releases.
