### ISSUE TITLE
Unable to enter formula on masked field

### ISSUE THREAD

**Issue by stringform** [jspreadsheet/ce#842]
Unable to type formula in cell when a field has mask on.  For example, using the demo in
https://bossanova.uk/jexcel/v3/examples/spreadsheet-formulas

![mask-formula](https://user-images.githubusercontent.com/48845308/73026031-b1ab4300-3dfe-11ea-894e-944dba4f23b7.gif)

**Comment by pphod** [comment]
This is the expected behavior. When using masking the user is limited to the format you have defined. If you wish to format the text after, but using formulas you must use updateTable, for example, to format the cell after the user enter whatever data in the cell.
