### ISSUE TITLE
Accessing New Column Names when edited by user via Context Menu

### ISSUE THREAD

**Issue by L-K-Mist** [jspreadsheet/ce#843]
Hi Paul,

I'm having a difficulty, where the user changes the column name via the Right-Click context menu, but then when they save the table, the column name stays it's old value.

How do I access the new Column name so that I can update the object that I save for the user appropriately?

Here's a lightly tweaked version of your Vue example sandbox: https://codesandbox.io/s/vue-jexcel-example-q0tux?fontsize=14&hidenavigation=1&theme=dark

Below, was hoping accessing the columns in the jExcelObj would do the trick.
![columns jexcel](https://user-images.githubusercontent.com/22072669/73133111-f5838f80-402c-11ea-8cd2-46330f61fc48.gif)

Any thoughts and guidance much appreciated. 
Once I know the answer, I'll update the codesanbox to show others how.

All the best...

**Comment by pphod** [comment]
This seems to be an old version being used. If you go to the website, which runs the most recent version this won't happen. Basically, the property title should be changed and it seems this version is not updating that for any reason.

**Comment by L-K-Mist** [comment]
Is there a version higher than 3.9.0 , because that's what I've got now in the CodeSandbox, but still the same issue.

See here: https://codesandbox.io/s/vue-jexcel-example-q0tux?fontsize=14&hidenavigation=1&theme=dark

**Comment by pphod** [comment]
Sorry, I understand now. I have fixed that. But, the correct way to get the headers is:
table.getHeaders();
