### ISSUE TITLE
Setting tabIndex for jexcel_textarea field

### ISSUE THREAD

**Issue by Ilayaraja-n** [jspreadsheet/ce#845]
Hi,
Please set the tabIndex attribute value "-1" for the "jexcel_textarea" field, so that on pressing "tab" key focus will not go to that field.
Example: obj.textarea.tabIndex="-1";

![tabIndex](https://user-images.githubusercontent.com/46338652/73262691-cfa8e700-41f4-11ea-8c7a-ba48ece5f768.png)

**Comment by pphod** [comment]
It has been done. It will be in the repo in the next few hours.
