### ISSUE TITLE
Increasing the speed of data updates in the DOM

### ISSUE THREAD

**Issue by honey-system** [jspreadsheet/ce#846]
I ran into the problem of updating a large amount of data, which in turn caused the calculation of each DOM element, especially when I used "updateTable" and "editor" together. 
The solution is very simple - detach the element from the DOM, make changes and put everything back in its place.

> let parent = this.mainTable.parentElement;
>  let removed = parent.removeChild(this.mainTable); // remove table for batch editing
> 
>  this.table.setData(dataTable); // inserting new data that causes element updates
> 
> parent.appendChild(removed); // add the list back after editing

**Comment by Rob89** [comment]
Just FYI, I submitted a PR which has been merged which might help you: #859

**Comment by pphod** [comment]
This has been included, closing...
