### ISSUE TITLE
Adjust row height

### ISSUE THREAD

**Issue by leahein** [jspreadsheet/ce#847]
This may be a feature request, based on the docs it doesn't seem this is currently supported.

Right now there's a way to adjust column width by hovering over the header and dragging the double-headed arrow.  However, there is no way to adjust the row height, such as by hovering over the row # and dragging, similar to how other spreadsheet programs offer this functionality.

If there is currently a way to do this with the existing functionality, please let me know.  Or, is there a plan to support this in the future?

**Comment by pphod** [comment]
This already exists, initiate your table with:
rowResize: true,
