### ISSUE TITLE
type: 'numeric' 4.6-3.52 = 1.0799999999999996

### ISSUE THREAD

**Issue by lunnarius** [jspreadsheet/ce#849]
hi. what can I do to get 1.08 ? (A1-A2)
=round(A1-A2,2) don't work because next time can be 0,532-0,047

**Comment by lunnarius** [comment]
it was easy - = ((A1 * 1000000)-(A2 * 1000000))/1000000 ;)

**Comment by pphod** [comment]
=ROUND(A1-A2) // Uppercase
