### ISSUE TITLE
decoupling csv data from init function

### ISSUE THREAD

**Issue by emtfe** [jspreadsheet/ce#85]
thanks for sharing your code.
i 've read your code, the question is :
is it possible to move your options.csv prepareTable from your init function?
in that way , i may init table first and feed dynamic data from csv at anytime.

**Comment by pphod** [comment]
You can use $('yourid').jexcel('setData', data); to redefined the data after the initiation. It will work with JS arrays.

**Comment by emtfe** [comment]
yes, i got it
thanks!
