### ISSUE TITLE
Bug in position of dropdown menu + autocomplete

### ISSUE THREAD

**Issue by leahein** [jspreadsheet/ce#850]
The positioning of the dropdown menu is incorrect when:

1. `autocomplete: true`
2. `tableOverflow: true`
3. dropdown is shown above, not below content.
4. user filters items in dropdown

For example:
![image](https://user-images.githubusercontent.com/15165051/73407744-17e50980-42c8-11ea-89a3-477e6566a8c5.png)

I was able to reproduce in the code sandbox [here](https://codesandbox.io/s/jexcel-and-react-cxug6).

Steps to reproduce:
1. Click into row #26
2. Begin typing "mus"

Inspecting the HTML, it seems the `style` of the `top` position of the div containing the `jdropdown-container` class is incorrect.

**Comment by pphod** [comment]
You are right. I will fix that very soon.

**Comment by leahein** [comment]
Thanks for addressing 👍 

Just tried to replicate this in the latest release (`3.9.1`) and the issue seems to persist.  Is this still a WIP?

**Comment by pphod** [comment]
There is delay, but it will be included in the v4 release next week.

**Comment by pphod** [comment]
It has been fixed.
https://codesandbox.io/s/jexcel-and-react-jsze0?file=/src/index.js

**Comment by pphod** [comment]
From jSuites v2.7.2+
