### ISSUE TITLE
It is possible setValue ignore the change Event in v3?

### ISSUE THREAD

**Issue by jpsarno** [jspreadsheet/ce#851]
Hello.

It is possible disable the change Event when use the method setValue in the V3?

I tried the lines:

$.fn.jexcel.ignoreEvents = true;
$.fn.jexcel.ignoreHistory = true;
$.fn.jexcel.ignoreEvents = false;
$.fn.jexcel.ignoreHistory = false;

But it dit not work.

Thank you very much.

Regards,
João

**Comment by pphod** [comment]
Yes, same logic:

yourtableinstance.ignoreEvents = true
