### ISSUE TITLE
Unable to set 1st column (id) width

### ISSUE THREAD

**Issue by Shnoulle** [jspreadsheet/ce#852]
Hi, and thank you.

I try to use jexcel with 
` table.jexcel{width:100%;table-layout:fixed}`

I set some width to forced value and keep other to default (50)

For example:
````
columns:[
    { title:'id', width:"5em" },
    { title:'Price' },
    { title:'Model'}
]
````
![Capture d’écran du 2020-01-31 16-04-39](https://user-images.githubusercontent.com/1439428/73549733-6ff44b00-4443-11ea-8953-8bb36d0146b1.png)

Then i try with `$(instance).find('colgroup col').first().width("6em").attr("width","6em");` in onload event
but no success : html seems updated, but table are not resetted (table-layout … )

Trying different combination … and checking code to see `options.defaultColWidth` are not for 1st column, i see only two solutions : 

Update
https://github.com/paulhodel/jexcel/blob/9a302f6758dbb80d7dc2cd0b4fdea3b2e29e47cc/dist/jexcel.js#L457
to
`tempCol.setAttribute('width', '5em');`

And the second solution
````
columns:[
    { title:'id', width:"50" },
    { title:'Price' },
    { title:'Model'}
]
````
with `options.defaultColWidth` to '*'.

I think an option to set only the 1st columns width can be really great.

**Comment by pphod** [comment]
Sorry,

I am not sure if I understood your problem. Would you like to change the index? You can change the default in the initialization.

columns: [{ width:'100px'}, {width:'50px'}],
defaultColumnWidth:'200px',

For example.

**Comment by Shnoulle** [comment]
The 1st column with line number (1,2,3 …) **didn't** use `defaultColumnWidth`

It's fixed here : https://github.com/paulhodel/jexcel/blob/9a302f6758dbb80d7dc2cd0b4fdea3b2e29e47cc/dist/jexcel.js#L457

Then even with defaultColumnWidth to 200px , the 1st column are at 50.

With : 
````
var options = {
    minDimensions:[2,2],
    defaultColumnWidth:"200",
    columns:[
        { title:'id', width:"100" },
        { title:'Price', width:"100" },
    ]
}
````
According to `defaultColumnWidth` the 1st column must be 2 times bigger then the 2 other : rtight ?

But it's false :  see this [jsbin](https://jsbin.com/kudeliheda/1/edit?html,js,output)
