### ISSUE TITLE
set table width/height to 100% of DIV

### ISSUE THREAD

**Issue by Scnck** [jspreadsheet/ce#853]
is it possible to set table width/height to 100% of DIV, I want it to auto resize

**Comment by pphod** [comment]
you can set the fullscreen mode.

fullscreen:true, during initialization.

Regards,

**Comment by Scnck** [comment]
been when I resize the DIV the table doesn't.

**Comment by pphod** [comment]
No, the table does not change based on his parent window. But, you can create a table with more columns them your windows.
minDimension:[20,20]

For example.
