### ISSUE TITLE
Empty array with getData()

### ISSUE THREAD

**Issue by ghost** [jspreadsheet/ce#854]
I am use the Jexcel 3.8.2 and Jsuite v2.7.
I have a jexcel object that it receive  JSON data:

` jexcel(document.getElementById('spreadsheet4'), {
data: result, loadingSpin: true, tableOverflow: true, defaultColWidth: "100px", tableWidth: "100%", tableHeight: "480px", minDimensions: [15, 15] });`

and try to get the data after I modified some cells:

`var data = jexcel(document.getElementById("spreadsheet4")).getData(false);
                console.log(data);`

but the array is empty, I don't know if I do something wrong or I don't declare correctly the object.

![image](https://user-images.githubusercontent.com/58598851/73782601-fb2d5380-4757-11ea-8841-39cab122b529.png)

**Comment by pphod** [comment]
```
var table = jexcel(document.getElementById('spreadsheet4'), {
  data: result,
  loadingSpin: true,
  tableOverflow: true,
  defaultColWidth: "100px",
  tableWidth: "800px",
  tableHeight: "480px",
  minDimensions: [15, 15]
});

var data = table.getData();
console.log(data);
```
