### ISSUE TITLE
Store old value during onbeforechange event

### ISSUE THREAD

**Issue by Krukosz** [jspreadsheet/ce#856]
I have assigned function to this event which prompts user for comment when the cell is changed.

I would like to prompt only when the cell has any value before. For now, it prompts in any case.

How to store the old value? Console.log from code below always returns <empty string>

```
`    var requireComment = function(instance, cell, x, y, value) {
        obj = jExcelObj;
        console.log(cell.firstChild.innerText);
        console.log(cell.firstChild);
        if (cell.innerText) {
            
            var title = (!cell.getAttribute('title')) ? "" : cell.getAttribute('title');
            obj.setComments([ x, y ], prompt("Podaj powód edycji", title));
        }
    }`
```

**Comment by pphod** [comment]
Try to add an oldValue and create a conditional.

`    var requireComment = function(instance, cell, x, y, value, oldValue) {
        obj = jExcelObj;
        console.log(cell.firstChild.innerText);
        console.log(cell.firstChild);
        if (cell.innerText) {
            
            var title = (!cell.getAttribute('title')) ? "" : cell.getAttribute('title');
            obj.setComments([ x, y ], prompt("Podaj powód edycji", title));
        }
    }`

**Comment by Krukosz** [comment]
oldValue is always `undefined`

**Comment by paulhodel** [comment]
Sorry, I miss understood your question. This has been fixed, but there is no event for change comments. But, we will reopen this to keep track for that in future releases. The workaround now is to create a custom contextMenu.

**Comment by pphod** [comment]
```
onbeforechange: function(el, cell, x, y, value) {
    var oldValue = cell.getAttribute('title');
    // do your stuff
}


```

**Comment by Krukosz** [comment]
I want to store old **cell** value, not old **comment** value
I checked cell.innerText, cell.value etc.- it has **always** the new cell value, even if I use onbeforechange event.

Is there any appropiate jExcel event for that or I have to write it on my own?

**Comment by pphod** [comment]
Use onchange or onafterchanges.

**Comment by uttara-appu** [comment]
Hi, I have a scenario wherein a calendar column cannot have null value. 
So, when I delete the cell contents by using "Delete" key, I want to restore the old value after prompting an Alert. 
However, I don't want to make it readOnly, because the value should be editable.
My question is, how do I store the old value somewhere, so that I can set it back.

**Comment by pphod** [comment]
You can do onbeforechange to intercept the change request, if you are not happy with the value, you can simply ignore the change. The worst-case scenario is to call undo on the onchange (not recommended).

**Comment by uttara-appu** [comment]
By Ignore, did you mean the below? This didn't work for me.

onbeforechange: function(el, cell, x, y, value) {
          if (x == 6 && value) {
                 if(value==null || value==''){
	          alert('This Date cannot be null')
	          el.jexcel.ignoreEvents = true;
          }
}

**Comment by pphod** [comment]
No, remove el.jexcel.ignoreEvents, and  return false;

**Comment by uttara-appu** [comment]
The thing is, it's not going to the "**if(x == 6 && value)**" block when the contents are deleted.
However I tried the below, but when I give "**return false;**" it populates the word "false" in the cell.
Here's my change:
```
onbeforechange: function(el, cell, x, y, value) {
dateLength=value.length;
if(x==6 && dateLength==0){
        alert('Date cannot be null');
	return false;
}
```

![image](https://user-images.githubusercontent.com/76616772/103244970-a3599580-4984-11eb-896e-b75dfda48161.png)
