### ISSUE TITLE
How to add a custom formula to a vue instance

### ISSUE THREAD

**Issue by spacewaffle** [jspreadsheet/ce#857]
I see the basic documentation for adding formulas, but attempting to use it in a vue instance hasn't given me any luck. Where do you define the formula in a vue app?

Also I noticed the custom formula example does not have parseFormulas as an option. Is this because parseFormulas is true by default?

**Comment by pphod** [comment]
https://bossanova.uk/jexcel/v3/examples/spreadsheet-formulas
Bear in mind, the formula must be in the global scope to be available in the parsing. Yes, parseFormulas is the default true for all spreadsheets.
