### ISSUE TITLE
Unable to initialize row height when loading a table

### ISSUE THREAD

**Issue by dana-crypto** [jspreadsheet/ce#858]
On the https://bossanova.uk/jexcel/v3/docs/getting-started page, there is an example of how to set row heights when initializing a table. However, the existing solution appears to be an associative array with incorrect syntax and it creates an error on loading the page. I have tried correcting the syntax but have been unable to get this feature to work. This is the instruction and example from the page:

"The inital row height can be defined in the height property include in the rows directive.

<script>
jexcel(document.getElementById('myTable'), {
    data:data,
    rows:[ 3: { height:500 }],
});
</script>"

**Comment by pphod** [comment]
Sorry, it seems there is an error in the documentation. This would do the trick, I will fix the documentation.

    var options = {
        data: [[1,2,3,4,5,6,7,8,9,10]],
        minDimensions:[10,10],
        rows:{ 2:{height:'100px'} },
    }

**Comment by dana-crypto** [comment]
Perfect, thank you!
