### ISSUE TITLE
how to use updateSettings function? 

### ISSUE THREAD

**Issue by emtfe** [jspreadsheet/ce#86]
Hi, Paul
i just test your example about using formula and format numeric type functions.
i want to Enter a Formula in col11 like "=D1 * C1"   and calc "col5 * col6 = col11", at same time,
to format col6 and col11 .
i find some fails : 
1,  when i load remote csv data,  i "must ?" use updateSettings function in  onload callback.
2,  when i format  col5  and col11, "=D1 * C1" not working.
`var loaded = function(instance) {
  $("#my").jexcel('updateSettings', {id: 'innergrid',
      cells: function (cell, col, row) {
          // 
          if(col == 5 || col == 11 ) {
             // 
            val = numeral($(cell).text()).format('0,0.00');
            $(cell).html('' + val);
            $(cell).css('color', '#333333');
           }
           // 
           if (col == 6 ) {
             $(cell).css('color', '#1c84c6');
             $(cell).css('font-weight', 'bold');
           }

      }
  }); 
} `
3, when i comment out below two line, "=D1 * C1" is working now,
but the rendered td's value is ugly.
 val = numeral($(cell).text()).format('0,0.00');
 $(cell).html('' + val);
4, how do i use updateSettings function properly?

**Comment by pphod** [comment]
I really like to use numeraljs for formatting. I guess this two example together can help you.

https://bossanova.uk/jexcel/examples/currency-and-masking-numbers
https://jsfiddle.net/paulhodel/03d5rhzo/

If not, please create a jsfiddle with your example and share with us. I would be happy to support you with an contextual example.

Regards,

**Comment by emtfe** [comment]
Hi paul
sorry for late ,
 i forked your https://jsfiddle.net/fatticat/3xbhvLzp/10/ 
please help
