### ISSUE TITLE
Row height doesn't visually adjust properly

### ISSUE THREAD

**Issue by dana-crypto** [jspreadsheet/ce#861]
In your documentation, you have laid out the following method for setting the row height on table initialization:

rows:{ 2:{height:'100px'} },

I used this method and it displays properly on load. However, when I try to adjust the row height manually, the row heights that were set on initialization do not appear to adjust. A screen refresh shows the row height did in fact change though. 

Upon further inspection, I discovered that the row heights on initialization are set in the style attribute, but the row heights that are set through on-screen manipulation of a jQuery table are set in the height attribute. So when I try to change the height of a row that was set in the table initialization, I end up with rows that have one height defined under the style attribute, and another under the height attribute.

**Comment by pphod** [comment]
It has been fixed. It will be in the repository and NPM in the next few hours.

**Comment by dana-crypto** [comment]
It works! Thank you.
