### ISSUE TITLE
How do I close the default cell editor programmatically?

### ISSUE THREAD

**Issue by AnaOrtega1** [jspreadsheet/ce#862]
I am adding an image inside the column header, next to the headers text, that brings up an angular material dialog. The problem I have is that if a cell is being edited when the dialog shows up and I start typing, the texts keeps being entered in the edited cell. I have tried setting the focus in the dialog input box, but it does not help. How do I close the default cell editor programmatically?

I tried but I get an error: "Cannot read property 'value' of undefined "when calling closeEditor

   var cellId = jexcel.getColumnNameFromId([selectedCell[1], selectedCell[0]]);
   var cell = jexcel.current.records[selectedCell[1]][selectedCell[0]];
   participantsSheet.closeEditor(cell, true);

Thank you.

**Comment by AnaOrtega1** [comment]
I am calling resetSelection() and it is working now.

**Comment by pphod** [comment]
Nice!

**Comment by ohabash** [comment]
How do you control when `closeEditor` fires?

**Comment by hodeware** [comment]
If you have the instance:
instance.closeEditor();

If you don't have:
jspreadsheet.current.closeEditor();

**Comment by ohabash** [comment]
I have it and can call it when i want. But currently clicking anywhere while a custom editor modal (like color picker) will fire closeEditor() but i need to be able to decide when it fires.

**Comment by hodeware** [comment]
You can create a custom editor. Examples here:
https://jspreadsheet.com/v8/docs/editors

For CE it is also possible, but the structure is slightly differnet.
