### ISSUE TITLE
Getting coordinates of selection to update values

### ISSUE THREAD

**Issue by alejandroeclair** [jspreadsheet/ce#863]
Hi there,

I'd like to be able to update the data of what I have selected on my sheet programatically when I press a button.

A bit more background:
I upload an excel file and I want to select a set of cells and then I press a button on my web that should process the data and then update the cells with the results. I've gotten to the point where I get the data and transform it, but I'm unable to update it back in it's same place, because I'm not able to find how to get their coordinates.

I have been able to do the `getJson(true)` method and that gives me their column address, but not their row.

I know that with a simple "A9" or "B1", I could split the letter from the number and then know that A is 0 and B is 1, but I wanna know if there's a simpler way, because if my document has over the letter Z, like AA or AB, that's harder to convert to number to place in array.

Thank you!

**Comment by pphod** [comment]
You have two native methods to deal with names/coords.

jexcel.getColumnNameFromId(x, y);
or
jexcel.getIdFromColumnName('A1', true); // true means return in a array format.

**Comment by alejandroeclair** [comment]
Hi @paulhodel ,

Unfortunately this isn't exactly it. 
getColumnNameFromId requires x and y, but I don't have x or y because I have a selection made, so what goes in XY?

The same for getIdFromColumnName, I don't know that my selection is in A1 or B1.

Here is the data I get from the `getJson(true)` method:
<img width="248" alt="Screen Shot 2020-02-09 at 11 38 09 pm" src="https://user-images.githubusercontent.com/52657230/74102202-59619880-4b95-11ea-9096-6dd6b4ccb0ba.png">

and this is my selection
<img width="203" alt="Screen Shot 2020-02-09 at 11 42 19 pm" src="https://user-images.githubusercontent.com/52657230/74102250-dc82ee80-4b95-11ea-8acc-b19398732503.png">


How would I go about updating those values and putting them back in their place?

**Comment by pphod** [comment]
Sorry, your coordinates you can get by using:
var coords = table.selectedCell;
x1 = coords[0];
y1 = coords[1];
x2 = coords[2];
y2 = coords[3];

One other option is to use:

table.paste(x, y, data);

Where x, y is the initial location, and data should be in CSV format. Rows split by \r\n and Columns \t

To get x, y  you have that:
x = table.selectedCell[0];
y = table.selectedCell[1];
