### ISSUE TITLE
Cancelling the Edit Comments action deletes the cell comments

### ISSUE THREAD

**Issue by dana-crypto** [jspreadsheet/ce#867]
When you go to edit the comments on a cell and then change your mind, clicking 'Cancel' clears the comments for that cell.  I believe clicking 'Cancel' should leave the comments unchanged. 

As far as I can tell, this is because the Edit Comments function shares code with Add Comments. In the case of Add Comments, the current behaviour would be the correct action for the Cancel button.

**Comment by pphod** [comment]
It has been done.

**Comment by dana-crypto** [comment]
Thank you!

**Comment by dana-crypto** [comment]
I'm not seeing the change in version 3.9.1. Is it yet to be released?

**Comment by pphod** [comment]
Yes, as the master on github and on NPM.
