### ISSUE TITLE
Extend editor to handle cell creation

### ISSUE THREAD

**Issue by Rob89** [jspreadsheet/ce#869]
I'm using custom editors heavily and I'd like easier control over the initial creation of the cell. At the moment, I'm using the updateTable option to customise the cell creation and then removing the updateTable function afterwards. It would be nice if the editor had an additional function: `initializeCell(el, cell, x, y, value)`  which could be called in `createCell` after setting the innerHTML to the value.

In case it's helpful: my use case is that I have a column that can have a few different types of data in it. E.g. a checkbox, a date etc. I've got this working using a custom editor which locates a specific editor for the cell and calls the appropriate openEditor, closeEditor, setValue etc. so this is just an improvement rather than a need.

I'd be happy to submit a PR for this - I wanted to ask your opinion on the idea first.

**Comment by pphod** [comment]
Yes, you are absolutely right. I am going to add that in the next release.

**Comment by krosoftware** [comment]
> Yes, you are absolutely right. I am going to add that in the next release.

Hello @paulhodel  can you also take a look here: https://github.com/paulhodel/jexcel/issues/652? You have examples there and you promised you will do that :)
Thanks!

**Comment by deftdawg** [comment]
I'm struggling with a way to have the default date on a calendar input type fall within its valid range (legal employment today - 13 years to today - 65 years) when its first opened.    I tried messing with column options for value and onopen to no avail.

I'm wondering if initializeCell is something you were thinking of for when the user first opens an editor on the cell or if it's something you do when when the sheet first renders (thinking about it UpdateTable makes me think it's the later).

**Comment by pphod** [comment]
That has been included on the Pro distribution and should go to the CE eventually.
https://jexcel.net
