### ISSUE TITLE
data object not updated

### ISSUE THREAD

**Issue by autodilo** [jspreadsheet/ce#872]
Hello, 
In version v3, oninsert or ondelete row in the table the associated data1 (data:data1) not changed. This happens also when updating (onchange) any cell. Maybe this is what was intended. Of course, we can update using getData. In version 2, it was updated automaticaly.

**Comment by pphod** [comment]
You will need to use getData. In v3 the data is much more flexible, accepting JSON format, etc. So you lose the reference on the processes of parsing the data.
