### ISSUE TITLE
How do you stop the Tab Key from creating new columns?

### ISSUE THREAD

**Issue by cwwms2** [jspreadsheet/ce#876]
How do you stop the Tab Key from creating new columns? Also, how do you make the cursor go to the first cell of the next row when you tab on last column of the previous row?

**Comment by nsch23** [comment]
Just take a look at the initial settings. Should be something like allowManualColumnInsert: false. -> google

**Comment by RaulBSantos** [comment]
As @nsch23 said, set the configuration **allowInsertColumn** to false

Reference: https://bossanova.uk/jexcel/v3/docs/quick-reference

**Comment by paulhodel** [comment]
There is a second option:
allowManualInsertColumn:true
