### ISSUE TITLE
How to disable paste from Excel

### ISSUE THREAD

**Issue by karapapas** [jspreadsheet/ce#877]
In the options I have both allowInsertRow and allowInsertColumn false, still I am able to paste from Excel directly into the jExcel table. I have also tried to use paste:false in the options, but with no luck. The version I am using is v3.8.2

**Comment by pphod** [comment]
Do you want the user to edit the columns but not use paste, is that correct?

**Comment by karapapas** [comment]
Thank you for your response!

Exactly, I would like the user to be able to edit the non-readyOnly columns but not be able to paste on them, for example in case they have a column copied in the clipboard from an excel. 

Is this possible with the standard options of jExcel or should I try to create an event handler?

**Comment by pphod** [comment]
you initiate your table with:

onbeforepaste: function() { return false; }

Regards,
