### ISSUE TITLE
Write documentation for a beginner

### ISSUE THREAD

**Issue by marco-brandizi** [jspreadsheet/ce#879]
I'm very interested in using jexcel. I know HTML/Javascript/webdev fairly well, but I know little about npm. So, I cannot understand how exactly I should use this package in my app.

I've tried `npm install jexcel`, and then what? Are there downloaded files I should point to? In which path? I've also tried to download the .zip mentioned in the README. However, I see this in the instructions:

```javascript
<script src="https://bossanova.uk/jexcel/v3/jexcel.js"></script>
<script src="https://bossanova.uk/jsuites/v2/jsuites.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jsuites/v2/jsuites.css" type="text/css" />
<link rel="stylesheet" href="https://bossanova.uk/jexcel/v3/jexcel.css" type="text/css" />
``` 

But `jsuites/*` aren't anywhere in the .zip, and I guess it wouldn't be good to link from bossanova.uk. Please, could you clarify this further in the README? Thanks in advance.

**Comment by pphod** [comment]
If you copy this code in FULL, save as index.html and open in your browser you will be able to write your code.

```
<html>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<script src="https://bossanova.uk/jexcel/v3/jexcel.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jexcel/v3/jexcel.css" type="text/css" />
<script src="https://bossanova.uk/jsuites/v2/jsuites.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jsuites/v2/jsuites.css" type="text/css" />

<div id="spreadsheet"></div>

<input type="button" value="Add new row" onclick="$('#spreadsheet').jexcel('insertRow')" />

<script>
var options = {
    minDimensions:[10,10],
    tableOverflow:true,
}

$('#spreadsheet').jexcel(options); 
</script>
</html>
```

**Comment by pphod** [comment]
Please refer to the website for more examples.

**Comment by marco-brandizi** [comment]
@paulhodel, thanks, but sorry, I still don't get it: is it fine to use links from bossanova.uk? If yes, what's the npm installation for? Can't I use it locally? How? Do I just need to download `jexcel.{js,css}` and `jsuites.{js,css}`? And what's the latter? These are the kind of questions that would be worth to answer in the README.

**Comment by pphod** [comment]
Marco,

You can use the links from bossanova or download the files and use locally
or use npm. All different options.

Jsuites is a dependency to create the components such as dropdown, etc
