### ISSUE TITLE
still the same question...

### ISSUE THREAD

**Issue by emtfe** [jspreadsheet/ce#88]
#87 
your jsfiddle  code:
![image](https://user-images.githubusercontent.com/8743877/35134432-479f3d02-fd11-11e7-82cc-ed8a93b5692a.png)

 i think you want me to getValue and format value first and setValue back.
but when use your code and change col 1 and the col 3 still return unformatted value like below:
![image](https://user-images.githubusercontent.com/8743877/35134625-7c69d5b4-fd12-11e7-8bf7-063466103d61.png)
help please...
i 've read your code and you may push a value for calculating into  your records array:
                        records.push({
                            cell: $(cell),
                            newValue: row[i],
                            oldValue: $(this).jexcel('getValue', $(cell)),
                            **calcValue: $(this).jexcel('getValue', $(cell)),**
                        });
......

**Comment by pphod** [comment]
Please, Please try to take a look again:
https://jsfiddle.net/paulhodel/fmhk668d/

**Comment by emtfe** [comment]
thanks!
you shed light on it.
