### ISSUE TITLE
About the date picker. Is it possible to make the week start on Monday?

### ISSUE THREAD

**Issue by agradecido** [jspreadsheet/ce#884]
About the date picker. Is it possible to make the week start on Monday or any option to localize the calendar?

Thanks!

**Comment by pphod** [comment]
Unfortunately not this version. In regards to localize, do you mean translations?

**Comment by agradecido** [comment]
Thanks for the reply.

Specifically I need to make the week start on Monday instead of Sunday, this is the convention in Spain (and other countries).

In any case, thanks for the good work.

**Comment by pphod** [comment]
I will keep that to be included in the next release

**Comment by jimmywarting** [comment]
Would be nice with a native picker such as `<input type="date" placeholder="yyyy-mm-dd">` that is all localized to the users own preferences

also for time and datetime-local

**Comment by pphod** [comment]
You can customize columns and will be very easy to do that.

**Comment by pphod** [comment]
The last example on this page shows how to custimize a column on v3+

https://bossanova.uk/jexcel/v3/examples/column-types

**Comment by pphod** [comment]
It has been done. (5th example in this page)
https://bossanova.uk/jsuites/javascript-calendar

initialization with
{
    startingDay: 1, // 0 for Sunday... 6 for Saturday.
}

**Comment by agradecido** [comment]
Thanks a lot and congratulations for the work you do.
