### ISSUE TITLE
How to create a multi sheet？

### ISSUE THREAD

**Issue by godpit** [jspreadsheet/ce#885]
How to create a multi sheet？

**Comment by pphod** [comment]
Do you mean with tabs? This will be available in the next versions.

**Comment by godpit** [comment]
Now, I tested within the v4 version.  jexcel.createTabs(document.getElementById('spreadsheet4'), optionsArray);
what is it about the 'optionsArray'?

**Comment by godpit** [comment]
This is a bug within the method of 'jexcel.createTabs',  such as 
<img width="545" alt="WX20200228-144200@2x" src="https://user-images.githubusercontent.com/34534331/75516981-8f799600-5a38-11ea-94eb-67d424404a2e.png">

Only, the first sheet is ok.
