### ISSUE TITLE
Jexcel not rendering in properly

### ISSUE THREAD

**Issue by subu1980** [jspreadsheet/ce#887]
Hi,
I am using  https://cdnjs.cloudflare.com/ajax/libs/jexcel/2.1.0/js/jquery.jexcel.js jsfile along with following files:
https://cdnjs.cloudflare.com/ajax/libs/jexcel/2.1.0/js/jquery.jdropdown.js
https://cdnjs.cloudflare.com/ajax/libs/jexcel/2.1.0/css/jquery.jexcel.min.css
https://cdnjs.cloudflare.com/ajax/libs/jexcel/2.1.0/css/jquery.jdropdown.min.css

In crome it is working fine and rendering properly but in IE it not rendering properly

![image](https://user-images.githubusercontent.com/61492266/75321518-f19a9580-5896-11ea-9fc0-df88d2c68e3c.png)

but in IE it rendering like below:

![image](https://user-images.githubusercontent.com/61492266/75321672-42aa8980-5897-11ea-9196-51f67f2cd774.png)

can any one help me out to resolve this issue for IE

**Comment by pphod** [comment]
Please upgrade to v3

**Comment by subu1980** [comment]
can you provide me the CDN path for V3, please

**Comment by subu1980** [comment]
Hi,
I used V3.0.1 code from code Section but it is showing  script1002 syntax error

**Comment by pphod** [comment]
Please use the most recent one.
https://cdnjs.com/libraries/jexcel

Examples:
https://bossanova.uk/jexcel/v3

**Comment by subu1980** [comment]
Hi,
I used most recent one which is not working  in chrome as well as IE. Please help me out to solve the issue of IE.

**Comment by subu1980** [comment]
Any Help

**Comment by pphod** [comment]
I am afraid you have something on your side that should be fixed. Please add me on your skype: paul.hodel

**Comment by subu1980** [comment]
I can'nt talk to your skype account due to business restriction. I am attaching the error message what i am getting by using 3.9.1 jexcel.js and jexcel.css with jsuites.js of 2.1.0 and jsuites.css. of 2.1.0
![image](https://user-images.githubusercontent.com/61492266/76068475-3caf5980-5fb7-11ea-8353-f1f817c8ab94.png)
