### ISSUE TITLE
when i set interval function post with ajax, table empty 

### ISSUE THREAD

**Issue by Aliansyah5** [jspreadsheet/ce#889]
when i send post with ajax to laraval, my tabel has empty

here is my code
![code](https://user-images.githubusercontent.com/13564607/75431107-ee7ad480-597e-11ea-8cf5-bf9b9314761c.jpg)

and mytabel empty when update with laravel but it saved to server
![table](https://user-images.githubusercontent.com/13564607/75431034-d6a35080-597e-11ea-8668-b984c8c177fd.jpg)

**Comment by pphod** [comment]
Sorry, your problem does not seem on jexcel and there is not enough information to help. I would suggest you create a jsfiddle...
