### ISSUE TITLE
Add option to give a custom name to the CSV

### ISSUE THREAD

**Issue by tbnovaes** [jspreadsheet/ce#89]
It would be nice to be able to give a custom name to the CSV file, instead of having it downloaded as jexcelTable.csv

**Comment by thebugbear** [comment]
yes, please - or at least point us to the easiest way to make the change ourselves

**Comment by pphod** [comment]
It has been done. You can declare csvFileName:'filename' in the innitialization to define the filename. Please, download the most recent version in the master repo.

**Comment by thebugbear** [comment]
Excellent - thank you!

**Comment by tbnovaes** [comment]
Thank you @paulhodel

**Comment by tbnovaes** [comment]
@paulhodel `npm install jexcel@1.3.4` returns me the 1.3.3 version of the package. Can you double check if you updated the package on npm?
