### ISSUE TITLE
Shortcut keys to get the focus into the jExcel grid

### ISSUE THREAD

**Issue by Ilayaraja-n** [jspreadsheet/ce#891]
Please provide shortcut keys to get the focus into the jExcel grid. Now mouse click is mandatory to get the focus into the jExcel grid. It would be better if the shortcut key is customizable as part of jExcel options.
This is needed as part of VPAT(i.e. Voluntary Product Accessibility Template) compliance.

**Comment by pphod** [comment]
It has been done. The tab key put focus on the first cell.

Available on v4.1.1+

**Comment by Ilayaraja-n** [comment]
Thank you very much Paul. Once the focus reaches to the last cell, focus is not moving out of the jExcel grid. 
Once the focus reaches to last cell on pressing the tab key please move the focus out of the jExcel grid.
