### ISSUE TITLE
Bug: dropdown with filter working as expected, but value doesn't show

### ISSUE THREAD

**Issue by jmodiano** [jspreadsheet/ce#892]
I think this might be a bug as I can't see what else would be causing this behavior. I've set up a few dropdowns with a filter, and they seem to be working fine. 

The one in the first column behaves exactly as expected. The one in the second column does too except for the fact that when you select a value it disappears. When you click on the dropdown again you can see that the correct thing is selected, even if the cell remains blank. 

What makes me pretty sure that this is a bug is that if I then copy and paste the contents of the table into Excel, the correct values show up. So basically it looks like everything is working fine, except for some reason the value is staying hidden after it's been selected. 

I've tried updating the CSS but nothing seems to work, and anyway I'm not sure why this would only happen to one cell.

**Comment by pphod** [comment]
This is probably related to the return of your filter function. It must contain the array the populates the dropdown. I am happy to look on your online example to help a bit better.

**Comment by kritisoft** [comment]
I am also facing the same issue ? any update ? on this
