### ISSUE TITLE
How do you get the coordinates of a row that matched a search?

### ISSUE THREAD

**Issue by cwwms2** [jspreadsheet/ce#893]
If you perform a search and bring back a row, how do you go about getting the "data-x" value of that row?

**Comment by GBonnaire** [comment]
You have : 
`MyTable.results[0]; // return first row (data-y) of table;`

**Comment by pphod** [comment]
> You have :
> `MyTable.results[0]; // return first row X of table;`


Guilaume, this is actually the "data-y", we don't have the "data-x" in this version.

**Comment by GBonnaire** [comment]
Oups 😊OK, i mixed x and y 

but with selector you can get row (y) and parse col (x) of row with function search (if return >0 is OK else NOK)
