### ISSUE TITLE
Conflict on using masks on number fields that are used in formulas.

### ISSUE THREAD

**Issue by karapapas** [jspreadsheet/ce#895]
Using onbeforechange and onchange, the values that I am getting instead of being "unmasked" it's masked which complicates things since I have to manually convert it back to numeric.

I have tried to use the unmask function but I have no idea how to do it. I guess that this might not be possible since we set the mask on the column in the jexcel options, whereas the unmask function is applied on the input field that is masked. 

So the question is, what is the proposed way of masking and unmasking fields that take part in formula calculations?

**Comment by karapapas** [comment]
@paulhodel If you need more details to understand or maybe reproduce this please inform me. Thank you.

**Comment by pphod** [comment]
This is included on Pro v5, for the CE or previous versions you need to use some external library for masking since the mask will work in the editor level.

This examples works on v3 & v4 using numeraljs for masking.
www.bossanova.uk/jexcel/v4/examples/table-scripting

**Comment by karapapas** [comment]
Ok let's talk about the solution based on numeraljs for v4.
It does work exactly as expected, using the code in the link you provided, but there is a drawback.
The function called on updateTable runs for every cell in the table and if you are setting the value of a cell during the onchange then the whole thing falls into a (almost) infinite loop.

So is there a way to avoid this? Maybe by changing the label instead of the value of a cell or by detecting whether the change was initialized by a user or programmatically in order to stop the cascade of events?

**Comment by paulhodel** [comment]
A possible solution , create a flag where you can apply mask only on edition after the edition. Is that work for you?

**Comment by pphod** [comment]
How about remove the mask property and apply the mask onchange?
1) Remove the property mask from the editor on initialiation.
2) Add a mask on the onchange event

**Comment by pphod** [comment]
You should avoid execute setValue inside updateTable. If you need change the table values you have other options. Can you create a jsfiddle of you example with your updateTable (simplified version). I can create a solution for you.
