### ISSUE TITLE
jexcel select multiple cell not working in mobile or ipad

### ISSUE THREAD

**Issue by prakash50166** [jspreadsheet/ce#898]
when i do select cell it's selected but i can't select multiple cell in mobile or ipad then i need select a1 cell to a4 cell in mobile or ipad totally i want 4 cell selected so please could tell what i do and please help me fix this issues in mobile

**Comment by GBonnaire** [comment]
When paul test and merge PR, you can select multiple cell on mobile and tablet

https://github.com/paulhodel/jexcel/pull/924
