### ISSUE TITLE
Break line inside cells

### ISSUE THREAD

**Issue by rokai3009** [jspreadsheet/ce#9]
Hi paul,

I want to have some break line inside cells when press ctrl+enter or shift+enter like excel or openoffice
Can we do this?

Regards

**Comment by pphod** [comment]
Unfortunately, this feature it is not supported at this moment. I will add that on the roadmap for future versions.

**Comment by adamdehaven** [comment]
@paulhodel Any update on this? I have a use-case where I need to insert a new line in a `wordWrap: true` cell.  I've tried overriding the keyup behavior with no luck.
