### ISSUE TITLE
Add option to make the entire spreadsheet read only

### ISSUE THREAD

**Issue by tbnovaes** [jspreadsheet/ce#90]
Currently we can make a column readonly, but it would be great if we could have a global option to make all columns read only instead.

**Comment by FJaque** [comment]
It works for all the table
`$('#table').jexcel('updateSettings', {
                cells: function (cell, col, row) {
                    $(cell).addClass('readonly');
                }
            });`

**Comment by pphod** [comment]
Please use the editable:false as below:

```
<script>
data = [
    ['Mazda', 2001, 2000],
    ['Pegeout', 2010, 5000],
    ['Honda Fit', 2009, 3000],
    ['Honda CRV', 2010, 6000],
];

$('#my-spreadsheet').jexcel({
    data:data,
    editable:false,
    colHeaders: ['Model', 'Price', 'Price' ],
    colWidths: [ 300, 80, 100 ]
});
</script>
```

**Comment by tbnovaes** [comment]
Thank you @paulhodel it did what I wanted! Is there a way to use `editable : false` for the entire table, and override one column to accept edition? I could not find it in the documentation, I will start looking at the source code to see if I can find more hidden features. Btw congratulations I'm enjoying a lot to use the jExcel.
