### ISSUE TITLE
Performance decrease dramatically when column up to 1000

### ISSUE THREAD

**Issue by yufawang** [jspreadsheet/ce#900]
we have done some extension works based on community version v3.9.1；But we found that when the column reach up to 1000，the performance become worse dramatically when we do operations like insert a column or row ， or any other operations involved with multiple cells。

On the other hand， we found tables with much rows than columns performs better than too much columns。

Please give us some tips to enhance the performance when table has a lots of columns ，let say more than 1000 columns and 300 rows data size with pure text contents, and no formulas...
thanks for your reply.  :)

**Comment by pphod** [comment]
Hi, you should enable lazyLoading: true or pagination: 10

Best regards,

**Comment by yufawang** [comment]
> 
> 
> Hi, you should enable lazyLoading: true or pagination: 10
> 
> Best regards,

actually we have already used the lazyLoading feature，but can not use pagination in our scenario.
What a pity~；
good luck and stay safe from coronavirus；
