### ISSUE TITLE
UpdateTable event - Doubts

### ISSUE THREAD

**Issue by jpsarno** [jspreadsheet/ce#901]
Hello Paul.

I saw the issue 759 and my problem is similar. I used the event UpdateTable do change the row colors. Because the event have the paramethers instance, cell, col, row, val, label and cellName.

But when a unique cell value is changed, the event is triggered and all logic is executed again. 

My doubt is, exists a event with the paramether row or a event executed after the load? The event onload has just one paramether.

Or a way to disable the updateTable on cell change value.

Thank you very much again.

**Comment by pphod** [comment]
No, updateTable runs every cell updates. For the purposes of odd even cell colors, you can use CSS only.

**Comment by pphod** [comment]
.jexcel tbody tr:nth-child(even){
  background-color: #EEE9F1 !important;
}
