### ISSUE TITLE
missing type ?  jexcels {any}

### ISSUE THREAD

**Issue by jonlepage** [jspreadsheet/ce#905]
Hi how i can get intellisense suggestion in vscode for jexcels?
It alway any !?
Do i made a mistake somewhere ?
![image](https://user-images.githubusercontent.com/24865815/77263480-e99ffc80-6c6e-11ea-8579-29e46c232bde.png)

how maybe do you have something like this ? i know sometime it work
`npm i --save @types/jexcels` ?
thanks for any help

**Comment by pphod** [comment]
npm install --save @types/jexcel
