### ISSUE TITLE
Angular binding broken

### ISSUE THREAD

**Issue by jainpradeep** [jspreadsheet/ce#906]
Sir,

I added a save button in your example for angular to reproduce the issue.

Data from the component is populating in JExcel grid but if we update the Jexcel grid component data (logged in alert on save click) is not getting updated.

This is happening in jExcel 3.7+ versions. 2 way binding works well with older version. I have verified with the same example in v3.4.

[https://codesandbox.io/s/jexcel-and-angular-hrbpl](https://codesandbox.io/s/jexcel-and-angular-hrbpl)

**Comment by pphod** [comment]
You need to change the button for
yourSpreadsheetInstance.getData()

**Comment by pphod** [comment]
I manage to restore that from v4 it would be release soon.
