### ISSUE TITLE
Prevent right click menu from displaying dropdown

### ISSUE THREAD

**Issue by tbnovaes** [jspreadsheet/ce#91]
Would be great to have the option of disabling the right click menu. To avoid users from add/remove rows, cols.

**Comment by pphod** [comment]
Please use the option contexMenu:methodname as below:

```
<script>
data = [
    ['Mazda', 2001, 2000],
    ['Pegeout', 2010, 5000],
    ['Honda Fit', 2009, 3000],
    ['Honda CRV', 2010, 6000],
];

$('#my-spreadsheet').jexcel({
    data:data,
    contextMenu:function() { return false; },
    colHeaders: ['Model', 'Price', 'Price' ],
    colWidths: [ 300, 80, 100 ]
});
</script>
```

**Comment by tbnovaes** [comment]
Thank you @paulhodel, that's great not only it prevents it to display, but it also allows me to return my own options.

**Comment by shrutiakki** [comment]
Even I'm having same issue please help me out

**Comment by jaspreetbmninfotech11** [comment]
Can I disable contextMenu for first n columns only?
