### ISSUE TITLE
BUG: Row drag & drop reorder does not work correctly with paged lists

### ISSUE THREAD

**Issue by ScottishDarren** [jspreadsheet/ce#910]
I've noticed that drag and dropping rows on a paged list does not honour the page position the reorder is on.

Using the demo https://bossanova.uk/jexcel/v3/examples/datatables as an example:

1. Go to page 2
2. Drag Item (20) - ADBE to position (11)
3. Click to page 1, ADBE will be listed at position (1)

I've already created a short video here that demonstrates the same behaviour:
https://www.screencast.com/t/Kz6rhoi1sdxY

Thanks.

**Comment by pphod** [comment]
Yes, I got it. Thanks for that. I will fix that soon...

**Comment by tsh356** [comment]
This is also a bug in jExcel Pro. Is there a separate repo for Pro issues?

**Comment by pphod** [comment]
I am working in the fix for both versions.

**Comment by pphod** [comment]
This has been fixed on v3 CE and v4 PRO. Both versions are available on NPM.

**Comment by tsh356** [comment]
Thank you!
