### ISSUE TITLE
How to copy cell values from other cells on startup?

### ISSUE THREAD

**Issue by jnksnd** [jspreadsheet/ce#911]
Hello all,
i am trying to copy over cell values from adjacent columns on startup, it kinda works. However when i try to edit the copied values they disappear. I think the problem is in line 137 in the following jsfiddle: 
`137: $(table.records[row][col]).html(preCatValue);`

https://jsfiddle.net/jnksnd/cajmhzd4/

For example, editing Row 1, Column 1(Code) "12345" (white background) works fine, but when you try to edit Row 2, Column 1(Code) "06842" (blue background), which has been copied from Row 2, Column 2(Code Predicted) on startup, the value will disappear when you double click it.

Sorry for this awful mess!

**Comment by GBonnaire** [comment]
HI,

Did you try to use function table.setValueFromCoords in place of $(table.records[row][col]).html ? 

setValueFromCoords(
@Param integer x,
@Param integer y,
@Param string Value - new value for the cell,
@Param bool force - update readonly columns
)

**Comment by pphod** [comment]
Hi, you should not change the innerHTML of a cell. Because this is just a label, the real value is in another array. Please use setValue() or as suggested by Guillume, use setValueFromCoords.

**Comment by jnksnd** [comment]
Thanks for your help guys! setValueFromCoords did the trick for me!
