### ISSUE TITLE
is there a way to highlight specific rows of data?

### ISSUE THREAD

**Issue by 3AUCE** [jspreadsheet/ce#914]
curious to know if it is possible to highlight specific rows of data?

**Comment by 3AUCE** [comment]
highlighting individual cells within a row is not working for me. 

```    var myTable = jexcel(document.getElementById('spreadsheet'), {
        url: '/gantt_data',
        columns: headers,
        onload: loaded,
        columnResize:false,
        nestedHeaders:[
                {
                    title: 'SCHEDULE',
                    colspan: headers.length-2,
                },
        ], 
        style:[
            { A1: 'background-color: grey; ' },
            { B1: 'background-color: grey; ' },
            { C1: 'background-color: grey; ' },
            { D1: 'background-color: grey; ' },
        ],
    });
```

**Comment by pphod** [comment]
```
        url: '/gantt_data',
        columns: headers,
        onload: loaded,
        columnResize:false,
        nestedHeaders:[
                {
                    title: 'SCHEDULE',
                    colspan: headers.length-2,
                },
        ], 
        style: {
            A1: 'background-color: grey; ',
            B1: 'background-color: grey; ',
            C1: 'background-color: grey; ',
            D1: 'background-color: grey; ',
        },
    });
```

**Comment by 3AUCE** [comment]
@paulhodel i cant seem to get this to work. 
short explanation of what i'm trying to do - i have a table that consists of a ton of projects as well as all of the phases for each project. initially i was trying to figure out a way to have each project group collapsed so that when you expanded it, you would see all of the phases within that project. now i'm trying to figure out a way to have each project row highlighted. ultimately i'm just trying to figure out a way to visually separate each project and phases from all of the other project and phases so that when the user is scrolling through the data, it does not appear as one long continuous project group. hope that makes sense
