### ISSUE TITLE
set rgb as default column color  & change calendar format as time

### ISSUE THREAD

**Issue by Aliansyah5** [jspreadsheet/ce#915]
i have field in database which contain rgb color,
can i set RGB as default colums color format in jexcel v3 ?
and second
in my record db format time, cant show value in column calendar
how to show time picker only & show my record in time in column, in jcalendar ?
thanks in advance

**Comment by pphod** [comment]
You need a custom column for the time only.
https://bossanova.uk/jexcel/v4/examples/column-types (Second example)

In regards to the RGB, you can define that as CSS.
