### ISSUE TITLE
setStyle part of 'undo' chain

### ISSUE THREAD

**Issue by leahein** [jspreadsheet/ce#922]
Using an undo shortcut (such as `ctrl+z' / 'cmd+z`) undoes the last thing typed in the jexcel table, which is a helpful shortcut.

However -- it appears that if you call `setStyle` on the table, that becomes part of the 'undo' chain.  Thus, if a user will 'undo' after a style was applied, it will undo the styling applied to the table, rather than the last thing that was typed.  This is a confusing user experience, since 'undo' doesn't typically remove styling.

I'm not sure if there's a workaround for this, but wanted to mention this and see if there was.

This can be replicated by going [here](https://bossanova.uk/jexcel/v3/examples/table-style), clicking the "Set A2 background" button, clicking into the table, and typing `ctrl+z` / `cmd + z`.

**Comment by GBonnaire** [comment]
Hi

You can use param of setStyle: set cell(s) CSS style
@Param mixed - json with whole table style information or just one cell identification. Ex. A1.
@param k [optional]- CSS key
@param v [optional]- CSS value 
@param force [optional]- Force overwriting value
@param ignoreHistoryAndEvent [option]- Ignore History (Not add in history)

`myTable.setSyle([object], [string], [string], [bool], [bool]);`

Example : 
`myTable.setStyle("A1", "background-color", "blue", false, true);`
