### ISSUE TITLE
getJson() shows new columns as "undefined"

### ISSUE THREAD

**Issue by robalexclark** [jspreadsheet/ce#927]
If you add a new column to the sheet and rename it from the default (appears as undefined in the input box) this new name is not reflected in a subsequent call to getJson (still appears as 'undefined' in the json).

**Comment by robalexclark** [comment]
I'm using 3.9 which has this bug. It looks like there were two bugs  in 3.9 that caused this problem:

The first is referenced in #843 and fixed in 46e390ef47e78dda52c63d6d2f610195bb9bd9f8. This fixes the title property being set correctly.

The second is caused in the getJson() function which has  the following row:
                    `row[obj.options.columns[i].name] = obj.options.data[j][i];`
I've changed to:
                  `  row[obj.options.columns[i].title] = obj.options.data[j][i];`

This seems to fix the issue for me, but I don't know whether this is correct (maybe name should be also set on column rename as well as title?). I'll leave the issue open for you to review and decide....

**Comment by pphod** [comment]
This is not the solution, name is the key where title is the label. When name is not provided, name is equal to the index of the column.

row[i] = xxx;

I am not sure the reason of the error in your side. But, I am happy to analise more information. Do you mind to share a jsfiddle?

**Comment by robalexclark** [comment]
I sort of see what you mean. I require the title (set by the user) to be output in the json whereas your implementation considers the row index to be the necessary output.

However when you create a new column that columns output comes out as 'undefined' (no matter whether you rename the column or not). If it was consistently the column index as you say then I could output column headers separately and handle outside of jExcel.

Here is a jsfiddle  https://jsfiddle.net/46ow5qnu/

If you right click and add a new column (appears menu below but still 'works') and then press 'Export' the new column is listed as 'undefined'
