### ISSUE TITLE
Using image or HTML in a cell

### ISSUE THREAD

**Issue by Svitra** [jspreadsheet/ce#929]
I would like to use your table as a replacement for another solution we were using that was depricated. I found you have all the features we need, I am just not sure about one: In one of our views we need a special row in the table that contains a clicable icon (delete) which triggers the action delete row (and this row is "readonly"). Could this be configured now using the image and hook or would it be possible to insert some html into a cell? Could you please provide me some example how (if) that could be done?

**Comment by pphod** [comment]
Yes, you can insert HTML in a cell.
https://bossanova.uk/jexcel/v4/examples/richtext-html-editor

**Comment by Svitra** [comment]
Thank you, I managed to display the button by following your suggestion and using a readonly html column, but I am not sure what event can I use to detect a cell was clicked? I tried to go through the examples and events in docs but I did not manage to find any suitable for this case. Can you suggest? What I need is to know that the "delete" button cell was clicked and which row it was clicked in.

**Comment by Svitra** [comment]
For now I managed to write a solution using the onSelection event, however I think that is not a very elegant solution.
