### ISSUE TITLE
Multiple spreadshets have same ids for cells

### ISSUE THREAD

**Issue by ondramu** [jspreadsheet/ce#93]
Hi,
I would like to use multiple spreadshets, but the cells have the same ids for every table.
Is there a way how to fix that?

Thanks a lot.

Ondrej

<img width="461" alt="screen shot 2018-01-31 at 14 06 44" src="https://user-images.githubusercontent.com/35999527/35624708-08ad1de8-0690-11e8-80fd-db82cfbbd61e.png">

**Comment by pphod** [comment]
The ID is like coordinates, so it is not possible to change that.
If you want to create any operation you can try: $('#table').find('#0-0');
