### ISSUE TITLE
Clearing multiple cells with backspace?

### ISSUE THREAD

**Issue by tomas** [jspreadsheet/ce#930]
Hi, this seems like a dumb question but I looked at the docs and couldn't find the answer. 

Currently, when I select multiple cells and hit backspace, only the first one gets cleared. Is there a way to tell jExcel to treat the backspace as the delete key?

**Comment by GBonnaire** [comment]
Hi,

You can add in your JS a new EventListener on keydown and use setValue function

Example :
```
document.addEventListener("keydown", function (e) {
    if (jexcel.current) {
        if (jexcel.current.edition) {
             if (e.keyCode == 8) { // 8 = Backspace key code
                 jexcel.current.setValue(jexcel.current.highlighted, '');
                 e.stopPropagation();
             }
         }
    }
});
```

**Comment by tomas** [comment]
Excellent, thanks!
