### ISSUE TITLE
Reload Source of Dropdown in VUE

### ISSUE THREAD

**Issue by ikhbalfuady** [jspreadsheet/ce#933]
Hello @paulhodel , its very awesome works, because of u, i have made my work very faster, iam newbie in you plugin, i have searching about my problem, but still not have a answer, 

how i can reload source of dropdown in vue ?
i use ajax mode with url, always have errors CORS and i stucked, 

can u tell me how to reload source of dropdown ?

`    XCL_init (sourceOfProduct) {
      var options = {
        data: [],
        allowToolbar: true,
        columns: [
          { type: 'dropdown', title: 'product', width: '250px', source: sourceOfProduct , autocomplete: true },
          { type: 'numeric', title: 'Harga', width: '100px', mask: '#.##,00', decimal: ',' }
        ]
      }
      
      var spreadsheet = jexcel(this.$el, tableOption)
      Object.assign(this, { spreadsheet })
    }`

when i call again this method, its make duplicate.

**Comment by pphod** [comment]
You can change by using the following code.

`spreadsheet.options.columns[columnNumber].source = newSource;`
