### ISSUE TITLE
is it supporting virtual dom functionality of react or you setup any diffing algorithm to know and update only change element . 

### ISSUE THREAD

**Issue by manojHDwork** [jspreadsheet/ce#936]
=> because in code i see we are just bind jexcel with dom directly so i thought to confirm with you like 
1  Is it supporting virtual dom functionality of react if i'm using in react project ?
2 can it handle large amount data ?

**Comment by pphod** [comment]
1) You can use the internal DOM references from the react to initiate your table.
2) jExcel CE renders as a HTML table. jExcel Pro has his own virtual DOM and engine for loading. So, it would be much more appriate for handling big datasets (www.jexcel.net)
