### ISSUE TITLE
JExcel + JCalendar - Done button event

### ISSUE THREAD

**Issue by jpsarno** [jspreadsheet/ce#937]
Hello.

It is possible to configure the "Enter" key action to execute the event of the button Done in jCalendar in a collumn from jExcel?

Thank you very much.

Regards,
João

**Comment by pphod** [comment]
Yes, I will include that in the next release.

**Comment by jpsarno** [comment]
Hello Paul.

Thank you very much. Do you have any ideia when the new release will be available?

**Comment by pphod** [comment]
It should be ready during the weekend.

**Comment by pphod** [comment]
I have included that, the version is almost ready. Should be in the repository this Sunday.
