### ISSUE TITLE
Pass '=' as a custom formula's argument

### ISSUE THREAD

**Issue by themagiulio** [jspreadsheet/ce#938]
I have the esigenze to pass the equal sign into a formula's argument. 
If I write it into a string the formula works: `=FORMULA('example=')`.
But, if I write `example=` into a cell (for example A1) and then I call the formula `=FORMULA(A1)`, it doesen't work, because I suppose that the argument is not passed as a string.
I'm wandering if there is a method to pass the equal sign with both methods...

**Comment by pphod** [comment]
I am not sure if this is the problem. Can you share you example on jsfiddle?

**Comment by themagiulio** [comment]
While I was creating the script I noticed that with samples strings it works, but if try to use more complex strings as argument like `C1(=CC=CC=C1)` it doesen't work [https://jsfiddle.net/6y4cnto2/](https://jsfiddle.net/6y4cnto2/)

**Comment by pphod** [comment]
In this case you should use some method to concat your string.

Regards,

Paul Hodel

**Comment by themagiulio** [comment]
I tried to return `C1(=CC=CC=C1)` without numbers (`C(=CC=CC=C)` ). In this case `=FORMULA(A1)` seems to work.
So, I tried to follow your advice, but, when I split the strings*: `=FORMULA(A1)` returns the error message `#ERROR`, while `=FORMULA('C1(=CC=CC=C1)')` returns correctly `C`.

So, it seems that the problem are the numbers and not the equal signs.

*`var FORMULA = function(v) {
return v.split('1')[0];
}`

**Comment by themagiulio** [comment]
I resolved the problem by setting `autoCasting: false`.
