### ISSUE TITLE
Hi Paul,I dont want the right click context menu on our  Jexcel grid,Want should i do?

### ISSUE THREAD

**Issue by aashiqahmed98** [jspreadsheet/ce#939]

**Comment by jenbuzz** [comment]
You can hide it with an empty contextMenu option or simply using CSS:

```
$('#mytable').jexcel({
  data: data,
  columns: tableColumns,
  contextMenu: function () {
    return null;
  }
});
```
```
.jcontextmenu {
  display: none; 
}
```

**Comment by aashiqahmed98** [comment]
Thanks, Paul for answering our question even in the tough times, we are currently implementing splendid grid in our project, you can expect more questions from us :-)

**Comment by pphod** [comment]
If you have a chance take a look in the options of v5. It brings lot of great features.
www.jexcel.net/v5
