### ISSUE TITLE
Make a cell active/editable like it was clicked

### ISSUE THREAD

**Issue by aisufi** [jspreadsheet/ce#94]
Hello,

is there a way to make the first cell in the first row active like the user clicked or double clicked the cell and make it editable right away...via javascript?

Thanks in advance!

**Comment by pphod** [comment]
You can add a class readonly to make the cell readonly. And you can create the click event to remove the class from the cells you have clicked.

$('#table .r0').addClass('readonly');

**Comment by aisufi** [comment]
Thank you very much for your fast response but I might have explained my issue wrong.

Imagine this: The page is done loading and after that I want the first cell in the first row to be editable (so the user can start typing right away) and does not have to click with his mouse in the first cell. I just need this when the page has done loading. So i would need some sort of function which makes that given cell active like the user double clicked the cell.

I hope this was better explained.
