### ISSUE TITLE
Button inside cell

### ISSUE THREAD

**Issue by kAvItHa-cL** [jspreadsheet/ce#941]
Can I put button inside cell or button column type  with unique id and onclick event..? On click event should call some function. Is this feature available @hodeware

**Comment by pphod** [comment]
Yes, there are many ways to do that.

**Comment by pphod** [comment]
You can actually include a <input type="button" value="action" onclick="youraction()"> in the source of your spreadsheet.

**Comment by saurabhghadi0401** [comment]
Hi @paulhodel , can you please share any example related to this?, I tried with custom editor, but didn't workout well. I am using 
jexcel v4.2.1

**Comment by gonzer31** [comment]
Hi @kAvItHa-cL were you able to solve this? I'm having trouble calling the onclick event within my button. 

I'm using a simple example (based on [create from HTML table)](https://bossanova.uk/jexcel/v4/examples/create-from-table), with this inside a div.

```
<td>
      <div>
        <h3>TESTING</h3>
        <button onClick={(e) => console.log(e, 'clicking on button!')}>button</button>
      </div>
    </td>
```

but my onclick event is not being called. I'm using React, which is why I'm using `onClick`. `onselection` works fine, though.

**Comment by marcosaso** [comment]
Hi guys,

I didn't find any code to resolve that issue.
So, I resolved in that way:

// get table by className - in my example is  'jexcel jexcel_overflow' - check in your HTML source code the className:

const spreadSheet1: HTMLTableElement = document.getElementsByClassName('jexcel jexcel_overflow')[0];

// after that just assign your click function in one or more cells using "for", rows and cell table proprieties 

      for (let i = 0; i < spreadSheet1.rows.length; i += 1) {
        // item(8) is equal to data-x = 7 (column = 7) for example: 
        spreadSheet1.rows[i].cells.item(8).onclick = teste;
      }


function teste() {
  alert('It works!!)
}

If there is other better way todo that inside the jspreadsheet lib, please, send it here.

**Comment by hodeware** [comment]
You can use a customEditor.
https://bossanova.uk/jspreadsheet/v4/examples/column-types
