### ISSUE TITLE
Error on v3 site

### ISSUE THREAD

**Issue by ahmadsyamim** [jspreadsheet/ce#943]
Seems like there's an error on 
https://bossanova.uk/jexcel/v3/

![image](https://user-images.githubusercontent.com/14102774/80776424-50350600-8b9d-11ea-9cb0-e854efb53fc2.png)

**Comment by pphod** [comment]
Thanks, there is a version conflict on jsuites. I will fix that thanks. But, if you are using v3, please consider moving to v4 or v5 (www.jexcel.net/v5)

**Comment by pphod** [comment]
It has been fixed, thanks.
