### ISSUE TITLE
Is it possible to apply style to entire row or column?

### ISSUE THREAD

**Issue by harshdesai991** [jspreadsheet/ce#945]
Hi Paul,

I know there is a way to apply table style for individual cells. Is it possible to apply a common style for the entire row or columns?
 Something like below:

`rowStyle: {
        1: "font-weight: bold;"
},

columnStyle: {
        "A": "font-weight:bold;"
}`

**Comment by pphod** [comment]
You can do using pure CSS. For example, the code below create row even/odd bg colours.

```
<style>
.jexcel tbody tr:nth-child(even) {
  background-color: #EEE9F1 !important;
}
</style>
```

The result you can see here.
https://bossanova.uk/jexcel/v4/examples/table-scripting
