### ISSUE TITLE
It is possible to remove all rows, which leads to unexpected behaviour

### ISSUE THREAD

**Issue by optilude** [jspreadsheet/ce#947]
Using v4.1.2 installed from npm, I have a table with a few columns and rows. If there is only one row remaining and the user right-clicks on that one row and selects "delete selected row", nothing happens, but an error is logged in the console:

```
JEXCEL. It is not possible to delete the last row
```

However, if there are two or more rows and the user selects an entire column (i.e. one cell from each row) and then performs the same action, all rows will be deleted.

At this point, other things begin to break in slightly unpredictable ways, and it is not possible to insert any rows again.

**Comment by pphod** [comment]
Thanks, this should not happen. I will take a look onto this soon.

**Comment by klren0312** [comment]
can use the `ondeleterow` event to handle delete, when delete more rows, add one row
```js
ondeleterow:  function () {
      const currentData = this.excelInstance.getData()
      if (currentData.length === 0) {
        excelInstance.setData(['', '', ''])
      }
}
```

**Comment by pphod** [comment]
That has been fixed on the Pro distribution and should be brought to the CE soon.

**Comment by PtrBednarik** [comment]
allowDeletingAllRows: true
