### ISSUE TITLE
Pasting from Excel inserts null string if last cell is empty

### ISSUE THREAD

**Issue by optilude** [jspreadsheet/ce#948]
I have a table with a fixed number of columns and a variable number of rows.

If a user copies data from Excel with the right number of columns and an arbitrary number of rows, and the bottom-right-most cell is empty in Excel, the data that is inserted into jExcel is not an empty string, but rather a null string (`"\0"`).

A workaround, sort of, is to have this event handler, which slices off a trialing tab in the paste data:

```
      onbeforepaste: function(instance, data, x, y) {
        // if the last cell is empty, we get a weird null value (see )
        if(data && data[data.length-1] === "\t") {
          data = data.slice(0, data.length-1);
        }
        return data;
      },
```

This pastes the data correctly, although the shape of selection afterwards is not quite right because it will exclude the final column.

**Comment by optilude** [comment]
Some additional context:

- The behaviour appears to be deliberate. In `parseCSV` we have:

```
       if (str.charCodeAt(str.length-1) == 9) {
            str += "\0";
        }
```

(note that this hardcodes 9, which is tab, even though the delimiter appears to be configurable)

- I've found it better to implement `onbeforechange` and modify `"\0"` to `""` (empty string) than to modify the paste value as per the workaround above.

I still don't think this is exactly expected behaviour. At least my code did not attempt to look for `"\0"` and because this is a non-printable character it's really confusing to debug!

**Comment by pphod** [comment]
That has been improved on the Pro version, and it will be eventually brought to the CE as well.
https://jexcel.net
