### ISSUE TITLE
BUG: Sorting integers with separator masks causes unpredictable behaviour

### ISSUE THREAD

**Issue by ScottishDarren** [jspreadsheet/ce#949]
On larger datasets with lots of integers using masks on 1000 separators, eg comma ',' or period '.' items get mixed up and ordered incorrectly.

Using a comma on numbers, eg 2,000, 1,345 the sorting gets really messed up. On periods, its not quite so bad, but if there's a mixture of numbers, eg some 100s and some 1000s, such as 234, 3.000 then the sort > ascending option groups 100s and 1000s seperately.

There's a fiddle here demonstrating this behaviour:
https://jsfiddle.net/darrenjames/ucts769y/1/
It seems to depend on the range of numbers, eg all 100s, or all 1000s are fine, the fiddle will generate random data each time its loaded to demonstrate.

**Comment by pphod** [comment]
This should be better on v4.2+ since we consider the column type for the sorting.

**Comment by ScottishDarren** [comment]
The sorting bug is still there in v4.2, although the behaviour is slightly different.
https://jsfiddle.net/darrenjames/ucts769y/7/

Sorting now happens on the first integer on the number, so a list of numbers sorted ascending would be displayed as:
1852
10759
19915
2002
2249
20001
3101
901

It now does properly handle the formatting mask however.
