### ISSUE TITLE
Hi paul

### ISSUE THREAD

**Issue by shroffritesh** [jspreadsheet/ce#951]
Hope you are doing great.........
I want to know. When we passing data into blank jexcelsheet and jump into next cell, at this time i want to add those data into  :
jexcel(document.getElementById('spreadsheet'){
         data: data , <<<<<<<<<<<<<<
}

Is it possible? 
so please let me know.

**Comment by pphod** [comment]
A very rough idea how would work.

```
onselection: function(instance, x1,y1,x2,y2) {
    var xxx = jexcel.getColumnNameFromId([x1,y1]);
    instance.setValue(xxx, value);
}
```

**Comment by shroffritesh** [comment]
I think you did not understand my question. Not an issue, When I'm integrating blank excel and at that time I select a single cell and add data init. That data I want in data = [...] available in "jexcel(document.getElementById('spreadsheet'){ data: data  } "  like that every cell data i want in data = []. Hope you understood. 
Thanks

**Comment by pphod** [comment]
To get the data back you should use:
getData();

If you want the element be in the data, you can try to use Jexcel Pro v5, where the data will be updated with the data automatically.

**Comment by pphod** [comment]
Example for you:
https://jsfiddle.net/paulhodel/qjm51org/

**Comment by pphod** [comment]
JExcel Pro v5
https://jexcel.net/v5
