### ISSUE TITLE
Ignore Events  - Doubt

### ISSUE THREAD

**Issue by jpsarno** [jspreadsheet/ce#954]
Hello Paul.

I already discovery what happens with my implementation, to trigger the onchange event more than one time in just one value adjustment.

In my code I inovoke the method setValue, and this method is triggering the onchange event again.

I tried to do like this:

$.fn.jexcel.ignoreEvents = true;
$.fn.jexcel.ignoreHistory = true;
currentGrid.setValue("A" + lineNumber, newIdValue, 0);

But it doesn't worked. The code still invoking the onchange event again. I'm using the version jExcel v3.8.2

Thank you very much.

**Comment by pphod** [comment]
// This is enough to change the value and the label without using setValue.
currentGrid.options.data[y][x] = newIdValue;
currentGrid.records[y][x].innerHTML = newIdValue;

**Comment by jpsarno** [comment]
Thank you Paul.

It works for me.

**Comment by pphod** [comment]
We have launched Pro v5, in case you want to give a try.
www.jexcel.net/v5

Regards
