### ISSUE TITLE
Calender input with kyboard keypress happens twice in angular example

### ISSUE THREAD

**Issue by jainpradeep** [jspreadsheet/ce#956]
Sir,

In your angular example

https://codesandbox.io/s/jexcel-and-angular-ej4u2

if we add a calender input. Each keypress on keyboard is recorded twice in the input box.

**Comment by pphod** [comment]
I was not able to replicate the problem. I tested and seems to be working fine.

**Comment by pphod** [comment]
Can you send more details?

**Comment by jainpradeep** [comment]
Sir,

Steps to reproduce
Single click on the calender input (without opening the calender modal)
press any number (the calender popup opens)
press the number key again 

now with every keystroke it is inputted twice in the input box.

**Comment by jainpradeep** [comment]
Sir,

Please find a gif for showing the issue
[Link](https://drive.google.com/file/d/1NDOs2ZT_3503Rshbs_w4dHioHyvsQJXW/view?usp=sharing)
2 keypress registering with one press.

**Comment by jainpradeep** [comment]
Also sir,

Calender options are not working with the example. eg. readonly to disable keyboard input.
