### ISSUE TITLE
Performance issue when loading 50000 rows 

### ISSUE THREAD

**Issue by likepeach789** [jspreadsheet/ce#957]
Hi Paul,

I googled javascript spreadsheet and thankfully found this awesome project. :) After watching the document, i tried to create a simple demo project using VUE. Here is the [codesandbox](https://codesandbox.io/s/dreamy-pike-k2b0t?file=/src/components/HelloWorld.vue) link.

There is some performance issue when i just simply increase the row size to 30000/40000/50000. It shows an empty page and i need to wait nearly 10s or mote to 
get the table rendered in page. The page also freezes when i try to edit a cell value,  Do you have any suggestions on how to solve this issue?

After searching in the doc, i see there is  [lazy loading ](https://bossanova.uk/jexcel/v4/examples/lazy-loading) feature available. Is it possible to directly scroll to the end of the table? It spend a lot of time to do the scrolling which may not be user friendly. Thanks for creating this amazing project and hope get your reply. :)

jExcelOptions:
```javascript
jExcelOptions() {
      let columns = _.map(["name", "title", "age"], columnName => {
        return {
          title: columnName,
          width: 150
        };
      });

      let rows = [];
      for (let i = 0; i < 30000; i++) {
        rows[i] = [];
        for (let j = 0; j < columns.length; j++) {
          rows[i].push("1000000");
        }
      }

      return {
        data: rows,
        columns: columns,
        minDimensions: [columns.length, 10],
        csvHeaders: true,
        columnDrag: true,
        allowInsertColumn: false,
        allowManualInsertColumn: false,
        allowDeleteColumn: false,
        onload: function() {
           // Looks like this function got executed before the table is finally rendered in the page.
           console.log('table got rendered..');
        }
        // tableOverflow:true,
        // lazyLoading:true,
        // loadingSpin:true,
      };
    }
```

**Comment by pphod** [comment]
You should use pagination or lazyLoading...

Check this example:
https://codesandbox.io/s/hopeful-einstein-yq5sc
