### ISSUE TITLE
Onblur doesn’t set value to last active cell

### ISSUE THREAD

**Issue by kAvItHa-cL** [jspreadsheet/ce#958]
Hi Paul, when onblur event triggers last cell value doesn’t set its value . it will be empty . How can it be resolved..?

**Comment by pphod** [comment]
Sorry, not sure if I understand correctly. Can you send an example of how to replicate that?

We launched a couple of weeks ago, Jexcel Pro v5, did you have a chance to take a look? I am trying to bring more active developers to that version so we can build a better product.

Let me know if you consider migrating and we discuss a exclusive conditions for you.
https://jexcel.net/v5

**Comment by kAvItHa-cL** [comment]
Ex : consider table has 3 columns and cusom method to handle on TableBlur event. If you enter some value in 2nd column and click outside of table, so onblur event occurs but value filled for 2nd cell will be empty. But after 2nd cell if you click on any other cell and then come out of table, the value will be set properly.
