### ISSUE TITLE
Append rows

### ISSUE THREAD

**Issue by jamesckemp** [jspreadsheet/ce#96]
Hey,

I'm not sure if I'm missing it, but is there a way to append rows, rather than replacing all of them?

**Comment by pphod** [comment]
Hi James, I am not sure if this is going to help, you but did you try insertRow()? It will append a new row in the end of the table without reload the table.

**Comment by jamesckemp** [comment]
Hey, 

I did see that but from my understanding it'd be a blank row? Did I miss a way to populate it?

**Comment by pphod** [comment]
Sorry, you are right. I am going to create something. Meanwhile, you will need to insertRow them setValues cell by cell or use the loadCells to update all cells in a batch.

**Comment by jamesckemp** [comment]
For now I'm just reloading the whole table when the new data is ready, but appending rows with data would be awesome as my table could be huge!

**Comment by pphod** [comment]
Yes, your request make a lot of sense. I am going to add that in the next release.

**Comment by pphod** [comment]
It has been done. appendRow has been included in the most recent version in the master repository.
