### ISSUE TITLE
Deleting the entire grid and updating the server

### ISSUE THREAD

**Issue by aashiqahmed98** [jspreadsheet/ce#960]
Can u pls explain how to delete the entire grid on clicking a button and updating on the database/serve.Thanks in advance!

**Comment by pphod** [comment]
For reseting your table:
yourTable.setData([[]]);


In regards to saving, if you consider a subscription I would suggest Jexcel Pro, which gives a lot of off the shelf options for remote saving. www.jexcel.net/v5

Regards,
