### ISSUE TITLE
v3: Sorting strange

### ISSUE THREAD

**Issue by sasha-x** [jspreadsheet/ce#964]
How to reproduce:
1. Go to https://bossanova.uk/jexcel/v3/examples/sorting , first table, select column A.
2. Paste example content
```txt
dewdew
5454545
222
333
4444
999
fe
refrefrefre
erfrefrefre
refrefre
erferfref
efrefrefref

refrefrefref
erfrefrefre

сывсыс
сывсыс
сывсыс
```
3.Sort by double-click asc and desc.

Sorting order in both asc and desc direction looks strange for me.
Why so? How to fix?

Screens below:
![Screenshot from 2020-05-15 23-56-09](https://user-images.githubusercontent.com/8925015/82095813-81b6e100-9708-11ea-9935-5ca8bd1388c4.png)
![Screenshot from 2020-05-15 23-56-13](https://user-images.githubusercontent.com/8925015/82095849-91cec080-9708-11ea-9c69-008e89eedcd8.png)

Firefox 70 and Chrome 81.

**Comment by pphod** [comment]
I have changed that. There is still room to improve considering the international UTF chars.

**Comment by sasha-x** [comment]
Sorry, where can I get fixed version of v3 code?
I see master point to v4 now.

**Comment by pphod** [comment]
Is there any chance you upgrade to v4?

**Comment by sasha-x** [comment]
I plan to do upgrade after a while.
Now I patch v3 locally with your last commit code. Works good.
Thank you!

**Comment by pphod** [comment]
Sasha, the last commit is already version 4.

Regards,
