### ISSUE TITLE
Cache dropdown data

### ISSUE THREAD

**Issue by jamesargent-contexcity** [jspreadsheet/ce#968]
Is it possible to cache data for a dropdown?

I have several dropdown which I need to populate with json from different urls. However I'm finding the table is slow to load when approaching 50+ records. Is there a way to load the data for each dropdown once and then apply it to the dropdown in all rows?

**Comment by pphod** [comment]
We need to see if this actually the problem. If you share an example in jsfiddle might help. Can you try with the new jSuites version? v3?
