### ISSUE TITLE
I would like to be able to resize the table after it is drawn

### ISSUE THREAD

**Issue by fsalamah** [jspreadsheet/ce#972]
Hi, 

I am trying to find a way to resize the table after it is drawn. I could not find a way to do that. It would be very helpful to have this feature. Or maybe it is there but i could not manage to find it.

**Comment by pphod** [comment]
You can try that.
jexcel.current.content.style.width = '100px';

Or:
document.getElementById('your-id').jexcel.content.style.width = '100px';
