### ISSUE TITLE
A problem occurs with columns display when you hide the row-numbers header 

### ISSUE THREAD

**Issue by vsajip** [jspreadsheet/ce#977]
See this fiddle: https://jsfiddle.net/vsajip/fcd9znoa/

If you change the CSS
```
.jexcel_row, .jexcel_selectall {
  zdisplay: none;
}
```
by renaming `zdisplay` to `display`, thereby hiding the row-numbers header column completely, the widths and display of the remaining columns are messed up. Before:

![before](https://i.imgur.com/ibGvVGo.png "before")

After:

![after](https://i.imgur.com/ruZu4RH.png "after")

This shouldn't happen.

**Comment by pphod** [comment]
Please use:
table.hideIndex()
