### ISSUE TITLE
selectionCopy setting not respected if freezeColumns is null

### ISSUE THREAD

**Issue by vsajip** [jspreadsheet/ce#978]
The `selectionCopy: false` setting is supposed to not show the cell corner. However, if `freezeColumns` is `null` (the default), [this code](https://github.com/paulhodel/jexcel/blob/master/src/js/jexcel.core.js#L2856) sets the corner style display to `''` (previously set to `'none'` in the initialisation code), thereby showing the corner even though `selectionCopy` is `false`.

**Comment by pphod** [comment]
It has been fixed on the master repository. Thanks for spotting that.
