### ISSUE TITLE
Context menus flicker and don't stay up as expected

### ISSUE THREAD

**Issue by vsajip** [jspreadsheet/ce#979]
See this fiddle: https://jsfiddle.net/vsajip/fcd9znoa/

If you right-click on a column heading, a context menu pops up and stays up, as expected. If you then immediately right-click on a different column heading (or the same column heading again), the context menu enters this strange mode where it pops up and disappears immediately, whichever column heading you click on. The following video demonstrates this:

![video of problem](https://i.imgur.com/jbWUHsO.gif "video of problem")

I don't believe this is meant to happen.

**Comment by pphod** [comment]
I have just do that same test on the website and I was not able to replicate this behavior.

Can you do the same test here and let me know if this behavior is here?
https://bossanova.uk/jexcel/v4/

**Comment by vsajip** [comment]
Sure, I reproduced it easily on your website. I'm using JExcel 4.2.0, Ubuntu 64-bit and Firefox 76.0.

![problem on Firefox](https://i.imgur.com/LnJEhrh.gif "problem on Firefox")

Using Chromium 81.0, the behaviour is slightly better, but still not quite right:

![Chromium behaviour](https://i.imgur.com/AVRAK28.gif "Chromium behaviour")

Note the flicker still happens, the menu appears for an instant at the second right-click location and then disappears.

**Comment by vsajip** [comment]
It also happens after a context menu item is selected and dismissed:

![context menu picked](https://i.imgur.com/icH195T.gif "context menu picked")

**Comment by pphod** [comment]
Thanks for the information... I get back to you soon
