### ISSUE TITLE
Page scrolling jumps to top on Ctrl+C

### ISSUE THREAD

**Issue by sasha-x** [jspreadsheet/ce#980]
How to reproduce:
In Firefox 70 
1. open https://bossanova.uk/jexcel/v4/examples/dropdown-and-autocomplete
2. scroll to table 1 or table 2, put focus to cell A1
3. type Ctrl+C
and page scrolling position jumps to top so table leave my screen. At the same time copy operation is successful. Browser console is clean.

On a large table with v3 lib it happens rarely, but looks very uncomfortable.

Not sure about other browsers.

Is that a known issue? Is it something browser-specific or environment-specific?

**Comment by znh0503** [comment]
how to solve?

**Comment by pphod** [comment]
I have just tested on 81.0 and it seems o be working fine. I was not able to reproduce this error.
