### ISSUE TITLE
Copy-paste on autocomplete column

### ISSUE THREAD

**Issue by sasha-x** [jspreadsheet/ce#982]
In https://bossanova.uk/jexcel/v4/examples/dropdown-and-autocomplete table 1 column A
`{ type:'dropdown', width:'300', title:'Product Origin', url:'/jexcel/countries', autocomplete:true, multiple:true }`
I see copy-paste works ok by id of list items. I mean "AF" for:
```js
{"name": "Afghanistan", "id": "AF"},
...
```
Is there any way to copy-paste cell content by item names ("Afghanistan") to be more user-frendly?
(Use events like `onbeforepaste`?)

My real use case is multistring pasting from MS Excel doc to jexcel table with autocomplete column(s).

**Comment by pphod** [comment]
That has been implemented on the Pro distribution and it should be brought to the CE distribution eventually.

https://jexcel.net/
