### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by pphod** [jspreadsheet/ce#983]
Hi Everyone.

I have added a translation template, so we can share Jexcel translations with other users.

If you wish to collaborate, please fork, add a new file to the lang folder and do the PR.

[Example](https://github.com/paulhodel/jexcel/blob/master/lang/en_GB.json)

Thanks.

**Comment by flywalt** [comment]
https://github.com/paulhodel/jexcel/pull/985
Hi Paul, here is a translation of Chinese(simplified) version. Thanks for your great project.

**Comment by GBonnaire** [comment]
Hi, here file for French from France

#987
