### ISSUE TITLE
Extra columns added automatically on initialization

### ISSUE THREAD

**Issue by vsajip** [jspreadsheet/ce#986]
It should be possible to have the spreadsheet only display the columns which are requested in the options, but it appears that extra columns can be displayed automatically on first initialization (before any user interaction). This is unexpected.

Fiddle: https://jsfiddle.net/vsajip/kw12cjhd/

The data passed in contains objects which have `id`, `key`, `value` and `index` properties, but the columns only ask to show `id`, `key` and `value`. Nevertheless, an extra column titled 'D' showing the `index` property is also displayed. I don't want to display `index` because in my real example, it's internal housekeeping data which it's useful to keep in the object itself, but not intended for display. I know I could add an extra hidden column for it, but in my real example I have other fields in the objects, which I don't want displayed.

**Comment by pphod** [comment]
In the current construction this is not possible. You should not include the data or use hidden column. Maybe include something on the onload to remove the columns you don't want after the load.
