### ISSUE TITLE
Can't have html in column header

### ISSUE THREAD

**Issue by CorentinMic** [jspreadsheet/ce#988]
Hello, 
I have been using version 4.2.0 and it seems to be impossible to add html in column header while it was possible in 3.5.0. Even setting html type on the column does not solve this.

Is there a way ?

**Comment by pphod** [comment]
onload: function(el, o) {
    o.headers[columnName].innerHTML = '<b>column name</b>';
}

**Comment by CorentinMic** [comment]
> onload: function(el, o) {
> o.headers[columnName].innerHTML = 'column name';
> }

Not the most intuitive way to do this but it works. Thank you. 
By the way, headers seems to be indexed by their index (number) and not their name.
