### ISSUE TITLE
How to disable adding columns or rows

### ISSUE THREAD

**Issue by thenewguy25** [jspreadsheet/ce#99]
Hi, is there a way to disable adding columns or rows?

**Comment by pphod** [comment]
You have some initial directives may help:

            // Allow new rows
            allowInsertRow:true,
            // Allow new rows
            allowManualInsertRow:true,
            // Allow new columns
            allowInsertColumn:true,
            // Allow new rows
            allowManualInsertColumn:true,
            // Allow row delete
            allowDeleteRow:true,
            // Allow column delete
            allowDeleteColumn:true,

**Comment by thenewguy25** [comment]
Thanks!

**Comment by VictorCandido** [comment]
Is there a way to disable adding columns with "allowInsertRow:false" and still use the "insertRow" function?
I need to block the add row event when enter key pressed but still add a row with customization.
Is there any way of doing that?

**Comment by pphod** [comment]
> Is there a way to disable adding columns with "allowInsertRow:false" and still use the "insertRow" function?
> I need to block the add row event when enter key pressed but still add a row with customization.
> Is there any way of doing that?


        // Allow new rows
        allowInsertRow:true,
        // Allow new rows
        allowManualInsertRow:false,

**Comment by VictorCandido** [comment]
Thank you!!

**Comment by debamishra14** [comment]
@paulhodel @Guillaume-Bo is there any way to disable a whole row? I did not find anything in the documentation. can u plz comment on it?

**Comment by GBonnaire** [comment]
> @paulhodel @Guillaume-Bo is there any way to disable a whole row? I did not find anything in the documentation. can u plz comment on it?

Put class readonly on each cell of this row, you can use updateTable for make that dynamically
