### ISSUE TITLE
Custom editor setValue function not called anymore

### ISSUE THREAD

**Issue by AntoninVA** [jspreadsheet/ce#990]
Hello,

upgrading from version 3.5.0 to 4.2.0, I encountered the following problem :
when leaving a custom editor, its setValue function is not called.

Looking into the source-code I found that this line has been removed from the obj.updateCell :
```
if (obj.options.columns[x].editor) {
    // Update data and cell
    obj.options.data[y][x] = value;
    // this line seems to be missing :
    // obj.options.columns[x].editor.setValue(obj.records[y][x], value, force);
} else {
    // Native functions
```

Is this an error or should I change the custom editor ?

Thank you for the great work anyway

**Comment by pphod** [comment]
I have just double checked and those line are there. L2310
