### ISSUE TITLE
Pricing in v5 ?

### ISSUE THREAD

**Issue by niloyniloy** [jspreadsheet/ce#993]
I would like to know, what benefit do I get if use paid plugins. is there any extra features in paid version ? Also the pricing applies only in V5 ?

**Comment by pphod** [comment]
Jexcel Pro & Jexcel CE are two different projects with different versions.

Jexcel CE is free and always will be.
Jexcel Pro brings support and more a few differences. Jexcel pro helps to keep Jexcel Health and with constant updates.

More information about JExcel Pro, including pricing (www.jexcel.net/v5).
