### ISSUE TITLE
BUG: Column sorting integers does not correctly handle 100s, 1000s numerical values

### ISSUE THREAD

**Issue by ScottishDarren** [jspreadsheet/ce#997]
This is related to a previously reported bug that was partially fixed here:
https://github.com/paulhodel/jexcel/issues/949

Sorting numeric columns happens on the first integer on the number, so a list of numbers sorted ascending would be displayed as:
1852
10759
19915
2002
2249
20001
3101
901

There's an example fiddle here:
https://jsfiddle.net/darrenjames/ucts769y/7/

And here's a screengrab showing the same behaviour on:
https://bossanova.uk/jexcel/v4/examples/sorting
![jexcel4-sorting](https://user-images.githubusercontent.com/12087427/83725939-f9738e00-a66c-11ea-895a-ca82efad3c20.png)

**Comment by pphod** [comment]
Actually, it is not a bug. The column on the example is defined as text, so it is ordering as text. I have taken the same example and created a JSFiddle. For the column B, C, I have defined as type: number, and you will see it ordering as a number:

https://jsfiddle.net/paulhodel/sawo3ydb/
