### ISSUE TITLE
Formula shows #ERROR

### ISSUE THREAD

**Issue by CodeCurosity** [jspreadsheet/ce#999]
I have a cell name B6 which is a date and B7 which is a number, i am using this formula in my sheet and it works fine but in your spreadsheet example it shows #ERROR 

`=IF((67-(YEAR(NOW())-YEAR(B6)))>=30;-ROUND(FV(-0,023;30;B7*12*0,4;0;1);-4);-ROUND(FV(-0,023;(67-(YEAR(NOW())-YEAR(B6)));B7*0,4*12;-PV(0,023;30-(67-(YEAR(NOW())-YEAR(B6)));B7*0,65*0,4*12;0;0);1);-4))`

**Comment by pphod** [comment]
Your formula has erros. 

In numbers decimal should: '.' you are using: ','
The formula arguments should: ',' you are using ';'

I have not checked any further problems. From what I have seem on FV implementation, it seems require 3 arguments.

https://exceljet.net/excel-functions/excel-fv-function

Good luck with your implementation. Next time, be polite and don't insult people we are all developers trying to do our work the best we can.

Regards,

**Comment by CodeCurosity** [comment]
i already tried and nothing works, maybe next time you help your potential customers rather than pushing ur subscription down their throat.
